src/compat-endian.h

Allows the building of timescaledb under FreeBSD 11.

Adding #elif defined(__FreeBSD__)

---

sql/main/ddl.sql
sql/main/ddl_triggers.sql
sql/main/ddl_util.sql
src/errors.h
test/expected/alternate_users.out
test/expected/ddl.out
test/expected/ddl_single.out
test/sql/alternate_users.sql
test/sql/ddl_single.sql
test/sql/include/ddl_ops_1.sql

This PR adds more regression tests for index creation and tests for more
user-errors. Significantly, it checks for the presence of both the time
and spaced-partition columns in unique indexes. This is needed because
Timescale cannot guarantee uniqueness if colliding rows don't land in the
same chunk.

Add better error checking for index creation.

---

src/planner.c
test/expected/insert_single.out
test/sql/insert_single.sql

Previously, INSERT INTO...SELECT FROM hypertable was broken. This was
caused by incorrectly tracking the commandType in change_name_walker.
Fixes #24.

Fix bug with INSERT INTO...SELECT

---

Makefile
src/executor.c
src/executor.h
src/init.c
src/insert.c

Previously, an INSERT on a hypertable would always return
INSERT 0 0 as the command tag. This makes it return the proper
number of items inserted for the second number. Fixes #28.

Fixes command tag return for INSERTS on hypertables.

---

Makefile
sql/common/ddl_utils.sql
sql/load_order.txt
sql/main/ddl_triggers.sql
src/ddl_utils.c
test/expected/alternate_users.out
test/expected/ddl.out
test/expected/ddl_single.out
test/sql/include/ddl_ops_1.sql
test/sql/include/ddl_ops_2.sql

Previously, an ALTER TABLE ADD COLUMN IF NOT EXISTS on a hypertable
caused an error if the column already did exist. The reversed problem
with DROP COLUMN is also fixed. Resolves issue #42.

Fix bug with alter table add/drop column if exists

---

src/cache_invalidate.c

This fixes a superfluous error that happened during cache invalidation.

Fix Invalid database ID error

---

src/executor.c
src/executor.h
src/process_utility.c
test/expected/alternate_users.out
test/expected/insert_single.out
test/expected/update.out
test/sql/include/insert_single.sql

Previously, COPY on hypertables always returned 'COPY 0' in the
command tag. Now, returns the correct count. Fixes #40.

Fixes command tag return for COPY on hypertables.

---

Makefile

Old versions of the extension sql files could hang around
bloating package sizes if not caught.

Cleanup sql/timescaledb--*.sql files on `make clean`

---

src/hypertable_cache.c
src/planner.c
src/utils.c
src/utils.h
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/expected/sql_query_results_x_diff.out
test/sql/include/sql_query_results.sql
test/sql/sql_query_results_unoptimized.sql

This PR disables query optimizations on regular tables by default.
The option timescaledb.optimize_plain_tables = 'on' enables them
again. timescaledb.disable_optimizations = 'on' disables all
optimizations (note the change from 'true' to 'on').

Disable query optimization on regular tables (non-hypertables)

---

sql/main/ddl.sql
sql/main/ddl_util.sql
sql/main/tables.sql
test/expected/alternate_users.out
test/expected/ddl.out
test/expected/ddl_single.out
test/expected/drop_chunks.out
test/expected/drop_rename_hypertable.out
test/expected/insert.out
test/expected/insert_single.out
test/expected/sql_query.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/expected/tablespace.out
test/sql/drop_chunks.sql
test/sql/include/ddl_ops_1.sql
test/sql/include/sql_query_results.sql

Changed create_hypertable to add time DESC and partitioning_column, time DESC
indexes by default (the latter only if partitioning column not null).
Indexes only created if there is no index on time and
partitioning_column, time respectively. Index creation can be turned off
with the create_default_indexes parameter to create_hypertable (default true).

Add default indexes for hypertables

---

src/catalog.h
src/hypertable_cache.c
src/hypertable_cache.h

This change makes the naming of the time interval field in
the hypertable cache entry consistent with the table schema.

Fix time interval field name in hypertable cache entry

---

sql/main/ddl.sql
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

Previously create_hypertable() would throw an error when called on
an already existing hypertable. This can now be skipped by setting
if_not_exists argument to true.

Add if_not_exists flag to create_hypertable()

---

src/guc.c
src/guc.h
src/init.c

Can't use a GUC variable before extension is loaded.

Fix bug with timescaledb.allow_install_without_preload GUC not working

---

src/partitioning.c
test/expected/drop_hypertable.out
test/sql/drop_hypertable.sql

This fixes a bug that caused the wrong column to be referenced when
scanning the partition_epoch table. The bug did not usually manifest
itself because the referenced (hypertable) ID was typically
incremented in unison with the desired (partition epoch) ID.

Reference the correct column when scanning partition epochs

---

.gitignore
Makefile
docker.mk
test/postgresql.conf
test/runner.sh

Tests are now run on a temporary Postgres instance, which is launched
by the `pg_regress` test runner. This allows running tests without
having an existing running instance with a matching configuration and
also obviates the need for preloading the TimescaleDB extension. As a
result, tests are simpler to setup and run, and are more reliable and
consistent.

Run tests on temp Postgres instance

---

.travis.yml

Tests are now run on Travis using a plain PostgreSQL Docker image,
requiring no Docker build step or other dependencies on the host. The source
directory is mounted into the running image and the build and test
steps are run in the container via `docker exec`. This simplifies the
build process, obviates the need fo building a new test Docker image,
and uses Postgres tools (such as psql and pgdump) from the image for
consistency.

Run Travis tests in Docker without building image

---

src/partitioning.c
test/expected/insert.out
test/sql/insert.sql

Padded fields such as character(20) did not work correctly before
because of differences between type output and coercion/casting.

Fix problems with partitioning logic for padded fields

---

.travis.yml
Dockerfile
test/expected/timestamp.out
test/sql/timestamp.sql

The timestamp test broke with Postgres 9.6.3, because that version
contained an accuracy fix for the `to_timestamp()` function, giving
slightly different results for some timestamp values. This fixes the
timestamp test to expect the correct `to_timestamp()` output as of
version 9.6.3 of Postgres.

Fix timestamp test

---

src/executor.c
src/executor.h
src/process_utility.c
test/expected/alternate_users.out
test/expected/copy_from.out
test/expected/delete.out
test/expected/drop_rename_hypertable.out
test/expected/insert.out
test/expected/insert_single.out
test/expected/pg_dump.out
test/expected/sql_query.out
test/sql/include/insert_two_partitions.sql
test/sql/insert.sql

Previously the count returned by insert and copy was wrong because
the count was reset on every execute. But, often there is an execute
in the middle of an insert (i.e. to create a chunk). This fixes the
logic to reset the count only at the start of the top-level statement.

Fix command-tag for COPY and INSERT

---

sql/ddl_internal.sql
test/expected/alternate_users.out
test/expected/ddl.out
test/expected/ddl_single.out
test/sql/include/ddl_ops_1.sql

Previously there was a bug causing indexes for partition, time to
be created twice.  This fixes #77.

Fix default index creation duplication of indexes

---

sql/chunk.sql
test/expected/create_chunks.out
test/sql/create_chunks.sql

Previously, chunks could end up unaligned betweeen partitions if the chunk_time_interval
was updated between chunk creations. Now there is a check when a chunk is created whether there is
a chunk matching the time point in another partition and if there is, the new chunk is created
with the same interval.

Ensure that chunks are aligned.

---

src/cache.c

Previously cache_destroy NULLed out memory in a MemoryContext that it
just deleted. This could cause a segfault and is fixed by this PR.

Fix possible segfault

---

src/dimension_slice.c
src/dimension_slice.h
src/subspace_store.c
src/subspace_store.h

This PR imposes a limit on the growth of the SubspaceStore size by
allowing only one slice to be present for the first dimension at a time.

Limit the SubspaceStore size; Add documentation.

---

sql/cache.sql
src/cache.c
src/cache_invalidate.c
src/extension.c
src/extension.h
test/expected/drop_extension.out
test/expected/pg_dump.out
test/sql/drop_extension.sql

Previously, the extension could end up in a bad state if it
was dropped as part of a cascade. This PR fixes that by
checking explicitly for the presence of the proxy table
to make sure we are not in the middle of an extension
drop. Fixes #73.

Fix extension drop handling

---

sql/ddl_api.sql
sql/ddl_internal.sql
sql/tables.sql
test/expected/create_hypertable.out
test/expected/ddl_errors.out
test/expected/extension.out
test/expected/insert_single.out
test/expected/pg_dump.out
test/sql/create_hypertable.sql
test/sql/insert_single.sql

A new public-facing API `add_dimension(table, column, ...)`
makes it possible to add additional dimensions (partitioning
columns) to a hypertable.
The code has also been refactored with a corresponding
internal function that is called by both `add_dimension()`
and `create_hypertable()`.

Provide API for adding hypertable dimensions

---

src/chunk_constraint.c
src/dimension_slice.c

Remove the following unused functions in order to quench compiler
warnings:
- chunk_constraint_from_form_data()
- chunk_constraint_from_tuple()
- hypercube_free()

Remove unused functions

---

sql/chunk.sql
test/expected/create_chunks.out
test/sql/create_chunks.sql

It is not an error for range_end of a new chunk to be equal to
range_start of an existing chunk because range_end is exclusive.
Fix logic not to throw an error in that case.

Fix off-by-one error when creating aligned chunks

---

Makefile
sql/load_order.txt
sql/version.sql
src/version.c
test/expected/pg_dump.out
test/expected/version.out
test/sql/version.sql

I found this useful when I compared different branches etc. to make sure what is running. Getting the git version from a shell command won't work when we build it in Docker but then I build with something like
```
docker build . -t timescaledb --build-arg EXT_VERSION_STRING=$(git describe --abbrev=4 --dirty --always --tags)
```

Add function to get git version of code base.

---

.travis.yml
Makefile
scripts/docker-build.sh
scripts/test_updates.sh
sql/updates/0.1.0--0.1.1-dev.sql
sql/updates/README.md
sql/updates/post-0.1.0--0.1.1-dev.sql
sql/updates/pre-0.1.0--0.1.1-dev.sql
test/sql/updates/test-0.1.1.sql

Also includes some update infrastructure changes. Main difference
is that sql/updates/ scripts are now split into pre- and post- files.
This is needed because table updates need to happen before reloading
functions (some functions checked for accessing right schema at
definition time). Meanwhile trigger updates need to happen after
since triggers must refer to valid functions at definition time.

Add update script for PR #121

---

Makefile

Previous syntax was not working on Ubuntu but fine on OSX. I've
tested this one both.

Fix sed syntax for getting extension version.

---

src/chunk_dispatch.c
src/chunk_dispatch.h
src/chunk_dispatch_plan.c
src/chunk_dispatch_plan.h
src/chunk_dispatch_state.c
src/chunk_dispatch_state.h
src/chunk_insert_state.c
src/chunk_insert_state.h
src/copy.c
src/planner.c
test/expected/upsert.out
test/sql/upsert.sql

Upserts are now supported as long as there is a unique index that
includes all hypertable dimensions. Upserts using ON CONFLICT ON
CONSTRAINT statements are currently unsupported, although this should
be possible in the future.

Add support for upserts (ON CONFLICT DO UPDATE)

---

Makefile
scripts/test_updates.sh

Get rid of dependencies on a local psql and stop mounting data volumes.

Reduce local non-docker dependencies for update tests

---

Makefile
src/chunk_dispatch.h
src/chunk_dispatch_info.c
src/chunk_dispatch_info.h
src/chunk_dispatch_plan.c
src/chunk_dispatch_plan.h
src/chunk_dispatch_state.c
src/chunk_dispatch_state.h
src/chunk_insert_state.c
src/hypertable_insert.c
src/hypertable_insert.h
src/init.c
src/planner.c
src/planner_utils.c
src/planner_utils.h
src/process_utility.c
test/expected/insert_single.out
test/sql/insert_single.sql

This fixes an issue that caused EXPLAIN and PREPAREd statements to
fail on INSERTs. The plan modification on INSERTs passed on a plan
node to the execution stage. However, that plan node pointer becomes
invalid when the plan is copied, as happens with prepared statements
or EXPLAINs. The fix required another modification to the plan by
wrapping also the ModifyTable plan node. This wrapping is necessary to
access the plan state node (ModifyTableState) on execution. Having
access to the ModifyTableState node is necessary to set the correct
arbiter index list for ON CONFLICT statements.
This change also fixes the output of EXPLAIN to properly show the plan
tree, and performs some cleanups.

Fix EXPLAIN and PREPAREd statements on INSERTs

---

src/cache.c
src/cache.h
src/init.c

Currently, if a transaction ends (normally or abnormally) while a
cache is pinned, that cache will never be released, leading to a
memory leak. This change ensures that all taken cache pins are
released when a transaction ends by registering all pins in a list and
cleaning it up in a transaction end callback. This makes the use of
cache_release() optional. However, timely calls to cache_release() is
still encouraged since it is better to release memory as soon as
possible during long-running transactions.

Release all cache pins when a transaction ends

---

src/hypertable.c
src/hypertable.h
src/hypertable_cache.c
src/process_utility.c
test/expected/reindex.out
test/expected/upsert.out
test/expected/vacuum.out
test/sql/reindex.sql
test/sql/upsert.sql
test/sql/vacuum.sql

Previously, when issued on hypertable, database maintenance
commands, like VACUUM and REINDEX, only affected the main
table and did not recurse to chunks.
This change fixes that issue, allowing database maintainers
to issue single commands on hypertables that affect all
the data stored in the hypertable.
These commands (VACUUM, REINDEX) only work at the table level
for hypertables. If issued at other levels, e.g., schema, or
database, the behavior is the same as in standard PostgreSQL
as all tables are covered by default.
REINDEX commands that specify a hypertable index do not
recurse as that requires mapping the hypertable
index to the corresponding index on the chunk. This might
be fixed in a future update.

Make VACUUM and REINDEX recurse to chunks

---

src/chunk_insert_state.c
src/copy.c
src/hypertable.c

This change ensures that the per-tuple exprcontext (on which per-tuple
state is allocated), is reset for every new tuple processed in a
long-running COPY transaction.

Reduce memory usage on long-running COPY operations

---

sql/ddl_api.sql
sql/ddl_internal.sql
test/expected/alternate_users.out
test/expected/copy_from.out
test/expected/create_hypertable.out
test/expected/ddl.out
test/expected/ddl_errors.out
test/expected/ddl_single.out
test/expected/delete.out
test/expected/drop_rename_hypertable.out
test/expected/insert.out
test/expected/insert_single.out
test/expected/pg_dump.out
test/expected/size_utils.out
test/expected/sql_query.out
test/expected/truncate_hypertable.out
test/expected/update.out
test/sql/create_hypertable.sql
test/sql/ddl_errors.sql
test/sql/include/ddl_ops_1.sql
test/sql/include/insert_single.sql
test/sql/include/insert_two_partitions.sql
test/sql/insert_single.sql
test/sql/updates/setup.sql

Previously the default chunk time in microseconds was too large
for an INTEGER field. If a user is using integer, they are using
seconds (since both milli and microsecond overflow), so now we
convert the default to the appropriate number in seconds.
Further, we check to make sure the chunk time interval is not too
large for INTEGER so as to avoid confusing problems later when the
user goes to insert.
Address issue #150

Improve handling of INTEGER timestamps

---

.gitignore
test/runner.sh

On my machine (OSX 10.10) `mktemp -d` prints out the usage message
and doesn't create a temporary directory.

Add -t flag to test/runner.sh's mktemp call

---

sql/chunk.sql
sql/tables.sql
sql/updates/pre-0.3.0--0.3.1-dev.sql
test/expected/insert_single.out
test/sql/insert_single.sql

Previously dimension_slice would only allow ranges to start and
end with values >= 0. However, this did not allow for timestamps
prior to 1970 because those times would be represented by negative
integers. With this PR we now support dates prior to 1970.
Addresses issue #153.

Add support for negative values in dimension range

---

test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/sql/include/append.sql

One of the append tests accidentally used the PostgreSQL now()
function instead of a mocked now_s() function. This caused
tests to eventually fail. This change corrects that mistake.

Fix append tests

---

sql/time_bucket.sql
src/utils.c
test/expected/pg_dump.out
test/expected/timestamp.out
test/sql/timestamp.sql

Previously, date was auto-cast to timestamptz when time_bucket was
called. This led to weird behavior with regards to timezones and
the return value was a timestamptz. This PR makes time_bucket return
a DATE on DATE input and avoids all timezone conversions.

Fix semantics of time_bucket on DATE input

---

sql/chunk.sql
test/expected/chunks.out
test/expected/insert_single.out
test/expected/pg_dump.out
test/sql/chunks.sql
test/sql/include/test_utils.sql
test/sql/insert_single.sql

Previously, negative dimension values had an off-by-one bug where the
wrong chunk was created for points on chunk borders. This PR fixes that.

Fix bug with negative dimension values

---

src/constraint_aware_append.c
src/constraint_aware_append.h
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/sql/include/append.sql

This change fixes a bug that occurs when a constraint-aware append
plan excludes all chunks at execution time. Append nodes do not handle
the case when all subplans are pruned and the append node's subplan
list is empty. To avoid a failure in that case, the constraint-aware
plan node will shortcut the execution of the query and never call the
append node.

Fix failure when constraint-aware append excludes all chunks

---

src/planner.c
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_x_diff.out

Previously, the planner had a global context that kept a reference to
the hypertable cache. The reference counting system in that global
context was unsafe and could lead to a segfault. This PR gets rid
of that context and makes the whole system a lot safer.
Fixes #184

Fix possible segfault in planner

---

scripts/ts_dump.sh
scripts/ts_restore.sh
sql/util_internal_table_ddl.sql
test/expected/create_hypertable.out
test/expected/pg_dump.out
test/sql/create_hypertable.sql

Using pg_dump/pg_restore for a database with hypertables will back
up all internal tables too, which is sometimes not desired. These
scripts allow one to backup regular PostgreSQL tables separately
and then pick and choose which hypertables to backup and restore.
This also provides a forward-compatible way of backing up and
restoring hypertables, since data is dumped to CSV and restored
by re-creating and re-inserting the data.

Add backup/restore scripts for single hypertables

---

src/process_utility.c
test/expected/relocate_extension.out
test/sql/relocate_extension.sql
timescaledb.control

Unfortunately, Postgres forbids relocating the "public api" schema
of extensions that use multiple schemas after initial installation.
This PR marks the extension as not relocatable and tests relocation
during initial install.

Forbid relocating extension after install.

---

src/chunk.c
src/chunk_constraint.c
src/dimension.c
src/dimension_slice.c
src/scanner.c
src/scanner.h

This adds an option to set a limit on how many tuples to return in a
relation scan using the scanner implemention. This avoids a common
pattern of manually implementing limits in the tuple handling
function.

Add limit option to scanner

---

src/process_utility.c
test/expected/constraint.out
test/sql/constraint.sql

Adding a constraint using an existing index changes the existing
index's name as a side effect (PostgreSQL wants the index name to
match the constraint name). This creates a mismatch between the
index's name and our metadata in the chunk_index table. Further, since
the name change happens as a result of an internal command (and not
via DDL command that we can capture) there is currently no way to sync
up this information.

Block adding constraints using an existing index

---

sql/size_utils.sql
sql/updates/pre-0.4.2--0.5.0-dev.sql
test/expected/extension.out
test/expected/pg_dump.out
test/expected/size_utils.out
test/sql/size_utils.sql

The hypertable, chunk, and index size functions are
now split into main function and a corresponding ´pretty´
function. In chunk_relation_size_pretty() the ranges are
now converted into a human readable form.

Improve the size utils functions.

---

src/guc.h
src/process_utility.c
test/expected/pg_dump.out
test/sql/pg_dump.sql

During a database restore, the creation of triggers and constraints on
hypertables should not recurse to chunks since the chunks will be
restored with existing triggers and constraints. Failing to block
recursing during restore risks duplicating these objects on chunks.
Further, operations on chunks (e.g., ALTER TABLE) should be allowed
during the restore process since those operations are needed to
recreate the constraints and triggers.
To fix this, the "restoring" GUC is used to bypass custom handling of
events in the ProcessUtility hook.

Fix dump and restore for tables with triggers and constraints

---

src/process_utility.c
test/expected/constraint.out
test/sql/constraint.sql

The current approach of handling alter table commands does not allow
getting the result of the command; for instance, the object address of
a created constraint on a hypertable. Thus there is no way to get the
auto-generated name of a constraint, which is needed when the
corresponding constraints are created on the hypertable's chunks.
Therefore, this change blocks the ability to create constraints
without an explicit name. When a better approach to handling alter
table is deviced, it is possible to remove this restriction.

Block adding constraints without a constraint name

---

src/agg_bookend.c
test/expected/agg_bookends.out
test/sql/agg_bookends.sql

There are 2 separate fixes:
1) Fix for NULL value handling when values are numeric types.
This fixes #209. Thanks to @raycheung for reporting this bug.
2) Correct handling for NULLs in compare/ordering elements.
The functions will now always return NULL if any comparison element
in group was NULL.

Fix NULL handling in first/last functions.

---

Makefile
sql/ddl_triggers.sql
src/event_trigger.c
src/event_trigger.h
src/hypertable.c
src/init.c
src/process_utility.c
test/expected/constraint.out
test/expected/pg_dump.out
test/sql/constraint.sql

The ProcessUtility hook doesn't give any information on applied DDL
commands, which makes it hard to implement DDL processing that
requires the result of a DDL command on a hypertable (for instance,
adding a constraint or index without an explicit name).
This change splits the DDL processing over start and end hooks,
handling DDL commands before and after regular PostgreSQL processing,
respectively.
The start DDL hook is still based on the ProcessUtility hook, while
the end DDL hook is based on an event trigger that allows getting
information on the created/dropped/altered objects.

Split DDL processing into start and end hooks

---

scripts/docker-build.sh

- Save an intermediate build image to avoid having to download APK
packages for every build
- Add debug symbols and assertions to extension build
- Install git and gdb by default for easier debugging

Tweak the docker image build script

---

src/process_utility.c
test/expected/create_table.out
test/sql/create_table.sql

Constraints on regular PostgreSQL tables need to be validatated so
that they don't have a foreign key constraint that references a
hypertable, as this is not yet supported. This change fixes a bug in
this validation caused by not checking for the proper node types when
parsing a CreateStmt node. The CreateStmt is now also parsed in the
DDL end hook, instead of the processUtility hook, which ensures that
the CreateStmt node has been run through parse analysis. The parse
analysis changes the contents of the node to be more consistent across
different CREATE statements. For instance, a CREATE LIKE statement
will look more similar to a regular CREATE statement after parse
analysis.

Fix constraint validation on regular tables

---

src/agg_bookend.c
src/cache.h
src/cache_invalidate.c
src/chunk.h
src/chunk_constraint.h
src/compat.c
src/dimension.c
src/dimension.h
src/dimension_vector.h
src/event_trigger.c
src/extension.c
src/histogram.c
src/hypercube.h
src/partitioning.c
src/scanner.c
src/utils.c
src/utils.h
src/version.c

For all exported functions the macro PGDLLEXPORT needs to be pre-
pended. Additionally, on Windows `open` is a macro that needed to
be renamed. A few other small changes are done to make Visual
Studio's compiler happy / get rid of warnings (e.g. adding return
statements after elog.

Prepare C code for compiling on Windows

---

src/chunk_dispatch_plan.c
src/chunk_dispatch_plan.h
src/planner.c
test/expected/insert.out
test/sql/insert.sql

When inserting into a hypertable using a sub-select clause that
involves an aggregate, the insert fails with the error "Aggref found
in non-Agg plan node". This happens because the target list from the
aggregate sub-select expects an aggregate parent node and we simply
reuse the target list when modifying the insert plan with new
CustomScan plan nodes.
This change creates a modified target list to use with the CustomScan
node that avoids this issue.

Fix INSERT on hypertables using sub-selects with aggregates

---

src/cache_invalidate.c
src/compat.c
src/dimension.c
src/partitioning.c

Files that have been modified with the PGDLLEXPORT macro
are no longer pgindent formatted. This change fixes these
pgindent issues.

Fix pgindent issues due to windows-related changes

---

src/planner.c

In the planner hook, we erroneously blocked "ON CONFLICT ON
CONSTRAINT" statements on plain tables. This fixes the issue
so that this error only occurs on hypertables.

Fix "ON CONFLICT ON CONSTRAINT" on plain PostgreSQL tables

---

src/catalog.c
src/chunk.c
src/dimension_slice.c
src/extension.c
src/histogram.c
src/partitioning.c
src/version.c

These changes will fix a number of warnings generated by some
compilers and platforms (most notably on Windows) that mostly relate
to assigning values to variables with mismatching types.
A number of datum functions were also called without actually passing
datums or assigning return values to datums. Those are now passed
datums instead of raw data types.

Quench a number of type mismatch warnings

---

src/process_utility.c

A previous commit mixed declarations and code, which causes
warnings on some compilers. This change quenches the warning
and fixes some indentation/formatting issues.

Fix mixed declaration and code warning and indentation

---

src/extension.c
src/process_utility.c

Extension_new_state() was sometimes using the pg cache before it
was fully initialized. This commit adds a check to make sure that
does not happen.

Fix bug with extension starting too early.

---

src/copy.c

- Remove definition of the previous chunk insert state as it does not change from NULL (is reassigned to null in loop)

Remove previous CIS definition from file copy procedure

---

src/chunk_insert_state.c
src/chunk_insert_state.h

By default, Postgres places constraint expressions on the query memory
context. However, these expressions only apply to individual chunks
and cannot be re-used across chunks. Placing them on the
chunk_insert_state context (created as part of this PR) allow these
expressions to be freed along with the insert state of individual
chunks.

Fix memory leak due to constraint expressions.

---

src/chunk_constraint.c
src/chunk_index.c
test/expected/index.out
test/sql/index.sql

When creating an index on a chunk based on a index on a hypertable, it
is necessary to adjust the attribute numbers of referenced columns in
case the hypertable and the chunk have different number of attributes
(this can happen, e.g., due to removing columns on the hypertable that
aren't inherited by a newly created chunk). This adjustment was
handled for regular indexes, but not expression indexes, causing an
error to be raised. This change adds the proper handling of expression
indexes.

Fix issue with creating expression indexes

---

src/process_utility.c
test/expected/plain.out
test/sql/plain.sql

A recent change blocked changing types of space-partitioned hypertable
columns. However, this blocking should not apply to regular tables,
which otherwise causes a crash. This change fixes this issue by
properly checking that the the table is a hypertable.

Fix column type change on plain tables

---

sql/ddl_api.sql
sql/ddl_internal.sql
sql/updates/pre-0.6.0--0.7.0-dev.sql
test/expected/partitioning.out
test/sql/partitioning.sql

Users might want to implement their own partitioning function
or use the legacy one included with TimescaleDB. This change
adds support for setting the partitioning function in
create_hypertable() and add_dimension().

Allow setting partitioning function

---

src/chunk_insert_state.c
src/chunk_insert_state.h
src/subspace_store.c

This PR comprises three commits that optimize or fix bugs in the chunk insert state code.
1. Limit the size of the range table on INSERT
2. Do not convert tuples to chunk format unless needed
3. Fix assertions in subspace store

Chunk insert state optimizations

---

src/chunk.c
src/chunk.h
src/chunk_insert_state.c
src/chunk_insert_state.h
src/hypercube.c
src/hypercube.h
src/hypertable.c

The chunk cache needs to free chunk memory as
it evicts chunks from the cache. This was previously
done by pfree:ing the chunk memory, but this didn't
account for sub-allocated objects, like the chunk's
hypercube. This lead to some chunk objects remaining
in the cache's memory context, thus inflating memory
usage, although the objects were no longer associated
with a chunk.
This change adds a per-chunk memory context in the cache
that allows all chunk memory to be easily freed when
the cache entry is evicted or when the chunk cache
is destroyed.

Use per-chunk memory context for cached chunks

---

src/constraint_aware_append.c
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_x_diff.out
test/sql/include/append.sql

This fixes a bug with an explain for ConstraintAware plans
when all chunks were excluded and a MergeAppend was used.
The problem was that the EXPLAIN output for MergeAppend nodes
expected at least one child to print the sorting column info.
When all chunks were excluded there are no children. This
PR removes all child execution states from the ConstraintAware
node when all chunks are excluded.

Fix EXPLAIN for ConstraintAware and MergeAppend

---

sql/partitioning.sql
sql/updates/post-0.6.1--0.7.0-dev.sql
sql/util_internal_table_ddl.sql
src/parse_rewrite.c
src/partitioning.c
src/process_utility.c
test/expected/drop_chunks.out
test/expected/hash.out
test/expected/partitioning.out
test/sql/drop_chunks.sql
test/sql/hash.sql
test/sql/util.sql

All partitioning functions now has the signature `int func(anyelement)`.
This cleans up some special handling that was necessary to support
the legacy partitioning function that expected text input.

Make all partitioning functions take anyelement argument

---

src/utils.c
test/expected/insert_single.out
test/sql/insert_single.sql

The insert logic in time_value_to_internal was not tz independent,
causing problems with date in some timezones. This is now fixed.
Fixes #306.

Change DATE partitioning to be completely tz-independent

---

.travis.yml
CMakeLists.txt
sql/bookend.sql
sql/ddl_internal.sql
sql/ddl_triggers.sql
sql/histogram.sql
sql/partitioning.sql
sql/util_internal_table_ddl.sql
sql/util_time.sql
sql/version.sql
test/CMakeLists.txt
test/pgtest/CMakeLists.txt
test/pgtest/README.md

This PR comprises three commits. The main change/commit enables running PostgreSQL's standard regression test suite and is based on @olofr's earlier PR. However, this PR contains some cleanups and test fixes not in the earlier PR. The other two commits fix failures in some of the tests by:
- Making serialize/deserialize functions `STRICT`
- Marking `IMMUTABLE` functions as `PARALLEL SAFE`
- Removing the `IMMUTABLE` label on some functions that aren't immutable
Two tests in the PG test suite still fails. One fails because our metadata tables show up in the test. The other fails on PG10 due to some of our functions being marked with `SECURITY DEFINER`, which none of the PostgreSQL functions are (the PostgreSQL test checks for empty result when querying for such functions). The failing …

Run standard PostgreSQL tests with TimescaleDB loaded

---

scripts/test_updates.sh
sql/updates/post-0.6.1--0.7.0-dev.sql
sql/util_time.sql
src/utils.c
test/expected/ddl_alter_column.out
test/expected/insert_single.out
test/expected/reindex.out
test/expected/vacuum.out
test/sql/ddl_alter_column.sql
test/sql/insert_single.sql
test/sql/updates/setup.sql
test/sql/vacuum.sql

Previously, for timezones w/o tz. The range_end and range_start were
defined as UTC, but the constraints on the table were written as as
the local time at the time of chunk creation. This does not work well
if timezones change over the life of the hypertable.
This change removes the dependency on local time for all timestamp
partitioning. Namely, the range_start and range_end remain as UTC
but the constraints are now always written in UTC too. Since old
constraints correctly describe the data currently in the chunks, the
update script to handle this change changes range_start and range_end
instead of the constraints.
Fixes #300.

Change TIMESTAMP partitioning to be completely tz-independent

---

src/chunk_index.c
src/chunk_index.h
src/process_utility.c
test/expected/cluster.out
test/sql/CMakeLists.txt
test/sql/cluster.sql

Clustering a table means reordering it according to an index.
This operation requires an exclusive lock and extensive
processing time. On large hypertables with many chunks, CLUSTER
risks blocking a lot of operations by holding locks for a long time.
This is alleviated by processing each chunk in a new transaction,
ensuring locks are only held on one chunk at a time.

Recurse CLUSTER command to chunks

---

sql/ddl_internal.sql
sql/util_time.sql
src/chunk.c
src/chunk.h
src/chunk_index.c
src/chunk_index.h
src/hypertable.c
src/scanner.c
src/scanner.h
src/utils.c
test/expected/pg_dump.out
test/expected/reindex.out
test/sql/reindex.sql

reindex_chunk allows you to reindex the indexes of only certain chunks,
filtering by time. This is a common use case because a user may
want to reindex chunks after they are no longer getting new data once.
reindex_create also has a recreate option which will not use REINDEX
but will rather CREATE INDEX a new index and then
DROP INDEX / RENAME new_index to old_name. This approach has advantages
in terms of blocking reads for a much shorter period of time. However,
it does more work and will use more disk space during the operation.

Add reindex_chunk function

---

CMakeLists.txt

This changes the order in which subdirectories are processed in the
top-level CMakeLists.txt file, so that dependencies from the scripts/
dir are set when processing the src/ dir. Otherwise, the `pgindent`
target won't be enabled on the first CMake run.

Fix pgindent on first CMake run

---

test/expected/reindex.out
test/sql/reindex.sql

The reindex test outputs the OID of a cloned index. This OID might
change with the state of the database, added tests, etc., causing
frequent test failures. The test is now updated to output the name of
the index instead of the OID.

Fix reindex test

---

src/constraint_aware_append.c
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/sql/include/append.sql

Append plans that are empty (no children) are replaced at planning-
time with a Result plan node that returns nothing. Such Result nodes
occur typically when querying outside the time range covered by chunks.
However, the ConstraintAwareAppend plan node did not handle the
case of a Result child node, instead expecting either an Append or
MergeAppend node. This is now fixed so that encountering a Result node
means doing nothing.
Fixes https://github.com/timescale/timescaledb/issues/294

Handle empty append plans in ConstraintAwareAppend

---

sql/cache.sql
sql/cache_functions.sql
sql/updates/pre-0.7.0--0.8.0-dev.sql
src/cache_invalidate.c
src/catalog.c
src/catalog.h
src/hypertable_cache.c

TimescaleDB cache invalidation happens as a side effect of doing a
full SQL statement (INSERT/UPDATE/DELETE) on a catalog table (via
table triggers). However, triggers aren't invoked when using
PostgreSQL's internal catalog API for updates, since PostgreSQL's
catalog tables don't have triggers that require full statement
parsing, planning, and execution.
Since we are now using the regular PostgreSQL catalog update API for
some TimescaleDB catalog operations, we need to do cache invalidation
also on such operations.
This change adds cache invalidation when updating catalogs using the
internal (C) API and also makes the cache invalidation more fine
grained. For instance, caches are no longer invalidated on some
INSERTS that do not affect the validity of objects already in the
cache, such as …

Refactor and fix cache invalidation

---

src/planner.c
test/expected/delete.out
test/expected/update.out
test/sql/delete.sql
test/sql/update.sql

Plans that have a result relation set (DELETE or UPDATE) should
not optimize subplans that contain append nodes. This is because
the PostgreSQL must turn such plans on an inheritance table into
a set of similar plans on each subtable (i.e., it needs to apply
UPDATE and DELETE to each subtable and not just the parent).
Optimizing such plans with, e.g., ConstraintAwareAppend makes
the planner believe it only needs to do the DELETE or UPDATE
on the root table, which means rows in subtables won't be affected.
Fixes https://github.com/timescale/timescaledb/issues/301

Do not append-optimize plans with result relations (DELETE/UPDATE)

---

sql/ddl_api.sql
sql/ddl_internal.sql
sql/updates/pre-0.7.0--0.8.0-dev.sql
test/expected/drop_chunks.out
test/sql/drop_chunks.sql

This PR fixes the handling of drop_chunks when the hypertable's
time field is a TIMESTAMP or DATE field. Previously, such
hypertables needed drop_chunks to be given a timestamptz in UTC.
Now, drop_chunks can take a DATE or TIMESTAMP. Also, the INTERVAL
version of drop_chunks correctly handles these cases.
A consequence of this change is that drop_chunks cannot be called
on multiple tables (with table_name = NULL or schema_name = NULL)
if the tables have different time column types.

Change time handling in drop_chunks for TIMESTAMP times

---

test/CMakeLists.txt

Remove user from regression tests so that the local test will work.
The tests itself will still be run with the appropriate user because
of the logic in runner.sh.

Fix installchecklocal

---

test/expected/insert_single.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/sql/include/sql_query_results.sql
test/sql/insert_single.sql

When testing on Windows these tests were returning differences
because of floating point (sql_query_results_*) differences and
because the cost was trivially higher (insert_single). Here we
remove the costs since it was not relevant to the regressions we
want to detect. Further we truncate the floating point averages
to 8 decimal places; enough to see significant differences.

Modify tests to make more platform agnostic

---

bootstrap

Users can now either force the removal of an existing BUILD_DIR
by passing BUILD_FORCE_REMOVE to ./bootstrap, or they will be
prompted to remove the dir if it already exists. Additionally, the
bootstrap script will now exit if there is an error in mkdir or
cmake.
Addresses https://github.com/timescale/timescaledb/issues/349

Improve bootstrap script's robustness 

---

src/chunk_insert_state.c

The chunk_result_relation_info should be put on the chunk memory
context. This will cause the rri constraint expr to also go onto
that context and be correctly freed when the chunk insert state
is destroyed.

Reduce memory usage for out-of-order inserts

---

src/copy.c
test/expected/copy.out
test/sql/CMakeLists.txt
test/sql/copy.sql
test/sql/copy_from.sql

Previously trigger relcache entries were not always freed during
COPY commands in PG10. This PR fixes that.
Fixes #351.

Fix trigger relcache handling for COPY 

---

src/process_utility.c
test/expected/partitioning-10.out
test/expected/partitioning-9.6.out
test/sql/.gitignore
test/sql/CMakeLists.txt
test/sql/partitioning.sql.in

Hey guys!
This PR will serve to raise an exception upon an attach partition event on a hypertable to a native postgres partition

Prevent native partitioning attachment of hypertables

---

sql/chunk_constraint.sql
sql/util_internal_table_ddl.sql
src/dimension.c
test/expected/insert.out
test/sql/chunks.sql
test/sql/insert.sql

This PR fixes handling of one space partition. It
avoids creating a CHECK constraint and also fixes the
logic in default dimension range creation.

Fix logic for one space partition

---

sql/ddl_api.sql
sql/ddl_internal.sql
src/extension.c
src/process_utility.c
test/expected/truncate_hypertable.out

Compatibility with pg_upgrade required 2 changes:
1) search_path on functions cannot be blank for pg_upgrade.
2) The timescaledb.restoring GUC had to apply to more code (now moved to
higher-level check)

Make TimescaleDB work with pg_upgrade

---

src/tablespace.c

Fixes a memory bug found by valgrind.

Make `tablespace_show` function return Name instead of CString

---

src/chunk.c
src/process_utility.c
test/expected/reloptions.out
test/sql/CMakeLists.txt
test/sql/reloptions.sql

When tables are created with storage parameters (reloptions),
these should be inherited by chunks so that one can set options
such as fillfactor and autovacuum settings on the hypertable.
This change makes chunks inherit the reloptions set on a hypertable
and allows altering options via the ALTER TABLE command.

Make chunks inherit reloptions set on the hypertable

---

bootstrap

Changing things like the location of pg_config and other macros,
additional cmake flags, etc require modifying bootstrap file. This
PR instead passes any flags given to bootstrap onto cmake itself.

Add support for passing flags to cmake

---

CMakeLists.txt
bootstrap.bat

Flags are now passed on to CMake, the source directory is correctly
resolved, and support for removing the old build directory added.
Additionally this will limit the VS solution file to only having
Release targets unless overriden with a flag.

Bring Windows bootstrap in line with Unix version.

---

src/CMakeLists.txt

This shows the current full version name instead of always 'nocommit'.

Support developer function for git commit in Docker

---

src/catalog.h
src/chunk_constraint.c
src/chunk_constraint.h
src/process_utility.c
test/expected/constraint.out
test/sql/constraint.sql

Renaming constraints on hypertables is now supported. Using the ONLY
option with RENAME CONSTRAINT is blocked for hypertables. Renaming
constraints on chunks is also blocked.
This commit also fixes a possible bug in chunk_constraint code.
Previously, `chunk_constraint_add_from_tuple` used GETSTRUCT on the
tuple to convert the tuple to `FormData_chunk_constraint`. This
was incorrect since some fields can be NULL. Using GETSTRUCT for
tables with NULLABLE fields is unsafe and indeed was incorrect·
in this case.

Add support for ALTER TABLE RENAME CONSTRAINT.

---

src/chunk_dispatch.c
src/dimension_vector.c
src/dimension_vector.h
src/guc.c
src/guc.h
src/hypertable.c
src/subspace_store.c
src/subspace_store.h
test/expected/insert_single.out
test/loader-mock/src/init.c
test/sql/insert_single.sql

Previously, the cache in chunk_dispatch was limited to only hold
the chunk_insert_state for the last time dimension as a consequence
of logic in subspace_store. This has now been relaxed so that a
chunk_dispatch holds the cache for any chunk_insert_states that it
encounters. Logic for the hypertable chunk cache has not been changed.
The rule that we should follow is to limit the subspace store size for
caches that survive across commands. But caches within commands can be
allowed to grow.

Improve speed of out-of-order inserts

---

src/cache.c
src/cache.h
src/cache_invalidate.c
src/process_utility.c
test/expected/insert_single.out
test/sql/insert_single.sql

This is a collection of 3 commits that fixes subtxn handling. It addresses #376. These commits reconsider all code that had RegisterXactCallback to add RegisterSubXactCallback.

Fix subtransaction handling

---

src/process_utility.c
test/expected/constraint.out
test/expected/ddl_alter_column.out
test/sql/constraint.sql
test/sql/ddl_alter_column.sql

ONLY does not make semantic sense for hypertables.
This commit blocks the use of this modifier.

Block ONLY hypertable on all ALTER TABLE commands.

---

src/chunk.c
src/chunk_index.c
src/hypertable.c
src/hypertable.h
test/expected/drop_chunks.out
test/expected/index.out
test/expected/reindex.out
test/expected/sql_query.out
test/expected/tablespace.out
test/expected/truncate_hypertable.out
test/sql/tablespace.sql
test/sql/utils/testsupport.sql

Currently, chunk indexes are always created in the tablespace of the
index on the main table (which could be none/default one), even if the
chunks themselves are created in different tablespaces. This is
problematic in a multi-disk setting where each disk is a separate
tablespace where chunks are placed. The chunk indexes might exhaust
the space on the common (often default tablespace) which might not
have a lot of disk space. This also prohibits the database, including
index storage to grow by adding new tablespaces.
Instead, chunk indexes are now created in the "next" tablespace after
that of their chunks to both spread indexes across tablespaces and
avoid colocating indexes with their chunks (for I/O throughput
reasons). To optionally avoid this spreading, one can pin chunk
indexes to …

Spread chunk indexes across tablespaces like chunks

---

src/constraint_aware_append.c

My Postgres server (10.1) with timescaledb (0.8) crashed with a segfault on queries like the following, where table_a is a regular table and timescale_table is a timescaledb hypertable:
`select count(*) from table_a i cross join lateral (select * from timescale_table g where g.a_id=i.id and updated_at > make_custom_timestamp(now()) order by updated_at desc limit 1) s where i.b=3;`
If there are no partitions to scan for the subquery (for example, in the case that there are no partitions for the specified timestamp), the Postgres planner figures out that it can exclude all existing partitions. During execution it does call this ca_append_rescan function with an empty list. ca_append_rescan tries to take the first element, which obviously fails.
There may be more occurrences in the …

Add check for null in ca_append_rescan to prevent segfault

---

sql/ddl_internal.sql
sql/tables.sql
sql/updates/pre-0.8.0--0.9.0-dev.sql
src/catalog.c
src/catalog.h
src/chunk.c
src/chunk.h
src/chunk_constraint.c
src/chunk_constraint.h
src/chunk_index.c
src/chunk_index.h
src/dimension.c
src/dimension.h
src/dimension_slice.c
src/dimension_slice.h
src/hypertable.c
src/hypertable.h
src/process_utility.c
src/tablespace.c
src/tablespace.h
test/expected/drop_chunks.out
test/expected/pg_dump.out
test/expected/tablespace.out
test/sql/drop_chunks.sql
test/sql/tablespace.sql

This is a multi-commit PR. 
Commit 1: Handle deletes on metadata objects via native catalog API
Handle deletes on metadata objects via native catalog API  …
Deletes on metadata in the TimescaleDB catalog has so far been a mix
of native deletes using the C-based catalog API and SQL-based DELETE
statements that CASCADEs.
This mixed environment is confusing, and SQL-based DELETEs do not
consistently clean up objects that are related to the deleted
metadata.
This change moves towards A C-based API for deletes that consistently
deletes also the dependent objects (such as indexes, tables and
constraints).  Ideally, we should prohobit direct manipulation of
catalog tables using SQL statements to avoid ending up in a bad state.
Once all catalog manipulations happend via the native API, we can …

 Handle deletes on metadata objects via native catalog API

---

CMakeLists.txt
src/dimension.c
src/hypertable.c
src/loader/loader.c
src/scanner.c
src/tablespace.c
src/tablespace.h

Previously stdint.h was not included on Windows so INT16_MAX and
friends were not defined. Additionally, having tablespace_attach
with PG_FUNCTION_ARGS in the header file caused issues during
linking, so a direct call version of the function is now exported
for others to use instead of the PG_FUNCTION_ARGS version.
Two minor warnings regarding not having a return in all cases are
also addressed.
Reported by RaedA on slack.

Fix several Windows compile errors and warnings

---

sql/ddl_internal.sql
sql/updates/pre-0.8.0--0.9.0-dev.sql
src/catalog.c
src/catalog.h
src/process_utility.c
test/expected/pg_dump.out

Changing the owner of a hypertable is now handled
entirely in the process utility hook without doing
an upcall to PL/pgSQL.

Handle change owner without upcall

---

sql/ddl_internal.sql
sql/updates/pre-0.8.0--0.9.0-dev.sql
src/catalog.c
src/catalog.h
src/process_utility.c
test/expected/pg_dump.out
test/expected/truncate.out
test/sql/CMakeLists.txt
test/sql/truncate.sql

This change refactors the handling of TRUNCATE so
that it is performed directly in process utility without
doing an upcall to PL/pgSQL.
It also adds handling for the ONLY modifier to TRUNCATE,
which shouldn't work on a hypertable. TRUNCATE now generates
an error if TRUNCATE ONLY is used on a hypertable.

Handle TRUNCATE without upcall and handle ONLY modifier

---

test/expected/triggers.out
test/sql/triggers.sql

This test adds a case where we use a trigger to automatically populate
a metadata table. This usage of triggers is described in our docs. This
commit makes sure that the code in our docs is tested.

Add test case for adding metadata entries automatically

---

src/chunk.c
src/chunk.h
src/hypertable.c
src/hypertable.h
src/process_utility.c
test/expected/drop_schema.out
test/sql/CMakeLists.txt
test/sql/drop_schema.sql

Dropping a schema that a hypertable depends on should clean up
dependent metadata. There are two schemas that matter for hypertables:
the hypertable's schema and the associated schema where chunks are
stored.
This change deals with the above as follows:
- If the hypertable schema is dropped, the hypertable and all chunks
should be deleted as well, including metadata.
- If an associated schema is dropped, the hypertables that use that
associated schema will have their associated schemas reset to the
internal schema.
- Even if no hypertable currently uses the dropped schema as their
associated schema, there might be chunks that reside in the dropped
schema (e.g., if the associated schema was changed for their
hypertables), so those chunks should have the metadata deleted.

Handle DROP SCHEMA for hypertable and chunk schemas

---

sql/ddl_api.sql
sql/updates/pre-0.8.0--0.9.0-dev.sql
src/hypertable.c
src/hypertable.h
src/process_utility.c
src/scanner.c
src/tablespace.c
src/tablespace.h
test/expected/alter.out
test/expected/alternate_users.out
test/expected/tablespace.out
test/sql/alter.sql
test/sql/tablespace.sql

This change improves the handling of tablespaces as follows:
- Add if_not_attached / if_attached options to attach_tablespace() and
detach_tablespace(), respectively
- Block DROP tablespace if it is still attached to a table
- Block REVOKE if it means the table owner no longer has CREATE
permissions on an attached tablespace
- Make error messages follow the PostgreSQL style guide

Improve tablespace handling, including blocks for DROP and REVOKE

---

sql/ddl_triggers.sql
sql/updates/post-0.8.0--0.9.0-dev.sql
src/catalog.c
src/catalog.h
src/chunk.c
src/chunk_constraint.c
src/chunk_constraint.h
src/chunk_index.c
src/chunk_index.h
src/compat.c
src/dimension.c
src/dimension_slice.c
src/event_trigger.c
src/event_trigger.h
src/hypertable.c
src/hypertable.h
src/process_utility.c
src/scanner.c
src/scanner.h
src/tablespace.c
test/expected/alternate_users.out
test/expected/constraint.out
test/expected/ddl.out
test/expected/ddl_single.out
test/expected/pg_dump.out
test/sql/constraint.sql

This Fixes at least two bugs:
1) A drop of a referenced table used to drop the associated
FK constraint but not the metadata associated with the constraint.
Fixes #43.
2) A drop of a column removed any indexes associated with the column
but not the metadata associated with the index.

Move index and constraints drop handling to event trigger

---

CMakeLists.txt

Sometimes pg_config reports versions like `PostgreSQL 10.2 (Ubuntu
10.2-1.pgdg16.04+1)`. Thus the regex is adjusted to allow for suffixes
after the postgres version number.

Fix regex for version reported by pg_config

---

sql/ddl_api.sql
sql/updates/pre-0.8.0--0.9.0-dev.sql
src/copy.c
src/copy.h
src/hypertable.c
src/indexing.c
src/indexing.h
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

Tables can now hold existing data, which is optionally migrated from
the main table to chunks when create_hypertable() is called.
The data migration is similar to the COPY path, with the single
difference that the inserted/copied tuples come from an existing table
instead of being read from a file. After the data has been migrated,
the main table is truncated.
One potential downside of this approach is that all of this happens in
a single transaction, which means that the table is blocked while
migration is ongoing, preventing inserts by other transactions.

Migrate table data when creating a hypertable

---

src/partitioning.c
test/expected/partitioning.out
test/sql/partitioning.sql

Previously, when the FmgrInfo was initialized for partitioning
functions, the type information was cached in the fn_extra
field. However, the contract for fn_extra is that it is to be set by
the called function and not prior to its invokation. Setting fn_extra
prior to function invokation is an issue for custom partitioning
functions implemented in SQL, as the SQL call manager expects to use
fn_extra for its own cache.
This change avoids setting fn_extra prior to function invokation, and
instead information is cached in fn_extra within our provided
partitioning functions.
The native partitioning functions now also support nested functions,
i.e., the input to the function is the output of another function.

Fix handling of custom SQL-based partitioning functions

---

sql/CMakeLists.txt
sql/cache_functions.sql
sql/ddl_triggers.sql
sql/timescaledb--0.1.0--0.2.0.sql
sql/timescaledb--0.2.0--0.3.0.sql
sql/timescaledb--0.3.0--0.4.0.sql
sql/timescaledb--0.4.0--0.4.1.sql
sql/timescaledb--0.4.1--0.4.2.sql
sql/timescaledb--0.4.2--0.5.0.sql
sql/timescaledb--0.5.0--0.6.0.sql
sql/timescaledb--0.6.0--0.6.1.sql
sql/timescaledb--0.6.1--0.7.0.sql
sql/timescaledb--0.6.1--0.7.1.sql
sql/timescaledb--0.7.0--0.7.1.sql
sql/timescaledb--0.7.1--0.8.0.sql
sql/timescaledb--0.8.0--0.9.0.sql
sql/trigger_functions.sql
sql/updates/post-global.sql
sql/updates/pre-global.sql

For multi-version upgrades it is necessary to change the location of
trigger functions before doing anything else in upgrade scripts.
Otherwise, it is possible to trigger an even before you change the
location of the functions, which would load the old shared library
and break the system.
This commit also fixes `/sql/timescaledb--0.8.0--0.9.0.sql` to
come from the release build.

Change trigger behavior on upgrades

---

sql/CMakeLists.txt
sql/cache.sql
sql/cache_functions.sql
sql/timescaledb--0.8.0--0.9.0.sql
sql/trigger_functions.sql
sql/updates/pre-0.8.0--0.9.0.sql
src/cache_invalidate.c
src/catalog.h
src/compat.c
test/expected/pg_dump.out

The cache invalidation triggers on our catalog tables
aren't used anymore as all modifications to catalog tables
happen using the C API, which won't invoke triggers and
has its own cache invalidation functionality.

Remove unused cache invalidation triggers

---

README.md

Upgrades from non-tagged commits are not supported, so building
from source should emphasize that for those who want to use
TimescaleDB instead of develop for TimescaleDB.

Update README to emphasize checking out tagged commit

---

sql/CMakeLists.txt
sql/updates/0.6.1--0.7.0.sql
sql/updates/0.7.0--0.7.1.sql
sql/updates/0.7.0.sql
sql/updates/README.md

A fix for updates of version 0.6.1 was lost in the previous PR that
refactored the update process. This change adds back that fix.
The build process for update scripts now also supports versioned
"origin" modfiles, which are included only in the update scripts that
origins in a particular version given by the origin modfile's
name. Origin modfiles make it possible to add fixes that should be
included only for the version upgrading from.

Fix update scripts for version 0.6.1

---

test/expected/pg_dump.out
test/sql/pg_dump.sql

Prior to PostgreSQL 10.3, the output for a trigger function did
not include the implied 'public' schema in its output when
outputting the function. In 10.3 this was changed causing the
regression test to fail. To make this more robust, the table is
now put into an explicit schema so the test does not rely on
the inconsistent behavior across versions as to printing out
'public'.

Make pg_dump regression test more robust

---

src/dimension.c
src/loader/loader.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

This fixes an issue with the `if_not_exists` option to add_dimension()
that caused the command to fail on a non-empty table. When this option
is set, the command should only fail if the dimension does not exists
and the table is non-empty.

Do not fail add_dimension() on non-empty table with 'if_not_exists'

---

test/sql/updates/post.v2.sql
test/sql/updates/setup.v2.sql

This commit adds a secondary FK to the update test. This
FK points to the same metadata table as the previous FK.
This case is added because it has caused problems in the
past.

Add second FK to update test

---

README.md
src/chunk.c
src/chunk.h
src/chunk_index.c
src/event_trigger.c
src/event_trigger.h
src/hypertable.c
src/hypertable.h
src/partitioning.c
src/process_utility.c
test/expected/drop_owned.out
test/expected/drop_schema.out
test/sql/CMakeLists.txt
test/sql/drop_owned.sql

This PR moves table, schema, and trigger drop handling into the event
trigger system. The event trigger system is a more reliable method of
intercepting object drops especially as they can CASCADE via other
object drops.
This PR also adds a test for DROP OWNED which was previously broken.

Move more drops into event trigger system

---

src/cache.c
test/expected/triggers.out
test/sql/triggers.sql

Previously, all Subtxn aborts released all cache pins. This is
wrong because that can release pins that are still in use by
higher-level subtxns and top-level txns. Now, we release only
pins corresponding to the appropriate subtxn. That means that we
now track the subtxn a pin was created in.

Fix Cache Pinning for Subtxns

---

.travis.yml
scripts/docker-run-abi-test.sh
scripts/docker_postgres_snapshot/Dockerfile

Test the ABI compatibility of postgres across minor version updates
wrt timescale. Namely, compile the extension on an early minor version
of postgres and test it on the latest snapshot of the major branch.

Add ABI compatibility tests

---

src/extension.c
src/extension_utils.c
src/loader/loader.c
test/expected/drop_extension.out
test/expected/loader.out

Previously, only the loader would complain if it was dynamically
loaded after preload. This PR adds a FATAL error message if the
versioned .so is not preloaded AND the loader has not been previously
loaded. This is a common case if the user forgets to edit
shared_preload_libraries to add the loader.
This PR also fixes the error in cases when it's encountered by a
non-superuser.

Add no preload error to versioned library.

---

src/constraint_aware_append.c
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/sql/include/append.sql

The explain output previously relied on the fact that the
estate->rtable was indexed the same way as the simple_rte_array
during planning. This is not always true when using CTEs. This
commit instead passes the oid of the hypertable to the EXPLAIN
directly.

Fix EXPLAIN output for ConstraintAwareAppend inside CTE

---

src/CMakeLists.txt

Building can still succeed even if not in a git context so this
"fatal" error should be hidden.

Remove irrelevant 'fatal not a .git repository' error

---

src/chunk_dispatch.c
src/chunk_dispatch.h
src/chunk_dispatch_info.c
src/chunk_dispatch_info.h
src/chunk_dispatch_state.c
src/chunk_dispatch_state.h
src/chunk_index.c
src/chunk_index.h
src/chunk_insert_state.c
src/chunk_insert_state.h
src/copy.c
src/hypertable_insert.c
test/expected/upsert.out
test/sql/upsert.sql

Previously, the chunk dispatch node used arbiter index and other
information from the top-level Query node. This did not work with CTEs
(and probably subqueries) because the info for this insert was not at
the top-level. This commit changes the logic to use that same info from the
parent ModifyTable node (and ModifyTableState).
This commit also changes the logic to translate the arbiter indexes
from the hypertable index to the chunk index directly using our catalog
tables instead of re-inferring the index on the chunk.

Enable hypertable inserts within CTEs

---

src/chunk_insert_state.c
src/copy.c
test/expected/insert.out
test/sql/insert.sql

Discovered a crash when doing an explain analyze on a CTE containing an insert that
did not reference the CTE in the select statement. This fixes by copying the eref
from the parent hypertable to the chunk so that columns can be described. It will
only copy the eref from the hypertable if there is a range table entry available.
Also modify copy so it actually sets a dummy variable as the RTE index rather than 1,
which is a valid RTE index, even if there is no RTE for the hypertable.

Fix crash on explain analyze with insert CTE

---

src/extension.c
src/extension_utils.c
src/loader/loader.c
test/expected/loader.out
test/loader-mock/src/init.c
test/sql/loader.sql

Previously, the GUC to let the versioned-extension know that
the loader was present was incorrectly reset during DISCARD ALL.
This caused newly minted parallel workers to throw an error
about the extension not being preloaded since it did not
know that a loader was, in fact, preloaded. This PR
fixes that by setting the correct default value for the GUC.
It also disables the loader in parallel workers since the loading
should have been handled in the parallel leader and the worker
start-up logic. Fixes #496

Fix bug with extension loader when DISCARD ALL is executed

---

src/tablespace.c

Macros that provide type assertion, like castNode() and lfirst_node()
were introduced in PG 9.6.3 and cannot be used if we want to support
the entire 9.6 series of releases. This change fixes usage of such
macros that was introduced as part of the 0.9.2 release of
TimescaleDB.

Fix a compilation issue on pre 9.6.3 versions

---

CMakeLists.txt
sql/ddl_api.sql
sql/size_utils.sql
sql/time_bucket.sql
test/expected/relocate_extension.out
test/sql/relocate_extension.sql

Checked to make sure each of these functions refers to one of the others using the correct schema and made relevant changes if it defaulted to PUBLIC schema instead.
"C" next to a function name below means it is written in C and therefore no changes were necessary.
--  add_dimension C
--  attach_tablespace C
--  chunk_relation_size SQL, changes not needed
--  chunk_relation_size_pretty SQL, changes not needed
--  create_hypertable C
--  detach_tablespace C
--  detach_tablespaces C
--  drop_chunks SQL, changes needed, done
--  first  C 
--  histogram C
--  hypertable_approximate_row_count SQL, changes not needed
--  hypertable_relation_size SQL, changes not needed
--  hypertable_relation_size_pretty SQL, changes needed, done
--  indexes_relation_size SQL, changes not needed
-- …

 use the correct schema to refer to external timescale functions from internal functions

---

src/loader/loader.c

This check should not be necessary and causes problems
under Windows builds. So it is removed.

Remove superfluous parallel check

---

src/chunk_dispatch.h
src/chunk_dispatch_state.c
src/chunk_insert_state.c
src/compat.h
test/expected/upsert.out
test/sql/upsert.sql

Previously, upserts (ON CONFLICT) clauses did not work well on tables
where the hypertable attribute numbers did not match chunk attribute
numbers. This is common if the hypertable has dropped columns or
there were other alter commands run on the hypertable before
chunks were created.
This PR fixes the projection of the returning clause as well
as the update clauses. It also fixes the where clause for ON CONFLICT
UPDATE. These fixes are mostly about mapping the attribute numbers
from the hypertable attnos->chunk attnos. Some slot tupleDesc also
needed to be changed to the tupleDesc of the chunk.
Note that because of the limitations in PG 9.6 we had to copy over
some expressions from the ModifyTable plan node inside the chunk
dispatch. These original expressions are irrecoverable from the …

Fix upserts on altered tables.

---

src/cache.c
src/cache.h
src/chunk.c
src/chunk.h
src/chunk_constraint.c
src/chunk_constraint.h
src/dimension.c
src/dimension.h
src/dimension_slice.c
src/dimension_slice.h
src/hypercube.c
src/hypercube.h
src/hypertable.c
src/hypertable.h
src/hypertable_cache.c
src/partitioning.c
src/partitioning.h
src/scanner.c
src/scanner.h
src/subspace_store.c
src/utils.h

Previously, cache lookups were run on the cache's memory
context. While simple, this risked allocating transient (work) data on
that memory context, e.g., when scanning for new cache data during
cache misses.
This change makes scan functions take a memory context, which the
found data should be allocated on. All other data is allocated on the
current memory (typically the transaction's memory context). With this
functionality, a cache can pass its memory context to the scan, thus
avoiding taking on unnecessary memory allocations.

Improve memory allocation during cache lookups

---

.travis.yml

We need the function `convert_tuples_by_name_map` which only
appears in 9.6.2.

Bump minimum version for ABI test to 9.6.2

---

src/indexing.c

This fixes a missing NULL check when creating default indexes that was
caught by a static analyzer.

Fix missing NULL check when creating default indexes

---

src/indexing.c

This fixes a static analyzer warning about using an unititalized
pointer. The analyzer doesn't realize that elog() will generate an
exception, so that the unitialized NULL check will never occur. This
change will clarify the code and silence the static analyzer.

Fix static analyzer warning when checking for index attributes

---

src/chunk.c
src/chunk.h
src/process_utility.c
test/expected/alter.out
test/sql/alter.sql

Previously, chunks could be renamed and have their schema changed, but
the metadata in the TimescaleDB catalog was not updated in a
corresponding way. Further, renaming a chunk column was possible,
which could break functionality on the hypertable.
Then catalog metadata is now properly updated on name and schema
changes applied to chunks. Renaming chunk columns have been blocked
with an informational error message.

Add support for changing chunk schema and name

---

src/agg_bookend.c
src/sort_transform.c
src/utils.c

This PR fixes all the formatting to be inline with the latest version of
pgindent. Since pgindent does not like variables named `type`, those
have been appropriately renamed.

Fix formatting to comply with pgindent

---

sql/size_utils.sql
test/expected/size_utils.out
test/sql/size_utils.sql

A bug in the SQL for getting the size of chunks would use the
TOAST size of the main/dummy table as the toast size for the
chunks rather than each chunks' own toast size.
Additionally, the 2nd commit addresses the formatting of chunk
names by using format() instead of string concatenation which
is safer from injection attacks.
Fixes https://github.com/timescale/timescaledb/issues/373

Fix misreported toast_size in chunk_relation_size funcs & formatting of chunk identifiers

---

scripts/CMakeLists.txt
scripts/generate_typedefs.sh.in
src/CMakeLists.txt

Trying to run `make pgindent` should result in runtime error if OBJDUMP not installed. This is in contrast to the current error message, which is easily missed during compile-time.

Helpful runtime error message in pgindent target when there's no objdump

---

src/constraint_aware_append.c
test/expected/lateral.out
test/sql/CMakeLists.txt
test/sql/lateral.sql

This bug manifested in LATERAL joins that have a time restriction and a constraint referencing the upper-level plan. As an optimization, also added a special case when the subplan is of type T_Result, which enables chunk pruning in this special case.
This fixes issue #579

Fix CustomScan pruning whenever the subplan is NOT of a Scan type

---

.travis.yml
src/compat.h
src/extension.c
src/extension.h
src/init.c

This PR adds a load-time check to the versioned extension for the
expected Postgres versions. This better handles the case where the
extension is distributed as a binary and compiled on a different
Postgres version than the one it is running on.
We also change the versioning to require:
PG >= 9.6.3 to avoid issues with missing functions in previous versions
OR
PG >= 10.2 to avoid issues with ABI incompatibility at PG 10.0 and 10.1

Improve version checking

---

src/loader/loader.c

Old versions used a GUC to determine whether the loader was present.
This PR sets that GUC in the loader so that those versions once
again work with the new loader.

Enable backwards compatibility for loader for 0.9.0 and 0.9.1

---

src/process_utility.c
test/expected/vacuum.out
test/sql/vacuum.sql

Previously, when running a VACUUM ANALYZE or ANALYZE on
a hypertable the statics on the parent table (hypertable)
were not correctly updated. This fixes that problem
and adds tests.

Update statistics on parent table when doing ANALYZE

---

src/chunk_constraint.c
src/hypertable.c
src/process_utility.c
test/expected/constraint.out
test/sql/constraint.sql

Constraints with the NO INHERIT option does not make sense on a
hypertable's root table since these will not be enforced.
Previously, NO INHERIT constraints were blocked on chunks, and were
thus not enforced until chunk creation time, allowing creation of NO
INHERIT constraints on empty hypertables, but then causing failure at
chunk-creation time. Instead, NO INHERIT constraints are now properly
blocked at the hypertable level.

Block NO INHERIT constraints on hypertables

---

src/dimension.c
src/partitioning.c
test/expected/create_hypertable.out
test/expected/partitioning.out
test/sql/create_hypertable.sql
test/sql/partitioning.sql

This adds a simple check to enforce that partitioning functions
are IMMUTABLE. This is a requirement since a partitioning function
must always return the same value given the same input.

Enforce IMMUTABLE partitioning functions

---

test/expected/alternate_users.out
test/expected/cluster.out
test/expected/ddl.out
test/expected/ddl_single.out
test/expected/index.out
test/expected/insert.out
test/expected/pg_dump.out
test/expected/plain.out
test/expected/reindex.out
test/expected/tablespace.out
test/sql/utils/testsupport.sql

This fixes the show_indexes test support function to properly show the
columns of the indexes instead of the table. The function now also
shows the expressions of expression indexes.

Fix and improve show_indexes test support function

---

src/dimension.c
test/expected/partitioning.out
test/sql/partitioning.sql

If the dimension that is being added via add_dimension is not
in all of hypertable indexes that have UNIQUE, PRIMARY KEY
or EXCLUSION constraints, then `add_dimension` call
should fail.
This PR enforces the above.

Validate existing indexes before adding a new dimension

---

src/partitioning.c
src/partitioning.h
test/expected/partitioning.out
test/sql/partitioning.sql

Previously, if a hypertable dimension type did not have a default
hash function, create_hypertable would throw an error.
However, this should not be the case if a custom partitioning
function is provided.
This commit addresses the issue making sure that arbitrary
custom types can be used as partitioning dimensions as long
as a valid partitioning function is provided.
Fixes #470.

Add support for custom hypertable dimension types

---

sql/CMakeLists.txt
sql/aggregates.sql
sql/bookend.sql
sql/histogram.sql
sql/updates/0.4.2--0.5.0.sql
sql/updates/README.md

There is no CREATE OR REPLACE AGGREGATE which means that the only way to replace
an aggregate is to DROP then CREATE which is problematic as it will fail
if the previous version of the aggregate has dependencies.
NOTE that WHEN CREATING NEW FUNCTIONS in sql/aggregates.sql you should also make
sure they are created in an update script so that both new users and people
updating from a previous version get the new function.
Fixes #612

Create aggregate functions only once to avoid dependency issues

---

src/dimension.c
src/dimension.h
src/process_utility.c
test/expected/constraint.out
test/expected/ddl_alter_column.out
test/sql/constraint.sql
test/sql/ddl_alter_column.sql

Previously the following commands would not through
an error on hypertables and this PR makes sure that
they do in order to avoid hypertable internals'
corruption:
* ALTER TABLE hypertable
ADD COLUMN new_device_id int UNIQUE;
* ALTER TABLE hypertable DROP COLUMN partitioning_column;
* ALTER TABLE hypertable DROP COLUMN time_open_dim;
* ALTER TABLE hypertable
ALTER COLUMN time_open_dim TYPE TEXT;
This pull request resolves the last comment of #536 by @soccerdroid

Fix some ALTER TABLE corner case bugs on hypertables

---

src/partitioning.c

Partitioning function information for closed (space) dimensions is passed
from SQL as REGPROC. This leaves no possibility for this info to be NULL
when internal partitioning function data structure is populated

Validate parameters when creating partition info

---

sql/util_time.sql
src/dimension.h
src/utils.c
src/utils.h
test/expected/custom_type.out
test/sql/CMakeLists.txt
test/sql/custom_type.sql

I was wondering what you think about adding support for custom types as a timescale column. This PR adds support for custom types that are binary castable to bigint type. It could quite easily be extended for different types I guess. I added specifically this case, as it involves little to no overhead at run-time to cast to a binary-compatible type.
Main use case that we have is that we have a custom timestamp type with extra precision, based on a bigint. We'd like to use this custom timestamp type instead of the bigint directly, because it is a nice abstraction and we can add custom casts/functions to it.

add support for binary compatible custom types as timescale column

---

src/dimension.h
test/expected/create_hypertable.out
test/expected/drop_hypertable.out
test/expected/insert_single.out
test/expected/partitioning.out
test/expected/size_utils.out
test/expected/timestamp.out

The previous default of 30 days was typically too long for most
starting use cases, which would lead users to have one large
chunk that lacked some of the benefits of using TimescaleDB, at
least for the initial chunk. This chunk size should be more
reasonable, especially for initial workloads.

Change default chunk size to one week

---

src/chunk_insert_state.c
src/chunk_insert_state.h
test/expected/partitioning.out
test/sql/partitioning.sql

Postgres assumes that exprs will live for the entire duration of the SQL expression that they are created from and stores pointers into them based on that assumption. As a memory usage optimization our INSERT dynamically creates chunk constraints which live for only an individual chunk insert, causing segfaults when postgres tries to read through the cleaned up memory. As we consider the constraint optimization critical, to fix this we now free the `per_tuple_exprcontext` _before_ deleting a chunk insert state memory context, ensuring the segfaulting callback is called on a valid state.
Supersedes #635 and #645.
Segfaulting code:
```SQL
CREATE TYPE simpl AS (val1 int4);
CREATE OR REPLACE FUNCTION simpl_type_hash(ANYELEMENT) RETURNS int4 AS $$
SELECT $1.val1 AS resut;
$$ LANGUAGE SQL …
```

Fix segfault with custom partition types V2.

---

src/chunk_adaptive.c

This error incorrectly intialized nulls to true, false. Now changed
both to be true. Error found by valgrind.

Fix memory initialization error

---

.travis.yml

The valgrind tests currently fail intermittently and take a lot of time
for the amount of CI workers we have available. We can still trigger
them by pushing to the prelease_test branch.

Remove valgrind tests from Travis cron

---

src/dimension_vector.c
src/subspace_store.README.md
src/subspace_store.c
test/expected/insert.out
test/sql/insert.sql

SubspaceStore keeps a running count of the number of objects added to
it called `descendants`. This patch fixes that count, so that it always
keeps track of the number of objects sitting at the leaves of the
SubspaceStore. (The current version treats `descendants` as keeping
track of the number of leaves at some places, and the number of objects
sitting at the next level at others, resulting in the counter containing
neither.
Adds documentation about the layout of, and insertion to, `SubspaceStore`.
Also fixes UB in dimension vector: `memcpy` cannot be used on overlapping memory.
This reduces memory usage of #643 by ~200MB.

Fix SubspaceStore to ensure max_open_chunks_per_insert is obeyed

---

src/guc.c

Our default `max_open_chunks_per_insert` was based on an assumption that
chunks used less memory than they actually do. Upping that constant based on results from `MemoryContextStats(TopMemoryContext) ` to reduce memory usage.

Reduce number of open chunks per insert

---

test/runner.sh

Using the regression test script on a remote machine would leave
behind a secondary database (by default called `single_2`) that
would cause the next run to fail when trying to remove the role
that owned the secondary database. This change has the script
remove the secondary database so that no longer happens.

Improve regression test script to cleanup more thoroughly

---

src/chunk.c
src/chunk_constraint.c
src/chunk_index.c
src/dimension.c
src/dimension_slice.c
src/hypertable.c
src/tablespace.c

Use the postgres macro instead of manual subtraction everywhere to be more readable, and gain the `Assert`.
This was done with `find ./src -type f -exec sed -i -e 's/\[Anum_\(.*\) - 1\]/\[AttrNumberGetAttrOffset(Anum_\1)\]/' {} \;`

Use AttrNumberGetAttrOffset instead of Anum_name - 1 for array indexing

---

test/sql/CMakeLists.txt

Our files generated from templates do not get recreated by `make` when
they get deleted, and have to be recreated manually or by rerunning
cmake. This commit adds a note to the CMakeLists.txt to that effect.

Note how to recreate templated files

---

sql/updates/0.10.1--0.11.0.sql
sql/updates/0.11.0--0.11.1-dev.sql
src/hypertable.c
src/hypertable.h
src/trigger.h
test/expected/create_hypertable.out
test/expected/pg_dump.out
test/sql/create_hypertable.sql
test/sql/pg_dump.sql
test/sql/utils/testsupport.sql

Previously, the pg_dump test was broken because it is not possible to reference psql variables
from inside bash commands run through psql. This is fixed by hardcoding the username passed to
the bash commands inside the test.
Also, we changed the insert block trigger preventing inserts into hypertable to a non-internal
trigger, because internal triggers are not dumped by pg_dump. We need to dump the trigger so that
it is already in place after a pg_restore, to prevent users from accidentally inserting rows into
a hypertable while timescaledb_restoring=on.

Fix pg_dump test and make insert block trigger a non-internal trigger

---

CMakeLists.txt
src/CMakeLists.txt
src/bgw/timer.c
src/bgw/timer.h
src/config.h.in
src/hypertable.c
src/init.c
src/loader/bgw_launcher.c
src/net/CMakeLists.txt
test/expected/privacy.out
test/sql/CMakeLists.txt
test/sql/privacy.sql
test/src/net/test_conn.c
test/src/telemetry/test_telemetry.c

This fixes a number of compilation and test issues when OpenSSL is not
available. While we still default to OpenSSL enabled, we allow
explicitly setting -DUSE_OPENSSL=false to compile and run tests
without OpenSSL installed. But if not specified, CMake will fail if
OpenSSL is not available on the system.

Fix issues when OpenSSL is not available

---

src/loader/CMakeLists.txt

The symbol_conflict test failed on Windows because the CMake build
script accidentally did not include the required code in the loader
during Debug builds. This change fixes the CMake script so that the
code is included in the laoder.

Fix symbol_conflict test on Windows

---

test/expected/alternate_users.out
test/expected/ddl.out
test/expected/ddl_single.out
test/expected/index.out
test/expected/pg_dump.out
test/expected/reindex.out
test/sql/pg_dump.sql
test/sql/utils/pg_dump_aux_dump.sh
test/sql/utils/pg_dump_aux_restore.sh
test/sql/utils/testsupport.sql

Windows and Unix platforms had different orderings
for some tests in pg_dump. Now we order by Index
name collated as a byte string so that we get the
same ordering regardless of platform.

Make pg_dump test work on remote and Windows

---

scripts/docker-build.sh
sql/bgw_scheduler.sql
sql/pre_install/tables.sql
sql/updates/0.11.0--0.11.1-dev.sql
sql/version.sql
src/bgw/job.c
src/bgw/scheduler.c
src/telemetry/telemetry.c
src/telemetry/uuid.c
test/expected/bgw_db_scheduler.out
test/expected/drop_rename_hypertable.out
test/expected/extension.out
test/expected/privacy.out
test/postgresql.conf
test/sql/bgw_db_scheduler.sql
test/sql/privacy.sql
test/sql/updates/post.post_insert.sql

This adds the telemetry job to the job scheduler. Telemetry is
scheduled to run every 24 hours with a 1 hour exponential backoff
retry period.

Add job for telemetry

---

test/CMakeLists.txt
test/sql/utils/pg_dump_aux_dump.sh
test/sql/utils/pg_dump_aux_restore.sh

Hi,
Trivial but If pg_dump, createdb, dropdb and pg_restore aren't in system default path 'make installcheck' test pg_dump fails.
pg_config output is already used for pg_regress.
Regards
Didier

Testing: use pg_config bindir directory for pg executables.

---

CMakeLists.txt

Setting the default build type was done after the build type was
outputted in bootstrap which caused a confusing output saying
the build type was blank. Also, this adds the install method to
verify binary builds are correct.

Update bootstrap output to include build type and install method

---

.travis.yml

These pre-built images should give us more robust Valgrind tests
due to the fact that each job does not have to build the image
each time, which caused a lot of flakes.

Change Travis to use remote images for Valgrind

---

src/loader/bgw_launcher.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql
test/sql/include/bgw_launcher_utils.sql
test/sql/include/bgw_launcher_utils_cleanup.sql

Avoid starting schedulers for template databases as connections to them (including from background workers) mean that they cannot be used as templates.

Don't start schedulers for template databases.

---

test/expected/installation_metadata.out
test/expected/pg_dump.out
test/sql/CMakeLists.txt
test/sql/installation_metadata.sql
test/sql/utils/pg_dump_aux_restore.sh

Removed NOTICE from extension file when in Debug mode, so we don't have to keep removing it from and fixing the version number in *.out files. Also added installation_metadata test back into CMakeList.

Remove NOTICE in debug mode

---

src/bgw/job_stat.c
test/src/telemetry/test_telemetry.c

This cleanup was run on master before background worker code was
merged, so this PR captures the code that was missed.

Use AttrNumberGetAttrOffset in missed bgw code

---

.travis.yml

We currently check code formatting and remind people to obey style by hand. Github's [unusual rendering](https://github.com/timescale/timescaledb/blob/0e4fce5dad1c307669fbe68bcb720c6f34421f98/src/net/conn.h#L24-L25), makes this tedious and error-prone, since it is difficult to be certain if some formatting is incorrect, or just strangely rendered. This commit adds a travis job which checks PRs for correct formatting by running `pgident` on each PR, and outputting the diff if one exists. Hopefully this will prevent incorrectly formatted code from merging into master with minimal overhead.

Add travis format checking

---

sql/version.sql
src/telemetry/telemetry.c
src/telemetry/telemetry.h
src/version.c
src/version.h
test/expected/pg_dump.out
test/expected/telemetry.out
test/sql/telemetry.sql
test/src/telemetry/test_telemetry.c

Version checks fail on pre-release versions (e.g., `1.0.0-rc1`) since
the version parsing didn't expect a pre-release tag at the end.
This change adds support for pre-release tags, using lexicographical
comparison in case of pre-release tags. Note that having a pre-release
tag vs not having one makes the version strictly "smaller", given
otherwise identical versions.

Add support for pre-release version checks

---

test/src/bgw/log.c
test/src/bgw/scheduler_mock.c

There was a Valgrind stack overflow bug that occurred occassionally inside the bgw_db_scheduler test.
This led us to identify several places in the scheduler test code in which infinite recursion could occur.
The biggest source of a potential stack overflow is inside the emit_log_hook_callback. In particular, if the
callback encounters an error, the code that throws the error will be trying to write a log message, which
will trigger a call to the log_hook_callback. If this error persists (ie is encountered on every subsequent
call to the callback), then the log_hook_callback will
infinitely loop on itself, thereby causing a stack overflow.
Another potential source of infinite recursion are the static variables, prev_emit_log_hook and
prev_signal_func, that preserve Postgres' default …

Fix custom error handling callbacks in scheduler test code

---

src/net/conn_plain.c

AF_UNSPEC is in SUS, postgres uses similar convention.  FreeBSD seems to lack whatever was implicitly importing sys/socket.h, so specify it here for !win32.

Fix build on FreeBSD wrt sockets

---

src/bgw/job.c
src/bgw/scheduler.c
src/loader/bgw_launcher.c
test/expected/bgw_db_scheduler.out

Previously TimescaleDB background jobs used Postgres's default `bgworker_die`
sigterm handler. However this signal handler had a few problems:
1) It does not respect critical sections and causes PANIC when the
signal is received inside a critical section
2) It can get called while the system has an acquired spinlock.
Both of these problems are solved by using the CHECK_FOR_INTERRUPTS
system inside native Postgres but this requires using the `die` signal
handler (note this is what the parallel infrastructure uses). So,
we switch to using a handler that calls `die` but also supplements
with better log messages.
We changed both the db scheduler and jobs to use this method of signal
handling. We also added a safety check to the launcher to handle
critical sections in a safer way.

Fix sigterm handling in background jobs

---

src/chunk_adaptive.c
test/expected/chunk_adaptive.out
test/sql/chunk_adaptive.sql

Previously we did not check that the type of the index was correct
so it would usually take the first default index, which actually
did not give the correct results for min and max and thus caused
adaptive chunking to potentially not work well.

Fix adaptive chunking so it chooses correct index

---

CMakeLists.txt

Previously, whenever the underlying Postgres installation did not have OpenSSL enabled, but Timescale was trying to compile WITH OpenSSL, users would get a compile error because the Postgres header file include/pg_config.h tries to redefine an OpenSSL function. To prevent this compilation error, we have modified CMake to simply fail the build if Postgres is not OpenSSL-enabled, but the user is trying to compile WITH OpenSSL. CMake will now print a message with 2 actions the user can take to fix the error.

Give a helpful build warning when Postgres does not have OpenSSL enabled

---

src/version.c
src/version.h

This prevents a possible memory overflow bug.

Add const qualifier to version_delimiter definition

---

test/expected/vacuum.out
test/sql/vacuum.sql

The original fix used the wrong array-to-string function getting the wrong output order. This commit fixes that and also removes the irrelevant ORDER BY `schemaname`, since we always constrain `schemaname` to be a constant and ORDERs BY `attrname` to ensure that we see similar orders in all tests regardless of the values of histogram bounds.

Fix and clean vacuum test

---

.travis.yml

Postgres has a compile flag EXEC_BACKEND which makes linux behave more
like windows in order to ease testing of windows behavior. By default
the postgres docker images are built without this, so we've built our
own version with the flag enabled for our CI. This commit enables
testing on those versions.

Update travis to run tests with EXEC_BACKEND also

---

src/chunk_adaptive.c
src/dimension.c
test/expected/chunk_adaptive.out
test/sql/chunk_adaptive.sql

The use of the incorrect index to find the hypertable that a
dimension belongs to caused adaptive chunking to break whenever
dimension_id != hypertable_id, which happened with hypertables that
have multiple dimensions where time is not the first one.

Fix adaptive chunking when hypertables have multiple dimensions

---

CMakeLists.txt

Instead of grepping around in the pg_config.h file, which might not contain proper defines/undefs for binary installations, we use pg_config --configure to determine if the underlying Postgres installation is compiled with OpenSSL. This is more robust.

Change detection of USE_OPENSSL in Postgres to use pg_config

---

src/bgw/launcher_interface.c
src/bgw/launcher_interface.h
src/extension_constants.h
src/init.c
src/loader/CMakeLists.txt
src/loader/bgw_interface.c
src/loader/bgw_interface.h
src/loader/loader.c

A loader API version is added for future-proofing. It will allow
versioned-extension to figure out the version of the loader API that
is installed. For example, if a future versioned extension uses new
functions made available by a new loader version it could use the loader
API version number to figure out if this new capability is actually
available in the installed loader (note a loader could be older than
the versioned-extension if the database was not restarted).

Add loader API version function

---

sql/time_bucket.sql
src/CMakeLists.txt
src/plan_add_hashagg.c
src/time_bucket.c
test/expected/plan_hashagg_optimized-10.out
test/expected/plan_hashagg_optimized-9.6.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/expected/sql_query_results_x_diff.out
test/expected/timestamp.out
test/sql/timestamp.sql

The integer variants of time_bucket don't handle negative time values properly and return the upper boundary of the interval instead of the lower boundary for negative time values.
Fixes #738

Fix negative value handling in time_bucket

---

src/loader/loader.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

n extension can be dropped indirectly via DROP OWNED. This
PR makes sure that such cases are correctly handled by stopping
the appropriate background workers.
This PR also includes a cleanup PR.

 Stop background workers when extension is DROP OWNED

---

sql/cache.sql
sql/pre_install/schemas.sql
sql/pre_install/tables.sql
test/expected/pg_dump_unprivileged.out
test/sql/CMakeLists.txt
test/sql/pg_dump_unprivileged.sql
test/sql/utils/pg_dump_unprivileged.sh

When timescaledb is installed in template1 and a user with only createdb privileges creates a database, the user won't be able to dump the database because of lacking permissions. This PR grants the missing permissions to PUBLIC for pg_dump to succeed.
Fixes #720 
Fixes #605

Grant permissions to public for pg_dump to work

---

.travis.yml
test/CMakeLists.txt
test/isolation/CMakeLists.txt
test/isolation/expected/isolation_nop.out
test/isolation/expected/read_committed_insert.out
test/isolation/expected/read_uncommitted_insert.out
test/isolation/expected/repeatable_read_insert.out
test/isolation/expected/serializable_insert.out
test/isolation/expected/serializable_insert_rollback.out
test/isolation/specs/isolation_nop.spec
test/isolation/specs/read_committed_insert.spec
test/isolation/specs/read_uncommitted_insert.spec
test/isolation/specs/repeatable_read_insert.spec
test/isolation/specs/serializable_insert.spec
test/isolation/specs/serializable_insert_rollback.spec
test/pg_isolation_regress.sh

Postgres has a tool pg_isolation_regress which allows testing the behavior of
concurrent commands. Despite not being installed by default, the tool is still
build with the rest of postgres, and can run outside of the postgres src
directory. This commit adds hooks within the timescale build system to call
pg_isolation_regress from the postgres source tree, and run timescale tests
using it.
This commit also adds some basic tests for the behavior of concurrent INSERTS
that create chunks.

Add pg_isolation_regress support to the timescale build system

---

src/bgw/job.c
src/bgw/job.h
src/telemetry/telemetry.c
src/telemetry/telemetry.h
test/expected/bgw_db_scheduler.out
test/expected/privacy.out
test/expected/telemetry.out
test/sql/bgw_db_scheduler.sql
test/sql/privacy.sql
test/sql/telemetry.sql
test/src/bgw/scheduler_mock.c
test/src/telemetry/test_privacy.c
test/src/telemetry/test_telemetry.c

To distinguish short-running instances from long-running instances, we have the telemetry BGW run hourly for the first 12 hours.
After this initial period, the BGW will run the default once every 24 hours.
Also added a scheduler test that tests background jobs are able to set next_start time within the job itself. Also modified telemetry function to return a boolean so that the scheduler can properly account for failures.

Modify telemetry BGW to run every hour the first 12 hours

---

src/process_utility.c
test/expected/alter.out
test/sql/alter.sql

This commit enables setting tablespace on hypertables and adds proper testing.
Setting tablespace of indexes was handled in a previous commit
here: 097db3d58928ab4784c679b8308ab0ebf3bf1fe0

Add support for ALTER TABLE SET TABLESPACE on hypertables

---

sql/ddl_internal.sql
sql/updates/0.4.2--0.5.0.sql
sql/util_internal_table_ddl.sql
src/chunk_adaptive.c
src/dimension.c
src/errors.h
src/hypertable.c
src/indexing.c
src/process_utility.c
src/tablespace.c

Our errorcodes have a `IO` prefix from when we were Iobeam. This commit
switches that prefix to `TS` for consistency.

Switch 'IO' error prefix to 'TS'

---

scripts/docker-run-abi-test.sh

We have no need to run the pg_isolation_regress tests with the ABI smoke
tests, and if we wanted to we'd have to build pg_isolation_regress each time. This commit disables them for that test.

Disable isolation tests on the ABI smoke test

---

scripts/docker-run-memory-test.sh
scripts/test_update_from_tag.sh

Using the new flag available in Docker images, turn off telemetry in Docker images used by Travis

Turn off telemetry in Docker images used in CI

---

test/sql/loader/CMakeLists.txt

This way they don't end up in a release installation

Only install the mock functions for debug builds

---

src/process_utility.c

This eliminates a compile warning from gcc-8.x in release mode builds

 Remove invalid assert in process_altertable_set_tablespace_end

---

test/CMakeLists.txt

Hi,
If there's multiple postgresql try to find the right pg_isolation_regress, likely in pg_config bin directory.
Regards
Didier

Search for pg_isolation_regress in pg_config bin directory

---

src/loader/README.md
src/loader/bgw_launcher.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

This PR changes the launcher to use a state machine to keep track
of the state of each database scheduler. Further, it add polling
to go through the list of databases and check their states. This
solves several issues
1) A CREATE DATABASE call using a template that already has TimescaleDB
installed previously did not start a scheduler until the next database
restart. A test for this case has been added.
2) A lack of available slots or background workers when a new database was added
meant that the scheduler would not be stared until the next database
restart. Now this will be retried on every polling event.
This PR also simplifies logic since database entries are never removed
from the hash table and thus never added more than once. State
transitions are now easier to read and reason …

Add state machine and polling to launcher

---

test/expected/pg_dump.out
test/sql/pg_dump.sql

The pg_dump test breaks if someone forgets to update the test when
adding a new function. Given that that is not what we are really
testing for in this test, it makes sense to instead save the number
of dependent objects in a psql variable and test against it later
in the script as needed.

Fix pg_dump test so that it doesn't rely on number of functions

---

sql/CMakeLists.txt
sql/bgw_scheduler.sql
sql/pre_install/bgw_scheduler_startup.sql
src/loader/README.md
src/loader/bgw_launcher.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

Modify the restart action to start schedulers if they do not exist, this fixes a
potential race condition where a scheduler could be started for a given
database, but before it has shut down (because the extension does not exist) a
create extension command is run, the start action then would not change the
state of the worker but it would be waiting on the wrong vxid, so not see that
the extension exists. This also makes it so the start action can be truly
idempotent and not set the vxid on its startup, thereby respecting any restart
action that has taken place before and better defining how each interacts with
the system.
Additionally, we decided that the previous behavior in which launchers were not
started up on, say, alter extension update actions was not all that desirable as
it …

Start stopped workers on restart message

---

src/tablespace.c
test/expected/alter.out
test/sql/alter.sql

This commit tests ALTER TABLE ... SET TABLESPACE, attach_tablespace,
detach_tablespace behaviour when pg_default is the argument
tablespace.
It also makes sure that a table can always be moved to the default
tablespace of its database. Previously, this was blocked whenever
the user owning the table did not own the tablespace.

Handle and test tablespace changes to and from the default tablespace

---

src/time_bucket.c
src/utils.c
src/utils.h

This change moves all time_bucket-related functions to the same source
file (time_bucket.c) for consistency. There are no changes to code
logic.

Move all time_bucket funtions to same source file

---

test/expected/version.out
test/sql/version.sql

Currently only get_git_commit is tested in our regression tests, I think it's a good idea to call them all at least once to check they are not broken. Since the returned values are highly variable I only check returned types.

Test get_git_commit, get_os_info and get_version returned types

---

.travis.yml
scripts/docker-build.sh
scripts/test_update_from_tag.sh
scripts/test_updates.sh
scripts/test_updates_no_constraints.sh
scripts/test_updates_with_constraints.sh

This change makes the update tests from each prior version of TimescaleDB to run in parallel instead of in serial order.
This speeds up the testing significantly.

 Run update tests in parallel

---

src/hypertable.c
test/expected/chunk_adaptive.out

Adaptive chunking is in beta, and we don't want users enabling it in
production by accident. This commit adds a warning to that effect.
(This was requested by @mfreed)

Add beta NOTICE when using adaptive chunking

---

src/bgw/job_stat.c

Using DatumGetTimestampTz is requires on some 32-bit platforms under
PG 9.6.

Fix incorrect function call

---

src/loader/loader.c

We use a custom loader to enable different databases within a single cluster to have different timescaledb versions. This code can be confusing to the uninitiated, so this PR adds documentation about how the loading happens.

[Documentation Only Change] Document timescales loading procedure

---

sql/bgw_scheduler.sql
sql/cache.sql
src/bgw/job.c
src/bgw/job_stat.c
src/bgw/job_stat.h
src/bgw/scheduler.c
src/bgw/scheduler.h
src/cache_invalidate.c
src/catalog.c
src/catalog.h
src/compat.h
test/expected/bgw_db_scheduler.out
test/expected/extension.out
test/sql/bgw_db_scheduler.sql
test/src/bgw/CMakeLists.txt
test/src/bgw/params.c
test/src/bgw/params.h
test/src/bgw/scheduler_mock.c
test/src/bgw/test_job_refresh.c
test/src/bgw/timer_mock.c

Previously, the scheduler only populated its jobs list once at start time. This commit enables the scheduler to receive notifications for updates (insert, update, delete) to the bgw_job table. Notifications are sent via the cache invalidation framework. Whenever the scheduler receives a notification, it re-reads the bgw_job table. For each job currently in the bgw_job table, it either instantiates new scheduler state for the job or copies over any existing scheduler state, for persisting jobs. For jobs that have disappeared from the bgw_job table, the scheduler deletes any local state it has.
Note that any updates to the bgw_job table must now go through the C, so that the cache invalidation framework in catalog.c can run. In particular, this commit includes a rudimentary API for …

Enable scheduler to update its jobs list

---

src/bgw/job.c
src/bgw/job_stat.c
src/chunk.c
src/chunk_constraint.c
src/chunk_index.c
src/dimension.c
src/dimension_slice.c
src/hypertable.c
src/hypertable_cache.c
src/installation_metadata.c
src/scanner.c
src/scanner.h
src/tablespace.c

This change adds proper result types for the scanner's filter and
tuple handling callbacks. Previously, these callbacks were supposed to
return bool, which was hard to interpret. For instance, for the tuple
handler callback, true meant continue processing the next tuple while
false meant finish the scan. However, this wasn't always clear. Having
proper return types also makes it easier to see from a function's
signature that it is a scanner callback handler, rather than some
other function that can be called directly.

Refactor scanner callback interface

---

test/expected/cluster.out
test/sql/cluster.sql

Adding ORDER BY to some select statements in cluster.sql test to ensure determinism.

Ensure deterministic results in cluster test

---

test/src/bgw/test_job_refresh.c

Surprisingly, the compiler didn't complain about allocating a stack array with a size only known at runtime. Modified memory allocation to be heap-allocation to remedy this error.

Change to heap allocation for runtime array size

---

src/dimension_vector.c
src/dimension_vector.h
src/hypertable_restrict_info.c
test/expected/plan_expand_hypertable_optimized.out
test/sql/include/plan_expand_hypertable_load.sql
test/sql/include/plan_expand_hypertable_query.sql

Exclude unneeded chunks for IN/ANY statement.
Optimization only takes care of equals operator. Only explicit values are supported eg.:
`WHERE some_value IN ('val1', 'val2'...) ` or `WHERE some_value = ANY(ARRAY['val1', 'val2'....])`.
IN/ANY with subqueries are not taken care of in this PR.

Exclude unneeded chunks for IN/ANY statement

---

src/loader/loader.c
test/expected/drop_owned.out
test/sql/drop_owned.sql

Currently `DROP OWNED BY user` throws an error in a database without timescaledb installed but with timesaledb preloaded. This patch fixes the behaviour and also adds a test for that case.

Check extension exists for DropOwnedStatement in post_analyze_hook

---

src/dimension.c

INTXX_MAX requires an extra include on windows and maybe other platforms. This patch changes the INTXX_MAX macros to PG_INTXX_MAX for consistency and to reduce platform specific code.

Use PG_INTXX_MAX macros instead of INTXX_MAX

---

src/chunk_insert_state.c
test/expected/upsert.out
test/sql/upsert.sql

Previously, there was a bug when chunks contained dropped columns
in the mapping of variable numbers. This PR fixes the bug and adds a
test for this case.
Thanks to @qmnonic for reporting this bug

Fix upsert TLE translation when mapping variable numbers

---

test/expected/plan_hashagg_results_x_diff.out
test/sql/plan_expand_hypertable_results_diff.sql
test/sql/plan_hashagg_results_x_diff.sql

after postgres commit c09daa9104099422ea998e0398934ca82eb37898 'fatal' is either not valid
or replaced by 'error'.

set client_min_messages to 'error' not 'fatal'

---

src/bgw/job.c
src/bgw/job_stat.c
src/hypertable.c
src/utils.c
src/utils.h

Refactored the boilerplate that allocates and copies over data from a tuple to a struct. This is typically used in the scanner context in order to read rows from a SQL table in C.

Provide helper function creating struct from tuple

---

sql/bgw_scheduler.sql
sql/size_utils.sql
src/chunk_adaptive.c
src/dimension.c
src/hypertable.c
test/expected/bgw_db_scheduler.out
test/expected/chunk_adaptive.out
test/expected/create_chunks.out
test/expected/ddl_errors.out
test/expected/drop_chunks.out
test/expected/size_utils.out
test/expected/tablespace.out
test/sql/bgw_db_scheduler.sql
test/sql/chunk_adaptive.sql
test/sql/create_chunks.sql
test/sql/create_hypertable.sql
test/sql/ddl_errors.sql
test/sql/drop_chunks.sql
test/sql/size_utils.sql
test/sql/tablespace.sql

Change hypertable_relation_size, hypertable_relation_size_pretty, chunk_relation_size, chunk_relation_size_pretty, indexes_relation_size, indexes_relation_size_pretty, partitioning_column_to_pretty ,insert_job and delete_job to STRICT
Add checks for NULL arguments to ts_chunk_adaptive_set,
ts_dimension_set_num_slices, ts_dimension_set_interval,
ts_dimension_add and ts_hypertable_create

Fix NULL handling in multiple functions and add calls with NULL arguments to tests

---

scripts/check_file_license_apache.sh

This fixes multiple warnings in bash 4.4
scripts/check_file_license_apache.sh: line 22: warning: command substitution: ignored null byte in input
and is also more correct since we dont want to inject 0-Bytes into the string

Set ORS to empty string instead of NUL in license check script

---

src/bgw/job.c
src/bgw/job.h
src/bgw/job_stat.c
src/catalog.c
src/catalog.h
src/chunk.c
src/chunk_adaptive.c
src/chunk_constraint.c
src/chunk_index.c
src/dimension.c
src/dimension_slice.c
src/hypertable.c
src/installation_metadata.c
src/process_utility.c
src/tablespace.c

Organize catalog.c so that functions that access the Catalog struct are physically separate from the functions that modify the actual catalog tables on disk. Also added macros and made static some functions that aren't used outside the catalog files. Also refactored out the CatalogDatabaseInfo struct, which is independent of the Catalog struct and will be reused in the future.

Clean up catalog code

---

sql/CMakeLists.txt
sql/views.sql
test/expected/loader.out
test/expected/pg_dump.out
test/expected/views.out
test/pgtest/CMakeLists.txt
test/sql/CMakeLists.txt
test/sql/loader.sql
test/sql/views.sql

Add information_schema._timescaledb_hypertables view that lists
hypertables, their owner, number of chunks and storage size
```
SELECT * FROM timescaledb_information.hypertable;
table_schema | table_name |    table_owner    | num_dimensions | num_chunks | table_size | index_size | toast_size | total_size 
--------------+------------+-------------------+----------------+------------+------------+------------+------------+------------
public       | ht1        | default_perm_user |              1 |          1 | 8192 bytes | 16 kB      |            | 24 kB
public       | ht2        | default_perm_user |              1 |          1 | 8192 bytes | 16 kB      | 8192 bytes | 32 kB
open         | open_ht    | super_user        |              1 |          3 | 24 kB      | 48 kB      |            | …
```

Add view to show hypertable information

---

sql/CMakeLists.txt
sql/ddl_api.sql
sql/ddl_internal.sql
sql/updates/1.0.1--1.1.0.sql
src/CMakeLists.txt
src/catalog.c
src/chunk.c
src/compat.c
src/compat.h
src/dimension.c
src/dimension.h
src/dimension_slice.c
src/dimension_slice.h
src/extension_utils.c
src/hypertable.c
src/hypertable.h
src/plan_add_hashagg.c
src/planner.c
src/utils.c
src/utils.h
test/expected/chunk_utils.out
test/expected/extension.out
test/sql/CMakeLists.txt
test/sql/chunk_utils.sql

Timescale provides an efficient and easy to use api to drop individual
chunks from timescale database through drop_chunks. This PR builds on
that functionality and through a new show_chunks function gives the
opportunity to see the chunks that would be dropped if drop_chunks was run.
Additionally, it adds a newer_than option to drop_chunks (also supported
by show_chunks) that allows to see/drop chunks in an interval or newer
than a point in time.
This commit includes:
- Implementation of show_chunks in C
- Additional helper functions to work with chunks
- New version of drop_chunks in sql that uses show_chunks. This
also adds a newer_than option to drop_chunks
- More enhanced tests of drop_chunks and new tests for show_chunks
Among other reasons, show_chunks was implemented in C in order …

Implement show_chunks in C and have drop_chunks use it

---

.travis.yml

Since we have proper windows ci now we dont need this anymore

Remove EXEC_BACKEND tests from travis

---

src/utils.c
src/utils.h

Remove int_cmp, create_fmgr and makeRangeVarFromRelid from utils.c
since they were not used and had no test coverage.

Remove unused functions from utils.c

---

src/hypertable.c
src/hypertable.h

hypertable_delete_by_id has long since been replaced by hypertable_delete_name and isn't used anywhere in the codebase.

Remove unused function from hypertable.c

---

.travis.yml
scripts/CMakeLists.txt
scripts/export_prefix_check.sh.in

Makes sure our exported symbols are namespaced correctly.

Check that functions start with the ts_ prefix in travis

---

.travis.yml
scripts/export_prefix_check.sh.in
src/bgw/job.c
src/bgw/scheduler.c
src/build-defs.cmake
src/loader/bgw_interface.c
src/loader/bgw_launcher.c
src/loader/bgw_message_queue.c
src/loader/bgw_message_queue.h
src/loader/loader.c
src/plan_add_hashagg.c
src/plan_agg_bookend.c
src/version.c
test/src/bgw/scheduler_mock.c
test/src/bgw/timer_mock.c
test/src/bgw/timer_mock.h
test/src/loader/init.c
test/src/net/conn_mock.c
test/src/net/conn_mock.h
test/src/net/test_http.c
test/src/telemetry/test_telemetry.c

This commit makes four changes:
1. Adds the ts_ prefix to some functions that were missed in the last
pass
2. Adds static to some variables that were confined to a single file but
missing it
3. Adds the ability to disable using "hidden" visibility by default by
setting the USE_DEFAULT_VISIBILITY variable
4. Switches the prefix-check in travis to use the flag defined in 3 so
that the checker now checks all non-static symbols we define

Have prefix check verify all functions in headers and clean up missing ones

---

test/expected/bgw_db_scheduler.out
test/sql/bgw_db_scheduler.sql

Hi,
When tested on an overload computer bgw scheduler test fail randomly.
This patch sort output first.
Regards
Didier

Ensure deterministic results in bw scheduler test

---

src/extension.c

Throwing errors this way breaks pg_upgrade as it tries to check
that libraries that have functions associated with them are
available before copying data from the old cluster over to the new.

Don't throw errors when extension is loaded but not installed yet

---

src/bgw/launcher_interface.c
src/extension_constants.h
src/loader/bgw_launcher.c
src/loader/loader.c

We removed a parallel workers check a while back because there were problems
with the macro on Windows, we define a new macro that works on Windows as we
received reports of some instances in which the Timescale library appeared to
be loading twice in parallel workers. Parallel workers instead restore the
library state of their parent process via their normal pathway and the loader
will take no action.
Additionally, prepend "$libdir/" to all calls to .so's so that we don't end up
accidentally loading from a place different from where we've loaded when we
create functions, which all refer to $libdir. This would only affect users
who have multiple separate .so's in different directories, but could be another
case where multiple .so's were loaded.

Avoid loading twice in parallel workers and load only from $libdir

---

README.md

The installation links were a bit out-of-date given our new page
structure. Also, our tools were not mentioned anywhere, so now the
README has pointers to them at the bottom, and in particular a
brief section to point to timescaledb-tune.

Update README with tools and other fixes

---

.travis.yml
test/pgtest/CMakeLists.txt

Run pginstallcheck with parallel schedule
Don't stop on dependency error for installcheck
Don't build postgres with --enable-coverage

CI improvements

---

.codecov.yml
test/expected/telemetry.out
test/sql/telemetry.sql

We should really test that this function works, and we're outputting all
the fields we expect. Not testing the actual values as that changes
across installs and runs.
Should also improve our code coverage.

Add telemetry report test

---

.travis.yml

Execute codecov for successful builds only
Don't run codecov for pgindent and license check
This also improves readability of the travis log because codecov output will be in a collapsed section of the output and not part of the main output.

Execute codecov for successful builds only

---

sql/util_internal_table_ddl.sql
test/expected/create_hypertable.out
test/sql/create_hypertable.sql
test/sql/utils/testsupport.sql

Fixes get_create_command to produce a valid create_hypertable
call when the column name is a keyword
Add test.execute_sql helper function to test support functions

Fix time column handling in get_create_command

---

LICENSE
LICENSE-APACHE
NOTICE

Clarify better how source code is split between Apache 2.0 and Timescale
License, to now serve as a reference file to which GitHub will point.  Also
cleanup NOTICE to point to LICENSE files.

Add new top-level licensing information

---

test/pgtest/CMakeLists.txt

This is will not fix testtablespace for remote test instances
but local instances will work

Create directory for postgres tablespace test

---

test/isolation/expected/deadlock_dropchunks_select.out
test/isolation/specs/deadlock_dropchunks_select.spec

Speeds up the test by detecting the deadlock due to the lock timeout instead of the test runner timeout. 
@gayyappan would you look at this? I don't _think_ it changes the semantics of the test, and should be a decent bit faster to run.

Reduce lock timeout on deadlock_dropchunkcs_select test

---

src/guc.c
src/guc.h
src/telemetry/telemetry.c

And guc recording the last time timescaledb-tuned
was run, and telemetry reporting for this guc.
This will tell us how many people actually run
timescaledb-tune.

Add last_tuned guc and telemetry reporting for this

---

appveyor.yml
src/jsonb_utils.c
src/telemetry/telemetry.c
test/expected/telemetry.out
test/postgresql.conf

Adds dummy values so that last_tuned telemetry gets
reported in our tests. Also moves the location of
the telemetry adding code to prevent a segfault.
Should have been part of PR #955.

Add dummy values to test last_tuned telemetry

---

test/pgtest/CMakeLists.txt

The way that ignores were used previously failed with parallel tests.
This fixes that.

Fix pgtest schedule of tests

---

scripts/docker-run-abi-test.sh
scripts/docker-run-tests.sh

We need to ensure we have all the source in order
to build timescaledb. Lacking this breaks the test.

Copy tsl into build directory in smoketest

---

tsl/LICENSE-TIMESCALE

It seems that a merge conflict was not completely cleaned up after
in the Timescale License.

Remove git merge/rebase lines from TSL

---

tsl/src/gapfill/interpolate.c

When compiling against Postgres 9.6 before 9.6.5 TupleDescAttr
is not defined, compat.h defines the macro for versions before 9.6.5

Add include for compat.h to gapfill/interpolate.c

---

test/expected/timestamp.out
test/sql/timestamp.sql

The order specified in some of the timestamp tests did not result
in consistent ordering when a different plan was chosen.

Fix order in timestamp test

---

src/cross_module_fn.c
test/expected/gapfill.out

Show different error hint depending on the license required
to use a feature.

Differentiate between required license in error hints

---

src/chunk.c
test/expected/chunk_utils.out

Improves error message when user improperly inputs an `older_than` parameter that comes before `newer_than`.
Previously, the existing error message was harder to reason with, since it didn't clarify that the specified time period needed to be an overlapping time range when both `older_than` and `newer_than` are used in show_chunks and drop_chunks. This commit clarifies the error message.

Make older_than / newer_than error message user friendly

---

src/bgw/job.c

Currently BGW jobs get guc values but do not necessarily run the assign
hook. This is an issue for the TSL because the TSL is loaded in just
such a hook; if they are never called, TSL functions cannot be used. Fix
this by reloading all the gucs using SerializeGUCState and
RestoreGUCState like in the parallel workers.

Update BGW to run licese guc assign hooks

---

tsl/src/bgw_policy/job.c
tsl/test/expected/bgw_policy.out

Log before and after we run the reorder job on a chunk so that there
is more information in the server logs around when and how reorder
jobs occur.

Log to pg log when running reorder jobs

---

tsl/src/license.c

This shouldn't be needed, but it fixes a spurious warning for those of
us that enable more warnings.

Clean missing braces warning

---

sql/ddl_api.sql
sql/ddl_internal.sql
sql/updates/latest-dev.sql
src/chunk.c
src/chunk.h
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/src/bgw_policy/job.c
tsl/src/license.c

We don't want to do this silently, so that users are
able to debug where their chunks went.
@davidkohn88 should we expose a `verbose` flag for the manual version also?

Log which chunks are dropped by background workers

---

test/pgtest/CMakeLists.txt
test/sql/CMakeLists.txt

The rolenames test seems to be fail quite often in CI, so we ignore
the result from that test for now.

Ignore rolenames pgregress test

---

README.md

Right now, clicking the travis build badge directs the user to the
currently running travis job. Since this is usually a PR, and we gate PR
merges on travis anyway, it's not very useful for determining the health
of the project. This commit switches the link to point at the build
history, which shows the previously run cron jobs; the jobs that the
badge points at anyway.

Point the travis build badge at "history" instead of "current"

---

src/dimension.c
src/dimension.h
tsl/src/bgw_policy/drop_chunks_api.c
tsl/test/expected/bgw_policy.out
tsl/test/sql/bgw_policy.sql

Scheduled drop_chunks works by dropping chunks older than a certain
interval. Since we have no way to calculate what 'now()' is for non-time
dimensions, we currently cannot have a scheduled drop_chunks job that
works with them. Currently this causes an error when the policy attempts
to execute. This commit moves the error, so that it occurs when a user
tries to add the policy in the first place.

Disallow scheduled drop_chunks policies on non-time open dimensions

---

src/bgw/job_stat.c
src/bgw/job_stat.h
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/reorder_api.c
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/bgw_reorder_drop_chunks.sql

To date all our bgw tests run in the normal psql environment. This
commit adds tests that the jobs function correctly when run from actual
background workers. This should catch cases where the background worker
behaves differently than a normal connection.
This PR also contains minor fixes to the reorder job in order to allow it to function in this context:
1. It switches the fast-restart to use the previously scheduled time instead of `now()`. This allows fast-restart to work correctly with the mock scheduler.
3. It uses the default retry interval when the open dimension is not a time type.

 Add tests of scheduled jobs within actual background workers

---

tsl/src/reorder.c
tsl/test/expected/bgw_policy.out
tsl/test/expected/reorder.out

In our workloads we expect that there will never be a case in which an
indexscan based reorder will perform better than a seqscan based one.
In order to prevent pessimization, disable indexscan based reordering.

Only use seqscans for reorder

---

src/bgw/scheduler.c
src/bgw/scheduler.h
src/guc.c
src/guc.h
src/loader/bgw_launcher.c
test/expected/bgw_db_scheduler.out
test/sql/bgw_db_scheduler.sql
test/src/bgw/scheduler_mock.c
tsl/src/bgw_policy/job.c

When receiving a SIGHUP, background workers should reload pg_conf to get
any changed guc values.
Also fix issue where the bgw_scheduler was not properly waiting for
child processes to die before shutting itself down. This should increase
the robustness of bgw_db_scheduler.

Fix signal processing in background workers

---

.travis.yml

The find syntax used by the codecov script is not compatible with
busybox find, installing GNU find makes the codecov script functional
again.

Install findutils in build container

---

.gitignore
src/CMakeLists.txt
src/dimension_vector.c
src/dimension_vector.h
src/guc.c
src/guc.h
src/hypertable_restrict_info.c
src/hypertable_restrict_info.h
src/plan_expand_hypertable.c
src/plan_ordered_append.c
src/plan_ordered_append.h
src/planner.c
src/planner.h
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/expected/plan_ordered_append_results_diff.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_x_diff.out
test/sql/CMakeLists.txt
test/sql/include/append.sql
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql
test/sql/plan_ordered_append.sql.in
test/sql/plan_ordered_append_results_diff.sql

This optimization will replace the MergeAppendPath for queries on
hypertables ordered by the time partitioning column and with a
LIMIT clause with an ordered AppendPath. This optimization will
remove the need for last point queries to access every chunk of
a hypertable.

Add ordered append optimization

---

sql/updates/latest-dev.sql
sql/version.sql
src/telemetry/telemetry.c
src/version.c
src/version.h
test/expected/telemetry.out
test/sql/telemetry.sql

The info gotten from uname is difficult to work with, so read the os
name from /etc/os-release if it's available.

Update telemetry with prettier os info

---

README.md

Small typo -> changing "build" to "built" when discussing Apache-ONLY

Update README for small typo

---

sql/chunk.sql
src/chunk.c
src/extension.c
src/extension.h
src/plan_add_hashagg.c
src/plan_agg_bookend.c
src/plan_expand_hypertable.c
src/utils.c
src/utils.h
test/expected/extension.out
test/expected/plan_expand_hypertable_optimized.out
test/expected/utils.out
test/sql/include/plan_expand_hypertable_chunks_in_query.sql
test/sql/plan_expand_hypertable_optimized.sql

In some cases user might already know what chunks need to be scanned to answer
a particular query. Using `chunks_in` function we can skip calculating chunks
involved in particular query which should also result in better performances.
A simple example:
`SELECT * FROM hypertable WHERE chunks_in(hypertable, ARRAY[1,2])`

Explicit chunk exclusion

---

tsl/src/gapfill/exec.c
tsl/src/gapfill/planner.c

Since we add PostgreSQL CFLAGS to our own CFLAGS on some platforms
using variable declarations in for loops will generate compile
warnings, depending on the CFLAGS PostgreSQL is compiled with.

Remove variable declaration in for loops

---

src/loader/bgw_message_queue.c

`errhint`'s should be full sentences, starting with a capital and ending with a period.

Fix formatting for error message

---

src/CMakeLists.txt
src/build-defs.cmake
tsl/src/build-defs.cmake

This is needed for tools like include-what-you-use to decide
which files should be included with quotes vs carrots.
This is probably more correct anyway as postgres files are
included with carrots in our code.

Mark Postgresql includes in cmake as SYSTEM includes.

---

sql/chunk.sql
src/plan_expand_hypertable.c
test/expected/extension.out
test/expected/plan_expand_hypertable_optimized.out
test/sql/include/plan_expand_hypertable_chunks_in_query.sql

This function needs chunk ids as input which is TimescaleDB internal metadata. Due to that it feels more natural to make this function internal.

Moving chunks_in function to internal catalog

---

sql/gapfill.sql

time_bucket_gapfill used end as argument name which is a sql keyword
and has to be quoted when used, this changes the argument names from
start/end to start/finish.

Change time_bucket_gapfill argument names

---

src/bgw/timer.c

Depending on host hardware, long can be 32 or 64 bits long.
Changing it to int64 or int32 makes the code more portable and helps
avoid issues when running in 32bit systems.

Change long to int64

---

sql/CMakeLists.txt

Without this, we generate multiple rules for the latest script for not-dev versions.

Fix issues with non-dev versions when generating the update scripts

---

src/chunk_dispatch.c
src/chunk_dispatch_state.c
src/chunk_insert_state.c
src/chunk_insert_state.h
src/copy.c
test/expected/upsert.out
test/sql/upsert.sql

Previously we set the mt_existing and onConflictProjInfo slot
descriptors only when the current chunk had a tup_conv_map this
was based on a false assumption that these slot descriptors had the
hypertable's slot descriptor. In fact, since we are reusing these slots
across chunks, the slot descriptor will correspond to the previous
chunk's one. This led to an error if the previous chunk had a
tup_conv_map but the current one did not.
This PR merges the changes from @cevian and @gayyappan

Fix upsert bug with incorrect tuple descriptors

---

src/loader/loader.c

The loader needs to be backwards compatible. Therefore we handle the case where post_load function doesn't exist gracefully.

Fix loader for old versions of timescale

---

src/license_guc.c
src/license_guc.h
tsl/src/init.c
tsl/test/expected/plan_gapfill-10.out
tsl/test/expected/plan_gapfill-11.out
tsl/test/expected/plan_gapfill-9.6.out
tsl/test/isolation/specs/.gitignore
tsl/test/sql/plan_gapfill.sql.in

Parallel workers have an unusual load path, which doesn't behave the
same as other processes. Since we don't have any obvious hooks we can
use to enable loading, and the library load order is already frozen
by the main process, fix this by adding a _PG_init which will enable
the tsl in background workers when needed.

Fix loading the tsl license in parallel workers

---

CMakeLists.txt
tsl/src/gapfill/interpolate.c
tsl/src/reorder.c
tsl/test/isolation/specs/reorder_deadlock.spec
tsl/test/isolation/specs/reorder_vs_insert.spec
tsl/test/isolation/specs/reorder_vs_select.spec
tsl/test/src/test_auto_policy.c
tsl/test/src/test_chunk_stats.c

This change makes code formatting (`pgindent`) cover the TSL test
sources under `tsl/test/src/`. It also addresses some minor formatting
issues with existing sources in other directories.

Make code formatting cover TSL test source code

---

src/loader/loader.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

When background workers are running RENAME DATABASE will not work
because there are still active sessions to that database open.
This stops background workers on RENAME DATABASE so databases can
be renamed without manually stopping background workers.
Fixes #1034

Stop background worker on rename database

---

CHANGELOG.md
src/agg_bookend.c
src/histogram.c

When the sfunc is never called to initialize InternalCmpAggStore
state can be NULL even though PG_ARGISNULL is false, so we check
for that condition here.

Explicitly check  for NULL pointer in ts_bookend_finalfunc

---

.travis.yml

Most of our testing is performed with Debug enabled. This is desired
as it enables more assertions, and helps ensure that our code is
correct. Still, it's good to ensure we're not accidentally depending
on Debug code in Release builds, so run tests in that mode nightly
and before each release.

Add cron a pre-release Release mode testing

---

CHANGELOG.md
tsl/src/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

When time_bucket_gapfill is used with multiple groups
but the query returned no rows we can not generate any
rows in the gapfill node.
Fixes #1046

Fix group handling in time_bucket_gapfill

---

src/chunk_insert_state.c
test/expected/upsert.out
test/sql/upsert.sql

When doing an upsert, we expect to be able to translate a
hypertable index used as an arbiter to a chunk index. But,
it is possible that the corresponding chunk index has been dropped.
Previously this resulted in a postgres generated error like
"unexpected failure to find arbiter index". We now handle
this more gracefully.

Fix displayed error when an arbiter index is missing.

---

src/process_utility.c
test/expected/cluster.out

This prevents the cluster index from being deleted or altered while in
middle of the CLUSTER. (currently this causes a cache lookup failure)
While this does not cause the CLUSTER to succeed, it at least changes the error to `ERROR:  index "foo_index" for table "foo" does not exist`.

Add session locks to CLUSTER

---

scripts/clang_format_all.sh

The script for running clang-format on the source code now properly
excludes hidden directories and CMake directories from the source code
scan. Including these directories may otherwise break clang-format
because hidden directories are often used for IDE/tools caches (e.g.,
`cquery`) where the cache files have the same ending as the source
code.

Exclude hidden and CMake directories when formatting code

---

src/hypertable_insert.c
src/hypertable_insert.h
src/planner.c
test/expected/upsert.out
test/sql/upsert.sql

Previously, hypertable insert tlists were only fixed
for the top-level plan. We also need to fix the tlist
for hypertable inserts that appear inside ctes

Fix tlist on hypertable inserts inside CTEs

---

src/chunk_dispatch_state.c

These asserts check that the mtstate->mt_conflproj is the same
slot as in the result rel info on conflict projection and that
the slot descriptor is set correctly.

Add additional asserts to upserts

---

src/chunk_dispatch.c
src/chunk_dispatch.h
src/chunk_dispatch_state.c
src/copy.c

This commit changes the code to only perform cis switch actions
when the cis changes instead of on every tuple. Several recent
bug fix changes have increase the amount of work that needs to be
done in switch actions and so this commit is a performance improvement
that avoids doing unnecessary work.

Only perform chunk insert state switch actions when necessary

---

src/dimension.c
src/dimension.h
src/hypertable_restrict_info.c

The existing constraint exclusion code creates issues on 32bit processors when constraint given
in a query does not exactly match the type of the table dimension but could be promoted to it.
For example, if hyper_w_space has bigint time type, the following query will pass 10 as
Const variable of type int32 (that has Oid INT4OID).
SELECT * FROM hyper_w_space WHERE time < 10
If this type info is not propagated correctly, later Const variable type is inferred as bigint (int64) and
DatumGetInt64 is used to get its value. In 64 bit systems, DatumGetInt32 and DatumGetInt64 are identical and so there
are no issues, however this makes a difference in 32 bit systems as there 32 bit values are passed by value while
64 bit values are passed by reference.

Fix chunk exclusion constraint type inference

---

src/sort_transform.c
test/expected/sort_optimization.out
test/sql/CMakeLists.txt
test/sql/sort_optimization.sql

The sort transform optimization to enable index usage are only
safe transformations when the modified PathKey is either the last
member of pathkeys or the only member.

Fix sort_transform optimization

---

.travis.yml
scripts/suppressions/Readme.md
scripts/suppressions/suppr_asan.txt
scripts/suppressions/suppr_leak.txt
scripts/suppressions/suppr_ub.txt
scripts/test_sanitizers.sh
src/histogram.c
src/net/http_request.c
test/src/bgw/log.c

The first commit fixes three issues:
1. It is technically UB to pass in NULL as the data argument to appendBinaryStringInfo
We fix this by providing a wrapper function which checks if len == 0 before calling
appendBinaryStringInfo.
2. It is technically UB to pass in NULL as any argument for memcopy, we use a similar
fix as in 1.
3. The Datum array in histogram was misaligned; Datums require 8 byte alignment, while
the data in a bytea is only guaranteed to be aligned to 4. We fix this by switching
to a better-typed internal histogram type. This will use approximately double the
memory for serialization, but is much simpler to read, and more morally correct.
The second PR adds sanitizer run script, and updates travis to run it in our nightly builds. Valgrind has been very slow and unstable, …

Fix issues discovered by sanitizers and add santizer based cron tests

---

.editorconfig

Our code uses a tabwidth = 4. By default, github displays everything
with tabwidth = 8. But github respects .editorconfig files. So
this commit adds the appropriate .editorconfig.

Add .editorconfig for better github display

---

tsl/src/gapfill/exec.c

We cannot access the column array in the increment; at that point we do
not yet know if the access is in bounds. Fixed by moving it to the
condition

Fix off by 1 error in gapfill/exec.c:foreach_column

---

tsl/src/gapfill/planner.c

Changing paths in-place causes issues when add_paths realizes the old
path is no longer optimal, and decides to free it. Instead duplicate
the path list, and use add_path ourselves to add our new gapfill paths

Fix use-after-free in gapfill

---

scripts/test_sanitizers.sh
test/sql/CMakeLists.txt

With the forthcoming new sanitizer image running tests in parallel
causes machines to run out of resources, and fail tests spuriously
This commit forces test_sanitizers.sh to run tests sequentially to
prevent this.

Force sanitizer tests to run serially

---

CHANGELOG.md
src/constraint_aware_append.c
src/constraint_aware_append.h
src/init.c
src/planner.c
test/expected/append.out
test/expected/append_x_diff.out
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/append.sql
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql
test/sql/parallel.sql.in

Constraint aware append used some planner data structures in the
executor which cannot be serialized so they will not be available
in parallel workers, this patch refactors this and marks the
constraint aware append node as parallel safe when the subpath is
parallel safe. The additional function executions in the test output
are because the constify is run once per chunk now, previously it run
only once and the result was copied to the restrictinfo of every chunk
and then adjusted for the chunk, but since the adjustment for the chunk
has to happen in the planner because it needs access to appendrelinfo
we now create per chunk restrictinfo in the planner and constify each of
these in the executor.
On PostgreSQL < 12 now() is not parallel safe
and using now() in a query will prevent …

Make constraint aware append parallel safe

---

CHANGELOG.md
src/planner.c

When using timescaledb with extensions that define their own
planner_hook the targetlist adjustments required for hypertable
inserts to work would never run. This patch fixes compatibility
with extensions that define their own planner_hook.
Fixes #1083

Fix compatibility with extensions that define planner_hook

---

CHANGELOG.md
src/chunk_dispatch_state.c
test/expected/upsert.out
test/sql/upsert.sql

A prepared statement or function plan can be turned into a generic plan after a couple executions. When this happens the last plan that run through plan creation gets reused so we need to revert any modifications we did to that plan so reusing it is safe.
Fixes #1086

Fix ON CONFLICT when using prepared statements and functions

---

test/expected/alternate_users-10.out
test/expected/alternate_users-11.out
test/expected/alternate_users-9.6.out
test/expected/ddl.out
test/expected/ddl_single.out
test/sql/include/ddl_ops_1.sql

The ddl_ops test queries were using a non-unique ORDER BY clause.
To improve test stability this patch adds explicit unique ordering.

Add unique ORDER BY to ddl_ops test

---

CHANGELOG.md
src/loader/loader.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql
test/sql/include/bgw_launcher_utils.sql
test/sql/include/bgw_launcher_utils_cleanup.sql

Alter database set tablespace will error out if there are still
active sessions to the database so we need to stop background workers
to not prevent the command from succeeding.
Fixes #1078

Stop background worker on ALTER DATABASE SET TABLESPACE and CREATE DATABASE WITH TEMPLATE

---

appveyor.yml
test/expected/agg_bookends_optimized-10.out
test/expected/agg_bookends_optimized-9.6.out
test/expected/append.out
test/expected/append_unoptimized.out
test/expected/append_x_diff.out
test/expected/ddl_alter_column.out
test/expected/index.out
test/expected/plan_expand_hypertable_optimized-11.out
test/expected/rowsecurity-10.out
test/expected/rowsecurity-11.out
test/expected/rowsecurity-9.6.out
test/expected/sql_query.out
test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/expected/sql_query_results_x_diff.out
test/pgtest.conf
test/pgtest/CMakeLists.txt
test/postgresql.conf
test/sql/include/append.sql
test/sql/rowsecurity-9.6.sql
test/test-defs.cmake
tsl/test/expected/tsl_tables.out
tsl/test/sql/tsl_tables.sql

Set random_page_cost to 1.0 to produce more reasonable plans.
This is similar to what timescaledb-tune would set.

Set random_page_cost to 1.0 for tests

---

CHANGELOG.md
src/plan_ordered_append.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql

Ordered append used to only consider startup cost of the first child.
This patch changes the cost for ordered append to use the normal postgresql append cost calculation
Fixes #1090

Adjust ordered append plan cost

---

src/chunk_adaptive.c
src/chunk_adaptive.h
src/dimension.h
src/hypertable.c
src/hypertable.h

This PR create a pure-C interface for create_hypertable. This
makes calling this function within C much easier. It also does
some interface cleanup. Most notably, it now disallows
chunk_sizing_func to be NULL since it has a NOT NULL constraint
on the hypertable catalog table.

Create a non-SQL C interface for create_hypertable

---

test/expected/chunk_utils.out
test/sql/chunk_utils.sql

The chunk_utils test sets `client_min_messages` to `FATAL` in order to
mute some error messages, which differ between PostgreSQL versions and
would otherwise cause test failures on some platforms. However,
according to the PostgreSQL documentation going back to at least 9.6,
this is not a valid log level for this configuration
parameter, although it has been allowed for legacy reasons. However,
starting with PostgreSQL 11.2, `FATAL` is silently turned into `ERROR`
and will cause the test to output the error anyway and thus fail.
This change removes the muting altogether, because the error that is
output is actually a TimescaleDB error and not a PostgreSQL error. The
generated error output probably changed at some point and therefore
this muting is no longer necessary.

Fix invalid client_min_messages level in chunk_utils test

---

src/dimension.c
src/dimension.h
src/hypertable.c

This PR adds a create function interface for dimension info since we
will want to create these objects in more places in the future. This
creates a more stable API then just setting struct elements directly.

Add create function for dimension info

---

CHANGELOG.md
src/plan_ordered_append.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql
test/sql/plan_ordered_append.sql.in
test/sql/plan_ordered_append_results_diff.sql

The comparison to check whether the column references
matches the time dimension column assumed that the reference
would be to the hypertable which might not be true for JOINs.
This patch adds a check to make sure the reference in the
ORDER BY is actually a reference to the hypertable before
checking the column is the time dimension.
Fixes #1114

Fix ordered append optimization for join queries

---

test/expected/relocate_extension.out
test/sql/relocate_extension.sql

The relocate_extension test used a relative time in the drop_chunks
call which makes the test always fail after a certain time. This
patch changes the test to use absolute time.

Fix relocate_extension test

---

CHANGELOG.md
tsl/src/gapfill/exec.c
tsl/src/gapfill/planner.c
tsl/test/expected/gapfill.out
tsl/test/expected/plan_gapfill-10.out
tsl/test/expected/plan_gapfill-11.out
tsl/test/expected/plan_gapfill-9.6.out
tsl/test/sql/gapfill.sql

Pass original arguments to time_bucket_gapfill in custom_private
so it is in the proper MemoryContext to work with prepared
statements.

Fix gapfill with prepared statements

---

test/pg_isolation_regress.sh
test/pg_regress.sh

Now TEST_SCHEDULER schedules groups of tests parallelly and sends them
as space separated lists. The PR makes sure this list is traversed
correctly when IGNORE option of installcheck is passed.

Fix installcheck IGNORE on grouped parallel tests

---

sql/ddl_triggers.sql
src/cross_module_fn.c
src/cross_module_fn.h
src/process_utility.c
src/process_utility.h
test/expected/index.out
test/sql/index.sql
tsl/test/expected/ddl_hook.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/ddl_hook.sql
tsl/test/src/CMakeLists.txt
tsl/test/src/test_ddl_hook.c

This patch does refactoring necessary to support execution of DDL commands on remote servers.
Basically it extends cross module api with `ddl_command_start` function and pass `ProcessUtilityArgs` context to it. Additionally it shares hypertables cache pin, which now happens before `process_ddl_command_start` function call and released afterwards.
New variables `hypertables_list`, `subcmd_list` added to `ProcessUtilityArgs`. These fields are used to keep a list of found hypertables during Utility/DDL statement parsing. This information will be used to distinct distributed hypertables and forward DDL commands to any remote servers associated with them.
Added functionaly and test to track DROP INDEX call and ensure it is used against only one hypertable at a time.

Track hypertables used during process utility hook execution

---

test/expected/append.out
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/expected/plan_hashagg-10.out
test/expected/plan_hashagg-11.out
test/expected/plan_hashagg-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/append.sql
test/sql/plan_expand_hypertable.sql.in
test/sql/plan_hashagg.sql.in
test/sql/plan_ordered_append.sql.in

A recently introduced change broke some tests on BSD / Mac OS X due
difference in output of the `wc` command, which is used to compare the
number of lines in different output files. The tests that are affected
are those that compare outputs of specific optimizations as they are
turned on and off.
This change removes the `wc` command and output from those tests as it
seems sufficient to rely on `diff`. In other words, if the number of
lines would be different in the output, then diff would also fail.

Fix diff tests on BSD / Mac OS X

---

test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/parallel.sql.in
tsl/src/gapfill/exec.c
tsl/src/gapfill/exec.h
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

Any column that does not have an aggregation function and is not
an explicit GROUP BY column has to be derived from a GROUP BY
column so we treat those similar to GROUP BY columns for gapfill
purposes.

Fix column handling for columns derived from GROUP BY columns

---

src/chunk.c
src/chunk_adaptive.c
src/dimension.c
src/hypertable_restrict_info.c
src/plan_add_hashagg.c
src/utils.c
src/utils.h
test/expected/c_unit_tests.out
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/.gitignore
test/sql/CMakeLists.txt
test/sql/c_unit_tests.sql
test/sql/parallel.sql.in
test/src/CMakeLists.txt
test/src/test_time_to_internal.c

We find ourselves needing to store intervals (specifically time_bucket widths) in
upcoming PRs, so this commit adds that functionality, along with tests that we
perform the conversion in a sensible, round-trip-able, manner.
The commit adds a single SQL file, c_unit_tests.sql, to be the driver for all such
pure-C unit tests. Since the tests run quickly, and there is very little work to
be done at the SQL level, it does not seem like each group of such tests requires
their own SQL file.
This commit also updates the `test/sql/.gitignore`, as some generated files were
missing.
Going to request @davidkohn88 do the initial review as @cevian is out right, now, so @cevian only needs to do the final review once he gets back.

Add interval to internal conversions, and tests for both this and time conversions

---

src/CMakeLists.txt
src/chunk_constraint.c
src/scan_iterator.c
src/scan_iterator.h
src/scanner.c
src/scanner.h
src/utils.h
src/with_clause_parser.h

This PR adds a foreach-style interface to our catalog scanner code.
It is split into 2 commits
1) Adds the interface to scanner (see commit message for reasons behind adding this interface)
2) Refactors the chunk_constraint code to use the new interface. This commit is meant to showcase best-practices for the usage of the new interface (as well as cleanup that code).
See the detailed info in each of the above commit's messages for more info.
Please review this PR not only for correctness but also for the style of the resulting usage code. Can we simplify it some more?

Add foreach-style interface to scanner

---

scripts/test_sanitizers.sh

Change test_sanitizers.sh to always run regresscheck-t even when
regresscheck fails and print regresscheck-t diff on errors.

Print regresscheck-t test diff after sanitizer run

---

scripts/suppressions/suppr_ub.txt

See https://api.travis-ci.org/v3/job/513807308/log.txt for an example failure.

Add array_unnest to alignment supressions it looks like trigger lookup triggers it

---

test/expected/sql_query_results_optimized.out
test/expected/sql_query_results_unoptimized.out
test/expected/sql_query_results_x_diff.out
test/sql/include/sql_query_results.sql

Using ANALYZE without a specific table will generate a warning
in the postgres log for every table the user does not have
permissions for. This leads to a lot of unnecessary noise
in the travis logs. This patch removes ANALYZE without table
and replaces it with calls that target the specific tables
used in this test case.

Remove unspecific ANALYZE from sql_query_results test

---

CHANGELOG.md
src/constraint_aware_append.c
test/expected/append.out
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/append_load.sql
test/sql/include/append_query.sql
test/sql/include/plan_expand_hypertable_load.sql
test/sql/include/plan_expand_hypertable_query.sql
test/sql/parallel.sql.in

Cross datatype comparisons between DATE/TIMESTAMP/TIMESTAMPTZ
are not immutable which prevents their usage for chunk exclusion.
Unfortunately estimate_expression_value will not estimate those
expressions which makes them unusable for execution time chunk
exclusion with constraint aware append.
To circumvent this we inject casts and use an operator
with the same datatype on both sides when building the
restrictinfo. This will allows estimate_expression_value
to evaluate those expressions and makes them accessible for
execution chunk exclusion with constraint aware append.
The following transformations are done:
TIMESTAMP OP TIMESTAMPTZ => TIMESTAMP OP (TIMESTAMPTZ::TIMESTAMP)
TIMESTAMPTZ OP DATE => TIMESTAMPTZ OP (DATE::TIMESTAMPTZ)
No transformation is required for TIMESTAMP OP DATE …

Add support for cross datatype chunk exclusion for time types

---

CHANGELOG.md
src/plan_ordered_append.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_load.sql

The cost for ordered append was changed recently to let postgres
do normal append cost calculation. Unfortunately that cost is rather
pessimistic and lead to that plan not being chosen in situations where
it should be. This patch adjusts the cost calculation to only
include child node cost until limit is hit.
This also marks the append node to no longer be parallel safe which
was not correct before because the append node cannot be parallelized
in ordered append plans.
Fixes #1124

Adjust ordered append path cost

---

scripts/test_sanitizers.sh

Only print postgres log and regression diff for the instance
that actually failed for regresscheck and regresscheck-t
respectively.

Improve information displayed on sanitizer test failure

---

.travis.yml
CMakeLists.txt
scripts/githooks/commit_msg.py
scripts/githooks/commit_msg_tests.py

Our coding guidelines recommend following "The seven rules of a great
Git commit message" by Chris Beams:
https://chris.beams.io/posts/git-commit/
This change adds a Git commit hook that validates all Git commit
messages according to these rules (at least to the extent possible).
Currently, the hook simply prints a warning and a list of violations
in case of a non-conforming Git commit message. The commit is
otherwise accepted. This could be changed to entirely fail the commit,
or, via another hook, fail to push any code that is non-conformant.
The hook will be installed on a CMake run, unless a hook already
exists.

Add a Git commit hook to validate commit messages

---

src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_chunks_in_query.sql

Building RestrictInfo for plan time chunk exclusion only collected
expressions in WHERE clause but not constraints present in ON clause
of JOINs. This patch adds support for collecting constraints from
JOIN conditions.
This patch also changes the expression_tree_mutator to an
expression_tree_walker because the modifications we do do not require
using a mutator.

Refactor collecting RestrictInfo

---

scripts/githooks/commit_msg.py

The commit message template may include the actual diff to be
committed separated with a special scissors. This patch adds
support for the scissors line to the commit hook otherwise
the diff content may trigger any of the rules.

Stop processing commit message on scissors line

---

src/guc.c

When the initial value for max_open_chunks_per_insert is calculated
it may be bigger then the max for high values of work_mem. This
patch limits the initial value to the max of the GUC.

Limit initial max_open_chunks_per_insert to PG_INT16_MAX

---

test/runner.sh

Any output or side-effects that a (private) .psqlrc generates should not
cause test failures. By excluding the start-up file we make sure we get
consistent output for everyone.

Ignore .psqlrc start-up file when running tests

---

appveyor.yml
src/guc.c
src/guc.h
src/telemetry/metadata.c
src/telemetry/metadata.h
src/telemetry/telemetry.c
test/expected/telemetry.out
test/postgresql.conf
test/sql/telemetry.sql

Add all entries from _timescaledb_catalog.installation_metadata
to the telemetry report under the key `meta`.

Add content of installation_metadata to telemetry

---

src/constraint_aware_append.c
src/plan_expand_hypertable.c
src/utils.c
src/utils.h
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_load.sql
test/sql/include/plan_expand_hypertable_query.sql

This patch adds support for chunk exclusion for time_bucket
expressions in the WHERE clause. The following transformation
is done when building RestrictInfo:
Transform time_bucket calls of the following form in WHERE clause:
time_bucket(width, column) OP value
Since time_bucket always returns the lower bound of the bucket
for lower bound comparisons the width is not relevant and the
following transformation can be applied:
time_bucket(width, column) > value
column > value
Example with values:
time_bucket(10, column) > 109
column > 109
For upper bound comparisons width needs to be taken into account
and we need to extend the upper bound by width to capture all
possible values.
time_bucket(width, column) < value
column < value + width
Example with values:
time_bucket(10, column) < 100 …

Add time_bucket support to chunk exclusion

---

src/license_guc.c
test/expected/edition.out
test/sql/edition.sql

Right now the only way to enable an ApacheOnly license is the hardcoded
default in the ApacheOnly binary. This commit allows users to specify
said license in the postgres.conf when running an ApacheOnly binary.
While this doesn't add any new capabilities, users who wish to be sure
they only use the ApacheOnly binary can specify the license in the conf
and be sure that of they accidentally run another binary they will get
an error.

Fix postgres.conf ApacheOnly license

---

tsl/src/partialize_finalize.c
tsl/test/expected/partialize_finalize.out
tsl/test/sql/partialize_finalize.sql

When finalize_agg is called as a window function AggCheckCallContext
will return true but the context will not be an AggState but a
WindowAggState, this patch checks for AggState explicitly and errors
when the function is called in window function context.

Check for window agg context in finalize_agg

---

sql/CMakeLists.txt
sql/edition.sql
sql/restoring.sql
test/expected/bgw_launcher.out
test/expected/edition.out
test/expected/extension.out
test/expected/pg_dump.out
test/sql/bgw_launcher.sql
test/sql/edition.sql
test/sql/pg_dump.sql

These functions improve usability and take all the proper steps to
set restoring on/off (and stop/start background workers in the process)
and to set the license key via a function rather than a guc modification.

Add functions for turning restoring on/off and setting license key

---

sql/chunk.sql
src/chunk.c
src/chunk_dispatch.c
src/hypertable.c
src/hypertable.h

ts_chunk_for_tuple should use the chunk cache.
ts_chunk_for_tuple should be marked stable.
These fixes markedly improve performance.

Fix ts_chunk_for_tuple

---

src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out

When doing a time_bucket comparison in the WHERE clause a
transformed expression was used to enable chunk exclusion for
those queries. This patch also adds the transformed expression
to the list of quals so that expression can be used as an index
condition.

Add transformed time_bucket comparison to quals

---

src/plan_ordered_append.c
test/expected/plan_ordered_append-11.out
test/expected/sql_query_results_optimized-11.out
test/expected/sql_query_results_x_diff-11.out

Merging the partitionwise aggregation patch broke ordered append
for PG11, this patch fixes ordered append for PG11.
We report the number of rows of the included chunks in the path
because the limit cost calculation will factor this into its cost
calculation.

Fix ordered append for PG11

---

src/plan_expand_hypertable.c
src/plan_ordered_append.c
test/expected/agg_bookends_optimized-10.out
test/expected/agg_bookends_optimized-11.out
test/expected/agg_bookends_optimized-9.6.out
test/expected/append.out
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out

This patch removes the restrictions for the ordered append
optimization to require a LIMIT clause. The other restrictions are
still in place, namely the ORDER BY clause needs to reference
the time dimension and the hypertable can only have a single
dimension.
The ordered append plans are preferable to the merge append plans
that would be used otherwise in this situation because they dont
need to resort data from individual chunks.

Remove LIMIT clause restriction from ordered append

---

src/hypertable_restrict_info.c
src/planner.c
src/utils.c
src/utils.h
test/expected/insert.out
test/expected/insert_many-10.out
test/expected/insert_many-11.out
test/expected/insert_many-9.6.out
test/expected/rowsecurity-10.out
test/expected/rowsecurity-9.6.out
test/sql/.gitignore
test/sql/CMakeLists.txt
test/sql/insert.sql
test/sql/insert_many.sql.in

Before this PR only SELECTs would be optimized to exclude unneeded
chunks by our planner. This PR enables such optimizations on SELECTs
found within an INSERT as well. This should speed up commands of the
form
INSERT INTO <hypertable> (SELECT ... FROM <hyepertable> WHERE ...)
We would like to enable this for all commands, but currently DELETE and
UPDATE can not handle them, and cause errors when the optimizations are
enabled.
This commit also fixes an issue that would occur if we tried to exclude
chunks based off of infinite time values.

Enable optimizing SELECTs within INSERTs

---

src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_query.sql

The expression generated when transforming time_bucket comparison
in qual can overflow leading to postgres throwing an error for an
otherwise valid query. This patch catches any errors when evaluating
the expressions and skips adding the transformation if an error
is thrown.

Improve overflow handling in time_bucket transformation

---

src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_query.sql

Change the time_bucket chunk exclusion to not use expressions
to construct the upper boundary but instead generate a Const
with the upper boundary. The previous approach with using expressions
made it harder to check cleanly for the existance of overflows
cause even though we could catch the error we would have a
catalog cache leak in the error path.

Refactor time_bucket chunk exclusion

---

src/process_utility.c

The address variable in process_create_trigger_start is only used
in an assert in debug builds so compiler will warn about this
variable in non-debug builds. This patch sets the unused attribute
for the variable to silence the warning.

Fix release build warning

---

scripts/test_sanitizers.sh
tsl/test/sql/CMakeLists.txt

We were not building timescaledb with debug enabled in the sanitizer
tests, causing tests which needed debug symbols to fail. This commit
changes the sanitizer tests to include such symbols. We still enable
optimizations, as that results in more realistic build environment for
memory tests.
This commit also ensures some tests which should only be run in debug
builds are in fact only run in debug builds.

Fix sanitizer and release tests [Merge into 1.3.x]

---

CHANGELOG.md
sql/chunk.sql
src/chunk.c
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/src/continuous_aggs/create.c

We replace chunk_for_tuple with chunk_id_from_relid for getting
chunk id fields when materializing continuous aggs. The old
function required passing in the entire row. This was very slow
because a lot of data was passed around at execution time.
The new function just uses the internal `tableoid` attribute to
convert the table relid to a chunk_id. This is much more efficient.
We also add memoization to the new function because it is most often
called consecutively for the same chunk.

Optimize getting the chunk_id in continuous aggs

---

src/continuous_agg.c
src/continuous_agg.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/options.c
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_errors.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/sql/continuous_aggs.sql
tsl/test/sql/continuous_aggs_errors.sql

Add indexes for materialization table created by continuous aggregates.
This behavior can be turned on/off by using timescaledb.create_groupcol_index parameter
of the WITH clause when the continuous agg is created.

Add default index for continuous aggregates

---

CHANGELOG.md
sql/bgw_scheduler.sql
sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/views.sql
src/bgw_policy/drop_chunks.c
src/catalog.c
src/catalog.h
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/job.c
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/tsl_tables.out
tsl/test/sql/bgw_reorder_drop_chunks.sql
tsl/test/sql/tsl_tables.sql

Before this PR, cascade was unconditionally set to true, as stored if the pointer to the inputted form data was non-null instead of the value stored within it. This PR changes that, so the intended setting for cascade is stored instead.
This PR also adds a `cascade_to_materializations` flag to the scheduled version of drop_chunks that behaves much like the one from manual `drop_chunks`: if a hypertable that has a continuous aggregate tries to drop chunks, and this flag is not set, the chunks will not be dropped

 Fix cascade in scheduled drop chunks, and allow scheduled drop_chunks to cascade to aggs

---

CHANGELOG.md
src/chunk_dispatch_state.c
src/hypertable_insert.c
test/expected/upsert.out
test/sql/upsert.sql

When doing upsert with prepared statement the code to restore
arbiter_indexes would not trigger when an error occurred on the
INSERT leading to a segfault on the next EXECUTE of the prepared
statement.
Fixes #1165

Fix UPSERT with prepared statements

---

test/expected/telemetry.out
tsl/src/continuous_aggs/create.c
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_errors.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/expected/continuous_aggs_watermark.out

Add a not-null constraint to the time column on the materialization
table automatically. This suppresses the superfluous notices which
happens when creating continuous aggregates (and don't tell you much).

Suppress not-null notice when creating cont aggs

---

tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/sql/continuous_aggs.sql
tsl/test/sql/continuous_aggs_ddl.sql.in

This commit change the name given to group columns in the materialized
tables to make them more intuitive for the user. The goal was to make
the column names the same as the column names in the view. The main
change was to change time_partitioning_col to be the same as the
view. "time_partition_col" is only used as the default when there is
no alias.
This commit also changes the assignment of the view aliases to the
target entries to occur much earlier in the create process.

Make cont aggs group column names more intuitive

---

src/bgw_policy/drop_chunks.c
src/bgw_policy/drop_chunks.h
src/bgw_policy/reorder.c
src/bgw_policy/reorder.h
src/telemetry/telemetry.c
test/expected/telemetry.out
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/sql/bgw_reorder_drop_chunks.sql

The commit will add telemetry for the number of drop_chunks and
reorder policies in the database. This will allow us to see
how much these features are used.

Add telemetry for policies: drop_chunk & reorder

---

tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs.out
tsl/test/sql/continuous_aggs.sql

The partial view should always project the time_bucket expression related
column as this is a special column for the materialization table. The partial
view failed to project it when the user query's SELECT targetlist did not
contain the time_bucket expression. The materialization fails in this
scenario.

Fix partial view targetlist for continuous aggregates

---

src/process_utility.c
test/expected/constraint.out
test/sql/constraint.sql

Hi,
I've got a strange situation. When I perform a DDL on a hypertable with adding
a column and an invalid check constraing, at the validation time it crashes. My
investigation resulted in this small change.
Check constraints are propagated to child chunks by default, but they're
missing from _timescaledb_catalog.chunk_constraint table. It can lead to a
situation, when such a constraint will be added as not valid, and then at
validation time validate_hypertable_constraint will construct a chunk_cmd with
a NULL name (since it was not there and
ts_chunk_constraint_get_name_from_hypertable_constraint returns NULL), what
eventually leads to a crash.
I haven't fixed any tests tests (looks like they're broken just because more
constraints are registered), because I would like to get a …

Handle NULL in a check constraint name

---

test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql

This patch adds tests for hypertables with indexes not on all chunks
and chunks with removed columns to the ordered append tests.

Add more ordered append tests

---

CHANGELOG.md
tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_errors.out
tsl/test/sql/continuous_aggs_errors.sql

When explicit JOIN syntax is used the from list will contain a
JoinExpr instead of a list of RangeTblRef which was not detected
properly by cagg_validate_query. This patch adds a check for
RangeTblRef to the validation code.

Fix detecting JOINs for continuous aggs

---

CHANGELOG.md
tsl/src/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

When using prepared statements or functions the arguments are turned
into Params when the plan is changed into a generic plan. This patch
allows Params as time_bucket_gapfill arguments so it can be used
in functions and prepared statements with variable time_bucket_gapfill
arguments.
Fixes #1231

Allow Param as time_bucket_gapfill arguments

---

test/expected/copy.out
test/expected/delete.out
test/expected/insert.out
test/expected/pg_dump.out
test/sql/copy.sql
test/sql/delete.sql
test/sql/insert.sql
test/sql/pg_dump.sql

Some of the ORDER BY clauses did not produce a unique order.
This patch fixes those queries to make the test results consistent.

Add missing ORDER BY to test query

---

src/plan_partialize.h

Code checking website lgtm.com flagged this as an alert. As far as
I can tell this is the only header file missing the guard.

Add missing header guard

---

src/process_utility.c

We prevent REFRESHing continuous aggregates within a transaction block
since we COMMIT and start our own transactions during this operation,
making it inherently non-transactional. This commit ensures we only
prevent REFRESHing continuous aggregates, and not REFRESH on other
materialized views.

Stop preventing REFRESH in transaction blocks

---

.travis.yml
test/sql/CMakeLists.txt

Travis did not actually run the release and apache only tests
with the apropriate build flags so they were identical to the
normal debug runs. This patch fixes passing the build flags
and also adjusts regresscheck to not run edition.sql
when compiled as apache only because it tests functionality
not available under this license.
Fixes #1241

Fix release and apache only tests

---

src/plan_expand_hypertable.c

This change makes the dummy partitioning info that we use for hooking
into the partitionwise planning code conform with the macro
`IS_PARTITIONED_REL()`. PG 11.3 relies more heavily on the use of this
macro to decide how to plan a relation and, since our dummy
partitioning info wasn't compliant with the macro, partitionwise
aggregates were therefore never planned.

Fix partitionwise aggregates on PG 11.3

---

src/utils.c
test/src/test_time_to_internal.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/materialize.c
tsl/test/src/test_continuous_aggs.c

int64 should be passed to functions that take a Datum parameter using Int64GetDatum.
Depending on the platform, postgres either passes int64 by value or allocs a pointer
to hold this value.
Without this change, we get SEGV on raspberry pi.

Pass int64 using Int64GetDatum when a Datum is required

---

.travis.yml
test/expected/telemetry.out
test/expected/telemetry_community.out
test/sql/CMakeLists.txt
test/sql/telemetry.sql
test/sql/telemetry_community.sql

The current telemetry test fails in ApacheOnly mode because it uses
community functions. The PR separates out the community from the
apache only testing and add a telemetry_community test that only
runs if not in ApacheOnly mode.
Also adjust the travis file to print telemetry output for the
telemetry test run without openssl.

Fix telemetry test

---

scripts/docker-run-abi-test.sh
scripts/docker_postgres_snapshot/Dockerfile

Previously the compile image for the ABI tests was based on a different
postgres image than the run image (e.g. 10-alpine vs 10.2-alpine). This
created dependency problems between different version of ssl packages
that may be available under different alpine versions.
We fix this by forcing the run image to be based off of the same image
as the compile version.

Run ABI tests on consistent alpine versions

---

src/chunk_append/chunk_append.c
src/chunk_append/chunk_append.h
src/plan_expand_hypertable.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_query.sql

When doing a JOIN with a hypertable ordered append required the
ORDER BY clause to have the time partitioning column as first
expression. This patch loosens that restriction.
If the ORDER BY clause of a query does not reference our hypertable
but has an equality condition on the time partitioning column
of our hypertable we will do an ordered append because
it allows the planner to skip the Sort step for MergeJoin.

Add ordered append support for MergeJoin

---

src/planner_import.c
test/expected/rowsecurity-10.out
test/sql/rowsecurity-10.sql

In https://github.com/postgres/postgres/commit/05eb923eae46c1698088d555ae590a73d4fc7070 Postgres fixed PARAM_EXEC handling which got backported to 9.6.12, 10.7 and 11.2. To allow TimescaleDB builds built on older versions to work with the latest PG version we need to backport some of the functions added in this commit.

Fix compilation errors

---

src/chunk_append/chunk_append.c
src/hypertable_restrict_info.c
src/plan_expand_hypertable.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_load.sql
test/sql/include/plan_ordered_append_query.sql

The initial support for space partitions for ordered append
only support 1 space dimension. This patch removes that restriction
and supports an arbitrary amount of space partitions.

Remove space partition restriction from ordered append

---

.travis.yml

To make it easier to diagnose problems that only occur in CI it is
useful to have the postgres logs in addition to having the test
diffs. This patch adds all the postgres logs and also removes
the hardcoded locations for the regression diffs and uses find to
locate them instead.

Output postmaster.log on travis failure

---

src/catalog.c
src/chunk_adaptive.c
src/chunk_append/planner.c
src/chunk_append/transform.c
src/chunk_insert_state.c
src/hypertable_insert.c
src/hypertable_restrict_info.c
src/plan_expand_hypertable.c
src/planner.c
src/scanner.c
src/scanner.h

Hi,
Remove a parameter hides a global variable warning and unnecessary  includes conflicting with PG12.
Regards
Didier

Trivial Cleanup

---

CHANGELOG.md
src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_query.sql

Using ON clause quals for constraint exclusion is only safe for
INNER JOINs for LEFT/RIGHT JOIN only quals referencing the appropriate
relation may be used for constraint exclusion.

Fix constraint exclusion for OUTER JOIN

---

CHANGELOG.md
src/plan_expand_hypertable.c
test/expected/delete.out
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/expected/update.out
test/sql/include/plan_expand_hypertable_load.sql
test/sql/include/plan_expand_hypertable_query.sql

When a hypertable is joined on any column with equality references
another tables all constraints that reference the same column will be
propagated to the hypertable.

Propagate quals to joined hypertables

---

src/constraint_aware_append.c

ConstraintAwareAppend removes Result node children from the plan
because usually Result nodes are injected to do projection on top
of nodes that cannot project themselves. ConstraintAwareAppend can
do this projection instead. The Result node must not be removed
when the Result node has a one-time filter though.

Do not remove Result nodes with one-time filter

---

src/chunk_append/exec.c
test/expected/alternate_users-10.out
test/expected/alternate_users-11.out
test/expected/alternate_users-9.6.out
test/expected/ddl.out
test/expected/ddl_alter_column.out
test/expected/ddl_single.out
test/expected/drop_rename_hypertable.out
test/expected/index.out
test/expected/insert.out
test/expected/insert_single.out
test/expected/multi_transaction_index.out
test/expected/partitioning.out
test/expected/pg_dump.out
test/expected/plain.out
test/expected/reindex.out
test/sql/utils/testsupport.sql
tsl/test/expected/ddl_hook.out

This PR contains two commits:
1. Fix column name in show_columns
2. Fix compiler warning in `ChunkAppend`
See individual commits for further descriptions.

Fix test output and compiler warning

---

CMakeLists.txt
test/CMakeLists.txt

Remove option `REQUIRED` from calls to `find_program` in CMake files, 
since such options doesn't exist and is ignored.

Remove option REQUIRED from CMake find_program

---

appveyor.yml

The 1.0.2 version of OpenSSL is broken on appveyor for now.
Disable openssl for now.

Disable OpenSSL on appveyor

---

src/chunk.c
src/dimension.c
src/dimension.h
src/hypertable.c
src/process_utility.c
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/reorder_api.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/insert.c
tsl/src/continuous_aggs/job.c
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/options.c

In various places, most notably drop_chunks and show_chunks, we
dispatch based on the type of the "time" column of the hypertable, for
things such as determining which interval type to use. With a custom
partition function, this logic is incorrect, as we should instead be
determining this based on the return type of the partitioning function.
This commit changes all relevant access of dimension.column_type to a
new function, ts_dimension_get_partition_type, which has the correct
behavior: it returns the partitioning function's return type, if one
exists, and only otherwise uses the column type. After this commit, all
references to column_type directly should have a comment explaining why
this is appropriate.
fixes #1250

Fix handling of types with custom partitioning

---

src/chunk_append/exec.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/runner.sh

Strip out memory usage from EXPLAIN ANALYZE output of Sort nodes
because it is not stable across platforms

Fix use-after-free in ChunkAppend

---

src/chunk_append/chunk_append.c
src/hypertable.c
src/hypertable.h
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_query.sql

When the column a Param references is not a partitioning column
the constraint is not useful for excluding chunks so we skip
enabling runtime exclusion for those cases.

Skip runtime exclusion when Param is not partitioning column

---

test/runner.sh

The regexp-based test output filtering in `runner.sh` does not work
with the Mac OS/BSD version of `sed` since it doesn't use the
extended/modern regexp syntax by default. This makes some tests fail
on Mac OS X/BSD.
This change makes the filter use non-extended regexp syntax to fix
this issue.

Make test runner output filter work on BSDs

---

src/chunk_append/explain.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_query.sql

The Order display of the ChunkAppend node used the output of
the node instead of the input of the node when resolving the
targetlist index to display the order information leading to
incorrect display when the Sort column was not passed through
or the position changed.

Fix Order display in ChunkAppend EXPLAIN

---

src/chunk_append/chunk_append.c
src/planner.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/expected/query.out
test/expected/sort_optimization-10.out
test/expected/sort_optimization-11.out
test/expected/sort_optimization-9.6.out
test/sql/include/plan_ordered_append_query.sql

The initial implementation for Ordered Append required the ORDER BY
clause expression to match the time partitioning column.
This patch loosenes that restriction and will apply the Ordered
Append optimizations for queries with ORDER BY time_bucket as well.

Support time bucket functions in Ordered Append

---

CHANGELOG.md
sql/updates/latest-dev.sql
sql/version.sql
src/telemetry/telemetry.c
test/expected/telemetry.out
test/expected/telemetry_community.out
test/sql/telemetry.sql
test/sql/telemetry_community.sql
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/sql/bgw_reorder_drop_chunks.sql

Previously, get_telemetry_report() returns full report even if telemetry is disabled.
Now, when telemetry is disabled, get_telemetry_report() informs user telemetry is 
disabled and how to view the report locally.

Update get_telemetry_report to expected behavior

---

.travis.yml

Make Travis test PRs and other branches on the latest released
PG patch version for each major version. Cron still tests the earliest
supported patch version (and the ABI tests run by cron cover the
tip of each major version).

Test PRs on the latest stable patch of Postgres

---

src/chunk.c
src/chunk.h
src/chunk_constraint.c
src/dimension_slice.c
src/dimension_slice.h
src/hypertable_restrict_info.c
src/plan_expand_hypertable.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/expected/sql_query-10.out
test/expected/sql_query-11.out
test/expected/sql_query-9.6.out
test/sql/include/plan_ordered_append_query.sql

With ordered append, chunk exclusion occur only along the primary open
"time" dimension, failing to exclude chunks along additional
partitioning dimensions. For instance, a query on a two-dimensional
table "hyper" (time, device), such as
```
SELECT * FROM hyper
WHERE time > '2019-06-11 12:30'
AND device = 1
ORDER BY time;
```
would only exclude chunks based on the "time" column restriction, but
not the "device" column restriction. This causes an unnecessary number
of chunks to be included in the query plan.
The reason this happens is because chunk exclusion during ordered
append is based on pre-sorting the set of slices in the primary
dimension to determine ordering. This is followed by a scan for
chunks slice-by-slice in the order of the sorted slices. Since those
scans do not include …

Fix chunk exclusion with ordered append

---

src/dimension.c
src/dimension.h
src/hypertable.c
test/expected/ddl_errors.out
test/sql/ddl_errors.sql

Calling `create_hypertable` with a space dimension silently succeeds
without actually creating the space dimension if `num_partitions` is
not specified.
This change ensures that we raise an appropriate error when a user
fails to specify the number of partitions.

Fail when adding space dimension with no partitions

---

CHANGELOG.md
sql/updates/latest-dev.sql
sql/views.sql
tsl/test/expected/continuous_aggs_usage.out

Add more information about job history for continuous aggregate
background worker jobs.

Add job statistics columns to timescaledb_information.continuous_aggregate_stats view

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
tsl/test/expected/continuous_aggs_multi.out
tsl/test/sql/continuous_aggs_multi.sql

The primary key on continuous_aggs_materialization_invalidation_log
prevents multiple records with the same materialization id. Remove
the primary key to fix this problem.

Fix continuous agg catalog table insert failure

---

scripts/test_sanitizers.sh

The `test_sanitizers.sh` script do not require regress tools, so
turning off regress tools check when calling CMake.

Disable tool checks for test_sanitizers.sh

---

src/bgw/job.c
src/bgw/job_stat.c
src/bgw/job_stat.h
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/sql/continuous_aggs_bgw.sql

When the continuous aggregate refresh_interval setting is modified,
it does not modify the job schedule until the next scheduled job
runs. This fix addresses it by updating the next_start time for
the bgw job.

Update continuous agg bgw job start time

---

scripts/check_license_all.sh
src/continuous_agg.c
src/continuous_agg.h
test/expected/cursor.out
test/expected/sort_optimization-10.out
test/expected/sort_optimization-11.out
test/expected/sort_optimization-9.6.out
test/expected/telemetry_community.out
test/sql/cursor.sql
test/sql/sort_optimization.sql.in
test/sql/telemetry_community.sql
test/sql/with_clause_parser.sql
test/src/test_time_to_internal.c
test/src/test_with_clause_parser.c

Add license information to files missing it and fix the license
check script to honor the return code of both the apache license
check and the TSL license check. Previously errors occurring during
apache license check would not be reflected in the return code of
the script, so only the TSL license check was effective.

Add missing license information

---

src/base64_compat.h
src/bgw/job.c
src/chunk_dispatch_state.c
src/chunk_insert_state.c
src/compat.h
src/hypertable.c
src/plan_expand_hypertable.c
src/planner.c
src/planner_import.c
src/process_utility.c
src/trigger.c
test/expected/partitioning-11.out

This change enables a check in `create_hypertable` that prohibits
turning partitioned tables into hypertables. The check was only
enabled when compiling against PG10, but should be there for PG
version 10 and greater.
To avoid such disabled code in the future, some extra convenience
macros have been added. For instance `PG10_GE` means PG10 and greater.

Fix partitioned table check and enhance PG macros

---

src/config.h.in
src/telemetry/telemetry.c
test/expected/telemetry.out

Add architecture and pointer bit size fields to what is sent in
telemetry. This will allow us to evaluate the product usage on
different architectures.

Add architecture and bit size to telemetry

---

src/chunk_append/planner.c

This patch changes ChunkAppend to treat CustomScan nodes which have
scanrelid set similar to postgres native Scan nodes. This enables
constraint exclusion to work for CustomScan nodes that scan a relation.

Handle CustomScan node with scanrelid similar to other Scans

---

sql/ddl_api.sql
sql/updates/latest-dev.sql
src/chunk.c
src/chunk.h
test/expected/alter.out
test/expected/chunk_utils.out
test/expected/relocate_extension.out
test/isolation/expected/deadlock_dropchunks_select.out
test/isolation/specs/deadlock_dropchunks_select.spec
test/sql/alter.sql
test/sql/chunk_utils.sql
test/sql/include/query_result_test_equal.sql
test/sql/relocate_extension.sql
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/sql/continuous_aggs_ddl.sql.in

Previously, drop_chunks returned an empty table, giving the user
no indication of what (if anything) had happened.
Now, drop_chunks returns a list of the chunks identifiers in the
same style as show_chunks, with the chunk's schema and table name.

Drop_chunks returns list of dropped chunks

---

CHANGELOG.md
sql/ddl_api.sql

The drop_chunks function was incorrectly marked as stable and
parallel safe this patch fixes the attributes.
Fixes #1333

Mark drop_chunks as VOLATILE and PARALLEL UNSAFE

---

CHANGELOG.md
src/constraint_aware_append.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/append.sql.in
test/sql/include/append_load.sql
test/sql/include/append_query.sql

The RangeTblEntry index used during planning might be different from
the index used during execution due to flattening. This patch changes
ConstraintAwareAppend to handle queries where the index changed between
planning and execution.
Fixes #1360

Fix ConstraintAwareAppend subquery exclusion

---

CHANGELOG.md
src/chunk_append/exec.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_query.sql

ChunkAppend replaced the list of child plans on the plan node with
a local copy which corrupted the child plans when the plan was
turned into a generic plan.
Fixes #1368

Fix ChunkAppend with prepared statements

---

CHANGELOG.md
tsl/src/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

Since bucket_width, start and stop of the gapfill node are
initialized during executor startup only PARAM_EXTERN params
are safe to be used.  This patch will make the gapfill node
throw an error if any argument is a param that is not
PARAM_EXTERN. This patch also improves the error message
for negative or 0 bucket_width.
Fixes #1372

Only allow PARAM_EXTERN as time_bucket_gapfill arguments

---

.travis.yml

We want to run all tests on the prerelease_test branch to make
sure we don't miss any required changes when cherry-picking.

Run all tests on branch prerelease_test

---

CHANGELOG.md
src/chunk_append/planner.c

In some occasions (other extensions modifying plans) MergeAppend
nodes might be wrapped in Result nodes when Projection is needed
and since MergeAppend cannot do projection a Result node is put
on top of MergeAppend. Since ChunkAppend can do projection we can
remove the Result node if it has no one-time filter.
Fixes #1379

Handle Result nodes gracefully in ChunkAppend

---

CHANGELOG.md
sql/CMakeLists.txt
version.config

This maintenance release contains bugfixes since the 1.4.0 release.
**Bugfixes**
* #1362 Fix ConstraintAwareAppend subquery exclusion
* #1363 Mark drop_chunks as VOLATILE and not PARALLEL SAFE
* #1369 Fix ChunkAppend with prepared statements
* #1373 Only allow PARAM_EXTERN as time_bucket_gapfill arguments
* #1380 Handle Result nodes gracefully in ChunkAppend
**Thanks**
* @overhacked for reporting an issue with drop_chunks and parallel queries
* @fvannee for reporting an issue with ConstraintAwareAppend and subqueries
* @rrb3942 for reporting a segfault with ChunkAppend and prepared statements
* @mchesser for reporting a segfault with time_bucket_gapfill and subqueries
* @lolizeppelin for reporting and helping debug an issue with ChunkAppend and Result nodes

Release 1.4.1

---

.codecov.yml
.travis.yml

Change cron triggered travis runs to include all tests.
This patch also adds tagging for coverage information to prevent
faulty coverage differences.

Run all tests on cron triggered runs

---

tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/sql/continuous_aggs_ddl.sql.in

The expression tree walker function used to validate the definition
did not check for NULL values. This patch adds checking for NULL
and also fixes the expression_tree_walker call.
Fixes #1391

Fix cagg_agg_validate expression handling

---

sql/maintenance_utils.sql
src/chunk_index.c
src/chunk_index.h
src/cross_module_fn.c
src/cross_module_fn.h
test/expected/extension.out
test/expected/tablespace.out
test/sql/tablespace.sql
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job.h
tsl/src/init.c
tsl/src/reorder.c
tsl/src/reorder.h
tsl/test/expected/move.out
tsl/test/expected/reorder.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/include/cluster_test_setup.sql
tsl/test/sql/move.sql
tsl/test/sql/reorder.sql
tsl/test/src/test_auto_policy.c

Adds a move_chunk function which to a different tablespace. This is
implemented as an extension to the reorder command.
Given that the heap, toast tables, and indexes are being rewritten
during the reorder operation, adding the ability to modify the tablespace
is relatively simple and mostly requires adding parameters to the relevant
functions for the destination tablespace (and index tablespace). The tests
do not focus on further exercising the reorder infrastructure, but instead
ensure that tablespace movement and permissions checks properly occur.

Add support for moving chunks to different tablespaces

---

src/extension.c
test/expected/loader.out
test/sql/loader.sql
test/sql/utils/test_fatal_command.sh

We currently check and throw an error if the version loaded in the
client is different from the installed extension version, however
there is no way to recover from this state in a backend. (There is
no way to load the new version as we cannot unload the old and no
commands can be effectively run). Now, we instead throw a
FATAL error which will cause the client to reconnect so it can load
the proper extension version.
Fixes #1406 
@svenklemm Do you agree that this is an appropriate use of a FATAL?

Make version mismatch errors FATAL

---

src/chunk_append/planner.c
src/planner.c
src/utils.c
src/utils.h
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_load.sql
test/sql/include/append_query.sql

When ordered append tried to push down targetlist to child paths
it assumed childs would be scans on rels which is not true for
space partitioning where children might be MergeAppend nodes.
This patch also no longer applies the ordered append optimization
to partial paths because its not safe to do so.
This patch also adds more tests for space partitioned hypertables.
Fixes #1397 #1404

Fix ChunkAppend space partitioning support for ordered append

---

src/bgw/job_stat.c
test/expected/bgw_db_scheduler.out
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/continuous_aggs_bgw.out

Since we backoff by a fixed amount, if multiple jobs fail at the same
time, if they have the same retry-interval, they will be rescheduled to
run at the same time again. Since running out of background workers is
considered a failure case by our scheduling code, this can cause
cascading backoffs, until the workers are scheduled at the maximum.
This commit fixes this issue by adding random jitter to the
re-scheduled time: a reschedule time of T will instead be scheduled at
T +- 12.5%

Add random jitter to BGW failure backoff

---

test/sql/utils/test_fatal_command.sh

When a local .psqlrc sets options that modify output of psql the
loader test will fail. This patch changes the test to ignore
the .psqlrc file.

Ignore .psqlrc in test_fatal_command

---

test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/expected/query.out
test/sql/include/plan_expand_hypertable_chunks_in_query.sql
test/sql/include/plan_expand_hypertable_errors.sql
test/sql/include/plan_expand_hypertable_query.sql
test/sql/plan_expand_hypertable.sql.in
test/sql/plan_hashagg.sql.in
test/sql/plan_ordered_append.sql.in
test/sql/query.sql

When using psql output redirection only the query results
get written to the output file which makes it hard to identify
misbehaving queries by looking at the output. This patch
changes the query script to use  \qecho to output query
comments in the output file as well to make identifying
queries in the results output easier.

Echo query description into plan_expand_hypertable test

---

src/interval.c
test/expected/partitionwise.out
test/sql/include/join_query.sql
test/sql/partitionwise.sql

In ts_interval_form_heaptuple the wrong macro was used to get a datum,
the macro is a noop on 64 bit builds but it resulted in a segfault
on 32 bit builds.

Fix segfault on ARM/32-bit builds

---

src/bgw/job.c
src/hypertable.c

The background worker function to check the owner of a job did not have
proper error handling when the object referenced by a job did not exist
leading to a segfault in that case.  This patch adds proper checking of
return values and errors when the object cannot be found.

Fix background worker segfaults

---

.travis.yml
CHANGELOG.md
src/chunk_append/chunk_append.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_query.sql

Do not push down limit to subplan when the query has operations
that modify the number of tuples returned.  Even if we know a
hard limit overall, it doesn't apply if the query has any
grouping/aggregation operations, or SRFs in the tlist.

Fix ChunkAppend LIMIT pushdown

---

CHANGELOG.md
CMakeLists.txt
src/bgw/job.c
src/bgw/job.h
src/bgw/scheduler.c
src/continuous_agg.c
src/utils.h
test/isolation/expected/bgw_job_delete.out
test/isolation/specs/CMakeLists.txt
test/isolation/specs/bgw_job_delete.spec.in
test/pg_isolation_regress.sh
test/postgresql.conf
test/src/bgw/params.c
test/src/bgw/scheduler_mock.c

Previously there were at least 2 problems with deletes of BGWs:
1) A delete of a job or job_stats row while a BGW was running
would often cause "tuple concurrently updated" errors in the
deleting backend, worker, or, worst of all, scheduler.
Sometimes the scheduler would abort because of these errors.
2) A delete of a job did not cause the BGW to quit, thus this
operation could take a long time and would not help with
misbehaving BGWs.
This commit solves both problems. We introduce a new job-row heavyweight
tuple lock that is taken by any running worker and that prevents
concurrent job deletes. We also use this lock to determine the PID
of the worker and cancel (SIGINT) the worker during job deletes.
Furthermore we make the scheduler more gracefully handle unexpected
job deletions and …

Fix deletes of background workers while a job is running

---

CHANGELOG.md
sql/CMakeLists.txt
version.config

This maintenance release contains bugfixes since the 1.4.1 release. We deem it medium
priority for upgrading.
In particular the fixes contained in this maintenance release address 2 potential
segfaults and no other security vulnerabilities. The bugfixes are related to
background workers, OUTER JOINs, ordered append on space partitioned hypertables
and expression indexes.

Release 1.4.2

---

src/utils.c
tsl/src/continuous_aggs/options.c

The microsoft compiler can't figure out that elog(ERROR) doesn't
return and warns about functions not returning a value in all code
paths. This patch adds pg_unreachable calls to those functions.

Fix microsoft compiler warnings

---

CHANGELOG.md
src/chunk_append/chunk_append.c
src/chunk_append/chunk_append.h
src/chunk_append/planner.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_query.sql

Pushing down limit in ChunkApppend is not safe in the JOIN case
because the decision about required tuples can happen above
ChunkAppend node. This patch disables LIMIT pushdown for all
JOINs.

Prevent LIMIT pushdown in JOINs

---

src/chunk_append/exec.c
src/chunk_append/exec.h
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/runner.sh
test/sql/include/append_query.sql

The intermediate expressions used for runtime exclusions would
only be freed at the end of a query leading to excessive memory
usage for nested loop joins with many loops. This patch changes
runtime exclusion to free intermediate expressions as soon as
they are no longer needed.
Fixes #1442

Fix runtime exclusion memory leak

---

src/plan_agg_bookend.c
src/plan_expand_hypertable.c
src/plan_partialize.c
src/telemetry/telemetry.c
src/utils.c
src/utils.h

Telemetry would send the postgres version the extension was compiled
against as postgres_version instead of the postgres version that is
currently running. This patch fixes telemetry to send the version
actually in use.

Fix postgres version reported by telemetry

---

src/chunk_append/exec.c
src/chunk_append/exec.h
test/expected/parallel-10.out
test/expected/parallel-11.out

This patch changes ChunkAppend to assign multiple worker per child
if the number of worker exceeds the number of children.

Enable multiple worker per child for ChunkAppend

---

scripts/clang_format_wrapper.sh

When running `make format` it will update all files. If a file does not
actually require reformatting, it will trigger a re-build of the entire
code base.
This commit instead compare the re-formatted file with the existing one
and does not update it unless it has actually changed.

Only update reformatted files

---

src/chunk_append/planner.c
test/expected/plan_ordered_append-10.out
test/expected/plan_ordered_append-11.out
test/expected/plan_ordered_append-9.6.out
test/sql/include/plan_ordered_append_query.sql

Ordered append for space partitioned hypertable would lead to an
error when the ORDER BY clause was not a column reference on PG 9.6
and PG 10. This patch fixes ordered append for space partitioned
hypertable and allows arbitary expressions to be used in the
ORDER BY clause.

Fix ordered append with expressions in ORDER BY clause with space partitioning

---

src/chunk_append/exec.c
src/chunk_append/exec.h
src/planner.c
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/parallel.sql.in

The initial iteration of assigning multiple workers per subplan
would always assign a fixed amount of workers per child. This
patch changes the logic to assign each child one worker and then
moving to the next subplan, iterating until all subplans are finished.
This will lead to a much better distribution of workers especially
when the children are not well balanced.

Improve ChunkAppend parallel worker assignment

---

.travis.yml

The ASAN_OPTIONS to disable leak check for this test were not
properly passed down into the container, this patch sets them
as environment variables in the container as well.

Fix clang-format and licence check on travis

---

CMakeLists.txt
src/indexing.c
test/src/bgw/timer_mock.c
test/src/test_with_clause_parser.c

It is not possible to enable both `-Wall` and `-Wextra` since that generate
too many warnings, so enabling some additional warnings to
get a decent level of checking.
Warnings enabled are:
-Werror -Wempty-body
For GCC version 7 and above and Clang version 3.3 and later:
-Wimplicit-fallthrough

Enable some compiler warnings and fix code

---

.travis.yml

Since a build job for PG 11.4 is run on every PR and every feature
branch, there is no need to run PG 11.0 on every commit on every
feature branch.

Disable running 11.0 on every branch on Travis-CI

---

appveyor.yml
test/postgresql.conf
tsl/test/postgresql.conf

The tests do not expect that autovacuum is run. The most of the tests
finishes before it runs, but some ARM tests might fail due if autovacuum
is executed.

Disable autovacuum in tests

---

test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/parallel.sql.in

Since we can now set reloptions on chunks we don't have to rely on
data volume to trigger parallel plans.

Speed up parallel test

---

src/bgw/job.c
src/bgw/scheduler.c
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/sql/continuous_aggs_bgw.sql

This fixes the logic for what happens when the next start time
is changed on the bgw job:
- When changing the schedule_interval, the new next start time
is set to last_finish + new_schedule_interval instead of
now() + new_schedule_interval. This makes it easier to test
and is semantically more correct
- New logic is added in the scheduler to recalculate the
scheduler's next start time
- Better tests are added
Fixes #1462

Fix logic for BGW rescheduling

---

sql/bgw_scheduler.sql
sql/updates/latest-dev.sql
src/bgw/job.c
src/bgw/job_stat.c
src/bgw/job_stat.h
tsl/src/bgw_policy/job.c
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/tsl_tables.out
tsl/test/sql/continuous_aggs_bgw.sql
tsl/test/sql/tsl_tables.sql

Add the option to set the next start time on a job in the
alter job schedule function. This also adds the ability
to pause jobs by setting next_start to 'infinity'
Also fix the enterprise licence check to only activate for
enterprise jobs.

Add next_start option to alter_job_schedule

---

tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/reorder_api.c
tsl/src/continuous_aggs/job.c
tsl/test/expected/bgw_policy.out
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/tsl_tables.out

The default retry_period for jobs was set too high, causing jobs
that failed because of lack of workers to be restarted too infrequently,
this sets it significantly lower, to 5 minutes, though exponential
backoff will cause that to be larger as multiple failures stack up.

Set default retry_period for jobs to 5 minutes

---

src/chunk_append/explain.h
src/chunk_append/planner.h
tsl/src/nodes/gapfill/exec.c
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/gapfill.out
tsl/test/sql/continuous_aggs_bgw.sql
tsl/test/sql/gapfill.sql

When locf was used with the treat_null_as_missing option and the
query ORDER BY did not match gapfill ordering the treat_null_as_missing
option was not working correctly because the values from orignal tuple
would be returned and not our modified ones.
Fixes #1466

Fix gapfill treat_null_as_missing

---

.travis.yml

Since the base image for travis changed from ubuntu trusty to xenial
the package name for cmake has to be adjusted to make the coverity
test work.

Fix coverity travis task

---

appveyor.yml
src/chunk_append/exec.c
src/loader/loader.c
test/expected/bgw_db_scheduler.out
test/expected/bgw_launcher.out
test/postgresql.conf
test/sql/bgw_db_scheduler.sql
test/src/bgw/scheduler_mock.c
tsl/test/postgresql.conf

When all subplans are excluded during runtime exclusion negative
array index access might be possible on the ChunkAppend finished
state. This patch fixes the check for a valid subplan index.

Fix negative array index access in ChunkAppend parallel worker assignment

---

CMakeLists.txt

clang-format > 8 has slightly different oppinion about source code
formatting than earlier versions, unfortunately some of the new
options cannot be set in a backwardscompatible way so we fall back
to docker for newer versions.

Only use local clang-format 7 or 8

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/views.sql
src/bgw/job_stat.c
src/catalog.h
test/expected/bgw_db_scheduler.out
test/sql/bgw_db_scheduler.sql
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_usage.out

This allows people to better monitor the bgw job health. It
indicates when the last time the job made progress was.

Add last_successful_finish to bgw_job_stats

---

src/extension.c

This patch prevents recursing into the cache invalidation code.
Since this code's result is dependent on the transaction snapshot,
processing it multiple times recursively won't change the result.
Fixes #1486

Prevent recursion in invalidation processing

---

tsl/src/nodes/gapfill/interpolate.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

All integer types must use numeric-based interpolation calculations
since they are multiplied by int64 and this could cause an overflow.
numerics also interpolate better because the answer is rounded and not
truncated. We can't use float8 because that doesn't handle really big
ints exactly. We can't use the Postgres INT128 implementation because
it doesn't support division.
In the future we can optimize this for cases where overflow doesn't
occur.
Fixes #1491.

Fix overflow in gapfill's interpolate

---

tsl/src/nodes/gapfill/interpolate.c

Interpolate was trying to use a datum as an int64. This is a bug
that was flagged on arm.

Fix interpolate for ARM32

---

sql/restoring.sql
test/expected/pg_dump.out
test/sql/pg_dump.sql
test/sql/utils/pg_dump_aux_restore.sh
tsl/test/expected/compression_hypertable.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/sql/continuous_aggs_dump.sql
tsl/test/sql/include/compression_test_hypertable.sql

When restoring a database, people would encounter errors if
the restore happened after telemetry has run. This is because
a 'exported_uuid' field would then exist and people would encounter
a "duplicate key value" when the restore tried to overwrite it.
We fix this by moving this metadata to a different key
in pre_restore and trying to move it back in post_restore.
If the restore create an exported_uuid, that restored
value is used and the moved version is simply deleted
We also remove the error redirection in restore so that errors
will show up in tests in the future.
Fixes #1409.

Fix error for exported_uuid in pg_restore

---

src/histogram.c
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/parallel.sql.in

Histogram's combine function threw a segfault if both state1
and state2 were NULL. I could only reproduce this case in
PG 10. Add a tests that hits this with PG 10.4
Fixes #1490

Fix bug with histogram function in parallel

---

CMakeLists.txt
src/build-defs.cmake
tsl/src/build-defs.cmake

When linking the extensions as shared libraries, the linker flags from
`pg_config` is not used. This means that if `PG_PATH` is provided and
refer to a locally compiled Postgres installation, shared libraries
from that installation will not be used. Instead any default-installed
version of Postgres will be used.
This commit adds `PG_LDFLAGS` to `CMAKE_SHARED_LINKER_FLAGS` and
`CMAKE_MODULE_LINKER_FLAGS`.
To handle that Windows set some fields to "not recorded" when they are
not available, it introduces a CMake function `get_pg_config` that will
replace it with `<var>-NOTFOUND` so that it is treated as undefined by
CMake.

Use Postgres linker flags when linking

---

test/expected/custom_type.out
test/sql/custom_type.sql

Fix tests that fail like so:
test=# CREATE CAST (customtype AS bigint)
test-# WITHOUT FUNCTION AS ASSIGNMENT;
ERROR:  source and target data types are not physically compatible

Fix failure with custom type test

---

.travis.yml
test/expected/chunk_adaptive.out
test/sql/chunk_adaptive.sql

The main reason to run ARM tests was not to identify issues with
ARM but to identify 32 bit issues e.g. int64 as pointer instead
type by value. Those issues don't need ARM emulation but can be
tested with i386 which is much faster.

Run 32 bit tests on i386 instead of ARM emulation

---

tsl/test/expected/transparent_decompression-10.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/sql/include/transparent_decompression_constraintaware.sql
tsl/test/sql/transparent_decompression.sql.in

1. This commit introduces changes to expected plan output due
to the addition of new chunks to metrics_ordered_idx.
2. Add tests for constraint aware appends on compressed
tables.

Add constraint aware tests for compression

---

src/process_utility.c

Set active snapshots when creating txns during index
create with timescaledb.transaction_per_chunk. This
is needed for some index types like `bloom`.
Tests not added since we don't want dependencies on contrib modules
like bloom.
Fixes #1521.

Set active snapshots in multi-xact index create

---

CMakeLists.txt

In some cases _temp variable will not be set due to pg_config not
returning any output for a specific flag. This will result in an
error when doing comparison using STREQUAL. Wrapping variable in
double quotes fixes the problem.

Fix CMake condition

---

src/func_cache.h
tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_errors.out

Refactor the continuous aggregate validation to use our function cache
to check for bucketing function. This simplifies the code and allows
adding support for other bucketing functions like date_trunc later on.

Use function cache to check for valid bucketing functions

---

.travis.yml

Adds notification from Travis CI to an internal Slack channel when a
CRON build fails.
The notification goes to [travis-ci-org channel](https://iobeam.slack.com/archives/CR2GTBLP2). The channel contains an example of a notification.

Notify internal Slack an Travis CRON build fail

---

src/compat.h
src/guc.c
src/utils.h
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/test/expected/compression_ddl.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_multi.out
tsl/test/expected/continuous_aggs_permissions-10.out
tsl/test/expected/continuous_aggs_permissions-11.out
tsl/test/expected/continuous_aggs_permissions-9.6.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/expected/transparent_decompression-10.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/isolation/expected/continuous_aggs_insert.out
tsl/test/isolation/expected/continuous_aggs_multi.out
tsl/test/sql/continuous_aggs_materialize.sql
tsl/test/src/test_continuous_aggs.c

This change the continuous aggregate materialization logic so that
the max_interval_per_job applies to invalidation entries as well
as new ranges in the materialization. The new logic is that the
MIPJ setting limits the sum of work done by the invalidations
and new ranges. Invalidations take precedence so new ranges
are only processed if there is time left over in the MIPJ
budget after all invalidations are done.
This forces us to calculate the invalidation range during the first
transaction. We still delete and/or cut the invalidation entries
in the second transaction. This change also more neatly separates concerns:
all decisions on work to be done happens in the first txn while only
execution happens in the second. Further refactoring could make
this more clear by passing a list of …

Apply max_interval_per_job to invalidations

---

tsl/src/continuous_aggs/materialize.c
tsl/test/sql/CMakeLists.txt

Fix some minor compiler warnings and errors. Move some tests that
require `timescaledb.current_timestamp_mock` from release to
debug-only.

Fix tests errors

---

tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs.out
tsl/test/sql/continuous_aggs.sql

Continuous aggregate views like
select time_bucket(), sum(col)
from ...
group by time_bucket(), grpcol;
when grpcol is missing from the select targetlist, the
partialize query's select targetlist is incorrect and the view
cannot be materialized. This PR fixes this issue.

Fix partial select query for continuous aggregate

---

CHANGELOG.md
sql/pre_install/tables.sql
sql/updates/latest-dev.sql
src/catalog.c
src/catalog.h
src/continuous_agg.c
src/continuous_agg.h
src/hypertable.c
src/hypertable.h
test/sql/updates/post.continuous_aggs.sql
test/sql/updates/setup.continuous_aggs.sql
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/insert.c
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/src/continuous_aggs/options.c
tsl/src/continuous_aggs/options.h
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_errors.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_multi.out
tsl/test/expected/continuous_aggs_watermark.out
tsl/test/sql/continuous_aggs.sql
tsl/test/sql/continuous_aggs_bgw.sql
tsl/test/sql/continuous_aggs_errors.sql
tsl/test/sql/continuous_aggs_multi.sql
tsl/test/sql/continuous_aggs_watermark.sql

We added a timescaledb.ignore_invalidation_older_than parameter for
continuous aggregatess. This parameter accept a time-interval (e.g. 1
month). if set, it limits the amount of time for which to process
invalidation. Thus, if
timescaledb.ignore_invalidation_older_than = '1 month'
then any modifications for data older than 1 month from the current
timestamp at insert time will not cause updates to the continuous
aggregate. This limits the amount of work that a backfill can trigger.
This parameter must be >= 0. A value of 0 means that invalidations are
never processed.
When recording invalidations for the hypertable at insert time, we use
the maximum ignore_invalidation_older_than of any continuous agg attached
to the hypertable as a cutoff for whether to record the invalidation
at all. …

Add ignore_invalidation_older_than to continuous aggs

---

src/planner.c

Removes duplicate call to setup_append_rel_array and avoids allocating
another append_rel_array with the same values during planning queries
with  hypertables.

Remove duplicate allocation during planning

---

src/chunk.c
src/chunk.h
src/chunk_constraint.c
tsl/src/compression/create.c

Previously, the Chunk struct was used to represent both a full
chunk and the stub used for joins. The stub used for joins
only contained valid values for some chunk fields and not others.
After the join determined that a Chunk was complete, it filled
in the rest of the chunk field. The fact that a chunk could have
only some fields filled out and not others at different times,
made the code hard to follow and error prone.
So we separate out the stub state of the chunk into a separate
struct that doesn't contain the not-filled-out fields inside
of it.  This leverages the type system to prevent errors that
try to access invalid fields during the join phase and makes
the code easier to follow.

Refactor chunk handling to separate out stub

---

tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/sql/continuous_aggs_ddl.sql.in

The continuous agg ddl test is flaky and occasionally fails with a
deadlock which might be caused by background workers running.

Disable background workers in cagg ddl tests

---

CHANGELOG.md
tsl/src/nodes/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

The locf treat_null_as_missing option would not trigger the lookup
query if there was a row for the first bucket and value in that row
was NULL. This patch fixes the behaviour and triggers the lookup
query for the first row too.
Fixes #1588

Fix locf treat_null_as_missing option

---

src/guc.c
src/guc.h
src/planner.c
tsl/test/expected/continuous_aggs_query-10.out
tsl/test/expected/continuous_aggs_query-11.out
tsl/test/expected/continuous_aggs_query-9.6.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/continuous_aggs_query.sql.in

Modify group by clause on continuous aggr views
Reorder the group by clause to match the ordering of the
ORDER BY by clause. SELECTs on continuous aggregate queries
often have an order by clause on the time_bucket column.
If the order-by does not match the grouping clause,
the planner inserts an additional Sort node after
the view evaluation (Aggregate node).
preprocess_groupclause does this reordering if the ORDER BY clause
is part of the current subquery being processed. But when we have
a continuous aggregate view, the order by needs to be derived
from the outer query. This PR allows the order by from
outer query to propagate to group clause of continuous aggr. view.
The rewrite is :
select * from (select a, b, max(c), min(d) from ...group by a, b)
order by b;
is transformed as
SELECT …

Reorder group-by clause for continuous aggregates

---

tsl/test/sql/CMakeLists.txt

Test case uses current_timestamp_mock which is
available only in debug builds.

Run continuous_aggs_query.sql only in debug build

---

CHANGELOG.md
tsl/src/compression/create.c
tsl/test/expected/compression_errors.out
tsl/test/sql/compression_errors.sql

The constraint check previously assumed that the col_meta
offset for a column was equal to that columns attribute
offset. This is incorrect in the presence of dropped columns.
Fixed to match on column names.
Fixes #1590

Fix error in compression constraint check

---

src/utils.c
src/utils.h
tsl/src/continuous_aggs/materialize.c
tsl/test/expected/compression_ddl.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_multi.out
tsl/test/expected/continuous_aggs_permissions-10.out
tsl/test/expected/continuous_aggs_permissions-11.out
tsl/test/expected/continuous_aggs_permissions-9.6.out
tsl/test/expected/continuous_aggs_query-10.out
tsl/test/expected/continuous_aggs_query-11.out
tsl/test/expected/continuous_aggs_query-9.6.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/expected/transparent_decompression-10.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/isolation/expected/continuous_aggs_insert.out
tsl/test/isolation/expected/continuous_aggs_multi.out

Switch from using internal timestamps to more user-friendly
timestamps in our log messages and clean up some messages.

Improve continuous agg user messages

---

CHANGELOG.md
src/bgw/job.c
src/bgw_policy/compress_chunks.c
src/bgw_policy/compress_chunks.h
src/bgw_policy/policy.c
tsl/src/bgw_policy/compress_chunks_api.c
tsl/src/compression/create.c
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression_ddl.sql

Previously we could have a dangling policy and job referring
to a now-dropped hypertable.
We also block changing the compression options if a policy exists.
Fixes #1570

Delete compression policy when drop hypertable

---

CHANGELOG.md
sql/views.sql

Add the compression and continuous aggs job types to the
timescaledb_information.policy_stats view. It is a bug
that it wasn't there before.

Add jobs to timescaledb_information.policy_stats

---

src/plan_partialize.c
src/planner.c
tsl/test/expected/partialize_finalize.out
tsl/test/sql/partialize_finalize.sql

This change fixes an assertion-based crash that happened when using
the `partialize_agg` function together with HAVING clauses. For instance,
```
SELECT time_bucket('1 day', time), device,
__timescaledb_internal.partialize_agg(avg(temp))
GROUP BY 1, 2
HAVING avg(temp) > 3;
```
would crash because the HAVING clause's aggregate didn't have its
`Aggref` node set to partial aggregate mode.
Regular partial aggregations executed by the planner (i.e., those not
induced by the `partialize_agg` function) have their HAVING aggs
transparently moved to the target list during planning so that the
finalize node can use it when applying the final filter on the
resulting groups. However, it doesn't make much sense to transparently
do that when partializing with `partialize_agg` since it would be odd
to …

Fix crash when partializing agg with HAVING

---

CHANGELOG.md
src/chunk_append/exec.c
test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_load.sql
test/sql/include/append_query.sql

Descending into subplans during constification of params
seems unsafe and has led to bugs. Turning this off seems
to be safe and not regress any tested optimizations.
In the future we may want to find a way to optimize this
case as well.
Fixes #1598.

Fix constify params during runtime exclusion

---

CHANGELOG.md
src/planner.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

Fix bug with transparent decompression getting the
hypertable parent table. This can happen with self-referencing
updates.
Fixes #1555

Fix bug with parent table in decompression

---

src/chunk.c

The drop_chunks function would call continuous_agg_drop_chunks_by_chunk_id
even for hypertables without continuous aggregates leading to license
errors when compiled as Apache-only. This PR skips the call when the
hypertable has no continuous aggregates.

Fix tests with drop_chunks for ApacheOnly

---

tsl/src/continuous_aggs/materialize.c

Move the NULL-check in continuous_agg_execute_materialization before
the first dereferncing of the variable.

Check for NULL before dereferencing variable

---

src/process_utility.c
test/expected/copy.out
test/expected/metadata.out
test/sql/copy.sql
test/sql/metadata.sql
test/sql/utils/pg_dump_aux_dump.sh
test/sql/utils/pg_dump_unprivileged.sh

When using `COPY TO` on a hypertable (which copies from the hypertable
to some other destination), nothing will be printed and nothing will be
copied. Since this can be potentially confusing for users, this commit
print a notice when an attempt is made to copy from a hypertable
directly (not using a query) to some other destination.
First part of fix for timescaledb/timescaledb-private#461. Need to be implemented for distributed hypertables as well.

Print notice for COPY TO on hypertable

---

src/build-defs.cmake
tsl/src/build-defs.cmake

Postgres CFLAGS includes -Wdeclaration-after-statement which leads
to problems when compiling with -Werror since we aim for C99 and allow
that so we strip this flag from PG_CFLAGS before adding postgres flags
to our own

Remove -Wdeclaration-after-statement from PG_CFLAGS

---

.github/CODEOWNERS

A `CODEOWNERS` file allows assigning default reviewers for a branch,
obviating the need to add reviewers manually.

Add CODEOWNERS file to auto-assign reviewers

---

src/chunk.c
src/chunk.h
src/continuous_agg.h
src/cross_module_fn.c
src/cross_module_fn.h
tsl/src/continuous_aggs/drop.c
tsl/src/continuous_aggs/drop.h
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/sql/continuous_aggs_ddl.sql.in

When drop_chunks is called with cascade_to_materialization = true,
the materialized data is deleted from the materialization
hypertable, but the chunks are not dropped. This fix drops chunks
if possible and deletes the data only if the materialized chunk
cannot be dropped (which is the case if the materialzied chunk
contains data from multiple raw chunks and some of the raw chunks
are not dropped).
Fixes #1644

Drop chunks for materialized hypertable

---

src/compression_with_clause.c
src/process_utility.c
tsl/src/compression/create.c
tsl/test/expected/compression.out
tsl/test/expected/compression_errors.out

Modify compression parameter related error messages
to make them consistent.
Fixes #1642

Use timescaledb prefix for compression errors

---

src/chunk.c
src/chunk_adaptive.c
src/chunk_dispatch_state.c
src/dimension.c
src/hypertable.c
src/hypertable_cache.c
src/hypertable_cache.h
src/hypertable_insert.c
src/interval.c
src/planner.c
src/process_utility.c
src/tablespace.c
tsl/src/bgw_policy/compress_chunks_api.c
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/job.c
tsl/src/compression/compress_utils.c
tsl/src/compression/create.c
tsl/src/continuous_aggs/create.c
tsl/src/reorder.c
tsl/test/expected/continuous_aggs_errors.out
tsl/test/expected/tsl_tables.out
tsl/test/src/test_continuous_aggs.c
tsl/test/src/test_ddl_hook.c

Refactors multiple implementations of finding hypertables in cache
and failing with different error messages if not found. The
implementations are replaced with calling functions, which encapsulate
a single error message. This provides the unified error message and
removes need for copy-paste.
PR notes:
Closes https://github.com/timescale/timescaledb-private/issues/539
I am not sure if I gave good names to functions. Let me know if you have better suggestions.

Unify error message if hypertable not found

---

CHANGELOG.md
tsl/src/nodes/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

The GapFill node was not fully reset on a ReScan, so if there was a
GapFill within a NestedLoop, only the first iteration would return
results. This commit fixes this issues.
**NOTE**: main reviewers are Cevian and Sven, others were added automatically

Fix GapFill with ReScan

---

CHANGELOG.md
src/dimension.c
src/hypertable.c
src/hypertable.h
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

add_dimension should fail when table has no
data but still has empty chunks.
Fixes #1623

Cannot add dimension if table has empty chunks

---

CHANGELOG.md
tsl/src/compression/create.c
tsl/test/expected/compression_errors.out
tsl/test/sql/compression_errors.sql

Fix failure with disabling compression when no
compressed chunks are present and the table has foreign
key constraints
Fixes #1661

Support disabling compression when foreign keys are present

---

CHANGELOG.md
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/nodes/decompress_chunk/planner.c
tsl/test/expected/transparent_decompression_queries.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/transparent_decompression_queries.sql

Fix order by queries on compressed hypertables that
have char segment by column.
The segment by var column for decompressed chunks should be
created after settng the typmod and collation ids. Otherwise, we
get failures with char datatypes while decompressing.
Fixes #1650

Fix segment_by var for decompress chunk node

---

README.md
docs/BuildSource.md

This commit updates the README with updated resources, including Timescale
Cloud, new support options, release notes, and others. For readability, it
also moves instructions for building from source to a separate readme file.

Update README with addt resources, build instructions to separate file

---

src/plan_partialize.c
src/plan_partialize.h
src/planner.c
tsl/test/expected/partialize_finalize.out
tsl/test/sql/partialize_finalize.sql

REFRESH MATERIALIZED VIEW statements sometimes crash
because the generated plan has a HashAgg node
instead of Partial Aggregate node when executing
INSERT INTO <materialization_table>
SELECT * FROM <view>
Where the view stmt itself is along these lines
SELECT time_bucket('1 day'::interval, cpu."time") ,
......
_timescaledb_internal.partialize_agg(avg(...))
FROM <table> ....

Fix bad plan for materialization

---

tsl/test/expected/continuous_aggs_query-10.out
tsl/test/expected/continuous_aggs_query-11.out
tsl/test/expected/continuous_aggs_query-9.6.out
tsl/test/sql/continuous_aggs_query.sql.in

Since planning costs are not stable across platforms they should not
be included in test output.

Remove plan costs from test output

---

CHANGELOG.md
src/chunk.c
src/chunk.h
src/continuous_agg.c
src/continuous_agg.h
src/cross_module_fn.c
src/cross_module_fn.h
src/hypertable.c
src/interval.c
src/interval.h
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/job.c
tsl/src/continuous_aggs/drop.c
tsl/src/continuous_aggs/drop.h
tsl/test/expected/bgw_policy.out
tsl/test/expected/compression_errors.out
tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
tsl/test/expected/continuous_aggs_ddl-10.out
tsl/test/expected/continuous_aggs_ddl-11.out
tsl/test/expected/continuous_aggs_ddl-9.6.out
tsl/test/expected/tsl_tables.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql
tsl/test/sql/continuous_aggs_ddl.sql.in

Add support for dropping chunks from materialized
hypertables. drop_chunks_policy can now be set up
for materialized hypertables.
Fixes #1639
Note to Reviewers:
This PR supports:
A. add_drop_chunks_policy( '<schema_name>.<view_name>' , ... )
cannot pass in materialized hypertable name directly here.
Policies are added by specifying the cont. aggregate view name.
If the cont. aggregate is based on "integer-type" time table, then the integer_now function is inherited by the cont. aggregate as well.
B. drop_chunks support for materialized hypertables.
1) drop_chunks( 'schema_name', 'view_name' , ... ) supported
2) drop_chunks ('_timescaledb_internal', ' materialized_hypertable_name', ... ) is supported.
3) drop_chunks( older_than => ..)
The table_name/view_name is not specifically passed in. …

Drop chunks from materialized hypertables

---

CHANGELOG.md
src/plan_expand_hypertable.c
test/expected/plan_expand_hypertable-10.out
test/expected/plan_expand_hypertable-11.out
test/expected/plan_expand_hypertable-9.6.out
test/sql/include/plan_expand_hypertable_chunks_in_query.sql
test/sql/include/plan_expand_hypertable_load.sql
test/sql/include/plan_expand_hypertable_query.sql
test/sql/plan_expand_hypertable.sql.in
tsl/test/expected/transparent_decompression-10.out
tsl/test/expected/transparent_decompression-11.out

This change fixes the `plan_expand_hypertable` test, which was broken
and never ran the output comparison due to prematurely ending in an
uncaught error. The test appeared to succeeded, however, since also
the broken test "expected" files were committed to the repo.
Fixing the test revealed that the query output with our optimizations
enabled is incorrect for outer joins (i.e., the output from the query
differed from regular PostgreSQL). Restriction clauses were too
aggressively pushed down to outer relations, leading to chunk
exclusion when it shouldn't happen. This incorrect behavior has also
been fixed.

Fix incorrect chunk exclusion and broken test 

---

src/utils.c

Error message used to specify that interval must be defined in terms of days or
smaller, which was confusing because we really meant any fixed interval (e.g.,
weeks, days, hours, minutes, etc.), but not an interval that is not of fixed
duration (e.g., months or years).

Clarify supported intervals in error msg

---

CHANGELOG.md
tsl/src/compression/create.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

When trying to compress a chunk that had a column of datatype
interval delta-delta compression would be selected for the column
but our delta-delta compression does not support interval and
would throw an errow when trying to compress a chunk.
This PR changes the compression selected for interval to dictionary
compression.
Fixes #1726

Fix compressing interval columns

---

src/bgw/job.c
src/bgw/job.h
tsl/src/bgw_policy/compress_chunks_api.c
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/reorder_api.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/continuous_aggs_permissions-10.out
tsl/test/expected/continuous_aggs_permissions-11.out
tsl/test/expected/continuous_aggs_permissions-9.6.out
tsl/test/expected/tsl_tables.out
tsl/test/sql/compression_bgw.sql

This change will check sql commands which start a background worker
on a hypertable to verify that the table owner has permission to
log into the database.  This is necessary, as background workers for
these commands will run with the permissions of the table owner, and
thus immediately fail if unable to log in.

Prevent starting background workers with NOLOGIN

---

src/continuous_agg.c
src/continuous_agg.h
src/process_utility.c
tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/bgw_policy/job.c
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_dump.out

A nit, but it doesn't look professional to have typos in the error messages. Fixed the names of functions at the same time.

Fix typo of "continuous"

---

src/copy.c

Function `timescaledb_CopyFrom` created a variable `errcallback` to
save away the previous error callback and restoring it afterwards.
However, if `ccstate->cstate` was false, the variable would not be set
and the later restore of the error callback would use a random value.
This commit fixes the issue by initializing `errcallback` to all zeroes
and checking if a callback has been saved away before restoring it.

Remove usage of uninitilized value

---

src/chunk_index.c
test/expected/index.out
test/sql/index.sql

When the index for a chunk was created the attnos for the index
predicate were not adjusted leading to insert errors on hypertables
with dropped columns that had indexes with predicates.
This PR adjust index predicate attnos when creating the chunk index
to match the chunk attno.
Fixes #1675

Adjust index predicate attnos when creating chunk index

---

src/bgw/job_stat.c
src/bgw/job_stat.h
src/bgw/scheduler.c
src/compat.h
test/expected/bgw_db_scheduler.out
test/sql/bgw_db_scheduler.sql

This PR improves the scheduling of jobs when the number of
jobs exceeds the amount of background workers. Previously,
this was not a case the scheduler handled well.
The basic strategy we employ to handle this case better is to
use a job's next_start field to create a priority for jobs.
More concretely, jobs are scheduled in increasing order of
next_start. If the scheduler runs out of bgw's it waits to
until bgws become available and then retries again, also
in increasing next_start order.
The first change this PR implements is start jobs in order
of increasing next_start. We also make sure that if we run
out of BGWs, the scheduler will try again in START_RETRY_MS
(1 second by default).
This PR also needed to change the logic of what happens when
a job fails to start because BGWs have run …

Handle many BGW jobs better

---

tsl/src/continuous_aggs/materialize.c
tsl/test/expected/continuous_aggs_multi.out
tsl/test/sql/continuous_aggs_multi.sql

When we copy the invalidation logs for individual continuous
aggregates, the lowest-value was globally overwritten. Fix this
so that the change is specific to a continuous aggregate.
This bug could result in missing invalidations.

Fix copy of continuous agg invalidation entries

---

CHANGELOG.md
src/constraint_aware_append.c
tsl/test/expected/transparent_decompression_queries.out
tsl/test/sql/transparent_decompression_queries.sql

When a MergeAppendPath has children that do not produce sorted
output a Sort node will be injected during plan creation, those
plans would trigger an error about invalid child nodes in
ConstraintAwareAppend. This PR makes ConstraintAwareAppend handle
those plans correctly.
Fixes #1577

Handle Sort nodes in ConstraintAwareAppend

---

sql/restoring.sql
src/loader/bgw_launcher.c
test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

There was a race condition between the post_restore function
restarting the background worker and the setting of the
restoring flag to "off". If the worker started before the
change to the restoring flag had been committed, it would not
see the change and then die because the worker should exit
when the db is in a restoring state. This modifies the
post_restore function to use a restart instead of a start
so that it waits on the commit to start up. It also adds
logic to the entrypoint to reload config changes caused
by an `ALTER DATABASE SET` command. These changes are
normally only seen at connection startup but we have to
wait until after our lock on the modifying transaction is
released to know whether we should adopt them.
Fixes #1712 
Changes the loader so would require a restart on …

Fix restoring/scheduler entrypoint to avoid BGW death

---

tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

The gapfill test assumed 1 day is always <= 24 hours which is not
true during DST switch leading to a failing test when run in that
time. This PR fixes the test to have reproducable output even
when run during DST switch.

Fix flaky gapfill test

---

tsl/src/bgw_policy/drop_chunks_api.c
tsl/src/compression/compress_utils.c
tsl/src/compression/compression.c
tsl/src/compression/create.c
tsl/test/expected/compression_errors.out

This change fixes a number of typos and issues with inconsistent
formatting for compression-related code. A couple of other fixes for
variable names, etc. have also been applied.

Cleanup compression-related errors

---

sql/size_utils.sql

Relation size should not include dropped chunks
Function hypertable_relation_size includes chunks that were dropped which causes a failure when looking up the size of dropped chunks. Adding this check to the WHERE statement in the SQL will ignore dropped chunks from the size calculation.
Fixes: #1692

Add logic to ignore dropped chunks in hypertable_relation_size

---

src/interval.c
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/sql/continuous_aggs_materialize.sql

For hypertables with a TIMESTAMP column materialization would not
honor the local timezone when determining the range for materialization
and instead treat times as UTC.
Fixes #1695

Fix continuous aggregate materialization timezone handling

---

tsl/src/bgw_policy/drop_chunks_api.c
tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql

Function `remove_drop_chunks_policy` did not work if a continuous
aggregate was provided as input.
This commit fixes that by looking for a continuous aggregate if a
hypertable is not found.
Fixes timescale/timescaledb-private#670

Fix remove_drop_chunks_policy for continuous aggregates

---

CMakeLists.txt

When building TimescaleDB with the EnterpriseDB package installed, it
does not include the debug versions of the DLLs, so a debug build of
TimescaleDB fails.
This commit fix the issue by replacing the debug DLLs in
`OPENSSL_LIBRARIES` with release DLLs even for a debug build when
compiling using MSVC.

Use release OpenSSL DLLs for debug builds

---

CHANGELOG.md
src/bgw/job.c
src/bgw/job_stat.c
src/bgw/scheduler.c
test/expected/bgw_db_scheduler.out
test/isolation/expected/bgw_job_delete.out
tsl/src/bgw_policy/job.c

Make scheduler more resilient to failures
Invalidate cache state when jobs are detected as
potentially missing. This will update the jobs list
used by the scheduler.
Restrict job start times to a finite interval when
there are consecutive job failures.
Additional logging.

Scheduler cache invalidations

---

src/chunk.c
src/chunk_constraint.c

Fixes to return error in ts_chunk_get_by_relid if fail_if_not_found is
true. Removes TSDLLEXPORT macro from definitions in few C files, which
helps VS Code to work properly and find function definitions.

Fix returning error on chunk get and exporting

---

CMakeLists.txt

If `clang-format` with the correct usage does not exist on the machine,
the `clang_format_all.sh` script is executed in a docker image. Since a
`--user` is not provided, the script is executed with the wrong user,
which gives wrong user for formatted files.

Docker version of clang-format use wrong user

---

CHANGELOG.md
sql/CMakeLists.txt
sql/updates/1.6.0--1.6.1.sql
sql/updates/latest-dev.sql
version.config

This maintenance release contains bugfixes since the 1.6.0 release. We deem it medium
priority for upgrading.
In particular the fixes contained in this maintenance release address bugs in continuous
aggregates, time_bucket_gapfill, partial index handling and drop_chunks.
**Minor Features**
* #1666 Support drop_chunks API for continuous aggregates
* #1711 Change log level for continuous aggregate materialization messages
**Bugfixes**
* #1630 Print notice for COPY TO on hypertable
* #1648 Drop chunks from materialized hypertable
* #1668 Cannot add dimension if hypertable has empty chunks
* #1673 Fix crash when interrupting create_hypertable
* #1674 Fix time_bucket_gapfill's interaction with GROUP BY
* #1686 Fix order by queries on compressed hypertables that have char segment by column
* …

Release 1.6.1

---

src/chunk.c
src/chunk.h
src/dimension_slice.c
tsl/test/expected/compression_bgw.out
tsl/test/sql/compression_bgw.sql

The function `get_chunks_to_compress` return chunks that are not
compressed but that are dropped, meaning a lookup using
`ts_chunk_get_by_id` will fail to find the corresponding `table_id`,
which later leads to a null pointer when looking for the chunk. This
leads to a segmentation fault.
This commit fixes this by ignoring chunk that have are marked as
dropped in the chunk table when scanning for chunks to compress.
Part of timescale/timescaledb-private#673

Do not attempt to compress chunks that are dropped

---

.travis.yml

Timescale is notified internally about failed builds on Travis. This
update adds information about the last commit.
PR note:
I propose this change to see if a failure is on a new commit or was seen previously in the channel, since there are some flaky tests still.

Update Travis build fail notification with commit

---

sql/views.sql
tsl/test/expected/continuous_aggs_usage.out

If `ignore_invalidation_older_than` is undefined, it is set to maximum
for `BIGINT` type. This is not handled in `continuous_aggregates`
information schema so the column shows up as a very strange value.
This commit fixes this by checking if `ignore_invalidation_older_than`
is set to maximum, and uses `NULL` in the view in that case, which will
show up as empty.
Duplicate commit of timescale/timescaledb-private#624

Handle undefined ignore_invalidation_older_than

---

tsl/src/nodes/compress_dml/compress_dml.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

The CompressChunkDml custom scan was missing a rescan function
leading to a segfault in plans that required a rescan.
Fixes #1768

Add rescan function to CompressChunkDml CustomScan node

---

test/expected/append-10.out
test/expected/append-11.out
test/expected/append-9.6.out
test/sql/include/append_load.sql
test/sql/include/append_query.sql

The queries to produce test data for space partitioned
hypertables in the append test did not have an explicit
ORDER BY clause leading to a different ordering for the
chunks created on PG12.

Add explicit ORDER BY to append test data generation

---

tsl/src/continuous_aggs/materialize.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_query-10.out
tsl/test/expected/continuous_aggs_query-11.out
tsl/test/expected/continuous_aggs_query-9.6.out
tsl/test/isolation/expected/continuous_aggs_multi-10.out
tsl/test/isolation/expected/continuous_aggs_multi-11.out
tsl/test/isolation/expected/continuous_aggs_multi-9.6.out
tsl/test/sql/continuous_aggs.sql
tsl/test/sql/continuous_aggs_materialize.sql
tsl/test/sql/continuous_aggs_query.sql.in

Set the threshold for continuous aggregates as the
max value in the raw hypertable when the max value
is lesser than the computed now time. This helps avoid
unnecessary materialization checks for data ranges
that do not exist. As a result, we also prevent
unnecessary writes to the thresholds and invalidation
log tables.

Restrict watermark to max for continuous aggregates

---

sql/views.sql
tsl/test/expected/continuous_aggs_bgw.out

last_run_success value is reset when a job is started.
So mask the value if the status of a job is
running, otherwise it will show an incorrect state.
Fixes #1781 
For reviewers, here is the output from a running job and a scheduled job.  (the change in this PR is for the running job case).
test=# SELECT now(), * from timescaledb_information.continuous_aggregate_stats ;
now              | view_name | completed_threshold | invalidation_threshold | job_id |     
last_run_started_at      |    last_successful_finish     | **last_run_status | job_status** | last_run_durat
ion |      next_scheduled_run       | total_runs | total_successes | total_failures | total_crashes 
-------------------------------+-----------+---------------------+------------------------+--------+----- …

Modify continuous_aggregate_stats view definition

---

tsl/src/continuous_aggs/materialize.c

The function to get the materialization end point for a continuous
aggregate could use uninitialized min and max time values in its
calculations when a hypertable has no data.
This change ensures that the min and max time is initialized to
`INT64_MIN` and `INT64_MAX`, respectively, if no min and max value is
found.
This will mute warnings on some compilers.

Fix use of uninitialized variables in cont. aggs

---

src/utils.h
tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_union_view-10.out
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-9.6.out

The view definition for the union view was missing a cast from int8
to the actual int type used for hypertables with int partitioning
column this was not a problem on 64 bit systems but on 32 bit systems
int4 and int8 are represented differently.

Add missing cast to cagg union view

---

CHANGELOG.md
src/chunk_append/exec.c
src/chunk_append/exec.h
test/expected/parallel-10.out
test/expected/parallel-11.out
test/expected/parallel-9.6.out
test/sql/parallel.sql.in

We have to let the leader participate in plan execution
because the number of workers planned for a query
might be different from the number of workers
available. And even though a parallel plan was created
no parallel workers might be available during execution,
leading to incorrect results unless the leader participates
in execution.
This commit also changes the parallel EXPLAINs to not run with
ANALYZE because the output is not stable as it depends on
worker assignment.
Fixes #1793

Include parallel leader in plan execution

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/views.sql
src/catalog.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/options.c
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_union_view-10.out
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-9.6.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/sql/continuous_aggs_union_view.sql.in

Record materialized_only state of continuous aggregate view in
catalog and show state in timescaledb_information.continuous_aggregates.

Record cagg view state in catalog

---

CMakeLists.txt
test/expected/insert-10.out
test/expected/insert-11.out
test/expected/insert-12.out
test/expected/insert-9.6.out
test/sql/insert.sql.in

This adds a test for INSERTs with cached plans. This test causes
a segfault before 1.7 but was fixed independantly by the refactoring
of the INSERT path when adding PG12 support.
Fixes #1809

Add test for INSERT in cached plans

---

src/hypertable.c
test/expected/chunk_utils_compression.out
test/sql/CMakeLists.txt
test/sql/chunk_utils.sql
test/sql/chunk_utils_compression.sql

When calling show_chunks or drop_chunks without specifying
a particular hypertable TimescaleDB iterates through all
existing hypertables and builds a list. While doing this
it adds the internal '_compressed_hypertable_*' tables
which leads to incorrect behaviour of
ts_chunk_get_chunks_in_time_range function. This fix
filters out the internal compressed tables while scanning
at ts_hypertable_get_all function.
Fixes #1535

Fix ts_hypertable_get_all for compressed tables

---

src/continuous_agg.c

There is a potential null pointer dereference in that `raw_hypertable`
might be NULL when counting the number of continuous aggregates
attached. This commit fixes this by assuming that no continuous
aggregates are attached if `raw_hypertable` is NULL.
Found using `clang-tidy`.

Fix null pointer deref in continuous aggregates

---

CMakeLists.txt

This change improves cmake check for PostgreSQL minor/patch versions
and makes it consistent with src/compat.h version check

Improve cmake PostgreSQL version check

---

src/net/conn_plain.c

The symbol `pgwin32_socket_strerror` was undefined on windows builds at
PG12 and later. This because the function was removed and instead
`pg_strerror` was introduced to be used on all platforms.
This commit fixes the issue by ensuring to use `pg_strerror` on PG12
and later, and `pgwin32_socket_strerror` on Windows builds before PG12.

Define strerror() for Windows

---

.clang-tidy
CMakeLists.txt

Adding a custom target `clang-tidy` that will run `run-clang-tidy` if
it is available and the compiler database is enabled. If the compiler
database is not enabled but `run-clang-tidy` is found, a warning will
be printed and the custom command will not be added.

Enable clang-tidy

---

docs/BuildSource.md

PostgreSQL 12 is supported since 1.7, while 9.6 and 10 are deprecated.
This PR updates the building from source instruction with this change
and uses 1.7.0 in examples.

Update build from source instructions for 1.7

---

src/copy.c
test/expected/copy.out
test/sql/copy.sql

When copying from standard input the range table was not set up to
handle the constraints for the target table and instead is initialized
to null. In addition, the range table index was set to zero, causing an
underflow when executing the constraint check. This commit fixes this
by initializing the range table and setting the index correctly.
The code worked correctly for PG12, so the code is also refactored to
ensure that the range table and index is set the same way in all
versions.
Fixes #1840

Fix segfault on COPY to hypertable

---

src/bgw/job.c
src/hypertable.c
src/hypertable_cache.h
src/import/planner.h
src/plan_add_hashagg.c
src/process_utility.c
test/CMakeLists.txt
tsl/src/compression/create.c
tsl/src/compression/deltadelta.c
tsl/src/compression/gorilla.c
tsl/src/compression/simple8b_rle.h
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/nodes/gapfill/exec.c
tsl/src/reorder.c

This change fixes various compiler warnings that show up on different
compilers and platforms. In particular, MSVC is sensitive to functions
that do not return a value after throwing an error since it doesn't
realize that the code path is not reachable.

Silence various compiler warnings

---

src/bgw/scheduler.c

Trying to use an invalid time for a job raises an error.
This case should be checked  by the scheduler. Failure to
do so results in the scheduler being killed.
To reviewers:
This is related to a failure reported on support. Found this issue by looking at the logs.
I am not able to reliably reproduce this. So I don't have a test case in the regression suite. We would hit this case if we are running the job for the first time and the bgw fails to start.

Validate job time to avoid error thrown by scheduler

---

CMakeLists.txt

The formatting requires `clang-format` version 7 or 8, but if a later
distro is used it will find a version that cannot be used and default
to using docker even if the user installs an earlier version of
`clang-format` in parallel with the default version.
This commit fixes this by looking for `clang-format-8` and
`clang-format-7` before `clang-format`.

Change lookup of clang-format version

---

src/chunk.c
src/chunk.h
src/chunk_constraint.c
src/chunk_index.c
src/chunk_index.h
src/chunk_insert_state.c
src/hypertable.c
src/hypertable.h
src/plan_expand_hypertable.c
src/planner.c
src/process_utility.c
src/trigger.c
src/trigger.h
tsl/src/bgw_policy/job.c
tsl/src/compression/compress_utils.c
tsl/src/compression/create.c
tsl/src/continuous_aggs/insert.c
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/planner.c
tsl/src/reorder.c

The internal chunk API is updated to avoid returning `Chunk` objects
that are marked `dropped=true` along with some refactoring, hardening,
and cleanup of the internal chunk APIs. In particular, chunks could
previously be returned in a partial state (without all fields set,
partial constraints, etc.) and this is no longer allowed. Further,
lock handling was unclear when joining chunk metadata from different
catalog tables. This is more clear now by having chunks built within
the scan loop so that proper locks are held when reading other
metadata (such as constraints).
This change also fixes issues with dropped chunks that caused chunk
metadata to be processed many times instead of just once, leading to
potential bugs or bad performance.
In particular, since the introduction of the …

Improve handling of "dropped" chunks 

---

CHANGELOG.md
tsl/src/nodes/decompress_chunk/qual_pushdown.c
tsl/test/expected/compression_qualpushdown-10.out
tsl/test/expected/compression_qualpushdown-11.out
tsl/test/expected/compression_qualpushdown-12.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression_qualpushdown.sql.in

Operators used for qual pushdown for compressed chunks
should take the RHS expression's type into account.
Fixes #1855

Fix qual pushdown for compression

---

CMakeLists.txt

CMake file is missing the path suffix for PG 12 when searching for
PostgreSQL binaries. This commit adds the path suffix for 12.

Add 12 folder to search for PG bin in CMake

---

src/extension.c

If a binary upgrade is in progress (when using `pg_upgrade`) the
per-database setting of `timescaledb.restoring` can be included in the
dump, which causes `pg_upgrade` to fail.
This commit fixes this by checking the global variable
`IsBinaryUpgrade` and not refreshing cache if we are in the middle of
doing a binary upgrade.
Fixes #1844

Don't rely on timescaledb.restoring for upgrade

---

.gitignore

Adds build output on Windows and CMake settings for VS to gitignore.

Ignore Windows build files

---

CHANGELOG.md
src/planner.c
test/expected/plan_hypertable_cache.out
test/sql/CMakeLists.txt
test/sql/plan_hypertable_cache.sql

When classify_relation is called for relations of subqueries it
would not be able to correctly classify the relation unless it
was already in cache. This patch changes classify_relation to
call get_hypertable without CACHE_FLAG_NOCREATE when the RangeTblEntry
has the inheritance flag set.
Fixes #1832

Fix hypertable detection in subqueries

---

src/dimension_slice.c
src/dimension_slice.h
tsl/src/bgw_policy/job.c
tsl/test/expected/compress_bgw_reorder_drop_chunks.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compress_bgw_reorder_drop_chunks.sql

Reorder policy does not skip compressed chunks when selecting
next chunk to apply reordering. This causes an error in job
execution since it's not possible to reorder compressed chunks.
With this fix the job excludes compressed chunks from selection.
Fixes #1810

Fix reorder policy job to skip compressed chunks

---

CHANGELOG.md
tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_union_view-10.out
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-12.out
tsl/test/expected/continuous_aggs_union_view-9.6.out
tsl/test/sql/continuous_aggs_union_view.sql.in

Continuous aggregates with real time support did not propagate
WHERE and HAVING clauses to the direct query on the table.
Fixes #1860

Support WHERE and HAVING clauses for real time aggregation

---

test/expected/plan_hypertable_cache.out
test/sql/plan_hypertable_cache.sql

The `plan_hypertable_cache` test used `current_date` to generate data,
which is inherently flaky since it can create a different number of
chunks depending on which date you start at. When the number of chunks
differ, the test output changes too.

Fix flaky hypertable cache plan test

---

src/func_cache.c
src/sort_transform.c
tsl/test/expected/gapfill.out
tsl/test/expected/plan_gapfill-10.out
tsl/test/expected/plan_gapfill-11.out
tsl/test/expected/plan_gapfill-12.out
tsl/test/expected/plan_gapfill-9.6.out
tsl/test/sql/gapfill.sql
tsl/test/sql/plan_gapfill.sql.in

This commit adds the optimization pushing down sort orders to the underlying time column to `time_bucket_gapfill`. This is made slightly more invasive by the fact that `time_bucket_gapfill` is marked as `VOLATILE` (to prevent postgres from moving it in inappropriate ways) so we much manually fix up orderings ourselves.
This PR requires @svenklemm's review, as he wrote the gapfill code, and @cevian is marked as he requested the feature

Improve time_bucket_gapfill optimizations

---

src/extension.c

This change removes a `DEBUG1` level log message that was added to the
`ts_extension_is_loaded` check. The problem with this message is that
it is called very frequently, e.g., in planning, and it will flood the
output log.

Remove DEBUG logging in extension check 

---

.github/workflows/windows-build-and-test.yaml

[ Resubmitting this PR from a branch in base repo to see if it triggers a build ]
Windows builds, for Debug and Release configurations, are now tested
using GitHub Actions. The build test covers all currently supported
PostgreSQL versions (9.6, 10, 11, 12) using a build matrix.
Currently, the TimescaleDB regression test suite is not run since it
requires a Windows-specific test client that we do not
support. Instead, the binaries are tested by doing a `CREATE
EXTENSION` to verify that they load and run without, e.g., missing
symbols or similar.
The test configuration is optimized for speed by using a cache for the
PostgreSQL installation. This avoids repeated downloads and
installations of PostgreSQL from EnterpriseDB's servers. But it also
means that we won't have a full installation on …

Run Windows builds and tests using GitHub Actions

---

CHANGELOG.md
src/chunk_append/exec.c

When running a parallel ChunkAppend query, the code would use a
subplan selection routine for the leader that would return an empty
slot unless it determined there were no workers started. While this
had the desired effect of forcing the workers to do the work of
evaluating the subnodes, returning an empty slot is not always safe.
In particular, Append nodes will interpret an empty slot as a sign
that a given subplan has completed, so a plan resulting in a
parallel MergeAppend under an Append node (very possible under a
UNION of hypertables) might fail to execute some or all of the
subplans.
This change modifies the ChunkAppend so that the leader uses the
same subplan function as the workers. This may result in the leader
being less responsive as it try to fetch a batch of results on its …

Change ChunkAppend leader to use worker subplan

---

src/chunk_append/exec.c

This removes warning of a function declared static but never defined.

Remove unused static declaration of a function

---

appveyor.yml

Change appveyor script to run regression tests against PG12 on
Windows. It is short term solution with official PG alpine image.
No EXEC_BACKEND is enabled.

Run Windows regression tests on PG12

---

src/hypertable_insert.c
test/expected/insert-10.out
test/expected/insert-11.out
test/expected/insert-12.out
test/expected/insert-9.6.out
test/sql/insert.sql.in

Apparently modify table state is not created with an empty tables, which lead to NULL pointer evaluation.
Fixes #1883.

Fix crash on SELECT WHERE NOT with empty table

---

CHANGELOG.md
sql/CMakeLists.txt
sql/updates/README.md
sql/updates/post-update.sql
sql/util_time.sql
src/extension.c
tsl/src/continuous_aggs/create.c
tsl/test/expected/continuous_aggs_multi.out
tsl/test/expected/continuous_aggs_query-10.out
tsl/test/expected/continuous_aggs_query-11.out
tsl/test/expected/continuous_aggs_query-12.out
tsl/test/expected/continuous_aggs_query-9.6.out
tsl/test/expected/continuous_aggs_union_view-10.out
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-12.out
tsl/test/expected/continuous_aggs_union_view-9.6.out
tsl/test/expected/jit-11.out
tsl/test/expected/jit-12.out
tsl/test/isolation/expected/continuous_aggs_multi.out
tsl/test/isolation/specs/continuous_aggs_multi.spec
tsl/test/sql/continuous_aggs_multi.sql
tsl/test/sql/continuous_aggs_union_view.sql.in

We should compute the watermark using the materialization
hypertable id and not by using the raw hypertable id.
New test cases added to continuous_aggs_multi.sql. Existing test
cases in continuous_aggs_multi.sql were not correctly updated
for this feature.
Fixes #1865

Fix real time aggregate support for multiple aggregates

---

.travis.yml
CMakeLists.txt
test/expected/test_utils.out
test/sql/CMakeLists.txt
test/sql/test_utils.sql
test/src/CMakeLists.txt
test/src/adt_tests.c
test/src/bgw/params.c
test/src/bgw/scheduler_mock.c
test/src/net/test_http.c
test/src/test_time_to_internal.c
test/src/test_utils.c
test/src/test_utils.h
test/src/test_with_clause_parser.c
tsl/test/src/CMakeLists.txt
tsl/test/src/test_compression.c
tsl/test/src/test_ddl_hook.c

Test code in C should use test-specific assertions that throw errors
instead of exiting the program with a signal (crash). Not only does
this provide more useful and easily accessible information of the
failing condition, but it also allows running the test suite without
assertions (`USE_ASSERT_CHECKING`) enabled. Having assertions disabled
during tests also provides more accurate test coverage numbers. Note
that these test-specific assertions are not intended to replace
regular assertions (`Assert`), which are used in non-test code.
The way to enable (or disable) assertions in CMake has also been
simplified and cleaned up. The option `-DASSERTIONS=[ON|OFF]` can be
used to enable assertions for a build, unless already enabled in the
PostgreSQL one is building against (in which case that …

Use test-specific assertions in C test code

---

CHANGELOG.md
sql/CMakeLists.txt
version.config

This maintenance release contains bugfixes since the 1.7.0 release. We deem it medium
priority for upgrading and high priority for users with multiple continuous aggregates.
In particular the fixes contained in this maintenance release address bugs in continuous
aggregates with real-time aggregation and PostgreSQL 12 support.
**Bugfixes**
* #1834 Define strerror() for Windows
* #1846 Fix segfault on COPY to hypertable
* #1850 Fix scheduler failure due to bad next_start_time for jobs
* #1851 Fix hypertable expansion for UNION ALL
* #1854 Fix reorder policy job to skip compressed chunks
* #1861 Fix qual pushdown for compressed hypertables where quals have casts
* #1864 Fix issue with subplan selection in parallel ChunkAppend
* #1868 Add support for WHERE, HAVING clauses with real time …

Release 1.7.1

---

test/sql/updates/post.continuous_aggs.v2.sql
test/sql/updates/post.v6-pg10.sql
test/sql/updates/post.v6-pg11.sql
test/sql/updates/post.v6-pg12.sql
test/sql/updates/post.v6-pg96.sql
test/sql/updates/setup.continuous_aggs.v2.sql

This patch adds a continuous aggregate with real-time aggregation
enabled to the update test suite since we rebuild view definition
for real time aggregation during extension update.
The continuous aggregate is in its own schema because all view
definitions in the public schema are dumped and those view
definitions will change between versions.

Add real-time aggregation test to update test

---

CHANGELOG.md
src/extension_utils.c

The extension_current_state is called in the cache_invalidate_callback
which might be called in a background worker when the database has not
been initialized yet leading to a "cannot read pg_class without having
selected a database" error.
This patch adds a check for this condition to prevent this error.
Fixes #1847

Check for database in extension_current_state

---

.travis.yml
CMakeLists.txt
codecov/CMakeLists.txt
codecov/README.md
test/CMakeLists.txt

The code coverage options for CMake have been cleaned up and fixed
where they were broken. Build targets for local coverage reports now
work. The option to enable code coverage has been changed to
`-DCODECOVERAGE=ON` and local HTML-based reports can be generated
using the `lcov` program through the following steps:
1. `make install`
2. `make installcheck`
3. `make coverage`
The previous CMake options and targets didn't properly work, and often
included redundant and confusing options.
For instance, the only compiler option needed for code coverage is
`--coverage` as this is an alias for `-fprofile-arcs
-ftest-coverage`. Previously, however, these options were added
multiple times in various places, often all of them, but sometimes
only a subset for no apparent reason. They were also added …

Cleanup code coverage and make it work locally

---

CHANGELOG.md
src/chunk_index.c
src/chunk_index.h
src/process_utility.c
test/expected/cluster.out
test/expected/index.out
test/sql/index.sql
tsl/test/expected/plan_gapfill-10.out
tsl/test/expected/plan_gapfill-11.out
tsl/test/expected/plan_gapfill-12.out
tsl/test/expected/plan_gapfill-9.6.out
tsl/test/expected/transparent_decompression-10.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/expected/transparent_decompression-12.out

This patch changes chunk index creation to use the same functions
for creating index in one transaction and using multiple transactions.
The single transaction index creation used to adjust the original
stmt and adjusted it for the chunk which lead to problems with table
references not being adjusted properly for the chunk.
Fixes #1866

Unify chunk index creation

---

.travis.yml

Because add_link_options is not supported on older cmake versions
available in older postgresql docker images we only enable
code coverage on the codecov jobs.

Only enable codecoverage on specific travis jobs

---

.travis.yml

PostgreSQL released 12.3, 11.8, 10.13 and 9.6.18. So tests, which uses
latest PostgreSQL, are updated to these versions.

Update tests to run on newest PG

---

CMakeLists.txt
src/copy.c
tsl/src/compression/.clang-tidy
tsl/src/compression/deltadelta.c
tsl/src/compression/simple8b_rle.h
tsl/src/remote/cursor_fetcher.c
tsl/src/remote/dist_commands.c
tsl/src/remote/row_by_row_fetcher.c

This change replaces the existing `clang-tidy` linter target with
CMake's built-in support for it. The old way of invoking the linter
relied on the `run-clang-tidy` wrapper script, which is not installed
by default on some platforms. Discovery of the `clang-tidy` tool has
also been improved to work with more installation locations.
As a result, linting now happens at compile time and is enabled
automatically when `clang-tidy` is installed and found.
In enabling `clang-tidy`, several non-trivial issues were discovered
in compression-related code. These might be false positives, but,
until a proper solution can be found, "warnings-as-errors" have been
disabled for that code to allow compilation to succeed with the linter
enabled.

Improve linter support with clang-tidy

---

CMakeLists.txt
src/compat.h
src/debug_guc.c
src/import/allpaths.c
src/process_utility.c
src/utils.h
tsl/src/fdw/data_node_scan_plan.c

This change makes compiler warnings into errors by default on all
builds. This setting used to be applied on Travis builds, but was
removed (assumingly by accident) in a previous commit. The new
behavior can be disabled by including `-DWARNINGS_AS_ERRORS=OFF`
when running cmake.

Make compiler warnings into errors

---

version.config

We want to have the version in the master branch to be the
version of the next major release with a -dev suffix.
Actual release versions of the code will get their own respective
branches.

Set version in master to 2.0.0-dev

---

.travis.yml

This patch changes the travis configuration to make the coverity run
not depend on the result of other test runs and runs it on the
coverity_scan branch only since there is a quota on the number of
coverity runs we can do and we dont want to exceed it by multiple
pushes to prerelease_test.

Make travis coverity run not depend on other tests

---

tsl/src/compression/compress_utils.c
tsl/src/compression/create.c

This patch changes the order in which locks are taken during
compression to avoid taking strong locks for long periods on referenced
tables.
Previously, constraints from the uncompressed chunk were copied to the
compressed chunk before compressing the data. When the uncompressed
chunk had foreign key constraints, this resulted in a
ShareRowExclusiveLock being held on the referenced table for the
remainder of the transaction, which includes the (potentially long)
period while the data is compressed, and prevented any
INSERTs/UPDATEs/DELETEs on the referenced table during the remainder of
the time it took the compression transaction to complete.
Copying constraints after completing the actual data compression does
not pose safety issues (as any updates to referenced keys are caught by
the …

Change compression locking order

---

scripts/check_license.sh
scripts/check_license_all.sh
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-12.out
tsl/test/expected/jit-11.out
tsl/test/expected/jit-12.out
tsl/test/sql/continuous_aggs_union_view.sql.in
tsl/test/sql/include/jit_load.sql

This patch fixes the return code of the license check, previously
it would always return the return code of the apache license check.
This patch also adds a missing newline to the jit_load.sql file
so the license check properly detects the license.

Fix license check return code

---

sql/ddl_triggers.sql
test/expected/alternate_users.out
test/expected/copy.out
test/expected/ddl-11.out
test/expected/ddl-12.out
test/expected/ddl_single-11.out
test/expected/ddl_single-12.out
test/expected/pg_dump.out
test/expected/triggers.out
test/expected/truncate.out
test/sql/copy.sql
test/sql/include/ddl_ops_2.sql
test/sql/pg_dump.sql
test/sql/triggers.sql
test/sql/truncate.sql
tsl/test/expected/compression_ddl.out
tsl/test/expected/continuous_aggs_watermark.out
tsl/test/expected/ddl_hook.out
tsl/test/expected/dist_ddl.out
tsl/test/expected/dist_hypertable-11.out
tsl/test/expected/dist_hypertable-12.out
tsl/test/sql/compression_ddl.sql
tsl/test/sql/continuous_aggs_watermark.sql
tsl/test/sql/ddl_hook.sql
tsl/test/sql/dist_ddl.sql
tsl/test/sql/dist_hypertable.sql.in
tsl/test/sql/include/deparse_create.sql

Replace EXECUTE PROCEDURE with EXECUTE FUNCTION because the former
is deprecated in PG11+. Unfortunately some test output will still
have EXECUTE PROCEDURE because pg_get_triggerdef in PG11 still
generates a definition with EXECUTE PROCEDURE.

Use EXECUTE FUNCTION instead of EXECUTE PROCEDURE

---

CHANGELOG.md
tsl/src/nodes/gapfill/exec.c

When using time_bucket_gapfill with the treat_null_as_missing
option we did not properly set the number of valid values when
generating our own virtual tuples leading to "cannot extract
attribute from empty tuple slot" when the number of values got
reset. This patch changes the gapfill code to always set
the number of valid values when generating virtual tuples.
Fixes #1937

Fix gapfill locf treat_null_as_missing

---

src/CMakeLists.txt

Fixes null device on Windows to work in both CMD and PowerShell.

Use correct null device on Windows

---

sql/CMakeLists.txt
sql/updates/set_post_update_stage.sql
sql/updates/unset_update_stage.sql

This patch changes the update script generation to not use
scratch files and removes the sql fragments to set and unset
the post_update_stage from CMakeLists.txt and puts them into
dedicated files.

Change update script generation to not use scratch files

---

CMakeLists.txt
sql/CMakeLists.txt

Enabling clang-tidy on builds not using clang compiler will not
compile due to incompatible compiler flags, so this patch
changes the current behaviour to only enable clang-tidy when
using clang compiler. You can still overwrite the behaviour
by passing -DLINTER=ON when not using clang.

Enable linter only for clang compiler

---

src/chunk_index.c
tsl/test/expected/continuous_aggs_drop_chunks.out
tsl/test/sql/continuous_aggs_drop_chunks.sql

If a hypertable is created with an index on it and a continuous
aggregate is further defined on the hypertable, it will create an
internal dependency between the chunks of the hypertable and the chunks
of the continuous aggregate.
When dropping chunks with `cascade_to_materialization` set to `FALSE`,
this will generate an error since the delete is not cascaded to the
internal dependencies.
This commit fixes this by collecting the internal dependencies and
using `performMultipleDelete` rather than `performDelete` to delete
several objects as one operation.
Fixes #1889

Include internal dependencies in delete of chunks

---

CHANGELOG.md

This release adds new functionality on distributed hypertables,
including (but not limited to) basic LIMIT pushdown, manual chunk
compression, table access methods storage options,  SERIAL columns,
and altering of the replication factor.
This release only supports PG11 and PG12. Thus, PG9.6 and PG10
are no longer supported.
Note that the 2.0 major release will introduce breaking changes
to user functions and APIs. In particular, this beta removes the
cascade parameter from drop_chunks and changes the names of
certain GUC parameters. Expect additional breaking changes to be
introduced up until the 2.0 release.
**For beta releases**, upgrading from an earlier version of the
extension (including previous beta releases) is not supported.
**Features**
* #1877 Add support for fast pruning of …

Release 2.0.0-beta5

---

CMakeLists.txt

The `NOTICE` level for `message` doesn't exist in CMake 3.11, which is
our minimum supported version, so removing it.

Do not use NOTICE in CMake files

---

src/bgw/job_stat.c
tsl/src/continuous_aggs/materialize.c

GCC 7.5 warns that invalidation_range in continuous aggregate
materialization may be used uninitialized.
Older clang versons warn that res in calculate_next_start_on_failure
may be used uninitialized.
This patch changes the code to always initialize those two variables.

Initialize variables complained about by older compilers

---

src/adts/bit_array_impl.h

If `bits_used` is not exactly 64, a shift will be attempted, even when
`bits_used > 64`. According to the standard "[...] if the value of the
right operand is negative or is greater or equal to the number of bits
in the promoted left operand, the behavior is undefined."
Hence we change the code to return `PG_UINT64_MAX` if a request to
shift more bits than the number of bits in the type is requested,
otherwise we perform the shift.
Found using `clang-tidy`

Fix bit array left shift count

---

sql/dist_internal.sql
src/cache_invalidate.c
src/cross_module_fn.c
src/cross_module_fn.h
tsl/src/data_node.c
tsl/src/init.c
tsl/src/process_utility.c
tsl/src/remote/async.c
tsl/src/remote/async.h
tsl/src/remote/connection.c
tsl/src/remote/connection.h
tsl/src/remote/connection_cache.c
tsl/src/remote/connection_cache.h
tsl/src/remote/dist_commands.c
tsl/src/remote/dist_ddl.c
tsl/src/remote/dist_txn.c
tsl/src/remote/txn.c
tsl/src/remote/txn.h
tsl/src/remote/txn_store.c
tsl/src/remote/txn_store.h
tsl/test/expected/remote_txn.out
tsl/test/sql/remote_txn.sql
tsl/test/src/remote/async.c
tsl/test/src/remote/connection_cache.c

This change refactors how connections are handled during remote
transactions. In particular, the connection cache now stays consistent
during transactions, even during rollbacks. Previously, the connection
cache was replaced on every rollback, even if the rollback was
intentional (i.e, not due to an error). This made it hard to debug
connections since the cache became completely empty.
Connections could also be left in the cache in a bad state after
failed transactions. This has been fixed by moving connection checks
to the cache and tying transaction state changes to each
connection. This ensures that such checks are done in one canonical
place instead of being spread out throughout the code.
Given how tightly coupled a remote transaction is with its connection,
it might make sense to …

Improve connection handling during transactions

---

src/hypertable.c
tsl/test/expected/dist_hypertable-11.out
tsl/test/expected/dist_hypertable-12.out
tsl/test/sql/dist_hypertable.sql.in

Function `ts_hypertable_create_from_info` will error if the hypertable
already exists unless the if-not-exists flag is not set.  If we reach
this point, either if-not-exists-flag was set or the hypertable did not
exist and was created above.
In `ts_hypertable_create_from_info`, a call to
`ts_dimension_info_validate` with `space_dim_info` will be made if (and
only if) the table did not exist. The function does not only validate
the dimension, it also set `dimension_id` field.
If the table already existed, `created` will be false and the
`dimension_id` will be set to the invalid OID, which means that
`ts_hypertable_check_partitioning` will crash since it it expect a
proper OID to be passed.
This commit fixes that by checking if the hypertable exists prior to 
calling …

Fix crash with create_distributed_hypertable

---

.github/workflows/windows-build-and-test.yaml

PostgreSQL 12 is preinstalled, while 11 is not. To unify different 
paths of PG 11 and 12 binaries, this commit implements workaround by 
forcing installation of PostgreSQL 12, so it is in the same path as 
PostgreSQL 11.

Force installing PostgreSQL in GH Actions on Windows

---

tsl/test/expected/continuous_aggs_materialize.out
tsl/test/sql/continuous_aggs_materialize.sql

Replaces now() with mocked timestamp value in
continuous_aggs_materialize test, so the test doesn't produce
unexpected result when now() is close to a chunk border.

Remove flakiness of cagg materializaion test

---

tsl/src/remote/connection_cache.c
tsl/test/expected/remote_txn.out
tsl/test/sql/remote_txn.sql

The "invalidation" column was accidentally set as the "processing"
column in `show_connection_cache`. This made the output of these
columns show the wrong values. This change fixes this issue.

Fix output in function to show connection cache

---

tsl/src/chunk_api.c
tsl/src/remote/dist_commands.c
tsl/src/remote/dist_commands.h
tsl/test/expected/chunk_api.out
tsl/test/sql/chunk_api.sql

With replicated chunks, the function to import column stats would
experience errors when updating `pg_statistics`, since it tried to
write identical stats from several replica chunks.
This change fixes this issue by filtering duplicate stats rows
received from data nodes.
In the future, this could be improved by only requesting stats from
"primary" chunks on each data node, thus avoiding duplicates without
having to filter the result. However, this would complicate the
function interface as it would require sending a list of chunks
instead of just getting the stats for all chunks in a hypertable.

Fix ANALYZE on replicated distributed hypertable

---

test/expected/agg_bookends-11.out
test/expected/agg_bookends-12.out
test/expected/append-11.out
test/expected/append-12.out
test/expected/bgw_launcher.out
test/expected/drop_extension.out
test/expected/plan_ordered_append.out
test/runner.sh
test/sql/agg_bookends.sql.in
test/sql/append.sql.in
test/sql/bgw_launcher.sql
test/sql/include/bgw_launcher_utils.sql
test/sql/plan_ordered_append.sql
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-12.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/expected/transparent_decompression-12.out
tsl/test/shared/expected/constraint_exclusion_prepared.out
tsl/test/shared/expected/ordered_append-11.out
tsl/test/shared/expected/ordered_append-12.out
tsl/test/shared/sql/constraint_exclusion_prepared.sql
tsl/test/shared/sql/ordered_append.sql.in
tsl/test/sql/continuous_aggs_union_view.sql.in
tsl/test/sql/transparent_decompression.sql.in

The sql tests still had version checks and would run EXPLAIN
with different parameters depending on postgres version. Since
all supported postgres versions now support all the parameters
we use we can safely remove the version check.

Remove dynamic version checks from SQL tests

---

src/chunk.c
src/chunk_adaptive.c
src/dimension.c
src/hypertable.c
src/process_utility.c
src/process_utility.h
src/tablespace.c
tsl/src/data_node.c
tsl/src/hypertable.c
tsl/test/expected/read_only.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/read_only.sql

This change ensures that API functions which modify data respects read-only transaction state set by
`default_transaction_read_only` option.
Related to https://github.com/timescale/timescaledb/issues/1912

Add checks for read-only transactions

---

sql/restoring.sql

Setting the `timescaledb.restoring` guc explicitly to 'off'
for the db meant that the setting got exported in `pg_dumpall`
and some other cases where that setting would then conflict
with the setting set by the pre_restore function causing it to
be overridden and causing errors on restore. This changes to
`RESET` so that instead it will take the system default and not
be dumped separately as an override.

Reset restoring gucs rather than explicitly setting 'off'

---

.github/workflows/alpine-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
README.md
test/pg_regress.sh
test/runner.sh
test/runner_shared.sh

Since most of our regression tests run on GitHub actions now this
patch replaces the build status badge from Travis with a GitHub
actions one.

Replace Travis badge with GitHub badge

---

test/expected/drop_extension.out
test/sql/utils/testsupport.sql
tsl/test/expected/dist_hypertable-11.out
tsl/test/expected/dist_hypertable-12.out
tsl/test/expected/dist_query-11.out
tsl/test/expected/dist_query-12.out
tsl/test/sql/dist_hypertable.sql.in
tsl/test/sql/include/debugsupport.sql
tsl/test/sql/include/dist_query_load.sql
tsl/test/sql/include/dist_query_run.sql

testsupport.sql had a reference to TSL code which will fail in
apache-only code since this file is included in every test run
for every build configuration.

Change testsupport.sql to not reference tsl code

---

scripts/gh_matrix_builder.py

The log output in the isolation tests when running on PG 11.0 seems
to be suppressed and not be recorded leading to a diff in the test
output.

Ignore continuous_aggs_insert and continuous_aggs_multi on PG11.0

---

src/plan_expand_hypertable.c
tsl/test/shared/expected/constify_timestamptz_op_interval-11.out
tsl/test/shared/expected/constify_timestamptz_op_interval-12.out
tsl/test/shared/sql/.gitignore
tsl/test/shared/sql/CMakeLists.txt
tsl/test/shared/sql/constify_timestamptz_op_interval.sql.in

Constify expressions of the following form in WHERE clause:
column OP timestamptz - interval
column OP timestamptz + interval
column OP interval + timestamptz
Iff interval has no month component.
Since the operators for timestamptz OP interval are marked
as stable they will not be constified during planning.
However, intervals without a month component can be safely
constified during planning as the result of those calculations
do not depend on the timezone setting.

Constify TIMESTAMPTZ OP INTERVAL in constraints

---

src/cross_module_fn.c
src/cross_module_fn.h
src/process_utility.c
src/process_utility.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/create.h

Introduce and use explicit enum type for process utility functions return
value instead of using bool type.

Refactor process utility functions result type

---

appveyor.yml
tsl/test/expected/transparent_decompression-11.out
tsl/test/expected/transparent_decompression-12.out
tsl/test/expected/transparent_decompression_ordered_index-11.out
tsl/test/expected/transparent_decompression_ordered_index-12.out
tsl/test/sql/.gitignore
tsl/test/sql/CMakeLists.txt
tsl/test/sql/include/transparent_decompression_constraintaware.sql
tsl/test/sql/include/transparent_decompression_ordered_index.sql
tsl/test/sql/include/transparent_decompression_query.sql
tsl/test/sql/transparent_decompression.sql.in
tsl/test/sql/transparent_decompression_ordered_index.sql.in

This PR reduces the dataset size in the transparent_decompression
test to make it finish in a more reasonable time. It also splits
the test.

Refactor transparent_decompression test

---

tsl/test/sql/CMakeLists.txt

This patch adds parallel execution capabilities to regresscheck-t.

Execute regresscheck-t tests in parallel

---

src/cache_invalidate.c
tsl/src/remote/connection_cache.c

It is incorrect to forward relcache invalidations as syscache invalidations, like `cacheid = InvalidOid` which is not possible condition at the moment. Allow syscache invalidations only for `FOREIGNSERVEROID`s.
Related to: http://github.com/timescale/timescaledb/issues/2001

Do not forward relcache invalidation as syscache invalidation

---

.github/workflows/alpine-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
scripts/gh_matrix_builder.py

Check for coredumps and only execute the stracktrace if there are
actually coredumps. This also changes the log handling to always
collect logs and upload them cause they might have useful
information even when all steps succeed.

Improve github action stacktrace handling

---

.github/workflows/alpine-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
scripts/bundle_coredumps.sh

This patch adds collecting coredumps to the regression workflow
in addition to the binary all shared libraries used by the coredump
are collected as well.

Upload coredumps as artifact

---

src/trigger.c

The TriggerDesc from rel->trigdesc seems to be modified during
iterations of the loop and sometimes gets reallocated leading
to a situation where the local variable trigdesc no longer matches
rel->trigdesc leading to a segfault in create_trigger_handler.
Fixes  #2013

Fix segfault in create_trigger_handler

---

.github/workflows/linux-build-and-test.yaml
test/pg_isolation_regress.sh
test/pg_regress.sh
tsl/test/sql/CMakeLists.txt

When either TESTS, SKIPS or IGNORES is set for a regression check
run we would generate a new temporary schedule based on those
variables without any parallelity. This patch changes the behaviour
to keep the original test schedule when only parallel is specified
and just prepend the ignore lines to a copy of the original schedule.

Retain parallel schedule when using IGNORES

---

tsl/src/continuous_aggs/create.c

Since relation_close will decrease the reference counter this
might lead to the relation being freed while we are still using
the view query. This patch changes cagg_update_view_definition
to release the relations later and also keeps the locks till
the end of the transaction.
Fixes #2042

Fix segfault in cagg_update_view_definition

---

src/chunk.h
tsl/src/remote/dist_copy.c

This change copies the chunk object into the distributed copy's
memory context before caching it in the ChunkConnectionList. This
resolves an issue where the chunk was being modified after being
stored which was resulting in rows being sent to the incorrect
data node.
Fixes #2037

Fix potential mem corruption in distributed copy

---

.github/workflows/apt-packages.yaml
.github/workflows/linux-build-and-test.yaml

This workflow will install our apt package and then try to enable
timescaledb in the database and also check the version installed
from the package against the expected version.

Add testing for released apt packages

---

test/expected/insert-11.out
test/expected/insert-12.out
test/sql/insert.sql.in

If a unique constraint is created on a hypertable, it could under some
circumstance crash. This commit adds a test for this situation even
though it was already fixed (but was reported on the 1.7 branch).
Test for #1699

Add tests for hypertable unique constraint crash

---

src/chunk_insert_state.c
test/expected/insert-10.out
test/expected/insert-11.out
test/expected/insert-12.out
test/expected/insert-9.6.out
test/sql/insert.sql.in

Previously, the memory context for the chunk insert state was freed
using a reset callback on the per-tuple context. This created an
unfortunate cyclic dependency between memory contexts, since both the
per-tuple context and chunk insert state shared the same memory
context parent (the query memory context).
Thus, when deletion happens by calling MemoryContextDelete on the
parent, without having deleted the children first, the parent could
first delete the chunk insert state child, followed by the per-tuple
context which then tried to delete the chunk insert state again.
A better way to handle this is to simply switch the parent of the
chunk insert state's memory context to be the per-tuple context as
long as it is still valid, thus breaking the cycle.
Fixes #1699
Part of #824

Better handling of chunk insert state destruction

---

tsl/src/compression/create.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

When enabling compression on a hypertable the existing
constraints are being cloned to the new compressed hypertable.
During validation of existing constraints a loop
through the conkey array is performed, and constraint name
is erroneously added to the list multiple times. This fix
moves the addition to the list outside the conkey loop.
Fixes #2000

Enable compression for tables with compound foreign key

---

tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/shared/expected/decompress_placeholdervar.out
tsl/test/shared/sql/CMakeLists.txt
tsl/test/shared/sql/decompress_placeholdervar.sql

When the relation targetlist of the uncompressed chunk contained
PlaceHolderVars the construction of the relation targetlist of
the compressed chunk would fail with an error. This patch changes
the behaviour to recurse into those PlaceHolderVar.
Fixes #1981

Fix handling of PlaceHolderVar in DecompressChunk

---

sql/chunk_constraint.sql
test/expected/alter.out
test/sql/alter.sql

If a tablespace is provided for an index on a hypertable, it will be
also used for the index on new chunks.
Fixes #903

Use index tablespace during chunk creation

---

sql/updates/latest-dev.sql
src/bgw/job.c
src/chunk.c
src/chunk.h
src/dimension_slice.c
src/dimension_slice.h
src/hypercube.c
src/hypercube.h
src/hypertable_restrict_info.c
src/scanner.c
src/scanner.h
test/isolation/expected/insert_dropchunks_race.out
test/isolation/specs/CMakeLists.txt
test/isolation/specs/insert_dropchunks_race.spec

If a dimension slice tuple is found while adding new chunk constraints
as part of a chunk creation it is not locked prior to adding the chunk
constraint. Hence a concurrently executing `drop_chunks` can find a
dimension slice unused (because there is no chunk constraint that
references it) and subsequently remove it. The insert will the continue
to add the chunk constraint with a reference to a now non-existent
dimension slice.
This commit fixes this by locking the dimension slice tuple with a
share lock and locking the dimension slice with an exclusive lock
prior to scanning for existing chunk constraints.
There is an isolation test as a separate commit.
An update script is added that will reconstruct the missing dimension slices and insert them into the `dimension_slice` table. It has …

Add locks for dimension slice tuples

---

scripts/check_license_all.sh
tsl/test/shared/expected/constraint_exclusion_prepared.out
tsl/test/shared/expected/ordered_append-11.out
tsl/test/shared/expected/ordered_append-12.out
tsl/test/shared/sql/include/constraint_exclusion_prepared.sql
tsl/test/shared/sql/include/ordered_append_query.sql
tsl/test/shared/sql/include/shared_setup.sql

This adds the directories used by regresscheck-shared to the license
check and adds a license where it is currently missing.

Add regresscheck-shared sql files to license check

---

.github/workflows/rpm-packages.yaml

This workflow will install our rpm packages and then try to enable
timescaledb in the database and also check the version installed
from the package against the expected version.

Add testing for RPM packages

---

tsl/src/continuous_aggs/materialize.c
tsl/test/isolation/expected/continuous_aggs_multi.out
tsl/test/isolation/specs/continuous_aggs_multi.spec

When we have multiple continuous aggregates defined on
the same hypertable, they could try to delete the hypertable
invalidation logs concurrently. Resolve this by serializing
invalidation log deletes by hypertable id.
Fixes #1940

Fix tuple concurrently deleted error with multiple continuous aggregates

---

.github/workflows/apt-packages.yaml
tsl/test/expected/chunk_api.out
tsl/test/sql/chunk_api.sql

The chunk_api test fails sometimes because of inconsistent resultset
ordering in one of the queries. This patch adds the missing ORDER BY
clause to that query.

Add missing ORDER BY clause to chunk_api test

---

src/chunk.c
src/dimension_slice.c
src/dimension_slice.h

One parameter was always true. This commit remove the parameter and
update the logic to match the existing usage.

Remove ts_dimension_slice_insert_multi parameter

---

src/chunk_dispatch_state.c
src/chunk_insert_state.c

This change removes some code paths that are no longer used after the
removal of PG10 and PG9.6 support.

Cleanup unused code paths

---

.github/workflows/apt-packages.yaml
.github/workflows/rpm-packages.yaml
scripts/gh_matrix_builder.py

This patch removes Debian 8 from the package test since its no
longer supported. This patch also fixes the repository URL for
centos 8.

Remove debian 8 from package test

---

tsl/src/nodes/gapfill/exec.c
tsl/test/expected/gapfill.out
tsl/test/sql/gapfill.sql

Infering start and stop parameter used to only work for top
level constraints. However even when constraints are at the
toplevel in the query they might not end up at the top-level
of the jointree depending on the plan shape. This patch
changes the gapfill code to traverse the jointree to find
valid start and stop arguments.

Improve infering start and stop arguments from gapfill query

---

test/sql/updates/post.post_insert.sql

The update test checks that default jobs are the same before and after
an upgrade, but does not order the jobs in any specific way. This means
that if the database order is different before and after the update, it
will result in a false negative even if the jobs are identical.
This commit fixes this by ordering the jobs by id.

Fix update tests

---

src/process_utility.c
test/expected/alter.out
test/sql/alter.sql
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression_ddl.sql

Allow ALTER SET TABLESPACE on an uncompressed chunk and automatically execute it on the associated compressed chunk,
if any. Block SET TABLESPACE command for compressed chunks.
Issue #2068

Apply SET TABLESPACE for compressed chunks

---

CHANGELOG.md
src/process_utility.c
test/expected/index.out
test/sql/index.sql

When creating an index with IF NOT EXISTS we still tried to
create indexes for all the chunks but since no index was created
on the parent table the meta data did not have the object id of
the main table index leading to an error when trying to open
the main table index. This patch adjusts the logic to check
for IF NOT EXISTS and does an early return when no index was
created on the parent table.
Fixes #2081

Fix index creation with IF NOT EXISTS for existing indexes

---

tsl/test/isolation/specs/compression_ddl.spec
tsl/test/isolation/specs/continuous_aggs_insert.spec
tsl/test/isolation/specs/continuous_aggs_multi.spec
tsl/test/isolation/specs/reorder_deadlock.spec.in
tsl/test/isolation/specs/reorder_vs_insert.spec.in
tsl/test/isolation/specs/reorder_vs_insert_other_chunk.spec.in
tsl/test/isolation/specs/reorder_vs_select.spec.in

Adding Timescale License header to specs of isolation TSL tests.

Add license note to TSL isolation test

---

tsl/test/expected/dist_api_calls.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/dist_api_calls.sql

Testing that drop_chunks works correctly on a distributed hypertable.
Tests of different arguments are assumed to be done on a usual
hypertable previously.

Add test of drop_chunks on distributed hypertable

---

src/init.c
src/loader/loader.c
src/net/conn.c
src/net/conn.h
src/net/conn_plain.c
src/net/conn_ssl.c
src/telemetry/telemetry.h
test/src/loader/init.c
test/src/net/conn_mock.c

The `pg_config.h` file in the PostgreSQL include directory does not
contain any include guards, so including it will generate errors when
building from PGDG-distributed packages.
Since `pg_config.h` is included from `c.h` (which has include guards)
which in turn is included from `postgres.h` (which also has include
guards), we remove usage of `pg_config.h` from all places where
`postgres.h` is included and replace it with `postgres.h` where it is
not included.

Remove include of pg_config.h

---

src/chunk.c
src/chunk.h
tsl/src/reorder.c
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression_ddl.sql

Allow move_chunk() to work with uncompressed chunk and automatically move associated compressed chunk to specified
tablespace. Block move_chunk() execution for compressed chunks.
This change executes alter set tablespace underneath for compressed chunk. I guess it we might also use index used for orderby compression and call chunk_reorder() with it, not really sure if that would work.
Related issue: https://github.com/timescale/timescaledb/issues/2067

Support moving compressed chunks

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
src/bgw/job.c
src/bgw/job.h
src/bgw/scheduler.c
src/catalog.c
src/catalog.h
src/jsonb_utils.c
src/jsonb_utils.h
test/expected/bgw_db_scheduler.out
test/sql/bgw_db_scheduler.sql
tsl/src/license.c

This patch makes the scheduler ignore all jobs where scheduled = false.
The schedule flag can be used to disable jobs without deleting the job
entry.
This patch also changes the job retrieval to use an index scan to
satisfy the assumption of the scheduler to receive a list ordered
by job_id.

Make scheduler ignore jobs where scheduled = false

---

src/chunk.c
src/process_utility.c
test/expected/grant_hypertable.out
test/expected/rowsecurity-11.out
test/expected/rowsecurity-12.out
test/sql/CMakeLists.txt
test/sql/grant_hypertable.sql
tsl/test/expected/dist_grant.out
tsl/test/sql/dist_grant.sql

Whenever chunks are created, no privileges are added to the chunks.
For accesses that go through the hypertable permission checks are
ignored so reads and writes will succeed anyway. However, for direct
accesses to the chunks, permission checks are done, which creates
problems for, e.g., `pg_dump`.
This commit fixes this by propagating `GRANT` and `REVOKE` statements
to the chunks when executed on the hypertable, and whenever new chunks
are created, privileges are copied from the hypertable.
Fixes #1927

Propagate privileges from hypertables to chunks

---

.github/workflows/update-test.yaml
scripts/test_update_from_tag.sh

This patch adds the diff output of the update in a separate step
in the workflow and also uploads the update test diff as artifact.
Fixes #2139

Improve update test github output

---

test/expected/extension.out
test/sql/extension.sql
tsl/test/sql/CMakeLists.txt

The chunk_api test requires a debug build for certain test functions
this patch changes the chunk_api test to only run for debug builds.

Only run chunk_api test on debug build

---

sql/ddl_api.sql
src/continuous_agg.c
src/continuous_agg.h
src/cross_module_fn.c
src/cross_module_fn.h
test/expected/extension.out
tsl/src/continuous_aggs/CMakeLists.txt
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/src/init.c
tsl/test/expected/continuous_aggs_refresh.out
tsl/test/isolation/expected/continuous_aggs_concurrent_refresh.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/continuous_aggs_concurrent_refresh.spec
tsl/test/sql/CMakeLists.txt
tsl/test/sql/continuous_aggs_refresh.sql

This change adds a new refresh function called
`refresh_continuous_aggregate` that allows refreshing a continuous
aggregate over a given window of data, called the "refresh window".
This is the first step in a larger overhaul of the continuous
aggregate feature with the goal of cleaning up the API and separating
policy from the core functionality.
Currently, the refresh function does a brute-force refresh of a window
and it bypasses the whole invalidation framework. Future updates
intend to integrate with this framework (with modifications) to
optimize refreshes. An exclusive lock is take on the continuous
aggregate's internal materialized hypertable in order to protect
against concurrent refreshing. However, as this serializes refreshes,
we might want to relax this locking in the future …

Add refresh function for continuous aggregates

---

tsl/test/expected/dist_hypertable-11.out
tsl/test/expected/dist_hypertable-12.out
tsl/test/sql/dist_hypertable.sql.in

Adds a test to call detach_tablespaces on a distributed hypertable.
Since no tablespaces can be attached to distributed hyperatbles, the
test detaches 0 tablespaces. Also a test to detach tablespaces on a
data node is added.

Test detach_tablespaces on distributed hypertable

---

tsl/src/data_node.c
tsl/src/dist_util.c
tsl/test/expected/data_node.out
tsl/test/sql/data_node.sql

If `add_data_node` is attempted with the same instance and database as
the one the `add_data_node` is executed on, it will deadlock since a
transaction is opened on the datanode which will block updates.
This commit fixes this by updating `set_dist_id` to check if the UUID
being added as `dist_uuid` is the same as the `uuid` in the metadata.
If that is the case, it raises an error.
In addition, it also checks that `uuid` is non-null and generate an
error if it is not. This should not normally happen, but can do for
broken data nodes if the `uuid` is accidentally dropped.
Fixes #2133

Add self-reference check to add_data_node

---

src/process_utility.c
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/continuous_aggs_dump.out
tsl/test/expected/continuous_aggs_errors.out
tsl/test/expected/continuous_aggs_materialize.out
tsl/test/expected/continuous_aggs_multi.out
tsl/test/expected/continuous_aggs_permissions.out
tsl/test/expected/continuous_aggs_union_view-11.out
tsl/test/expected/continuous_aggs_union_view-12.out
tsl/test/expected/continuous_aggs_usage.out
tsl/test/expected/transparent_decompression-11.out
tsl/test/expected/transparent_decompression-12.out
tsl/test/sql/bgw_reorder_drop_chunks.sql
tsl/test/sql/continuous_aggs.sql
tsl/test/sql/continuous_aggs_bgw.sql
tsl/test/sql/continuous_aggs_dump.sql
tsl/test/sql/continuous_aggs_errors.sql
tsl/test/sql/continuous_aggs_materialize.sql
tsl/test/sql/continuous_aggs_multi.sql
tsl/test/sql/continuous_aggs_permissions.sql
tsl/test/sql/continuous_aggs_union_view.sql.in
tsl/test/sql/continuous_aggs_usage.sql
tsl/test/sql/include/cont_agg_equal.sql
tsl/test/sql/include/transparent_decompression_query.sql

To drop a continuous aggregate it was necessary to use the `CASCADE`
keyword, which would then cascade to the materialized hypertable. Since
this can cascade the drop to other objects that are dependent on the
continuous aggregate, this could accidentally drop more objects than
intended.
This commit fixes this by removing the check for `CASCADE` and adding
the materialized hypertable to the list of objects to drop.
Fixes timescale/timescaledb-private#659

Remove requirement of CASCADE from DROP VIEW

---

src/catalog.c
src/catalog.h
src/scanner.c
src/scanner.h
tsl/src/continuous_aggs/CMakeLists.txt
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/continuous_aggs_invalidation.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/continuous_aggs_invalidation.sql

This change adds intitial support for invalidation processing when
refreshing a continuous aggregate. Note that, currently, invalidations
are only cleared during a refresh, but not yet used to optimize
refreshes. There are two steps to this processing:
1. Invalidations are moved from hypertable invalidation log to the
cagg invalidation log
2. The cagg invalidation entries are then processed for the continuous
aggregate that gets refreshed.
The second step involves finding all invalidations that overlap with
the given refresh window and then either deleting them or cutting
them, depending on how they overlap.
Currently, the "invalidation threshold" is not moved up during a
refresh. This would only be required if the refresh window crosses
that threshold and will be addressed in a future …

 Process invalidations when refreshing continuous aggregate 

---

tsl/test/expected/compression_bgw.out
tsl/test/sql/compression_bgw.sql

Compression is not enterprise feature anymore. Thus enabling
enterprise is not needed in tests.

Remove enabling enterprise from compression test

---

src/bgw/job.c
src/bgw/job.h
src/bgw/scheduler.c
src/bgw/scheduler.h
test/src/bgw/scheduler_mock.c

This patch changes the scheduler main loop to use a scratch
context during operation which gets reset after every scheduling
loop iteration.
Fixes #2115

Fix background worker scheduler memory consumption

---

.github/workflows/linux-build-and-test.yaml
src/telemetry/telemetry.c
test/expected/telemetry.out
test/sql/telemetry.sql

This patch changes the telemetry code to always send the installed_time
timestamp AS ISO8601. Previously it was depending on local settings
leading to timestamps not processable by the telemetry receiver.

Fix telemetry installed_time format

---

tsl/src/continuous_aggs/create.c
tsl/test/expected/dist_ddl.out
tsl/test/sql/dist_ddl.sql

Show an error message in case if a distributed hypertable being used.
Issue: https://github.com/timescale/timescaledb-private/issues/835

Add check for distributed hypertable to continuous aggs

---

appveyor.yml
test/expected/with_clause_parser.out
test/sql/CMakeLists.txt
tsl/test/expected/continuous_aggs_drop_chunks.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/continuous_aggs_drop_chunks.sql

The with_clause_parser and continuous_aggs_drop_chunks tests were
not referenced in the CMakeLists leading to those tests never being
run. This patch adds them to the appropriate file and adjusts the
output.

Add unreferenced test files to CMakeLists

---

sql/bgw_scheduler.sql
sql/updates/latest-dev.sql
src/bgw/job.c
test/expected/bgw_db_scheduler.out
tsl/test/expected/bgw_policy.out
tsl/test/expected/bgw_reorder_drop_chunks.out
tsl/test/expected/compress_bgw_reorder_drop_chunks.out
tsl/test/expected/compression_bgw.out
tsl/test/expected/continuous_aggs.out
tsl/test/expected/continuous_aggs_bgw.out
tsl/test/expected/tsl_tables.out

This patch changes the application name for background worker jobs
to include the job_id which makes the application name unique and
allows joining against pg_stat_activity to get a list of currently
running background worker processes. This change also makes
identifying misbehaving jobs easier from the postgres log as the
application name can be included in the log line.

Make application name for bgw jobs unique

---

tsl/src/reorder.c
tsl/test/expected/dist_api_calls.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/dist_api_calls.sql

Ensure that move_chunk() and reorder_chunk() functions cannot be used with distributed hypertable

Add check for distributed hypertable to reorder/move_chunk

---

.github/workflows/code_style.yaml
scripts/check_unreferenced_files.sh

This patch adds a check for test files not referenced in the
CMakeLists.txt file to CI.

Add check for unreferenced test files

---

sql/ddl_api.sql
tsl/src/continuous_aggs/CMakeLists.txt
tsl/src/continuous_aggs/invalidation_threshold.c
tsl/src/continuous_aggs/invalidation_threshold.h
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/continuous_aggs_invalidation.out
tsl/test/expected/continuous_aggs_refresh.out
tsl/test/isolation/expected/continuous_aggs_concurrent_refresh.out
tsl/test/isolation/specs/continuous_aggs_concurrent_refresh.spec
tsl/test/sql/continuous_aggs_invalidation.sql
tsl/test/sql/continuous_aggs_refresh.sql
tsl/test/src/test_continuous_aggs.c

The invalidation threshold governs the window of data from the head of
a hypertable that shouldn't be subject to invalidations in order to
reduce write amplification during inserts on the hypertable.
When a continuous aggregate is refreshed, the invalidation threshold
must be moved forward (or initialized if it doesn't previously exist)
whenever the refresh window stretches beyond the current threshold.
This change implements the functionality that initializes or moves the
invalidation threshold. This happens in its own transaction during a
refresh of a continuous aggregate in order to "publish" the new
threshold before materialization. The extra transaction requires an
access exclusive lock in order to avoid losing invalidations.
Some care has been taken to not unnecessarily lock the …

Set invalidation threshold during continuous aggregate refresh

---

tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/continuous_aggs_invalidation.out
tsl/test/sql/continuous_aggs_invalidation.sql

This change implements deduplication and merging of invalidation
entries for continuous aggregates in order to reduce the number of
reduntant entries in the continuous aggregate invalidation
log. Merging is done both when copying over entries from the
hypertable to the continuous aggregate invalidation log and when
cutting already existing invalidations in the latter log. Doing this
merging in both steps helps reduce the number of invalidations also
for the continuous aggregates that don't get refreshed by the active
refresh command.
Merging works by scanning invalidations in order of the lowest
modified value, and given this ordering it is possible to merge the
current and next entry into one large entry if they are
overlapping. This can continue until the current and next invalidation …

Merge continuous aggregate invalidations

---

src/utils.c
test/expected/timestamp.out
test/sql/timestamp.sql
test/src/test_time_to_internal.c
tsl/src/continuous_aggs/refresh.c

When clearing invalidations during a refresh of a continuous
aggregate, one should use the bucketed refresh window rather than the
"raw" user-defined window. This ensures that the window is capped at
the allowable timestamp range (e.g., when using an infinite window)
and that the window used to clear invalidations actually matches what
gets materialized.
Note, however, that, since the end of the refresh window is not
inclusive, the last possible time value is no included in the refresh.
To include that value, there needs exist a time-type agnostic
definition of "infinity" and both the invalidation code and
the materialization code must be able to handle such windows.
From other commit:
The internal conversion functions for timestamps didn't account for
timestamps that are infinite …

Allow use of infinite refresh windows 
