timescale/timescaledb

- src/continuous_agg.c
- src/continuous_agg.h
- tsl/src/bgw_policy/job.c
- tsl/src/chunk.c
- tsl/test/expected/dist_policy.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_policy.sql
If a retention policy is set up on a distributed hypertable, it will
not propagate the drop chunks call to the data nodes since the drop
chunks call is done through an internal call.
This commit fixes this by creating a drop chunks call internally and
executing it as a function. This will then propagate to the data nodes.
Fixes timescale/timescaledb-private#833
Fixes #2040
> Fix retention policy on distributed hypertables

- .github/workflows/alpine-32bit-build-and-test.yaml
- .github/workflows/coverity.yaml
- .github/workflows/cron-tests.yaml
- .github/workflows/update-test.yaml
- scripts/gh_matrix_builder.py
This patch changes all regression tests that were running on 11.8
and 12.3 to 11.9 and 12.4.
> Run regression tests on PG 11.9 and 12.4

- sql/updates/post-update.sql
- sql/util_time.sql
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_query-11.out
- tsl/test/expected/continuous_aggs_query-12.out
- tsl/test/expected/continuous_aggs_union_view-11.out
- tsl/test/expected/continuous_aggs_union_view-12.out
- tsl/test/expected/jit-11.out
- tsl/test/expected/jit-12.out
This patch changes the signature from cagg_watermark(oid) to
cagg_watermark(int). Since this is an API breaking change it couldn't
be done in an earlier release.
Fixes #2216
> Fix signature of cagg_watermark

- src/telemetry/telemetry_metadata.h
- tsl/src/compression/array.h
- tsl/src/compression/deltadelta.h
- tsl/src/compression/dictionary.h
- tsl/src/compression/gorilla.h
- tsl/src/compression/simple8b_rle.h
- tsl/src/fdw/fdw.c
- tsl/src/license.c
- tsl/src/nodes/gapfill/gapfill.c
- tsl/src/remote/connection.c
Since almost all the functions in the tsl library are accessed via
cross module functions there is no need to export the indivial
functions.
> Remove unnecessary exports in tsl library

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
Due to a typo in the code the relid of the relation instead of the
rangetable index was used when building the pathkey for the
DecompressChunk node. Since relids are unsigned but bitmapsets
use signed int32 this lead to 'negative bitmapset member not allowed'
being thrown as error when the relid is greater than INT32_MAX.
This patch also adds an assert to prevent this from happening again.
> Fix negative bitmapset member not allowed in decompression

- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/isolation/expected/continuous_aggs_concurrent_refresh.out
- tsl/test/isolation/specs/continuous_aggs_concurrent_refresh.spec
Invalidation processing during refreshing of a continuous aggregate is
now better protected against concurrent refreshes by taking the lock
on the materialized hypertable before invalidation processing.
Since invalidation processing is now split across two transactions,
the first one processing the hypertable invalidation log and the
second one processing the continuous aggregate invalidation lock, they
are now separately protected by serializing around the invalidation
threshold lock and the materialized hypertable lock, respectively.
In separate commits, refreshing now uses the bucketed refresh 
window for all operations (including invalidation processing) and the 
concurrent refresh test has been improved to also process invalidations.
> Improve locking when processing invalidations

- src/hypertable.c
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/sql/dist_hypertable.sql.in
Option `migrate_data` does not currently work for distributed
hypertables, so we block it for the time being and generate an error if
an attempt is made to migrate data when creating a distributed
hypertable.
Fixes #2230
> Block data migration for distributed hypertables

- tsl/src/bgw_policy/job_api.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
When trying to alter a job with NULL config alter_job did not
set the isnull field for config and would segfault when trying
to build the resultset tuple.
> Fix segfault in alter_job

- .github/workflows/linux-build-and-test.yaml
- scripts/gh_matrix_builder.py
- src/bgw/job_stat.c
Since CopyErrorData asserts that the current MemoryContext is not
ErrorContext we need to make sure to switch context before copying
ErrorData.
> Fix assertion failure in job_stat error handling

- tsl/src/bgw_policy/job.c
This patch adds check for NULL config as makeConst will segfault
when trying to detoast datum when passed a NULL config.
> Fix segfault when executing jobs with NULL config

- src/scanner.c
When scan is started using `ts_scanner_start_scan` it create a snapshot
to use when scanning the data, but this is not subsequently used in
`ts_scanner_next`.
This commit fixes this by using the already created snapshot instead of
calling `GetLastSnapshot()`.
> Use saved snapshot for scanner

- src/chunk_append/chunk_append.c
When postgres prunes children before we create the ChunkAppend
path there might be a mismatch between the children of the path
and the ordered list of children in a space partitioned hypertable.
Fixes #1841
> Fix segfault in chunk_append with space partitioning

- src/CMakeLists.txt
- src/chunk.c
- src/compat.h
- src/debug_wait.c
- src/debug_wait.h
- src/dimension_slice.c
- src/dimension_slice.h
- src/hypercube.c
- src/hypertable.c
- src/scanner.c
- src/scanner.h
- test/expected/broken_tables.out
- test/isolation/expected/dropchunks_race.out
- test/isolation/specs/CMakeLists.txt
- test/isolation/specs/dropchunks_race.spec.in
- test/sql/CMakeLists.txt
- test/sql/broken_tables.sql
If a hypercube is built from constraints in
`ts_hypercube_from_constraints`, which can happen during a run of
`drop_chunks` or when a chunk is explicitly dropped as part of other
operations, dimension slices will be removed and the hypercube will
contain references that are not valid.
This is fixed by adding a tuple lock on the dimension slices
that are used to build the hypercube.
In addition, commits for the following were added:
- A simple implementation of debug waitpoints are added.
- Dropping or truncating a broken table will not crash.
- A deleted dimension slice while running concurrent drop chunks will not error out and rather ignore the dimension slice (since the last chunk associated with the dimension slice is removed by the concurrently executing `drop_chunks`).
Fixes #1986
> Lock dimension slice tuple when scanning

- src/CMakeLists.txt
- src/chunk.c
- src/compat.h
- src/debug_wait.c
- src/debug_wait.h
- src/dimension_slice.c
- src/dimension_slice.h
- src/hypercube.c
- src/hypertable.c
- src/scanner.c
- src/scanner.h
- test/expected/broken_tables.out
- test/isolation/expected/dropchunks_race.out
- test/isolation/specs/CMakeLists.txt
- test/isolation/specs/dropchunks_race.spec.in
- test/sql/CMakeLists.txt
- test/sql/broken_tables.sql
This is a backport of #2150. Changes are:
* Using `follow_updates` instead of `lockflags` in the `ScanTupLock`.
* Changing order of parameters to `drop_chunks`.
> Backport lock dimension slice

- src/extension.c
Previously, cache invalidation could cause recursion in cache processing.
PR #1493 fixed this for the
- cache_invalidate_callback() -> ts_extension_invalidate()
call path. But the call path
- cache_invalidate_callback() -> ts_extension_is_loaded()
could still go into recursion.
So, this PR moves the recursion-prevention logic into
extension_update_state(), which is common to both call paths.
Fixes #2200.
> Fix recursion in cache processing

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This maintenance release contains bugfixes since the 1.7.2 release. We deem it high
priority for upgrading.
In particular the fixes contained in this maintenance release address issues in compression,
drop_chunks and the background worker scheduler.
**Bugfixes**
* #2059 Improve infering start and stop arguments from gapfill query
* #2067 Support moving compressed chunks
* #2068 Apply SET TABLESPACE for compressed chunks
* #2090 Fix index creation with IF NOT EXISTS for existing indexes
* #2092 Fix delete on tables involving hypertables with compression
* #2164 Fix telemetry installed_time format
* #2184 Fix background worker scheduler memory consumption
* #2222 Fix `negative bitmapset member not allowed` in decompression
* #2255 Propagate privileges from hypertables to chunks
* #2256 Fix …
> Release 1.7.3

- src/utils.c
Related Issue: #2167
Not really sure how to test it, since we not exported this function. If necessary I guess I could make a test c function to wrap it up and then check that the result of it does not change when executed inside an active transaction more then once.
> Fix ts_get_now_internal to use transaction time

- src/build-defs.cmake
- src/process_utility.c
Postgres added a new alter table subcommand in a bugfix for
CREATE TABLE LIKE with inheritance which got backported to previous
versions. We check for presence of the subcommand with cmake so
we can support building on snapshot versions which also fixes the
ABI breakage test.
https://github.com/postgres/postgres/commit/50289819230d8ddad510879ee4793b04a05cf13b
> Handle AT_CookedColumnDefault in process_utility

- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/sql/continuous_aggs_invalidation.sql
This change fixes some corner-case issues that could lead to a refresh
not actually refreshing when it should.
The issues arise because invalidations are inclusive in both ends
while the refresh window is exclusive in the end. In some case, this
wasn't correctly accounted for.
To fix the issues, the remainder after cutting invalidations has been
adjusted and we always add 1 to the end of the refresh window when it
is set from an invalidation. In addition, we add an extra check for
this case when computing the bucketed refresh window and the end of
the refresh window is at the start of the bucket (i.e., the window
size is 1).
The test suite has also been expanded to test for some of these corner
cases.
> Fix issues relate to non-inclusive refresh window

- src/cross_module_fn.c
- src/cross_module_fn.h
- src/process_utility.c
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/src/init.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/sql/continuous_aggs_ddl.sql
- tsl/test/sql/continuous_aggs_invalidation.sql
This change adds the ability to truncate a continuous aggregate and
its source hypertable. Like other mutations (DELETE, UPDATE) on a
continuous aggregate or the underlying hypertable, an invalidation
needs to be added to ensure the aggregate can be refreshed again.
When a hypertable is truncated, an invalidation is added to the
hypertable invalidation log so that all its continuous aggregates will
be invalidated. When a specific continuous aggregate is truncated, the
invaliation is instead added to the continuous aggregate invalidation
log, so that only the one aggregate is invalidated.
> Add TRUNCATE support for continuous aggregates

- .github/workflows/apt-packages.yaml
This patch removes Ubuntu 19.10 from APT package test because
19.10 is no longer supported by Ubuntu so we don't build packages
for it anymore.
> Remove Ubuntu 19.10 from APT package test

- sql/size_utils.sql
- sql/updates/latest-dev.sql
- test/expected/extension.out
- test/expected/size_utils.out
- test/sql/size_utils.sql
- tsl/test/expected/compression.out
- tsl/test/expected/dist_api_calls.out
- tsl/test/sql/compression.sql
- tsl/test/sql/dist_api_calls.sql
This change renames function to `approximate_row_count()` and adds support for regular tables. Return a row count estimate for a table instead of a table list. Add test for compression.
Issue: https://github.com/timescale/timescaledb/issues/2252 and https://github.com/timescale/timescaledb/issues/1741
> Make hypertable_approximate_row_count return row count only

- test/sql/CMakeLists.txt
- tsl/test/sql/CMakeLists.txt
Tablespaces are created cluster-wide, which means that tests that
create tablespaces cannot run together with other tests that create the
same tablespaces. This commit make those tests into solo tests to avoid
collisions with other tablespace-creating tests and also fix a test
that could trigger error if it was not executed after a test that
created the tablespaces.
> Make tests with tablespaces solo tests

- .gitignore
Updating gitignore to exclude default build folders and CLion folder.
> Ignore build and IDE folders

- src/process_utility.c
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/continuous_aggs_ddl.sql
Adding support for tablespaces when creating a continuous aggregate
using `CREATE MATERIALIZED VIEW` and when altering a continuous
aggregate using `ALTER MATERIALIZED VIEW`.
Fixes #2122
> Support tablespaces for continuous aggregates

- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/nodes/gapfill/planner.c
- tsl/src/nodes/gapfill/planner.h
- tsl/src/planner.c
- tsl/test/expected/dist_api_calls.out
- tsl/test/sql/dist_api_calls.sql
There are number of issues when time_bucket_gapfill is run on
distributed hypertable. Thus a non-supported error is returned in this
case until the issues are fixed.
PR note: The issues are described in https://github.com/timescale/timescaledb-private/issues/838
> Disable gapfill on distributed hypertable

- sql/util_time.sql
- src/continuous_agg.c
- src/continuous_agg.h
- src/time_utils.c
- src/time_utils.h
- test/src/test_time_utils.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_permissions.out
- tsl/test/expected/continuous_aggs_union_view-11.out
- tsl/test/expected/continuous_aggs_union_view-12.out
- tsl/test/sql/continuous_aggs_union_view.sql.in
The function `cagg_watermark` returns the time threshold at which
materialized data ends and raw query data begins in a real-time
aggregation query (union view).
The watermark is simply the completed threshold of the continuous
aggregate materializer. However, since the completed threshold will no
longer exist with the new continuous aggregates, the watermark
function has been changed to return the end of the last bucket in the
materialized hypertable.
In most cases, the completed threshold is the same as the end of the
last materialized bucket. However, there are situations when it is
not; for example, when there is a filter in the view query some
buckets might not be materialized because no data matched the
filter. The completed threshold would move ahead regardless. For
instance, if …
> Use end of last bucket as cagg watermark

- appveyor.yml
Due to a version conflict between the 12.2 and the 12.4 postgres
packages in alpine the 12.2 package was not installable on recent
alpine images. This patch bumps the involved packages to the latest
postgres version and also uses the most recent postgres image for
running appveyor tests.
> Bump appveyor docker image to postgres 12.4 

- test/isolation/specs/deadlock_dropchunks_select.spec
The test `deadlock_dropchunks_select` get a timeout on MacOS, but not
on other platforms, so this commit extend the lock timeout to make the
test pass.
> Extend timeout for isolation test

- .gitignore
Patterns `#*#` and `.#*` are for auto-genereated files from Emacs and
can end up in source directories.
Pattern `.clangd` is the working directory for `clangd` and handles
source code indexing.
> Add common patterns to .gitignore

- src/dimension_slice.h
- src/hypercube.c
When executing a SELECT on a hypertable, it is not possible to acquire
tuple locks since they require a transaction id and transaction ids
cannot be created when running as a standby running in ephemeral
recovery mode.
This commit removes the tuple lock from the SELECT code path. Since
this means that a slice might not be found as a result of a scan, we
need to ignore that dimension slice to avoid a segmentation fault.
> Remove tuple lock on select path

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This maintenance release contains bugfixes since the 1.7.3 release. We deem it high
priority for upgrading.
In particular the fixes contained in this maintenance release address an issue with
running queries on compressed hypertables on standby nodes.
**Bugfixes**
* #2336 Remove tuple lock on select path
> Release 1.7.4

- src/hypertable.c
- src/process_utility.c
- src/tablespace.c
- src/tablespace.h
- test/expected/alter.out
- test/expected/tablespace.out
- test/sql/alter.sql
- test/sql/tablespace.sql
If a tablespace is attached to a hypertable the tablespace of the
hypertable is not set, but if the tablespace is set it is also
attached. A similar situation occurs if tablespaces are detached.
With this commit, attaching a tablespace to a hypertable will set the
tablespace of the hypertable if it does not already have one. Detaching
a tablespace from a hypertable will set the tablespace to the default
tablespace if the tablespace being detached is the tablespace for the
hypertable.
Fixes #2299
> Update tablespace of table on attach and detach

- src/continuous_agg.c
- src/hypertable.c
- src/hypertable.h
- src/time_utils.c
- src/time_utils.h
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/invalidation_threshold.h
- tsl/src/continuous_aggs/materialize.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/expected/continuous_aggs_union_view-11.out
- tsl/test/expected/continuous_aggs_union_view-12.out
- tsl/test/sql/continuous_aggs_invalidation.sql
- tsl/test/src/test_continuous_aggs.c
When refreshing with an "infinite" refresh window going forward in
time, the invalidation threshold is also moved forward to the end of
the valid time range. This effectively renders the invalidation
threshold useless, leading to unnecessary write amplification.
To handle infinite refreshes better, this change caps the refresh
window at the end of the last bucket of data in the underlying
hypertable, as to not move the invalidation threshold further than
necessary. For instance, if the max time value in the hypertable is
11, a refresh command such as:
```
CALL refresh_continuous_aggregate(NULL, NULL);
```
would be turned into
```
CALL refresh_continuous_aggregate(NULL, 20);
```
assuming that a bucket starts at 10 and ends at 20 (exclusive). Thus
the invalidation threshold would at most …
> Cap invalidation threshold at last data bucket

- sql/views.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_materialize.out
- tsl/test/expected/continuous_aggs_multi.out
- tsl/test/expected/continuous_aggs_usage.out
- tsl/test/sql/continuous_aggs_bgw.sql
- tsl/test/sql/continuous_aggs_materialize.sql
- tsl/test/sql/continuous_aggs_multi.sql
- tsl/test/sql/continuous_aggs_usage.sql
With the new continuous aggregate API, some of
the parameters used to create a continuous agg are
now obsolete. Remove obsolete settings information from
timescaledb_information.continuous_aggregates.
> Continuous aggregate view changes

- scripts/docker-build.sh
The update tests use the scripts for building the
timescaledb image. Build errors should be reported
and return a failure code. This will force the failure
of the rest of the pipeline.
> Report docker build failures for update test

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/sql/continuous_aggs_errors.sql
The invalidation log initialization did not adjust
the timestamp to internal format. Use ts_get_now_internal
in all places that write entries to the invlaidation log.
> Fix invalidation log initialization

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/expected/continuous_aggs_tableam.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/continuous_aggs_ddl.sql
- tsl/test/sql/continuous_aggs_tableam.sql
If a table access method is provided when creating a continuous
aggregate using `CREATE MATERIALIZED VIEW` it will be used to set the
table access method for the materialized hypertable.
Closes #2123
> Support continuous aggregates table access method

- src/chunk_constraint.c
- src/chunk_constraint.h
- src/chunk_index.c
- src/chunk_index.h
- test/expected/alter.out
- test/sql/alter.sql
When a constraint is backed by an index like a unique constraint
or a primary key constraint the constraint can be renamed by either
ALTER TABLE RENAME CONSTRAINT or by ALTER INDEX RENAME. Depending
on the command used to rename different internal metadata tables
would be adjusted leading to corrupt metadata. This patch makes
ALTER TABLE RENAME CONSTRAINT and ALTER INDEX RENAME adjust the
same metadata tables.
Fixes #2101
> Fix rename constraint/rename index

- sql/updates/latest-dev.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
When the extension is updated to 2.0, we need to migrate
existing ignore_invalidation_older_than settings to the new
continuous aggregate policy framework.
ignore_invalidation_older_than setting is mapped to start_interval
of the refresh policy.If the default value is used, it is mapped
to NULL start_interval, otherwise it is converted to an
interval value.
> Migrate ignore_invalidation_older_than for continuous aggregates

- src/planner.c
- test/expected/plan_hypertable_cache-11.out
- test/expected/plan_hypertable_cache-12.out
- test/sql/plan_hypertable_cache.sql.in
When a hypertable was referenced in a subquery that was not already
in our hypertable cache we would fail to detect it as hypertable
leading to transparent decompression not working for that hypertable.
Fixes #2328
> Fix detection of hypertables in subqueries

- sql/updates/latest-dev.sql
- test/sql/updates/post.sequences.sql
When rebuilding the bgw_job table the update script wouldnt remember
the state of the sequence and reset it back to the default leading
to failed job inserts until the sequence catches up.
Fixes #2366
> Remember job_id sequence value in update script

- sql/ddl_api.sql
- sql/ddl_internal.sql
- test/expected/extension.out
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
This change moves the block chunks functionality to the internal
namespace since it won't be part of the public API for the 2.0
release.
Fixes #2236
> Make block chunks API internal

- sql/views.sql
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
This change filters materialized hypertables from the hypertables
view, similar to how internal compression hypertables are
filtered.
Materialized hypertables are internal objects created as a side effect
of creating a continuous aggregate, and these internal hypertables are
still listed in the continuous_aggregates view.
Fixes #2383
> Filter materialized hypertables in view

- src/process_utility.c
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/sql/continuous_aggs_refresh.sql
If a continuous aggregate is created using `CREATE MATERIALIZED VIEW`
using the `WITH DATA` option, it will fail with a segmentation fault if
executed inside a transaction or block. This is because starting a new
transaction in the middle of the statement will reset the SPI stack.
This commit fixes this by raising an error if `CREATE MATERIALIZED
VIEW` is not executed on top-level and `WITH DATA` is used either
directly or indirectly.
Closes #2371
> Error on create continuous aggregate with data

- src/process_utility.c
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/sql/continuous_aggs_refresh.sql
It is now possible to use `REFRESH MATERIALIZED VIEW` as an
alternative to `refresh_continuous_aggregate` when doing "infinite"
refreshes.
> Allow REFRESH MATERIALIZED VIEW to refresh caggs

- scripts/gh_matrix_builder.py
Early version of PG11 produces slightly different output for isolation
tests. Thus the affected tests are ignored.
continuous_aggs_concurrent_refresh is one of them and this commit adds
it to the ignored test list.
PR comment:
[Link](https://github.com/timescale/timescaledb/runs/1114025453?check_suite_focus=true) to the failed test
> Fix failing isolation test on PG11.0

- .github/workflows/linux-build-and-test.yaml
During migration of CI from travis to github actions running
postgres regression test suite was missed. This patch changes
our regression workflow to run postgres regression test suite
as well.
> Run postgres regression test suite as part of our CI

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/sql/continuous_aggs_ddl.sql
This patch changes the time_bucket validation to constify the width
argument so any immutable expression will be allowed. This change
allows continuous aggregates on hypertables with int8 time dimension
without requiring a workaround from a user to get the time_bucket
call accepted.
Fixes #1597
> Fix caggs width expression handling on int based hypertables

- sql/views.sql
- test/expected/tablespace.out
- test/expected/views.out
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_views.out
The is_compressed column for timescaledb_information.chunks
view is defined as TEXT instead of BOOLEAN
as true and false were specified using string literals.
> Fix typo in chunks view

- sql/views.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- tsl/test/expected/continuous_aggs_usage.out
Rename the `refresh_interval` field in
`timescaledb_information.continuous_aggregate` view to match the
parameter name in `add_continuous_aggregate_policy`.
> Fix field name in continuous_aggregate view

- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_permissions.out
This change checks for ownership of the user view when refreshing a
continuous aggregate (it's assumed the other objects have the same
owner). This mimics the checks done when refreshing a regular
materialized view.
Fixes #2408
> Check owner when refreshing a continuous aggregate

- src/bgw/job.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
Fix bgw_job_tuple_update_by_id to also update scheduled and config
field of bgw_job.
Fixes #2402
> Fix alter_job not updating new job fields

- src/catalog.h
- src/chunk_data_node.h
- src/chunk_index.c
- src/chunk_index.h
- src/dimension.c
- src/dimension.h
- src/net/conn.h
- src/plan_add_hashagg.h
- src/utils.c
- src/utils.h
- tsl/src/continuous_aggs/options.h
- tsl/src/data_node.h
- tsl/src/fdw/deparse.c
- tsl/src/fdw/deparse.h
- tsl/src/fdw/scan_plan.c
- tsl/src/remote/txn_store.h
The functions find_em_expr_for_rel and ts_find_em_expr_for_rel are
identical. This patch removes find_em_expr_for_rel and changes all
call-sites to use ts_find_em_expr_for_rel.
> Remove duplicate find_em_expr_for_rel function

- src/time_utils.c
- src/time_utils.h
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/sql/continuous_aggs_policy.sql
This patch does a minor refactoring and adds a way to guess
interval argument type based on used cagg
Issue: #2286
> Avoid having to cast time arg for cagg policy

- tsl/src/chunk_api.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/dist_grant.out
- tsl/test/sql/chunk_api.sql.in
- tsl/test/sql/dist_grant.sql
To create a chunk in a hypertable, it is currently necessary to be the
owner of the hypertable of the chunk. If a user has insert privileges
only, it will fail with an error message, which causes problems when
inserting data into distributed hypertables since the user cannot
create new chunks.
This commit changes this and only requires that the user has insert
privileges on the hypertable of the chunk for allowing creation of a
new chunk.
Closes #2393
> Check insert privileges to create chunk

- tsl/test/expected/dist_views.out
- tsl/test/sql/dist_views.sql
Create more than 2 dimensions and verify
that dimensions view displays information correctly.
> Add test for dimensions view

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/catalog.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/insert.c
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_watermark.out
- tsl/test/sql/continuous_aggs_watermark.sql
This change removes the catalog options `refresh_lag`,
`max_interval_per_job` and `ignore_invalidation_older_than`, which are
no longer used.
Closes #2396
> Remove catalog options for continuous aggregates

- sql/views.sql
- test/expected/pg_dump.out
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/sql/bgw_custom.sql
- tsl/test/sql/bgw_reorder_drop_chunks.sql
This patch adds a convenience view to list all configured jobs.
> Add timescaledb_information.jobs view

- src/process_utility.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
Implements support for changing the owner of the continuous aggregate.
This will change the owner of the materialized hypertable, the
user view, the partial view, and the direct view.
Fixes #2414
Fixes #1277
> Allow owner change of continuous aggregate

- test/expected/tablespace.out
- test/sql/tablespace.sql
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/expected/continuous_aggs_tableam.out
- tsl/test/sql/continuous_aggs_ddl.sql
- tsl/test/sql/continuous_aggs_tableam.sql
This patch fixes the format strings used to construct object names
in tests. The format strings used in those tests would break when
object names are involved that require quoting.
> Fix format strings used in tests

- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/src/continuous_aggs/refresh.c
After recent refactoring the refresh window arguments are not used in
many invalidation functions. This fixes the code and removes unused
arguments to avoid future confusions.
> Remove unused refresh arguments from invalidation

- src/process_utility.c
- tsl/test/expected/continuous_aggs_permissions.out
- tsl/test/sql/continuous_aggs_permissions.sql
Before this commit, grants on continuous aggregates were not propagated
to the materialized hypertable, direct view, and partial view. With
this commit, grants on a continuous aggregate is propagated.
Fixes #2413
> Propagate grants in continuous aggregates

- tsl/src/continuous_aggs/invalidation.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/sql/continuous_aggs_invalidation.sql
Since invalidations are inclusive in both ends, adjacent invalidations
can be merged. However, adjacency wasn't accounted for when merging
invalidations, which meant that a refresh could leave more
invalidations in the log than strictly necessary. Note that this
didn't otherwise affect the correctness of a refresh.
The PR also includes the following fix:
Fix index attribute in invalidation scan
When setting up an index scan for invalidations, a table attribute
number was used instead of the corresponding index attribute
number. While the attribute numbers happened to be the same, it isn't
future proof to use the wrong attribute reference.
> Merge adjacent invalidations during refresh

- sql/policy_api.sql
Continuous aggregate policy parameters start_interval/end_interval
are renamed to start_offset/end_offset
> Rename continuous_aggregate_policy parameters

- src/copy.c
- src/loader/bgw_launcher.c
This patch removes allocation of 2 arrays in the copyfrom function
that were never used.
> Remove unused allocation in copy path

- src/annotations.h
- src/cache_invalidate.c
- src/indexing.c
- src/planner.c
- src/process_utility.c
- test/src/bgw/timer_mock.c
- test/src/test_with_clause_parser.c
- tsl/src/remote/dist_ddl.c
This change adds a compiler-agnostic annotation for fall-throughs in
switch statements. The definition is put in `annotations.h`, which can
be expanded to hold definitions for similar functionality in the
future.
The `clang` compiler (as of version 12) seems to have have dropped
support for the previous comment-based annotations to allow
fall-throughs in favor of native annotations or GCC-style attributes.
> Support compiler-agnostic annotations

- sql/policy_api.sql
- tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
- tsl/test/sql/continuous_aggs_bgw_drop_chunks.sql
Policy parameters are renamed to be more consistent and intuitive
across different policies.
Fixes #2442
> Rename policy parameters

- sql/views.sql
Remove the ORDER BY clause from timescaledb_information.jobs to
make it consistent with our other information views.
> Remove ORDER BY clause from timescaledb_information.jobs view

- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/isolation/expected/continuous_aggs_concurrent_refresh.out
- tsl/test/isolation/specs/continuous_aggs_concurrent_refresh.spec
- tsl/test/sql/continuous_aggs_invalidation.sql
- tsl/test/sql/continuous_aggs_refresh.sql
Refresh of a continuous aggregate was expanding refresh window to
include buckets, which contain the start and end of the window. This
was leading to refreshing dropped data into the first bucket in the
corner case, when drop_before of a retention policy is the same as
start_offset of a continuous aggregate policy and the last dropped
chunk happens to intersect with the first bucket. See #2198 for
detailed discussion.
A behavior of a refresh, which is called when chunks are dropped, is
not changed, i.e., buckets, which fully cover chunks ot be dropped,
are refreshed if needed (i.e., there were changes in the chunks, which
were not refreshed yet). It can be done separately if needed.
Fixes #2198
> Change cagg refresh to cover buckets

- src/compat.h
- src/import/planner.c
- src/import/planner.h
- src/plan_add_hashagg.c
Only use our own implementation of estimate_hashagg_tablesize on
versions where the postgres implementation is static.
> Use postgres implementation of estimate_hashagg_tablesize

- .github/workflows/alpine-32bit-build-and-test.yaml
- appveyor.yml
- scripts/gh_matrix_builder.py
continuous_aggs_policy is flaky and prevents to proceed with current
PRs. This commit ignores it until it is fixed.
##PR note:
GH has problem with apprveyor.yml and shows diff for no changes.
> Ignore flaky test for now

- appveyor.yml
Fixes the regression test of Apache license on Windows.
GH is confused by some reason and shows difference on number of unchanged lines.
#2435 removed the Apache license test on Windows. This PR fixes it back.
> Test Apache license on Windows

- sql/views.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_multi.out
- tsl/test/expected/continuous_aggs_permissions.out
- tsl/test/expected/continuous_aggs_usage.out
- tsl/test/isolation/expected/continuous_aggs_multi.out
- tsl/test/isolation/specs/continuous_aggs_multi.spec
- tsl/test/sql/continuous_aggs_bgw.sql
- tsl/test/sql/continuous_aggs_multi.sql
- tsl/test/sql/continuous_aggs_permissions.sql
Use hypertable_schema and hypertable_name instead
of regclass in job_stats and
continuous_aggregates views.
> Modify job_stats and continuous_aggregates view

- sql/updates/latest-dev.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
This change will add an invalidation to the
materialization_invalidation_log for any region earlier than the
ignore_invalidation_older_than parameter when updating a continuous
aggregate to 2.0. This is needed as we do not record invalidations
in this region prior to 2.0 and there is no way to ensure the
aggregate is up to date within this range.
Fixes #2450
> Create low end invalidation when updating caggs

- src/annotations.h
Change the check for fallthrough support to check for the attribute
instead of specific compiler versions.
> Improve check for fallthrough support

- sql/updates/latest-dev.sql
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/compression_api.h
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/bgw_policy/retention_api.h
- tsl/test/expected/bgw_policy.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/compress_bgw_reorder_drop_chunks.out
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_bgw_drop_chunks.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/expected/continuous_aggs_usage.out
- tsl/test/expected/tsl_tables.out
A previous change updated the public function definitions, but didn't
update the code, config, and error messages to match these changes.
> Fix parameter names in policy API code

- sql/views.sql
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/sql/continuous_aggs_bgw.sql
Rename next_scheduled_run to next_start so that
jobs and job_stats views have the same column names
> Rename column in job_stats view

- sql/views.sql
- test/expected/pg_dump.out
- tsl/test/expected/data_node.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_util.out
- tsl/test/sql/data_node.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/dist_util.sql
Rename the data_node view to data_nodes to be consistent with other
views that all use the plural form.
> Make data nodes view consistent with other views

- sql/views.sql
- tsl/test/expected/continuous_aggs_permissions.out
- tsl/test/expected/continuous_aggs_usage.out
- tsl/test/sql/continuous_aggs_permissions.sql
Removing usage of `REGCLASS` from view `continuous_aggregates` and
splitting it into schema and name.
> Remove use of REGCLASS in views

- sql/views.sql
- test/expected/tablespace.out
- test/expected/views.out
- test/sql/tablespace.sql
- test/sql/views.sql
- tsl/test/expected/compression.out
- tsl/test/expected/compression_hypertable.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_query-11.out
- tsl/test/expected/dist_query-12.out
- tsl/test/expected/dist_util.out
- tsl/test/expected/dist_views.out
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_hypertable.sql
- tsl/test/sql/continuous_aggs.sql
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/dist_query.sql.in
- tsl/test/sql/dist_util.sql
- tsl/test/sql/dist_views.sql
Make all views that reference hypertables use `hypertable_schema` and
`hypertable_name`.
> Use consistent column names in views

- scripts/suppressions/suppr_leak.txt
Ignore memory leaks in openssl code when running sanitizer tests
in CI.
> Ignore memory leaks in openssl code

- sql/CMakeLists.txt
- sql/pre_install/timescaledb_fdw.sql
- sql/updates/latest-dev.sql
Since CREATE FOREIGN DATA WRAPPER is not idempotent it must not be
grouped with the normal sql scripts but has to be in the pre_install
group.
> Fix timescaledb_fdw sql script

- sql/views.sql
- tsl/test/expected/tsl_tables.out
- tsl/test/sql/tsl_tables.sql
This change updates the timescaledb_information.job_stats view to
check whether a job is currently scheduled in the bgw_config table.
If it is not, the `job_status` field will show `Paused` and the
`next_start` field will be NULL.
Fixes #2488
> Show unscheduled jobs as paused in job_stats

- sql/CMakeLists.txt
- sql/data_node.sql
- sql/remote_txn.sql
This patch merge data_node and remote_txn sql scripts and fixes
the CREATE FUNCTION statement to use CREATE OR REPLACE FUNCTION.
> Fix datanode sql function script

- tsl/src/bgw_policy/reorder_api.c
- tsl/test/expected/dist_policy.out
- tsl/test/sql/dist_policy.sql
Block for `add_reorder_policy` were missing previously for distributed hypertables, yet `reorder_chunk` and `move_chunk` are blocked when called directly.
Issue: https://github.com/timescale/timescaledb-private/issues/839
> Block reorder policy for distributed hypertables

- src/time_utils.c
- src/time_utils.h
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.h
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/policy_utils.h
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/sql/continuous_aggs_policy.sql
When we compute the start and end intervals for the
refresh job execution, there is a potential to
run into overflow with integer computations. Handle 
overflow condition by setting the start/end boundaries to 
PG_INT64_MIN or PG_INT64_MAX.
> Overflow handling for refresh policy with integer based time

- tsl/src/data_node.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
We stop enforcing an extension owner to be the same as a user adding a
data node since that's not strictly necessary. In multi-node setups
it is common that a data node is pre bootstrapped and an extension owner
is already set. This will prevent getting an error when a non
extension owner tries to add a data node.
Closes https://github.com/timescale/timescaledb/issues/2508
> Fix validation logic when adding a new data node

- tsl/src/data_node.c
- tsl/test/expected/data_node_bootstrap.out
If the database exists on the data node when executing `add_data_node`
it will generate an error in the data node log, which can cause
problems since there is an error indication in the log but there are no
failing operations.
This commit fixes this by first validating the database and only if it
does not exist, create the database.
Closes #2503
> Remove error for correct bootstrap of data node

- sql/ddl_api.sql
- sql/updates/latest-dev.sql
- tsl/src/data_node.c
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
This change makes detach_data_node() function consistent with
other data node management functions by adding missing
if_attach argument.
The function will not show an error in case if data node is not
attached and if_attached is set to true.
Issue: #2506
> Add if_attached argument to detach_data_node()

- sql/updates/1.5.1--1.6.0.sql
- test/sql/updates/post.policies.sql
- test/sql/updates/setup.policies.sql
- test/sql/updates/setup.v6-pg11.sql
When updating from version 1.5.1 to 1.6.0 the meaning of the
`cascade_to_materialization` column in `bgw_policy_drop_chunks`
changed and `NULL` was introduced as an acceptable value. This means
that the table was updated and `false` in this column was replaced with
`NULL`.
This triggered the check function `valid_ts_interval` to execute as
part of a check constraint. However, it referred to the C version in
the old library and not the new library and therefore triggers an error
in the `ts_extension_check_version` function since the function is in
the old shared library.
This commit fixes the issue by replacing the function definition with
the same function in the new library, so that the check doesn't fail.
Closes #2513
> Replace check function when updating

- .github/workflows/update-test.yaml
- test/sql/updates/setup.continuous_aggs.v2.sql
Disable background workers during update tests to prevent deadlocks
in continuous aggregates on 1.7.x
> Fix flaky update test

- sql/ddl_api.sql
- sql/updates/latest-dev.sql
- src/compat.h
- tsl/src/remote/dist_commands.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/dist_commands.out
- tsl/test/expected/dist_ddl.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_query-11.out
- tsl/test/expected/dist_query-12.out
- tsl/test/sql/chunk_api.sql.in
- tsl/test/sql/dist_commands.sql
- tsl/test/sql/dist_ddl.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/include/dist_query_load.sql
Before this commit, executions of `distributed_exec` was always
transactional and this could not be disabled. This cause problems when
executing statements that cannot be executed inside a transaction, such
as `CREATE DATABASE`.
With this commit, we introduce a parameter `transactional` to
`distributed_exec` that allow non-transactional executions on data
nodes. The parameter defaults to `TRUE`.
It also changes `distributed_exec` to be a procedure, which better
matches it's usage (it returns `VOID`).
Closes #1660
> Support non-transactional distibuted_exec

- sql/ddl_api.sql
- sql/updates/latest-dev.sql
- sql/views.sql
- test/sql/updates/post.continuous_aggs.v2.sql
- tsl/test/expected/continuous_aggs_usage.out
Removes unlrelated column schedule_interval from 
timescaledb_information.continuous_aggregates view and simplifies it. 
Renames argument cagg in refresh_continuous_aggregate into 
continuous_aggregate as in add_continuous_aggregate_policy.
Part of #2521
> Cleanup public API

- .github/workflows/linux-build-and-test.yaml
GitHub deprecates use of set-env in workflows so switch to using
environment files.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Use environment files for github actions

- sql/CMakeLists.txt
- sql/pre_install/fdw_functions.sql
- sql/pre_install/timescaledb_fdw.sql
This patch splits the timescaledb_fdw sql file into two parts to
separate the idempotent parts from the non-idempotent ones so
the function definitions can be included in the regular update
script.
> Fix timescaledb_fdw function handling in update script

- tsl/test/expected/dist_ddl.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_ddl.sql
Change database names to be unique over the test suite by adding the
test database name in front of the created database names in the test.
This will allow the test to be executed in parallel with other tests
since it will not have conflicting databases in the same cluster.
> Update test dist_ddl to execute in parallel

- src/bgw/job.c
lock_job is passed incorrect Status as argument.
The lock is incorrectly interpreted as a session
lock when a transaction lock is desired.
To reviewers: I ran into this due to a deadlock issue while executing bgw_db_scheduler.sql.
> Pass correct status to lock_job function

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/catalog.h
- src/utils.c
- src/utils.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/expected/continuous_aggs_multi.out
- tsl/test/expected/continuous_aggs_watermark.out
The `modification_time` column is hard to maintain with any level of consistency over merges and splits of
invalidation ranges so this commit removes it from the invalidation log entries for both hypertables and continuous aggregates. If the modification
time is needed in the future, we need to re-introduce it in a manner
that can maintain it over both merges and splits.
Part of #2521
> Remove modification time from invalidation log

- tsl/test/isolation/specs/compression_ddl.spec
- tsl/test/isolation/specs/continuous_aggs_concurrent_refresh.spec
- tsl/test/isolation/specs/continuous_aggs_multi.spec
Some isolation tests had steps that were not referenced in
any of the permutations so this patch removes those.
> Remove unreferenced steps from isolation tests

- tsl/test/expected/remote_connection.out
- tsl/test/expected/remote_txn.out
- tsl/test/sql/remote_connection.sql
- tsl/test/sql/remote_txn.sql
Change expected test output to sqlstate only in places where the
error message might differ between platforms/environments.
> Fix flaky remote_txn test

- src/dimension.c
- src/dimension.h
- src/time_utils.c
- src/time_utils.h
- src/utils.c
- test/expected/create_chunks.out
- test/expected/create_hypertable.out
- test/expected/custom_type-11.out
- test/expected/custom_type-12.out
- test/expected/timestamp.out
- test/sql/custom_type.sql.in
- test/src/test_time_utils.c
- tsl/src/continuous_aggs/invalidation_threshold.c
The database must know the valid time range of a custom time type,
similar to how it knows the time ranges of officially supported time
types. However, the only way to "know" the valid time range of a
custom time type is to assume it is the same as the one of a supported
time type.
A previous commit tried to make such assumptions by finding an
appropriate cast from the custom time type to a supported time
type. However, this fails in case there are multiple casts available
that each could return a different type and range.
This change restricts the choice of valid time ranges to only that of
the bigint time type.
Fixes #2523
> Assume custom time type range is same as bigint

- src/chunk.c
- src/chunk.h
- src/dimension_slice.c
- src/dimension_slice.h
- src/hypercube.c
- src/hypercube.h
- src/hypertable.c
- test/isolation/expected/dropchunks_race.out
- test/isolation/specs/dropchunks_race.spec.in
This change makes two changes to address issues with processes doing
concurrent inserts and `drop_chunks` calls:
- When a new chunk is created, any dimension slices that existed prior
to creating the new chunk are locked to prevent them from being
dropped before the chunk-creating process commits.
- When a chunk is being dropped, concurrent inserts into the chunk
that is being dropped will try to lock the dimension slices of the
chunk. In case the locking fails (due to the slices being
concurrently deleted), the insert process will treat the chunk as
not existing and will instead recreate it. Previously, the chunk
slices (and thus chunk) would be found, but the insert would fail
when committing since the chunk was concurrently deleted.
A prior commit (PR #2150) partially solved a related …
> Lock dimension slices when creating new chunk

- src/plan_expand_hypertable.c
- test/expected/lateral.out
- test/expected/plan_expand_hypertable-12.out
- test/sql/lateral.sql
time_bucket_annotate_walker passes an incorrect status
for outer join to the function that checks quals eligibility
for propagation.
Fixes #2500
> Fix outer join qual propagation

- sql/updates/latest-dev.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
When upgrading from 1.7, it's possible to have retention policies
which overlap with continuous aggregates.  These make use of the
cascade_to_materializations parameter to avoid invalidating the
aggregate.
In 2.0 there is no equivalent behavior to prevent the retention from
disrupting the aggregate.  So during the 2.0 upgrade, check for any
running retention policies that are dropping chunks still used by a
continuous aggregate and suspend them (scheduled=>false).  This will
also print a notice informing the user of what happened and how to
resume the retention policy if that's what they truly want.
Fixes #2530
> Suspend retention policies with caggs conflicts

- sql/updates/latest-dev.sql
- test/sql/updates/post.integrity_test.sql
In #2514 a a race condition between inserts and `drop_chunks` is fixed
and this commit will repair the dimension slices table by
re-constructing missing dimension slices from the corresponding
constraint expressions.
Closes #1986
> Repair dimension slice table on update

- tsl/src/partialize_finalize.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
This patch improves datatype handling when the aggregate function
argument type is a pseudotype.
Fixes #2455
> Improve cagg datatype handling

- src/planner.c
- tsl/src/compression/compression.c
- tsl/test/expected/compression.out
- tsl/test/expected/transparent_decompression-11.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/shared/expected/ordered_append_join.out
- tsl/test/sql/compression.sql
This change captures the reltuples and relpages (and relallvisible)
statistics from the pg_class table for chunks immediately before
truncating them during the compression code path.  It then restores
the values after truncating, as there is no way to keep postgresql
from clearing these values during this operation.  It also properly
uses these values properly during planning, working around some
postgresql code which substitutes in arbitrary sizing for tables
which don't see to hold data.
Fixes #2524
> Ensure reltuples are preserved during compression

- src/telemetry/telemetry.c
This tracks the extension usage.
> Add Promscale extension to telemetry

- appveyor.yml
- tsl/src/remote/connection.c
- tsl/test/postgresql.conf.in
By default, user certificates are placed in the directory
`timescaledb/certs` relative to the data directory. This location can,
however, be changed by setting `timescaledb.ssl_dir` to another value.
If `timescaledb.ssl_dir` is set, user certificates will be
`timescaledb/certs` relative to this location.
This commit changes the usage of `timescaledb.ssl_dir` to point to the
actual directory for the user SSL certificates and keys rather than the
subdirectory `timescaledb/certs` under that directory.
The default location of the user certificates and keys are unchanged.
Closes #2568
> Change use of ssl_dir GUC

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/shared/expected/decompress_placeholdervar.out
- tsl/test/shared/sql/decompress_placeholdervar.sql
The non-parallel pathes generated by DecompressChunk were
incorrectly marked as parallel_safe even when the child scan
was not parallel aware. Leading to incorrect query results
when those pathes were used in a parallel plan.
Additionaly DecompressChunk code didnt set total_table_pages on
PlannerInfo leading to an assertion failure in BitmapHeapscan
path creation.
Fixes #2211
Fixes #2424
> Fix DecompressChunk path generation

- src/process_utility.c
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
This change makes sure that ANALYZE and VACUUM commands run without
any relations will not clear the stats on compressed chunks that
were saved at compression time.  It also will skip any distributed
tables.
Fixes #2576
> Exclude compressed chunks from ANALYZE/VACUUM

- tsl/src/compression/compress_utils.c
There is a bug in some versions of PG11 where ANALYZE was not
calling CommandCounterIncrement.  This is causing us to fail to
update pg_class statistics during compression for those versions.
To work around this, this change adds an explicit
CommandCounterIncrement call after ExecVacuum in PG11.
Fixes #2581
> Add missing increment for PG11 decompression

- src/chunk.c
- src/chunk_adaptive.c
- src/compat.h
- src/dimension.c
- src/hypertable.c
- src/tablespace.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/data_node.c
- tsl/src/hypertable.c
The function name is hard-coded in some cases in the C function, so
this commit instead extract the function name from the `fcinfo`
structure. This prevents mismatches between the hard-coded names and
the actual function name.
Closes #2579
> Read function name dynamically

- appveyor.yml
- test/pg_regress.sh
- test/runner.sh
- test/sql/utils/testsupport.sql
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_hypertable.sql.in
Change database names to be unique over the test suite by adding the
test database name in front of the created database names in the test.
This will allow the test to be executed in parallel with other tests
since it will not have conflicting databases in the same cluster.
To handle tablespaces, a directory prefix is created where tablespaces
can be put. Each test should then create a subdirectory under that
prefix for the tablespace. The commit keeps variables for the old
tablespace paths around so that old tests work while we transition to
the new system.
> Fix dist_hypertable test for parallel execution

- src/time_utils.c
- src/time_utils.h
- tsl/src/bgw_policy/policy_utils.c
- tsl/test/expected/continuous_aggs_policy_run.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/continuous_aggs_policy_run.sql
Add mock timestamp support for subtract_from_now.
Use mock timestamp to execute cont. agg policies for
date and timestamp based tables.
> Add test for continuous agg policies

- test/pgtest/CMakeLists.txt
PostgreSQL's `timetz` test fails outside of daylight savings. The
test is ignored until fixed in PostgreSQL (likely to happen in
12.5).
> Ignore PostgreSQL's timetz test

- src/bgw/job.c
Sets the flag parameter to pass for tuple lock during alter_job
execution. Restores the lost comment explaining the value of the flag
parameter.
> Set explicitly all lock parameters in alter_job

- src/continuous_agg.c
- tsl/test/expected/continuous_aggs_union_view-11.out
- tsl/test/expected/continuous_aggs_union_view-12.out
The internal function `cagg_watermark` is often used as part of an
index scan condition and is therefore called on every row of such a
scan. Ideally, the planner should be able to reuse the result of
repeated calls of the same function since it is marked STABLE, but
this doesn't seem to be the case for C functions, making scans very
slow.
To deal with this, we cache the watermark value in the `fn_extra`
field of the function call info context. This avoids row-by-row max
value calculations, which otherwise makes things very slow.
The function could be optimized further by making the scan for the max
value faster (e.g., by doing an internal scan for max instead of
relying on SPI). However, by caching the max value, this is already
faster than the corresponding watermark function in 1.7.x. …
> Optimize internal cagg_watermark function

- sql/chunk_constraint.sql
- test/expected/constraint.out
- test/sql/constraint.sql
This resolves an issue when using both constraints with index
tablespaces AND constraints that have no indexes on a single hypertable.
chunk_constraint_add_table_constraint() was attempting to add
`USING INDEX TABLESPACE` to all constraints when a given hypertable had
any constraint configured to use a tablespace, resulting in a SYNTAX
error and blocking the creation of new chunks.
The solution here is to limit index tablespace lookups to only the
constraint types which use indexes: primary key and unique so that only
those constraits will have `USING INDEX TABLESPACE` prepended when
necessary.
> Fix chunk creation on hypertables with foreign key constraints

- tsl/src/data_node_dispatch.c
- tsl/src/nodes/decompress_chunk/planner.c
Remove two commented code blocks in data node dispatch and the
decompress chunk executor node.
> Remove commented code blocks

- tsl/src/data_node.c
- tsl/src/dist_util.c
We want to check all available extension versions
and not just the installed one. This is because we
might be setting up a cluster for a database that
has different extension version then the `postgres` or
`template1` database which  we actually use to perform
this validation.
So instead of using `pg_available_extensions` view we
use `pg_available_extension_versions` that should return
the same list of extension versions no matter which database
we connect to.
> Fix validation of available extensions on data node

- src/chunk.c
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/continuous_aggs/materialize.c
- tsl/src/continuous_aggs/materialize.h
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
- tsl/test/expected/continuous_aggs_drop_chunks.out
- tsl/test/sql/continuous_aggs_drop_chunks.sql
When drop_chunks is called on a hypertable manually or through
a retention policy, it initiates refresh in hypertable's continuous
aggregates. The refresh includes all buckets of each dropped chunk.
Some buckets are inside a dropped chunk only partially. In such case,
this commit fixes to refresh only the correct partials of the buckets.
The fix passes chunk id to refresh on drop of a chunk. The chunk id is
used to identify and update correct partials. This is a workaround
that the invalidation outside of the refreshed chunk doesn't update
the other partial, which is outside the refreshed chunk.
The commit also adds the test demonstrating correct refresh.
Fixes #2592
> Refresh correct partial during refresh on drop

- src/process_utility.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
Currently we treat cagg materialized view as a view internally, but that was missed in case of the drop cascade.
Issue: #2608
> Fix DROP CASCADE for continuous aggregate

- src/guc.c
- tsl/src/async_append.c
- tsl/src/async_append.h
- tsl/src/fdw/data_node_scan_exec.c
- tsl/src/fdw/option.c
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/scan_exec.c
- tsl/src/fdw/scan_exec.h
- tsl/src/fdw/scan_plan.c
- tsl/src/remote/async.c
- tsl/src/remote/cursor_fetcher.c
- tsl/src/remote/cursor_fetcher.h
- tsl/src/remote/data_fetcher.c
- tsl/src/remote/data_fetcher.h
- tsl/src/remote/row_by_row_fetcher.c
- tsl/src/remote/row_by_row_fetcher.h
- tsl/test/expected/dist_query-11.out
- tsl/test/expected/dist_query-12.out
- tsl/test/sql/data_fetcher.sql
- tsl/test/sql/dist_query.sql.in
- tsl/test/sql/include/dist_query_run.sql
This change fixes errors when using sub-queries together with
AsyncAppend on distributed hypertables.
Since all subqueries are sent to remote data nodes as separate queries
on the same connection, it is important that one query does not block
the connection once the other query starts to execute. In other words,
a query must complete a request and retrieve the result before another
(sub-)query can execute. During query execution, this means that the
following invariant must hold: An executor node cannot leave a request
(or result) pending on a connection after returning a tuple, since for
the next tuple a different executor node can be called to execute
another sub-query on the same connection. This would be the case if
two sub-queries are, e.g., joined with a nested loop.
AsyncAppend …
> Fix subquery errors when using AsyncAppend

- src/time_utils.c
- test/expected/chunk_utils.out
- tsl/test/expected/continuous_aggs_refresh.out
API functions that take "any" type to support any supported time
argument type sometimes do implicit conversion to the "right" type
when a type coercion path exists. This change improves the error
message when such a path does not exist.
Closes #2614
> Improve error when converting time arguments

- src/bgw/job.c
- src/bgw/job.h
- src/bgw_policy/policy.c
- src/bgw_policy/policy.h
- src/telemetry/telemetry.c
- test/expected/telemetry.out
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/bgw_policy.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/compress_bgw_reorder_drop_chunks.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/sql/bgw_custom.sql
- tsl/test/sql/bgw_policy.sql
- tsl/test/sql/bgw_reorder_drop_chunks.sql
- tsl/test/sql/compress_bgw_reorder_drop_chunks.sql
- tsl/test/sql/continuous_aggs_bgw.sql
This patch adjusts the telemetry code to the job refactorings.
Additionally it adds telemetry entries for user-defined actions,
continuous aggregate policies, compression policies and renames
drop_chunks to retention to match the new policy names.
Fixes #2596
> Add user-defined actions to telemetry

- src/continuous_agg.c
- src/hypertable.c
- src/hypertable.h
- src/process_utility.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
This change fixes the situation when schema object is dropped
before the cagg which leads to an error when it tries to
resolve it.
Fixes: #2350
> Fix SCHEMA DROP CASCADE with continuous aggregates

- tsl/src/compression/compression.c
This patch fixes a segfault in decompress_chunk for chunks with dropped
columns. Since dropped columns don't exists in the compressed chunk
the values for those columns were undefined in the decompressed tuple
leading to a segfault when trying to build the heap tuple.
It's cherry pick of https://github.com/timescale/timescaledb/pull/2619 into 1.7.x branch
> Fix segfault in decompress_chunk for chunks with dropped columns

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression-11.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/sql/transparent_decompression.sql.in
The compressed scan path overwrites the total_table_pages
setting on PlannerInfo. This results in an assertion failure in
index_pages_fetched function at
Assert(T <= total_pages)
When a hypertable has a mix of compressed and uncompressed chunks,
the total_table_pages value is calculated in reenable_inheritance code
path and create_compressed_scan_paths. create_compressed_scan_path
should not overwrite the value previously computed by
reenable_inheritance.
> Fix incorrect total_table_pages setting for compressed scan

- src/compression_chunk_size.c
- src/compression_chunk_size.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/process_utility.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/init.c
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
When an internal compression table is analyzed,
statistics from the compressed chunk (such as page count and
tuple count) is used to update the
statistics of the corresponding chunk parent.
> Support analyze of internal compression table

- src/chunk.c
- test/expected/constraint.out
- test/sql/constraint.sql
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
Fix an uninitialized field in a struct in the refresh code for
continuous aggregates. Other fixes are mostly to silence false
positives.
> Fix minor issues found by Coverity

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.0.0-rc2--2.0.0-rc3.sql
- sql/updates/latest-dev.sql
- version.config
This release candidate contains bugfixes since the previous release
candidate, as well as additional minor features including support for
"user-mapping" authentication between access/data nodes and an
experimental API for refreshing continuous aggregates on individual
chunks.
**Minor Features**
* #2627 Add optional user mappings support
* #2635 Add API to refresh continuous aggregate on chunk
**Bugfixes**
* #2560 Fix SCHEMA DROP CASCADE with continuous aggregates
* #2593 Set explicitly all lock parameters in alter_job
* #2604 Fix chunk creation on hypertables with foreign key constraints
* #2610 Support analyze of internal compression table
* #2612 Optimize internal cagg_watermark function
* #2613 Refresh correct partial during refresh on drop
* #2617 Fix validation of available …
> Release 2.0.0-rc3

- src/chunk.c
- tsl/src/continuous_aggs/materialize.c
Fixes usage of const to be identical in declarations and definitions,
since 15.9 VS compiler gets warnings otherwise.
> Make compatible with old Windows compiler

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
Fixes support for continuous aggregates when the view query contains
an expression with several aggregates, e.g., `max(val) - min(val)`.
Usage of continuous aggregates with such expression was producing
errors if the aggregate expression was not the last in the SELECT
clause or not all GROUP BY expressions were present in the SELECT
clause.
An expression with several aggregates is materialized with partials
per aggregate. For example, `max(val) - min(val)` will be materialized
in two partial entry columns: one for `max` and one for `min`. Thus
all columns in the materialized hypertable should account for the
number of partials and cannot just use the position in the original
query. This fix makes sure to account for such case.
Fixes #2616
> Fix support for complex aggregate expression

- sql/updates/latest-dev.sql
- sql/views.sql
- tsl/test/expected/continuous_aggs_usage.out
Add the hypertable's schema and name to the continuous aggregates view
in the information schema, since these fields where missing.
The new fields use the same names and order in the view to be
consistent with other information views that reference the hypertable.
Fixes #2653
> Add hypertable to continuous aggregates view

- sql/updates/latest-dev.sql
- sql/views.sql
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
timescale_infromation.job_stats view was missing information about
jobs running user actions. This commit fixes that the view includes
user jobs with.
Replaces https://github.com/timescale/timescaledb/pull/2674
> Include user actions into job stats view

- tsl/src/bgw_policy/job_api.c
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/tsl_tables.out
- tsl/test/sql/bgw_custom.sql
This change fixes a crash in `add_job` when given an NULL
schedule interval as input. In addition, the following improvements
have been implemented for all job API functions:
* Validation of input parameters, specifically NULL checks
* Improved error messages for clarity and consistency
* Tests for bad input arguments
> Fix crash in add_job when given NULL interval

- tsl/src/remote/async.c
- tsl/src/remote/async.h
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/src/remote/txn.c
- tsl/test/expected/remote_txn.out
- tsl/test/sql/remote_txn.sql
- tsl/test/src/remote/async.c
This change removes a hard-coded 1 minute connection timeout that
would cause long-running queries and commands (e.g., compressing a
chunk) to time out before completion. Queries can still be canceled by
the user or the database when `statement_timeout` is reached.
One exception where timeouts is still used is cleanup during
transaction abort (e.g., sending a `ROLLBACK` statement to a data node
in the abort handler). Queries sent at this stage should have a
timeout since they occur in the transaction abort handler after the
main query has already been canceled or reached `statement_timeout`.
Fixes #2645
Closes #2646
> Fix timeout handling in async library

- .github/workflows/alpine-32bit-build-and-test.yaml
- scripts/docker-build.sh
- sql/updates/latest-dev.sql
- sql/version.sql
- src/CMakeLists.txt
- src/annotations.h
- src/gitcommit.h.in
- src/version.c
- test/expected/version.out
- test/sql/version.sql
Show more information in get_git_commit
The command `get_git_commit` shows quite a little information and
especially if mistakes are made it is hard to verify what the binary is
actually based on.
This commit extends the function to provide some more information:
specifically the SHA of the HEAD regardless of whether there is a tag
on it or not and the time for the HEAD commit.
```
postgres=# select * from _timescaledb_internal.get_git_commit();
commit_tag        | commit_hash |      commit_time
--------------------------+-------------+------------------------
1.7.4-10-g09b0b778-dirty | 09b0b778    | 2020-09-13 17:50:38+02
(1 row)
```
If git is not installed, the function `get_git_commit` will return an
error indicating that no git information is available. If some of the
fields are …
> Show more information in get_git_commit

- src/dimension_slice.c
- src/scanner.c
- src/scanner.h
- tsl/test/isolation/expected/deadlock_drop_chunks_compress.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/deadlock_drop_chunks_compress.spec
This change fixes a segfault that occured when `drop_chunks` is
concurrently executed with `compress_chunk` and the same chunk that
gets dropped is also being compressed.
The crash happened because the tuple lock status function for a
dimension slice passed in a pointer to a dimension slice that was
always NULL.
An isolation test is also added to cover concurrent compression and
drop of the same chunk. To make the test pass with identical errors
for PG11 and PG12, additional changes are made to the scanner API to
pass on the lock failure data so that it is possible to distinguish
between an update and delete on PG11.
> Fix crash for concurrent drop and compress chunk

- tsl/src/fdw/deparse.c
- tsl/src/nodes/gapfill/planner.c
- tsl/src/nodes/gapfill/planner.h
- tsl/src/planner.c
- tsl/test/expected/dist_api_calls.out
- tsl/test/sql/dist_api_calls.sql
This commits enables support for executing queries with
time_bucket_gapfill on distributed hypertables. Current implementation
always plans to execute time_bucket_gapfill on the access node. In
future, it can be optimized to be executed on data nodes in suitable
cases.
> Support gapfill on distributed hypertable

- .github/workflows/alpine-32bit-build-and-test.yaml
- .github/workflows/coverity.yaml
- .github/workflows/update-test.yaml
Versions in the build matrix with significant leading/trailing zeroes
need the version string quoted otherwise it will get treated as number
and those zeroes will be removed. As currently those tests fixed by
this patch run PG 11.1 instead of 11.10.
> Fix postgres versions in build matrix

- CMakeLists.txt
- scripts/clang_format_wrapper.sh
The clang-format wrapper is always using `clang-format` even if a
different version of `clang-format` has been found and has the correct
version.
This commit fixes the issue by passing the name of the found version of
`clang-format` to the wrapper script using the `CLANG_FORMAT` variable.
It will default to use `clang-format` if `CLANG_FORMAT` is unset.
> Fix clang-format wrapper

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/views.sql
- src/catalog.h
- src/chunk.c
- src/hypertable.c
- src/hypertable.h
- src/process_utility.c
- test/expected/alter.out
- test/expected/alternate_users.out
- test/expected/create_hypertable.out
- test/expected/ddl.out
- test/expected/drop_extension.out
- test/expected/drop_hypertable.out
- test/expected/drop_owned.out
- test/expected/drop_rename_hypertable.out
- test/expected/drop_schema.out
- test/expected/dump_meta.out
- test/expected/pg_dump.out
- test/expected/relocate_extension.out
- test/expected/truncate.out
- tsl/src/bgw_policy/retention_api.c
- tsl/src/compression/create.c
- tsl/test/expected/compression.out
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_views.out
- tsl/test/sql/compression.sql
- tsl/test/sql/dist_compression.sql
1. Add compression_state column for hypertable catalog
by renaming compressed column for the hypertable catalog
table. compression_state is a tri-state column.
This column indicates if the hypertable has
compression enabled (value = 2) or if it is an internal
compression table (value = 1).
2. Save compression settings on access node when compression
is turned on for a distributed hypertable
For a distributed hypertable, that has compresison enabled,
compression_state is set. We don't create any internal tables
on the access node.
Fixes #2660
> Save compression metadata settings on access node

- src/copy.c
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/remote/dist_copy.c
- tsl/src/remote/dist_copy.h
- tsl/test/expected/remote_copy.out
This change improves memory usage in the `COPY` code used for
distributed hypertables. The following issues have been addressed:
* `PGresult` objects were not cleared, leading to memory leaks.
* The caching of chunk connections didn't work since the lookup
compared ephemeral chunk pointers instead of chunk IDs. The effect
was that cached chunk connection state was reallocated every time
instead of being reused. This likely also caused worse performance.
To address these issues, the following changes are made:
* All `PGresult` objects are now cleared with `PQclear`.
* Lookup for chunk connections now compares chunk IDs instead of chunk
pointers.
* The per-tuple memory context is moved the to the outer processing
loop to ensure that everything in the loop is allocated on the
per-tuple …
> Improve memory handling for remote COPY

- tsl/src/data_node.c
We now try connecting to three databases before giving up:
postgres, template1 and defaultdb.
> Introduce additional db for data node bootstrapping

- src/hypertable.c
- src/hypertable.h
- src/planner.c
- src/process_utility.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/compression/compress_utils.c
- tsl/src/compression/create.c
- tsl/src/planner.c
This PR cleans up some macro names.
Rename macro TS_HYPERTABLE_HAS_COMPRESSION
to TS_HYPERTABLE_HAS_COMPRESSION_TABLE.
> Rename macro TS_HYPERTABLE_HAS_COMPRESSION

- src/build-defs.cmake
- src/process_utility.c
Since PG12.5 has been released the workaround for AT_CookedColumnDefault
is no longer needed and a simple PG version check is sufficient.
> Remove workaround for AT_CookedColumnDefault to build against snapshot

- tsl/src/fdw/data_node_scan_exec.c
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable_with_oids.out
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/dist_hypertable_with_oids.sql
This change adds a check which raises an error when system column (like
tableoid) being requested in case if data node scan is enabled.
Fixes: #2528
> Block tableoid access on distributed hypertable

- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
When renaming views of a continuous aggregate, schema rename with the
direct view was not covered. This commit move an explicit rename of a
direct view so that we can test a schema rename including a direct view
as well as a partial view.
Closes #2138
> Increase test coverage for rename

- src/process_utility.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
CREATE UNIQUE INDEX is not supported on a hypertable
that has compression enabled.
> Do not allow unique index on compressed hypertables.

- CMakeLists.txt
- src/compat.h
This patch adjusts the version checks to allow building against
postgres 13. It also adjusts the cmake version check to allow
building against RC and devel versions.
> Allow building against PG13 source

- src/compat.h
- tsl/src/compression/compression.c
PG13 adds a destination length 4th argument to pg_b64_decode and
pg_b64_encode functions so this patch adds a macro that translates
to the 3 argument and 4 argument calls depending on postgres version.
This patch also adds checking of return values for those functions.
https://github.com/postgres/postgres/commit/cfc40d384a
> Add compatibilty wrapper functions for base64 encoding/decoding

- src/bgw/job.c
- src/bgw/scheduler.c
- src/chunk.c
- src/chunk_adaptive.c
- src/extension_utils.c
- src/license_guc.c
- src/process_utility.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/continuous_aggs/refresh.c
PG13 removed acl.h from objectaddress.h so the places that need it
need to now include it explicitly if they got it indirectly this
way previously.
https://github.com/postgres/postgres/commit/3c173a53a8
> Add missing utils/acl.h includes

- CMakeLists.txt
- src/build-defs.cmake
- src/time_utils.h
- test/sql/CMakeLists.txt
- tsl/src/build-defs.cmake
- tsl/src/fdw/fdw_utils.c
- tsl/src/fdw/fdw_utils.h
- tsl/src/fdw/relinfo.h
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/src/remote/txn.c
- tsl/src/remote/txn.h
- tsl/src/remote/txn_store.c
From `pg_config` it is possible to get the flags that were used to
build PostgreSQL and we include when building the extension. However,
on some platforms and some compilers (CentOS 8 and gcc, for example)
flags are included that cannot be used when building the extension and
will result in a compiler error.
If the compiler used to build the extension is different from the
compiler used when building PostgreSQL, we can also get errors because
some options are not supported (PostgreSQL built using GCC and
extension built using CLang, for example).
This commit solves this by not adding the C compile flags from
`pg_config` and explicitly add the flags that we need for building the
extension.
In addition, some compilers do not support using `#if SYMBOL` when
`SYMBOL` is undefined and give an …
> Exclude PostgreSQL compiler flags when building

- CMakeLists.txt
- scripts/gh_matrix_builder.py
There are some flags that cannot be used in preprelease tests, which
this commit fixes. It uses the flag `-DWARNINGS_AS_ERRORS=OFF` to not
turn warnings into errors for release builds. In addition, explicit
checks for compiler flags are added instead of using a function, which
for some reason causes problems.
> Fix compile issues in prerelease tests

- src/chunk.c
- src/debug_wait.c
- tsl/test/isolation/expected/remote_create_chunk.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/remote_create_chunk.spec.in
The create-chunk API, which is used by the access node to create
chunks on data nodes, always grabs a lock on the root hypertable. This
change optimizes this locking so that the lock is only taken when the
chunk doesn't already exist.
> Optimize locking for create chunk API

- sql/views.sql
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_views.out
The compression status of individual chunks for distributed tables is
unknown on the access node. Fix the view so that is_compressed is NULL
instead of false for distributed chunks.
> Fix compression status in chunks view for distributed chunks

- test/sql/CMakeLists.txt
chunk_utils test experiences some inconsistency in permissions
sometimes. To avoid this the test is run solo without other tests
interfering.
PR note: 
[link](https://github.com/timescale/timescaledb/runs/1563206122?check_suite_focus=true#step:15:25) to a failed test.
> Run chunk_utils test in solo to reduce flakiness

- tsl/src/data_node.c
- tsl/src/dist_util.c
- tsl/src/remote/connection.c
- tsl/test/expected/data_node.out
This change fixes two issues with `add_data_node`:
1. In one case, a check for a valid connection pointer was not done,
causing a segmentation fault when connection attempts failed.
2. Connections were made with a blocking API that would hang
indefinitely if the receiving end is not responding. The user
couldn't cancel the connection attempt with CTRL-C, since no wait
latch or interrupt checking was used. The code is now updated to
use a non-blocking connection API, where it is possible to wait on
the socket and latch, respecting interrupts.
This was tested locally by setting up a bogus listening socket with `netcat -l` that would not respond to connection attempts by `add_data_node`. Without the fix, the command could not be canceled with CTRL-C. With the update code, this works as …
> Fix crash and cancel when adding data node

- tsl/src/data_node.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/test/expected/dist_grant.out
- tsl/test/sql/dist_grant.sql
If a user mapping is created without a user name in the options, a
crash would happen when querying a distributed hypertable.
This change fixes the crash by assuming that the user to connect with
is the "current user" (i.e., no username mapping is done). This makes
it possible to create user mappings that only provide a password
option.
> Fix crash when user mapping has no username

- CMakeLists.txt
The verification of version number in version.config required
pre-release label always. This fixes the bug and allows release versions.
> Fix version number verification to allow releases

- .github/workflows/coverity.yaml
The coverity build should not build with warnings-as-errors, so
disabling it for the build.
> Fix Coverity build to not use -Werror

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
With this release, we are officially moving TimescaleDB 2.0 to GA, 
concluding several release candidates.
TimescaleDB 2.0 adds the much-anticipated support for distributed 
hypertables (multi-node TimescaleDB), as well as new features and 
enhancements to core functionality to give users better clarity and 
more control and flexibility over their data.
Multi-node architecture:  In particular, with TimescaleDB 2.0, users 
can now create distributed hypertables across multiple instances of 
TimescaleDB, configured so that one instance serves as an access node 
and multiple others as data nodes. All queries for a distributed 
hypertable are issued to the access node, but inserted data and queries
are pushed down across data nodes for greater scale and performance.
Multi-node TimescaleDB can …
> Release 2.0.0

- scripts/test_update_from_tag.sh
- sql/pre_install/tables.sql
- sql/updates/2.0.0-rc3--2.0.0-rc4.sql
- sql/updates/latest-dev.sql
- test/sql/updates/post.integrity_test.sql
- test/sql/updates/post.update.sql
- test/sql/updates/post.v6.sql
- test/sql/updates/setup.bigint.sql
- test/sql/updates/setup.multinode.sql
- test/sql/updates/setup.v2.sql
- test/sql/updates/setup.v6.sql
The `replication_factor` is set to `-1` on hypertables that are
created on data nodes as part of a larger distributed
hypertable. However, the check constraint on the hypertable metadata
table doesn't allow such values, causing update scripts to fail when
this check constraint is recreated as part of updating to version
`2.0.0-rc4`.
The reason it is possible to insert violating rows is because check
constraints aren't validated when inserting data using PostgreSQL's
internal catalog functions (in C). Therefore, the violating row can
exist until one tries to update a data node to `2.0.0-rc4`, at which
point the update script tries to recreate the `hypertable` metadata
table due to other changes that were made to the table.
This change fixes the check constraint to account for `-1` as a …
> Fix check constraint on hypertable metadata table

- src/extension.c
- src/extension.h
- tsl/src/data_node.c
When the access node bootstraps a data node and creates the extension,
it should use the extension version of the access node. This change
adds the `VERSION` option to the `CREATE EXTENSION` statement sent to
a data node so that the extension versions on the access node and data
nodes will be the same. Without the version option, data nodes will be
bootstrapped with the latest version installed, potentially leading to
data nodes running different versions of the extension compared to the
access node.
> Bootstrap data nodes with versioned extension

- src/hypertable.c
- src/hypertable.h
Remove an unused field called `max_ignore_invalidation_older_than`
that was left in the `Hypertable` struct after refactoring of
continuous aggregates.
> Remove unused field for ignoring invalidations

- tsl/src/data_node.c
- tsl/test/expected/data_node_bootstrap.out
- tsl/test/expected/dist_util.out
- tsl/test/sql/data_node_bootstrap.sql
This change ensures the database and extension is validated whenever
these objects aren't created, instead of only doing validation when
`bootstrap=>false` is passed when adding a data node.
This fixes a corner case where a data node could be added and removed
several times, even though the data node's database was already marked
as having been part of a multi-node setup.
> Always validate existing database and extension

- src/guc.c
config_enum entries, which are used for GUC values, need to contain 
the end mark. Missing the end mark in the data fetcher entries 
resulted in crashing TimescaleDB in Release on Windows. This commit 
fixes the end mark for data fetcher config_enum entries.
Fixes #2775
PR note:
No test is added, since there is no Release test on Windows, and the bug doesn't happen in Debug or on other platforms.
> Fix config enum entries for remote data fetcher

- src/copy.c
PG13 removes addRTEtoQuery and provides a similar function
addNSItemToQuery which has a different signature.
https://github.com/postgres/postgres/commit/5815696bc6
> Adjust copy code to PG13 addRTEtoQuery changes

- src/chunk_insert_state.c
- src/compat.h
- tsl/src/fdw/modify_exec.c
PG13 removed the msg parameter from convert_tuples_by_name.
https://github.com/postgres/postgres/commit/fe66125974
> Adjust code to PG13 convert_tuples_by_name signature change

- src/jsonb_utils.c
PG13 moved jsonapi.h from utils to common.
https://github.com/postgres/postgres/commit/beb4699091
> Adjust jsonb_utils to PG13 changes

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
PG13 renames the varnoold and varoattno field of Var to varnosyn and
varattnosyn.
https://github.com/postgres/postgres/commit/9ce77d75c5
> Adjust decompress code to Var field renames

- src/process_utility.c
PG13 adds a new ALTER TABLE subcommand for dropping the generated
property from a column.
https://github.com/postgres/postgres/commit/f595117e24
> Handle AT_DropExpression in process_utility

- tsl/src/remote/async.c
- tsl/src/remote/stmt_params.c
- tsl/src/reorder.c
PG13 split tuptoaster.c into three separate files. This patch also
removes unnecesary tuptoaster.h includes.
https://github.com/postgres/postgres/commit/8b94dab066
> Adjust code to PG13 tuptoaster changes

- sql/updates/1.7.4--2.0.0-rc1.sql
- test/sql/updates/post.integrity_test.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
If `drop_chunks` has been executed on a hypertable that has a
continuous aggregate defined, the chunks will be removed and marked as
dropped in `_timescaledb_catalog.chunk` but the lines will not be
removed. This will cause problems for the update script since it is
missing a check to only process chunks that are not dropped and will
try to cast the chunk name into a `REGCLASS` for a table that does not
exist.
This commit fixes this by adding a check that the chunk is not dropped
and also fixes the update test to not count dropped chunks when
comparing with the chunk index since the chunk index does not count
dropped chunks.
Fixes #2791
> Add check for dropped chunk on update

- src/chunk_append/explain.c
PG13 changes EXPLAIN to use Plan instead PlanState as context.
https://github.com/postgres/postgres/commit/6ef77cf46e
> Adjust code to deparse_context changes

- src/copy.c
PG13 adds a CmdType argument to ExecComputeStoredGenerated.
https://github.com/postgres/postgres/commit/c6679e4fca
> Adjust copy code to PG13 changes

- src/compat.h
In PG 13:
define for_each_cell(cell, lst, initcell) \
for (ForEachState cell##__state = for_each_cell_setup(lst, initcell); \
(cell##__state.l != NIL && \ cell##__state.i < cell##__state.l->length) ? \
(cell = &cell##__state.l->elements[cell##__state.i], true) : \
(cell = NULL, false); \
cell##__state.i++)
Extra brackets is wrong. Trying to concatenate parameters with brackets generate
an preprocessor error.
> Fix for_each_cell_compat macro for PG13

- src/loader/loader.c
- src/process_utility.c
- src/process_utility.h
- tsl/test/src/test_ddl_hook.c
PG13 changes the representation of command completion tags to structs.
https://github.com/postgres/postgres/commit/2f9661311b
> Adjust code to PG13 command completion tag changes

- src/continuous_agg.c
- tsl/test/expected/continuous_aggs_query-11.out
- tsl/test/expected/continuous_aggs_query-12.out
- tsl/test/sql/continuous_aggs_query.sql.in
The internal function `cagg_watermark` returns the last/max bucket in
a continuous aggregate and is used to get the point where to union the
raw and materialized data when using real-time aggregation.
Since the function is marked `STABLE` the planner should be able to
constify the function so that it need not be called repeatedly during
execution. However, this optimization is not guaranteed and the
function might be constified many times during planning if it occurs,
e.g., as an index scan condition on many chunks. This leads to slow
queries due to repeated calls to the function.
Previously, the watermark was cached in the function's `fn_extra`
state, but this state doesn't survive all repeated calls of the
function and doesn't help if the function occurs many times in the
same plan.
To …
> Improve cagg watermark caching

- CHANGELOG.md
- src/bgw/job_stat.c
- tsl/src/bgw_policy/job.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
The mark_start field should be set to false when
a new job stat record is created.
Fixes #2793
> Do not mark job as started when setting next_start

- tsl/test/shared/sql/dist_gapfill.sql
The `TEST_OUTPUT_DIR` for the test `dist_gapfill` is incorrect inside the test
files (when called from `pg_regress`) because `TEST_OUTPUT_DIR` is set
to the parent directory rather than the subdirectory.
> Fix path to dist_gapfill

- src/chunk_append/planner.c
- test/expected/append-11.out
- test/expected/append-12.out
- test/sql/include/append_load.sql
- test/sql/include/append_query.sql
When the targetlist of a ChunkAppend node was modified after plan
creation the ChunkAppend node would not properly project because
input and output targetlist where pointing to the same list.
Fixes #2661
> Fix projection in ChunkAppend nodes

- .github/workflows/linux-build-and-test.yaml
Occasionally tests would segfault but the coredump would not be
uploaded as artefact because the coredump was still in progress.
This patch changes CI to wait for potential in progress coredumps
to upload coredumps more reliably.
> Improve CI coredump detection

- CHANGELOG.md
- scripts/test_update_from_tag.sh
- sql/updates/latest-dev.sql
- test/sql/updates/post.continuous_aggs.sql
- test/sql/updates/setup.continuous_aggs.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
- test/sql/updates/setup.roles.sql
Copy ACL privileges (grants) from the query view (user-facing object)
to the internal objects (e.g., materialized hypertable, direct view,
and partial view) when updating the extension to the new version. A
previous change added such propagation of privileges when executing
`GRANT` statements, but didn't apply it retrospectively to the
internal objects of existing continuous aggregates.
Having the right permissions on internal objects is also necessary for
the watermark function used by real-time aggregation since it queries
the materialized hypertable directly.
The update script copies the ACL information from the user-facing view
of every continuous aggregate to its internal objects (including the
materialized hypertable and its chunks). This is done by direct insert
into `pg_class` …
> Fix continuous aggregate privileges during upgrade

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/sql/transparent_decompression_queries.sql
Volatile functions that are in chunk's baserestrictinfo
list were not correctly handled when we inserted a
DecompressChunk node. This PR adds these quals as a filter
to the DecompressChunk node.
Fixes #2864
> Apply volatile function quals at decompresschunk

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression_ordered_index-11.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/sql/include/transparent_decompression_ordered_index.sql
This change adds equivalence class members for non segment
by attributes of compressed tables. Before the change
introduced by this PR, we added equivalence members to the
compressed chunk only for segment by columns. If we
have a join condition like:
hyper.segment_col = A.col1 and hyper.compressed_attr = A.col2
The compressed rel had EM only for
compressed_chunk.segment_col = A.col1
When a parameterized path is created for the compressed chunk,
it has only 1 clause (corresponding to the segment by EM )
in its list of ppi_clauses. The other clause is missing since
it did not have an EM. A parameterized path is expected to carry
all the clauses that come from the outer_rel for the join
(table A in this case).Since the ppi_clauses did not have all
the clauses that come from table A, we …
> Fix nested loop joins that involve compressed chunks

- CHANGELOG.md
- tsl/src/nodes/gapfill/planner.c
- tsl/test/shared/expected/gapfill.out
- tsl/test/shared/sql/gapfill.sql
This change fixes a bug with gapfill that caused certain query plans
to fail with the error "could not find pathkey item to sort". This was
caused by a corruption in the query plan which happened as a result of
removing the last two arguments to the `time_bucket_gapfill` function
expression during query planning. Since the function expression was
modified via a reference to the original query plan tree, it affected
also the expression in the target list. When the planner couldn't
match the target list with the corresponding equivalence member (which
still included the two removed arguments), the error was generated.
The original reason for removing the two arguments was to avoid
passing them on to `time_bucket`, which is called internally by
`time_bucket_gapfill`. However, the last to …
> Fix corruption in gapfill plan

- CHANGELOG.md
- src/plan_expand_hypertable.c
- src/plan_partialize.c
- src/plan_partialize.h
- src/planner.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/partialize_finalize.out
- tsl/test/sql/continuous_aggs.sql
- tsl/test/sql/dist_partial_agg.sql
- tsl/test/sql/dist_query.sql.in
- tsl/test/sql/partialize_finalize.sql
partialize_agg is an internal function, which serializes partial
aggregate results. It is used to prepare partials for materialization
in continuous aggregates and partial results on data nodes in
distributed query execution. paritalize_agg doesn't expect push down of
aggregates, which happens when partitionwise aggregate is enabled, and
produces a query plan, which either crashes on assert during execution
or produces incorrect result.
This fix avoids adding partition info if the function is present in the
query. This can be seen as a work around and it is good to fix planning
of partialize_agg in the case of pushed down aggregates.
This commit also contains few minor fixes of readability of comments
and code around the changes.
Fixes #2849 and fixes #2858
> Avoid partitionwise planning of partialize_agg

- src/plan_expand_hypertable.c
When building the partition information for hypertables, the memory
for partition bound information wasn't properly initialized. The
uninitialized memory could make the planner believe it could plan an
ordered append (PostgreSQL's built-in version) when the contents of
the memory happened to have the "right" value (specifically the
`strategy` char field of the partition bound info).
This change fixes the crash by properly initializing the partition
bound info so that PostgreSQL's ordered append plans are not triggered
on hypertables.
Due to the randomness of the uninitialized memory, it isn't possible
to reproduce the crash reliably and create a test for it. But the
crash was manually reproduced by initializing the `strategy` field of
the partition bound info to a value that triggered the …
> Fix partitionwise agg crash due to uninitialized memory

- .github/workflows/update-test.yaml
- scripts/test_update_from_tag.sh
- scripts/test_updates.sh
- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
- sql/updates/1.7.1--1.7.2.sql
- sql/updates/2.0.0-rc1--2.0.0-rc2.sql
- test/sql/updates/post.repair.sql
- test/sql/updates/setup.check.sql
- test/sql/updates/setup.repair.sql
- test/sql/updates/setup.v6.sql
This commit creates an update repair test that breaks a few tables for
pre-2.0 versions to ensure that the repair script actually fixes them.
The integrity check for the update tests already contain a check that
dimension slices are valid, so there is no need to add a test for that.
In addition, the commit fixes two bugs in the repair scripts that could
prevent an update in rare circumstances.
For the 1.7.1--1.7.2 repair script: if there were several missing 
dimension slices in different hypertables with the same column name, 
the repair script would be confused on what contraint had what type and
generate an error.
For the 2.0.0-rc1--2.0.0-rc2 repair script: if a partition constraint 
was broken, it would generate an error rather than repairing the 
dimension slices because `BIGINT_MIN` …
> Add update test for repair table script

- sql/updates/latest-dev.sql
- src/chunk.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/include/compression_alter.sql
The check for existence of compressed chunks when disabling
compression would not ignore dropped chunks making it impossible
to disable compression on hypertables with continuous aggregates
that had dropped chunks.
This patch ignores dropped chunks in this check and also sets
compressed_chunk_id to NULL in the metadata for deleted chunks.
Fixes #2844
> Fix compressed chunk check when disabling compression

- src/bgw/job_stat.c
- src/bgw/scheduler.c
- tsl/src/bgw_policy/job.c
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
The status of background workers is recorded using
`pgstat_record_activity` which allow the status of the worker to be
inspected using the `status` field in `pg_stat_activity`. This is used
by the `timescaledb_information.job_stats` view to show if a job is
running, scheduled, or paused.
However, the activity was never recorded in the code and hence the
field was always NULL. Since this was the default for the `job_status`
field of `timescaledb_information.job_stats` it would always show as
`Scheduled`.
This commit fixes this by adding calls to `pgstat_record_activity` and
suitable locations and also add a default of `Undefined` for the
`job_status` field to capture missing calls of
`pgstat_record_activity`. This is more of a precaution and is unlikely
to ever show.
Fixes #2831
> Set status for backend in background jobs

- src/guc.c
- src/guc.h
- src/plan_expand_hypertable.c
- test/expected/plan_expand_hypertable-11.out
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-13.out
- test/sql/plan_expand_hypertable.sql.in
This patch adds a `enable_qual_propagation` GUC to control
propagation of JOIN quals. Since there have been a few instances
where JOIN qual propagation was too aggressive this GUC can be
used to disable qual propagation.
> Add GUC to control join qual propagation

- CHANGELOG.md
- appveyor.yml
- scripts/gh_matrix_builder.py
- src/process_utility.c
- test/expected/cluster-11.out
- test/expected/cluster-12.out
- test/expected/cluster-13.out
- test/sql/cluster.sql.in
When changing the column type of a column that is part of an index
that is being clustered on with either postgres CLUSTER or reorder
the alter type operation would fail with a segfault because it
couldn't lookup the index.
> Fix changing column type of clustered hypertables

- scripts/gh_matrix_builder.py
When adding the bugfix for clustered hypertables a typo was
introduced making the PG12.0 test run with PG11 settings.
> Fix typo in CI config

- CHANGELOG.md
- src/plan_expand_hypertable.c
- test/expected/plan_expand_hypertable-11.out
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-13.out
- test/sql/include/plan_expand_hypertable_query.sql
Join propagation would propagate join quals for nested joins even
when it was not safe to do so leading to wrong query results.
Fixes #2790
> Fix join propagation for nested joins

- .github/workflows/coverity.yaml
- CMakeLists.txt
- scripts/gh_matrix_builder.py
In contrast to the default for CMake files, `Release` is used as the
default in `CMakeFiles.txt` which causes the `bootstrap` script to do a
release build with development flags, in particular `-Werror`. Since
warnings are triggered in a release build, this cause the build to
fail while a debug build works fine.
This commit fixes this by removing the `-Werror` flag (by setting
`WARNINGS_AS_ERRORS` to `OFF`) on anything that is not a debug build
and also disable the warnings that (currently) trigger the warnings in
the release build.
The commit also changes some of the GitHub workflows to run without
`WARNINGS_AS_ERRORS` since it should always work without this option
regardless of build type (on release build this should be disabled, on
debug builds this should be enabled).  But it is set …
> Change bootstrap and CMake defaults 

- CMakeLists.txt
Older versions of GCC do not have this flag, so check for it explicitly
before adding it.
Fix by Mats Kindahl
> Explicitly check for "-Wno-stringop-truncation" compiler flag

- src/guc.c
- src/guc.h
- src/plan_expand_hypertable.c
- test/expected/plan_expand_hypertable-10.out
- test/expected/plan_expand_hypertable-11.out
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-9.6.out
- test/sql/plan_expand_hypertable.sql.in
This patch adds a `enable_qual_propagation` GUC to control
propagation of JOIN quals. Since there have been a few instances
where JOIN qual propagation was too aggressive this GUC can be
used to disable qual propagation.
> 1.7.5 Add GUC to control join qual propagation

- .travis.yml
- scripts/test_update_from_tag.sh
- scripts/test_updates.sh
- scripts/test_updates_pg10.sh
- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
- scripts/test_updates_pg96.sh
- sql/updates/1.7.1--1.7.2.sql
- test/sql/updates/post.repair.sql
- test/sql/updates/setup.check.sql
- test/sql/updates/setup.repair.sql
- test/sql/updates/setup.v6-pg10.sql
- test/sql/updates/setup.v6-pg11.sql
- test/sql/updates/setup.v6-pg12.sql
- test/sql/updates/setup.v6-pg96.sql
This is a backport to fix issue #2824.
The commit fixes two bugs in the repair scripts that could
prevent an update in rare circumstances.
For the 1.7.1--1.7.2 repair script: if there were several missing
dimension slices in different hypertables with the same column name,
the repair script would be confused on what constraint had what type
and generate an error.
This commit also creates an update repair test that breaks a few tables
for pre-1.7.2 versions to ensure that the repair script actually fixes
them.
This commit adds an extra dimension in the workflow to test updates
with repair and run that separately. It also changes the update test
scripts to by default run without repair tests and add the additional
option `-r` for running repair tests in addition to the normal tests.
> Fix repair in update scripts

- .travis.yml
Docker has added rate limits for image pulls, which breaks some Travis
builds when the rate limit is reached. By authenticating with
DockerHub we get a higher rate limit that we don't share with other
anonymous users.
Note that PRs have to be created from a branch in the main repo (not from a fork) after this PR is merged. This is because PRs from forks cannot access encrypted environment variables needed for Docker credentials.
> Add Docker authentication to Travis builds

- .github/workflows/alpine-32bit-build-and-test.yaml
- .github/workflows/coverity.yaml
- .github/workflows/cron-tests.yaml
- .github/workflows/update-test.yaml
- scripts/gh_matrix_builder.py
Run tests on PG 11.11, 12.6 and 13.2
> Bump postgres versions used in CI

- test/expected/rowsecurity-13.out
- test/sql/CMakeLists.txt
- test/sql/rowsecurity-13.sql
Copying the test file for row security checks from PG12 to PG13 and
creating a new output file. The test is identical to the PG12 test, but
the PG11 test is different, so we are not using a generated test.
Subtask of #2779
> Add row security tests for PG13

- .github/workflows/windows-build-and-test.yaml
- src/compat.h
The minimum required PG13 version is 13.2 because we require a
bugfix only present in that version otherwise decompression might
not work properly for certain queries.
> Set minimum required PG13 version to 13.2

- .travis.yml
Some Docker images have issues running on Ubuntu Xenial, which is the
default build environment on Travis. Switching to Ubuntu Focal in
order to use a newer Docker.
> Run Travis tests on Ubuntu Focal

- CMakeLists.txt
The strict-overflow check on gcc < 8 produces false positives
leading to build failuren when compiling with -Werror
> Disable strict-overflow for gcc < 8

- scripts/test_sanitizers.sh
The sanitizer test is running on PG11.1 where the cluster test is
expected to fail. This patch changes the sanitizer test to ignore
the test result of the cluster test.
> Fix sanitizer test

- tsl/src/remote/connection_cache.c
PG13 adds a new connection status when checking for a proper
target connection.
https://github.com/postgres/postgres/commit/b438e7e7a1c58e0c20b5f46e73cbd713e8033c69
> Add string mapping for CONNECTION_CHECK_TARGET

- CHANGELOG.md
- src/continuous_agg.c
- src/continuous_agg.h
- src/process_utility.c
- test/sql/updates/setup.continuous_aggs.v2.sql
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/expected/continuous_aggs_policy_run.out
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/sql/continuous_aggs_bgw.sql
- tsl/test/sql/continuous_aggs_policy.sql
- tsl/test/sql/continuous_aggs_policy_run.sql
- tsl/test/sql/continuous_aggs_refresh.sql
This change adds validation of the settings for a continuous aggregate
policy when the policy is created. Previously it was possible to
create policies that would either fail at runtime or never refresh
anything due to bad configuration.
In particular, the refresh window (start and end offsets for
refreshing) must now be at least two buckets in size or an error is
generated when the policy is created. The policy must cover at least
two buckets to ensure that at least one bucket is refreshed when the
policy runs, since it is unlikely that the policy runs at a time that
is perfectly aligned with the beginning of a bucket.
Note that it is still possible to create policies that might not
refresh anything depending on the time when it runs. For instance, if
the "current" time is close to the …
> Validate continuous aggregate policy

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
In PG13, eclass_indexes are used to traverse the equivalence classes. This should be set correctly
for compressed chunks.
Reviewers: There are plan changes due to the filters/join conditions being pushed down (as expected) to the compressed chunk.
> Adjust eclass_indexes for compressed chunks for PG13

- CHANGELOG.md
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/expected/continuous_aggs_multi.out
- tsl/test/sql/continuous_aggs_invalidation.sql
This PR includes two changes:
**Change 1:**
The refreshing of a continuous aggregate is slow when many small
invalidations are generated by frequent single row insert
backfills. This change adds an optimization that merges small
invalidations by first expanding invalidations to full bucket
boundaries. There is really no reason to maintain invalidations that
aren't covering full buckets since refresh windows are already aligned
to buckets anyway.
**Change 2:**
When there are many small (e.g., single timestamp) invalidations that
cannot be merged despite expanding invalidations to full buckets
(e.g., invalidations are spread across every second bucket in the
worst case), it might no longer be beneficial to materialize every
invalidation separately.
Instead, this change adds a threshold for …
> Optimize cagg refresh for small invalidations

- CHANGELOG.md
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/hypertable_compression.c
- src/hypertable_compression.h
- src/process_utility.c
- tsl/src/compression/compression.c
- tsl/src/compression/create.c
- tsl/src/compression/create.h
- tsl/src/init.c
- tsl/src/process_utility.c
- tsl/src/process_utility.h
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_ddl.sql
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/compression_alter.sql
ALTER TABLE <hypertable> RENAME <column_name> TO <new_column_name>
is now supported for hypertables that have compression enabled.
To reviewers:
This PR has multiple commits to help with reviewing test changes. These will be merged.
> Support column renames on tables that have compression enabled.

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.0.1--2.0.2.sql
- sql/updates/latest-dev.sql
- version.config
This maintenance release contains bugfixes since the 2.0.1 release. We
deem it high priority for upgrading.
The bug fixes in this release address issues with joins, the status of
background jobs, and disabling compression. It also includes
enhancements to continuous aggregates, including improved validation
of policies and optimizations for faster refreshes when there are a
lot of invalidations.
**Minor features**
* #2926 Optimize cagg refresh for small invalidations
**Bugfixes**
* #2850 Set status for backend in background jobs
* #2883 Fix join qual propagation for nested joins
* #2884 Add GUC to control join qual propagation
* #2885 Fix compressed chunk check when disabling compression
* #2908 Fix changing column type of clustered hypertables
* #2942 Validate continuous aggregate policy …
> Release 2.0.2

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release adds major new features since the 2.0.2 release.
We deem it moderate priority for upgrading.
This release adds the long-awaited support for PostgreSQL 13 to TimescaleDB.
The minimum required PostgreSQL 13 version is 13.2 due to a security vulnerability
affecting TimescaleDB functionality present in earlier versions of PostgreSQL 13.
This release also relaxes some restrictions for compressed hypertables;
namely, TimescaleDB now supports adding columns to compressed hypertables
and renaming columns of compressed hypertables.
**Major Features**
* #2779 Add support for PostgreSQL 13
**Minor features**
* #2736 Support adding columns to hypertables with compression enabled
* #2909 Support renaming columns of hypertables with compression enabled
> Release 2.1.0

- .github/workflows/alpine-32bit-build-and-test.yaml
- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
Notifying a Slack channel on regression test failures fails in a fork,
which is common for PRs. The failed Slack error is confusing, since it
disturbs from checking actual regression test failure. Furthermore,
notifying Slack is not needed in the case of PRs as developers rely on
GitHub's GUI around PRs. This commit fixes GH Actions workflows to not
notify Slack on PRs.
> Do not notify Slack if in PR

- src/chunk_insert_state.c
- tsl/src/data_node_dispatch.c
- tsl/src/fdw/modify_plan.c
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/sql/dist_hypertable.sql.in
Our current support is limited to "ON CONFLICT DO NOTHING" without
specifying any inference index columns. While we do error out in the
other cases, the error messages do not convey things clearly. So rework
them.
> Clearer error messages for ON CONFLICT DO [NOTHING|UPDATE] scenarios

- src/histogram.c
In the histogram deserialization function the StringInfoData's pointer
is set to VARDATA(...) which does not include the varlen header, while
the length is set to VARSIZE(...) which does include the header's
length.
Fixes #2684
> Fix off by 4 error in histogram deserialize

- CHANGELOG.md
- src/process_utility.c
- test/expected/ddl-11.out
- test/expected/ddl-12.out
- test/expected/ddl-13.out
- test/sql/ddl.sql.in
The index creation code would take the IndexInfo from the hypertable
and adjust it for the chunk but wouldnt reset IndexInfo for each
individual chunk leading to errors when the hypertable has dropped
columns.
Fixes #2504
> Fix index creation for hypertables with dropped columns

- sql/ddl_api.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/debug_wait.h
- test/expected/extension.out
- tsl/src/CMakeLists.txt
- tsl/src/dist_backup.c
- tsl/src/dist_backup.h
- tsl/src/init.c
- tsl/src/remote/txn.c
- tsl/test/expected/dist_backup.out
- tsl/test/isolation/expected/dist_restore_point.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/dist_restore_point.spec.in
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_backup.sql
This change adds `create_distributed_restore_point()` function
which allows to create recovery restore point across
nodes.
Issue: https://github.com/timescale/timescaledb/issues/2846
> Add distributed restore point functionality

- test/expected/histogram_test.out
- test/sql/histogram_test.sql
- tsl/test/expected/compression_hypertable.out
- tsl/test/expected/continuous_aggs_refresh.out
- tsl/test/sql/compression_hypertable.sql
- tsl/test/sql/continuous_aggs_refresh.sql
Add missing ORDER BY clause to queries in histogram_test,
compression_hypertable, and continuous_aggs_refresh test.
> Add missing ORDER BY to flaky tests

- CONTRIBUTING.md
Since we require that commit messages follow seven rules of writing good
commit messages and include GitHub issues number, this commit clarifies these
requirements in the contribution.
> Explain commit message requirement in contribution

- scripts/test_update_from_tag.sh
- test/sql/updates/setup.continuous_aggs.v2.sql
- test/sql/updates/setup.policies.sql
In order to support smoke-testing with a single server, the update
tests are refactored. This is part of a longer sequence of changes to
support both running smoke tests and update tests and contain the
following changes:
- All timestamp columns now have `not null` added to avoid spamming the
output file and help finding the real issue.
- Extension of dump files are changed from `sql` to `dump` since they
use the custom format and are not SQL files.
> Refactor update tests for smoke testing

- test/src/bgw/log.c
- tsl/src/remote/connection.c
A weird crash was coming up while running the bgw_db_scheduler test
while using log_min_messages with DEBUG3 setting. So what's happening
here is that we register a RegisterXactCallback callback which gets
called at post-commit time. This remote_connection_xact_end callback
was issuing a debug3 level message. As part of its processing, the
emit_log_hook_callback function was trying to write this message
to a catalog table via a transaction. Obviously trying to start a
transaction at this post-commit stage will error out and leads to
weird behavior and crashes. In general it's not a good idea to have
emit_log_hook_callback functions start transactions because messages
can be emitted at any point of a transaction cycle, but we have to live
with the current code for now.
The fix is to reset …
> Fix crash due to txns in emit_log_hook_callback

- src/telemetry/telemetry.c
Much like PR https://github.com/timescale/timescaledb/pull/2573 before it, this will allow us to track usage of the timescale_analytics extension.
Sven and Dmitry, you approved the last one, want to get this one too?
> Add timescale_analytics to telemetry

- scripts/test_update_from_tag.sh
- scripts/test_update_smoke.sh
- test/sql/updates/post.continuous_aggs.sql
- test/sql/updates/pre.cleanup.sql
- test/sql/updates/pre.smoke.sql
- test/sql/updates/pre.testing.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
- test/sql/updates/setup.databases.sql
- test/sql/updates/setup.repair.sql
- test/sql/updates/setup.timestamp.sql
- test/sql/updates/setup.v2.sql
In order to support smoke-testing with a single server, the update
tests are refactored to not require a `postgres` user with full
privileges. The following changes where made:
- Database creation code was factored out of tests and is only executed
for update tests.
- Since the default for `docker_pgscript` was to use the `postgres`
database and the database creation code also switched database to
`single` as part of the execution, the default of `docker_pgscript` is
now changed to `single`.
- Parts of tests that changes roles during execution was removed since
it is more suitable for a regression test and does not work unless you have superuser privileges.
- Operations that require escalated privileges are factored out into
support functions that execute the original code for update …
> Break out superuser operations in update tests

- CMakeLists.txt
- test/expected/trusted_extension.out
- test/sql/CMakeLists.txt
- test/sql/trusted_extension.sql
- timescaledb.control.in
PG13 adds the trusted attribute to extensions. Extensions marked
as trusted do not require superuser privileges, but can be installed
by a non-superuser with CREATE privilege in the database.
The objects within the extension will be owned by the bootstrap
superuser, but the extension itself will be owned by the calling user.
https://github.com/postgres/postgres/commit/50fc694e
> Mark timescaledb as trusted extension

- CMakeLists.txt
If an unsupported CMake build type is used, it is accepted but generate
strange builds for the compiler. This commit adds a check that only one
of the standard build types are used.
> Check CMake build type

- test/isolation/expected/multi_transaction_indexing.out
- test/isolation/specs/multi_transaction_indexing.spec
There is a race condition between `CREATE INDEX` and `DROP INDEX` so
disabling that test in `multi_transaction_indexing`.
> Disable test in multi_transaction_indexing

- docs/StyleGuide.md
Declarations before code has been informally supported and we have
several examples in the code. This commit adds that guideline to the
coding guidelines.
> Add declaration before code to guidelines

- .github/workflows/update-test.yaml
- scripts/test_functions.inc
- scripts/test_repair_from_tag.sh
- scripts/test_repairs.sh
- scripts/test_update_from_tag.sh
- scripts/test_update_smoke.sh
- scripts/test_updates.sh
- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
- scripts/test_updates_pg13.sh
- test/sql/updates/post.integrity_test.sql
- test/sql/updates/setup.repair.sql
- test/sql/updates/setup.v6.sql
In order to implement repair tests, changes are made to the
`constraint_check` table to simulate a broken dependency, which
requires the constraints on that table to be dropped. This means that
the repair runs without constraints, and a bug in the update test could
potentially not get caught.
This commit fixes this by factoring out the repair tests from the
update tests and run them as a separate pass. This means that the
contraints are not dropped in the update tests and bugs there will be
caught.
> Factor out repair test from update test

- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/test/expected/continuous_aggs_policy.out
Adds an error detail, which clarifies that only one continuous
aggregate policy can be created per a continuous aggregate. It also
reports the job id of the continuous aggregate policy, which already
exists.
> Add error detail for failed refresh policy

- tsl/test/sql/CMakeLists.txt
The `data_fetcher` test currently causes tests to fail regularly when
run in parallel. Therefore, this change moves `data_fetcher` to solo
tests.
> Make data_fetcher solo test to fix failing tests

- CHANGELOG.md
- src/process_utility.c
- test/isolation/expected/multi_transaction_indexing.out
- test/isolation/specs/CMakeLists.txt
- test/isolation/specs/multi_transaction_indexing.spec.in
When executing `CREATE INDEX` with `transaction_per_chunk` one
transaction is created at the start to mark the index as invalid, a
session lock is taken to prevent competing `DROP INDEX` from modifying
the indexes, then each chunk is updated inside a separate transaction,
one transaction is created to mark the index as valid, and lastly the
session lock is released.
However, the last transaction was not committed and left open, so a
competing `DROP INDEX` would try to read index status after the session
lock was released, resulting in a concurrent access of the index row
from the `CREATE INDEX`.
This commit fixes that by committing the transaction before releasing
the session lock (and starting another transaction to match the
end-of-statement commit that is done later).
Fixes #3021
NOTE: …
> Commit end transaction for CREATE INDEX

- tsl/src/nodes/decompress_chunk/planner.c
This patch fixes a typo in DecompressChunk comment and also changes
the initialization function to use the node name from the
CustomScanMethods struct instead of hardcoding it.
> Fix typo in DecompressChunk comment

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/size_utils.sql
- sql/updates/latest-dev.sql
- test/expected/relocate_extension.out
- test/expected/size_utils.out
- test/isolation/expected/multi_transaction_indexing.out
- test/sql/size_utils.sql
- tsl/test/expected/compression.out
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_util.out
- tsl/test/expected/dist_views.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_util.sql
Fix a number of issues with size and stats functions:
* Return `0` size instead of `NULL` in several functions when
hypertables have no chunks (e.g., `hypertable_size`,
`hypertable_detailed_size`).
* Return `NULL` when functions are called on non-hypertables instead
of simply failing with generic error `query returned no rows`.
* Include size of "root" hypertable, which can have non-zero size
indexes and other objects even if the root table holds no data.
* Make `hypertable_detailed_size` include one additional row for
storage size of objects on the access node. While the access node
stores no data, the empty hypertable may still take up some disk
space.
* Improve test coverage for all size utility functions. In particular,
add tests on regular tables as well as empty and compressed …
> Refactor and harden size and stats functions 

- src/debug_wait.c
- src/debug_wait.h
- tsl/src/remote/connection.c
- tsl/test/expected/remote_txn.out
- tsl/test/sql/remote_txn.sql
The remote_txn.sql test used to be consistently flaky in CI runs.
The RegisterXactCallback function in the test does the following on the
access node:
1) Send an async command to the remote node
2) Invoke the eventcallback, for example:
eventcallback(DTXN_EVENT_WAIT_COMMIT) which kills the remote node
backend
3) Wait for async responses for (1) from remote node and expect it to
fail due to the killing of the remote backend in (2) above.
The above works most of the times but it's possible that (1) completes
successfully and returns successful async response via (3) before the
remote backend gets killed via (2).
To make things more predictable, we now use the DEBUG_WAITPOINT
infrastructure.
To ensure predictability, we want to kill the remote backend when it's
in the midst of processing the …
> Fix flaky remote_txn.sql test

- CHANGELOG.md
- src/chunk_insert_state.c
- test/expected/insert-11.out
- test/expected/insert-12.out
- test/expected/insert-13.out
- test/sql/insert.sql.in
When a column with a DEFAULT was added to a hypertable after
hypertable creation this column would have atthasmissing true
for the hypertable itself but not for chunks created after.
This lead to the attribute mapping from the hypertable to
the chunk being non-NULL but the chunk -> hypertable map being
NULL leading to a segfault because the code assumed both maps
would either be NULL or non-NULL.
Fixes #3036 
Fixes #3037
> Fix UPSERT on hypertables with columns with defaults

- CHANGELOG.md
- src/plan_add_hashagg.c
- tsl/test/shared/expected/gapfill-11.out
- tsl/test/shared/expected/gapfill-12.out
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/sql/gapfill.sql.in
The hashagg optimization adds a hashagg plan with modified costs
to the list of paths. This happens after gapfill pathes have been
created so those newly created pathes would miss the GapFill node.
If those created pathes would turn out to be cheaper than other
pathes GapFill would fail to work as no GapFill node would be
executed.
This patch changes hashagg path creation to skip adding pathes
when there is a GapFill path.
Fixes #3048
> Fix gapfill/hashagg planner interaction

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This maintenance release contains bugfixes since the 2.1.0 release. We
deem it high priority for upgrading.
The bug fixes in this release address issues with CREATE INDEX and
UPSERT for hypertables, custom jobs, and gapfill queries.
This release marks TimescaleDB as a trusted extension in PG13, so that 
superuser privileges are not required anymore to install the extension.
**Minor features**
* #2998 Mark timescaledb as trusted extension
**Bugfixes**
* #2948 Fix off by 4 error in histogram deserialize
* #2974 Fix index creation for hypertables with dropped columns
* #2990 Fix segfault in job_config_check for cagg
* #2987 Fix crash due to txns in emit_log_hook_callback
* #3042 Commit end transaction for CREATE INDEX
* #3053 Fix gapfill/hashagg planner interaction
* #3059 Fix UPSERT on …
> Release 2.1.1

- CHANGELOG.md
- tsl/src/data_node_dispatch.c
The data node dispatcher used a per-tuple memory context that wasn't
automatically reset as part of each iteration of the execution
loop. This lead to linearly growing memory usage over a transaction
that inserted a lot of data.
This change switches to using the right per-tuple memory context and
also introduces a new "batch" memory context that maintains the batch
data until it is fully processed and the next batch is read. These
changes mean that memory usage never grows higher than what is needed
for one batch, which will avoid out-of-memory situations.
Fixes #3049
> Reduce memory usage for distributed inserts

- .github/workflows/pr-validation.yaml
This commit adds a GitHub action that will check that there is only a
single commit in the pull request and trigger an error if that is not
the case.
The check can be disabled by adding the following line as a trailer to
the pull request message (case-insensitive check). Note that only the
pull request body is checked. Trailers are assumed to follow RFC2822
conventions, even though this is not formally enforced right now.
Disable-Check: commit-count
> Add GitHub action to ensure a single commit

- CHANGELOG.md
- src/hypertable_restrict_info.c
- src/hypertable_restrict_info.h
- src/plan_expand_hypertable.c
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/sql/dist_hypertable.sql.in
It was observed on DNs that "ORDER BY time" queries when the
"chunks_in" exclusion function was specified were running slower than
expected.
Examination of the EXPLAIN output revealed that when "chunks_in" was
specified then the ChunkAppend plan which provides the exclusion of
unwanted chunks was not getting picked up for execution.
Logic in get_explicit_chunk_oids() function has now been improved to
populate the fdw_private structure appropriately if ordering info is
present. Care has been taken to also handle the case where multiple
dimensions are present.
Fixes #2733
> Fix chunks_in queries to use ChunkAppend plans

- .github/workflows/code_style.yaml
- src/constraint_aware_append.c
- src/constraint_aware_append.h
- src/planner.c
The hypertable argument to ts_constraint_aware_append_path_create was
never actually used in the function so this patch removes it.
> Remove Hypertable argument from ts_constraint_aware_append_path_create

- test/pg_regress.sh
This patch enables the use of wildcards in TESTS allowing you to
specify multiple tests with a single pattern.
```
TESTS="compression*" will match all tests whose name starts with compression
TESTS="*compression*" will match all tests that have compression anywhere in the name
Wildcard matching also applies to version specific tests so compression-13
would also be matched by those patterns.
```
> Allow use of wildcards in TESTS

- scripts/gh_matrix_builder.py
clang-8 is no longer installed by default in the ubuntu images so
we have to explicitly install it for any actions that require it.
https://github.com/actions/virtual-environments/issues/2950
> Install clang-8 for PG11.0 CI test

- .github/workflows/linux-build-and-test.yaml
Slack notification only works on Linux and produces error if it is
called during MacOS test. This fix avoids notifying Slack if a
regression test is run on MacOS.
PR comment:
[This build](https://github.com/timescale/timescaledb/runs/2272609163?check_suite_focus=true#step:20:15) contains the error:
```
Run rtCamp/action-slack-notify@v2.0.2
Error: Container action is only supported on Linux
```
> Do not notify Slack for MacOS test

- CHANGELOG.md
- src/chunk_append/chunk_append.c
- test/expected/append-11.out
- test/expected/append-12.out
- test/expected/append-13.out
- test/expected/query-12.out
- test/expected/query-13.out
- test/sql/include/append_query.sql
- tsl/test/expected/continuous_aggs_query-13.out
- tsl/test/expected/continuous_aggs_union_view-12.out
- tsl/test/expected/continuous_aggs_union_view-13.out
- tsl/test/expected/jit-13.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
This changes ChunkAppend to always keep the pathkeys from the original
path because the original path was either a MergeAppendPath and this
will become an ordered append or the original path is an AppendPath
and since we do not reorder children the order will be kept intact.
For the AppendPath case with pathkeys it was most likely an Append
with only a single child. We could skip the ChunkAppend path creation
if there is only a single child but we decided earlier that ChunkAppend
would be beneficial for this query so we treat it the same as if it
had multiple children.
Fixes #3030
> Keep Append pathkeys in ChunkAppend

- src/catalog.c
- src/catalog.h
- src/chunk.c
- src/chunk.h
- src/chunk_constraint.c
- src/hypercube.c
- src/hypercube.h
- src/hypertable.c
- src/hypertable.h
- tsl/src/chunk_api.c
Separates chunk preparation and metadata update. Separates preparation
of constraints names, since there is no overlap between preparing
names for dimension constraints and other constraints. Factors out 
creation of json string describing dimension slices of a chunk.
This refactoring is preparation for implementing new functionalities.
> Refactor chunk creation for future extension

- CHANGELOG.md
- src/chunk_index.c
- src/chunk_index.h
- src/process_utility.c
- test/expected/index.out
- test/pgtest/CMakeLists.txt
- test/sql/index.sql
When mapping index columns references from the hypertable index
to the chunk index the name of the index column was used instead
of the column name of the hypertables. While those names are
identical most of time unless modified this is not true for indexes
with INCLUDE on a column that is also a key column.
Fixes #3056
> Fix chunk index column name mapping

- tsl/test/isolation/expected/dist_restore_point.out
- tsl/test/isolation/specs/dist_restore_point.spec.in
The test fails on PG11.0 since there is no notice during data node deletion. Reduce client notice level to warning, to make it compatible with other versions.
Fixes https://github.com/timescale/timescaledb/issues/3093
> Fix dist_restore_point test on PG11.0

- .github/workflows/pr-validation.yaml
The github action to check for multiple commits would check the
pullrequest message for a command to disable the check.
While processing the message any commands enclosed in backticks
would be executed as shell commands.
> Fix command execution in pr-validation

- tsl/src/nodes/skip_scan/planner.c
- tsl/test/expected/plan_skip_scan-11.out
- tsl/test/expected/plan_skip_scan-12.out
- tsl/test/expected/plan_skip_scan-13.out
- tsl/test/expected/skip_scan.out
- tsl/test/sql/include/skip_scan_query.sql
If the row estimate for the scan below Skip Scan is 1 we assume that the
estimate got clamped to 1 and no rows would be returned by this scan and
this chunk will most likely be excluded by runtime exclusion.
Otherwise the cost for this path would be highly inflated due to
(ndistinct / rows) * total leading to SkipScan not being chosen for
queries on hypertables with a lot of excluded chunks.
> Fix Skip Scan cost calculation for queries with excluded chunks

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.1.1--2.2.0.sql
- sql/updates/latest-dev.sql
- version.config
This release adds major new features since the 2.1.1 release.
We deem it moderate priority for upgrading.
This release adds the Skip Scan optimization, which significantly 
improves the performance of queries with DISTINCT ON. This 
optimization is not yet available for queries on distributed 
hypertables.
This release also adds a function to create a distributed 
restore point, which allows performing a consistent restore of a 
multi-node cluster from a backup.
The bug fixes in this release address issues with size and stats 
functions, high memory usage in distributed inserts, slow distributed 
ORDER BY queries, indexes involving INCLUDE, and single chunk query 
planning.
**PostgreSQL 11 deprecation announcement**
Timescale is working hard on our next exciting features. To make that …
> Release 2.2.0

- CHANGELOG.md
- CMakeLists.txt
get_git_commit used the author date instead of the commit date
when showing information about the commit. For the purpose of
the function the author date is not that significant and when
the commit to the branch actually happened is much more relevant.
> Use commit date in get_git_commit()

- CMakeLists.txt
Possible values are Release, Debug, RelWithDebInfo and MinSizeRel
https://llvm.org/docs/CMake.html#frequently-used-cmake-variables
> Fix CMAKE_BUILD_TYPE check

- CHANGELOG.md
- tsl/src/bgw_policy/reorder_api.c
The hypertable object in policy_reorder_add was still used after
releasing the cache leading to occasional segfaults in CI.
https://github.com/timescale/timescaledb/pull/3100/checks?check_run_id=2321566721
Fixes https://github.com/timescale/timescaledb-private/issues/906
> Fix use after free in add_reorder_policy

- src/bgw/scheduler.c
- src/hypertable_restrict_info.c
- src/plan_agg_bookend.c
- src/time_bucket.c
- src/utils.c
- test/src/bgw/scheduler_mock.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/compression/compression.c
- tsl/src/compression/create.c
- tsl/src/compression/deltadelta.c
- tsl/src/compression/gorilla.c
- tsl/src/continuous_aggs/create.c
- tsl/src/deparse.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
Since Oid is unsigned int we have to use %u to print it otherwise
oids >= 2^31 will not work correctly.
> Use %u to format Oid instead of %d

- src/cache.c
When calling hash_search with HASH_REMOVE the returned pointer should not
be dereferenced because it returns a dangling pointer
Issue: https://github.com/timescale/timescaledb-private/issues/914
> Fix use after free in cache

- CHANGELOG.md
- src/process_utility.c
- test/expected/index-11.out
- test/expected/index-12.out
- test/expected/index-13.out
- test/sql/CMakeLists.txt
- test/sql/index.sql.in
Fix crash while using REINDEX TABLE CONCURRENTLY
CONCURRENTLY option of the REINDEX TABLE is not supported and
leads to a crash when using with hypertable. Block it and print
the error message.
Fix #3122
> Fix crash while using REINDEX TABLE CONCURRENTLY

- CHANGELOG.md
- src/utils.h
- tsl/src/fdw/deparse.c
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_query-11.out
- tsl/test/expected/dist_query-12.out
- tsl/test/expected/dist_query-13.out
- tsl/test/shared/expected/dist_distinct.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_distinct.sql
- tsl/test/shared/sql/include/dist_distinct_run.sql
Construct "SELECT DISTINCT target_list" or "SELECT DISTINCT ON (col1,
col..) target_list" statement to push down the DISTINCT clause to the
remote side.
We only allow references to basic "Vars" or constants in the DISTINCT
exprs
So, "SELECT DISTINCT col1" is fine but "SELECT DISTINCT 2*col1" is not.
"SELECT DISTINCT col1, 'const1', NULL, col2" which is a mix of column
references and constants is also supported. Everything else is not
supported.
This pushdown also needs to work when
timescaledb.enable_per_data_node_queries is disabled.
All existing test cases in which "SELECT DISTINCT" is now being pushed
down have been modified. New test cases have been added to check that
the remote side uses "Skip Scans" as is suitable in some cases.
> Add "SELECT DISTINCT" pushdown in multi-node

- test/sql/.gitignore
- tsl/test/shared/sql/.gitignore
`index` test was moved into SQL test template in #3123 and
`generated_columns` - in #2927. They are added to relevant gitignore.
> Ignore generated SQL test files from templates

- .github/workflows/code_style.yaml
Checking code formatting and other simple code style test is good to
perform on PRs to feature branches, not only the master branch. This
commit removes the limitation to perform tests only on PR to the
master.
> Run code style regression test on all PRs

- test/expected/pg_dump.out
- test/sql/pg_dump.sql
This patch fixes the flaky pg_dump test by switching off the current
database before using it as template. It also disables background
job scheduling instead of stopping them before creating the new
database as stopping bgw jobs might not happen immediately.
Fixes #2847
> Fix flaky pg_dump test

- CHANGELOG.md
- tsl/src/nodes/skip_scan/planner.c
- tsl/test/expected/plan_skip_scan-11.out
- tsl/test/expected/plan_skip_scan-12.out
- tsl/test/expected/plan_skip_scan-13.out
- tsl/test/sql/include/skip_scan_query_ht.sql
The SkipScan code assumed IndexPaths on ordered indexes always
have pathkeys which is not true when the pathkeys are not useful
for the query, leading to a segfault for those queries.
> Fix SkipScan for IndexPaths without pathkeys

- src/planner.c
- test/expected/append-12.out
- test/expected/append-13.out
- tsl/test/expected/continuous_aggs_union_view-12.out
- tsl/test/expected/continuous_aggs_union_view-13.out
Since postgres has optimizations for Append paths without children
we do not replace those paths with ChunkAppend. While this will
prevent ChunkAppendPaths without children during planning, in the
executor it is still possible for ChunkAppend to have no children
as run-time exclusion may remove all of them.
> Skip ChunkAppend if AppendPath has no children

- tsl/src/fdw/deparse.c
- tsl/test/shared/expected/dist_distinct.out
- tsl/test/shared/sql/include/dist_distinct_run.sql
The current SELECT DISTINCT pushdown code assumed that the targetlist
will always contain references to column attributes of the target
table.
So, even a simple "SELECT DISTINCT 1 from table;" causes a segmentation
fault because the "varno" field is not assigned. Fix this oversight.
Issue reported by @svenklemm
Fixes timescale/timescaledb-private#920
> Make SELECT DISTINCT handle non-var targetlists

- .github/workflows/alpine-32bit-build-and-test.yaml
- .github/workflows/apt-packages.yaml
- .github/workflows/ci_summary.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/rpm-packages.yaml
- .github/workflows/update-test.yaml
- scripts/gh_ci_summary.py
This patch adds a GitHub action that posts all failed CI jobs in
the last 24 hours with link to the failed job.
> Add GitHub action for posting daily CI summary

- src/indexing.c
- src/indexing.h
- src/nodes/chunk_dispatch_state.c
- src/nodes/chunk_insert_state.c
- src/nodes/chunk_insert_state.h
- tsl/src/compression/compression.c
- tsl/src/compression/segment_meta.c
- tsl/src/compression/segment_meta.h
- tsl/test/expected/compression.out
- tsl/test/expected/compression_insert.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_insert.sql
This  is the 2nd PR and builds on the initial framework.
Inserts are supported by making calls to CompressRowSingleState
(1st PR is : https://github.com/timescale/timescaledb/pull/3105 )
> Support for inserts into compressed chunks

- scripts/test_functions.inc
- scripts/test_update_from_tag.sh
- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
- sql/updates/post-update.sql
- sql/updates/pre-update.sql
- test/sql/updates/post.catalog.sql
- test/sql/updates/post.continuous_aggs.sql
- test/sql/updates/setup.catalog.sql
- test/sql/updates/setup.roles.sql
- test/sql/updates/setup.v2.sql
Tables, indexes, and sequences that are recreated as part of an update
does not propagate permissions to the recreated object. This commit
fixes that by saving away the permissions in `pg_class` temporarily and
then copying them back into the `pg_class` table.
If internal objects are created or re-created, they get the wrong
initial privileges, which result in privileges not being dumped when
using `pg_dump`. Save away the privileges before starting the update
and restore them afterwards to make sure that the privileges are
maintained over the update.
For new objects, we use the initial privileges of the `chunk` metadata
table, which should always have correct initial privileges.
Fixes #3078
> Copy recreated object permissions on update

- sql/chunk.sql
- src/chunk.c
- src/chunk.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/dimension.c
- tsl/src/chunk_api.c
- tsl/src/chunk_api.h
- tsl/src/init.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/chunk_api-13.out
- tsl/test/sql/chunk_api.sql.in
Adds an internal API function to create an empty chunk table according 
the given hypertable for the given chunk table name and dimension 
slices. This functions creates a chunk table inheriting from the 
hypertable, so it guarantees the same schema. No TimescaleDB's 
metadata is updated.
To be able to create the chunk table in a tablespace attached to the 
hyeprtable, this commit allows calculating the tablespace id without 
the dimension slice to exist in the catalog.
If there is already a chunk, which collides on dimension slices, the 
function fails to create the chunk table.
The function will be used internally in multi-node to be able to 
replicate a chunk from one data node to another.
> Create an empty chunk table

- .github/workflows/linux-32bit-build-and-test.yaml
This patch adds coredump support for the 32bit CI runs. This patch
switches 32bit run to the debian base image and install postgres
from PGDG instead of using the alpine image so we don't have to
compile postgres ourselves and can just install the debugsymbol
package for postgres.
> Add coredump support for 32bit ci runs

- sql/chunk.sql
- src/error_utils.h
- tsl/src/chunk_api.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/chunk_api-13.out
- tsl/test/sql/chunk_api.sql.in
Gives errors if any argument of create_chunk_table is NULL instead of 
being STRICT. Utilizes newly added macros for this.
PR notes:
This PR addresses comments from @erimatnor @pmwkaa @nikkhils about #3137
> Return error for NULL input to create_chunk_table

- CMakeLists.txt
We started inheriting CFLAGS from postgresql via ba51adc3. Although we
remove "-W" flags, we still end up accepting other options like "-L"
from postgresql. This can cause compilation to fail with compilers
like Clang which enable reporting of errors on unused command line
arguments.
This patch conditionally adds -Wno-unused-command-line-argument in
our cmake files to avoid unhelpful unused-command-line-argument
warnings/errors.
> Use no-unused-command-line-argument flag

- CHANGELOG.md
- tsl/src/bgw_policy/compression_api.c
The int64 compress after read from compression policy is cast to an int32, which causes compression jobs behave not as expected when the value is > 2^31 -1.
Verified the patch fixes the issue with compress after of 7 days in nanos and chunk time interval of 1 day.
Fixes #3009 
> Fix incorrect type cast when reading int64 compress after

- src/chunk.c
- tsl/src/fdw/deparse.c
1) Quell a compiler warning about uninitialized use of "varno"
variable.
2) Fix ts_chunk_get_by_name to return early if rogue schema/table args
are passed in.
> Add a few miscellaneous code fixes

- src/chunk.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/chunk_api-13.out
- tsl/test/sql/chunk_api.sql.in
When an empty chunk table is created, it is not associated with its
hypertable in metadata, however it was inheriting from the hypertable.
This commit removes inheritance, so the chunk table is completely
standalone and cannot affect queries on the hypertable.
In future, this fix of dropping inherit can be replaced with the chunk
table creation, which does not create inheritance in the first place.
Since it is larger amount of work, it was not considered now.
> Drop inherit from chunk table to hypertable

- sql/ddl_internal.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/chunk_api.c
- tsl/src/chunk_api.h
- tsl/src/data_node.c
- tsl/src/data_node.h
- tsl/src/init.c
- tsl/src/remote/dist_commands.c
- tsl/src/remote/dist_commands.h
- tsl/test/shared/expected/dist_chunk.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_chunk.sql
- tsl/test/shared/sql/include/shared_setup.sql
Creates a table for chunk replica on the given data node. The table 
gets the same schema and name as the chunk. The created chunk replica 
table is not added into metadata on the access node or data node.
The primary goal is to use it during copy/move chunk.
> Create chunk table from access node

- src/chunk.h
- tsl/src/compression/compression.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
Compressed chunks with inserts after being compressed have batches
that are not ordered according to compress_orderby for those
chunks we cannot set pathkeys on the DecompressChunk node and we
need an extra sort step if we require ordered output from those
chunks.
> Adjust pathkeys generation for unordered compressed chunks

- sql/ddl_internal.sql
- src/chunk.c
- src/chunk.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/init.c
- tsl/test/shared/expected/chunk_move_copy.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/chunk_move_copy.sql
This function drops a chunk on a specified data node. It then removes
the metadata about the datanode, chunk association on the access node.
This function is meant for internal use as part of the "move chunk"
functionality.
If only one chunk replica remains then this function refuses to drop it
to avoid data loss.
> Implement drop_chunk_replica API

- CHANGELOG.md
- tsl/src/bgw_policy/retention_api.c
When reading the configuration for retention policy of integer
based hypertables int32 was used instead of int64.
Fixes #2877
> Fix wrong datatype in integer based retention policy

- src/chunk_adaptive.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Block calling calculate_chunk_interval on distributed hypertables
to prevent segfault when finding min and max as distributed chunks
have no tableam since they are foreign tables.
> Fix segfault in calculate_chunk_interval

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This maintenance release contains bugfixes since the 2.2.0 release. We
deem it high priority for upgrading.
This release extends Skip Scan to multinode by enabling the pushdown
of `DISTINCT` to data nodes. It also fixes a number of bugs in the
implementation of Skip Scan, in distributed hypertables, in creation
of indexes, in compression, and in policies.
**Features**
* #3113 Pushdown "SELECT DISTINCT" in multi-node to allow use of Skip
Scan
**Bugfixes**
* #3101 Use commit date in `get_git_commit()`
* #3102 Fix `REINDEX TABLE` for distributed hypertables
* #3104 Fix use after free in `add_reorder_policy`
* #3106 Fix use after free in `chunk_api_get_chunk_stats`
* #3109 Copy recreated object permissions on update
* #3111 Fix `CMAKE_BUILD_TYPE` check
* #3112 Use `%u` to format Oid instead …
> Release 2.2.1

- sql/chunk.sql
- sql/updates/latest-dev.sql
- src/chunk.c
- src/chunk.h
- tsl/src/chunk_api.c
- tsl/test/expected/chunk_api-11.out
- tsl/test/expected/chunk_api-12.out
- tsl/test/expected/chunk_api-13.out
- tsl/test/sql/chunk_api.sql.in
The `create_chunk` API has been extended to allow creating a chunk
from an existing relational table. The table is turned into a chunk by
attaching it to the root hypertable via inheritance.
The purpose of this functionality is to allow copying a chunk to
another node. First, the chunk table and data is copied. After that,
the `create_chunk` can be executed to make the new table part of the
hypertable.
Currently, the relational table used to create the chunk has to match
the hypertable in terms of constraints, triggers, etc. PostgreSQL
itself enforces the existence of same-named CHECK constraints, but no
enforcement currently exists for other objects, including triggers
UNIQUE, PRIMARY KEY, or FOREIGN KEY constraints. Such enforcement can
be implemented in the future, if deemed necessary. …
> Add ability to create chunk from existing table

- src/cross_module_fn.h
Use the `PGFunction` type on all PostgreSQL function definitions when
defining cross-module (TSL) functions.
> Clean up cross-module function definitions

- tsl/LICENSE-TIMESCALE
In the definition of "Timescale Data Manipulation Interfaces", the description of
Data Manipulation Language was accidentally and erroneously given the acronym
"DDL" as a parenthetical, when it should have been (and was meant to be) given
the proper acronym of "DML". No intent is changed with this correction.
> Fix accidental misused acronym for Data Manipulation Language

- src/process_utility.c
- tsl/src/nodes/data_node_dispatch.c
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/ddl_hook.out
- tsl/test/expected/dist_ddl.out
- tsl/test/expected/dist_hypertable-11.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_triggers.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_ddl.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/dist_triggers.sql
This change makes it possible to create and use triggers on
distributed hypertables. The DDL for `CREATE TRIGGER` and `DROP
TRIGGER` are now forwarded to data nodes. Previously, `CREATE TRIGGER`
worked, but didn't forward the DDL command.
Note that triggers exist only on the data nodes and on the data node's
root hypertable. Triggers need to execute on the data nodes where data
is stored; in particular, row-based "before" triggers might modify the
tuple. On the access node, chunks are foreign tables and such tables
do not support triggers.
Also note that statement-level triggers execute once on each node
involved, including the access node. So, if, e.g., two rows are
inserted into two different data nodes in the same statement, a
statement-level insert trigger will fire once on the access …
> Add trigger support on distributed hypertables

- sql/maintenance_utils.sql
- sql/updates/latest-dev.sql
- src/chunk.c
- src/chunk.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/dimension_slice.c
- src/nodes/chunk_insert_state.c
- test/expected/extension.out
- tsl/src/bgw_policy/job.c
- tsl/src/compression/compress_utils.c
- tsl/src/compression/compress_utils.h
- tsl/src/compression/compression.c
- tsl/src/init.c
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/dist_compression.out
- tsl/test/isolation/expected/compression_ddl.out
- tsl/test/sql/compression_bgw.sql
- tsl/test/sql/compression_insert.sql.in
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/recompress_basic.sql
After inserts go into a compressed chunk, the chunk is marked as unordered.
This PR adds a new function recompress_chunk that compresses the data and sets the status back to
compressed. Further optimizations for this function are planned but not part of this PR.
This  function can be invoked by calling `SELECT recompress_chunk(<chunk_name>)`.
recompress_chunk function is automatically invoked by the compression policy job, when it sees that a chunk is in unordered state.
> Support for compressing chunks that are in unordered state

- src/nodes/chunk_dispatch_state.c
- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
This patch adds support for BEFORE ROW insert triggers defined
on the uncompressed chunk when inserting into a compressed chunk.
> Add support for BEFORE ROW insert triggers

- tsl/src/compression/compression.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_permissions.out
- tsl/test/sql/compression_permissions.sql
Make use of BulkInsertState optional in row compressor
Add test for insert into compressed chunk by a different role
other than the owner
Fix broken test output
> More cleanup

- tsl/src/compression/compress_utils.c
- tsl/src/remote/dist_copy.c
- tsl/test/expected/dist_compression.out
- tsl/test/sql/dist_compression.sql
This PR adds a test case for this case, verifies that recompress_chunk
and compression policy work as expected.
> Test support for copy on distributed hypertables with compressed chunks

- src/nodes/chunk_dispatch_state.c
- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
We first compute the tuple mapping between the hypertable
and chunk, before executing the triggers. This ensures that
metadata differences between a chunk and hypertable are
accounted for when the trigger is executed.
> Move trigger execution code for compressed chunks

- sql/views.sql
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_views.out
The timescaledb_information.chunks view used to return NULL in the is_compressed field for distributed chunks. This changes the view to always return true or false, depending on the chunk status flags in the Access Node. This is a hint and cannot be used as a source of truth for the compression state of the actual chunks in the Data Nodes.
The documentation used to say:
```
is_compressed | BOOLEAN |
Is the data in the chunk compressed?
NULL for distributed chunks.
Use chunk_compression_stats() function to get compression status for distributed chunks.
```
The new semantics are going to be:
```
is_compressed | BOOLEAN |
Is the data in the chunk compressed?
Hint for distributed chunks, it cannot be relied upon as a source of truth.
Use chunk_compression_stats() function to get reliable …
```
> Use chunk status for is_compressed field in view

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- scripts/check_file_license.sh
- scripts/check_license.sh
- scripts/check_license_all.sh
- scripts/perltidyrc
- test/perl/README.md
- test/perl/TimescaleNode.pm
- tsl/test/CMakeLists.txt
- tsl/test/t/001_simple_multinode.pl
- tsl/test/t/CMakeLists.txt
The TAP testing PG framework meets our requirements for doing
multinode/stand-alone-binaries testing for scenarios which need
individual multiple PG instances (multi-node testing is a prime
example).
This commit adds the necessary wrappers to allow the use of the TAP
testing framework in timescale code base. The README in "test/perl"
directory gives a fair idea of how to write tap tests. A simple tap
test has been added to provide a reference point for developers to
write new ones.
One can go to build/tsl/test and invoke "make checkprove" to see
the tap test in action.
Also includes changes for enabling github CI to run these taptests by
installing the requisite dependencies.
Includes changes to license checking scripts to handle new *.pl and
*.pm files.
Also added a new …
> Add tap tests infrastructure support

- src/chunk.c
Use RowExclusive lock instead of AccessShareLock when updating a
chunk's metadata.
> Use correct lock mode when updating chunk

- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/sql/transparent_decompression_queries.sql
decompress_chunk_plan_create used get_actual_clauses to extract
RestrictInfo clauses and adds them as quals. This function is only
supposed to be used when none of the RestrictInfos are pseudoconstant
leading to an assertion failure when the query has pseudoconstant
quals.
Fixes #3241
> Fix assertion failure in decompress_chunk_plan_create

- CHANGELOG.md
- src/chunk.c
chunk_scan_internal is called with 2 callback functions, a
filter function and a tuple_found function that
are invoked with the same argument. ts_chunk_set_compressed
and ts_chunk_clear_compressed use chunk_tuple_dropped_filter
but do not pass in the required ChunkStubScanCtx* as argument.
Instead an argument of type int* is passed in. This causes
a segmentation fault.
Add a new chunk filter function that is compatible with
the tuple_found function used by ts_chunk_clear_compressed_chunk
and ts_chunk_set_compressed_chunk
Fixes #3158
> Fix segmentation fault due to incorrect call to chunk_scan_internal

- test/perl/AccessNode.pm
- test/perl/DataNode.pm
- test/perl/TimescaleNode.pm
- tsl/test/t/001_simple_multinode.pl
Use subclassing to inherit from `PostgresNode` and create a hierarchy
containing `AccessNode` and `DataNode` to simplify creating tests with
multiple nodes.
Also, two new functions are added: 
`TimescaleNode::create` 
Creates the new node by calling `get_new_node`, `init` and `start` in 
that order.
`AccessNode::add_data_node`
Adds a new data node to the access node.
Also rewrite the test to use the new hierarchy.
> Add TimescaleNode subclasses for TAP Testing

- .github/workflows/coverity.yaml
GitHub only has the last 3 clang versions installed by default in
the virtual environment and no longer installed clang-9 when they
added clang-12. Since we need clang-9 to build postgres with
llvm support we need to explicitly install the required package.
https://github.com/actions/virtual-environments/pull/3381
> Explicitly install clang-9 in coverity workflow

- sql/size_utils.sql
- sql/updates/latest-dev.sql
- test/expected/size_utils.out
The view uses cached information from compression_chunk_size to
report the size of compressed chunks. Since compressed chunks
can be modified, we call pg_relation_size on the compressed chunk
while reporting the size
The view also incorrectly used the hypertable's reltoastrelid to
calculate toast bytes. It has been changed to use the chunk's
reltoastrelid.
> Fix hypertable_chunk_local_size view

- src/bgw/job.c
- src/bgw/job.h
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/continuous_aggs/job.c
When refactoring the job code the job_type was removed from our
catalog but a few places got overlooked that still had a variable
holding the job type.
> Remove unused job_type from policies

- CHANGELOG.md
The 2.3.0 release used the wrong heading level. Fix it for future
releases.
> Use correct heading level in changelog

- sql/chunk.sql
- sql/ddl_internal.sql
- src/chunk.c
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/hypertable.c
- tsl/src/init.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/src/remote/dist_commands.h
- tsl/test/t/002_copy_chunk_data.pl
- tsl/test/t/CMakeLists.txt
Add internal copy_chunk_data() function which implements a way
to copy chunk data between data nodes using logical
replication.
Some moments to consider
* this functionality needs to be tested using separate instances,  `test_copy_chunk_data.sh` been introduced for that purpose
* no chunk locking been made during the copy operation
* no tests for corner cases such as connection failure during the copy or operation retry after failure
* there is no undo/clean procedure in case if operation fails during its operation
> Introduce function to copy chunk data between data nodes

- sql/notice.sql
Hi 👋🏼 🐯
I was trying Timescale and found these links were moved to somewhere else after installed the extension:
We could either:
1) Add page redirects to existing links and keep these links unchanged, then close this PR
2) Change these links to something that should never change. Add redirects of these links so the `notice.sql` won’t need to be changed in the future:
- https://docs.timescale.com/telemetry
- https://docs.timescale.com/getting-started
- https://docs.timescale.com/api
- https://docs.timescale.com/core-concepts
3) Merge this PR and call it a day 😅
I am happy with any options.
Thanks!
> Fix broken links in notice

- CHANGELOG.md
The 2.3.0 release used the wrong heading level. Fix it for future
releases.
> Use correct heading level in changelog (in release branch 2.3.x)

- src/compat.h
- src/event_trigger.c
- tsl/src/compression/compression.c
- tsl/src/nodes/gapfill/exec.c
Remove TTSOpsVirtualP, TTSOpsHeapTupleP, TTSOpsMinimalTupleP and
TTSOpsBufferHeapTupleP macros since they were only needed on PG11
to allow us to define compatibility macros for TupleTableSlot
operations.
> Remove TTSOps pointer macros

- .github/workflows/linux-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- CMakeLists.txt
- appveyor.yml
- scripts/docker-build.sh
- tsl/test/CMakeLists.txt
CMake now detects if the necessary prerequisites for running TAP
tests are installed on the local system. This includes perl
installation and other dependencies, such as the IPC::Run module and
prove binary.
> Detect TAP test prerequisites with CMake

- src/copy.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/nodes/data_node_dispatch.c
When adding support for PG13 we introduced a macro to  hide the
function signature differences of ExecComputeStoredGenerated
but the callers of this function never got adjusted to use the
macro.
> Use ExecComputeStoredGeneratedCompat macro

- .github/workflows/coverity.yaml
- scripts/docker-run-abi-test.sh
Install the Perl prerequisites when building the image for ABI tests,
including the `prove` binary.
Although the ABI tests currently don't run TAP tests, CMake still
failed the configuration since it expects the prerequisites to be
installed unless it is run with `-DTAP_CHECKS=off`.
> Run ABI tests with TAP support

- sql/CMakeLists.txt
- sql/ddl_experimental.sql
- sql/ddl_internal.sql
- sql/updates/latest-dev.sql
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/expected/continuous_aggs_drop_chunks.out
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/expected/data_node.out
- tsl/test/sql/continuous_aggs_ddl.sql
- tsl/test/sql/continuous_aggs_drop_chunks.sql
- tsl/test/sql/continuous_aggs_errors.sql
- tsl/test/sql/data_node.sql
Move the "block new chunks" functions and the chunk-based continuous
aggregate refresh function to the new experimental schema.
> Move internal API functions to experimental schema

- test/pg_prove.sh
- tsl/test/CMakeLists.txt
Introduce a shell wrapper around perl prove utility to control running
of TAP tests. The following control variable is supported:
PROVE_TESTS: only run TAP tests from this list
e.g make provecheck PROVE_TESTS="t/foo.pl t/bar.pl"
Note that you can also use regular expressions to run multiple taps
tests matching the pattern:
e.g make provecheck PROVE_TESTS="t/\*chunk\*"
If the existing "TESTS=" option is used along with PROVE_TESTS then
the subset represented by PROVE_TESTS will also get run. Otherwise tap
tests will be skipped if "TESTS=" is specified.
e.g make installcheck TESTS=dist_hyper* PROVE_TESTS="t/001_*"
> Make provecheck run specific tap tests

- tsl/src/continuous_aggs/materialize.c
- tsl/src/continuous_aggs/materialize.h
- tsl/src/continuous_aggs/refresh.c
continuous_agg_update_materialization() doesn't use this argument and
we can't rely on a fixed bucket_width in the future anyway.
> Remove unused bucket_width argument

- test/pg_prove.sh
- tsl/test/CMakeLists.txt
Look for PostgresNode.pm in the right path
$(pg_config --libdir)/pgxs/src/test/perl is the right path for
PostgresNode.pm on Linux. On MaxOS and PG 13.x another path seems
to be used: $(pg_config --libdir)/postgresql/pgxs/src/test/perl
> Look for PostgresNode.pm in the right path

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/sql/transparent_decompression_ordered_index.sql.in
We explicilty filter paths for compressed chunks that
have spurious clauses between the compressed chunk and
the original chunk or hypertable. However there are other
cases where a chunk could be a child rel
(i.e. RELOPT_OTHER_MEMBER_REL) such as when the chunk is
referenced as part of a UNION ALL query. We remove
all plans that have spurious clauses between the compressed
chunk and any implied parent for the chunk.
Fixes #2917
> Remove paths that reference parent relids for compressed chunks

- CHANGELOG.md
- src/compat.h
- src/plan_expand_hypertable.c
- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/scan_plan.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/src/nodes/skip_scan/planner.c
Upstream fixed a bug with miscomputation of relids for
PlaceHolderVar. Those fixes changed the signature of pull_varnos,
make_simple_restrictinfo and make_restrictinfo.
The fixes got backported to the PG12 and PG13 branch but to not
break compatibility with extensions the old functions were left in.
This patch makes our code use the new functions when compiling
against a postgres version that has them.
https://github.com/postgres/postgres/commit/1cce024fd2
https://github.com/postgres/postgres/commit/73fc2e5bab
> Fix pull_varnos miscomputation of relids set

- sql/maintenance_utils.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/catalog.c
- src/catalog.h
- src/chunk.c
- src/chunk.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- test/expected/drop_rename_hypertable.out
- test/expected/pg_dump.out
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/chunk_api.c
- tsl/src/chunk_api.h
- tsl/src/init.c
- tsl/src/remote/dist_commands.c
- tsl/src/reorder.c
- tsl/src/reorder.h
- tsl/test/t/003_chunk_copy_move.pl
- tsl/test/t/CMakeLists.txt
The building blocks required for implementing end-to-end copy/move
chunk functionality have now been wrapped in a procedure.
A procedure is required because multiple transactions are needed to
carry out the activity across the access node and the involved two data
nodes.
The following steps are encapsulated in this procedure
1) Create an empty chunk table on the destination data node
2) Copy the data from the src data node chunk to this newly created
destination node chunk. This is done via inbuilt PostgreSQL logical
replication functionality
3) Attach this chunk to the hypertable on the dst data node
4) Remove this chunk from the src data node to complete the move if
requested
A new catalog table "chunk_copy_activity" has been added to track
the progress of the above stages. A unique id …
> End-to-end wrapper API for copy/move chunk

- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/test/expected/continuous_aggs_policy.out
```
Remove two_buckets_to_str() procedure
The two_buckets_to_str() procedure relies on fixed bucket_width
which is not going to be fixed in the future. Since the procedure
is used only to generate a hint that accompanies an error message,
the simplest solution is to remove this procedure. We can improve
error messages later if that would be necessary.
```
> Remove two_buckets_to_str() procedure

- CHANGELOG.md
- sql/updates/post-update.sql
- sql/updates/pre-update.sql
- test/sql/updates/post.catalog.sql
pg_init_privs can have multiple entries per relation if the relation
has per column privileges. An objsubid different from 0 means that
the entry is for a column privilege. Since we do not currently
restore column privileges we have to ignore those rows otherwise
the update script will fail when tables with column privileges are
present.
Fixes #3331
> Fix pg_init_privs objsubid handling

- sql/updates/pre-update.sql
When executing "ALTER EXTENSION timescaledb UPDATE TO ..." it will fail
if parallel workers spawn for the update itself. Add the appropriate
check to fix this.
Fixes #3286 
Fixes #2795
Tested as described in #3286
> Fix failed update with parallel workers

- src/catalog.h
- src/continuous_agg.c
- src/continuous_agg.h
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/refresh.c
```
Don't access bucket_width directly
Refactoring. Since bucket_width will not be fixed in the future this
patch introduces two new procedures:
- ts_continuous_agg_bucket_width(), for determining the exact width
of given bucket;
- ts_continuous_agg_max_bucket_width(), for estimating the maximum
bucket width for given continuous aggregate;
This will allow determining the bucket width on the fly, which is
not possible when ContinuousAgg* -> data.bucket_width is accessed
directly. All accesses to data.bucket_width were changed accordingly.
```
> Don't access bucket_width directly

- sql/CMakeLists.txt
- sql/time_bucket_ng.sql
- src/CMakeLists.txt
- src/time_bucket_ng.c
- src/time_bucket_ng.h
- test/expected/timestamp.out
- test/sql/timestamp.sql
```
Introduce experimental time_bucket_ng() function
This patch adds time_bucket_ng() function to the experimental
schema. The "ng" part stands for "next generation". Unlike
current time_bucket() implementation the _ng version will support
months, years and timezones.
Current implementation doesn't claim to be complete. For instance,
it doesn't support timezones yet. The reasons to commit it in it's
current state are 1) to shorten the feedback loop 2) to start
experimenting with monthly buckets are soon as possible,
3) to reduce the unnecessary work of rebasing and resolving
conflicts 4) to make the work easier to the reviewers
```
See also https://github.com/timescale/timescaledb/pull/3211#issuecomment-864057030
> Introduce experimental time_bucket_ng() function

- src/func_cache.c
```
Refactor initialize_func_info()
Replace unnecessary chain of ts_extension_schema_oid() ->
ts_extension_schema_name() -> get_namespace_oid() calls with
a single OID lookup.
```
> Refactor initialize_func_info()

- .github/workflows/linux-32bit-build-and-test.yaml
Change the postgresql ftp URL from snapshot/ to source/.
> Fix Regression Linux i386 workflow

- src/hypertable_compression.c
Fix heap buffer overflow when renaming compressed hypertable columns.
Fixes #3354
> Fix memory overflow

- test/sql/CMakeLists.txt
- tsl/test/shared/expected/timestamp_limits.out
- tsl/test/shared/expected/with_clause_parser.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/include/shared_setup.sql
- tsl/test/shared/sql/timestamp_limits.sql
- tsl/test/shared/sql/with_clause_parser.sql
Move the timestamp_limits and with_clause_parser test to
regresscheck-shared since those tests don't need a private
database incurring less overhead to run those tests.
> Move timestamp_limits and with_clause_parser test

- CHANGELOG.md
- src/compat.h
- src/nodes/chunk_insert_state.c
- tsl/src/nodes/skip_scan/planner.c
- tsl/test/expected/plan_skip_scan-12.out
- tsl/test/expected/plan_skip_scan-13.out
- tsl/test/expected/skip_scan.out
- tsl/test/shared/expected/timestamp_limits.out
- tsl/test/shared/sql/timestamp_limits.sql
- tsl/test/sql/include/skip_scan_query.sql
The SkipScan code assumed the first entry in PathKeys would match the distinct column. This is not always true as postgres will remove entries from PathKeys it considers constant leading to SkipScan operating on the wrong column under those circumstances. This did most likely not cause any wrong results as the other constraints for SkipScan to apply still had to be satisfied but resulted in very inefficient query execution for those affected
queries.
This patch refactors the SkipScan code to use the distinctClause from the Query instead.
Fixes #3330
> Fix SkipScan distinct column identification

- .github/workflows/postgres_dev.yaml
- CMakeLists.txt
- src/compat.h
- src/process_utility.c
- test/src/test_utils.h
> Add workflow to test PG14

- scripts/docker-run-abi-test.sh
Add the files that had been missing from the docker environment since
the introduction of the downgrade scripts.
> Fix ABI breakage test in CI

- sql/time_bucket_ng.sql
```
time_bucket_ng() may be IMMUTABLE depending on arguments
This function is IMMUTABLE when it doesn't accept timestamptz arguments,
and STABLE otherwise. See the comments in sql/time_bucket_ng.sql for
more details.
```
> time_bucket_ng() may be IMMUTABLE depending on arguments

- tsl/src/chunk_copy.c
We used to run transactions in autocommit mode on DN while running the
chunk copy/move activity. This meant that any failures on the access
node were de-coupled from the activity on the DN. This can make future
cleanup messy since we wouldn't know what's failed/succeeded on the
data nodes.
We now drive the entire activity via transactions started on the access
node.
> Make move_chunk use AN txns on DN

- .github/workflows/postgres_dev.yaml
- sql/size_utils.sql
- tsl/src/chunk_api.c
- tsl/src/fdw/relinfo.c
- tsl/test/expected/chunk_api.out
- tsl/test/expected/compression.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/sql/chunk_api.sql
- tsl/test/sql/compression.sql
- tsl/test/sql/dist_hypertable.sql.in
PG14 changes the initial value of pg_class.reltuples to -1 to allow
differentiating between an empty relation and a relation where
ANALYZE has not yet run.
https://github.com/postgres/postgres/commit/3d351d916b
> Adjust code to PG14 reltuples changes

- src/chunk_constraint.c
- src/plan_expand_hypertable.c
- src/tablespace.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
In contrast to `realloc`, the PostgreSQL function `repalloc` does not
accept a NULL pointer to fall back on `palloc`. For that reason it is
necessary to check if the pointer is NULL and either use `palloc` or
`repalloc`.
> Fix bad use of repalloc

- cmake/ScriptFiles.cmake
- sql/updates/reverse-dev.sql
- sql/views_experimental.sql
- test/expected/pg_dump.out
- tsl/test/expected/dist_views.out
- tsl/test/sql/dist_views.sql
A new view in the experimental schema shows information related to
chunk replication. The view can be used to learn the replication
status of a chunk while also providing a way to easily find nodes to
move or copy chunks between in order to ensure a fully replicated
multi-node cluster.
Tests have been added to illustrate the potential usage.
> Add experimental chunk replication view

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.3.0--2.3.1.sql
- sql/updates/latest-dev.sql
- version.config
```
**Bugfixes**
* #3279 Add some more randomness to chunk assignment
* #3288 Fix failed update with parallel workers
* #3300 Improve trigger handling on distributed hypertables
* #3304 Remove paths that reference parent relids for compressed chunks
* #3305 Fix pull_varnos miscomputation of relids set
* #3310 Generate downgrade script
* #3314 Fix heap buffer overflow in hypertable expansion
* #3317 Fix heap buffer overflow in remote connection cache.
* #3327 Make aggregate in caggs fully qualified
* #3336 Fix pg_init_privs objsubid handling
* #3345 Fix SkipScan distinct column identification
* #3355 Fix heap buffer overflow when renaming compressed hypertable columns.
* #3367 Improve DecompressChunk qual pushdown
* #3377 Fix bad use of repalloc
**Thanks**
* @db-adrian for reporting an …
```
> Release 2.3.1

- CMakeLists.txt
The regex expected a trailing version like `-rc1` or `-dev` but only
the non-dash part was optional. This correct the regex to ensure that
the entire trailing part is optional.
> Fix regex that matches version

- src/chunk.c
- tsl/src/chunk_api.c
- tsl/test/expected/chunk_api.out
- tsl/test/sql/chunk_api.sql
Chunk constraints are now added after a chunk has been copied from one
data node to another. The constraints are added when the chunk is made
visible on the destination node, i.e., after data has been copied and
the chunk's metadata is created.
As an alternative, the constraints could be added when the chunk table
is first created, but before the metadata for the chunk is added. This
would have the benefit of validating each copied (inserted) row
against the constraints during the data copy phase. However, this
would also necessitate decoupling the step of creating the constraint
metadata from the creation of the actual constraints since the other
chunk metadata that is referenced does not yet exist. Such decoupling
would require validating that the metadata actually matches the …
> Add constraints when copying chunks across data nodes

- sql/updates/reverse-dev.sql
The internal function `copy_chunk_data` was removed as part of
refactoring and is no longer necessary to remove in the downgrade
script since the function was never part of a release.
> Remove copy_chunk_data from downgrade script

- tsl/test/shared/expected/dist_chunk.out
- tsl/test/shared/sql/dist_chunk.sql
- tsl/test/shared/sql/include/shared_setup.sql
A test that drops the primary chunk replica was hard coded to drop the
chunk on a specific data node, which wasn't the primary. Thus the
chunk's primary node wasn't changed as expected after the 
chunk replica was dropped. This also caused flakiness because the
ordering of foreign servers for the chunk could vary. These issues
have been fixed.
> Fix issues in the dist_chunk test

- sql/ddl_experimental.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/catalog.c
- src/catalog.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/utils.c
- src/utils.h
- test/expected/drop_rename_hypertable.out
- test/expected/pg_dump.out
- tsl/src/chunk_api.c
- tsl/src/chunk_copy.c
- tsl/src/chunk_copy.h
- tsl/src/init.c
- tsl/src/reorder.c
- tsl/src/reorder.h
- tsl/test/t/002_chunk_copy_move.pl
- tsl/test/t/CMakeLists.txt
A chunk copy/move activity is carried out in stages and it can
fail in any of them. We track the last completed stage in the
"chunk_copy_activity" catalog table. In case of failure, a
"chunk_copy_cleanup" function can be invoked to bring the chunk back
to its original state on the source datanode and all transient objects
like replication slot, publication, subscription, empty chunk, metadata
updates, etc are cleaned up.
Includes test case changes for each and every stage induced failure.
> Implement cleanup for chunk copy/move

- .github/workflows/sanitizer-build-and-test.yaml
This test sometimes fails because it generates extra "rehashing
catalog cache" debug messages, which is not very helpful.
> Ignore debug_notice test during sanitizer runs

- CHANGELOG.md
- src/planner.c
- src/planner.h
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-13.out
- test/sql/plan_expand_hypertable.sql.in
In nested function invocations hypertable expansion would not work
correctly and a hypertable would not be expanded by timescaledb
code but by postgres table inheritance leading to fdw_private
not being properly initialized.
Fixes #3391
> Fix segfault for RelOptInfo without fdw_private

- .github/workflows/postgres_dev.yaml
- src/copy.c
- src/planner.c
- src/process_utility.c
- tsl/src/reorder.c
> PG14 changes

- test/CMakeLists.txt
- test/perl/CMakeLists.txt
- test/perl/TimescaleNode.pm
- tsl/test/CMakeLists.txt
We have added additional functionality in timescaledb extension to
use in tap tests. Install these perl files in the PG installation
directory so that external modules (the current "forge_ext" extension
as an example) can use this functionality without having to have an
additional dependency on the timescaledb extension source code. Note
that these perl files should be installed only if PG installation has
the relevant "${PG_PKGLIBDIR}/pgxs/src/test/perl" subdirectory.
Also rejig the configuration directory variable that's used for the
tap tests so that external modules can specify their own locations by
using their own values for it (the current variable was tightly tied to
timescaledb source code location).
> Add perl module files to PG install

- test/sql/updates/setup.continuous_aggs.v2.sql
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
If the names for entries in the targetlist for the direct and partial
views of the continuous aggregate does not match the attribute names in
the tuple descriptor for the result tuple of the user view an error
will be generated. This commit fixes this by setting the targetlist
resource names of the columns in the direct and partial view to the 
corresponding attribute name of the user view relation tuple
descriptor.
Fixes #3051
Fixes #3405
> Fix targetlist for cagg views

- CHANGELOG.md
- src/nodes/chunk_insert_state.c
- tsl/test/isolation/expected/compression_ddl.out
- tsl/test/isolation/specs/compression_ddl.spec
When a insert into a compressed chunk is blocked by a
concurrent recompress_chunk, the latter process could move
the storage for the compressed chunk. Verify validity of
the compressed chunk before proceeding to acquire locks.
Fixes #3400
> Verify compressed chunk validity for insert path

- src/loader/loader.c
The timescaledb extension checking code uses syscache lookups to
determine whether the proxy table exists. Doing syscache lookups
inside the invalidation callback context was corrupting the syscache.
For this reason, we remove this callback.
Fixes #3188
> Remove check from relcache invalidation callback

- tsl/src/remote/txn_resolve.c
- tsl/test/expected/remote_txn_resolve.out
- tsl/test/sql/remote_txn_resolve.sql
Since pg_prepared_xacts is shared between databases, the healing
function tried to resolve prepared transactions created by other
distributed databases.
This change makes the healing function to work only with current
database.
Fix #3433
> Fix remote_txn_heal_data_node() for multiple DB's

- sql/CMakeLists.txt
- sql/updates/2.3.1--2.3.0.sql
- sql/updates/reverse-dev.sql
The cagg rebuild was required for a fix introduced in 2.3.1 but
was not removed from reverse-dev.sql when that version got released.
> Fix downgrade files for 2.3.1

- test/perl/CMakeLists.txt
Don't install the TAP-related perl files when TAP checks has been
disabled. Installing this files unconditionally creates problem
when building packages as these files should not be part of the
package.
> Skip perl file installation without TAP_CHECKS

- src/dimension.c
- test/expected/chunk_utils.out
- test/sql/chunk_utils.sql
In this specific case, when we create a hypertable then
we add a "not-null" constraint to the "time" column if it
does not exist. That is done via an internal ALTER TABLE
subcommand in dimension_add_not_null_on_column function. If the
currentEventTriggerState structure is enabled then it's necessary to
set up the command tracking appropriately, otherwise crash ensues. This
has been fixed via this now.
Fixes #3442
> Fix crash while tracking alter table commands

- .github/workflows/coverity.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- CMakeLists.txt
- appveyor.yml
- scripts/docker-build.sh
- scripts/docker-run-abi-test.sh
- scripts/test_sanitizers.sh
- test/CMakeLists.txt
- tsl/test/CMakeLists.txt
If tools like `pg_regress` or `pg_isolation_regress` are not found, an
error is generated telling you that you need to disable the tests
explicitly using `REGRESS_CHECKS`. This is an inconvenience for the
user since in most cases you just want to build the system with what
you have.
This commit changes that by automatically disabling regression tests,
isolation tests, TAP tests, and formatting targets when tools cannot be
found, which means that users do not normally have to disable tests
explicitly. A notice is still printed that the targets are not added.
In addition, the commit adds an option `REQUIRE_ALL_TESTS` for the rare
case when you want to make sure that all tests are indeed executed (for
example, in CI runs), which by default is off.
> Disable tests by default if tools are not found

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
If the targetlist for the cagg query has both subexprs and exprs
from the having clause, the havingqual for the partial view
is generated incorrectly. Fix this issue by checking havingqual
against all the entries in the targetlist instead of first match.
Fixes #2655
> Fix havingqual processing for caggs

- src/hypertable.c
Older gcc versions will throw a warning about missing braces when
a nested struct is initialized with {0}.
> Fix compiler warning about missing braces

- tsl/src/hypertable.c
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
When data nodes are added but are missing USAGE privileges, a hint will
be shown suggesting to add more data nodes. This is misleading since
data nodes are added. Instead, if there are data nodes but they are not
used, the hint will be to fix the privileges for the data nodes.
Fixes #3479
> Improve error message when adding data nodes

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
```
This release contains bug fixes since the 2.4.0 release. We deem it
high priority to upgrade since it is needed to support PostgreSQL 12.8
and 13.4.
**Bugfixes**
* #3430 Fix havingqual processing for continuous aggregates
* #3468 Disable tests by default if tools are not found
* #3468 Fix crash while tracking alter table commands
* #3494 Improve error message when adding data nodes
* #3498 Fix continuous agg bgw job failure for PG 12.8 and 13.4
**Thanks**
* @brianbenns for reporting a segfault with continuous aggregates
```
> Release 2.4.1

- tsl/src/chunk_copy.c
- tsl/src/reorder.c
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
The procedures `copy_chunk` and `move_chunk` internally manipulate the
transaction state using plumbing-level commands such as
`StartTransactionCommand` and `CommitTransactionCommand`. Since these
affect the internal state of the SPI execution context, it generates
warnings when used inside a PL/SQL procedures.
This commit fixes this by switching to using SPI-level commands and
connecting and finishing the SPI properly.
Fixes #3495
> Use SPI transaction manipulation functions

- test/CMakeLists.txt
When running bootstrap with regression checks disabled but tap
tests enabled, bootstrap would fail when trying to add dependencies to
the installcheck target which was not defined when regression checks
are off.
Fixes #3518
> Fix bootstrap with regresschecks disabled

- .github/workflows/linux-build-and-test.yaml
- scripts/gh_matrix_builder.py
Run CI against PG snapshots to discover potential issues with
upcoming PG releases earlier.
> Run CI against PG snapshots

- sql/time_bucket_ng.sql
- sql/updates/reverse-dev.sql
- src/time_bucket.c
- src/time_bucket.h
- test/expected/timestamp.out
- test/sql/timestamp.sql
This patch adds support of timezones in time_bucket_ng(). The 'origin'
argument can't be used with timezones yet. This will be implemented in
a separate pull request.
The volatility of time_bucket_ng() is kept as is, although there is
a discussion in the progress of making it IMMUTABLE. This will be
addressed in a separate PR as well.
> Support timezones in time_bucket_ng()

- sql/time_bucket_ng.sql
- sql/updates/reverse-dev.sql
- src/time_bucket.c
- src/time_bucket.h
- test/expected/timestamp.out
- test/sql/timestamp.sql
This patch adds a version of time_bucket_ng() with 'origin' argument.
It doesn't address any other known issues. E.g. volatility of the function will be changed
in another patch. The error messages are going to be improved when the feature gets
a little more stable.
> time_bucket_ng() version with `origin` argument

- sql/time_bucket_ng.sql
This patch marks time_bucket_ng() as IMMUTABLE. Two exceptions are:
- time_bucket_ng(interval, timestamptz) timestamptz
- time_bucket_ng(interval, timestamptz, timestamptz) timestamptz
... due to their implementation, see the comments. These two overloaded
versions were introduced only for backward compatibility with time_bucket()
and are not needed for building continuous aggregates.
> Mark time_bucket_ng() as IMMUTABLE

- src/loader/bgw_launcher.c
Reporting errors using `ereport` can call `malloc()`, which is not
signal-safe. Using `ereport()` in a signal handler can therefore cause
`malloc()` to run nested inside `malloc()` if the termination handler
is called in the middle of a `malloc()` call, which will trigger an
assertion in `malloc()` that will take down the server.
This commit fixes this by using the signal-safe `write_stderr()` inside
the signal handlers for the background workers.
Fixes #3469
> Use signal-safe functions in signal handler

- src/catalog.c
- src/utils.c
PG14 adds an include_out_arguments parameter to FuncnameGetCandidates.
https://github.com/postgres/postgres/commit/e56bce5d
> Adjust FuncnameGetCandidates calls to PG14 changes

- tsl/src/compression/compression.c
PG14 changes the reindex_relation `params` argument from integer
to a struct.
https://github.com/postgres/postgres/commit/a3dc9260
> Adjust code to PG14 reindex_relation changes

- src/chunk.c
- src/chunk.h
- src/dimension_slice.c
- src/dimension_slice.h
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/compression_api.h
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/job.h
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_bgw.sql
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/recompress_basic.sql
To reviewers:
The PR has multiple commits to help with reviewing the changes. I'll combine them into a single commit before merging.
Commit 1: change  logic for picking chunks to process
Commit 2: add a new parameter to limit the number of chunks that are chosen by the compression job
Commit 3: Test file changes ( needed as the new algorithm processes all pending chunks and the old way processes exactly ONE chunk).
> Modify compression bgw chunk selection logic

- src/import/planner.c
find_ec_member_matching_expr is not available in PG13.2 so this patch
adjusts the macro that enables the function for our code.
https://github.com/postgres/postgres/commit/7bfba4f1
> Fix find_ec_member_matching_expr backport for 13.2

- sql/size_utils.sql
- test/expected/size_utils.out
- test/sql/size_utils.sql
Rewrite approximate_row_count to SQL instead of PLpgSQL and remove
superfluous JOINs against pg_namespace. Adjust tuple calculation
for PG14 since in PG14 reltuples for partitioned tables is the sum
of it's children so we need to exclude those from calculation to
not doublecount.
> Optimize approximate_row_count

- src/cache.c
- src/init.c
- tsl/src/init.c
- tsl/src/remote/connection_cache.c
A number of cleanup functions for various data structures (e.g.,
caches) are designed to be called when the extension library is
unloaded (via `_PG_fini`). But unloading is disabled in PostgreSQL and
the library is also not unloaded when the backend exits. Therefore,
cleanup functions are never called in practice.
In most cases this is not a problem since memory is released in any
case. However, in the case of the connection cache, connections need
to be closed before memory is released or otherwise the DNs will emit
"Connection reset by peer" log entries when the AN backend exits.
Add proper cleanup of caches and other data structures by adding a
callback via `on_proc_exit`, which gets called when the backend exits.
The closing of AN to DN backend connections are also logged on
the AN if …
> Call cleanup functions on backend exit

- tsl/src/bgw_policy/job.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
If the registered procedure has COMMIT inside the code, the execution
of the job by the background worker was failing.
Fixed it checking if there are a PortalContext defined, if no then
create a Portal from scratch and execute the code using PortalRun, and
if there are a PortalContext then use the existing job execution code.
> Fix failure on job execution by background worker

- scripts/test_downgrade_from_tag.sh
- sql/updates/latest-dev.sql
- sql/updates/post-update.sql
- src/catalog.h
- src/cross_module_fn.h
- src/process_utility.c
- test/sql/updates/post.catalog.sql
- test/sql/updates/post.integrity_test.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
- test/sql/updates/setup.post-downgrade.sql
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/create.h
- tsl/src/continuous_aggs/options.c
- tsl/src/process_utility.c
- tsl/src/process_utility.h
- tsl/test/expected/continuous_aggs_ddl.out
- tsl/test/sql/continuous_aggs_ddl.sql
When renaming a column on a continuous aggregate, only the user view
column was renamed. This commit changes this by applying the rename on
the materialized table, the user view, the direct view, and the partial
view, as well as the column name in the dimension table.
Since this also changes some of the table definitions, we need to
perform the same rename in the update scripts as well, which is done by
comparing the direct view and the user view to decide what columns that
require a rename and then executing that rename on the direct view,
partial view, and materialization table, as well as updating the column
name in the dimension table.
When renaming columns in tables with indexes, the column in the table
is renamed but not the column in the index, which keeps the same name.
When …
> Rename on all continuous aggregate objects

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/sql/continuous_aggs_errors.sql
Users often have trouble creating continuous aggregates because many
error messages are the same and quite terse offering no guidance
for the user in how to fix. This makes some of them less terse.
> Make continuous aggregate error messages more descriptive

- src/cache_invalidate.c
- tsl/src/remote/connection_cache.c
- tsl/src/remote/connection_cache.h
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/remote_connection_cache.out
- tsl/test/sql/remote_connection_cache.sql
- tsl/test/t/003_connections.pl
- tsl/test/t/CMakeLists.txt
The access node maintains a cache of connections to its data
nodes. Each entry in the cache is a connection for a user and remote
data node pair. Currently, a cache entry is invalidated when a foreign
server object representing a data node is changed (e.g., the port
could have been updated). The connection will remain in the cache for
the duration of the current command, but will be remade with the
updated parameters the next time it is fetched from the cache.
This change invalidates a connection cache entry if the connection's
role/user changes and drops an entry if the role is dropped. One
reason for invalidating a connection is that a role rename invalidates
the certificate the connection is using in case client certificate
authentication is used. Thus, connections that have been …
> Update connection cache on role changes

- src/nodes/chunk_insert_state.c
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
If insertion is attempted into a chunk that is compressed, the error
message is very brief. This commit adds a hint that the chunk should be
decompressed before inserting into it and also list the triggers on the
chunk so that it is easy to debug.
> Show details on compressed chunk error

- src/chunk.c
- src/chunk.h
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
When a chunk is not found, we print a generic error message that does
not hint at what we are looking for, which means that it is very hard
to locate the problem.
This commit adds details to the error message printing out values used
for the scan key when searching for the chunk.
Related-To: #2344
Related-To: #3400
Related-To: #153
> Improve error message when chunk not found

- cmake/ScriptFiles.cmake
- sql/cagg_utils.sql
- src/chunk.c
- src/continuous_agg.c
- src/continuous_agg.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
- tsl/src/init.c
For the `refresh_continuous_aggregate()` operation:
Support Continuous Aggregates over distributed hypertables by moving
1. hypertable log invalidation processing
2. materialization log invalidation processing
3. refresh window tuplestore processing
to the Data-Nodes.
This processing remains local for normal hypertables.
Refresh window tuplestore entries are not transferred over the network in the distributed case. In this case, refresh window merging is forced to limit the amount of network traffic per refresh operation.
> Update refresh procedure to read invalidation logs from data nodes for distributed hypertables

- .github/workflows/linux-build-and-test.yaml
- src/chunk.c
- test/expected/drop_owned.out
- test/sql/drop_owned.sql
When a new chunk is created, the ACL is copied from the hypertable, but
the shared dependencies are not set at all. Since there is no shared
dependency, a `DROP OWNED BY` will not find the chunk and revoke the
privileges for the user from the chunk. When the user is later dropped,
the ACL for the chunk will contain a non-existent user.
This commit fixes this by adding shared dependencies of the hypertable
to the chunk when the chunk is created.
Fixes #3614
> Add shared dependencies when creating chunk

- .github/workflows/linux-build-and-test.yaml
MacOS 10.15 image version 20210927.1 does not have OpenSSL installed
so we have to explicitly install OpenSSL in the workflow for
PostgreSQL to build.
> Install OpenSSL in MacOS workflow

- test/expected/drop_owned.out
- test/sql/drop_owned.sql
Using now() in regression tests will result in flaky tests as this
can result in creating different number of chunks depending on
alignment of now() relative to chunk boundaries.
> Fix flaky drop_owned test

- appveyor.yml
Since there is an issue with the current appveyor image we switch
appveyor to the preview image which runs CI fine.
> Switch appveyor to preview image

- tsl/src/deparse.c
- tsl/test/t/001_simple_multinode.pl
"create_distributed_hypertable" fails on the datanodes if the columns
involved in the underlying non-default schema-qualified PG table are
using user defined types (UDTs) from another non-standard schema.
This happens because we explicitly set the namespace during the table
creation on the datanode which doesn't allow us to lookup other
schemas. We now unconditionally schema-qualify the UDT while sending
the SQL from access node to the datanode to avoid this.
Includes test case changes.
Issue reported by and general fix provided by @phemmer
Fixes #3543
> Schema qualify UDTs in multi-node

- src/guc.c
- tsl/test/expected/dist_util.out
- tsl/test/sql/dist_util.sql
`timescaledb.ssl_dir/passfile` GUC's is currently only visible for superusers. This makes it impossible for non superusers to read GUC value which might be useful in some cases (eg. troubleshooting or building multinode automation).
Since this GUC's does not contain any sensitive information it makes sense to make it public.
Fixes #3608
> Make ssl_dir/passfile gucs accessible for read

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/dist_ddl.sql
Unlock and support ALTER TABLE ALTER TYPE on distributed
hypertable.
Fix #3582
> Allow alter column type on distributed hypertable

- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
When calling the `refresh_continous_aggregate` from a user defined
action (jobs) causes segmentation fault.
Fixed it by adding the `SPI_connect_ext/SPI finish` during the
execution because there are underlying SPI calls that lead us to a
nonexistent `_SPI_current` global variable.
> Fix execution of refresh_caggs from user actions

- .github/workflows/linux-build-and-test.yaml
The telemetry without openssl test did not use the correct args
supplied in the build matrix leading to a failure on PG14 as
building against PG14 currently requires -DEXPERIMENTAL=ON
> Fix CI telemetry test to use correct build args

- CHANGELOG.md
- src/process_utility.c
- test/expected/truncate.out
- test/sql/truncate.sql
- tsl/test/expected/chunk_api.out
- tsl/test/sql/chunk_api.sql
Inside the `process_truncate` function is created a new relations list
removing the distributed hypertables and this new list is assigned to
the current statement relation list. This new list is allocated into
the `PortalContext` that is destroyed at the end of the statement
execution.
The problem arise on the subsequent `TRUNCATE` call because the
compiled plpgsql code is cached into another memory context and the
elements of the relations inside this cache is pointing to an invalid
memory area because the `PortalContext` is destroyed.
Fixed it by allocating the new relations list to the same memory
context of the original list.
Fixes #3580, fixes #3622, fixes #3182
> Fix memory context bug executing TRUNCATE.

- src/nodes/chunk_dispatch_state.c
- src/nodes/chunk_dispatch_state.h
- src/nodes/hypertable_insert.c
- src/nodes/hypertable_insert.h
- src/planner.c
Change ts_hypertable_insert_path_create and add hypertable as
argument since we always check for that in caller allowing us
to remove an error branch from the function, save an additional
lookup for the hypertable and save a lookup for the range table
entry.
> Refactor ts_hypertable_insert_path_create

- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/remote/dist_commands.c
- tsl/src/remote/dist_commands.h
Fix coverity issue for Out-of-bounds access (ARRAY_VS_SINGLETON):
"Passing &sql to function
ts_dist_multi_cmds_params_invoke_on_data_nodes which uses it as an
array"
> Refactor function in dist_commands.c

- CHANGELOG.md
- src/histogram.c
- test/expected/histogram_test.out
- test/sql/histogram_test.sql
Since the number of buckets of the histogram function is an argument
to the function call it is possible to initialize the histogram
state with a lower number than actually needed in further calls
leading to a segfault. This patch changes the memory access to use
the number the state was initialized with instead of the number
passed to the call. This also changes the function to error when
the passed number differs from the initialized state.
Fixes: https://github.com/timescale/timescaledb-private/issues/935
> Fix segfault in ts_hist_sfunc

- .gitignore
- src/chunk.c
- src/chunk_constraint.c
- src/chunk_data_node.c
- src/chunk_index.c
- src/extension.c
- src/extension_utils.c
- src/hypertable.c
- src/hypertable_data_node.c
- src/loader/loader.c
- src/metadata.c
- src/metadata.h
- src/tablespace.c
- src/telemetry/telemetry_metadata.c
- tsl/src/chunk_copy.c
- tsl/src/dist_util.c
- tsl/src/remote/txn.c
A lot of our scankey initialization when scanning indexes for
a name had a superfluous namein call.  This patch remove those
unnecessary calls.
> Remove namein calls from scankey initialization

- src/continuous_agg.c
- src/continuous_agg.h
Remove two procedures declared in continuous_agg.c:
- ts_create_arrayexprs_from_caggs_info
- ts_continuous_agg_get_user_view_oid
This code is not used for anything, nor is documented or test-covered.
> Remove dead code

- test/pg_hba.conf.in
- tsl/src/dist_backup.c
- tsl/src/remote/dist_txn.c
- tsl/src/remote/txn.c
- tsl/test/t/004_multinode_rdwr_1pc.pl
- tsl/test/t/CMakeLists.txt
In high availability setups, a streaming replica of the access node can 
be configured. Since it's a hot standby users should be able to run 
read-only queries from this replica and should be able to query the 
distributed hypertables from it. 
To allow this, we need to disable the "timescaledb.enable_2pc" GUC on
the standby.
Additionally, the internal code which sets up a connection from the 
standby access node to the data nodes now marks the ongoing transaction
explicitly as READ ONLY ones. This ensures that any functions or any 
activity which tries to make modifications on the data nodes errors
out.
In normal Postgres, the ongoing transaction becomes READ WRITE
immediately on promotion whereas in our case the ongoing transaction
will remain READ ONLY till completion. New transactions …
> Enable 1PC and DN reads for read only AN txns

- src/continuous_agg.c
- src/continuous_agg.h
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation.h
- tsl/src/continuous_aggs/refresh.c
CaggsInfo is an immutable structure and a good candidate to be const'ified.
This simplifies the maintenance of the code and probably could save a CPU
cycle or two here and there.
> const'ify CaggsInfo structure

- CHANGELOG.md
- src/hypertable_compression.c
- src/hypertable_compression.h
- src/process_utility.c
- tsl/src/compression/create.c
- tsl/src/compression/create.h
- tsl/src/process_utility.c
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/compression_errors.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_errors.sql
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/compression_alter.sql
This patch allows dropping columns from hypertables with compression
enabled when the dropped column is neither an orderby nor a
segmentby column.
Fixes #3683
> Allow ALTER TABLE DROP COLUMN on compressed hypertable

- CHANGELOG.md
- sql/policy_internal.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/compression_errors.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_bgw.sql
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/recompress_basic.sql
Commit fffd6c2350f5b3237486f3d49d7167105e72a55b fixes problem
related to PortalContext using PL/pgSQL procedure to execute the policy.
Unfortunately this new implementation introduced a problem when we use
INTEGER and not BIGINT for the time dimension.
Fixed it by dealing correclty with the integer types: SMALLINT, INTEGER
and BIGINT.
Also refatored the policy compression procedure replacing the two
procedures `policy_compression_{interval|integer}` by a simple
`policy_compression_execute` casting dimension type dynamically.
Fixes #3773
> Fix compression policy on tables using INTEGER

- test/expected/pg_dump.out
- test/expected/test_utils.out
- test/sql/CMakeLists.txt
- test/sql/pg_dump.sql
- test/src/test_utils.c
Calling `CREATE DATABASE` we cannot have any backends connected to the
source database, except the current one. Since background workers
connect to any database that has installed the extension, they can
linger and cause a flaky error.
The test changed to just check that the extension can be implicitly
installed, but this require waiting for backends to be unregistered
from `procArray` in `procarray.c`, which the function
`pg_terminate_backend` does not handle properly and hence results in a
flaky test. This happen because `pg_terminate_backend` only signals the
process to terminate, but does not wait for it to actually terminate.
Instead, we add an explicit function that checks the `procArray` and
waits for it to not have any backends for a database and uses that to
wait for termination.
> Fix flaky pg_dump

- test/src/test_utils.c
Supress the following CLang warning:
```
warning: 2nd function call argument is an uninitialized value
[clang-analyzer-core.CallAndMessage]
```
> Fix possible uninitialized value in test_utils.c

- CHANGELOG.md
- src/plan_expand_hypertable.c
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-13.out
- test/expected/plan_expand_hypertable-14.out
- test/sql/include/plan_expand_hypertable_query.sql
The time_bucket transformation code assumed the value and the width
of the time_bucket comparison expression were both Const. But this
was not validated only asserted. This can lead to wrong query results.
Found by sqlsmith.
> Fix time_bucket comparison transformation

- tsl/src/compression/dictionary.c
- tsl/src/compression/simple8b_rle.h
CLang 11 generates several warnings regarding possible null pointer
dereferences and division by zero. The warnings seem to be false-positive.
However, they may hide new valuable warnings. Thus this patch double-checks
that there is nothing to be concerned about and also silences these warnings.
> Silence 3 clang warnings for simple8b_rle.h/dictionary.c

- .github/workflows/shellcheck.yaml
- bootstrap
- scripts/check_file_license.sh
- scripts/check_license.sh
- scripts/check_unreferenced_files.sh
- scripts/clang_format_all.sh
- scripts/clang_format_wrapper.sh
- scripts/cmake_format_all.sh
- scripts/docker-build.sh
- scripts/docker-run-abi-test.sh
- scripts/docker-run-restore-points-test.sh
- scripts/docker-run-tests.sh
- scripts/export_prefix_check.sh.in
- scripts/run_sql.sh
- scripts/shellcheck-ci.sh
- scripts/test_restore_points.sh
- scripts/test_sanitizers.sh
- scripts/test_update_from_tag.sh
- scripts/test_updates.sh
- scripts/test_updates_pg12.sh
- scripts/test_updates_pg13.sh
- scripts/test_updates_pg14.sh
- scripts/ts_dump.sh
- scripts/ts_restore.sh
- test/pg_prove.sh
- test/pg_regress.sh
- test/runner.sh
- test/runner_shared.sh
In my experience, writing a shell script correctly is hard even for a skilled programmer.  [shellcheck](https://github.com/koalaman/shellcheck) is a static analysis tool that helps catch common errors in shell scripts. I found it to be very useful when working with shell scripts.
We now have 36 executable scripts in our repository, for which shellcheck reports 126 errors (calculated like `find . -type f -executable -exec bash -c '[ "$(file --brief --mime-type "$1")" == "text/x-shellscript" ]' sh {} \; -exec shellcheck -f gcc --exclude=SC2086 {} \; | cut -d: -f1 | sort | uniq | wc -l`) I think it might make sense to run shellcheck on changed scripts in pull requests. This PR adds a GitHub actions workflow that does this.
This check only runs on the changed files, so this PR doesn't fix all …
> add shellcheck to CI

- src/chunk.c
When a data node tries to create a chunk itself, and not via the
access node, an error is raised. The hint in this error was not
conforming to the error style guide, so fix it.
> Tweak chunk creation error message

- CHANGELOG.md
- sql/size_utils.sql
- tsl/test/t/001_simple_multinode.pl
Size utility functions, such as `hypertable_size()`, excluded
non-responding data nodes from size calculations, which led to the
functions succeeding but returning the wrong size information. To
avoid reporting confusing numbers, it is better to fail.
This change updates the SQL queries for the relevant functions to no
longer exclude non-responding data nodes and also adds a TAP test to
illustrate the error when data nodes are not responding.
Fixes #3713
> Fail size utility functions when data nodes do not respond

- scripts/docker-build.sh
The header file `gssapi/gssapi.h` is present in Alpine package
`krb5-dev` but for some reason it was not installed prior to building,
causing upgrade and downgrade test failures.
> Add krb5-dev dependency to alpine build

- tsl/test/isolation/expected/continuous_aggs_multi_dist_ht.out
- tsl/test/isolation/specs/continuous_aggs_multi_dist_ht.spec
During the developing of Continuous Aggregates for Distributed
Hypertables we left some work to be done later and refator the
isolation tests to prevent SQL injection was on of them.
Per discussion:
https://github.com/timescale/timescaledb/pull/3693#discussion_r735098888
Epic issue #3721
> Refactor isolation tests to prevent SQL injection

- src/compat/compat.h
- src/continuous_agg.c
- src/event_trigger.c
- tsl/test/src/remote/remote_exec.c
Postgres 13 introduced macros for typalign and typstorage constants in
commit postgres/postgres@3ed2005ff59.
For better code readability let's port `TYPALIGN_CHAR` macro for the
compatibility layer.
Closes #3817
> Backport PG13 typalign macros for PG12

- src/loader/loader.c
- tsl/test/expected/data_node_bootstrap.out
- tsl/test/sql/data_node_bootstrap.sql
For all security labels from provider `timescaledb` an error was
printed, which make `pg_restore` fail because the security labels are
printed to the dump.
Instead, we only print an error if the security label is not of the
correct format.
Fixes #3760
> Fix error printout on correct security label

- src/continuous_agg.c
- src/continuous_agg.h
- tsl/src/continuous_aggs/invalidation.c
Currently, the int64 elements are always passed by reference, which is
not necessary on 64-bit architectures where it can be passed by value.
Make it so they are only passed by reference for 32-bit architectures
and by value for 64-bit architectures, since the element fits in a
64-bit architecture pointer.
Fixes #3816
> Remove pointers from CAGG lists for 64-bit archs

- tsl/src/remote/connection.c
clang-tidy reports that after eed2810d under certain conditions
remote_connection_error_elog() macro can read from the memory that was not
initialized. Make sure this can't happen.
> Fix reading garbage value from TSConnectionError

- tsl/src/planner.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
If the relation being inserted into and the relation in the SELECT are
both distributed hypertables then do not use COPY. This is because we
will need two connections to the same set of datanodes (one to ingest
data into src table using COPY and one to SELECT from dst table) which
is not supported currently in a single transaction. This restriction
will be lifted in the future.
Fixes #3447
> Fix INSERT..SELECT involving dist hypertables

- .github/workflows/homebrew.yaml
- test/pgtest/CMakeLists.txt
Upstream added a new regression test for binary compatibility check.
Since we define our own types the test will fail with timescaledb
installed as the test does not expect to see those additional types.
This patch changes our CI to ignore result of type_sanity test.
Currently those are only in REL_XX_STABLE but with release of next minor
version those will enter normal tests as well.
https://github.com/postgres/postgres/commit/cf3d79aa31f
> Fix snapshot pg regresscheck

- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
Make sure `ALTER TABLE SET (timescaledb.compress)` command properly
propagated to the data nodes when executed within a procedure.
This includes only test a case, actual fix was done in #3663.
Fix #3705
> Test enabling dist compression within a procedure

- tsl/test/sql/.gitignore
Pull request #3779 introduced a new template SQL test file but missed
to add the properly gitgnore entry to ignore generated test files.
> Add missing gitignore entry

- .github/ISSUE_TEMPLATE/flaky-test.yml
Tests are sometimes flaky, so add an issue template to report such
tests. The template ensures the issue is labeled and has the required
information we need to fix the flake.
> Add an issue template for reporting flaky tests

- .github/ISSUE_TEMPLATE/config.yml
Configure the GitHub issue template chooser to include options with
links to the page about support requests, the Slack community, and
documentation changes.
> Add configuration for the GitHub issue template chooser

- src/process_utility.c
- tsl/test/src/data_node.c
Value node struct was removed in the upstream and the code that uses it will
not compile against PG15. Better rewrite the code now than deal with a whole
bunch of changes one year later.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=639a86e3
> Don't use Value type

- sql/policy_internal.sql
- tsl/test/isolation/expected/deadlock_recompress_chunk.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/deadlock_recompress_chunk.spec.in
When executing recompress chunk policy concurrently with queries query, a
deadlock can be generated because the chunk relation and the chunk
index or the uncompressed chunk or the compressed chunk are locked in
different orders. In particular, when recompress chunk policy is
executing, it will first decompress the chunk and as part of that lock
the compressed chunk in `AccessExclusive` mode when dropping it and when
trying to compress the chunk again it will try to lock the uncompressed
chunk in `AccessExclusive` mode as part of truncating it.
To avoid the deadlock, this commit updates the recompress policy to do
the compression and the decompression steps in separate transactions,
which will avoid the deadlock since each phase (decompress and compress 
chunk) locks indexes and …
> Eliminate deadlock in recompress chunk policy

- scripts/gh_matrix_builder.py
This isolation test will fail in early versions of the PG servers, just
like the other isolation tests, so ignoring failures for it.
> Ignore deadlock_recompress_chunk in early version

- tsl/src/nodes/skip_scan/planner.c
When SkipScan paths are added it can result in a crash if the new
SkipScan dominates the PostgreSQL planned unique path. In that case,
the previous unique path is pruned and freed, leading to a potential
memory corruption since a pointer to the original unique path is used
when looping over all subpaths to try to apply SkipScan. Thus, if the
original unique path is pruned, and there are multiple subpaths, a
crash will occur in the next iteration over the subpaths.
The crash is fixed by making a shallow copy of the original unique
path while iterating the subpaths.
> Fix SkipScan crash due to pruned unique path

- tsl/src/dist_backup.c
Sanitizer reports a heap buffer overflow in
`create_distributed_restore_point` because we are not copying the
restore node name. This commit fixes this by copying the string to a
new name buffer.
Commit is by @mfundul
> Fix create_distributed_restore_point memory issue

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.5.0--2.5.1.sql
- sql/updates/latest-dev.sql
- version.config
This release contains bug fixes since the 2.5.0 release.
We deem it medium priority to upgrade.
**Bugfixes**
* #3706 Test enabling dist compression within a procedure
* #3734 Rework distributed DDL processing logic
* #3737 Fix flaky pg_dump
* #3739 Fix compression policy on tables using INTEGER
* #3766 Fix segfault in ts_hist_sfunc
* #3779 Support GRANT/REVOKE on distributed database
* #3789 Fix time_bucket comparison transformation
* #3797 Fix DISTINCT ON queries for distributed hyperatbles
* #3799 Fix error printout on correct security label
* #3801 Fail size utility functions when data nodes do not respond
* #3809 Fix NULL pointer evaluation in fill_result_error()
* #3811 Fix INSERT..SELECT involving dist hypertables
* #3819 Fix reading garbage value from TSConnectionError
* #3824 …
> Release 2.5.1

- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/deadlock_recompress_chunk.spec.in
After the synchronizing lock is released and the transaction is
committed, both sessions are free to execute independently. This means
that the query can actually start running before the recompress step
has completed, which means that the order for completion is
non-deterministic.
We fix this by adding a marker so that the query is not reported as
completed until the recompress has finished execution. Since markers in
isolation tests is a recent thing, we only run the test for PostgreSQL
versions with markers added.
Part-Of: #3846
> Fix race condition in deadlock_recompress_chunk

- tsl/src/deparse.c
- tsl/src/deparse.h
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_grant-12.out
- tsl/test/expected/dist_grant-13.out
- tsl/test/expected/dist_grant-14.out
- tsl/test/sql/dist_grant.sql.in
Statements that alter default privileges are now by default forwarded
to all data nodes. For instance:
```sql
ALTER DEFAULT PRIVILEGES IN SCHEMA myschema GRANT INSERT ON TABLES TO myrole;
```
is applied across the entire cluster of data nodes.
Fixes #3851
> Handle default privileges on distributed databases

- .github/workflows/windows-packages.yaml
Change the windows package test to use an URL with latest instead
of explicit package version since this is what we use in docs.
> Use generic URL in windows package test

- src/bgw/job_stat.c
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
pg_*rand48() functions family was removed in the upstream and the code that
uses it will not compile against PG15. This patch replaces pg_lrand48() with
standard random() function from stdlib.h. Also the patch rewrites the
bgw_db_scheduler test so that the output doesn't contain any pseudo-random
data.
> Use standard random() instead of pg_lrand48()

- src/chunk.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.h
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/policy_utils.c
- tsl/src/bgw_policy/policy_utils.h
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/continuous_aggs_errors.sql
- tsl/test/sql/continuous_aggs_policy.sql
Move code from job.c to policy_utils.c
Add support functions to check compression
policy validity for continuous aggregates.
Add compression policy tests for caggs
> Support compression policy on continuous aggregates

- tsl/src/remote/dist_ddl.c
Commit 6424dd20 added a redundant early exit to dist_ddl_process
which triggered a Coverity dead code warning. This patch refactors
the code slightly to remove the redundant code and get rid of the
coverity warning.
> Remove dead code in dist_ddl_process

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
This change adds support for `ALTER TABLE SET/DROP NULL` commands
to the list of supported commands that can be run with
distributed hypertable.
Fix #3860
> Fix ALTER SET/DROP NULL contstraint on dist hypertable

- src/compat/compat.h
- src/loader/bgw_message_queue.c
There was an additional argument added to shm_mq_send() in the upstream. This
patch adds a corresponding _compat() macro to be able to compile against
future versions of PostgreSQL. Better handle this now than solve a bunch of
problems one year later.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=46846433
> Add shm_mq_send_compat() macro for compatibility with PG15

- src/compat/compat.h
- tsl/src/deparse.c
- tsl/src/fdw/shippable.c
The macro FirstBootstrapObjectId was renamed in the upstream. This patch adds
a corresponding FirstBootstrapObjectIdCompat macro to compat.h and uses it
instead of FirstBootstrapObjectId. This will allow us to compile agains PG15.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=a49d0812
> Use compat.h version of FirstBootstrapObjectId

- src/compat/compat.h
- tsl/src/reorder.c
The number of arguments of make_new_heap() has changed in PG15. In order to be
able to compile against PostgreSQL 15 use a _compat() macro instead of the
direct function call.
Also, it should have been #if PG15_GE, not #if PG15 - fix this too!
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=b0483263
> Add make_new_heap_compat() macro

- tsl/src/continuous_aggs/create.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/remote/dist_ddl.c
This is a follow-up to 8afac602. In this commit we refactored the code that
used Value* type because the type was removed in the upstream. However, we
missed a few places. This patch fixes it.
> Remove the rest of Value* type usage

- tsl/src/data_node.c
- tsl/src/remote/txn.c
- tsl/src/remote/txn.h
- tsl/src/remote/txn_id.c
- tsl/src/remote/txn_resolve.c
- tsl/src/remote/txn_resolve.h
- tsl/test/expected/remote_txn_resolve.out
- tsl/test/sql/remote_txn_resolve.sql
- tsl/test/src/remote/txn_persistent_record.c
- tsl/test/src/remote/txn_resolve.c
* A few tweaks to the remote txn resolution logic
* Add logic to delete a specific record in remote_txn table by GID
* Allow heal logic to move on to other cleanup if one specific GID
fails
* Do not rely on ongoing txns while cleaning up entries from remote_txn
table
Includes test case changes to try out various failure scenarios in the
healing function.
Fixes #3219
> Fix remote txn heal logic

- sql/chunk.sql
- sql/maintenance_utils.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- tsl/src/chunk_api.h
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/dist_compression.out
- tsl/test/isolation/expected/compression_ddl.out
- tsl/test/isolation/expected/deadlock_recompress_chunk.out
- tsl/test/isolation/specs/compression_ddl.spec
- tsl/test/isolation/specs/deadlock_recompress_chunk.spec.in
- tsl/test/sql/dist_compression.sql
- tsl/test/sql/include/compression_alter.sql
- tsl/test/sql/include/compression_utils.sql
- tsl/test/sql/include/recompress_basic.sql
When executing `recompress_chunk` and a query at the same time, a
deadlock can be generated because the chunk relation and the chunk
index and the compressed and uncompressd chunks are locked in different
orders. In particular, when `recompress_chunk` is executing, it will
first decompress the chunk and as part of that lock the uncompressed
chunk index in AccessExclusive mode and when trying to compress the
chunk again it will try to lock the uncompressed chunk in
AccessExclusive as part of truncating it.
Note that `decompress_chunk` and `compress_chunk` lock the relations in
the same order and the issue arises because the procedures are combined
inth a single transaction.
To avoid the deadlock, this commit rewrites the `recompress_chunk` to
be a procedure and adds a commit between the …
> Eliminate deadlock for recompress_chunk

- tsl/src/remote/txn_resolve.c
Address sanitizer reported a crash due to a use-after-free code
block. Fixed that and verified with a subsequent sanitizer local
run.
Fixes #3907
> Fix use-after-free crash in remote heal code

- src/guc.c
- src/guc.h
- src/planner.c
- src/planner.h
- tsl/src/fdw/data_node_scan_exec.c
- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/data_node_scan_plan.h
- tsl/src/fdw/scan_exec.c
- tsl/src/fdw/scan_exec.h
- tsl/src/remote/data_fetcher.c
- tsl/src/remote/data_fetcher.h
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_partial_agg.out
- tsl/test/expected/dist_query.out
- tsl/test/shared/expected/dist_distinct.out
- tsl/test/shared/expected/dist_distinct_pushdown.out
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_fetcher_type.sql
- tsl/test/sql/dist_partial_agg.sql
Fixes https://github.com/timescale/timescaledb/issues/2807
The row-by-row fetcher is more efficient, so we want to use it when we can -- that is, when the have to read only one table from the data node, without interleaving it with anything else. This patch adds an option of choosing the fetcher type automatically. It detects the simplest case of only one distributed table in the entire query, and enables row-by-row fetcher. For other cases, the cursor fetcher is used.
> use row-by-row fetcher for some queries to enable parallel plans on data nodes

- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/compression/compress_utils.c
- tsl/src/init.c
Since we are re-implementing `recompress_chunk` as a PL/SQL function,
there is no need to keep the C language version around any more, so we
remove it from the code.
> Remove C language recompress_chunk 

- tsl/src/fdw/scan_plan.c
UpperRelationKind enum was extended in the upstream and now can be
UPPERREL_PARTIAL_DISTINCT as well. This patch rewrites the switch-case
expression in the fdw_create_upper_paths() procedure accordingly.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=22c4e88e
> Support UPPERREL_PARTIAL_DISTINCT stage in fdw_create_upper_paths()

- src/nodes/chunk_append/planner.c
- src/nodes/constraint_aware_append/constraint_aware_append.c
- src/utils.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/nodes/skip_scan/planner.c
When loading several different versions of shared libraries after a
restart, it might attempt to register the custom scan nodes several
times.  This is fixed by adding a function that checks if the custom
scan method was already registered and skips registering it if it was.
Fixes #3901
> Check custom scan node registration

- src/nodes/chunk_dispatch.c
- src/subspace_store.c
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/sql/compression_insert.sql.in
When trying to insert into the internal compressed hypertable
timescaledb would segfault. This patch blocks direct inserts into
the internal compressed hypertable through our tuple routing.
Internally we don't use this code path for compression as we
create chunks explicitly and insert directly into those chunks
in compress_chunk.
Fixes #3920
> Fix segfault on insert into internal compressed table

- sql/cagg_utils.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/catalog.c
- src/catalog.h
- src/continuous_agg.c
- src/continuous_agg.h
- src/time_utils.c
- src/time_utils.h
- src/utils.c
- src/utils.h
- test/expected/drop_rename_hypertable.out
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
- tsl/test/expected/continuous_aggs_variable_size_buckets.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/continuous_aggs_variable_size_buckets.sql
```
Monthly buckets support in CAGGs
This patch allows using time_bucket_ng("N month", ...) in CAGGs. Users can also
specify years, or months AND years. CAGGs on top of distributed hypertables
are supported as well.
```
The RFC section that clarifies the changes in the catalog schema:
```
While reviewing Monthly buckets support in CAGGs pull request the team agreed
on the following iterative changes in the catalog schema.
When user creates a CAGG with a variable bucket, the corresponding `bucket_width`
value in the `_timescaledb_catalog.continuous_agg` table is -1 (declared as
BUCKET_WIDTH_VARIABLE in continuous_agg.h). This indicates that the bucket width
is variable and the information about the bucketing function is stored in the
`_timescaledb_catalog.continuous_aggs_bucket_function` …
```
> Monthly buckets support in CAGGs

- CHANGELOG.md
- tsl/src/nodes/async_append.c
- tsl/test/shared/expected/dist_queries.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_queries.sql
When a query has a filter that only needs to be evaluated once per
query it will be represented as a Result node with the filter
condition on the Result node and the actual query as child of the
result node. find_data_node_scan_state_child did not consider
Result node as valid node to contain a DataNodeScan node leading
to a `unexpected child node of Append or MergeAppend: 62` for
queries that had one-time filter with a subquery.
Fixes #3658
> Fix DataNodeScan plans with One-Time Filter

- tsl/src/planner.c
- tsl/test/expected/dist_query.out
This imporves performance.
This is a part of https://github.com/timescale/timescaledb/pull/3890
> Don't do unnecessary planning for the relations proven to be empty

- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
When initially adding the package tests for PG14 Debian, Ubuntu and
RPM packages we couldn't test downgrade with the packages because
there was no previous version with PG14 support. Since we now have
released a 2nd version with PG14 support we can enable the downgrade
test for Debian, Ubuntu and RPM packages.
> Enable downgrade test for PG14 packages

- src/extension.c
- src/extension.h
- src/planner.c
- tsl/src/fdw/relinfo.c
Use the one from the static variable. This improves performance by
avoiding excessive catalog lookups.
Part of https://github.com/timescale/timescaledb/pull/3890
> Don't excessively look up the extension oid

- sql/cagg_utils.sql
- src/catalog.h
- src/continuous_agg.c
- src/continuous_agg.h
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
Our code occasionally mentions max_bucket_width. However, in practice, there is
no such thing. For fixed-sized buckets, bucket_width and max_bucket_width are
always the same, while for variable-sized buckets bucket_width is not used at
all (except the fact that it equals -1 to indicate that the bucket size is
variable).
This patch removes any use of max_bucket_width, except for arguments of:
- _timescaledb_internal.invalidation_process_hypertable_log()
- _timescaledb_internal.invalidation_process_cagg_log()
The signatures of these functions were not changed for backward compatibility
between access and data nodes, which can run different versions of TimescaleDB.
> Refactoring: get rid of max_bucket_width

- sql/ddl_api.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- tsl/src/data_node.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/test/expected/data_node_bootstrap.out
- tsl/test/sql/data_node_bootstrap.sql
When deleting a data node, it is often convenient to be able to also
drop the database on the data node so that the node can be added again
using the same database name. However, dropping the database is
optional since it should be possible to delete a data node even if it
is no longer responding.
With the new functionality, a data node's database can be dropped as
follows:
```sql
SELECT delete_data_node('dn1', drop_database=>true);
```
Note that the default behavior is still to not drop the database in
order to be compatible with the old behavior. Enabling the option also
makes the function non-transactional, since dropping a database is not
transactional. Therefore, it is not possible to use this option in a
transaction block.
Closes #3876
> Add option to drop database when deleting data node

- CMakeLists.txt
- src/bgw/scheduler.c
- tsl/src/chunk.c
- tsl/src/chunk_copy.c
Today was another time I used `#if PG14_LT` but forgot to include
compat.h, spent a good deal of time debugging this. This flag will
catch references to undefined macros.
> Add -Wundef to compiler flags

- tsl/src/deparse.c
Instead of `#if PG14` added in 519e5de21 it should have been `#if PG14_GE`.
> Fix compilation against PG15

- CHANGELOG.md
- tsl/src/nodes/gapfill/exec.c
- tsl/test/shared/expected/gapfill-12.out
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/sql/gapfill.sql.in
When getting the next tuple from the subplan gapfill would apply
the projection to it which was incorrect since the subplan already
did the projection and the projection for the gapfill tuple has to
be done when the tuple is handed to the parent node.
Fixes #3834
> Fix projection handling in gapfill

- src/chunk.c
- src/hypertable.c
- src/utils.c
- tsl/src/bgw_policy/policy_utils.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/chunk_utils_compression.out
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/expected/reorder.out
- tsl/test/shared/expected/subtract_integer_from_now.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/subtract_integer_from_now.sql
- tsl/test/sql/chunk_utils_compression.sql
- tsl/test/sql/continuous_aggs_errors.sql
- tsl/test/sql/reorder.sql
This would trigger an assert when called on a hypertable without
integer time dimension. Found by sqlsmith.
> Fix subtract_integer_from_now on 32-bit platforms and improve error handling

- src/process_utility.c
- tsl/test/expected/data_node.out
- tsl/test/sql/data_node.sql
Allow changing the name and configuration of a data node via `ALTER
SERVER` since there is no `alter_data_node` command.
The functions `add_data_node` and `delete_data_node` are wrappers
around `CREATE SERVER` and `DROP SERVER`, respectively. They block the
PostgreSQL commmands since they do additional things, like data node
bootstrapping.
However, there's currently no way to change a data node's
configuration, and no additional functionality is required over
standard `ALTER SERVER`, so we might as well allow it until a
`alter_data_node` is implemented.
Fixes #3915
> Allow changing a data node via alter server

- tsl/src/bgw_policy/compression_api.c
- tsl/test/expected/compression_bgw.out
Postgres snprintf before 89ad14cd787 will segfault on NULL char
pointers. This patch changes add_compression_policy to check for
NULL get_rel_name before reporting the error.
https://github.com/postgres/postgres/commit/89ad14cd787
> Fix segfault in add_compression_policy

- CHANGELOG.md
- src/agg_bookend.c
- test/expected/agg_bookends-12.out
- test/expected/agg_bookends-13.out
- test/expected/agg_bookends-14.out
- test/sql/include/agg_bookends_query.sql
This patch optimizes how first()/last() initialize the compare
function. Previously the compare function would be looked up for
every transition function call but since polymorphic types are
resolved at parse time for a specific aggregate instance the compare
function will not change during its lifetime. Additionally this
patch also fixes a memory leak when using first()/last() on
pointer types.
These changes lead to a roughly 2x speed improvement for first()/
last() and make the memory usage near-constant.
Fixes #3935
> Optimize first/last

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
This PR changes logic and allows DROP SCHEMA command to be executed
on each data node, even if the schema being dropped has no distributed
hypertables in it.
Fix: #3909
> Add support for DROP SCHEMA on multi-node

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
This change adds support for `ALTER SCHEMA RENAME TO` and
`ALTER SCHEMA OWNER TO` commands to distributed database.
Issue: #3909
> Add support for ALTER SCHEMA command on multi-node

- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
When no size statistics is available for a chunk because it haven't
been ANALYZEd, we have to resort to some estimates. A good way to
estimate the size of the chunk is to look at the sizes of the nearby
chunk.  Before this commit, we would look up the ten nearby chunk for
each chunk w/o statistics, which was slow. This commit adds the code
to maintain exponential moving average of the recent chunk sizes in
the parent RelOptInfo as we go through them, avoiding the additional
lookups.
Part of #3890
> Use moving average to estimate chunk size

- test/runner.sh
- tsl/src/data_node.c
Override the default ACL for public schema on PG15
Since PG15, by default, non-superuser accounts are not allowed to create
tables in public schema of databases they don't own. This default can be
changed manually. This patch ensures that the permissions are going to be the
same regardless of the used PostgreSQL version.
Without this patch, none of our tests pass on PG15 because they fail with the
"access denied to schema public" error. This is why runner.sh was modified.
Then, some other tests keep failing because when we call create_distributed_hypertable()
we create a new database on each of the data nodes, also not granting enough
permissions to non-privileged users. This is what the fix of data_node.c
addresses.
This is not necessarily the best approach possible, but it preserves the …
> Override the default ACL for public schema on PG15

- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/test/expected/continuous_aggs_variable_size_buckets.out
- tsl/test/sql/continuous_aggs_variable_size_buckets.sql
This is a follow-up to 95804069, "Monthly buckets support in CAGGs". In that
patch we didn't check the creation of a CAGG on top of an empty hypertable.
It works, but displays "ERROR: origin must be before the given date", which is
a bit misleading.
This happens because 95804069 didn't modify invalidation_threshold_compute()
in the same way as tsl_process_continuous_agg_viewstmt(). As a result,
compute_circumscribed_bucketed_refresh_window_for_months() calls
time_bucket_ng() for ts_time_get_min() argument. It doesn't work because
the minimum time is 4714-11-24 BC which is before any reasonable origin,
and the user sees corresponding error message.
This patch fixes the problem in the same way as 95804069 did and adds
a corresponding test.
> Don't display an error message when creating an empty CAGG

- tsl/src/fdw/scan_exec.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
The crash is occurring in "fdw_scan_explain" function because the
fsstate passed in is NULL and we try to access the "fetcher_type" field
from it in VERBOSE mode.
When we are doing EXPLAIN, we short circuit the init foreign scan calls
and that's why fsstate is not filled up.
Fixes #3960
> Fix crash in EXPLAIN VERBOSE on dist table

- tsl/src/remote/cursor_fetcher.c
- tsl/src/remote/row_by_row_fetcher.c
The macro `remote_result_elog` is used in the cursor and row-by-row
fetchers and clears the result value using the function `PQclear()`
before rethrowing its error. However, this error is later captured to
clear the wrapping result value that holds a reference to the original
result. To avoid this double-clearing, set the response to NULL before
the error is thrown.
> Avoid double PQclear() in data fetchers

- .github/workflows/apt-packages.yaml
Adjust the APT package test to closer match the instructions used
in our documentation. This changes the apt package test to use the postgresql-common package
to install the postgres repository instead of installing it manually.
> Adjust apt package test to match docs

- src/compat/compat.h
- tsl/src/remote/connection.c
The number of arguments of pg_md5_hash() has changed in REL_14_STABLE.
This patch adds a corresponding compat.h version of the procedure.
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=3a0cced8
> Fix the build against REL_14_STABLE

- tsl/src/continuous_aggs/invalidation.c
- tsl/test/expected/continuous_aggs_invalidation.out
- tsl/test/expected/continuous_aggs_invalidation_dist_ht.out
- tsl/test/sql/include/continuous_aggs_invalidation_common.sql
Per Sven's sqlsmith run we got some assertion errors adding
invalidation for hypertables and continuous aggregates.
Fixed id adding the proper validation in the invalidation SQL functions
to check properly the parameters `start_time` and `end_time`.
> Add exception to invalidation SQL functions

- CHANGELOG.md
- src/chunk_index.c
- test/expected/alter.out
- test/sql/alter.sql
- tsl/test/expected/plan_skip_scan-12.out
When adjusting attribute numbers of chunk index, also adjust
varattnosyn which is used at the time of reconstructing index
definition.
> Update syntactic attribute number

- .travis.yml
- scripts/gh_matrix_builder.py
Commit 6a8c2b66 renamed cagg tests in isolationcheck-t to have a
common prefix but did not adjust the CI ignorelists to reflect
that change.
> Adjust CI ignore lists to isolation test renames

- scripts/gh_matrix_builder.py
Upstream changed the explain output for the memoize node to include
an additional `Cache Mode` line. While we could adjust our test
runner to always ignore that line this would prevent us from testing
the cache mode in future tests.
https://github.com/postgres/postgres/commit/6c32c0977783fae217b5eaa1d22d26c96e5b0085
> Ignore memoize test in pg14 snapshot

- src/planner.c
- tsl/test/expected/debug_notice.out
- tsl/test/sql/debug_notice.sql
The current approach to planning queries on distributed hypertables
first plans a "naive" plan for scanning each remote chunk individually
(the chunks are children of an append) and then that plan gets replaced
by a datanode scan plan (each data node is a child in the Append).
While we need to include each chunk in the planning for cost reasons
(we need to know the stats for chunk rels) we need not actually create
paths for scanning chunks. This unnecessary work is now avoided and we
now plan datanode scans directly.
Fixes #3685
> Avoid distributed chunks scan plans

- src/continuous_agg.c
- src/utils.c
- src/utils.h
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs_variable_size_buckets.out
- tsl/test/sql/continuous_aggs_variable_size_buckets.sql
This is in fact a backport from the "Buckets with timezones" feature branch.
While working on the feature a bug was discovered. We allow creating buckets
like '1 month 15 days', i.e. fixed-sized + variable-sized, which is supposed to
be forbidden.
This patch fixes the bug and also simplifies the code a little. timezone_in /
timezone_out procedures are used instead of snprintf/scanf. Also, the
CAggTimebucketInfo structure was changed slightly. These changes are going to be
needed for timezones support anyway.
> Don't allow using buckets like '1 month 15 days' + some refactorings

- test/pg_regress.sh
- test/runner.sh
This patch adds suport for wildcards to the SKIPS environment
variable similar to wildcard support in TESTS.
This enables the following test invocations:
```
-- run all tsl tests expect background worker and multinode
make regresscheck-t SKIPS="*bgw* *dist*"
-- run cagg tests except background worker
make regresscheck-t TESTS="continuous_agg*" SKIPS="*bgw*"
```
> Add support for wildcards to SKIPS

- src/copy.c
- src/nodes/chunk_dispatch_state.c
- src/nodes/chunk_insert_state.c
- src/nodes/chunk_insert_state.h
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/sql/compression_insert.sql.in
AFTER ROW triggers are not supported on compressed chunks.
Directly call the continuous aggregate trigger function for copies.
This fix is similar to PR 3764 that handles cagg triggers for
inserts into compressed chunks.
> Support continuous agg trigger on copy into compressed chunks

- CHANGELOG.md
- tsl/src/nodes/gapfill/interpolate.c
- tsl/test/shared/expected/gapfill-12.out
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/sql/gapfill.sql.in
When interpolating float values the result of the calculation
might be unstable for certain values when y0 and y1 are equal.
This patch short circuits the formula and returns y0 immediately
when y0 and y1 are identical.
Fixes #1528
> Eliminate float rounding instabilities in interpolate

- test/pgtest/CMakeLists.txt
PG15 removes the input and output directory from the pg regression
test files and moves those files into sql and output directories.
Currently cmake errors when those directories are not present in
PG_SOURCE_DIR. This patch makes those directories optional so cmake
does not fail when PG_SOURCE_DIR contains the checkout of a version
without these directories.
https://github.com/postgres/postgres/commit/d1029bb5
https://github.com/postgres/postgres/commit/dc9c3b0f
> Make pgtest input/output dir optional

- src/extension.c
When executing the post-update scripts we get an assertion failure and
subsequent segfault because `ts_extension_oid` is still set to
`InvalidOid`. This happen because `ts_extension_oid` is not set up
until after the post-update state has finished, but we need to set it
up already in the extension transitioning state used during post-update
execution.
The reason for not setting up the `ts_extension_oid` is because we
cannot issue queries to the catalog, but this is possible already in
the post-update stage, so we add code to set up `ts_extension_oid`
already in this state.
Fixes #4009
> Update ts_extension_oid in transitioning state

- src/nodes/CMakeLists.txt
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
- src/planner.c
- test/expected/delete-12.out
- test/expected/delete-13.out
- test/expected/delete-14.out
- test/expected/insert-12.out
- test/expected/insert-13.out
- test/expected/insert-14.out
- test/expected/insert_many.out
- test/expected/insert_single.out
- test/expected/rowsecurity-12.out
- test/expected/rowsecurity-13.out
- test/expected/rowsecurity-14.out
- test/sql/delete.sql.in
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_triggers.out
- tsl/test/expected/jit-12.out
- tsl/test/expected/jit-13.out
- tsl/test/expected/jit-14.out
This patch changes DELETE handling for hypertables to have the
postgres ModifyTable node be wrapped in a custom HypertableModify
node. By itself this does not change DELETE handling for hypertables
but instead enables subsequent patches to implement e.g. chunk
exclusion for DELETE or DELETE on compressed chunks.
Since PG 14 codepath for INSERT is different from previous versions
this PR will only change the plan for PG14+.
> Route delete on Hypertables through CustomScan

- tsl/src/fdw/relinfo.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
For the chunks that don't have the ANALYZE stats, we have to estimate
the number of pages and tuples in some other ways. One thing we factor
in this estimation is the expected fill factor of the chunk. There are
two ways we calculate the fill factor: 
1. For time dimensions, by
looking at whether the now() belongs to the chunks [begin, end)
interval and calculating the fill factor accordingly.  
2. For space
dimensions, by looking at whether the chunk is one of the last chunks
in the hypertable.
To check (2), we used to compare the chunk ids. Turns out it didn't
work correctly, because the chunk ids are global for all hypertables,
and looking at them doesn't tell us anything if there are many
hypertables.  The code that did that was also very slow.
This commit just removes this logic and …
> Don't guess historical/current chunk by ids

- src/ts_catalog/chunk_data_node.c
- tsl/src/fdw/data_node_chunk_assignment.c
- tsl/src/fdw/data_node_chunk_assignment.h
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/src/fdw/scan_plan.c
Before assigning chunks to data nodes, we have to look up the same
Chunk structs to estimate the chunk relation size. Cache them in chunk
RelOptInfos to avoid the costly lookup.
Part of #3890
> Use cached Chunks for data node assignment

- tsl/src/remote/connection.c
- tsl/test/t/005_add_data_node.pl
- tsl/test/t/CMakeLists.txt
On disconnect libpq will create a result object without
creating event data, which is usually done for a regular errors.
This fix handles this case and forces the result object to always
have have associated connection meta data.
Fix: #3951
> Fix crash when execute add_data_node

- CHANGELOG.md
- src/process_utility.c
When ALTER TABLE SET (timescaledb.compress) is executed, the
compression table is created as part of this command. But when
run as part of an extension installation the EventTrigger for
ALTER TABLE does not get initialized leading to a segfault.
Fixes #4017
> Fix ALTER TABLE EventTrigger initialization

- CHANGELOG.md
- src/hypertable_cache.h
- src/utils.c
The cache entry for a hypertable is created by calling
ts_hypertable_from_tupleinfo. This sets up the ht->space
structure, which in turn sets up the dimension information.
These structures are allocated in the cache's memory context.
The dimension information is accessed after the cache is
released in ts_subtract_integer_from_now. This PR fixes this
by releasing the cache before returning from the function.
Fixes #4014
> Fix premature cache release call

- tsl/src/bgw_policy/compression_api.c
- tsl/test/expected/cagg_errors.out
- tsl/test/expected/cagg_policy.out
- tsl/test/sql/cagg_errors.sql
- tsl/test/sql/cagg_policy.sql
When a compression policy is added for a continuous
aggregate, verify that compression has been enabled, before
adding a policy.
> Verify compression settings before enabling compression policy

- .github/workflows/coccinelle.yaml
- coccinelle/hypertable_cache.cocci
- coccinelle/hypertable_cache2.cocci
- scripts/coccinelle.sh
This patch adds coccinelle scripts for detecting use-after-free
bugs in relation to ts_cache_release.
This will find code using the following pattern:
Use of the hypertable from cache after releasing the cache
and use of the dimension of the hypertable from a cache
after the cache was released.
This will detect bugs similar to #4024, #3106, #3104
> Add coccinelle scripts for detecting use-after-free

- tsl/src/compression/compress_utils.c
- tsl/test/expected/cagg_errors.out
- tsl/test/expected/compression_errors.out
- tsl/test/sql/cagg_errors.sql
Fix the error message for compress chunks so that it
specifies the cagg name instead of the materialized
hypertable name.
> Improve error message for compress_chunk

- src/CMakeLists.txt
- src/func_cache.c
- src/time_utils.c
- src/time_utils.h
- src/timezones.c
- src/timezones.h
- src/ts_catalog/catalog.h
- src/ts_catalog/continuous_agg.c
- src/ts_catalog/continuous_agg.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/continuous_aggs/refresh.h
- tsl/test/expected/cagg_with_timezone.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_with_timezone.sql
This patch allows using timezones in CAGGs, for instance:
time_bucket_ng(bucket_size, ts, 'Europe/Moscow')
Both months/years and days/hours/minutes can be used in bucket_size.
The bucket size is considered variable-sized in all these cases
because DST affects days/hours/minutes as well.
CAGGs on top of distributed hypertables, compressed hypertables and
compressed distributed hypertables are supported as well.
> Timezones support in CAGGs

- src/chunk.c
- src/chunk.h
- src/planner.c
- src/ts_catalog/chunk_data_node.c
- tsl/src/fdw/modify_plan.c
- tsl/src/fdw/relinfo.c
This function is called often, at least 4 times per chunk, so these add
up. Freeing these chunks allows us to save memory. Ideally, we should
fix the function not to look up the chunk anew each time.
Also make a couple other tweaks that reduce memory usage for planning.
Fixes https://github.com/timescale/timescaledb/issues/2486
For a simple query `explain delete from t where value = 1.1`, where `t` is a distributed hypertable with 106 partitions on two data nodes, the memory usage at query completion is reduced from 6.7 MB baseline to 5.5 MB with this patch.
> Don't leak Chunks in classify_relation

- src/chunk.c
- tsl/test/expected/compression.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression.sql
- tsl/test/sql/dist_compression.sql
Chunks that are dropped but preserve the catalog entries
have an incorrect status when they are marked as dropped.
This happens if the chunk was previously compressed and then
gets dropped - the status in the catalog tuple reflects the
compression status. This should be reset since the data is now
dropped
> Fix status for dropped chunks that have catalog entries

- .github/workflows/update-test.yaml
- scripts/test_downgrade_from_tag.sh
The artifact upload for the downgrade test was using the filenames
of the update test and so would never upload any files.
> Fix downgrade test artifact upload

- .github/workflows/rpm-packages.yaml
Since CentOS 8 went EOL in december last year most of the repository
URLs error out now. This patch switches the test to use Rockylinux
which is a drop in replacement for CentOS.
> Fix centos 8 package test

- src/extension_utils.c
The privilege check in extension_load_without_preload used
is_member_of_role which does not respect the inherit flag of
roles instead of has_privs_for_role.
For additional context:
https://www.postgresql.org/message-id/flat/CAGB%2BVh5RpzZroX-RKLXYWyTidpWX6%3DqcbMoVWERotAWh-_CeUQ%40mail.gmail.com#f08fc3998fad5d919c1660c6a1926158
> Fix privilege check in extension_load_without_preload

- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/test/expected/cagg_monthly.out
- tsl/test/expected/cagg_with_timezone.out
- tsl/test/sql/cagg_monthly.sql
- tsl/test/sql/cagg_with_timezone.sql
Variable-sized buckets don't work with CAGG policies:
```
SELECT add_continuous_aggregate_policy('conditions_summary_policy',
start_offset => INTERVAL '65 days',
end_offset => INTERVAL '1 day',
schedule_interval => INTERVAL '1 hour');
ERROR:  bucket width is not defined for a variable bucket
```
This patch fixes it and adds corresponding tests.
Reported by Miranda Auhl <miranda@timescale.com>
> Bugfix: make add_continuous_aggregate_policy() work with variable-sized buckets

- src/import/allpaths.c
- src/planner.c
- src/planner.h
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/src/fdw/scan_plan.c
- tsl/src/planner.c
It doesn't cause any problems except degrading the performance.
The TsFdwRelInfo is initialized twice for hypertable on access node:
1) when using it for chunk size estimation in `estimate_chunk_size`,
2) when expanding the distributed hypertable in `tsl_set_rel_pathlist`
callback.
The initialization has to happen inside the TSL module, this is why we
can't easily move it up the call graph to, say,
`import/ts_set_append_rel_size`, which is FDW-agnostic. As a fix, just
accept that TimescaleDBPrivate structure can be allocated already, and
don't discard the previous one.
Part of #3890
> Fix double initialization of TsFdwRelInfo

- scripts/export_prefix_check.sh.in
On MacOS Monterey with LLVM 13.0.1 when executing export_prefix_check.sh
we get an error:
/usr/local/opt/llvm/bin/nm: error: : unknown argument '-defined-only',
did you mean '--defined-only'?
This patch adds a better check of which flag does `nm` expect.
> Fix "nm: unknown argument -defined-only" error on MacOS

- CHANGELOG.md
- src/hypertable_restrict_info.c
- test/expected/sql_query.out
- test/sql/sql_query.sql
If the ANY construct contains a singleton NULL then the logic in
"dimension_values_create_from_array" barfs causing a crash. Fix it
appropriately in the caller "hypertable_restrict_info_add_expr"
function.
> Fix riinfo NULL handling in ANY construct

- src/telemetry/stats.c
- src/telemetry/stats.h
- src/telemetry/telemetry.c
- tsl/test/expected/telemetry_stats.out
- tsl/test/sql/telemetry_stats.sql
Add the following telemetry fields for continuous aggregates:
* The number of continuous aggregates created on distributed
hypertables
* The number of continuous aggregates using real-time aggregation
> Add extra telemetry for continuous aggregates

- CHANGELOG.md
- src/plan_expand_hypertable.c
- tsl/src/fdw/data_node_scan_plan.c
Reallocate the partitioning attributes arrays when forcing GROUP BY
aggregates down.
Fixes #4050
> Fix buffer overflow in partition scheme

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.5.1 release.
We deem it high priority to upgrade.
**Bugfixes**
* #3900 Improve custom scan node registration
* #3911 Fix role type deparsing for GRANT command
* #3918 Fix DataNodeScan plans with one-time filter
* #3921 Fix segfault on insert into internal compressed table
* #3938 Fix subtract_integer_from_now on 32-bit platforms and improve error handling
* #3939 Fix projection handling in time_bucket_gapfill
* #3948 Avoid double PGclear() in data fetchers
* #3979 Fix deparsing of index predicates
* #4020 Fix ALTER TABLE EventTrigger initialization
* #4024 Fix premature cache release call
* #4037 Fix status for dropped chunks that have catalog entries
* #4069 Fix riinfo NULL handling in ANY construct
* #4071 Fix extension installation privilege …
> Release 2.5.2

- CMakeLists.txt
For some reason the configure parameter for openssl on windows is
--with-ssl=openssl instead of --with-openssl on PG14. This patch adjusts
the check to detect both versions.
> Fix openssl detection for PG14 on windows

- sql/updates/1.7.5--2.0.0-rc1.sql
- sql/updates/2.0.0-rc3--2.0.0-rc4.sql
- sql/updates/2.2.1--2.3.0.sql
- sql/updates/2.4.1--2.4.2.sql
- sql/updates/post-update.sql
- sql/updates/pre-update.sql
Scripts run under pgextwlist cannot use pg_temp so we replace
pg_temp usage in update scripts with _timescaledb_internal.
> Don't use pg_temp in update scripts

- sql/maintenance_utils.sql
- sql/policy_internal.sql
SET LOCAL is only active until end of transaction so we set search_path
again after COMMIT in functions that do transaction control. While we
could use SET at the start of the function we do not want to bleed out
search_path to caller.
> Set search_path again after COMMIT

- src/telemetry/telemetry.c
- test/expected/telemetry.out
Some telemetry fields were removed by mistake as part of an earlier
refactoring. Add back the missing fields that provide information
about the operating system.
> Add missing OS-information in telemetry

- cmake/GenerateTestSchedule.cmake
On non-debug builds we might end up with an empty list of tests
when generating the schedule. On older cmake versions < 3.14
trying to sort an empty list will produce an error, so
we check for empty list here.
> Fix non-debug build with older cmake

- scripts/check_update_scripts.sh
- sql/updates/README.md
Since we now lock down search_path during update/downgrade there
are some additional requirements for writing sql files.
> Document requirements for statements in sql files

- src/hypertable_restrict_info.c
- src/hypertable_restrict_info.h
- src/plan_expand_hypertable.c
- src/planner.h
- test/sql/include/join_query.sql
- tsl/src/fdw/data_node_chunk_assignment.c
- tsl/src/fdw/relinfo.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
We cache the Chunk structs in RelOptInfo private data. They are later
used to estimate the chunk sizes, check which data nodes they belong
to, et cetera. Looking up the chunks is expensive, so this change
speeds up the planning.
Part of https://github.com/timescale/timescaledb/pull/3890
> Cache chunk data when performing chunk exclusion

- CHANGELOG.md
- tsl/src/nodes/data_node_dispatch.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
When inserting in a distributed hypertable with a query on a
distributed hypertable a segfault would occur when all the chunks
on the query would get pruned.
> Fix segfault on INSERT in distributed hypertables

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
This PR fixes ON_END logic for distributed DDL execution
by removing old leftover check, which marked those commands
as unsupported.
Fix: #4106
> Fix RENAME TO/SET SCHEMA on distributed hypertable

- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/planner.c
- src/nodes/constraint_aware_append/constraint_aware_append.c
- src/utils.c
- tsl/src/nodes/async_append.c
Change error messages when unexpected nodes are encountered to
actually show the node name instead of the node id.
> Improve planner error messages regarding nodes

- scripts/test_update_smoke.sh
- test/sql/updates/cleanup.constraints.sql
- test/sql/updates/cleanup.continuous_aggs.v2.sql
- test/sql/updates/cleanup.multinode.sql
- test/sql/updates/cleanup.timestamp.sql
- test/sql/updates/cleanup.v7.sql
- test/sql/updates/post.v6.sql
- test/sql/updates/post.v7.sql
Smoke tests where missing critical files and some tests had changed
since last run and did not handle update smoke tests, so fixing all
necessary issues.
> Fixes to smoke update tests

- scripts/gh_matrix_builder.py
- test/src/test_scanner.c
Add concurrent_query_and_drop_chunks to ignore-list (https://github.com/timescale/timescaledb/runs/5397594903?check_suite_focus=true) and fix C compiler warning (https://github.com/timescale/timescaledb/runs/5397595100?check_suite_focus=true).
> Fix regressions found in nightly CI

- sql/size_utils.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/telemetry/stats.c
- src/utils.c
- src/utils.h
- test/expected/relocate_extension.out
- test/expected/size_utils.out
- test/sql/size_utils.sql
- tsl/src/compression/compress_utils.c
- tsl/test/expected/compression.out
- tsl/test/expected/dist_util.out
- tsl/test/sql/dist_util.sql
Reorganize the code and fix minor bug that was not computing the size
of FSM, VM and INIT forks of the parent hypertable.
Fixed the bug by exposing the `ts_relation_size` function to the SQL
level to encapsulate the logic to compute `heap`, `indexes` and `toast`
sizes.
> Refactor function `hypertable_local_size`

- .github/workflows/sqlsmith.yaml
sqlsmith is a random SQL query generator and very useful for finding
bugs in our implementation as it tests complex queries and thereby
hits codepaths and interactions between different features not tested
in our normal regression checks.
Fixes #4147
> Add workflow for running sqlsmith

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Allow execution of VACUUM/ANALYZE commands on a data node without
enabling timescaledb.enable_client_ddl_on_data_nodes GUC
Fix #4157
> Allow ANALYZE command on a data node directly

- src/hypertable.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
When running `performDeletion` is necessary to have a valid relation
id, but when doing a lookup using `ts_hypertable_get_by_id` this might
actually return a hypertable entry pointing to a table that does not
exist because it has been deleted previously. In this case, only the
catalog entry should be removed, but it is not necessary to delete the
actual table.
This scenario can occur if both the hypertable and a compressed table
are deleted as part of running a `sql_drop` event, for example, if a
compressed hypertable is defined inside an extension. In this case, the
compressed hypertable (indeed all tables) will be deleted first, and
the lookup of the compressed hypertable will find it in the metadata
but a lookup of the actual table will fail since the table does not
exist.
Fixes #4140
> Ignore invalid relid when deleting hypertable

- CHANGELOG.md
The CVE ID was already referenced in the commit introducing the fix
but not in the CHANGELOG.
> Reference CVE ID in CHANGELOG

- .github/workflows/sqlsmith.yaml
Add workflow events to allow manually running Sqlsmith tests or when
pushing to the 'sqlsmith' branch. This is useful when submitting PRs
that one wants to run extra checks on, including Sqlsmith.
> Trigger Sqlsmith tests manually or by push to branch 

- CHANGELOG.md
- src/chunk_scan.c
- src/scan_iterator.c
- src/scan_iterator.h
- src/scanner.c
- src/scanner.h
- src/telemetry/stats.c
Scan functions cannot be called on a per-tuple memory context as they
might allocate data that need to live until the end of the scan. Fix
this in a couple of places to ensure correct memory handling.
Fixes #4148, #4145
Disable-Check: Commit-Count
> Fix memory handling during scans

- CMakeLists.txt
cmake > 3.10 is not packaged for some of the platforms we build
packages eg old ubuntu and debian version. Currently we modify
the CMakeLists.txt in those build environments and set the
minimum version to 3.10 already, which proofes that timescaledb
builds fine with cmake 3.10.
> Set minimum required cmake version to 3.10

- CHANGELOG.md
- tsl/src/fdw/scan_exec.c
- tsl/test/t/001_simple_multinode.pl
In certain multi-node queries, we end up using a parameterized query
on the datanodes. If "timescaledb.enable_remote_explain" is enabled we
run an EXPLAIN on the datanode with the remote query. EXPLAIN doesn't
work with parameterized queries. So, we check for that case and avoid
invoking a remote EXPLAIN if so.
Fixes #3974
Reported and test case provided by @daydayup863
> Fix remote EXPLAIN with parameterized queries

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/chunk_constraint.c
- src/chunk_scan.c
- src/dimension_slice.c
- src/dimension_slice.h
- src/dimension_vector.c
- src/hypertable_restrict_info.c
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- tsl/test/expected/chunk_api.out
Improve the performance of metadata scanning during hypertable
expansion.
When a hypertable is expanded to include all children chunks, only the
chunks that match the query restrictions are included. To find the
matching chunks, the planner first scans for all matching dimension
slices. The chunks that reference those slices are the chunks to
include in the expansion.
This change optimizes the scanning for slices by avoiding repeated
open/close of the dimension slice metadata table and index.
At the same time, related dimension slice scanning functions have been
refactored along the same line.
An index on the chunk constraint metadata table is also changed to
allow scanning on dimension_slice_id. Previously, dimension_slice_id
was the second key in the index, which made scans on this key …
> Improve restriction scanning during hypertable expansion

- src/chunk.c
- src/chunk.h
- tsl/src/fdw/modify_plan.c
Instead of loading the entire Chunk struct, just look up the data
nodes. This improves the performance of planning of UPDATEs
of distributed hypertables.
> Scan less chunk metadata when planning ForeignModify

- src/chunk.c
- src/chunk.h
- src/planner.c
Cache whether a rel is a chunk in classify_relation
Use a per-query hash table for this. This speeds up the repeated calls
to classify_relation by avoiding the costly chunk lookup.
Fixes https://github.com/timescale/timescaledb/issues/4044
> Cache whether a rel is a chunk in classify_relation     

- src/bgw/job.c
- src/bgw/scheduler.c
- src/loader/bgw_launcher.c
- test/src/bgw/scheduler_mock.c
- tsl/test/expected/bgw_db_scheduler.out
Functions `elog` and `ereport` are unsafe to use in signal handlers
since they call `malloc`. This commit removes them from signal
handlers.
Fixes #4200
> Remove signal-unsafe calls from signal handlers

- CHANGELOG.md
- src/loader/loader.c
If a session is started and loads (and caches, by OID) functions in the
extension to use them in, for example, a `SELECT` query on a continuous
aggregate, the extension will be marked as loaded internally.
If an `ALTER EXTENSION` is then executed in a separate session, it will
update `pg_extension` to hold the new version, and any other sessions
will see this as the new version, including the session that already
loaded the previous version of the shared library.
Since the pre-update session has loaded some functions from the old
version already, running the same queries with the old named functions
will trigger a reload of the new version of the shared library to get
the new functions (same name, but different OID), but since this has
already been loaded in a different version, it will …
> Abort sessions after extension reload

- tsl/src/compression/create.c
- tsl/test/expected/compression_errors.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_errors.sql
- tsl/test/sql/dist_compression.sql
When an ALTER TABLE ... ADD COLUMN IF NOT EXISTS ... command is executed
and the column already exists, we get an error message that the column already
exists on the compressed hypertable, even though IF NOT EXISTS is specified.
This PR removes this error.
Fix #4087
> Fix ADD COLUMN IF NOT EXISTS error on compressed hypertable

- tsl/src/fdw/scan_exec.c
- tsl/src/remote/cursor_fetcher.c
- tsl/src/remote/data_fetcher.c
- tsl/src/remote/data_fetcher.h
- tsl/src/remote/row_by_row_fetcher.c
- tsl/src/remote/tuplefactory.c
- tsl/src/remote/tuplefactory.h
We needlessly form/deform the heap tuples currently. Sometimes we do
need heap tuples when we have row marks and need a ctid (UPDATE RETURNING),
but not in this case. The implementation has three parts:
1. Change data fetcher interface to store a tuple into given slot
instead of returning a heap tuple.
2. Expose the creation of virtual tuple in tuple factory.
3. Use these facilities in row-by-row fetcher.
This gives some small speedup. It will become more important in the
future, as other parts of row-by-row fetcher are optimized.
> Use virtual tuples in row-by-row fetcher

- CHANGELOG.md
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Allow ALTER TABLE OWNER TO command to be used with distributed
hypertable.
Fix #4180
> Fix owner change for distributed hypertable

- CHANGELOG.md
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/compression_api.h
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/job.h
- tsl/src/bgw_policy/policy_utils.c
- tsl/src/bgw_policy/policy_utils.h
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/sql/bgw_reorder_drop_chunks.sql
Also remove unused code from compression_api. The function
policy_compression_get_verbose_log was unused. Moved it to
policy_utils and renamed to policy_get_verbose_log so that it can
be used by all policies
> Add logging for retention policy

- tsl/src/fdw/data_node_scan_exec.c
- tsl/src/fdw/data_node_scan_plan.c
Before, we would complain that we don't support fetching the system
columns with per-data node queries enabled, but still execute the code
that fetches it. Don't do this and complain earlier.
> Move the check to a more appropriate place

- tsl/src/partialize_finalize.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
The function `tsl_finalize_agg_ffunc` modified the aggregation state by
setting `trans_value` to the final result when computing the final
value. Since the state can be re-used several times, there could be
several calls to the finalization function, and the finalization
function would be confused when passed a final value instead of a
aggregation state transition value.
This commit fixes this by not modifying the `trans_value` when
computing the final value and instead just returns it (or the original
`trans_value` if there is no finalization function).
Fixes #3248
> Do not modify aggregation state in finalize

- src/hypertable.h
- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/deparse.c
- tsl/src/fdw/fdw.c
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/src/fdw/scan_plan.c
- tsl/src/nodes/gapfill/planner.c
- tsl/src/nodes/gapfill/planner.h
- tsl/src/planner.c
- tsl/test/shared/expected/dist_gapfill.out
- tsl/test/shared/expected/dist_gapfill_pushdown-12.out
- tsl/test/shared/expected/dist_gapfill_pushdown-13.out
- tsl/test/shared/expected/dist_gapfill_pushdown-14.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_gapfill_pushdown.sql.in
- tsl/test/shared/sql/include/dist_gapfill_query.sql
- tsl/test/shared/sql/include/shared_setup.sql
Allow the calls of time_bucket_gapfill to be executed at the
data nodes for improved query performance.
> Pushdown of gapfill to data nodes

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release is patch release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* #3974 Fix remote EXPLAIN with parameterized queries
* #4122 Fix segfault on INSERT into distributed hypertable
* #4142 Ignore invalid relid when deleting hypertable
* #4159 Fix ADD COLUMN IF NOT EXISTS error on compressed hypertable
* #4161 Fix memory handling during scans
* #4186 Fix owner change for distributed hypertable
* #4192 Abort sessions after extension reload
* #4193 Fix relcache callback handling causing crashes
**Thanks**
* @abrownsword for reporting a crash in the telemetry reporter
* @daydayup863 for reporting issue with remote explain
> Release 2.6.1

- CHANGELOG.md
- src/process_utility.c
- test/expected/truncate.out
- test/sql/truncate.sql
Stop throwing error "must be owner of hypertable" when a user with
TRUNCATE privilege on the hypertable attempts to TRUNCATE.
Previously we had a check that required TRUNCATE to only be
performed by the table owner, not taking into account the user's
TRUNCATE privilege, which is sufficient to allow this operation.
Fixes #4183
> Fix TRUNCATE error as non-owner on hypertable

- scripts/docker-build.sh
Due to a security vulnerability in git recent git versions now check
ownership of files and error out if it doesnt match current user.
Since we bind mount the source checkout into the build container
the user of the checkout is unlikely to match the user inside the
container. This patch configures git to skip the owner check for
the bind-mounted directory.
https://github.blog/2022-04-12-git-security-vulnerability-announced/
> Fix downgrade test git failure

- src/dimension_slice.c
- tsl/src/compression/simple8b_rle.h
Fix the potential NULL pointer dereference in
ts_dimension_slice_scan_iterator_get_by_id().
> Fix Coverity defect 376602

- CHANGELOG.md
- scripts/test_repair_from_tag.sh
- scripts/test_repairs.sh
- scripts/test_update_smoke.sh
- sql/updates/post-update.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/utils.c
- src/utils.h
- test/sql/updates/setup.repair.cagg.sql
- test/sql/updates/setup.repair.sql
- tsl/src/chunk_api.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/create.h
- tsl/src/continuous_aggs/options.c
- tsl/src/init.c
- tsl/src/process_utility.c
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/sql/include/cagg_ddl_common.sql
Add the missing variables to the finalization view of Continuous Aggregates and the corresponding columns to the materialization table. Cover the case of targets that contain Aggref nodes and Var nodes that are outside of the Aggref nodes at the same time.
Stop rebuilding the Continuous Aggregate view with ALTER MATERIALIZED VIEW. Attempt to repair the view at post-update time instead, and fail gracefully if it is not possible to do so without raw hypertable schema or data modifications.
Stop rebuilding the Continuous Aggregate view when switching realtime aggregation on and off. Instead, manipulate the User View by either:
1. removing the `UNION ALL` right-hand side and the `WHERE` clause when disabling realtime aggregation
2. adding the Direct View to the right of a `UNION ALL` operator …
> Fix segfault in Continuous Aggregates

- src/loader/loader.c
- src/planner.c
- tsl/src/reorder.c
Change reorder_rel function to not be exported and also removes the
timescale_ function name prefix from local functions.
> Don't export local reorder function

- scripts/gh_matrix_builder.py
- tsl/src/compression/create.c
- tsl/test/expected/compressed_collation.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compressed_collation.sql
We don't do this currently, so some queries return the wrong ordering
of rows if there is an index on the compressed chunk.
> Set the correct collation for the compressed chunk columns

- CHANGELOG.md
- sql/updates/pre-update.sql
The query to get the list of saved privileges during extension
upgrade had a bug and only applying the classoid restriction
for a subset of the entries when it should have been applied to
all returned rows leading to a failure during extension update
when init privileges for other classoids existed on any of the
relevant objects.
> Fix logic bug in init_privs query

- test/runner.sh
- test/runner_shared.sh
- tsl/test/expected/dist_grant-12.out
- tsl/test/expected/dist_grant-13.out
- tsl/test/expected/dist_grant-14.out
Commit 9b180915 introduce some tests that are a bit flaky because are
checking a DEBUG message from Postgres catcache rehashing.
Fixed it by teaching our test runner to ignore this Postgres DEBUG
message.
> Fix flaky dist grant tests

- .git-blame-ignore-revs
- CHANGELOG.md
This patch adds the spelling fix commit to the git blame ignore
list and adds a thank you to the changelog for the author.
The git blame change couldnt be done in the spelling PR because
it references the commit hash.
> Ignore spelling fixes in git blame

- sql/updates/post-update.sql
post_update_cagg_try_repair was created with `CREATE OR REPLACE`
instead of CREATE. Additionally the procedure was created in the
public schema. This patch adjusts the procedure to be created
with `CREATE` and in a timescaledb internal schema.
Found by pgspot.
> Fix unsafe procedure creation in update script

- tsl/test/src/remote/async.c
Postgres changed the connection error reporting in the stable
branches of PG12, PG13 and PG14 leading to our snapshot tests
always failing. This patch removes the checks that now fail
with the upstream change.
https://github.com/postgres/postgres/commit/ae27b1ac
> Fix flaky remote_connection test

- tsl/src/compression/compress_utils.c
- tsl/test/expected/cagg_errors.out
- tsl/test/sql/cagg_errors.sql
When we have a hypertable with a cagg defined on it,
a call to the compress_chunk with the hypertable's chunk
returns an unexpected status error. Fix the error message
to return "compression not enabled"
> Fix compress_chunk error message

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
Previously this option was ignored when creating a
continuous aggregate, even when explicitly set to true.
Fixes #4249
> Fix option "timescaledb.create_group_indexes"

- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
No functional change.
This refactoring adds explicit output attnos to the metadata of column
decompression, enabling DecompressChunk node to skip some input columns
of the compressed scan. This is ultimately needed to support physical
targetlists in compressed scan.
Part of #4234
> NFC. Enable DecompressChunk node to skip some input columns

- sql/time_bucket.sql
This was not caught earlier and is not currently caught by CI
because the check for unqualified casts is currently only in main
branch of pgspot and not yet in the tagged version we use as
part of PR checks.
> Fix unqualified type reference in time_bucket

- .github/workflows/pgspot.yaml
- sql/chunk_constraint.sql
- sql/ddl_internal.sql
- sql/hypertable_constraint.sql
- sql/maintenance_utils.sql
- sql/policy_internal.sql
- sql/pre_install/schemas.sql
- sql/restoring.sql
- sql/schema_info.sql
- sql/size_utils.sql
- sql/updates/README.md
- sql/updates/pre-update.sql
- sql/util_internal_table_ddl.sql
- sql/util_time.sql
Postgres will prepend pg_temp to the effective search_path if it
is not present in the search_path. While pg_temp will never be
used to look up functions or operators unless explicitly requested
pg_temp will be used to look up relations. Putting pg_temp in
search_path makes sure objects in pg_temp will be considered last
and pg_temp cannot be used to mask existing objects.
> Append pg_temp to search_path

- .github/workflows/abi.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- scripts/gh_matrix_builder.py
This is a *temporary* change to our workflows to ignore the test
because it is flaky and requires many jobs to be restarted before a
commit can be merged.  Does not address the issue that causes the
flakiness, which needs to be investigated.
> Ignore flaky "dist_gapfill_pushdown" test

- tsl/test/expected/remote_copy-12.out
- tsl/test/expected/remote_copy-13.out
- tsl/test/expected/remote_copy-14.out
- tsl/test/sql/remote_copy.sql.in
Currently it depends on the (unspecified) order in which the original
rows were inserted.
Part of #4285
> Make the test remote_copy stable by adding ORDER BYs

- tsl/src/fdw/data_node_scan_exec.c
- tsl/src/fdw/scan_exec.c
- tsl/src/fdw/scan_exec.h
- tsl/src/remote/cursor_fetcher.c
- tsl/src/remote/cursor_fetcher.h
- tsl/src/remote/data_fetcher.c
- tsl/src/remote/data_fetcher.h
- tsl/src/remote/row_by_row_fetcher.c
- tsl/src/remote/row_by_row_fetcher.h
- tsl/src/remote/tuplefactory.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_partial_agg.out
- tsl/test/expected/dist_query.out
- tsl/test/shared/expected/dist_distinct.out
- tsl/test/shared/expected/dist_distinct_pushdown.out
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/expected/dist_gapfill_pushdown-12.out
- tsl/test/shared/expected/dist_gapfill_pushdown-13.out
- tsl/test/shared/expected/dist_gapfill_pushdown-14.out
- tsl/test/shared/sql/dist_fetcher_type.sql
- tsl/test/shared/sql/include/shared_setup.sql
- tsl/test/sql/dist_hypertable.sql.in
This gives some minor speedup and prepares for use of COPY protocol in
row-by-row-fetcher. We can only use the binary format if all the data
types support binary serialization. This is checked at execution time
when creating a TupleFactory. The fetcher interface is refactored to
allow for external creation of TupleFactory.
When a data type doesn't have binary serialization, we revert to using Cursor fetcher.
Part of #4188
> Use binary format in row-by-row fetcher

- .github/workflows/apt-packages.yaml
- scripts/gh_matrix_builder.py
ubuntu jammy only has 1 timescaledb version packaged at the moment
so downgrade is not possible.
> Disable downgrade test for ubuntu jammy

- src/telemetry/stats.c
- src/telemetry/stats.h
- src/telemetry/telemetry.c
- src/ts_catalog/continuous_agg.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/telemetry_stats.out
- tsl/test/sql/telemetry_stats.sql
Introduced by #4294 and #4269 PRs the default implementation of
Continuous Aggregates get rid of `chunk_id` in the materialization
hypertable and `partialize_agg`/`finalize_agg` aggregate functions.
A new counter named `num_caggs_finalized` was added to telemetry report
in this PR to count the number of Continuos Aggregates created in this
new format.
> Telemetry Stats for CAggs finals form

- .github/workflows/apt-packages.yaml
Ubuntu 21.04 is EOL since january so we no longer need to support
and test it.
> Remove Ubuntu 21.04 from packages tests

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-12.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
Namely, we don't have to project the result of the underlying scan of DecompressChunk, because the latter can selectively decompress the resulting columns anyway. The projection slows down the things especially when we use JIT, when the projection has to be compiled for each chunk.
Fixes https://github.com/timescale/timescaledb/issues/4222
Fixes https://github.com/timescale/timescaledb/issues/4195
Avoid extra projection when scanning a compressed chunk
We don't have to project the result of the underlying scan of DecompressChunk, because the latter can selectively decompress the resulting columns anyway. The projection slows down the things especially when we use JIT, when the projection has to be compiled for each chunk.
To avoid this unnecessary work, use the physical targetlist for …
> Avoid extra projection when scanning a compressed chunk

- CHANGELOG.md
- src/copy.c
- src/nodes/chunk_insert_state.h
- test/expected/copy-12.out
- test/expected/copy-13.out
- test/expected/copy-14.out
- test/sql/copy.sql.in
This commit backports the Postgres upstream multi-buffer / bulk insert
optimization into the timescale copy operator. If the target chunk
allows it (e.g., if no triggers are defined on the hypertable or the
chunk is not compressed), the data is stored in in-memory buffers
first and then flushed to the chunks in bulk operations.
The `CopyMulti*` functions are based on the [PG 14 source code](https://github.com/postgres/postgres/blob/REL_14_STABLE/src/backend/commands/copyfrom.c)
and adapted to work with hypertables and chunks.
Implements: #4080
For posterity, the benchmarks are here: https://docs.google.com/document/d/1qi44rQOcagirCBTWorB5ht1useZpzdgvhBVECkOQUPg/edit //akuzm
> Multi-buffer copy optimization backport

- src/init.c
- src/loader/loader.c
- test/src/loader/init.c
- tsl/src/init.c
_PG_fini is meant to be the hook to run code on module unload but
this code is not working and has not been working for over 12 years
because upstream does not support it.
https://github.com/postgres/postgres/commit/ab02d702ef08343fba30d90fdf7df5950063e8c9
> Remove _PG_fini functions

- src/bgw/job.c
- src/bgw/scheduler.c
- src/loader/bgw_launcher.c
In #4199 existing calls of `ereport` were replaced with calls of
`write_stderr` to eliminate the use of signal-unsafe calls, in
particular calls to `malloc`. Unfortunately, `write_stderr` contains a
call to `vfprintf`, which allocates memory as well, occationally
causing servers that are shutting down to become unresponsive.
Since the existing signal handlers just called `die` after printing out
a useful message, this commit fixes this by using `die` as a signal
handler.
Fixes #4200
> Remove printouts from signal handlers

- CHANGELOG.md
- src/loader/bgw_launcher.c
- src/loader/loader.c
- src/loader/loader.h
This GUC permits configuring the TIMEOUT parameter
for the background worker launcher in the loader.
Fixes #4217
> Add GUC "bgw_launcher_poll_time"

- CHANGELOG.md
- src/compat/compat.h
- src/guc.c
- src/guc.h
- src/planner/CMakeLists.txt
- src/planner/add_hashagg.c
- src/planner/constify_now.c
- src/planner/planner.c
- src/planner/planner.h
- test/expected/append-12.out
- test/expected/append-13.out
- test/expected/append-14.out
- test/sql/append.sql.in
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/expected/constify_timestamptz_op_interval.out
- tsl/test/shared/expected/ordered_append_join-12.out
- tsl/test/shared/expected/ordered_append_join-13.out
- tsl/test/shared/expected/ordered_append_join-14.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/constify_now.sql.in
- tsl/test/shared/sql/constify_timestamptz_op_interval.sql
- tsl/test/shared/sql/ordered_append_join.sql.in
This implements an optimization to allow now() expression to be
used during plan time chunk exclusions. Since now() is stable it
would not normally be considered for plan time chunk exclusion.
To enable this behaviour we convert `column > now()` expressions
into `column > const AND column > now()`. Assuming that time
always moves forward this is save even for prepared statements.
This optimization works for SELECT, UPDATE and DELETE.
On hypertables with many chunks this can lead to a considerable
speedup for certain queries.
The following expressions are supported:
- column > now()
- column >= now()
- column > now() - Interval
- column > now() + Interval
- column >= now() - Interval
- column >= now() + Interval
Interval must not have a day or month component as those depend
on timezone …
> Enable now() usage in plan-time chunk exclusion

- test/src/test_utils.c
Building against PG12.0 failed with
test_utils.c:99:5: error: expected ‘;’ before ‘errmsg’
because the errmsg argument was not in parens.
> Fix build failure on PG12.0

- .github/workflows/update-test.yaml
Bump PG versions to 12.11, 13.7 and 14.3 in update tests. The update
test was skipped with the previous PG version bump because upstream
docker images were not yet available which we rely on in the update
test.
> Bump pg version in update test

- tsl/test/shared/sql/include/shared_setup.sql
Commit 3b35da76 changed the setup script for regresscheck-shared
to no longer be usable directly by the sqlsmith workflow. This
patch set TEST_DBNAME at the top of the script so it is easier
to use the script outside of regression check environment.
> Fix sqlsmith CI workflow

- sql/ddl_experimental.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/chunk_copy.c
- tsl/src/init.c
- tsl/src/reorder.c
- tsl/src/reorder.h
- tsl/test/expected/dist_move_chunk.out
- tsl/test/shared/expected/extension.out
- tsl/test/t/002_chunk_copy_move.pl
The non-superuser needs to have REPLICATION privileges atleast. A
new function "subscription_cmd" has been added to allow running
subscription related commands on datanodes. This function implicitly
upgrades to the bootstrapped superuser and then performs subscription
creation/alteration/deletion commands. It only accepts subscriptions
related commands and errors out otherwise.
> Support non-superuser move chunk operations

- CHANGELOG.md
- test/sql/updates/setup.continuous_aggs.v2.sql
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/expected/cagg_errors_deprecated.out
- tsl/test/expected/cagg_query-12.out
- tsl/test/expected/cagg_query-13.out
- tsl/test/expected/cagg_query-14.out
- tsl/test/expected/cagg_union_view-12.out
- tsl/test/expected/cagg_union_view-13.out
- tsl/test/expected/cagg_union_view-14.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_deprecated.out
- tsl/test/expected/jit-12.out
- tsl/test/expected/jit-13.out
- tsl/test/expected/jit-14.out
- tsl/test/expected/telemetry_stats.out
- tsl/test/isolation/expected/cagg_drop_chunks.out
- tsl/test/isolation/specs/cagg_drop_chunks.spec.in
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_errors.sql
- tsl/test/sql/cagg_errors_deprecated.sql
- tsl/test/sql/cagg_query.sql.in
- tsl/test/sql/continuous_aggs.sql
- tsl/test/sql/continuous_aggs_deprecated.sql
- tsl/test/sql/include/cagg_ddl_common.sql
Following work started by https://github.com/timescale/timescaledb/pull/4294 to improve performance of Continuous
Aggregates by removing the re-aggregation in the user view.
This PR get rid of `partialize_agg` and `finalize_agg` aggregate
functions and store the finalized aggregated (plain) data in the
materialization hypertable.
Because we're not storing partials anymore and removed the
re-aggregation, now is be possible to create indexes on aggregated
columns in the materialization hypertable in order to improve the
performance even more.
Also removed restrictions on types of aggregates users can perform
with Continuous Aggregates:
* aggregates with DISTINCT
* aggregates with FILTER
* aggregates with FILTER in HAVING clause
* aggregates without combine function
* ordered-set aggregates …
> Continuous Aggregates finals form

- sql/maintenance_utils.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/ts_catalog/catalog.h
- tsl/src/chunk_copy.c
- tsl/src/compression/compress_utils.c
- tsl/src/compression/compress_utils.h
- tsl/src/compression/create.c
- tsl/src/compression/create.h
- tsl/src/init.c
- tsl/test/expected/dist_move_chunk.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/dist_move_chunk.sql
This change allows to copy or move compressed chunks between data nodes by including compressed chunk into the chunk copy command stages.
> Support moving compressed chunks between data nodes

- test/sql/updates/post.catalog.sql
This patch adds a test for attnum consistency to our update scripts.
When attnum between fresh install and updated install is different
the updated installation will not be able to correctly process affected
catalog tables.
Fixes #4351
> Test attnum stays consistent in update

- src/planner/constify_now.c
- src/planner/planner.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
This patch fixes the constify_now optimization to ignore Vars of
different level. Previously this could potentially lead to an
assertion failure cause the varno of that varno might be bigger
than the number of entries in the rangetable. Found by sqlsmith.
> Fix Var handling for Vars of different level in constify_now

- src/copy.c
- test/expected/copy-12.out
- test/expected/copy-13.out
- test/expected/copy-14.out
- test/sql/copy.sql.in
This patch solves a crash in the multi-buffer copy optimization,
which was introduced in commit bbb2f414d2090efd2d8533b464584157860ce49a.
This patch handles closed chunks (e.g., caused by timescaledb.max_open_
chunks_per_insert) properly. The problem is addressed by:
1) Re-reading the ChunkInsertState before the data is stored, which
ensures that the underlying table is open.
2) A TSCopyMultiInsertBuffer is deleted after the data of the buffer
is flushed. So, operations like table_finish_bulk_insert are
executed and the associated chunk can properly be closed.
> Fix a crash in the copy multi-buffer optimization

- src/chunk.c
- src/chunk_index.c
- src/dimension.c
- src/ts_catalog/tablespace.c
- src/utils.c
- src/utils.h
- test/expected/tablespace.out
- test/sql/tablespace.sql
- tsl/src/compression/compress_utils.c
- tsl/src/compression/create.c
- tsl/src/reorder.c
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/move.out
- tsl/test/sql/compression_ddl.sql
- tsl/test/sql/move.sql
A number of TimescaleDB functions internally call `AlterTableInternal`
to modify tables or indexes. For instance, `compress_chunk` and
`attach_tablespace` act as DDL commands to modify
hypertables. However, crashes occur when these functions are called
via `SELECT * INTO FROM <function_name>` or the equivalent `CREATE
TABLE AS` statement. The crashes happen because these statements are
considered process utility commands and therefore sets up an event
trigger context for collecting commands. However, the event trigger
context is not properly set up to record alter table statements in
this code path, thus causing the crashes.
To prevent crashes, wrap `AlterTableInternal` with the event trigger
functions to properly initialize the event trigger context.
> Fix crashes in functions using AlterTableInternal

- test/runner_shared.sh
- tsl/test/shared/expected/dist_distinct.out
- tsl/test/shared/expected/dist_distinct_pushdown.out
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/expected/dist_remote_error.out
- tsl/test/shared/sql/dist_remote_error.sql
- tsl/test/shared/sql/include/shared_setup.sql
The table metrics_dist1 was only used by a single test and therefore
should not be part of shared_setup but instead be created in the
test that actually uses it. This reduces executed time of
regresscheck-shared when that test is not run.
> Move metrics_dist1 out of shared_setup

- appveyor.yml
On appveyor the pg_dump is flaky and seems to fail every other time.
This patch makes appveyor ignore the result of that test.
> Ignore pg_dump test on appveyor

- CHANGELOG.md
- src/telemetry/stats.c
- src/telemetry/telemetry.c
- tsl/test/isolation/expected/telemetry.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/telemetry.spec.in
Make the following changes to the telemetry reporter background
worker:
- Add a read lock to the current relation that the reporter collects
stats for. This lock protects against concurrent deletion of the
relation, which could lead to errors that would prevent the reporter
from completing its report.
- Set an active snapshot in the telemetry background process for use
when scanning a relation for stats collection.
- Reopen the scan iterator when collecting chunk compression stats for
a relation instead of keeping it open and restarting the scan. The
previous approach seems to cause crashes due to memory corruption of
the scan state. Unfortunately, the exact cause has not been
identified, but the change has been verified to work on a live
running instance (thanks to @abrownsword for the …
> Fix crash and other issues in telemetry reporter 

- scripts/gh_matrix_builder.py
The tablespace test causes a segfault on PG12.0 due to an upstream
bug in the event trigger handling.
> Skip tablespace test on PG12.0

- scripts/gh_matrix_builder.py
With recent refactorings the telemetry test seems to trigger the
same use-after-free bug that got triggered by tablespace test so
we skip that test on PG12.0 as well.
> SKIP telemetry test on PG12.0

- scripts/gh_matrix_builder.py
Commit 7b9d8673 added an isolation test for telemetry but did not
add it to the ignore list for earlier postgres versions. PG14 changed
the output format for isolation tests which got backported to PG12
and PG13 which makes the output of earlier PG12 and PG13 different
from the latest one so we ignore isolation tests on those earlier
versions.
> Ignore telemetry isolation test on PG13.2

- scripts/gh_matrix_builder.py
The deadlock_recompress_chunk isolation test uses syntax not
supported by earlier versions of the isolation tester leading
to a parse failure when processing that file on PG13.2.
This patch skips that particular test on PG13.2.
> Fix PG13.2 isolation tests

- src/copy.c
- src/nodes/chunk_insert_state.h
The multi-buffer copy optimization creates a multi-insert buffer per
`ChunkInsertState`. However, chunks can be closed. When
`ts_chunk_dispatch_get_chunk_insert_state` is called for a closed chunk
again, a new `ChunkInsertState` is returned. So far, also a new
multi-insert buffer has been created. Therefore, multiple batch
operations could be executed per chunk, which reduces the efficiency
of the optimization.
This patch introduces an `HTAB` that maps from the `chunk_id` to the
multi-insert buffer. Even when a chunk is closed, all tuples for
a chunk are stored in the same buffer.
> Improved buffer management in the copy operator

- scripts/gh_matrix_builder.py
- test/pg_prove.sh
The 001_extension test uses the background_psql function which is not
present in the 13.2 PostgresNode module. This function is only
available in PG 13.5+.
https://github.com/postgres/postgres/commit/a9d0a540
> Fix PG13.2 nightly CI failures

- tsl/src/data_node.c
Compilers are not smart enough to check that `conn` is initialized
inside the loop so not initializing it gives an error. Added an
initializer to the auto variable to get rid of the error.
> Add initializer to auto variable

- src/guc.c
- src/guc.h
- src/loader/CMakeLists.txt
- src/loader/function_telemetry.c
- src/loader/function_telemetry.h
- src/loader/loader.c
- src/planner/planner.c
- src/process_utility.c
- src/telemetry/CMakeLists.txt
- src/telemetry/functions.c
- src/telemetry/functions.h
- src/telemetry/telemetry.c
- test/expected/telemetry.out
- test/sql/telemetry.sql
- tsl/test/expected/telemetry_stats.out
- tsl/test/sql/telemetry_stats.sql
This PR extends our telemetry system with function call telemetry. It gathers function call-counts from all queries, and send back counts for those functions that are built in or from our related extensions.
See [the RFC](https://docs.google.com/document/d/1wy_ma4RzCNceCDkR6HAC1NPZffdHJTOWTy4QhGPsXsY/edit#heading=h.6bq5eesegmp8) (internal link) for more details.
> Function telemetry

- .github/workflows/coccinelle.yaml
- .github/workflows/shellcheck.yaml
Currently coccinelle and shellcheck get run an additional time
for every merged commit to master. This patch adjusts the config
so they are only run on pull request or on push to prerelease_test
instead of push to any branch, similar to how all the other
workflows are set up.
> Adjust coccinelle and shellcheck CI config

- CHANGELOG.md
- src/planner/constify_now.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
The initial patch to use now() expressions during planner hypertable
expansion only supported intervals with no day or month component.
This patch adds support for intervals with day component.
If the interval has a day component then the calculation needs
to take into account daylight saving time switches and thereby a
day would not always be exactly 24 hours. We mitigate this by
adding a safety buffer to account for these dst switches when
dealing with intervals with day component. These calculations
will be repeated with exact values during execution.
Since dst switches seem to range between -1 and 2 hours we set
the safety buffer to 4 hours.
This patch also refactors the tests since the previous tests
made it hard to tell the feature was working after the constified
values have been …
> Support intervals with day component when constifying now()

- tsl/src/data_node.c
- tsl/src/remote/connection_cache.c
- tsl/test/src/test_compression.c
PG 15 removes pg_atoi, so this patch changes all callers to use
pg_strtoint16/32.
https://github.com/postgres/postgres/commit/73508475
> Replace pg_atoi with pg_strtoint16/32

- CHANGELOG.md
- src/planner/constify_now.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
When dealing with Intervals with month component timezone changes
can result in multiple day differences in the outcome of these
calculations due to different month lengths. When dealing with
months we add a 7 day safety buffer.
For all these calculations it is fine if we exclude less chunks
than strictly required for the operation, additional exclusion
with exact values will happen in the executor. But under no
circumstances must we exclude too much cause there would be
no way for the executor to get those chunks back.
> Support intervals with month component when constifying now()

- sql/partialize_finalize.sql
- test/runner_shared.sh
- tsl/test/shared/expected/dist_parallel_agg.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_parallel_agg.sql
Just an experiment to see what happens.
UPD: the experiment turned out to be a success. Seems that we can mark the partialize_agg function as parallel safe always, and the parallel plans are generated depending on the underlying aggregate function. Postgres does the full expression tree traversal to check for parallel unsafe functions, as expected.
Fixes https://github.com/timescale/timescaledb/issues/4306
Mark partialize_agg as parallel-safe
This function is used to push down aggregation to data nodes, and making it parallel-safe allows to use parallel plans on data nodes, if the underlying aggregate function is parallel-safe as well. Add negative and positive tests for this.
> Mark partialize_agg as parallel safe

- src/bgw/job.c
- src/bgw/scheduler.c
- src/bgw/scheduler.h
- src/bgw/worker.h
- test/src/bgw/scheduler_mock.c
Non-functional change.
Parameters to workers were passed in as a serialized string, which then
needs to be serialized and deserialized using dedicated functions.
This commit refactors code to pass parameters to workers as a struct,
which is then just copied into the `bgw_extra` field of
`BackgroundWorker`. The struct contains simple values and can therefore
be copied using memcpy(3c).
> Pass parameters to workers as a struct

- tsl/src/compression/create.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
When enabling compression on a hypertable, the orderby option can be
omitted, which will set the default value of "time DESC". 
However previously, when executing the same command twice not setting
orderby, the second time we would get an error that orderby was
previously set and must be specified.
For example executing
`alter table set (timescaledb.compress, timescaledb.segmentby = '..')`
The reason for that error was that it's unclear if no orderby means
leave as is, or if it means set the default value. 
But in the case where orderby is already set to the default value, 
there is no ambiguity and both cases are equivalent, so the default
value can be reset without giving an error. 
Fixes #4331
> Don't ask for orderby column if default already set

- src/compat/compat.h
- src/utils.c
- src/utils.h
PG13 added an implementation of find_em_expr_for_rel to postgres
core code. Which is removed again in PG15. This patch adjusts
our macros to deal with the removal in PG15.
https://github.com/postgres/postgres/commit/f3dd9fe1
> Use our implementation of find_em_expr_for_rel for PG15+

- .github/workflows/linux-32bit-build-and-test.yaml
- CHANGELOG.md
- src/nodes/chunk_dispatch_state.h
- src/nodes/chunk_insert_state.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/nodes/data_node_dispatch.c
- tsl/test/shared/expected/dist_queries.out
- tsl/test/shared/sql/dist_queries.sql
- tsl/test/shared/sql/include/shared_setup.sql
For certain inserts on a distributed hypertable, e.g., involving CTEs
and upserts, plans can be generated that weren't properly handled by
the DataNodeCopy and DataNodeDispatch execution nodes. In particular,
the nodes expect ChunkDispatch as a child node, but PostgreSQL can
sometimes insert a Result node above ChunkDispatch, causing the crash.
Further, behavioral changes in PG14 also caused the DataNodeCopy node
to sometimes wrongly believe a RETURNING clause was present. The check
for returning clauses has been updated to fix this issue.
Fixes #4339
Disable-Check: Commit-Count
> Fix crash during insert into distributed hypertable

- tsl/src/compression/create.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
Previously we created one index per segmentby column, of the form
`(col, _ts_meta_sequence_num)`. 
Compressed data is ordered by segmentby, then by orderby within
the segments and lastly by the sequence number of the batch. So if
segmentby columns are missing from the index, that index cannot be
used to produce ordered output, requiring an extra sort step.
A composite index containing all segmentby columns removes the 
additional sort step and gives better plans. 
Fixes #4314
> Create composite index on segmentby columns

- src/loader/loader.c
This patch consolidates all shared memory requests in a
shmem_request_hook. While there are no strict requirements when
to request shared memory for PG < 15 in PG 15 it has to happen
in the shmem_request_hook otherwise the request will be blocked.
https://github.com/postgres/postgres/commit/4f2400cb
> Add shmem_request_hook

- src/chunk.c
- src/chunk.h
- src/dimension_slice.c
- src/dimension_slice.h
- src/hypertable.c
- src/hypertable.h
- src/nodes/chunk_dispatch.c
- tsl/src/remote/dist_copy.c
Don't keep the chunk constraints while searching. The number of
candidate chunks can be very large, so keeping these constraints is a
lot of work and uses a lot of memory. For finding the matching chunk,
it is enough to track the number of dimensions that matched a given
chunk id. After finding the chunk id, we can look up only the matching
chunk data with the usual function.
This saves some work when doing INSERTs.
Gives 10%-30% speedup on my COPY tests that touch a lot of chunks.
Part of #4285
> Faster lookup of chunks by point

- src/process_utility.c
- test/sql/utils/testsupport.sql
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/expected/continuous_aggs_deprecated.out
- tsl/test/sql/continuous_aggs_deprecated.sql
- tsl/test/sql/include/cagg_ddl_common.sql
Timescale 2.7 released a new version of Continuous Aggregate (#4269)
that allows users efectivelly create and use indexes in the
materialization hypertable. The boring part of it is that users should
discover what is the associated materialization hypertable to issue a
`CREATE INDEX` statement.
Improved it by allowing users to easily create indexes in the
materialization hypertable by simple executing a `CREATE INDEX` direct
in the Continuous Aggregate.
Example:
`CREATE INDEX name_of_the_index ON continuous_agregate (column);`
> Create indexes on Continuous Aggregates

- tsl/src/reorder.c
- tsl/test/t/002_chunk_copy_move.pl
Add a check for NULL input to subscription_exec as the function
currently segfaults on NULL input. Found by sqlsmith.
> Fix segfault in subscription_exec

- test/expected/chunk_utils.out
- test/sql/include/query_result_test_equal.sql
When running Timescaledb tests with a custom build of PostgreSQL 14 (with modified planner code), I noticed that some **alter** and **chunk_utils** tests fail:
[regression.diff.txt](https://github.com/timescale/timescaledb/files/8918266/regression.diff.txt)
I found that it was due to different plans e.g. in alter.sql. I got:
[modified.txt](https://github.com/timescale/timescaledb/files/8918311/modified.txt)
instead of 
[original.txt](https://github.com/timescale/timescaledb/files/8918318/original.txt)
This leads to change in the order of calls of _drop_chunks_ and _show_chunks_ which is not expected by the test.
In a current PR I propose a quick fix for the problem.
(for easy reproduction of planner change there can be used planner hacking from the patch, though I found the problem other …
> Fix tests to be resilient to possible PG planner changes.

- tsl/src/chunk_api.c
- tsl/src/chunk_copy.c
- tsl/test/expected/chunk_api.out
- tsl/test/sql/chunk_api.sql
- tsl/test/t/002_chunk_copy_move.pl
We mandate that a superuser or a user with REPLICATION privileges can
invoke copy_chunk or move_chunk procedures. Internally, many stages
are carried out to complete the activity and different stages need
different user permissions. To keep things uniform we now switch to the
bootstrap superuser in each stage. Care is taken to ensure that the
original hypertable ownership is retained on the new chunk post the
move operation.
> Fix perms in copy/move chunk

- test/src/test_utils.c
- tsl/src/remote/async.c
- tsl/src/remote/connection.c
- tsl/test/shared/expected/dist_remote_error.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/dist_remote_error.sql
- tsl/test/shared/sql/include/dist_remote_error_setup.sql
Use a data type with faulty send/recv functions to test various error
handling paths.
> Add more tests for errors on data nodes

- .github/workflows/update-test.yaml
Switch update/downgrade test to use 14.4. This has been split off
the CI PR switching the rest of CI to 14.4 because it usually takes
more then a week for the upstream docker images to become available.
> Use PG 14.4 in update test

- tsl/src/remote/tuplefactory.c
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/sql/dist_fetcher_type.sql
- tsl/test/shared/sql/include/shared_setup.sql
The "empty" bytea value in a column of a distributed table when
selected was being returned as "null". The actual value on the
datanodes was being stored appropriately but just the return code path
was converting it into "null" on the AN. This has been handled via the
use of PQgetisnull() function now.
Fixes #3455
> Fix empty bytea handlng with distributed tables

- sql/job_api.sql
- sql/updates/reverse-dev.sql
- src/bgw/job.c
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/bgw_policy/job_api.c
- tsl/src/bgw_policy/job_api.h
- tsl/src/init.c
- tsl/test/expected/bgw_custom.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/bgw_custom.sql
This PR introduces a new SQL function to associate a
hyperatable or continuous agg with a custom job. If
this dependency is setup, the job is automatically
deleted when the hypertable/cagg is dropped.
Reviewers: Need this functionality  for policy functions in OSM  extension.
> Add api to associate hypertable with custom jobs

- tsl/src/chunk_copy.c
- tsl/test/expected/dist_move_chunk.out
- tsl/test/t/002_chunk_copy_move.pl
The current code was assuming the bootstrap superuser for the actual
move chunk operation. However, we can make it further flexible by using
the logged in credentials if those happen to have superuser privileges.
> Better superuser handling for move_chunk

- sql/chunk.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/chunk.h
- src/nodes/chunk_insert_state.c
- src/planner/planner.c
- tsl/src/compression/api.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/chunk_utils_internal.sql
A chunk in frozen state cannot be dropped.
drop_chunks will skip over frozen chunks without erroring.
Internal api , drop_chunk will error if you attempt to  drop
a chunk without unfreezing it.
This PR also adds a new internal API to unfreeze a chunk.
> Block drop chunk if chunk is in frozen state

- .github/workflows/procedural.yaml
Add workflow to automatically add all issues opened or labeled to the
bug board for triage.
> Add workflow to move issue to triage

- test/src/test_utils.c
- tsl/test/shared/expected/dist_remote_error.out
- tsl/test/shared/sql/dist_remote_error.sql
- tsl/test/shared/sql/include/dist_remote_error_setup.sql
More interleavings of INSERT/COPY, and test with slow recv() to check
waiting.
Also fix some flakiness while we're at it.
Fixes https://github.com/timescale/timescaledb/issues/4485
> Add more tests for distributed INSERT and COPY

- CHANGELOG.md
- src/planner/planner.c
- test/expected/ddl-12.out
- test/expected/ddl-13.out
- test/expected/ddl-14.out
- test/sql/ddl.sql.in
Executing an IMMUTABLE function that has parameters and exception
handling block multiple times in the same transaction causes a null
pointer segfault when try to reset a non-initialized `ts_baserel_info`.
Fixed it by preventing to reset a non-initialized `ts_baserel_info`.
Fixes https://github.com/timescale/timescaledb/issues/4489
> Segfault when executing IMMUTABLE functions

- tsl/src/data_node.c
- tsl/src/dist_util.c
- tsl/src/dist_util.h
- tsl/src/remote/connection.c
- tsl/test/expected/dist_util.out
- tsl/test/sql/dist_util.sql
- tsl/test/src/test_dist_util.c
The current check where we deem a DN incompatible if it's on a newer
version is exactly the opposite of what we want it to be. Fix that and
also add relevant test cases.
> Handle timescaledb versions aptly in multinode

- CHANGELOG.md
This release is a patch release. We recommend that you upgrade at the
next available opportunity.
**Bugfixes**
* #4494 Handle timescaledb versions aptly in multinode
* #4493 Segfault when executing IMMUTABLE functions
* #4482 Fix race conditions during chunk (de)compression
* #4367 Improved buffer management in the copy operator
* #4375 Don't ask for orderby column if default already set
* #4400 Use our implementation of `find_em_expr_for_rel` for PG15+
* #4408 Fix crash during insert into distributed hypertable
* #4411 Add `shmem_request_hook`
* #4437 Fix segfault in subscription_exec
* #4442 Fix perms in copy/move chunk
* #4450 Retain hypertable ownership on `attach_data_node`
* #4451 Repair numeric partial state on the fly
* #4463 Fix empty bytea handlng with distributed tables
* #4469 …
> Release 2.7.1

- .github/workflows/stalebot.yaml
This PR introduces a configuration for the 'actions/stale' stalebot,
which is used to automatically flag and close stale issues after
a few days of inactivity.
Note: The configuration runs in dry-mode to test the behavior of the
bot on our repository first.
> Introduce a stalebot to close issues

- tsl/src/remote/row_by_row_fetcher.c
The sanitizer found unaligned pointers. On amd64 this is not a problem
but other platforms like arm are more strict regarding pointer alignment.
Fixes #4513
> Fix unaligned pointer access

- tsl/src/remote/row_by_row_fetcher.c
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/sql/dist_fetcher_type.sql
When executing multinode queries that initialize row-by-row fetcher
but never execute it the node cleanup code would hit an assertion
checking the state of the fetcher. Found by sqlsmith.
Fixes #4515
> Fix assertion hit in row_by_row_fetcher_close

- .github/workflows/stalebot.yaml
In #4499, a stalebot configuration was introduced. According to the
configuration, the stalebot runs in dry mode. The [output](https://github.com/timescale/timescaledb/runs/7383402365?check_suite_focus=true) of a dry
mode run was analyzed and issues with an outdated  "need-more-info"
label have been cleaned up. So, the stalebot can now be activated.
> Activate a stalebot to close issues

- src/nodes/chunk_append/exec.c
- tsl/test/shared/expected/compression_dml.out
- tsl/test/shared/expected/constraint_exclusion_prepared.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/compression_dml.sql
- tsl/test/shared/sql/include/constraint_exclusion_prepared.sql
This patch fixes the param handling in prepared statements for generic
plans in ChunkAppend making those params usable in chunk exclusion.
Previously those params would not be resolved and therefore not used
for chunk exclusion.
Fixes #3719
> Fix prepared statement param handling in ChunkAppend

- CHANGELOG.md
- tsl/src/nodes/gapfill/exec.c
- tsl/src/nodes/gapfill/exec.h
- tsl/test/shared/expected/gapfill-12.out
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/sql/gapfill.sql.in
The gapfill mechanism to detect an aggregation group change was
using datumIsEqual to compare the group values. datumIsEqual does
not detoast values so when one value is toasted and the other value
is not it will not return the correct result. This patch changes
the gapfill code to use the correct equal operator for the type
of the group column instead of datumIsEqual.
> Fix gapfill group comparison for toasted values

- CHANGELOG.md
- tsl/src/chunk_api.c
- tsl/test/expected/chunk_api.out
- tsl/test/sql/chunk_api.sql
For range types, the operator entry in statistics table is invalid.
Also, certain range types don't have "VALUES" but only have "NUMBERS"
entries.
> Handle stats properly for range types

- src/telemetry/functions.c
hash_create will create the hash table in TopMemoryContext unless
explicitly requested to create in different memory context. The
function telemetry code did not explicitly request a different
context leading to a memory leak.
Fixes #4507
> Fix memory leak in function telemetry

- .github/CODEOWNERS
In #4525 a workflow was introduced for running pull-review to
automate reviewer assignment based on code ownership. However
the CODEOWNERS file was not removed.  As reviewers will be assigned
based on it if it exists, it prevents the pull-review workflow
from taking effect. This commit removes CODEOWNERS to allow
pull-review to do the reviewer assignment.
> Remove CODEOWNERS file to activate pull-review

- CHANGELOG.md
- tsl/src/chunk_api.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Make sure ANALYZE can be run on a specific set of data nodes
assigned to the distributed hypertable.
Fix #4508
> Fix ANALYZE on dist hypertable for a set of nodes

- src/func_cache.c
- tsl/src/continuous_aggs/insert.c
This changes the hash_create calls in the function cache and in the
cagg code to use explicit memory context. Without this hash_create
will create the hash table in TopMemoryContext potentially leading
to memory leaks.
> Use explicit memory context with hash_create

- src/copy.c
Specifically, flush the chunk multi-insert states when the number of it
reaches the size of the chunk cache. Otherwise, the chunks
corresponding to the multi-insert states go out of cache and have to be
looked up again when the multi-insert state is flushed, which leads to
a performance hit.
Let's see if tsbench shows any improvement.
Part of https://github.com/timescale/timescaledb/pull/4285
> Synchronize chunk cache sizes

- scripts/gh_matrix_builder.py
macOS 10.15 is deprecated as github action environment and will
be unsupported by end of august. This PR switches our CI to use
macOS 11 environment instead.
https://github.com/actions/virtual-environments/issues/5583
> Bump macOS version used in CI to 11

- tsl/test/expected/dist_copy_long.out
- tsl/test/sql/dist_copy_long.sql
On macOS zcat expects the file to end in .Z appending that extension
when the supplied filename does not have it. Leading to the following
error for the dist_copy_long test:
zcat: can't stat: data/prices-10k-random-1.tsv.gz
(data/prices-10k-random-1.tsv.gz.Z): No such file or directory
This patch changes the dist_copy_long test to use the shell to read
the file instead and use input redirection so zcat never sees the
filename.
> Fix dist_copy_long test on macOS
