- sql/main/ddl_util.sql
Revised the get_general_index_definition function to handle cases where indexes have definitions other than just 'CREATE INDEX'.
Handles mixed-case identifiers correctly too.
```
\d "Foo"
Table "public.Foo"
Column    |  Type   | Modifiers
-------------+---------+-----------
foo_id      | integer |
foo_some_id | integer |
person_id   | integer |
Some ColumN | text    |
Indexes:
"foo_SomeColum Index" UNIQUE, btree ("Some ColumN")
"Foo_foo_some_id_IDX" btree (foo_some_id)
select oid,relname from pg_class where relname in ('Foo','foo_SomeColum Index','Foo_foo_some_id_IDX');
oid   |       relname
--------+---------------------
100798 | Foo
175162 | foo_SomeColum Index
175163 | Foo_foo_some_id_IDX
-- Index "foo_SomeColum Index"
-- This is the original function, it fails because the index def is …
```
> Revised the get_general_index_definition function

- README.md
Adding a few spaces to make it consistent with the rest of the SQL.
> Added spaces

- Makefile
- docs/API.md
- sql/load_order.txt
- sql/main/bookend.sql
- src/agg_bookend.c
- src/executor.h
- test/expected/agg_bookends.out
- test/sql/agg_bookends.sql
Add the first and last aggregate functions, which allows for getting
the first and last value, by time, per group.
> Add the first(value, time),last(value, time) aggregates

- src/init.c
Because this extension uses hooks, it should be preloaded into postgres.
This PR adds an error message if it is loaded dynamically (i.e. when
CREATE EXTENSION is run before without the library being preloaded).
> Add error when timescaledb library is not preloaded.

- Makefile
- src/guc.c
- src/guc.h
- src/init.c
- src/planner.c
- src/utils.c
- src/utils.h
- test/expected/sql_query_results_optimized.out
- test/expected/sql_query_results_unoptimized.out
- test/sql/include/sql_query_results.sql
This PR improves GUC handling to be more inline with the Postgres GUC
system.
> Improve GUC handling

- src/planner.c
- test/expected/sql_query.out
- test/sql/sql_query.sql
> Make constraint exclusion work with non-text partition keys

- src/planner.c
- src/process_utility.c
Make sure parameter names are in lowercase-underscore format. Also,
rename the query tree walker change_table_name_walker() to
hypertable_query_walker() to reflect that it is no long renaming
anything (only setting up state in case of a query on a hypertable).
> Cleanup planner and process utility hooks

- README.md
Currently it only select data from exactly 3 hours ago, but I think this probably meant in the last 3 hours :D
> Fix README example; 3 hours ago to last 3 hours

- sql/ddl_internal.sql
- src/metadata_queries.c
- src/metadata_queries.h
- src/process_utility.c
- test/expected/pg_dump.out
- test/expected/truncate_hypertable.out
- test/sql/truncate_hypertable.sql
> Remove empty chunks on TRUNCATE hypertable

- src/process_utility.c
This breaks up the handling of process utility statements into a clean
and efficient switch statement with separate functions for each
statement.
> Refactor process utility

- Makefile
- sql/chunk.sql
- sql/chunk_constraint.sql
- src/catalog.c
- src/catalog.h
- src/chunk.c
- src/chunk.h
- src/process_utility.c
- src/process_utility.h
- test/expected/ddl_errors.out
- test/expected/drop_chunks.out
- test/sql/ddl_errors.sql
- test/sql/drop_chunks.sql
This PR adds logic to block alter table and drop operations on chunks.
> Block operations on chunks

- Makefile
- sql/functions_load_order.txt
- sql/histogram.sql
- src/histogram.c
- test/expected/extension.out
- test/expected/histogram_test.out
- test/expected/parallel.out
- test/expected/pg_dump.out
- test/sql/histogram_test.sql
- test/sql/parallel.sql
A rebase with only minor modifications from commit e80720dd9b412a31d1079533323d0b01231926e3, pr #157
> Add histogram function.

- src/process_utility.c
- Move DDL upcalls to function macros for clarity and readability
- Rename some functions for consistency and remove unused parameters
- Refactor some code that did unecessary work
> Cleanup process utility for consistency

- scripts/dump_meta_data.sql
- test/expected/dump_meta.out
- test/runner.sh
- test/sql/dump_meta.sql
This is a script that can be run to dump relevant debug info.
> Add script to dump meta data that can be useful for debugging.

- src/process_utility.c
When recursing DDL operations to chunks, you often want
access to the hypertable in the chunk handler function. This
change gives the handler access to the hypertable data structure
rather then just the hypertable OID, obviating the need to do
a separate lookup that has likely already been done previously.
> Refactor functions used to recurse DDL commands to chunks

- scripts/test_updates.sh
- sql/chunk.sql
- sql/chunk_constraint.sql
- sql/ddl_api.sql
- sql/updates/pre-0.6.0--0.7.0-dev.sql
- src/catalog.c
- src/catalog.h
- src/chunk.c
- src/chunk_constraint.c
- src/chunk_constraint.h
- src/chunk_index.c
- src/chunk_index.h
- src/partitioning.c
- src/process_utility.c
- test/expected/constraint.out
- test/expected/index.out
- test/expected/pg_dump.out
- test/sql/index.sql
- test/sql/pg_dump.sql
- test/sql/updates/test-rerun.sql
This PR is two commits.
1) Adds an entry to the catalog entry for constraint-backed indexes
2) Improves the update test infrastructure with an additional test
> Add constraint index entries to the catalog

- src/copy.c
Refactor the copy code to get rid of the NOT is_from path. This
removes a lot of confusing dead code.
> Remove code related to COPY TO statements

- sql/ddl_api.sql
Hi, 
This error was encountered when defining a table with partitioning, and then calling create_hypertable() (on master, timescale repo, docker build process):
`[42809] ERROR: cannot create index on partitioned table "temps" Where: SQL statement " CREATE INDEX ON public.temps("time" DESC) " PL/pgSQL function _timescaledb_internal.create_default_indexes(_timescaledb_catalog.hypertable,regclass,name) line 29 at EXECUTE SQL statement "SELECT _timescaledb_internal.create_default_indexes(hypertable_row, main_table, partitioning_column)" PL/pgSQL function public.create_hypertable(regclass,name,name,integer,name,name,anyelement,boolean,boolean,regproc) line 102 at PERFORM`
this PR serves to raise exception on create_hypertable() under this condition.
---
`SELECT create_hypertable(temps); ALTER …
> [PG10] Handle already partitioned table on create_hypertable()

- src/chunk_constraint.c
- src/dimension_slice.c
Fixes problem with insert on 32bit architecture. Fixes #336.
> Fixes insert for 32bit architecture

- bootstrap
Thanks @sztanpet for pointing this out (let us know if this works for you)
> Fix bootstrap script to correctly name SRC_DIR

- test/sql/updates/setup.sql
- test/sql/updates/test-0.1.1.sql
- test/sql/updates/test-rerun.sql
Adds a FK constraint, check constraint, and exclusion constraint to the
update test.
> Improve updated test

- src/chunk.c
Chunk creation needs to be serialized in order
to avoid having multiple processes trying to
create the same chunk and causing conflicts.
This serialization didn't work as expected, because
a lock on the chunk catalog table that implemented
this serialization was prematurely released.
This change fixes that issue and also changes the
serialization to happen around a lock on the
chunk's parent table (the main table) instead. This
change should allow multiple processes to simultaneously
create chunks for different hypertables.
> Fix locking for serializing chunk creation

- src/process_utility.c
The compiler does not seem to like when I use the msvc enter/exit
guards for utils/guc.h, so the alternative is to grab the value
via GetConfigOptionByName.
> Fix an unexported GUC for Windows

- src/loader/loader.c
Previously, there was a case involving cache invalidation when
the extension could be preloaded. Namely the following happened:
1) extension_check (outer) was called and found loaded = true.
2) While the extension_check was checking the state of the extension
a cache invalidation callback happened.
3) The cache invalidation callback called extension_check (inner).
4) The inner extension_check loads the extension and sets
loaded = true.
5) The outer extension_check also loads the extension after the
cache invalidation callback returns. This happens because it
never re-checks the value of loaded.
This commit adds another check of loaded just before it is changed
to prevent this situation.
> Fix double-loading of extension

- src/hypertable.c
- src/tablespace.c
This fixes a few issues that manifest themselves mostly on 32-bit platforms, like ARM.
> Fixes for various bugs that show up on 32-bit platforms

- .travis.yml
- CMakeLists.txt
- README.md
This pull request is meant to integrate code coverage report generation through codecov.io. 
I am not sure this actually works yet but am creating a pull request to trigger travis build and will fix all the issues that arise here.
> integrate code coverage through codecov.io

- src/cache.c
Cache pins are allocated on the CacheMemoryContext in order to survive
subtransactions, and, optionally, main transactions (in case of, e.g.,
clustering or vaccuming). However, cache pins that are released also
needs to free memory on the CacheMemoryContext in order to avoid
leaking memory in a session.
This change ensures cache pin memory is freed when a cache pin is
released. It also allocates cache pins on a separate memory context,
which is a child of the CacheMemoryContext. This separate memory
context makes it easier to track the memory used by cache pins and
also release it when necessary.
Fixes issue https://github.com/timescale/timescaledb/issues/573, introduced in PR https://github.com/timescale/timescaledb/pull/467
> Release cache pin memory

- .travis.yml
- scripts/test_memory_spikes.py
Testing with Travis to see if test runs as expected.
> added memory spike test for random inserts

- src/hypertable.c
This refactor does three things:
1) Upgrades the lock taken to AccessExclusive. This is
to prevent upgrading locks during data migration.
2) Explicitly release lock in the IF NOT EXISTS case.
This is more inline with what PG itself does. Also,
optimize the easy IF NOT EXISTS case.
3) Exposes a rel inside create_hypertable itself
so that checks can use one rel instead of opening and closing
a bunch of them.
> Refactor create_hypertable rel access.

- test/expected/create_hypertable.out
- test/sql/create_hypertable.sql
This makes sure that tables created OF type work as hypertables.
It also makes sure that ALTER table command related to OF work
correctly.
> Add tests for table OF type

- .travis.yml
- scripts/docker-run-memory-test.sh
Added scripts and Travis cron job to test if out of order inserts cause memory spikes.
> Add memory spike test for out of order inserts

- .travis.yml
Force memory tests to run when pushing to prelease_test branch in
addition to cron. This allows us to run a these tests explicitly.
> Add prelease_test branch testing in travis

- src/dimension.h
- src/subspace_store.c
This fixes a number of formatting issues that were captured by
pgindent.
> Fix formatting issues

- bootstrap
> Update bootstrap to check for cmake and exit if not found

- scripts/docker-run-abi-test.sh
The previous fix did not actually include openssl-dev when trying
to build TimescaleDB. Also, this fixes broken tests due to lack
of permissions.
> Fix ABI test, correctly this time 

- test/src/bgw/log.c
This PR adds a signal block while writing to the log table
in our tests. This improves test reliability since messages
that get generated during signal handling are no longer lost
if the signal is received while another log message is being commited.
> Block signals when writing to the log table in tests

- src/loader/bgw_launcher.c
SIGTERM/SIGINT shouldn't cause an exit in the handler functions as you might interrupt something important (like having a spinlock etc)
Instead, we should only set vars in the handler functions, then handle them in a separate function built for that purpose.
> Handle SIGTERM asynchronously

- src/bgw/scheduler.c
- src/chunk_constraint.c
- src/dimension.c
- src/dimension_slice.c
- src/plan_add_hashagg.c
Hi,
Again trivial stuff, missing () and so on.
Regards
Didier
> Macros hardening

- bootstrap
- scripts/docker-build.sh
- scripts/docker-run-abi-test.sh
- scripts/docker-run-memory-test.sh
- scripts/docker-run-tests.sh
- scripts/docker-run.sh
- scripts/generate_typedefs.sh.in
- scripts/run_sql.sh
- scripts/start-test-docker.sh
- scripts/test_update_from_tag.sh
- scripts/test_updates_no_constraints.sh
- scripts/test_updates_with_constraints.sh
- scripts/ts_dump.sh
- scripts/ts_restore.sh
- test/pg_isolation_regress.sh
- test/pg_regress.sh
> Use /usr/bin/env bash instead of hardcoded path for bash in scripts

- src/chunk_adaptive.c
We want it to be clear that the adaptive chunking feature is
currently in beta, so a notice at the top of the C file should
suffice even if the user does not see the docs. Also while I was
there I commented some of the functions without comments.
> Update code comments in adaptive chunking; mark as beta

- src/hypertable.c
As per discussion in https://github.com/timescale/docs.timescale.com-content/pull/42
> Change case of timescaledb.restoring to be consistent with docs

- src/version.c
`snprint` has different behavior on some windows versions than on unix.
This commit replaces the `snprintf` version with one that uses `sscanf`,
which behaves the same on all platforms. (This is a higher priority
commit than it would appear, since we're tracking down a stack-overflow,
and this is one of the candidates for the cause)
Requesting reviews by @amytai since she owns the version-checking code and @erimatnor since he wrote the last version of the version_parse code.
> Fix version_parse on windows

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Release 1.0.1

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/1.0.0--1.0.1-dev.sql
- sql/updates/1.0.1--1.1.0-dev.sql
- version.config
Brings the changelog changes and re-orgs the update files correctly.
> Release 1.0.1 on master, prepare for 1.1.0-dev

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Release 1.1.1

- scripts/test_updates.sh
This fixes a number of issues with the update test script that
prohibited it from displaying a log of any failing tests. In
particular, the script needs to be run with `set +e` to ensure a test
error doesn't immediately cause an exit without recording the failed
log.
> Do not exit immediately on failure in update test script

- src/telemetry/telemetry.c
should be `apache_only` not `ApacheOnly`
> Fix casing in telemetry

- src/bgw/job.c
We currently do not have a parallel worker context in out BGW
and we wouldn't want our BGW to start parallel workers anyway
in order to conserve resources. This commit disables parallel
workers in BGW jobs.
> Disable parallel workers in background workers

- tsl/src/license.c
> Clean error handling for invalid licenses

- src/loader/bgw_launcher.c
- src/loader/bgw_message_queue.c
We do cleanup for bgw_message_queue in the before_shmem_exit function,
but we were registering said function after initializing the database
hashtable. When bgw_launcher would crash in middle of populating the
hashtable, this would cause issues as the bgw_message_queue wouldn't be
reset, and the launcher would fail to restart as it would think that
another launcher was running. This commit moves the hook registering to
before we touch any of the state that the hook cleans up, in order to
ensure that the state will be cleaned regardless of where the failure
occurs. This is already safe for the bgw_message_queue since that
function validates that the caller owns the queue before altering it,
and is made safe for the hashtable via an additional level of
indirection, so we can check if the …
> Fix bgw_launcher restart when failing during launcher setup

- src/plan_ordered_append.c
When an index is not available on all chunks pathkeys of the child
might not match pathkeys of the MergeAppendPath, PostgreSQL fixes
this when creating the merge append plan by inserting a sort node
for the child. Unfortunately this is too late for us so we don't do
this optimization for those cases for now.
> Bail on ordered append when pathkeys don't match

- test/expected/parallel-10.out
- test/expected/parallel-11.out
- test/expected/parallel-9.6.out
- test/sql/parallel.sql.in
I offset the generated data by 1 to align with the chunk boundaries
> Use hypertable for parallel tests

- CHANGELOG.md
And a "thanks" to @skebanga for finding a loader bug we missed.
> Add warning about restarting loader for this release

- src/loader/bgw_launcher.c
- tsl/src/gapfill/exec.c
- tsl/src/gapfill/interpolate.c
Also fixes a typo in bgw error message.
> Improve error handling for unsupported datatypes

- tsl/src/gapfill/exec.c
- tsl/src/gapfill/planner.c
- tsl/test/expected/gapfill.out
- tsl/test/sql/gapfill.sql
Infer time_bucket_gapfill start and finish arguments from
WHERE clause when they are not supplied as arguments.
> Infer time_bucket_gapfill arguments from WHERE clause

- sql/chunk.sql
- src/chunk.c
- test/expected/chunk_utils.out
- test/sql/chunk_utils.sql
This will be useful for some in-progress projects.
> Add function to determine the chunk for a given row

- src/constraint_aware_append.c
The PR for transforming cross datatype comparisons was
merged with 2 changes missing. This patch changes the
DATATYPE_PAIR macro to include the variables it compares
against and improves the check for Var position in the
expression the transformation is applied on.
> Add better validation for datatype chunk exclusion

- test/sql/CMakeLists.txt
@svenklemm this should fix the bug you noticed
> c_unit_tests.sql are debug-only tests, the contents are meaningless otherwise

- tsl/src/gapfill/planner.c
When building the new targetlist expressions for WindowAggPath
the sortgrouprefs of the PathTarget where not properly adjusted.
This patch creates a new PathTarget for every WindowAggPath
so sortgrouprefs of the PathTarget is valid.
> Fix gapfill sanitizer bugs

- src/plan_ordered_append.c
- src/planner.c
This patch changes the ordered append behavior to no longer replace
MergeAppendPath with AppendPath but instead leave the original
MergeAppendPath in place and add the ordered AppendPath as a new path.
> Leave MergeAppendPath in pathlist for ordered append

- src/planner.c
This patch changes the ordered append path creation to not
happen when iterating over the pathlist because add_path modifies
the pathlist and can remove more expensive pathes when a new
path is added that is cheaper.
> Fix ordered append sanitizer failures

- appveyor.yml
Appveyor is updating the image they use to provide docker.
This commit updates our appveyor config to use it.
> Update appveyor.yml for new build image

- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/continuous_aggs.sql
Just a sanity check to make sure they work correctly.
> Test continuous aggregates with space partitions

- test/expected/views.out
- test/sql/views.sql
Add ORDER BY clause to views test to make result of the test
consistent
> Add missing ORDER BY clause to views test

- CHANGELOG.md
This commit build out the release notes for 1.3.0.
> Improve 1.3.0 release notes

- CHANGELOG.md
Improves wording and fixes nits.
> Fix nits in release 1.3.0 notes

- src/process_utility.c
In PG11 the relation field in a VacuumStmt can be NULL, and is only
supposed to be used if the oid field is not valid. This commit changes
to prefer the oid field, and adds a check that relation is not NULL.
potential fix for issue #1219
> Fix segfault in VACUUM on PG11

- scripts/docker-run-abi-test.sh
This fix makes the smoke test return the correct exit code. It also
adds libssl1.0, which is needed for some openssl functionality.
> Fix ABI smoke test

- src/constraint_aware_append.c
Postgres introduced a change in commit `e7eed0` that sometimes
creates a Result node above an append/mergeappend node. This commit
makes sure that our constraint aware node logic is compatible with
this change in behavior.
> Handle plan node changes in upstream Postgres

- src/chunk_append/CMakeLists.txt
- src/chunk_append/chunk_append.c
- src/chunk_append/chunk_append.h
- src/chunk_append/exec.c
- src/chunk_append/exec.h
- src/chunk_append/explain.c
- src/chunk_append/explain.h
- src/chunk_append/planner.c
- test/expected/agg_bookends_optimized-10.out
- test/expected/agg_bookends_optimized-11.out
- test/expected/agg_bookends_optimized-9.6.out
- test/expected/append.out
- test/expected/multi_transaction_index.out
- test/expected/plan_expand_hypertable-10.out
- test/expected/plan_expand_hypertable-11.out
- test/expected/plan_expand_hypertable-9.6.out
- test/expected/plan_ordered_append-10.out
- test/expected/plan_ordered_append-11.out
- test/expected/plan_ordered_append-9.6.out
- test/expected/sql_query-10.out
- test/expected/sql_query-11.out
- test/expected/sql_query-9.6.out
- test/expected/sql_query_results_optimized-10.out
- test/expected/sql_query_results_optimized-11.out
- test/expected/sql_query_results_optimized-9.6.out
- test/expected/sql_query_results_x_diff-10.out
- test/expected/sql_query_results_x_diff-11.out
- test/expected/sql_query_results_x_diff-9.6.out
- test/sql/include/plan_ordered_append_load.sql
- test/sql/include/plan_ordered_append_query.sql
Change EXPLAIN output to include the order if its an ordered append
> Improve ChunkAppend explain

- CHANGELOG.md
> Update release notes for 1.3.1

- sql/CMakeLists.txt
- sql/updates/1.3.0--1.3.1.sql
- version.config
> Release 1.3.1

- .travis.yml
Get rid of the PG_GIT_TAG and instead only rely on PG_VERSION.
Download the postgres source based on the definition in the docker
file.
> Improve travis config definitions

- scripts/test_updates_pg10.sh
- scripts/test_updates_with_constraints.sh
- test/sql/updates/post.continuous_aggs.sql
- test/sql/updates/post.v3.sql
- test/sql/updates/setup.continuous_aggs.sql
- test/sql/updates/setup.v3.sql
Add a v3 update test that makes sure that continuous aggregates
continue to work after extensions are updated.
> Test continuous aggs with extension updates

- CHANGELOG.md
> Update release notes for 1.3.2

- tsl/src/continuous_aggs/insert.c
We use the InvalidationThreshold as a barrier to ensure that all transactions see an invalidation threshold. Upon transaction commit, all transactions grab a lock on said table, while during the first phase of materialization, the materializer grabs an AccessExclusive lock on the table. This is supposed to ensure that all INSERT/UPDATE/DELETEs are ordered strictly before or after the first phase of materialization, and thus any mutations to newly materialized data will be part the new materialization, or append an invalidation. Unfortunately, the scanner does not hold its locks until the end of the transaction, and since that was the only manner we were taking a lock on the InvalidationLog in mutations, it was not functioning as a barrier. To fix this, we now take an explicit lock.
> Fix potentially lost invalidations in continuous aggs

- appveyor.yml
- sql/CMakeLists.txt
- sql/updates/1.3.1--1.3.2.sql
- sql/updates/latest-dev.sql
- version.config
> Release 1.3.2

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/catalog.c
- src/catalog.h
- src/continuous_agg.c
- test/expected/drop_rename_hypertable.out
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/materialize.c
- tsl/src/continuous_aggs/materialize.h
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_ddl-10.out
- tsl/test/expected/continuous_aggs_ddl-11.out
- tsl/test/expected/continuous_aggs_ddl-9.6.out
- tsl/test/expected/continuous_aggs_multi.out
- tsl/test/isolation/expected/continuous_aggs_insert.out
- tsl/test/isolation/expected/continuous_aggs_multi.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/continuous_aggs_insert.spec
- tsl/test/isolation/specs/continuous_aggs_multi.spec
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/continuous_aggs.sql
- tsl/test/sql/continuous_aggs_ddl.sql.in
- tsl/test/sql/continuous_aggs_multi.sql
- tsl/test/src/test_continuous_aggs.c
Support for multiple continuous aggregates on a hypertable
> Support for multiple continuous aggregates

- src/chunk_append/exec.c
Move ChunkAppend selection of next subplan into separate function
> Refactor ChunkAppend plan selection

- CHANGELOG.md
- src/bgw/launcher_interface.c
- src/chunk_append/chunk_append.c
- src/chunk_append/chunk_append.h
- src/chunk_append/exec.c
- src/chunk_append/exec.h
- src/chunk_append/explain.c
- src/guc.c
- src/guc.h
- src/loader/CMakeLists.txt
- src/loader/bgw_interface.c
- src/loader/loader.c
- src/loader/lwlocks.c
- src/loader/lwlocks.h
- src/planner.c
- test/expected/append-10.out
- test/expected/append-11.out
- test/expected/append-9.6.out
- test/expected/parallel-10.out
- test/expected/parallel-11.out
- test/expected/parallel-9.6.out
- test/sql/include/append_load.sql
- test/sql/include/append_query.sql
- test/sql/parallel.sql.in
This patch makes ChunkAppend parallel aware allowing ChunkAppend
to coordinate parallel workers.
> Make ChunkAppend parallel aware

- scripts/suppressions/suppr_leak.txt
- src/bgw/job.c
- src/loader/bgw_launcher.c
- src/loader/bgw_message_queue.c
- test/sql/.gitignore
- test/src/bgw/scheduler_mock.c
- tsl/src/license.c
This series of commits fix memory leaks across the database.
Note that the PR is still WIP, more commits may be added if more leaks are found.
> Memory leak fixes

- src/process_utility.c
- test/expected/alter.out
- test/sql/alter.sql
This patch unblocks setting reloptions on chunks.
> Allow setting reloptions on chunks

- .travis.yml
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/sql/bgw_reorder_drop_chunks.sql
Changes the PR tests to run against 9.6.15, 10.10 and 11.5
> Bump the postgres version PR tests run against

- src/telemetry/telemetry.c
Fix telemetry logic for ARM32.
> Fix telemetry for ARM32

- scripts/test_sanitizers.sh
The `test_sanitizer.sh` test failed because source code was being
copied from the host to the container as user `postgres` and this user
did not have read permissions on the mounted directory. This is fixed
by copying the files as `root` and then changing the owner to
`postgres`.
The commit also removes `wait_for_pg` since PostgreSQL server status is
not relevant for the tests since they start their own temporary
instance and switches to use here-is documents for execution purely for readability reasons.
> Fix permission issue in test_sanitizer

- .travis.yml
- scripts/test_updates_pg11.sh
- sql/updates/1.4.2--1.5.0.sql
- sql/updates/latest-dev.sql
- test/sql/updates/post.v4.sql
- test/sql/updates/setup.v4.sql
Change travis to to run update tests on PG11
> Fix bad SQL updates from previous updates.

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/transparent_decompression-10.out
- tsl/test/expected/transparent_decompression-11.out
- tsl/test/sql/include/transparent_decompression_ordered_index.sql
- tsl/test/sql/include/transparent_decompression_query.sql
- tsl/test/sql/transparent_decompression.sql.in
> Add join info to compressed chunk

- CHANGELOG.md
- sql/updates/latest-dev.sql
- sql/views.sql
- tsl/test/expected/continuous_aggs_usage.out
Add ignore_invalidation_older_than parameter to
timescaledb_information.continuous_aggregates view
Fixes #1664
> Add ignore_invalidation_older_than to view

- src/copy.c
When doing a migrate of table data to a hypertable during a call of
create_hypertable, any error, including an interrupt signal, would cause the signal handling to
call `CopyFromErrorCallback` which would read garbage data because a
heap scan descriptor is read as if it was a `CopyState` structure.
This commit fixes that by not adding a new context to the error context
stack when migrating data.
Fixes #1651
> Fix crash when interrupting create_hypertable

- src/bgw/job_stat.c
- src/cache_invalidate.c
Reviwers:
commit messages describe the specific changes.
> Fix miscellaneous bgw issues

- tsl/src/continuous_aggs/materialize.c
Uninitialized variable error with cc.
> Fix compiler error

- src/chunk.c
This commit fixes chunk_scan_find to not return chunks that are
marked as dropped, since the callers don't expect such chunks to be returned as found.
> Treat dropped chunks as not found

- .github/CODE_OF_CONDUCT.md
Create file that points to Timescale Code of Conduct on webpage
> Point to Timescale Code of Conduct

- sql/views.sql
- test/sql/views.sql
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
Updates and replaces https://github.com/timescale/timescaledb/pull/1811 with suggested changes.
> Ignore dropped chunks in compressed_chunk_stats

- scripts/test_updates_pg10.sh
- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
- scripts/test_updates_pg96.sh
Needs published docker images to pass CI
> Add 1.7.1 to update test scripts

- tsl/src/deparse.c
- tsl/test/expected/dist_hypertable_am.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_hypertable_am.sql
This PR adds support for CREATE TABLE USING clause and includes
it for tables created on the data nodes.
> Support table access methods for distributed hypertables

- .github/workflows/linux-build-and-test.yaml
- scripts/export_prefix_check.sh.in
- scripts/gh_matrix_builder.py
- test/isolation/specs/bgw_job_delete.spec.in
- test/isolation/specs/deadlock_dropchunks_select.spec
- test/isolation/specs/multi_transaction_indexing.spec
- test/isolation/specs/read_committed_insert.spec
- test/isolation/specs/read_uncommitted_insert.spec
- test/isolation/specs/repeatable_read_insert.spec
- test/isolation/specs/serializable_insert.spec
- test/isolation/specs/serializable_insert_rollback.spec
- tsl/test/isolation/expected/compression_ddl.out
- tsl/test/isolation/expected/continuous_aggs_insert.out
- tsl/test/isolation/specs/compression_ddl.spec
- tsl/test/isolation/specs/continuous_aggs_insert.spec
- tsl/test/isolation/specs/reorder_vs_insert.spec.in
- tsl/test/isolation/specs/reorder_vs_insert_other_chunk.spec.in
- tsl/test/isolation/specs/reorder_vs_select.spec.in
Some checks are commented out atm to make debugging quicker will reenable those before pushing
> Add mac os regression test to GitHub Actions

- .github/workflows/linux-build-and-test.yaml
This patch adds local variables to github action stacktraces to
add more context and make investigating issues easier.
> Include local variables in github action stacktrace

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/bgw/job.c
- src/bgw/job.h
- src/catalog.h
- src/jsonb_utils.c
- src/jsonb_utils.h
- test/expected/bgw_db_scheduler.out
- test/sql/bgw_db_scheduler.sql
- test/src/bgw/scheduler_mock.c
- tsl/src/bgw_policy/compress_chunks_api.c
- tsl/src/bgw_policy/drop_chunks_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/continuous_aggs/job.c
- tsl/test/expected/bgw_policy.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/compress_bgw_reorder_drop_chunks.out
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/tsl_tables.out
This patch adds the columns required for custom jobs to the bgw_job
catalog table.
> Change bgw_job catalog table to enable custom jobs

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- src/catalog.c
- src/catalog.h
- src/hypertable.c
Reorder schema_name + table_name index. Remove
unnecessary constraint.
> Cleanup index on hypertable catalog table

- sql/views.sql
- test/expected/pg_dump.out
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
Add informational view that lists the settings
used while enabling compression on a hypertable.
> Add compression settings view

- sql/views.sql
- test/expected/pg_dump.out
- test/expected/views.out
- test/sql/views.sql
- tsl/test/expected/dist_compression.out
- tsl/test/sql/dist_compression.sql
timescaledb_information.chunks and dimensions view show metadata
related to chunks and hypertable dimensions
> Add chunks and dimensions view

- scripts/gh_matrix_builder.py
Switches MacOS test in PR to run release, so the build time is
reduced. Adds the test in Debug to scheduled job.
> Test both debug and release on MacOS in CI

- tsl/src/bgw_policy/compression_api.c
- tsl/test/expected/compression_bgw.out
- tsl/test/sql/compression_bgw.sql
The policy is called compression now and this fixes error messages.
> Fix error messages to compression policy

- .github/workflows/update-test.yaml
- scripts/test_update_from_tag.sh
- sql/updates/latest-dev.sql
- test/sql/updates/post.policies.sql
- test/sql/updates/setup.policies.sql
- test/sql/updates/setup.v6.sql
- test/sql/updates/test-rerun.sql
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/continuous_aggs/job.c
- tsl/test/expected/bgw_policy.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/compress_bgw_reorder_drop_chunks.out
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/tsl_tables.out
This patch adds policies to the update test to ensure their
configuration is properly migrated during updates.
> Add policies to update test

- tsl/test/expected/dist_api_calls.out
- tsl/test/sql/dist_api_calls.sql
Related to: https://github.com/timescale/timescaledb/issues/1902
> Add distributed hypertable support to hypertable_approximate_row_count()

- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
> Fix segfaults in caggs on 32-bit systems

- tsl/src/bgw_policy/compression_api.c
- tsl/test/expected/dist_compression.out
- tsl/test/sql/dist_compression.sql
> Block compression policy with dist hypertable

- src/process_utility.c
- test/expected/alter.out
- test/sql/alter.sql
Fix a segfault in ALTER VIEW when trying to SET view options
on normal postgres views.
> Fix segfault in ALTER VIEW SET

- sql/views.sql
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/continuous_aggs_bgw.out
Update policy_stats view to make it more end user
friendly. These changes mirror the fields in
continuous_aggregate_stats.
> Update policy_stats view with additional fields

- sql/views.sql
- test/expected/pg_dump.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_usage.out
- tsl/test/sql/continuous_aggs_bgw.sql
- tsl/test/sql/continuous_aggs_usage.sql
Reviewers:
see continuous_aggs_bgw.sql on how to query stats for continuous aggregates
> Remove continuous_aggregate_stats view

- tsl/src/continuous_aggs/Readme.md
The README that gives an overview of the implementation of continuous
aggregates is updated to reflect changes to the feature.
Fixes #2147
> Update README for continuous aggregates

- tsl/LICENSE-TIMESCALE
* Add right-to-repair
* Add right-to-improve
* Remove Enterprise tier
* Remove Usage Limits from Community
* Other rights and simplifications
> Update Timescale License

- sql/updates/latest-dev.sql
Commit 8e1e6036 changed chunk compression to disable autovacuum
on compressed chunks but did not apply the setting to chunks
compressed before that change. So this patch changes chunks
compressed with previous version to disable autovacuum as well.
> Set autovacuum_enabled to false for compressed chunks

- sql/views.sql
- test/expected/pg_dump.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/sql/bgw_reorder_drop_chunks.sql
- tsl/test/sql/continuous_aggs_bgw.sql
Rename policy_stats view to job_stats
> Rename policy_stats view

- .github/workflows/alpine-32bit-build-and-test.yaml
- appveyor.yml
- scripts/gh_matrix_builder.py
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/policy_utils.c
- tsl/src/bgw_policy/policy_utils.h
- tsl/test/expected/continuous_aggs_bgw.out
- tsl/test/expected/continuous_aggs_policy.out
- tsl/test/sql/continuous_aggs_policy.sql
Add check to verify that start_interval >
end_interval specified by the refresh continuous
aggregate policy
> Check start > end for refresh policy

- tsl/src/chunk_api.c
> Fix member access within misaligned address in chunk_update_colstats

- src/partitioning.c
- src/process_utility.c
- test/expected/index.out
- test/sql/index.sql
- tsl/src/remote/dist_copy.c
> Fix index creation on hypertables with dropped columns

- tsl/src/remote/dist_copy.c
Switch to postgres builtin functions for converting from host to
network byte order since those are better optimized.
https://github.com/postgres/postgres/commit/510b8cbff15fcece246f66f2273ccf830a6c7e98
> Use postgres builtin hton functions

- src/cache_invalidate.c
Inside the `cache_invalidate_callback` the OID of the namespace is read
using `get_namespace_oid`, which usually goes to the cache. However, if
there is a cache miss inside that function, it will attempt to read the
OID from the heap, which involves invalidating the cache, which further
leads to `cache_invalidate_callback` being called recursively.
This commit prevent an infinite recursion by not doing a recursive call
and instead considering the cache invalidated. This will allow
`get_namespace_oid` (and other functions) to proceed with reading the
OID from the heap tables, fill in the cache, and return it to callers.
Closes #2143
> Stop recursion in cache invalidation

- tsl/src/compression/compression.c
This patch fixes a segfault in decompress_chunk for chunks with dropped
columns. Since dropped columns don't exists in the compressed chunk
the values for those columns were undefined in the decompressed tuple
leading to a segfault when trying to build the heap tuple.
> Fix segfault in decompress_chunk for chunks with dropped columns

- tsl/src/data_node.c
Initialize a boolean variable used to check for a compatible extension
on a data node. Leaving it uninitialized might lead to a potential
read of a garbage value and unpredictible behavior.
> Fix uninitialized variable in data node validation

- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
Add the latest release candidate to the update tests.
> Add 2.0.0-rc3 to update tests

- sql/updates/latest-dev.sql
- test/sql/updates/post.compression.sql
> Set metadata for chunks compressed before 2.0

- src/hypertable.c
- src/hypertable.h
- tsl/src/compression/create.c
- tsl/test/expected/dist_compression.out
- tsl/test/sql/dist_compression.sql
> Support disabling compression on distributed hypertables

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.0.0-rc4--2.0.0.sql
- sql/updates/latest-dev.sql
- version.config
With this release, we are officially moving TimescaleDB 2.0 to GA, 
concluding several release candidates.
TimescaleDB 2.0 adds the much-anticipated support for distributed 
hypertables (multi-node TimescaleDB), as well as new features and 
enhancements to core functionality to give users better clarity and 
more control and flexibility over their data.
Multi-node architecture:  In particular, with TimescaleDB 2.0, users 
can now create distributed hypertables across multiple instances of 
TimescaleDB, configured so that one instance serves as an access node 
and multiple others as data nodes. All queries for a distributed 
hypertable are issued to the access node, but inserted data and queries
are pushed down across data nodes for greater scale and performance.
Multi-node TimescaleDB can …
> Release 2.0.0

- .clang-format
- src/bgw/scheduler.c
- src/cache.c
- src/chunk_append/chunk_append.c
- src/chunk_append/exec.c
- src/compat.h
- src/import/planner.c
- src/plan_agg_bookend.c
- src/plan_expand_hypertable.c
- test/src/bgw/test_job_refresh.c
- tsl/src/continuous_aggs/create.c
- tsl/src/debug.c
- tsl/src/fdw/deparse.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/gapfill/planner.c
PG13 changes the List implementation from a linked list to an array
while most of the API functions did not change a few them have slightly
different signature in PG13, additionally the list_make5 functions
got removed.
https://github.com/postgres/postgres/commit/1cff1b95ab
> Add support for PG13 List implementation

- src/bgw/scheduler.c
PG13 changes the name of the list sorting function from list_qsort
to list_sort. Additionally PG13 does in-place sort.
https://github.com/postgres/postgres/commit/569ed7f483
> Adjust code to PG13 list sort changes

- src/planner.c
PG13 adds the query string as argument to the planner_hook.
https://github.com/postgres/postgres/commit/6aba63ef3e
> Adjust planner code to PG13 planner_hook signature change

- .travis.yml
- scripts/test_sanitizers.sh
- test/sql/updates/setup.v6-pg96.sql
Run tests on PG 12.6, 11.11, 10.16, 9.6.21
> Bump postgres versions used in CI (based on master repo)

- test/src/bgw/params.c
A backend is allowed to only do one dsm_attach call to attach to
any given dynamic shared memory segment (it needs to detach before
calling attach again). The code in params_open_wrapper took care of
calling it once. However the code in params_close_wrapper was doing an
unconditional dsm_detach everytime which can cause the dsm refcnt to go
down unnecessarily and was causing weird crashes
The fix is to track when we should be calling params_close_wrapper
instead of doing an unconditional detach always.
> Fix mismatched dsm_attach/dsm_detach calls

- tsl/src/bgw_policy/job.c
- tsl/test/expected/continuous_aggs_errors.out
- tsl/test/sql/continuous_aggs_errors.sql
> Fix segfault in job_config_check for cagg

- tsl/src/reorder.c
> Annotate fallthrough with TS_FALLTHROUGH

- .github/workflows/cron-tests.yaml
- scripts/docker-run-restore-points-test.sh
- scripts/test_restore_points.sh
Test PostgreSQL restore point recovery for single node and multi node cluster, make sure that single and multi node results match after recovery.
> Add script to test recovery using restore points

- scripts/test_updates_pg11.sh
- scripts/test_updates_pg12.sh
Cherry pick of https://github.com/timescale/timescaledb/pull/2973
> Add 2.1.0 to update test scripts

- src/process_utility.c
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
> Allow REINDEX TABLE to work on dist hypertables

- src/chunk.c
- src/chunk.h
Add 2 helper functions to modify status of a chunk
ts_chunk_add_status(Chunk *chunk, int status);
ts_chunk_set_status(Chunk *chunk, int status);
> Add functions to set chunk status

- src/time_bucket.c
> Error spelling

- sql/updates/latest-dev.sql
- src/chunk.c
- src/chunk.h
- src/utils.h
- test/sql/updates/post.catalog.sql
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/job.c
- tsl/src/compression/compress_utils.c
- tsl/src/compression/compress_utils.h
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/compression_errors.out
- tsl/test/expected/dist_compression.out
- tsl/test/sql/compression_bgw.sql
- tsl/test/sql/dist_compression.sql
Add distributed hypertable compression policies.
> compression policies on distributed hypertables

- src/chunk.c
- src/chunk.h
- src/nodes/chunk_insert_state.c
- src/nodes/chunk_insert_state.h
- tsl/src/compression/compress_utils.c
- tsl/src/compression/compression.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
Move CHUNK_STATUS_UNORDERED into C file and add setter and getter.
> Add setter for CHUNK_STATUS_UNORDERED

- docs/BuildSource.md
Issue #2779 introduced support for PostgreSQL 13
> Added Postgres 13 prerequisites for compilation

- tsl/test/expected/compression_insert-11.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/sql/compression_insert.sql.in
Add tests for conditional triggers and triggers that abort INSERT
when inserting into compressed chunk.
> Add more trigger tests for insert into compressed chunk

- src/bgw/scheduler.c
- src/catalog.c
- src/chunk.c
- src/dimension.c
- src/hypertable.c
- src/loader/bgw_launcher.c
- src/loader/loader.c
- src/partitioning.c
- tsl/src/compression/create.c
- tsl/src/continuous_aggs/create.c
PG14 removes StrNCpy and some Name helper functions.
https://github.com/postgres/postgres/commit/1784f278a6
> Replace StrNCpy with strlcpy

- .github/workflows/code_style.yaml
- test/perl/TimescaleNode.pm
Add a run of `perltidy` to make sure that all the Perl code is
correctly formatted. Also fix the formatting of one file that did not
follow the style in `scripts/perltidyrc`.
> Add Perl code check GitHub action

- src/chunk.c
Two insert transactions could potentially try
to update the chunk status to unordered. This results in
one of the transactions failing with a tuple concurrently
update error.
Before updating status, lock the tuple for update, thus
forcing the other transaction to wait for the tuple lock, then
check status column value and update it if needed.
> Fix locking issue when updating chunk status

- test/sql/updates/cleanup.continuous_aggs.v2.sql
- test/sql/updates/setup.catalog.sql
Corrected a function name and replaced a variable with the explicit
commands to use.
> Fix issues in update smoke test

- sql/pre_install/schemas.sql
- sql/updates/latest-dev.sql
This commit adds an experimental schema where experimental features can
be added.
> Add experimental schema

- tsl/src/remote/connection_cache.c
Fix heap buffer overflow in remote connection cache.
Fixes #3315
> Fix memory overflow

- .github/workflows/sanitizer-build-and-test.yaml
- scripts/export_prefix_check.sh.in
- scripts/suppressions/suppr_leak.txt
- scripts/suppressions/suppr_ub.txt
Change sanitizer test to run on PG12 and make it use the same
infrastructure as the other linux regression tests.
> Run sanitizer tests on PG12

- CMakeLists.txt
The variable `VERSION_MOD` is used by `config.h`.
> Fix version modifier

- src/time_bucket.c
- test/expected/timestamp.out
- test/sql/timestamp.sql
Also make the code more explicit about handling 'infinity' values.
> Improve test coverage of time_bucket_ng()

- CMakeLists.txt
Removing some debug printouts and moving some other status messages to
more appropriate locations.
> Remove CMake debug printouts

- .github/workflows/apt-packages.yaml
- .github/workflows/homebrew.yaml
- .github/workflows/rpm-packages.yaml
> Test Apache-only packages in CI

- tsl/src/continuous_aggs/insert.c
- Stop CAGG trigger memory context from crashing by changing its lifetime.  
- Add more cases to transaction callback handling to cover parallel workers as well.
- Force distributed hypertable members to always append invalidation entries in the corresponding tables residing in the data nodes.
> Fix CAGG distributed invalidation path

- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
> Add downgrade test to APT tests

- .github/workflows/rpm-packages.yaml
- src/compat/compat.h
- src/estimate.c
- tsl/src/fdw/estimate.c
PG14 adds an additional argument to estimate_num_groups to
allow passing back additional information about the estimation.
https://github.com/postgres/postgres/commit/ed934d4fa3
> Adjust estimate_num_groups calls to PG14 changes

- src/chunk_append/chunk_append.c
- src/compat/compat.h
- src/compression_with_clause.c
- src/copy.c
- src/copy.h
- src/import/allpaths.c
- src/nodes/chunk_dispatch_state.c
- src/plan_expand_hypertable.c
- src/process_utility.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/nodes/data_node_dispatch.c
- tsl/src/nodes/skip_scan/planner.c
- tsl/src/remote/dist_copy.c
- tsl/src/reorder.c
PG14 removes partitioned_rels from create_append_path and
create_merge_append_path
https://github.com/postgres/postgres/commit/f003a7522b
> Adjust code to PG14 append changes

- src/compat/compat.h
- src/loader/loader.c
- src/plan_add_hashagg.c
- test/src/loader/init.c
- tsl/src/fdw/estimate.c
PG14 adds an argument to post_parse_analyze_hook
https://github.com/postgres/postgres/commit/5fd9dfa5f5
> Adjust code to PG14 post_parse_analyze_hook changes

- appveyor.yml
- src/loader/loader.c
- src/process_utility.c
- src/process_utility.h
PG14 adds an additional readOnlyTree argument to the process utility
hook.
https://github.com/postgres/postgres/commit/7c337b6b
> Adjust code to processutility hook API change

- tsl/src/fdw/fdw.c
PG14 changes the signature of AddForeignUpdateTargets and the method
it must use for adding junk columns to the query.
https://github.com/postgres/postgres/commit/86dc9005
> Adjust code to PG14 FDW API changes

- tsl/src/bgw_policy/job.c
PG14 changes LookupFuncName to longer match procedures but only
functions. The only place where we actually expected to match
procedures is the bgw. This patch changes bgw job lookup to
use LookupFuncWithArgs which can return both functions and
procedures depending on the requested object type.
https://github.com/postgres/postgres/commit/e56bce5d
> Use LookupFuncWithArgs in bgw job lookup

- src/import/planner.c
Update prepare_sort_from_pathkeys postgres import according to
PG13 and PG14 changes. This also backports find_ec_member_matching_expr
and find_computable_ec_member to PG12 where those are missing.
> Update prepare_sort_from_pathkeys import

- sql/size_utils.sql
Simplify the CTE to recursively inspect all partitions of a relation
and calculate the sum of `pg_class.reltuples` taking in account the
differences introduced by PG14.
> Refactor SQL function approximate_row_count

- src/copy.c
- src/hypertable.c
- src/import/allpaths.c
- src/nodes/chunk_dispatch.c
- src/nodes/chunk_dispatch_plan.c
- src/nodes/chunk_dispatch_state.c
- src/nodes/chunk_dispatch_state.h
- src/nodes/chunk_insert_state.c
- src/nodes/hypertable_insert.c
- src/plan_expand_hypertable.c
- tsl/src/debug.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/nodes/data_node_dispatch.c
There are more changes required to adjust our code to the insert path changes but i pulled this PR out to keep the mechanical changes separate from the actual refactoring to make reviewing easier.
> PG14 ModifyTablePath struct change

- tsl/src/continuous_aggs/refresh.c
Disable per-data-node optimization so that 'tableoid' system column is evaluated in the Access Node to generate Access Node chunk-IDs for the materialization table.
> Disable per data node queries in distributed CAGG

- .github/workflows/linux-build-and-test.yaml
- scripts/gh_matrix_builder.py
- test/expected/agg_bookends-14.out
- test/expected/append-14.out
- test/expected/cluster-14.out
- test/expected/constraint-14.out
- test/expected/copy-14.out
- test/expected/ddl-14.out
- test/expected/delete-14.out
- test/expected/insert-14.out
- test/expected/partitionwise-14.out
- test/expected/plan_expand_hypertable-14.out
- test/expected/plan_hypertable_inline-14.out
- test/expected/rowsecurity-14.out
- test/expected/update-14.out
- test/sql/.gitignore
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/continuous_aggs_query-14.out
- tsl/test/expected/continuous_aggs_union_view-14.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/jit-14.out
- tsl/test/expected/plan_skip_scan-14.out
- tsl/test/expected/remote_copy-14.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/expected/generated_columns-14.out
- tsl/test/shared/expected/ordered_append-14.out
- tsl/test/shared/expected/ordered_append_join-14.out
- tsl/test/sql/.gitignore
This only adds the infrastructe for running make installcheck on PG14 we still need the INSERT and UPSERT fixes for PG14 merged to master for these tests to pass.
> Add PG14 to our CI

- CHANGELOG.md
- src/process_utility.c
- test/expected/constraint-12.out
- test/expected/constraint-13.out
- test/expected/constraint-14.out
- test/sql/constraint.sql.in
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
Don't get too hyped, it's a simple change ;)
> Fix typo in error message

- sql/updates/latest-dev.sql
- tsl/test/shared/expected/continuous_aggs_compression-12.out
- tsl/test/shared/expected/continuous_aggs_compression-13.out
- tsl/test/shared/expected/continuous_aggs_compression-14.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/continuous_aggs_compression.sql.in
- tsl/test/shared/sql/include/continuous_aggs_compression_query.sql
- tsl/test/shared/sql/include/continuous_aggs_compression_setup.sql
Add regression tests for caggs+compression
> Add regression tests for caggs+compression

- .github/workflows/coccinelle.yaml
- coccinelle/README.md
- coccinelle/heap_freetuple.cocci
- scripts/coccinelle.sh
This patch adds a workflow to run coccinelle scripts against our
codebase. This can be used to find errors in the code base.
The initial patch adds a check to find unbalanced heap_form_tuple
heap_freetuple occurances.
https://coccinelle.gitlabpages.inria.fr/website/
> Add coccinelle workflow to CI

- CHANGELOG.md
- tsl/src/fdw/deparse.c
- tsl/test/shared/expected/dist_distinct_pushdown.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_distinct_pushdown.sql
- tsl/test/shared/sql/include/shared_setup.sql
Fixes https://github.com/timescale/timescaledb/issues/3784
> Fix DISTINCT ON pushdown

- CHANGELOG.md
- tsl/src/remote/connection.c
> Fix NULL pointer evaluation in fill_result_error()

- .github/ISSUE_TEMPLATE/enhancement.yml
Add an issue template for "Enhancement" requests. An enhancement is an
improvement to an existing feature or functionality. The user must
pick from a set of features or subsystems to improve.
> Add enhancement issue template

- .github/ISSUE_TEMPLATE/feature.yml
The feature request issue template adds a form for people to fill out
so that we can ensure we get the information we need.
> Add a feature request issue template

- tsl/src/continuous_aggs/create.c
- tsl/src/deparse.c
- tsl/src/deparse.h
Add deparser for CreateTrigStmt to use for distributed hypertables.
Fixes #3825
> Add deparser for CreateTrigStmt

- src/sort_transform.c
This is more explicit, and looking up the function name each time has a
performance impact.
Part of https://github.com/timescale/timescaledb/pull/3890
> Use function oids instead of names when transforming the sort keys

- src/loader/loader.c
It appears as though this comment had a run-in with auto-formatting
which left it somewhat mangled.
> Fix weirdly formatted comment

- cmake/ScriptFiles.cmake
- sql/updates/README.md
> Clean up dead code

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
Change the bug report issue template to have dropdown options
sorted alphabetically.
> Sort bug report options

- src/compat/compat.h
The API for pg_md5_hash was changed for PG15 which was initially
backported to the PG14 branch but that commit was later reverted
to not introduce an ABI breakage for extensions.
https://github.com/postgres/postgres/commit/ad5b6f24
https://github.com/postgres/postgres/commit/b69aba74
> Adjust pg_md5_hash compat macro to upstream changes

- test/expected/test_utils.out
- test/src/test_utils.h
- tsl/test/expected/remote_connection.out
- tsl/test/sql/remote_connection.sql
> Increase psql verbosity to see error line numbers in remote_connection test

- .github/workflows/apt-arm-packages.yaml
Add tests for ARM64 Debian and Ubuntu packages
> Test APT ARM64 packages

- src/nodes/hypertable_modify.c
- src/planner.c
- test/expected/rowsecurity-14.out
- test/expected/update-14.out
- tsl/test/expected/jit-14.out
Route UPDATE on Hypertables through our custom HypertableModify
node. This patch by itself does not make any other changes to
UPDATE but is the foundation for other features regarding UPDATE on hypertables.
> Route UPDATE through HypertableModify

- CHANGELOG.md
- src/hypertable.c
- src/process_utility.c
- test/sql/updates/setup.repair.sql
- tsl/src/remote/txn.c
- tsl/test/expected/chunk_api.out
- tsl/test/expected/compression_errors.out
- tsl/test/expected/data_node.out
- tsl/test/expected/dist_grant-12.out
- tsl/test/expected/dist_grant-13.out
- tsl/test/expected/dist_grant-14.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_query.out
- tsl/test/expected/remote_txn_resolve.out
- tsl/test/sql/chunk_api.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/src/remote/txn_resolve.c
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/timescaledb/commit/d656f77926ce70a1b17b4eecc541a7a519250d6e#commitcomment-68700565
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/timescaledb/commit/bc1214288984c914d76d08ba4c53f9b2033320e8
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
> Spelling: Error messages

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
No functional change.
Constructing a whole row var with compressed columns doesn't make
sense. It has to be constructed from decompressed columns by projection
of DecompressChunk node.
Part of https://github.com/timescale/timescaledb/pull/4234
> NFC. Don't add whole row var to compressed scan tlist

- CHANGELOG.md
- scripts/test_update_from_tag.sh
- sql/updates/latest-dev.sql
Add a changelog message and add a check for broken chunks to the update
script.
> Follow-up for compressed chunk collation #4236

- src/hypertable.c
For some reason, we create a MemoryContext for each Chunk. This context
then is almost never used. Just don't do this.
> Do not create a memory context for each Chunk

- CHANGELOG.md
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/cagg_policy.out
- tsl/test/sql/cagg_policy.sql
> Fix refresh window cap for cagg refresh

- tsl/src/remote/tuplefactory.c
It's in a temporary context, so not a memory leak, but it's just not
needed.
In passing, clean up the tuple factory error handling code, again.
> Remove unused memory allocation in tuplefactory

- src/copy.c
This patch adds a reference to the PostgreSQL license file.
> PostgreSQL license file reference added

- test/runner_shared.sh
- test/src/test_utils.c
- tsl/src/fdw/deparse.c
- tsl/src/fdw/shippable.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/shared/expected/dist_remote_error.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_remote_error.sql
- tsl/test/shared/sql/include/shared_setup.sql
- tsl/test/sql/dist_hypertable.sql.in
Add a special function that allows to inject these errors.
> More tests for errors when fetching from data nodes

- sql/updates/post-update.sql
Postgres changes the internal state format for numeric aggregates
which we materialize in caggs in PG14. This will invalidate the
affected columns when upgrading from PG13 to PG14. This patch
adds a warning to the update script when we encounter this
configuration.
> Show warning for caggs with numeric

- .github/workflows/linux-build-and-test.yaml
- CMakeLists.txt
- src/guc.c
- src/histogram.c
- src/loader/bgw_launcher.c
- src/loader/loader.c
- src/nodes/chunk_append/exec.c
- src/nodes/chunk_append/transform.c
- src/partitioning.c
- src/planner/planner.c
- src/process_utility.c
- src/telemetry/functions.c
- src/time_bucket.c
- src/ts_catalog/continuous_agg.c
- test/src/net/conn_mock.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/chunk_api.c
- tsl/src/compression/compress_utils.c
- tsl/src/compression/compression.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/materialize.c
- tsl/src/fdw/modify_exec.c
- tsl/test/src/remote/connection.c
> Fix some of the least controversial clang-tidy warnings

- tsl/src/data_node.c
PG15 changes the type of collate and ctype from name to text.
https://github.com/postgres/postgres/commit/54637508
> Adjust code to PG15 pg_database changes

- src/planner/CMakeLists.txt
- src/planner/planner.c
- src/planner/planner.h
- src/planner/space_constraint.c
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/modify_exclusion.out
- tsl/test/shared/expected/space_constraint-12.out
- tsl/test/shared/expected/space_constraint-13.out
- tsl/test/shared/expected/space_constraint-14.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/space_constraint.sql.in
This patch adds support for chunk exclusion to UPDATE/DELETE on
space dimensions of hypertables.
> Add chunk exclusion for space dimensions to UPDATE/DELETE

- src/planner/space_constraint.c
Coverity warned about usage of pass by value in this instance so
we switch it to pass by reference to reduce the amount of copying
required for the function call.
> Use pass by reference in make_partfunc_call

- sql/pre_install/tables.sql
In `src/ts_catalog/catalog.c` we explicit define some constraints and
indexes names into `catalog_table_index_definitions` array, but in our
pre-install SQL script for schema definition we don't, so let's be more
explicit here and prevent future surprises.
> Explicit constraint names in schema definition

- .github/workflows/coverity.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/pgspot.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/windows-build-and-test.yaml
- scripts/gh_matrix_builder.py
Make CI use just released PG 14.4.
> Bump Postgres version used in CI to 14.4

- tsl/src/data_node.c
- tsl/test/expected/data_node_bootstrap.out
- tsl/test/sql/data_node_bootstrap.sql
> Fix flaky datanode_bootstrap test

- .github/workflows/pull-review.yaml
- .pull-review
- scripts/pull-review.sh
This commit adds a workflow for running pull-review in
the serverless mode, using docker container CLI.
Currently, it only does a dry run and logs the output.
> Add config file and workflow for pull-review

- src/chunk.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
Add chunk inheritance when attaching a OSM
tabel as a chunk of the hypertable
> Fix attach_osm_table_chunk

- CMakeLists.txt
- src/CMakeLists.txt
- src/gitcommit.cmake
Create gitcommit.h everytime the commit info is changed.
Fixes #4490
> Fix gitcommit regenerate issue

- .github/workflows/coverity.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/pgspot.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/update-test.yaml
- .github/workflows/windows-build-and-test.yaml
- scripts/gh_matrix_builder.py
> Bump PG version used in CI to 14.5,13.8 and 12.12

- .github/ci_settings.py
- .github/workflows/abi.yaml
Recent CI settings refactoring made in commit 0c6f4e24 broke the
ABI test. This patch fixes the test and adds setting for the minimum
ABI compatible version.
> Fix ABI test

- src/cross_module_fn.c
A call to `compressed_data_out` from a replication worker would
produce a misleading error saying that your license is "timescale"
and you should upgrade to "timescale" license, even if you have
already upgraded.
As a workaround, we try to load the TSL module it in this function.
It will still error out in the "apache" version as intended.
We already had the same fix for `compressed_data_in` function.
> Load TSL library on compressed_data_out call

- src/cross_module_fn.c
This patch ensures that the TSL library is loaded when the database is upgraded and `post_update_cagg_try_repair` is
called.
There are some situations when the TSL library is not loaded properly during an upgrade (see timescale/Support-Dev-Collab#468), resulting in the following error message:
```
Error while upgrading extensions: ERROR:  function "post_update_cagg_try_repair" is not supported under the current "timescale" license
HINT:  Upgrade your license to 'timescale'
```
This patch basically makes the same changes as #4573, but for `cagg_try_repair`.
> Ensure TSL library is loaded on database upgrades

- CHANGELOG.md
- src/nodes/chunk_insert_state.c
- test/expected/insert_returning.out
- test/sql/CMakeLists.txt
- test/sql/insert_returning.sql
To make it work, it is enough to properly pass the parent of the
PlanState while initializing the projection in RETURNING clause.
Fixes https://github.com/timescale/timescaledb/issues/4640
> Fix joins in RETURNING

- src/compat/compat.h
- src/nodes/hypertable_modify.c
- tsl/src/chunk_api.c
PG15 refactors INSERT/UPDATE/DELETE code and changes the signatures
of some of the functions.
https://github.com/postgres/postgres/commit/25e777cf
> Add compat macros for PG15 signature changes

- test/pg_regress.sh
This patch changes the regression test schedule generation to only completely rebuild the schedule when TESTS is specified. In all other cases the existing schedule is amended. This means any parallelity present in the cmake generated schedule will be kept.
> Improve SKIPS handling in regression tests

- tsl/src/bgw_policy/policies_v2.c
Local compilation of timescaledb fails on MaCOSx with clang version
11.0.0. Fixes for a couple of warnings.
> Fix some clang compile warnings

- src/planner/constify_now.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
> Fix assertion failure in constify_now

- src/bgw/job.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
> Remove support for procedures as custom checks

- .github/workflows/stalebot.yaml
This PR improves the text of the stalebot and makes it clearer who is addressed by the message.
> Updated the text of the stalebot

- CHANGELOG.md
- tsl/src/remote/connection.c
Pass proper flags to WaitLatchOrSocket
Fixes https://github.com/timescale/timescaledb/issues/4728
> Fix error when waiting for remote COPY to finish

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/shared/expected/decompress_join-12.out
- tsl/test/shared/expected/decompress_join-13.out
- tsl/test/shared/expected/decompress_join-14.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/decompress_join.sql.in
> Fix join on time column of compressed chunk

- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
For some reason the cost estimates are different on my machine.
> Add COSTS OFF to make test more stable

- .github/workflows/homebrew.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
> Fix update script handling of bgw_job_stat

- src/copy.c
We don't need reference counting there, and it spends a lot of CPU in ResourceOwner.
It slightly improves COPY performance on some data sets:
```
benchmark:
environment_type: "timescaledb_singlenode"
prepare-benchmark:
steps:
- run: |
drop table if exists uk_price_paid;
create table uk_price_paid(price integer, "date" date, postcode1 text, postcode2 text, type smallint, is_new bool, duration smallint, addr1 text, addr2 text, street text, locality text, town text, district text, country text, category smallint);
SELECT create_hypertable('uk_price_paid', 'date');
COPY uk_price_paid FROM '/home/akuzm/dataset/uk-price-paid/prices-1M-2001-random-1.tsv';
VACUUM ANALYZE;
CHECKPOINT;
benchmark:
executions: 5
steps:
- run: |
BEGIN;
COPY uk_price_paid FROM …
```
> Use non-refcounted tupdesc for multi-insert buffers

- src/planner/planner.c
- test/expected/merge.out
- test/sql/CMakeLists.txt
- test/sql/merge.sql
Fixes #4930
Co-authored-by: Lakshmi Narayanan Sreethar <lakshmi@timescale.com>
> Disable MERGE when using hypertables

- src/bgw/job.c
Old assertions checking integrety of metadata for jobs will print error message in release builds instead of continuing executing with bad metadata.
> Print errors in release builds for jobs

- .github/gh_matrix_builder.py
- tsl/test/expected/data_node.out
- tsl/test/expected/dist_param.out
- tsl/test/sql/data_node.sql
- tsl/test/sql/dist_param.sql
The dist_move_chunk causes the CI to hang when compiled and run with PG15 as explained in #4972.
> Disable dist_move_chunk test in PG15

- .github/workflows/rpm-packages.yaml
> Add Enterprise Linux 9 packages to RPM package test

- test/expected/copy-15.out
- test/expected/insert-15.out
- test/expected/merge.out
- tsl/test/expected/cagg_on_cagg_integer_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamp_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamptz_dist_ht.out
- tsl/test/sql/cagg_on_cagg_integer_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_timestamp_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_timestamptz_dist_ht.sql
PR #4668 introduced the Hierarchical Continuous Aggregates (aka Continuous Aggregate on top of another Continuous Aggregate) but unfortunately we miss to fix the regression tests on PG15.
> Fix caggs on caggs tests on PG15

- .github/gh_matrix_builder.py
- tsl/test/shared/expected/dist_fetcher_type-12.out
- tsl/test/shared/expected/dist_fetcher_type-13.out
- tsl/test/shared/expected/dist_fetcher_type-14.out
- tsl/test/shared/expected/dist_fetcher_type-15.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_fetcher_type.sql.in
Fix dist_fetcher_type test on PG15
> Fix dist_fetcher_type test on PG15

- .github/workflows/sanitizer-build-and-test.yaml
Updating scheduled run to avoid original creator from being notified.
> Updating scheduled run

- .github/workflows/sanitizer-build-and-test.yaml
- scripts/upload_ci_stats.sh
This patch contains two changes to the Sanitizer checks:
(1) All logfiles of the Sanitizer will be uploaded to the
CI database.
(2) The Sanitizer checks are executed on every PR.
> Improve Sanitizer checks

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
> More gdb output in CI

- src/chunk_scan.c
- src/guc.c
- src/guc.h
- src/hypertable_restrict_info.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
The GUC variable controls whether OSM chunk is used in a select query plan.
> Add a GUC variable to enable/disable OSM reads

- test/sql/utils/testsupport.sql
- tsl/src/nodes/async_append.c
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_hypertable-15.out
We forgot to add a case for it.
> Allow AsyncAppend under IncrementalSort

- tsl/src/fdw/deparse.c
This patch adds the missing functionality to handle joins to the deparser. Most of the code is a backport from PG Upstream.
**Note:** This is the first PR for the join functionality in the multi-node code. Test cases will follow with the PR containing the planner changes.
> Add join functionality to the deparser code

- .github/workflows/apt-packages.yaml
> Don't run the APT package test on PRs

- .github/workflows/sqlsmith.yaml
- scripts/upload_ci_stats.sh
Mostly we are interested in stacktraces and failed queries here.
> Save SQLSmith results to the CI DB

- .github/gh_matrix_builder.py
- .github/workflows/code_style.yaml
- scripts/githooks/commit_msg.py
- scripts/githooks/commit_msg_tests.py
- scripts/test_memory_spikes.py
Helps find some errors and cosmetic problems.
Specifically, I added [prospector](https://prospector.landscape.io/en/master/index.html) because it combines many different linters and has lenient defaults. We could also run [black](https://github.com/psf/black) on them but that might be too opinionated.
> Run python linter in CI

- .github/workflows/sqlsmith.yaml
This would help to gather more statistics. We have some rare assertion failures that happen with SQLSmith like #4185
> Run sqlsmith on all commits in main

- tsl/src/continuous_aggs/materialize.h
Disable-Check: force-changelog-changed
> Remove unused function prototype

- .github/workflows/code_style.yaml
- scripts/backport.py
Apparently a new version is out and it complains about Exception being too general.
> Fix pylint again

- tsl/src/compression/compression.c
Restructur the code inside decompress_chunk slightly to make core loop reusable by other functions.
> Refactor chunk decompression functions

- .codecov.yml
Codecov keeps complaining that it's invalid.
> Fix our codecov repository yaml

- tsl/test/sql/.gitignore
> Add dist_ref_table_join generated test files to .gitignore

- tsl/test/expected/dist_compression.out
- tsl/test/sql/dist_compression.sql
Make sure inserts into compressed chunks work when a DN is down
Fix #5039
> Add additional tests for compression with HA

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/sql/include/cagg_ddl_common.sql
> Allow named time_bucket arguments in cagg definition

- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/invalidation_threshold.h
Remove unused function `invalidation_threshold_htid_found`.
> Remove unused function

- CHANGELOG.md
- scripts/test_updates_pg13.sh
- scripts/test_updates_pg14.sh
- scripts/test_updates_pg15.sh
- sql/updates/post-update.sql
- test/sql/updates/post.repair.cagg_joins.sql
- test/sql/updates/post.repair.sql
- test/sql/updates/setup.repair.cagg_joins.sql
- test/sql/updates/setup.repair.sql
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_joins-12.out
- tsl/test/expected/cagg_joins-13.out
- tsl/test/expected/cagg_joins-14.out
- tsl/test/expected/cagg_joins-15.out
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_joins.out
- tsl/test/expected/cagg_on_cagg_joins_dist_ht.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_joins.sql.in
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_joins.sql
- tsl/test/sql/cagg_on_cagg_joins_dist_ht.sql
- tsl/test/sql/include/cagg_on_cagg_common.sql
- tsl/test/sql/include/cagg_on_cagg_setup.sql
Also had to cherry-pick https://github.com/timescale/timescaledb/commit/98218c1d079231a9aa469b37ddd0ed39e77c2adb and https://github.com/timescale/timescaledb/commit/3cc8a4ca34ec76f4de66349af3194851acb7c228 to avoid merge conflicts.
> Backport Pass join related structs to the cagg rte #5441 to 2.10.x

- CHANGELOG.md
- src/time_utils.c
- src/time_utils.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/sql/include/cagg_ddl_common.sql
> Backport more fixes to 2.10.x

- .gitattributes
- CHANGELOG.md
[Milestone](https://github.com/timescale/timescaledb/milestone/70?closed=1)
> Changelog for 2.10.2

- sql/CMakeLists.txt
- version.config
For less confusion if we ever want to do the 2.10.3.
> Bump version to 2.10.3-dev after release

- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
> Refactor compression code to reduce duplication

- .github/workflows/windows-packages.yaml
> Update windows package link in github action

- CHANGELOG.md
- sql/CMakeLists.txt
[Changelog](https://github.com/timescale/timescaledb/pull/5671)
[Milestone](https://github.com/timescale/timescaledb/milestone/71)
> Release 2.10.3

- .github/workflows/linux-build-and-test-ignored.yaml
> Add missing matrix in ignored regression workflow

- .github/workflows/linux-32bit-build-and-test-ignored.yaml
> Add missing matrix in ignored 32bits regression workflow

- CHANGELOG.md
[Milestone](https://github.com/timescale/timescaledb/milestone/71)
> Changelog for 2.10.3

- src/bgw/job.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
Unused Value reported during coverity scan
link: https://scan4.scan.coverity.com/reports.htm#v56957/p12995
> Fixed Coverity Scan Warnings

- tsl/test/expected/cagg_joins-12.out
- tsl/test/expected/cagg_joins-13.out
- tsl/test/expected/cagg_joins-14.out
- tsl/test/expected/cagg_joins-15.out
- tsl/test/sql/cagg_joins.sql.in
Add more regression tests for Continuous aggregates with joins.
> Improve test suite

- src/copy.c
- src/hypertable.c
- src/loader/bgw_launcher.c
- test/src/bgw/params.c
- tsl/src/compression/compression.c
> Replace heap_endscan to table_endscan

- .github/workflows/procedural.yaml
With this PR we allow issues with flaky-test label to be added to our bugs board.
> Allow flaky-test label

- src/chunk.c
- src/chunk_constraint.c
- src/hypertable.c
- src/hypertable.h
- src/hypertable_cache.c
- src/planner/planner.c
- src/process_utility.c
- src/ts_catalog/continuous_agg.c
- src/ts_catalog/tablespace.c
- src/utils.h
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/data_node.c
> Add Ensure-s to avoid crashes if chunk table gets dropped.

- scripts/backport.py
The backport script for the PRs does not have the permission to backport PRs which include workflow changes. So, these PRs are excluded from being automatically backported.
Failed CI run:
https://github.com/timescale/timescaledb/actions/runs/5387338161/jobs/9780701395
> refusing to allow a GitHub App to create or update workflow
> `.github/workflows/xxx.yaml` without `workflows` permission)
> Exclude workflow changes from being backported

- .github/gh_config_reader.py
- .github/gh_matrix_builder.py
- .github/workflows/libfuzzer.yaml
Might help us find something interesting.
> Cache the libfuzzer corpus between runs

- .github/workflows/sqlsmith.yaml
The build was failing because it was picking up the wrong version of Postgres. Remove it.
> Fix SQLSmith workflow

- .github/workflows/apt-packages.yaml
> Test timescaledb debian 12 packages in CI

- .github/ci_settings.py
> Bump Postgres versions used in CI

- src/compat/compat.h
PG16 refactors how VACUUM passes around its XID cutoffs. A new dedicated struct is now used by VACUUM to maintain the XID/MXID cutoffs such as FreezeLimit and OldestXmin. The vacuum_set_xid_limits() function is also now replaced with a a new vacuum_get_cutoffs() function that uses the new struct.
postgres/postgres@4ce3afb8
Disable-Check: commit-count
> PG16: vacuum_set_xid_limits is now vacuum_get_cutoffs

- scripts/test_updates_pg13.sh
- scripts/test_updates_pg14.sh
- scripts/test_updates_pg15.sh
- sql/CMakeLists.txt
- version.config
Bumping the previous version and adding tests for 2.11.2
> Post-release fixes for 2.11.2

- test/sql/updates/setup.continuous_aggs.v2.sql
The expression part of the psql \if cannot contain actual SQL expression
and is instead much more limited.
A valid value is any unambiguous case-insensitive match for one of: true, false, 1, 0, on, off, yes, no.
See https://www.postgresql.org/docs/current/app-psql.html
> Fix psql \if expression

- tsl/test/expected/dist_compression.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_hypertable-15.out
Adjust output of dist_compression and dist_hypertable to catalog changes.
> Fix dist_compression and dist_hypertable tests

- test/t/001_extension.pl
The extension tap test is very flakey and seems to fail very often with unhelpful error messages. This patch simplifies the test to make it more reliable.
> Simplify extension tap test

- tsl/test/expected/cagg_ddl_dist_ht-16.out
- tsl/test/expected/cagg_usage-16.out
- tsl/test/expected/dist_param.out
Seems there was some leftovers from #6139 do be fixed.
> PG16: Fix regression tests

- .unreleased/PR_6117
- .unreleased/pr_6113
- .unreleased/pr_6142
- CHANGELOG.md
- scripts/test_updates_pg13.sh
- scripts/test_updates_pg14.sh
- scripts/test_updates_pg15.sh
- sql/CMakeLists.txt
- version.config
> Release 2.12.1

- .unreleased/PR_6155
- .unreleased/pr_6210
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.12.1 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* #6155 Align gapfill bucket generation with time_bucket
* #6181 Ensure fixed_schedule field is populated
* #6210 Fix EXPLAIN ANALYZE for compressed DML
> Release 2.12.2

- src/planner/partialize.c
a094f175eb7c98173c78f557880ccd2d89b791f8 changes the contains_path_plain_or_sorted_agg function. However, a return statement is missing to properly return the result of subpaths.
---
Found by Coverity
> Simplified aggregation type detection logic

- src/bgw/scheduler.c
This patch adds some further debug messages to the job scheduler. This allows to debug the scheduled jobs in production environments.
---
> Add debug messages to job scheduler

- .github/workflows/sqlsmith.yaml
> PG16: Enable SQLSmith on CI

- tsl/src/continuous_aggs/insert.c
Print more precise error message and the affected chunk.
See https://github.com/timescale/timescaledb/issues/6281
> Improve diagnostics for cagg trigger errors

- tsl/test/expected/transparent_decompression-16.out
- tsl/test/shared/expected/transparent_decompress_chunk-16.out
I forgot to update them in #6212
> Fix the PG16 test references

- src/planner/expand_hypertable.c
- src/ts_catalog/CMakeLists.txt
- src/ts_catalog/array_utils.c
- src/ts_catalog/array_utils.h
- tsl/src/remote/dist_commands.c
These will see more use in follow-up patches that adjust how compression settings are stored in our catalog.
> Add helper functions for arrays

- tsl/src/compression/create.c
Slight refactoring to decouple toast storage options from Hypertable_compression and instead base it on the default algorithm for the uncompressed datatype of a column. This should result in the exact same storage option used as before.
> Decouple toast storage options from Hypertable_compression

- src/bgw/job.c
- src/chunk.c
- src/chunk_adaptive.c
- src/compression_with_clause.c
- src/hypertable.c
- src/hypertable_cache.c
- tsl/src/bgw_policy/job.c
- tsl/src/chunk_api.c
- tsl/src/chunk_copy.c
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/deparse.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/src/remote/connection_cache.c
> Use NameStr() macro for NameData struct usage

- tsl/src/compression/api.c
- tsl/src/compression/compression.c
Refactor the compression code to only use the table scan API when scanning relations instead of a mix of the table and heap scan APIs. The table API is a higher-level API and recommended as it works for any type of relation and uses table slots directly, which means that in some cases a full heap tuple need not be materialized.
> Use table scan API in compression code

- src/planner/partialize.c
- test/expected/agg_bookends.out
- test/expected/parallel-13.out
- test/expected/parallel-14.out
- test/expected/parallel-15.out
- test/expected/parallel-16.out
- test/expected/partitionwise-13.out
- test/expected/partitionwise-14.out
- test/expected/partitionwise-15.out
- test/expected/partitionwise-16.out
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/merge_append_partially_compressed-13.out
- tsl/test/expected/merge_append_partially_compressed-14.out
- tsl/test/expected/merge_append_partially_compressed-15.out
- tsl/test/expected/merge_append_partially_compressed-16.out
- tsl/test/sql/merge_append_partially_compressed.sql.in
> Do not produce partial aggregation plans for the only chunk

- .github/workflows/linux-build-and-test.yaml
- scripts/upload_ci_stats.sh
- tsl/test/expected/cagg_migrate.out
- tsl/test/sql/include/cagg_migrate_common.sql
The upload script needs access to the "psql" binary with its proper path. Fix that.
> Fix MacOSx build issues

- test/src/telemetry/test_telemetry.c
In telemetry test we are using an external service for checking status codes and that service can have intermittent outages which cause this test to fail. Retrying the request should make the test a bit more reliable.
> Fix telemetry test flakiness

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
This reverts commit 2bd06e22a5a64eff19d2a272a9fd355829ecdcf5.
It broke some builds on main branch, revert it pending investigation.
> Revert "Remove unneded parameter from PG build cache keys"

- tsl/src/compression/create.c
This patch moves the check function for orderby and segmentby into dedicated functions and cleans up a few other places where code was redundant.
> Refactor compression settings handling

- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/insert.h
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/refresh.c
> Remove some multinode leftovers from CAggs

- src/ts_catalog/array_utils.c
- src/ts_catalog/array_utils.h
- src/ts_catalog/compression_settings.c
- src/ts_catalog/compression_settings.h
- tsl/src/compression/api.c
- tsl/test/expected/compression_merge.out
- tsl/test/sql/compression_merge.sql
Add a check to verify compression settings for chunks to be rolled up are identical.
> Verify compression configuration on compression rollup

- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/compressed_batch.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/nodes/decompress_chunk/pred_vector_array.c
- tsl/src/nodes/decompress_chunk/vector_predicates.h
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/sql/decompress_vector_qual.sql
Implement vectorized computation of AND, OR and NOT operators in WHERE
clause.
Merge after https://github.com/timescale/timescaledb/pull/6460
> Vectorized boolean operators

- test/sql/updates/cleanup.policies.sql
PERFORM can only be used in PLpgSQL context and not SQL context.
> Fix wrong usage of PERFORM in update test script

- tsl/src/nodes/decompress_chunk/compressed_batch.c
Change the variable from single uint64 to array to prevent the error.
> Fix coverity false positive

- coccinelle/attrnumbergetattroffset.cocci
Forgot to fix some typo raised by Mats before merge #6661.
> Fix typo in coccinele script

- tsl/src/continuous_aggs/repair.c
The PR #6624 introduces a catalog access to get the Oid of a relation. However, C strings were passed to the catalog cache and NameStr are needed since namehashfast() is called internally. This PR fixes the problem. Found by sanitizer.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/7934100833/job/21664369115
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/7935016720/job/21667254530?pr=6668
> Fix passed parameter to system catalog

- .github/workflows/issue-handling.yaml
The field reference for the event URL was wrong.
> Fix URL reference for event

- .github/workflows/issue-handling.yaml
The JSON format was not correct for the generated message, so this commit fixes that.
> Fix JSON format for message

- sql/updates/latest-dev.sql
PR #6752 resets the autovaccum storage options. However, storage options can not be set for OSM chunks. Therefore, the need to be excluded from resetting the autovaccum storage option.
---
> Exclude OSM chunks from enabling autovaccum

- .github/workflows/issue-handling.yaml
The existing service does not seem to stable and does not work so switch to using the official Spack API GitHub action instead.
> Switch to official Slack API

- src/chunk.c
- src/chunk_adaptive.c
- src/hypertable.c
- src/hypertable.h
For reviewers:
multiple commits to help with reviewing. I'll rebase as 1 commit after reviews.
> Modify hypertable catalog update API

- src/bgw/job.c
So far, we have loaded the timezone information not into the correct memory context when we fetched a job from the database. Therefore, this value was stored in the scratch_mctx and removed too early. This PR moved the value into the desired memory context.
----
Failed sanitizer run: https://github.com/timescale/timescaledb/actions/runs/8785696269/job/24106812757
Fixed sanitizer run: https://github.com/timescale/timescaledb/actions/runs/8790138976/job/24121503360?pr=6847
> Fix handling of timezone attr in job scheduler

- src/hypertable_restrict_info.c
- src/utils.c
- src/utils.h
This enum is used in no codepath.
> Remove TimevalInfinity enum

- src/CMakeLists.txt
- src/expression_utils.c
- src/expression_utils.h
- src/hypertable_restrict_info.c
- tsl/src/compression/compression.c
Atm this just extracts OpExpr handling into separate function. Stay tuned for more changes in this area.
> Refactor expression handling for compressed UPDATE/DELETE

- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
> Add Ubuntu 24.04 to CI packaging

- .github/codespell-ignore-words
- .github/workflows/code_style.yaml
- cmake/GenerateScripts.cmake
- cmake/ScriptFiles.cmake
- scripts/backport.py
- scripts/export_prefix_check.sh.in
- tsl/src/continuous_aggs/repair.c
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/t/003_mvcc_cagg.pl
> Silence codespell check

- .github/gh_matrix_builder.py
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- tsl/test/t/002_logrepl_decomp_marker.pl
* Fix sanitizer failure
https://github.com/timescale/timescaledb/actions/runs/9277248240
* Fix flaky TAP test
https://github.com/timescale/timescaledb/actions/runs/9287713038/job/25557441079?pr=6973
> Fix some CI failures

- src/planner/expand_hypertable.c
> Fix code comment ending mid-sentence

- NOTICE
Update copyright to include 2023 and 2024 in NOTICE
> Update copyright notice to 2024

- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
Made some small tweaks in the testing order to actually do what the comments are saying.
> Reorder some tests in bgw_custom

- sql/CMakeLists.txt
- version.config
> Post release 2.15.2

- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
> Backport to 2.15.x: #6906: Add Ubuntu 24.04 to CI

- tsl/src/continuous_aggs/common.c
- tsl/test/expected/cagg_utils.out
> Fix typo in cagg error message

- .github/gh_matrix_builder.py
> Cleanup some specific PG14 stuff from GH matrix

- tsl/src/compression/api.c
We added a few diagnostic log messages in the compression/decompression code paths some time ago and they have been useful in identifying hotspots in the actual activities. Adding a few more for recompression now. The row_compressor_append_sorted_rows function which is also used in recompression is already logged so we need just a few log messages here.
> Add logs in the recompression code path

- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
> Remove some dead code related to distributed hypertables

- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
- tsl/src/compression/compression.h
- tsl/src/compression/compression_dml.c
- tsl/test/shared/expected/compress_unique_index.out
- tsl/test/shared/expected/compression_dml.out
- tsl/test/shared/expected/decompress_tracking.out
Show information about filtered batches in EXPLAIN ANALYZE output.
> Add compression tuple filtering information to EXPLAIN

- tsl/test/expected/foreign_keys.out
- tsl/test/sql/foreign_keys.sql
> Add more tests for foreign key constraints on hypertables

- tsl/src/bgw_policy/policies_v2.c
> Fix integer overflow in window size calculation

- tsl/src/continuous_aggs/common.c
> Remove unused variable

- src/guc.c
- src/guc.h
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
Allow controlling FK query behaviour with GUC
enable_foreign_key_propagation.
> Add GUC for foreign key propagation

- src/planner/expand_hypertable.c
> Remove some leftover code from multinode

- tsl/src/continuous_aggs/common.c
- tsl/src/continuous_aggs/materialize.c
> Leftover from previous CAgg refactoring

- .github/workflows/pgspot.yaml
> Bump pgspot to 0.8.0

- sql/CMakeLists.txt
- version.config
Add 2.16.1 to update tests and adjust version configuration
> 2.16.1 post release

- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
> Fix early abort in compression-ddl test

- .unreleased/RELEASE_NOTES_HEADER.md.j2
From the header template.
This is needed to simplify scripts for automation of releases.
> Comment tentative feature-notes lines

- .github/gh_matrix_builder.py
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- test/expected/ts_merge-17.out
> Fix MERGE ROWID_VAR handling for PG17

- tsl/test/expected/privilege_maintain.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/privilege_maintain.sql
Test maintain privilege gets propagated to chunks.
> Add simple test for new PG17 MAINTAIN privilege

- .unreleased/group_by_segmentby
- .unreleased/pr_6882
- .unreleased/pr_7126
- .unreleased/pr_7187
- .unreleased/pr_7191
- .unreleased/pr_7195
- .unreleased/pr_7201
- .unreleased/pr_7204
- .unreleased/pr_7207
- .unreleased/pr_7209
- .unreleased/pr_7227
- .unreleased/pr_7229
- .unreleased/pr_7230
- .unreleased/pr_7234
For docs-compliance for the upcoming release.
> Improve release-notes further

- .github/workflows/abi.yaml
> Bump alpine version on ABI workflow

- .github/workflows/linux-32bit-build-and-test-ignored.yaml
> PG17: Fix ignored 32bit workflow

- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
> Test PG17 packages in linux package test

- .github/workflows/pg_upgrade-test.yaml
- test/sql/updates/post.catalog.sql
- test/sql/updates/post.pg_upgrade.sql
> PG17: Enable pg_upgrade tests on CI

- .github/workflows/pgspot.yaml
> Bump pgspot to 0.8.1

- .github/workflows/windows-packages.yaml
> Add PG17 windows package tests

- .github/workflows/docker-images.yaml
> Add pg17 images to docker tests

- tsl/src/continuous_aggs/materialize.c
> Simplify usage of SPI_execute_with_args

- .github/workflows/update-test.yaml
- scripts/test_updates.sh
> Enable update test for PG17

- .unreleased/pr_7360
- src/guc.c
- src/guc.h
- src/hypertable.c
- src/hypertable_restrict_info.c
- src/nodes/chunk_append/exec.c
- src/ts_catalog/chunk_column_stats.c
- tsl/test/expected/chunk_column_stats-14.out
- tsl/test/expected/chunk_column_stats-15.out
- tsl/test/expected/chunk_column_stats-16.out
- tsl/test/expected/chunk_column_stats-17.out
- tsl/test/sql/chunk_column_stats.sql.in
Add the ability to enable/disable new chunk skipping functionality completely.
(cherry-picked from commit 8767565e3)
> Backport to 2.17.x: #7360 Add chunk skipping GUC

- .unreleased/pr_7335
- .unreleased/pr_7345
- .unreleased/pr_7360
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains performance improvements and bug fixes since the 2.17.0 release. We recommend that you upgrade at the next available opportunity.
**Features**
* #7360 Add chunk skipping GUC
**Bugfixes**
* #7335 Change log level used in compression
* #7342 Fix collation for in-memory tuple filtering
**Thanks**
* @gmilamjr for reporting an issue with the log level of compression messages
* @hackbnw for reporting an issue with collation during tuple filtering
> Release 2.17.1

- .unreleased/pr_7335
- .unreleased/pr_7345
- .unreleased/pr_7360
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains performance improvements and bug fixes since the 2.17.0 release. We recommend that you upgrade at the next available opportunity.
**Features**
* #7360 Add chunk skipping GUC
**Bugfixes**
* #7335 Change log level used in compression
* #7342 Fix collation for in-memory tuple filtering
**Thanks**
* @gmilamjr for reporting an issue with the log level of compression messages
* @hackbnw for reporting an issue with collation during tuple filtering
> Release 2.17.1 on main

- .gitignore
> Add .gdb_history to gitignore

- scripts/backport.py
Currently if a PR that is elegible for backporting touches a workflow file then the automatic backport fails.
Now adding the label `force-auto-backport-workflow` to a PR that touches workflow files will proceed with the automatic backporting. This is useful because sometimes we need to fix a workflow and backport it to the current release branch or when we're adding support to a new Postgres major version that requires workflow changes and it should be backported to the release branch in case of creating patch releases.
> Force auto backport workflow

- test/runner.sh
- test/runner_shared.sh
https://github.com/timescale/timescaledb/actions/runs/11504450173/job/32024163052?pr=7386#step:13:17
> Update runner script to avoid flaky tests

- .github/workflows/pr-approvals.yaml
> run pr review workflow when a review is changed

- tsl/test/expected/hypercore_stats.out
- tsl/test/sql/hypercore_stats.sql
https://github.com/timescale/timescaledb/actions/runs/11825528841/job/32949516502?pr=7434
> Fix hypercore stats flaky tests (take 2)

- README.md
> Update note for breaking change in Postgres 17.1.

- sql/updates/post-update.sql
> Warning for the old CAggs format in all PG versions

- .github/workflows/windows-build-and-test.yaml
> Bump setup windows wsl on CI

- docs/BuildSource.md
> Fix broken link for installation docs

- .github/workflows/pgspot.yaml
> Bump pgspot version to 0.9.0

- .unreleased/pr_6901
- .unreleased/pr_7104
- .unreleased/pr_7271
- .unreleased/pr_7295
- .unreleased/pr_7378
- .unreleased/pr_7390
- .unreleased/pr_7409
- .unreleased/pr_7411
- .unreleased/pr_7412
- .unreleased/pr_7426
- .unreleased/pr_7432
- .unreleased/pr_7434
- .unreleased/pr_7443
- .unreleased/pr_7455
- .unreleased/pr_7482
- .unreleased/pr_7486
- .unreleased/pr_7488
- .unreleased/pr_7514
- .unreleased/pr_7557
- .unreleased/resolve-vars
- .unreleased/vectorized-agg-filter
- .unreleased/vectorized-grouping-one-fixed
Minor changes to enable preview from docs team.
> Edit release notes

- tsl/test/isolation/expected/compression_ddl_iso.out
- tsl/test/isolation/specs/compression_ddl_iso.spec
> Add missing ORDER BY clause to compression_ddl_iso test

- test/expected/append-14.out
- test/expected/append-15.out
- test/expected/append-16.out
- test/expected/append-17.out
- test/sql/append.sql.in
https://github.com/timescale/timescaledb/actions/runs/12671498355/job/35313519874?pr=7577#step:17:14
> Disable IndexOnlyScans for ChunkAppend tests

- tsl/src/hypercore/arrow_tts.c
When creating a heap tuple from an arrow slot, it is necessary to also transfer the visibility information from the compressed tuple. Otherwise, the new tuple, if written into another relation, might not have the correct visibility.
> Transfer visibility when copying arrow tuple slot

- tsl/test/shared/expected/constify_now.out
- tsl/test/shared/sql/constify_now.sql
> Add chunk ranges to constify_now test and remove costs

- scripts/backport.py
- version.config
> Bump version to 2.19.0-dev

- scripts/backport.py
> Fix the backport script

- .github/workflows/windows-packages.yaml
> Add Windows package test for latest pg17

- .github/workflows/catalog-updates-check.yaml
- scripts/check_updates.py
> Add actionable hints to update script checker

- src/hypertable.c
> Remove dead is_dist_call argument from ts_hypertable_create

- sql/size_utils.sql
- src/chunk.c
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/dimension.c
- src/hypertable.h
- src/indexing.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/process_utility.c
- src/telemetry/stats.c
- src/telemetry/stats.h
- src/ts_catalog/metadata.h
- tsl/src/chunk.c
- tsl/src/init.c
- tsl/src/partialize_finalize.c
- tsl/src/planner.c
- tsl/src/planner.h
> Remove outdated references to distributed hypertables

- .github/workflows/prerelease-test.yaml
> prerelease test on release branch: github action

- .github/workflows/prerelease-test.yaml
- .github/workflows/sqlsmith.yaml
Also, schedule sqlsmith daily on release branch.
> Schedule coverity scan weekly on release branch.

- .github/workflows/pr-approvals.yaml
> Revert one-reviewer rule for table access method

- .github/workflows/minor_release.yaml
> Simplify environment variables setting

- .github/workflows/minor_release.yaml
> Set environment for gated action

- .unreleased/pr_7712
> Add thanks for executor hook fixes

- src/planner/planner.c
Split off the code for dealing with FK queries into own function.
No code is changed within this PR just moved around.
> Move FK query handling into own function

- README.md
Tiny updates to align with the RTA messaging 
> RTA updates

- CHANGELOG.md
> Add links to PRs in changelong

- .github/gh_matrix_builder.py
- .github/workflows/abi.yaml
> Fix ABI CI workflow

- .github/workflows/windows-build-and-test.yaml
- CMakeLists.txt
> Allow providing extra options for clang-tidy

- .unreleased/pr_7799
> Add missing thanks to bug fix

- tsl/test/expected/merge_chunks.out
- tsl/test/sql/merge_chunks.sql
Adding ordering to output to reduce flakiness.
> Order merge_chunks test output

- tsl/test/expected/cagg_refresh_policy_incremental.out
- tsl/test/sql/cagg_refresh_policy_incremental.sql
> Use timer mock on Incremental CAgg Refresh policy tests take 2

- .unreleased/pr_7806
- src/process_utility.c
- tsl/test/expected/compression_constraints.out
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/compression_errors-14.out
- tsl/test/expected/compression_errors-15.out
- tsl/test/expected/compression_errors-16.out
- tsl/test/expected/compression_errors-17.out
- tsl/test/expected/hypercore_index_btree.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_constraints.sql
- tsl/test/sql/compression_ddl.sql
- tsl/test/sql/compression_errors.sql.in
- tsl/test/sql/hypercore_index_btree.sql
> Allow adding unique constraints to compressed chunks

- tsl/src/hypercore/hypercore_handler.c
- tsl/src/nodes/vector_agg/plan.c
- tsl/src/nodes/vector_agg/plan.h
- tsl/src/nodes/vector_agg/plan_decompress_chunk.c
- tsl/src/nodes/vector_agg/plan_tam.c
The two fixes are separate commits.
> Fix two Coverity issues

- .github/workflows/release_build_packages.yml
> Fix workflow call to docker build

- CHANGELOG.md
> Review 2.19 release notes

- scripts/test_update_smoke.sh
> Simplify smoke test script

- .github/gh_matrix_builder.py
> Adjust runner name after change

- .github/workflows/linux-build-and-test.yaml
- scripts/upload_ci_stats.sh
- tsl/test/expected/compression_ddl.out
> Fix the CI error with the IPE summary file not being created

- .github/workflows/sqlsmith.yaml
> Add CAggs to sqlsmith CI tests

- src/guc.c
> Improve description for restoring GUC

- src/nodes/hypertable_modify.c
- **Simplify ChunkDispatchState handling**
> Simplify ChunkDispatchState handling

- .unreleased/pr_7834
- .unreleased/pr_7890
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Forwardport 2.19.1

- src/nodes/chunk_dispatch/chunk_dispatch.c
- tsl/test/expected/compression_insert.out
- tsl/test/sql/compression_insert.sql
Adding test which covers using all compression algorithms in an unique constraint. This test will be useful when we implement vectorized decompression and filtering.
> Add constraint checking test for compression algos

- src/chunk_constraint.c
- src/hypertable.c
- tsl/src/nodes/vector_agg/plan.h
> Remove unused structs

- .unreleased/pr_7902
- .unreleased/pr_7911
- .unreleased/pr_7923
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
- changelog
- upgrade & downgrade files
- version config
> 2.19.2 release

- .unreleased/pr_7902
- .unreleased/pr_7911
- .unreleased/pr_7923
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
Cherry-pick changes from d454524eb6ef63196e3d22bc8a2e3cdf0719cfaf
> Forwardport 2.19.2

- .github/gh_matrix_builder.py
Backport of https://github.com/timescale/timescaledb/pull/7867/
> Manual backport of 7867

- .github/workflows/pg_ladybug.yaml
> Add workflow for running pg_ladybug on timescaledb

- src/process_utility.c
- src/with_clause/create_table_with_clause.c
- src/with_clause/create_table_with_clause.h
- test/expected/create_table_with.out
- test/sql/create_table_with.sql
> Add create_default_indexes option to CREATE TABLE ... WITH ()

- src/process_utility.c
- src/with_clause/create_table_with_clause.c
- src/with_clause/create_table_with_clause.h
- test/expected/create_table_with.out
- test/sql/create_table_with.sql
> Support associated_schema and associated_table_prefix in CREATE TABLE ... WITH ()

- .unreleased/pr_7893
- .unreleased/pr_7903
- .unreleased/pr_7910
- .unreleased/pr_7912
- .unreleased/pr_7913
- .unreleased/pr_7935
- .unreleased/pr_7941
- .unreleased/pr_7954
- .unreleased/uuid-segmentby-grouping-segfault
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Forwardport of 2.19.3

- tsl/test/expected/compression_qualpushdown.out
- tsl/test/sql/compression_qualpushdown.sql
Add some VACUUMs.
Needed for https://github.com/timescale/timescaledb/pull/7551
> Stabilize the compression_qualpushdown test

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- scripts/upload_ci_stats.sh
> Install jq explicitly in workflows that use upload_ci_stats

- CMakeLists.txt
This simplifies the build configuration a little.
> Detect ccache and CC for TimescaleDB from pg_config --cc

- src/bgw/job.c
> Use proper ERRCODE on jobs

- .unreleased/pr_8031
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
- tsl/src/compression/compression.h
- tsl/src/compression/compression_dml.c
- tsl/test/expected/compression_update_delete-15.out
- tsl/test/expected/compression_update_delete-16.out
- tsl/test/expected/compression_update_delete-17.out
- tsl/test/sql/compression_update_delete.sql.in
> Fix reporting of deleted tuples for direct batch delete

- src/guc.c
> Add missing sentry value in compress_truncate_behaviour_options

- .github/workflows/trigger-prerelease-tests.yaml
> Trigger prerelease tests via workflow

- .github/workflows/sanitizer-build-and-test.yaml
> Fix log directory in sanitizer test

- src/cache.c
- src/cache.h
- src/chunk.c
- src/chunk_adaptive.c
- src/dimension.c
- src/hypertable.c
- src/hypertable_cache.c
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/modify_hypertable.c
- src/planner/planner.c
- src/process_utility.c
- src/telemetry/stats.c
- src/ts_catalog/chunk_column_stats.c
- src/ts_catalog/tablespace.c
- src/utils.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/chunk.c
- tsl/src/chunk_api.c
- tsl/src/compression/api.c
- tsl/src/continuous_aggs/common.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/insert.c
- tsl/src/continuous_aggs/options.c
- tsl/src/continuous_aggs/planner.c
- tsl/src/continuous_aggs/repair.c
- tsl/src/reorder.c
> Modify cache_destroy to clear the pointer

- version.config
> 2.20 release - bump to next version

- tsl/src/nodes/skip_scan/planner.c
Use `get_attnum` and `get_attname` instead of building TupleDesc maps to map distinct var from hypertable to chunk.
> Avoid locking tables to map distinct var in SkipScan

- src/cross_module_fn.h
- src/process_utility.c
- src/with_clause/alter_table_with_clause.c
- src/with_clause/alter_table_with_clause.h
- src/with_clause/create_materialized_view_with_clause.c
- src/with_clause/create_materialized_view_with_clause.h
- src/with_clause/create_table_with_clause.c
- src/with_clause/create_table_with_clause.h
- tsl/src/compression/create.c
- tsl/src/compression/create.h
- tsl/src/continuous_aggs/options.c
- tsl/test/expected/create_table_with.out
- tsl/test/sql/create_table_with.sql
> Support orderby and segmentby in CREATE TABLE WITH

- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/expected/transparent_decompression_ordered_index-16.out
- tsl/test/expected/transparent_decompression_ordered_index-17.out
- tsl/test/sql/transparent_decompression_ordered_index.sql.in
> Stabilize the transparent_decompression_ordered_index test

- tsl/test/expected/vector_agg_default.out
- tsl/test/sql/vector_agg_default.sql
> Stabilize the vector_agg_default test

- src/with_clause/alter_table_with_clause.c
- src/with_clause/create_materialized_view_with_clause.c
- src/with_clause/create_table_with_clause.c
- test/expected/create_chunks.out
- test/expected/create_table_with.out
- test/sql/create_chunks.sql
- test/sql/create_table_with.sql
- tsl/test/expected/cagg_ddl-15.out
- tsl/test/expected/cagg_ddl-16.out
- tsl/test/expected/cagg_ddl-17.out
- tsl/test/expected/compression_update_delete-15.out
- tsl/test/expected/compression_update_delete-16.out
- tsl/test/expected/compression_update_delete-17.out
- tsl/test/expected/create_table_with.out
- tsl/test/sql/cagg_ddl.sql.in
- tsl/test/sql/compression_update_delete.sql.in
- tsl/test/sql/create_table_with.sql
Rename some WITH option names to make them more generic:
chunk_time_interval => chunk_interval
time_column => partition_column
> Rename CREATE TABLE WITH options

- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
> Stabilize the compression_ddl test

- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
temporary fix for 2.20.x release branch for the change of the version.config file
> Fix new version schema

- src/nodes/modify_hypertable.c
Since we dropped PG14 support this code is no longer needed.
> Remove special handling of rows and width for PG14

- src/copy.c
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/modify_hypertable.c
- src/nodes/modify_hypertable_exec.c
- src/planner/planner.c
Remove some nesting and some outdated comments regarding PG14.
Also remove some dead code in ChunkDispatch and ChunkInsertState
> Small refactor to replace_modify_hypertable_paths

- .unreleased/pr_8126
- .unreleased/pr_8145
- .unreleased/pr_8151
- .unreleased/pr_8162
- .unreleased/pr_8163
- .unreleased/pr_8171
- .unreleased/sort-transform-join
- sql/CMakeLists.txt
- version.config
Follow up: https://github.com/timescale/timescaledb/pull/8185
> Forwardport 2.20.1 release artefacts

- sql/updates/post-update.sql
- test/sql/updates/post.repair.cagg_joins.sql
- tsl/src/hypercore/hypercore_handler.c
- tsl/test/isolation/specs/CMakeLists.txt
> Remove PG14 leftovers

- tsl/test/expected/compression_insert.out
- tsl/test/sql/compression_insert.sql
> Add upsert test cases for UUID and Numeric data types

- .unreleased/fix_8107
- tsl/src/nodes/skip_scan/planner.c
- tsl/test/expected/plan_skip_scan-15.out
- tsl/test/expected/plan_skip_scan-16.out
- tsl/test/expected/plan_skip_scan-17.out
- tsl/test/expected/skip_scan.out
- tsl/test/sql/include/skip_scan_query.sql
> Adjust skipscan cost for quals needing sequential scan of indexed data

- tsl/test/expected/vectorized_aggregation.out
- tsl/test/sql/vectorized_aggregation.sql
> Stabilize vectorized_aggregation test

- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.h
> Remove unused CAgg policy API code

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- tsl/test/expected/compress_bloom_sparse.out
- tsl/test/shared/expected/compress_bloom_sparse_compat.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/compress_bloom_sparse_compat.sql
- tsl/test/sql/compress_bloom_sparse.sql
* Binary compatibility test for text hashes (checks that hashing for bloom filter is the same across platforms).
* Test with an array column.
> Add more bloom filter tests

- .unreleased/null-array
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/sql/decompress_vector_qual.sql
This was not handled properly.
> Fix error with null array in vectorized scalar array operation

- tsl/test/expected/hypercore_scans.out
- tsl/test/sql/hypercore_scans.sql
> Fix flaky hypercore_scans test

- test/sql/updates/post.catalog.sql
> Include compression_algorithm in update/downgrade test

- .unreleased/pr_8314
- src/loader/loader.c
timescaledb_lake extension added to list of supported extensions by loader
> Loader changes for timescaledb_lake extension

- tsl/src/continuous_aggs/insert.c
- tsl/test/expected/cagg_usage-15.out
- tsl/test/expected/cagg_usage-16.out
- tsl/test/expected/cagg_usage-17.out
- tsl/test/sql/cagg_usage.sql.in
Since the flaky test checks for "new" internal errors, this causes CI failures in other PRs when you modify tests.
It's the first error message that is the problem, the other ones were added only because I am modifying the code.
> Add errcode to invalidation trigger function error

- scripts/changelog/generate.sh
- scripts/release/build_post_release_artefacts.sh
CHANGELOG
- adds the newly introduced GUCs
- fixes the links from the .unlreleased files
Post release
- remove .unreleased files
> Release action fixes

- .github/workflows/release_feature_freeze_ceremony.yaml
- .github/workflows/release_post_release_ceremony.yaml
- version.config
- on new minor releases, create a PR that bumps the minor + 1 in version.config on main
- added a bit more description of what's happening in the file headers
> Bump version.config on main

- tsl/src/continuous_aggs/create.c
- tsl/src/nodes/gapfill/gapfill_internal.h
- **Add missing include to gapfill_internal.h**
> Add missing include to gapfill_internal.h

- tsl/src/continuous_aggs/invalidation.c
Remove debug printout since it is causing memory issues.
> Remove debug printout

- version.config
> Bump to next patch version on release branch

- .github/gh_matrix_builder.py
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/snapshot-abi.yaml
- tsl/test/isolation/specs/split_chunk_concurrent.spec
> Remove extensions no longer used from CI

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
move artefacts from release branch to main
> Forwardport 2.21.1

- .pull-review
> Update the list of reviewers for the pull-review bot

- .github/workflows/release_build_packages.yml
- .github/workflows/release_feature_freeze_ceremony.yaml
- .github/workflows/release_post_release_ceremony.yaml
- moved away from existing PR creation action as they failed with the changelog
- fixed issue which created the release branch for non .0 versions
- simplified steps
- leverage summaries for better overview of what happened
> Fix and improve release actions

- .github/workflows/release_feature_freeze_ceremony.yaml
- .github/workflows/release_post_release_ceremony.yaml
> Set git config for EON

- version.config
missed the version after 2.21.1
> missed bump

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Forward port 2.21.2

- .github/workflows/release_build_packages.yml
- Fix the output of the package build workflow summary, e.g. https://github.com/timescale/timescaledb/actions/runs/16750045447
- change failure of action to make the workflow finish but fail if one dispatch did not work
> Package release cosmetics

- .unreleased/pr_8471
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
> Forwardport 2.21.3

- test/sql/CMakeLists.txt
> Add net regression tests to SOLO_TESTS

- src/chunk_index.c
This is in prepatation for removal of chunk_index catalog table
> Use postgres catalog for index lookups during CLUSTER

- src/compat/compat.h
> Update version compatibility comment

- tsl/src/compression/compression.c
In PG18, input/output pointer types changed from
`char` to `uint8` for byte arrays. This update
reflects that change.
https://github.com/postgres/postgres/commit/b28c59a6
> Update base64 encode/decode functions for PG18

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
Child EquivalencyMembers are not not present in ec_members but are stored in a separate list to speedup lookup in planner.
https://github.com/postgres/postgres/commit/d69d45a5
> Maintain child em lists in PG 18

- src/process_utility.c
https://github.com/postgres/postgres/commit/80d7f990
> Use ATAlterConstraint for ALTER TABLE stmt in PG18

- src/planner/agg_bookend.c
- src/planner/planner.c
https://github.com/postgres/postgres/commit/0d2aa4d4
> Track sort direction in SortGroupClause for PG18

- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- tsl/src/compression/compression_dml.c
- **Remove ChunkDispatch references from compression**
> Remove ChunkDispatch references from compression

- src/chunk_tuple_routing.c
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- src/nodes/modify_hypertable.c
- src/nodes/modify_hypertable_exec.c
- **Remove hypertable_result_rel_info from ChunkDispatch**
- **Used counters from ChunkTupleRouting**
- **Remove tracking of previous chunk from ChunkDispatch**
- **Unify COPY and INSERT path ChunkInsertState creation**
> ChunkDispatch refactoring

- src/nodes/modify_hypertable_exec.c
Move merge action handling into tuple routing block to avoid
rechecking ChunkInsertState
> Small refactor to MERGE code

- .unreleased/pr_8654
- sql/size_utils.sql
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
- **Fix approximate_row_count for compressed chunks**
> Fix approximate_row_count for compressed chunks

- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/init.c
> Remove some distributed CAggs leftovers

- README.md
> fix: fixing readme tigerdata logo

- .github/workflows/windows-build-and-test.yaml
Apply a workaround I found on the internet to change the package archive address.
> Fix the package update on WSL

- src/process_utility.c
- tsl/src/compression/api.c
- tsl/src/compression/recompress.c
> Remove Hypercore TAM references from comments

- .unreleased/pr_7766
- .unreleased/pr_8550
- .unreleased/pr_8593
- .unreleased/pr_8599
- .unreleased/pr_8607
- .unreleased/pr_8638
- .unreleased/pr_8644
- .unreleased/pr_8657
- .unreleased/pr_8659
- .unreleased/pr_8693
- .unreleased/pr_8707
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
* cherrypicked: 687331da33dce1be390d277cbaa0eef62e6ede9d
* adjusted post release CHANGELOG message https://github.com/timescale/timescaledb/pull/8726
* added up & downgrade files
* update pervious version in version.config
> Forward port 2.22.1

- src/nodes/modify_hypertable_exec.c
> Remove dead FDW code from ModifyHypertable

- sql/CMakeLists.txt
- version.config
Set the 2.22.2 config. Post-release action item to always keep the branch in a ready-to-release state
> Set 2.22.2 config
