- src/chunk.c
- test/expected/alter.out
- test/sql/alter.sql
When triggering chunk creation on a hypertable with non-default
statistics targets by a user different from the hypertable owner
the chunk creation will fail with a permission error. This patch
changes the chunk table creation to run the attribute modification
as the table owner.
Fixes #4474
> Fix chunk creation on hypertables with non-default statistics

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release is a patch release. We recommend that you upgrade at the
next available opportunity.
Among other things this release fixes several memory leaks, handling
of TOASTed values in GapFill and parameter handling in prepared statements.
**Bugfixes**
* #4517 Fix prepared statement param handling in ChunkAppend
* #4522 Fix ANALYZE on dist hypertable for a set of nodes
* #4526 Fix gapfill group comparison for TOASTed values
* #4527 Handle stats properly for range types
* #4532 Fix memory leak in function telemetry
* #4534 Use explicit memory context with hash_create
* #4538 Fix chunk creation on hypertables with non-default statistics
**Thanks**
* @3a6u9ka, @bgemmill , @hongquan, @stl-leonid-kalmaev and @victor-sudakov for reporting a memory leak
* @hleung2021 and @laocaixw  for …
> Release 2.7.2

- .github/workflows/coccinelle.yaml
Switch coccinelle CI action to ubuntu 22.04 because 21.10 is EOL
and stopped working.
> Fix coccinelle CI action

- .github/workflows/apt-packages.yaml
Ubuntu 21.10 is EOL and we no longer build packages for it.
> Remove ubuntu 21.10 (impish) from package tests

- src/chunk.h
This patch removes ts_chunk_add_foreign_table_as_chunk function
never had an implementation added and the ASSERT_IS_NULL_OR_VALID_CHUNK
macro which has no user.
> Remove unused function and macro

- .github/workflows/procedural.yaml
So far, issues were added to the bug board when they are labeled;
issues that are not on the board and receive a response were not
automatically added. This patch extends the workflow trigger; all
bug issues that receive a response are also assigned to the board.
> Trigger bug board assignment on issue comment

- .github/workflows/memory-tests.yaml
- scripts/memory_leaks.sql
- scripts/test_memory_spikes.py
Unlike the existing memory leak test which tests a single INSERT
of 100.000.000 rows in a single transaction, this runs 1000000
SELECT, 10K UPDATE and 10K INSERT queries in the same backend.
> Add a generic memory leak test to CI

- CHANGELOG.md
- src/process_utility.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
Enables adding a boolean column with default value to a compressed table.
This limitation was occurring due to the internal representation of default 
boolean values like 'True' or 'False', hence more checks are added for this.
Fixes https://github.com/timescale/timescaledb/issues/4486
> Fix alter column for compressed table

- sql/restoring.sql
- test/expected/pg_dump.out
- test/sql/pg_dump.sql
In the session timescaledb_post_restore() was called the value for
timescaledb.restoring might not be changed because the reset_val
for the GUC was still on. We have to use explicit SET in this
session to adjust the GUC.
Fixes #4267
> Fix timescaledb_post_restore GUC handling

- scripts/dump_meta_data.sql
The dump_meta_data sql script used an external call to date to get
the current data which does not work on windows. This patch changes
the script to use now() instead to get the current time and date.
Fixes #3674
> Fix dump_meta_data for windows

- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
This speeds up the planning by avoiding the repeated lookup of the
chunk metadata.
Gives about 10% speedup on planning-only queries like `explain select * from my_hypertable`.
> Add chunks to baserel cache on chunk exclusion

- src/planner/planner.c
- tsl/test/expected/dist_query.out
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/sql/dist_fetcher_type.sql
- tsl/test/sql/dist_query.sql
When a query has multiple distributed hypertables the row-by-by
fetcher cannot be used. This patch adjusts the fetcher type
selection to always use cursor fetcher when multiple distributed
hypertables are involved.
Fixes #4518
> Throw better error message on incompatible row fetcher settings

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_errors.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/sql/cagg_errors.sql
- tsl/test/sql/continuous_aggs.sql
Users often execute TopN like queries over Continuous Aggregates and
now with the release 2.7 such queries are even faster because we
remove the re-aggregation and don't store partials anymore.
Also the previous PR #4430 gave us the ability to create indexes
direct on the aggregated columns leading to performance improvements.
But there are a noticable performance difference between
`Materialized-Only` and `Real-Time` Continuous Aggregates for TopN
queries.
Enabling the ORDER BY clause in the Continuous Aggregates definition
result in:
1) improvements of the User Experience that can use this so commom
clause in SELECT queries
2) performance improvements because we give the planner a chance to
use the MergeAppend node by producing ordered datasets.
Closes #4456
> Enable ORDER BY on Continuous Aggregates

- coccinelle/hash_create.cocci
- src/cache.c
- tsl/src/fdw/data_node_chunk_assignment.c
- tsl/src/fdw/shippable.c
This patch fixes callsites that set an explicit memory context
in the control structure but do not specify the HASH_CONTEXT flag
leading to the hash table being created in TopMemoryContext.
This patch also changes call sites that want to create the hash
table in TopMemoryContext to be explicit about this.
Additionally this patch adds a coccinelle script to detect these
errors and prevent adding similar code in the future.
> Fix hash_create calls without HASH_CONTEXT flag

- src/chunk.c
- src/chunk_constraint.c
- src/chunk_constraint.h
- src/dimension.c
- test/expected/create_hypertable.out
- test/isolation/expected/concurrent_add_dimension.out
- test/isolation/specs/CMakeLists.txt
- test/isolation/specs/concurrent_add_dimension.spec.in
- test/sql/create_hypertable.sql
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/sql/dist_hypertable.sql.in
This change allows to create new dimensions even with
existing chunks.
It does not modify any existing data or do migration,
instead it creates full-range (-inf/inf) dimension slice for
existing chunks in order to be compatible with newly created
dimension.
All new chunks created after this will follow logic of the new
dimension and its partitioning.
Issue: https://github.com/timescale/timescaledb/issues/2818
> Support add_dimension() with existing data

- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/post-update.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/dimension.c
- src/dimension.h
- src/hypercube.c
- src/hypertable.c
- src/hypertable.h
- src/ts_catalog/CMakeLists.txt
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- src/ts_catalog/dimension_partition.c
- src/ts_catalog/dimension_partition.h
- test/expected/drop_rename_hypertable.out
- test/expected/partition.out
- test/sql/partition.sql
- tsl/src/data_node.c
- tsl/src/hypertable.c
- tsl/test/expected/chunk_api.out
- tsl/test/expected/data_node.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_triggers.out
- tsl/test/expected/read_only.out
- tsl/test/sql/data_node.sql
- tsl/test/sql/dist_hypertable.sql.in
- tsl/test/sql/dist_triggers.sql
Add a new metadata table `dimension_partition` which explicitly and
statefully details how a space dimension is split into partitions, and
(in the case of multi-node) which data nodes are responsible for
storing chunks in each partition. Previously, partition and data nodes
were assigned dynamically based on the current state when creating a
chunk.
This is the first in a series of changes that will add more advanced
functionality over time. For now, the metadata table simply writes out
what was previously computed dynamically in code. Future code changes
will alter the behavior to do smarter updates to the partitions when,
e.g., adding and removing data nodes.
The idea of the `dimension_partition` table is to minimize changes in
the partition to data node mappings across various events, …
> Add stateful partition mappings

- .github/workflows/stalebot.yaml
GitHub issues that are closed by a collaborator (or the stalebot)
cannot be re-opened by the issue author. This commit changes the
close message of the stale bot to reflect this.
> Change the stalebot close message.

- .github/workflows/abi.yaml
The most recent versions of the postgres docker image no longer
contain git by default. The version available also contains a fix
for the git vulnerability that changed the git behaviour to check
file ownership.
Since we bind mount the source checkout into the build container
the user of the checkout is unlikely to match the user inside the
container. This patch configures git to skip the owner check for
the bind-mounted directory.
https://github.blog/2022-04-12-git-security-vulnerability-announced/
> Fix ABI test git errors

- appveyor.yml
- tsl/src/remote/connection.c
This PR switches the postgres connections to data nodes to non-blocking mode for the duration of the COPY. Other operations on these connections are unaffected.
It serves as a preparation for working with multiple connections simultaneously. No functional changes are introduced, but it's done as a separate PR to simplify review and debugging/bisect in case we introduce an error.
Part of https://github.com/timescale/timescaledb/pull/4285
>  Use non-blocking data node connections for COPY

- .github/workflows/linux-build-and-test.yaml
- scripts/gh_matrix_builder.py
The output format of the isolation tester got changed by pg upstream
and backported to earlier versions. This means PG versions before
the backport have different output format then latest PG version.
We used to add all the isolation tests to the IGNORE list for those
PG versions but that is error prone and often forgotten when new
isolation tests are added. This patch skips the isolation test on
PG versions with incompatible output format.
> Dont run isolation tests on PG 12.0 and 13.2

- src/process_utility.c
- test/expected/grant_hypertable.out
- test/sql/grant_hypertable.sql
When working on a fix for #4555 discovered that executing
`{GRANT|REVOKE} .. ON ALL TABLES IN SCHEMA` in an empty schema lead to
an assertion because we change the way that command is executed by
collecting all objects involved and processing one by one.
Fixed it by executing the previous process utility hook just when the
list of target objects is not empty.
Fixes #4581
> Fix assertion in GRANT .. ON ALL TABLES IN SCHEMA

- CHANGELOG.md
- src/partitioning.c
- test/expected/hash.out
- test/sql/hash.sql
When executing `get_partition_{hash|for_key}` inside an IMMUTABLE
function we're getting the following error:
`ERROR: unsupported expression argument node type 112`
This error is because the underlying `resolve_function_argtype` was not
dealing with `T_Param` node type.
Fixed it by dealing properly with `T_Param` node type returning the
`paramtype` for the argument type.
Fixes #4575
> Fix partitioning functions

- src/partitioning.c
- src/utils.c
In partitioning.c the function `resolve_function_argtype` deal with
some primitive nodes in order to resolve the argument type for hashing
functions.
Refactoring the code a bit and added the primitive nodes (primnodes.h)
to the `ts_get_node_name` and improve the error message of
`resolve_function_argtype` showing the name of the node type instead of
the code when an unsupported node type is detected.
> Add primnodes.h to ts_get_node_name function

- appveyor.yml
- tsl/src/compression/compression.c
Sanity check the compression header for sane algorithm
before using it as index into an array. Previously
this would result in a segfault and could happen with
corrupted compressed data.
> Fix segfaults in compression code with corrupt data

- src/chunk.c
- src/chunk_constraint.c
- src/chunk_constraint.h
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
When a table is added to an inheritance hierrachy, PG checks
if all check constraints are present on this table. When a OSM chunk
is added as a child of a hypertable with constraints,
make sure that all check constraints are replicated on the child OSM
chunk as well.
> Add inherited check constraints to OSM chunk

- CHANGELOG.md
- src/chunk.c
- src/utils.c
- src/utils.h
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_permissions.out
- tsl/test/sql/cagg_permissions.sql
If a default privilege is configured and applied to a given Continuous
Aggregate during it creation just the user view has the ACL properly
configured but the underlying materialization hypertable no leading to
permission errors.
Fixed it by copying the privileges from the user view to the
materialization hypertable during the Continous Aggregate creation.
Fixes #4555
> Handle properly default privileges on CAggs

- .github/ci_settings.py
- .github/gh_config_reader.py
- .github/gh_matrix_builder.py
- .github/workflows/abi.yaml
- .github/workflows/coverity.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/stalebot.yaml
- .github/workflows/update-test.yaml
This patch adds a new settings file for common github action settings.
Instead of repeating latest pg versions in every github workflow we
can read the settings from this central file.
> Centralize CI settings

- tsl/src/compression/compression.c
- tsl/test/expected/compression.out
- tsl/test/expected/dist_move_chunk.out
- tsl/test/sql/compression.sql
The sequence number of the compressed tuple is per segment by grouping
and should be reset when the grouping changes to prevent overflows with
many segmentby columns.
> Reset compression sequence when group resets

- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
Change chunk_utils_internal test to not use oid but instead use the
role name. Using the oid can lead to failing tests when oid assignment
is different especially when run with regresschecklocal-t.
> Fix chunk_utils_internal test

- test/sql/CMakeLists.txt
They should be functioning after 2.7.2
> Re-enable telemetry tests

- src/telemetry/functions.c
Applies the same fix as PR #4534 to the hash table created in the telemetry background worker.
(unlikely to cause a serious memory leak b/c apparently BGWs don't live long, but it's needed for code-quality anyway)
> Fix telemetry BGW memory leak

- coccinelle/hash_create.cocci
- src/loader/bgw_launcher.c
Previously the hash_create coccinelle script would not detect
hash_create calls that declared the return variable in the same
statement or that used the return value of hash_create as return
value.
> Fix coccinelle hash_create script

- tsl/src/bgw_policy/policies_v2.c
The same code is executed because the 'then' and
'else' branches are identical. Discovered by
Coverity CID 380009.
> Fix identical branches

- test/pg_hba.conf.in
- test/test-defs.cmake
Windows does not support unix domain socket connections so we comment
out `local` lines in pg_hba.conf. On PG12 on Windows this will prevent
server start otherwise.
> Disable local line in pg_hba.conf on Windows

- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/options.c
The Postgres header utils/int8.h is not necessary and it was removed in
version 15 by commit postgres/postgres@cfc7191dfea330dd7a71e940d59de78129bb6175
> Remove unused header file

- src/compat/compat.h
- tsl/src/continuous_aggs/invalidation.c
PostgreSQL 15 changed `scanint8` to `pg_strtoint64`, so added it to the
compatibility layer and use just of pg_strtoint64 in source code.
postgres/postgres@cfc7191dfea330dd7a71e940d59de78129bb6175
> Change usage of scanint8 to pg_strtoint64

- src/telemetry/functions.c
We cannot rely on the planner initializing the shared hashmap reference since there's no guarantee we'll actually run SPI code in the BGW before we marshal the request. This commit adds initialization checking to `ts_function_telemetry_read()` itself to ensure it will always read from an initialized state if possible. As this code run very infrequently, it currently checks every time and does not skip if it once saw a lack of entries. This is unlikely to matter.
It would be nice to test this more explicitly, but that will likely have to wait until we have better reporting about BGW internals. For now I've relied on manual testing. Look at the telemetry report for the DB with UUID `d412018f-a435-492f-9ab6-b09d480ab1c1` received at timestamp `2022-08-16 18:56:53+00` for an example.
> Fix telemetry initialization

- .github/workflows/windows-build-and-test.yaml
Enable the Windows CI workflow in nightly runs. In nightly runs
the CI run will also test release configuration in addition to
the debug configuration run on PRs.
> Enable Windows workflow in nightly CI run

- .github/workflows/windows-packages.yaml
Change the windows package test to use explicit postgres versions
and test both minimum and maximum supported postgres minor version.
> Improve windows package test

- sql/views.sql
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
Modify timescaledb_information.chunks
view to filter out osm chunks. We do not want
user to invoke chunk specific operations on
OSM chunks.
> Filter out osm chunks from chunks information view

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Fix ALTER TABLE RENAME TO command execution on a distributed
hypertable, make sure data node list is set and command is
executed on the data nodes.
Fix #4491
> Fix rename for distributed hypertable

- src/telemetry/telemetry.c
- test/expected/telemetry.out
This commit unconditionally schema-qualifies the function telemetry. In the default setting `format_procedure()` only schema-qualifies things that aren't on the search path. This could cause to much variation across users. Further, it'd be nice to tell if functions in-use are from an experimental schema or a main one.
> Schema-qualify function telemetry

- CHANGELOG.md
- src/time_bucket.c
- test/expected/timestamp.out
This patch makes time_bucket_ng work correctly with origin values
that are after the timestamp value to be bucketed.
Fixes #4117
> Fix time_bucket_ng origin handling

- src/chunk.c
- src/planner/planner.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
The OSM chunk registers a dummy primary dimension range in the TimescaleDB catalog. Use the max interval of the dimension instead of the min interval i.e
use range like [Dec 31 294246 PST, infinity).
Otherwise, policies can try to apply the policy on an OSM chunk.
Add test with policies for OSM chunks
> Modify OSM chunk constraint info in chunk catalog

- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/expected/cagg_dump.out
- tsl/test/expected/cagg_multi.out
- tsl/test/expected/cagg_query-12.out
- tsl/test/expected/cagg_query-13.out
- tsl/test/expected/cagg_query-14.out
- tsl/test/expected/cagg_refresh.out
- tsl/test/expected/cagg_usage.out
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/continuous_aggs_deprecated.out
- tsl/test/expected/debug_notice.out
- tsl/test/expected/dist_ddl.out
- tsl/test/expected/dist_grant-12.out
- tsl/test/expected/dist_grant-13.out
- tsl/test/expected/dist_grant-14.out
- tsl/test/isolation/specs/cagg_insert.spec
- tsl/test/isolation/specs/cagg_multi.spec
- tsl/test/isolation/specs/cagg_multi_dist_ht.spec
- tsl/test/postgresql.conf.in
- tsl/test/sql/cagg_dump.sql
- tsl/test/sql/cagg_multi.sql
- tsl/test/sql/cagg_query.sql.in
- tsl/test/sql/cagg_usage.sql
- tsl/test/sql/continuous_aggs.sql
- tsl/test/sql/continuous_aggs_deprecated.sql
- tsl/test/sql/include/cagg_ddl_common.sql
Remove client_min_messages = LOG where not needed. In tests where it's necessary, adjust the output to include the `LOG: statement` messages.
The statement logging is needed to debug the test failures.
> Try to enable statement logging in the tests

- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/chunk_append.h
- src/nodes/chunk_append/exec.c
- src/nodes/chunk_append/planner.c
- test/expected/append-12.out
- test/expected/append-13.out
- test/expected/append-14.out
- test/sql/include/append_load.sql
- test/sql/include/append_query.sql
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/shared/expected/ordered_append-12.out
- tsl/test/shared/expected/ordered_append-13.out
- tsl/test/shared/expected/ordered_append-14.out
Add runtime exclusion for statements such as :
WHERE col @> ANY(subselect)
In this case, if the subselect returns no rows, the
result is always false. This is independent of whether
or not the partitioning columns is referenced.
Also fix a bug (or missed optimization) if the subselect
hasn't been executed by the time the runtime exclusion
executes.
> Add runtime exclusion for ANY using subselect

- sql/ddl_api.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/guc.c
- src/guc.h
- src/hypertable.c
- src/hypertable.h
- tsl/src/hypertable.c
- tsl/test/expected/dist_ddl.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/dist_ddl.sql
This PR introduces a new `distributed` argument to the
create_hypertable() function as well as two new GUC's to
control its default behaviour: timescaledb.hypertable_distributed_default
and timescaledb.hypertable_replication_factor_default.
The main idea of this change is to allow automatic creation
of the distributed hypertables by default.
> Add hypertable distributed argument and defaults 

- src/bgw/job_stat.c
- src/bgw/job_stat.h
- src/bgw/scheduler.c
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
The scheduler detects the following three types of job failures:
1.Jobs that fail to launch (due to shortage of background workers)
2.Jobs that throw a runtime error
3.Jobs that crash due to a process crashing
In cases 2 and 3, additive backoff is applied in calculating the next
start time of a failed job.
In case 1 we previously retried to launch all jobs that failed to launch
simultaneously.
This commit introduces exponential backoff in case 1,
randomly selecting a wait time in [2, 2 + 2^f] seconds at microsecond granularity.
The aim is to reduce the collision probability for jobs that compete
for a background worker. The maximum backoff value is 1 minute.
It does not change the behavior for cases 2 and 3.
Fixes #4562
> Exponentially backoff when out of background workers

- src/utils.c
PG15 removes T_Expr nodeTag because it's an abstract type.
https://github.com/postgres/postgres/commit/85399291
> Adjust ts_get_node_name for PG15

- src/compat/compat.h
- tsl/src/reorder.c
PG15 removes "recheck" argument from check_index_is_clusterable
and consolidate VACUUM xid cutoff logic.
https://github.com/postgres/postgres/commit/b940918d
https://github.com/postgres/postgres/commit/efa4a946
> Adjust reorder code for PG15

- src/ts_catalog/compression_chunk_size.c
Since the process that adjusts the compressed chunk statistics gets
run during VACUUM we do not want to throw any errors in that process
to let the VACUUM succeed.
> Don't error when compression metadata is missing

- src/bgw/job_stat.c
There is a potential overflow in shifting in the code. The shift count
should be less than 20, so this should be safe, but adding a cast to
ensure that types match later usage and also extending the assert to
capture bugs.
----
Fix max backoff on MAX_CONSECUTIVE_FAILURES
----
> Fix coverity warning about potential overflow

- tsl/src/remote/connection.c
Apparently, pqFlush can report a success status, but the underlying
socket can become invalid at the same time. Check for this.
In passing, also change to the proper error reporting functions that
use the connection error information, where needed.
> Fix a possible error while flushing the COPY data

- test/expected/copy_memory_usage.out
- test/sql/copy_memory_usage.sql
Increase the failure threshold.
> Make the copy_memory_usage test less flaky

- CHANGELOG.md
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/ts_catalog/catalog.h
The primary key for compression_chunk_size was defined as chunk_id, compressed_chunk_id but other places assumed chunk_id is actually unique and would error when it was not. Since it makes no sense to have multiple entries per chunk since that reference would be to a no longer existing chunk the primary key is changed to chunk_id only with this patch.
> Fix compression_chunk_size primary key

- CHANGELOG.md
- src/planner/planner.c
- src/planner/space_constraint.c
- tsl/test/shared/expected/space_constraint-12.out
- tsl/test/shared/expected/space_constraint-13.out
- tsl/test/shared/expected/space_constraint-14.out
- tsl/test/shared/sql/space_constraint.sql.in
Since we do not use our own hypertable expansion for SELECT FOR UPDATE
queries we need to make sure to add the extra information necessary to
get hashed space partitions with the native postgres inheritance
expansion working.
Fixes #4683
> Fix chunk exclusion for space partitions in SELECT FOR UPDATE queries

- src/chunk.c
- src/chunk.h
- src/chunk_scan.c
- src/chunk_scan.h
- src/compat/compat.h
- src/hypertable_restrict_info.c
- src/hypertable_restrict_info.h
- src/planner/expand_hypertable.c
We don't have to look up the dimension slices for dimensions for which
we don't have restrictions.
This also fixes a planning time regression introduced in 2.7. It was introduced in this commit https://github.com/timescale/timescaledb/commit/37190e8a8#diff-e488f45c83647e5d9415d438f2e79eb2780639b7888c7533890b6c577e02d03dL852-L857
We stopped using the fast path for case where there are no restrictions, and the normal path turned out to be slower. This commit speeds it up to the previous level.
The lookup logic this PR introduces is basically the same as the one introduced for `chunk_point_find_chunk_id` by https://github.com/timescale/timescaledb/pull/4390 . The difference is that here the conditions may be underspecified, so multiple chunks match.
> Speed up chunk search by restriction clauses

- CHANGELOG.md
- src/planner/constify_now.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
Allow planner chunk exclusion in subqueries. When we decicde on
whether a query may benefit from constifying now and encounter a
subquery peek into the subquery and check if the constraint
references a hypertable partitioning column.
Fixes #4524
> Fix planner chunk exclusion for VIEWs

- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
Timescale 2.8 released a migration path from the old format of Continuous Aggregate to the new format (#4552).
Unfortunately it lacks of proper tests when a non-superuser execute the migration. For a non-superuser execute the migration properly it requires SELECT/INSERT/UPDATE permissions in some catalog objects:
* _timescaledb_catalog.continuous_agg_migrate_plan
* _timescaledb_catalog.continuous_agg_migrate_plan_step
* _timescaledb_catalog.continuous_agg_migrate_plan_step_step_id_seq
Improved the regression tests to cover the lack of permissions in the catalog objects for non-superusers.
> Add CAGG migration permission tests

- .github/workflows/pgspot.yaml
- sql/cagg_migrate.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
Removed the underline character prefix '_' from the parameter names of the procedure `cagg_migrate`. The new signature is:
```sql
cagg_migrate(
IN cagg regclass,
IN override boolean DEFAULT false,
IN drop_old boolean DEFAULT false
)
```
> Change parameter names of cagg_migrate procedure

- .github/workflows/procedural.yaml
If an issue is labeled with `needs-more-info` it is automatically
considered as waiting for author and we should move it to the column
for that.
> Add automation for waiting on author

- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
The out of background worker test in bgw_db_scheduler is flaky and fails very often, especially in the 32bit environment and on windows. This patch removes that specific test from bgw_db_scheduler. If we want to test this specific part of the scheduler this should be better rewritten in an isolation test.
> Remove flaky test from bgw_db_scheduler

- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
Patch #4425 introduced regression test failures, namely, a crash in function `ts_bgw_job_update_by_id`. The failures are due to the COMMIT statement in the custom check procedure. This patch removes that particular test case from bgw_custom.
> Remove test case causing bgw_custom crash

- .github/workflows/pgspot.yaml
Previously the pgspot call used in CI did not properly check the update script. Unsafe function creations for functions with changed signatures could go undetected in the update script.
> Fix pgspot update script check

- src/planner/planner.c
- tsl/src/fdw/scan_exec.c
- tsl/src/remote/row_by_row_fetcher.c
- tsl/test/shared/expected/dist_fetcher_type.out
- tsl/test/shared/sql/dist_fetcher_type.sql
We have to prepare the data node statement in this case, and COPY queries don't work with prepared statements.
Fixes #4695
> Do not use row-by-row fetcher for parameterized plans

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- tsl/test/sql/CMakeLists.txt
Pretty print the active query during a coredump when printing the stacktrace for a coredump.
> Include running query in CI coredump information

- src/compat/compat.h
Fix an error in the PG15 portion of the vacuum_set_xid_limits_compat() preprocessor macro.
> Fix vacuum_set_xid_limits_compat() macro

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
The patch #4714 introduces the extraction of the running query from a coredump by calling `gdb` with two commands. These commands are separated by a newline character. This character may not always be correctly converted to a new line before being processed by gdb, resulting in the following error ([link to failed CI run](https://github.com/timescale/timescaledb/actions/runs/3078445332/jobs/4974007557)):
`Invalid character '\' in expression.`
This PR ensures the proper handling of the newline character.
> Fix CI coredump information print

- .github/workflows/procedural.yaml
We now have an organization-wide token for automation. This patch changes the name in existing Github actions accordingly.
> Update the name of the automation token

- tsl/src/nodes/gapfill/gapfill_plan.c
Very recent compilers will warn about function pointers with empty argument list. While currently in C func() means a function with an unspecified argument list the next version of the C standard will change this to mean func(void).
> Fix gapfill function signature

- CHANGELOG.md
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/test/isolation/expected/decompression_chunk_and_parallel_query.out
- tsl/test/isolation/expected/decompression_chunk_and_parallel_query_wo_idx.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/decompression_chunk_and_parallel_query.in
- tsl/test/isolation/specs/decompression_chunk_and_parallel_query_wo_idx.in
This patch fixes a deadlock between chunk decompression and SELECT queries
executed in parallel. The change in
a608d7db614c930213dee8d6a5e9d26a0259da61 requests an AccessExclusiveLock
for the decompressed chunk instead of the compressed chunk, resulting in
deadlocks.
In addition, an isolation test has been added to test that SELECT
queries on a chunk that is currently decompressed can be executed.
Fixes #4605
Fixes #2565
> Fix a deadlock when decompressing chunks and performing SELECTs

- .github/workflows/procedural.yaml
In af8e3c6b12035dd45bc7bf61e9420489cfa56eaa, an GitHub action to assign issues to a project column has been introduced. However, this action does not work with organization-wide projects. This patch replaces the used project management action with a more recent one.
Link to failed action run: https://github.com/timescale/timescaledb/actions/runs/3104545193
> Change project management github action

- CHANGELOG.md
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
Instances upgraded to 2.8.0 will end up with a wrong check constraint in catalog table `continuous_aggregate_migrate_plan_step`.
Fixed it by removing and adding the constraint with the correct checks.
Fix #4727
> Fix continuous aggregate migrate check constraint

- sql/cagg_migrate.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
After migrate a Continuous Aggregate from the old format to the new using `cagg_migrate` procedure we end up with the following problems:
* Refresh policy is not copied from the OLD to the NEW cagg;
* Compression setting is not copied from the OLD to the NEW cagg.
Fixed it by properly copying the refresh policy and setting the `timescaledb.compress=true` flag to the new CAGG.
Fix #4710
> Fix Continuous Aggregate migration policies

- .github/workflows/code_style.yaml
- .perltidyrc
To allow perltidy to be used from editors and IDEs, the perltidyrc file is moved from `scripts/perltidyrc` to `.perltidyrc`. This will allow editors and IDEs to quickly find the style file in the root of the repository, where `perltidy` normally searches for the style file.
The workflow is then updated to use the new location, and the two options `--backup-file-extension` and `--backup-and-modify-in-place` are moved to the workflow file to allow editors and IDEs to use whatever method they find useful to process the file.
> Move perltidyrc to root

- CHANGELOG.md
- src/chunk_constraint.c
- test/expected/create_hypertable.out
- test/sql/create_hypertable.sql
Consider a hypertable which has a foreign key constraint on a
referenced table, which is a parititioned table. In such case, foreign
key constraint is duplicated for each of the partitioned table. When
we insert into a hypertable, we end up checking the foreign key
constraint multiple times, which obviously leads to foreign key
constraint violation. Instead we only check foreign key constraint of
the parent table of the partitioned table.
Fixes #4684
> Hypertable FK reference to PostgreSQL partitioned table

- src/bgw/job.c
- src/bgw/job_stat.c
- src/bgw/scheduler.c
- test/src/bgw/scheduler_mock.c
When reading the job status table `bgw_job_stat` and after that
updating it, locks where released after the read, allowing a competing
session to update the job status and trigger a concurrent update error
either in a session doing the update or in the scheduler. Since the
scheduler does not recover after aborting with an error, this caused
the background worker subsystem to stop and not start new jobs.
This commit fixes this by upgrading `RowExclusiveLock` to
`ShareRowExclusiveLock` to ensure that not two sessions tries to update
the row at the same time, remove an initial speculative lock
that are taken when a job status row can be added, and also keeps the
lock until the end of the transaction to prevent other sessions to
update. Since these updating transactions are short, it should …
> Keep locks after reading job status

- CHANGELOG.md
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
This PR does a couple of changes to improve IO usage for compression jobs:
- changes sort memory limits from `work_mem` to `maintenance_work_mem`, reducing the chance to use temp buffers for larger chunks
- moves uncompressed chunk ANALYZE operation after heap has been loaded into shared buffers by the heap scan we need to do in order to sort the chunk contents
> Improve compression job IO performance

- CHANGELOG.md
- src/planner/planner.c
- tsl/test/shared/expected/ordered_append_join-12.out
- tsl/test/shared/expected/ordered_append_join-13.out
- tsl/test/shared/expected/ordered_append_join-14.out
- tsl/test/shared/sql/ordered_append_join.sql.in
This fixes a segfault when INNER JOINing 2 hypertables that are ordered by time.
Fixes #4418
> Fix segfault when INNER JOINing hypertables

- cmake/ScriptFiles.cmake
- sql/job_error_log_retention.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- sql/views.sql
- src/bgw/job.c
- src/bgw/job.h
- src/bgw/job_stat.c
- src/bgw/job_stat.h
- src/bgw/scheduler.c
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- test/expected/chunk_utils.out
- test/expected/drop_rename_hypertable.out
- test/expected/pg_dump.out
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/expected/bgw_policy.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/troubleshooting_job_errors.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/bgw_custom.sql
- tsl/test/sql/bgw_db_scheduler.sql
- tsl/test/sql/troubleshooting_job_errors.sql
- tsl/test/t/006_job_crash_log.pl
- tsl/test/t/CMakeLists.txt
This commit gives more visibility into job failures by making the
information regarding a job runtime error available in an extension
table (`job_errors`) that users can directly query.
This commit also adds an infromational view on top of the table for
convenience.
To prevent the `job_errors` table from growing too large,
a retention job is also set up with a default retention interval
of 1 month. The retention job is registered with a custom check
function that requires that a valid "drop_after" interval be provided
in the config field of the job.
> Add interface for troubleshooting job failures

- .github/workflows/pgspot.yaml
Change the pgspot check to use downgrade_to_version instead of update_from_version.
We use downgrade_to_version instead of update_from_version because when the release PR for a new version has been merged to main but the version is not tagged yet update_from will not exist yet. In all other situations update_from_version and downgrade_to_version should point to the same version.
> Adjust pgspot CI check

- sql/CMakeLists.txt
- tsl/src/remote/connection_cache.c
- tsl/src/remote/connection_cache.h
- tsl/src/remote/dist_commands.c
- tsl/test/isolation/expected/dist_cmd_exec.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/dist_cmd_exec.spec.in
- tsl/test/shared/expected/dist_parallel_agg.out
- tsl/test/shared/sql/dist_parallel_agg.sql
Calling `ts_dist_cmd_invoke_on_data_nodes_using_search_path()` function without an active transaction allows connection invalidation event happen between applying `search_path` and the actual command execution, which leads to an error.
This change introduces a way to ignore connection cache invalidations using `remote_connection_cache_invalidation_ignore()` function.
This work is based on @nikkhils original fix and the problem research.
Fix #4022
> Add connection cache invalidation ignore logic

- sql/policy_internal.sql
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/read_only.out
- tsl/test/sql/bgw_custom.sql
- tsl/test/sql/read_only.sql
When a compression_policy is executed by a background worker, the policy
should continue to execute even if compressing or decompressing one of
the chunks fails.
Fixes: #4610
> Continue compressing other chunks after an error

- .github/workflows/procedural.yaml
This patch adds a membership check to the 'Waiting for Engineering' workflow. The check ensures that the workflow is only triggered by external users. Without this check, when someone from the database engineering team responded to an issue, the "need-more-info" flag was removed and the issue was erroneously moved to the "waiting for engineering" column.
> Ensure that internal users don't trigger user workflows

- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
The test was flaky because the scheduler was launching the scheduled jobs, therefore their next_start field could differ depending on whether they had finished executing.
Fixed by not selecting the next_start field in alter_job calls, when it is not of interest.
Fixes #4719
> Fix flaky bgw_custom test

- CHANGELOG.md
- src/planner/constify_now.c
- tsl/test/shared/expected/constify_now-12.out
- tsl/test/shared/expected/constify_now-13.out
- tsl/test/shared/expected/constify_now-14.out
- tsl/test/shared/sql/constify_now.sql.in
The optimization that constifies certain now() expressions before hypertable expansion did not apply to CURRENT_TIMESTAMP even though it is functionally similar to now(). This patch extends the optimization to CURRENT_TIMESTAMP.
Fixes #4782
> Extend the now() optimization to also apply to CURRENT_TIMESTAMP

- sql/size_utils.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
Changed queries to use LATERAL join on size functions and views instead
of CTEs and it eliminate a lot of unnecessary projections and give a
chance for the planner to push-down predicates.
Closes #4775
> Improve size utils functions and views performance

- scripts/test_downgrade_from_tag.sh
- test/sql/updates/post.catalog.sql
Recently we fixed a DDL error (#4739) after upgrading to 2.8.0 version that surprisly the CI upgrade/dowgrade tests didn't complained during the development of the feature (#4552).
Fixed it by adding an specific query in the `post.catalog.sql` script to make sure we'll check all the constraints of our internal tables and catalog.
> Fix missing upgrade/downgrade tests DDL validation

- .github/workflows/windows-build-and-test.yaml
By default pg_isready only waits for 3 seconds before giving up which is occasionally not enough in the windows tests. This patch bumps the timeout up to 30 seconds which should be plenty to have the cluster start up under all circumstances.
> Increase timeout to wait for cluster start

- tsl/test/t/006_job_crash_log.pl
Older versions seens to have problems when undef is passed to poll_query_until so we change the call to pass explicit query instead.
> Improve job_crash_log test

- tsl/src/remote/connection.c
Make sure the FATAL error message before the data node disconnects is not lost when using PG15.
https://github.com/postgres/postgres/commit/618c1670
> Fix libpq disconnect for PG15

- src/guc.c
- src/guc.h
- test/src/test_utils.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/remote/connection.c
- tsl/src/remote/dist_copy.c
- tsl/src/remote/dist_copy.h
- tsl/test/expected/dist_copy_format_long.out
- tsl/test/expected/dist_copy_long.out
- tsl/test/expected/remote_copy-12.out
- tsl/test/expected/remote_copy-13.out
- tsl/test/expected/remote_copy-14.out
- tsl/test/shared/expected/dist_remote_error.out
- tsl/test/shared/sql/.gitignore
- tsl/test/shared/sql/dist_remote_error.sql
- tsl/test/sql/.gitignore
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_copy_format_long.sql
- tsl/test/sql/dist_copy_long.sql
- tsl/test/sql/remote_copy.sql.in
Group the incoming rows into batches on access node before COPYing to
data nodes.
This gives 2x-5x speedup on various COPY queries to distributed
hypertables.
Also fix the text format passthrough, and prefer text transfer format for text input to be able to use this passthrough. It saves a lot of CPU on the access node.
Fixes https://github.com/timescale/timescaledb/issues/4761
Part of #4285
> Batch rows on access node for distributed COPY

- .git-blame-ignore-revs
- tsl/src/fdw/scan_plan.c
Mark the variable as used for asserts only.
> Fix a warning with clang 14

- tsl/src/remote/dist_copy.c
ereport in PG 12.0 requires extra parenthesis around the auxiliary function calls.
> Fix ereport call in dist_copy for PG 12.0

- tsl/test/t/002_chunk_copy_move.pl
- tsl/test/t/003_connections_privs.pl
Starting with PG15, default permissions on the public schema is restricted for any non-superuser non-owner. Adjust TAP tests so as to not fail with "permission denied for schema public".
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=b073c3cc
> Adjust TAP tests permissions

- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
Include OOM kill event logs into error printout. Previously these
would only be visible by inspecting the postgres log and looking
for killed by signal 9.
> Show information about OOM killer in CI 

- CHANGELOG.md
- tsl/src/compression/compression.c
- tsl/test/shared/expected/compression_dml.out
- tsl/test/shared/sql/compression_dml.sql
INSERT into compressed hypertable with number of open chunks greater than ts_guc_max_open_chunks_per_insert causes segementation fault. New row which needs to be inserted into compressed chunk has to be compressed. Memory required as part of compressing a row is allocated from RowCompressor::per_row_ctx memory context. Once row is compressed, ExecInsert() is called, where memory from same context is used to allocate and free it instead of using "Executor State". This causes a corruption in memory.
Fixes #4778
> Fix segmentation fault during INSERT into compressed hypertable.

- src/planner/expand_hypertable.c
- test/src/test_utils.c
- tsl/src/fdw/data_node_scan_plan.c
PostgreSQL 15 introduced a Bitmapset for tracking non-pruned partitions for performance purposes. Adjust our code for expanding hypertable chunks to support this.
https://github.com/postgres/postgres/commit/475dbd0b718
> Adjust partition pruning to support PG15

- test/expected/pg_dump.out
- test/sql/pg_dump.sql
It was frequently failing on Windows. Sort by what is actually printed.
> Fix the flaky pg_dump test

- tsl/src/continuous_aggs/options.c
- tsl/test/expected/continuous_aggs.out
- tsl/test/expected/telemetry_stats.out
Timescale 2.7 released a new version of Continuous Aggregate (#4269)
that store the final aggregation state instead of the byte array of
the partial aggregate state, offering multiple opportunities of
optimizations as well a more compact form.
This new version also removes the unecessary `chunk_id` column from the
materialization hypertable and consequently the re-aggregation in the
user view. It means the user view that query the materialization
hypertable don't have a GROUP BY clause anymore that was problematic
for query performance.
Before 2.7 when users turn compression ON we infer compression options
`segmentby` and `orderby` based on the GROUP BY clause and time bucket
respectively. With the new version without a GROUP BY clause in the user
view the inferetion for the 'segmentby' …
> Miss segmentby compression option in CAGGs

- .github/workflows/abi.yaml
- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
- .github/workflows/coccinelle.yaml
- .github/workflows/code_style.yaml
- .github/workflows/coverity.yaml
- .github/workflows/cron-tests.yaml
- .github/workflows/homebrew.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/memory-tests.yaml
- .github/workflows/pgspot.yaml
- .github/workflows/pr-validation.yaml
- .github/workflows/pull-review.yaml
- .github/workflows/release.yaml
- .github/workflows/rpm-packages.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/update-test.yaml
- .github/workflows/windows-build-and-test.yaml
- .github/workflows/windows-packages.yaml
All github actions that run on Node12 are deprecated so bumped github action versions to run on Node16.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump github action versions

- .github/workflows/linux-build-and-test.yaml
Leftover from previous commit 8950ab where we bumped some github action versions to run on Node16 instead of Node12 (in deprecation).
> Bump codecov github action version

- tsl/test/expected/dist_copy_format_long.out
- tsl/test/expected/dist_copy_long.out
- tsl/test/sql/dist_copy_format_long.sql
- tsl/test/sql/dist_copy_long.sql
In some cases we can use less chunks, less data, and not truncate tables.
> Speed up the dist_copy tests

- src/guc.c
- src/guc.h
- tsl/src/remote/connection.c
External components like timescaledb_cloudutils might want to add additional options or do additional ssl related processing. They can do so by implementing a hook and then assigning it to a timescaledb variable to allow timescale to invoke it as appropriate.
> Add hook for ssl options

- CMakeLists.txt
- src/bgw/job.c
- src/chunk_constraint.c
- src/chunk_index.c
- src/dimension_vector.c
- src/ts_catalog/hypertable_compression.c
- src/ts_catalog/metadata.c
- tsl/src/continuous_aggs/invalidation.c
- tsl/src/continuous_aggs/options.c
Helps find accidentally swapped arguments, like in the recent epoll_ctl() error.
> Add clang-tidy warning readability-suspicious-call-argument

- src/ts_catalog/dimension_partition.c
Dimension partitions uses binary search to find the partition to place a chunk in. However, in the code, an array of partitions might not be sorted because the sort happened on a copy of the array instead of the main array. This change fixes the issue to ensure the array is sorted and binary search works properly.
> Fix unused sort in dimension partition lookup

- CHANGELOG.md
- src/copy.c
- test/expected/copy_memory_usage.out
- test/sql/copy_memory_usage.sql
In 8375b9aa536a619a5ac2644e0dae3c25880a4ead, a patch was added to handle chunks closes during an ongoing copy operation. However, this patch introduces a performance regression. All `MultiInsertBuffers` are deleted after they are flushed. In this PR, the performance regression is fixed. The most commonly used `MultiInsertBuffers` survive flushing. 
The 51259b31c4c62b87228b059af0bbf28caa143eb3 commit changes the way the per-tuple context is used. Since this commit, more objects are stored in this context. The size of the context was used to set the tuple size to PG < 14. The extra objects in the context lead to wrong (very large) results and flushes almost after every tuple read.
The cache synchronization introduced in 296601b1d7aba7f23aea3d47c617e2d6df81de3e is reverted. With the current …
> Fix performance regressions in the copy code

- src/copy.c
Since e555eea9dbc05f4c09cf0d7e23b814054a459d19 the function TSCopyMultiInsertInfoIsEmpty is no longer used. This patch removes the unused code from src/copy.c.
> Remove an unused function in the copy code

- sql/ddl_internal.sql
- sql/updates/reverse-dev.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/init.c
- tsl/src/remote/CMakeLists.txt
- tsl/src/remote/healthcheck.c
- tsl/src/remote/healthcheck.h
- tsl/test/expected/dist_commands.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/dist_commands.sql
- tsl/test/t/007_healthcheck.pl
- tsl/test/t/CMakeLists.txt
A new health check function _timescaledb_internal.health() returns the
health and status of the database instance, including any configured
data nodes (in case the instance is an access node).
Since the function returns also the health of the data nodes, it tries
hard to avoid throwing errors. An error will fail the whole function
and therefore not return any node statuses, although some of the nodes
might be healthy.
The health check on the data nodes is a recursive (remote) call to the
same function on those nodes. Unfortunately, the check will fail with
an error if a connection cannot be established to a node (or an error
occurs on the connection), which means the whole function call will
fail. This will be addressed in a future change by returning the error
in the function result …
> Add health check function

- .github/gh_config_reader.py
- .github/gh_matrix_builder.py
- .github/workflows/abi.yaml
- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/rpm-packages.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/windows-build-and-test.yaml
- .github/workflows/windows-packages.yaml
To avoid untrusted logged data to use `set-state` and `set-output` workflow
commands without the intention of the workflow author GitHub have
introduced a new set of environment files to manage state and output.
This commit changes the existing uses of `set-output` to use the new
environment files instead.
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Fix GitHub output action

- test/expected/copy_memory_usage.out
- test/sql/copy_memory_usage.sql
The changes from e555eea lead to flakiness. They are a leftover of earlier version and probably not needed anymore.
> Fix flaky copy_memory_usage tests

- src/bgw/job.c
Since PG 12.3 the `ereport` syntax changed and the commit 54ed0d introduced and `ereport` call that works just using newer PG versions.
Changed the `ereport` call a PG 12.0 compatible syntax.
CI failure: https://github.com/timescale/timescaledb/actions/runs/3292571583/jobs/5428090238
Related PRs: #4733, #4809
> Fix ereport call in job schedule for PG 12.0

- src/telemetry/telemetry.c
- src/telemetry/telemetry.h
- test/expected/telemetry.out
- tsl/test/expected/telemetry_stats.out
- tsl/test/sql/telemetry_stats.sql
Previous commit #4664 introduced the ability to execute background jobs on a fixed schedule.
This commit updates our telemetry data to include the number of jobs scheduled to execute on a fixed schedule vs the number registered to execute on a drifting schedule.
> Add telemetry for fixed schedule jobs

- coccinelle/ereport_pg12.cocci
This PR adds a Coccinelle test for ereport(..) calls that use the PG 12.3+ syntax
(postgres/postgres@a86715451653c730d637847b403b0420923956f7). We had some of these calls in the past, which we had to fix afterward (see #4733, #4809, #4871). This Coccinelle patch detects such calls and reports them in the CI run.
> Add a Coccinelle test for PG 12.3+ ereport syntax

- src/compat/compat.h
- src/telemetry/telemetry.c
The telemetry code that reads the postgres version was not updated when support for older postgres version was dropped so we introduce a new macro PG_MAJOR_MIN which is the oldest pg major version we support.
> Fix postgres version assert in telemetry

- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Ensure that queries involving several distributed DDL commands in one query string are blocked.
Fix #4818
> Block multi-statement DDL command in one query

- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
- tsl/test/shared/expected/classify_relation.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/classify_relation.sql
It depends on the context, not only on the relation id. The same chunk can be expanded both as a child of hypertable and as an independent table.
Fixes https://github.com/timescale/timescaledb/issues/4708
> Do not cache the classify_relation result

- tsl/src/continuous_aggs/create.c
The PR #3899 introduced a new function named `tsl_cagg_try_repair` to try to fix buggy Continuous Aggregates that lead to segfault on a select query. It added an INFO message when skipping the check for Continuous Aggregate that don't have partials and it's annoying during the upgrade/downgrade the extension specially if you have many Continuous Aggregate.
Remove this message because it's completely useless.
> Remove useless message from tsl_cagg_try_repair

- src/ts_catalog/continuous_agg.c
- src/ts_catalog/continuous_agg.h
Get rid of `GETSTRUCT` to fill the form data and use `heap_deform_tuple` instead. This is necessary specially when you have variable lenght fields and/or fields that accept NULL values. This refactoring will be specially usefull in a following PR for Nested Continuous Aggregates where we'll add a new metadata to the catalog that can accept NULL values.
Also refactor the rename view and schema code paths improving the readability and maintainability.
> Refactor Continuous Aggregate catalog code

- scripts/clang_format_wrapper.sh
- src/import/allpaths.c
- src/nodes/chunk_append/chunk_append.c
- src/planner/constify_now.c
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/space_constraint.c
- tsl/src/fdw/deparse.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/src/nodes/skip_scan/planner.c
It changed the type of Var.varno from Index to int. I'm starting to wonder if it was a good idea to enable this warning, but maybe we can give it the last try.
> Fix -Wsign-compare with PG 15

- .github/workflows/procedural.yaml
So far, only the "need-more-info" label was removed when there was activity on an issue. This PR ensures that the "no-activity" label is also removed.
> Remove no-activity label on issue activity

- src/nodes/hypertable_modify.c
OSM chunks are foreign tables. Modify assert to allow updates/deletes on hypertables with foreign table chunks.
> Allow foreign tables in hypertable modify path

- src/chunk.c
- src/utils.c
- src/utils.h
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/chunk_utils_internal.sql
- tsl/test/src/test_chunk_stats.c
After data is tiered using OSM, we cannot insert data into the same range. Need a callback that can be invoked by timescaledb to check for range overlaps before creating a new chunk
> Add hook for chunk creation

- .github/gh_matrix_builder.py
- .github/workflows/linux-build-and-test.yaml
It runs the changed tests many times to find flakiness.
> Add the Flaky Check

- CMakeLists.txt
- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
Look for the binary with exact version before looking for the generic name to prevent failure when clang-format is lower then required version but clang-format-14 exists.
> Swap lookup order for clang-format

- .github/gh_matrix_builder.py
- test/expected/metadata.out
- test/expected/pg_dump.out
- test/expected/pg_dump_unprivileged.out
- test/sql/utils/pg_dump_aux_dump.sh
- test/sql/utils/pg_dump_unprivileged.sh
- tsl/test/expected/cagg_dump.out
- tsl/test/expected/compression_hypertable.out
Version 15 pg_dump program does not log any messages with log level < PG_LOG_WARNING to stdout. Whereas this check is not present in version 14, thus we see corresponding tests fail with missing log information. This patch fixes by supressing those log information, so that the tests pass on all versions of postgresql.
Fixes #4832
> pg_dump on PG15 does not log messages with log level set to PG_LOG_INFO.

- .github/workflows/linux-build-and-test.yaml
I accidentally re-enabled it when adding the flaky check.
> Disable llvm on macos

- sql/cagg_migrate.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
Trying to resume a failed Continuous Aggregate raise an exception that the migration plan already exists, but this is wrong and the expected behaviour should be resume the migration and continue from the last failed step.
> Fix failure resuming a CAgg migration

- .gitignore
- coccinelle/oidisvalid.cocci
- src/custom_type_cache.c
- src/dimension.c
- src/extension.c
- src/hypertable.c
- src/hypertable_restrict_info.c
- src/indexing.c
- src/loader/loader.c
- src/nodes/chunk_insert_state.c
- src/partitioning.c
- src/planner/agg_bookend.c
- src/planner/expand_hypertable.c
- src/planner/partialize.c
- src/planner/planner.c
- src/process_utility.c
- src/telemetry/functions.c
- src/ts_catalog/catalog.c
- src/ts_catalog/continuous_agg.h
- src/utils.h
- tsl/src/bgw_policy/compression_api.c
- tsl/src/chunk_api.c
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/create.c
- tsl/src/continuous_aggs/create.c
- tsl/src/data_node.c
- tsl/src/fdw/data_node_chunk_assignment.c
Postgres source code define the macro `OidIsValid()` to check if the Oid is valid or not (comparing against the `InvalidOid` type). See `src/include/c.h` in Postgres source three.
Changed all direct comparisons against `InvalidOid` for the `OidIsValid` call and add a coccinelle check to make sure the future changes will use it correctly.
> Honor usage of OidIsValid() macro

- src/loader/loader.c
They use GCC 10 which has some other set of false positives.
> Fix sanitizer builds with -Wclobbered

- sql/cagg_migrate.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
When using `override => true` the migration procedure rename the current cagg using the suffix `_old` and rename the new created with suffix `_new` to the original name.
The problem is the `copy polices` step was executed after the `override` step and then we didn't found the new cagg name because it was renamed to the the original name leading the policy orphan (without connection with the materialization hypertable).
Fixed it by reordering the steps executin the `copy policies` before the `override` step. Also made some ajustments to properly copy all `bgw_job` columns even if this catalog table was changed.
Fixes #4885
> Fix orphan jobs after CAgg migration

- coccinelle/oidisvalid.cocci
- src/process_utility.c
The initial version of the check did not include a detailed message about the code failure in the CI output and did not check for expressions with operands in wrong order.
> Improve InvalidOid coccinelle check

- sql/maintenance_utils.sql
- src/chunk.c
- src/chunk.h
A chunk is in this state when it is compressed but also has uncompressed data in the uncompressed chunk. Individual tuples can only ever exist in either area. This is preparation patch to add support for uncompressed staging area for DML operations.
> Add new chunk state CHUNK_STATUS_COMPRESSED_PARTIAL

- src/bgw/job.c
- test/expected/pg_dump.out
- test/sql/pg_dump.sql
We have a rare condition where a debug build asserts on more than one job with the same job id. Since it is hard to create a reproduction, this commit adds a printout for those conditions and print out all the jobs with that job id in the postgres log.
Part of #4863
> Add printout for multiple jobs with same job_id

- test/sql/.gitignore
- tsl/test/shared/sql/.gitignore
- tsl/test/sql/.gitignore
Since new tests specific to PG15 were added, these tests which generated .sql files needs to be added to .gitnore
> Add new tests to .gitignore list

- sql/cagg_migrate.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/sql/include/cagg_migrate_common.sql
The current implementation update the jobs table directly and to make it consistent with other parts of the code we changed it to use the `alter_job` API instead to enable and disable the jobs during the migration. This refactoring is related to #4863.
> Refactor CAgg migration code to use job API

- .github/workflows/code_style.yaml
- tsl/test/t/003_connections_privs.pl
As a result of editing, trailing whitespace is often resulting and since some editors automatically remove trailing whitespace this creates diffs with more changed lines than necessary.
Add a check that files do not have trailing whitespace and fail if there are.
> Check for trailing whitespace

- .github/workflows/apt-packages.yaml
Debian 9 is EOL since July 2022 so we won't build packages for it anymore and can remove it from CI.
> Remove debian 9 from packages tests.

- scripts/test_downgrade_from_tag.sh
The downgrade script has printed a message in which the same variable is used for the upgrade and the downgrade version. This patch corrects the output and uses the correct variables.
Wrong CI output:
https://github.com/timescale/timescaledb/actions/runs/3420931335/jobs/5696393173#step:4:2818
Corrected CI output:
https://github.com/timescale/timescaledb/actions/runs/3437207346/jobs/5731676559#step:4:3184
> Print correct variables in downgrade test script

- sql/ddl_api.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/hypertable.c
- src/hypertable.h
- src/process_utility.c
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- src/ts_catalog/chunk_data_node.c
- src/ts_catalog/chunk_data_node.h
- src/utils.c
- src/utils.h
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/chunk_api.c
- tsl/src/data_node.c
- tsl/src/data_node.h
- tsl/src/fdw/option.c
- tsl/src/init.c
- tsl/test/expected/data_node.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/data_node.sql
Add a new function, `alter_data_node()`, which can be used to change the data node's configuration originally set up via `add_data_node()` on the access node.
The new functions introduces a new option "available" that allows configuring the availability of the data node. Setting
`available=>false` means that the node should no longer be used for reads and writes. Only read "failover" is implemented as part of this change, however.
To fail over reads, the alter data node function finds all the chunks for which the unavailable data node is the "primary" query target and "fails over" to a chunk replica on another data node instead. If some chunks do not have a replica to fail over to, a warning will be raised.
When a data node is available again, the function can be used to switch back to …
> Add function to alter data nodes

- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
When deleting a job in the test, the job does not necessarily terminate immediately, so wait for a log entries from the job before checking the jobs table.
Fixed #4859
> Fix race in bgw_db_scheduler_fixed

- src/planner/planner.c
- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/deparse.c
- tsl/src/fdw/deparse.h
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/src/fdw/scan_plan.c
- tsl/test/expected/dist_param.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_param.sql
This allows us to perform a nested loop join of a small outer local table to an inner distributed hypertable, without downloading the entire hypertable to the access node.
Related to https://github.com/timescale/timescaledb/issues/4305
On the example query from the above issue, this plan gives about 2x speedup, but in practice this can be arbitrarily high for a join with high selectivity and a large distributed hypertable.
> Support parameterized data node scans in joins

- sql/updates/post-update.sql
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/sql/CMakeLists.txt
This patch will report a warning when upgrading to new timescaledb extension. Also restrict users from creating cagss with old format on timescaledb with PG15.
> Deprecate continuous aggregates with old format

- CHANGELOG.md
- tsl/src/nodes/gapfill/gapfill_exec.c
Add CHECK_FOR_INTERRUPTS() macro to gapfill main loop.
Fixes #4963
> Check for interrupts in gapfill main loop

- src/process_utility.c
- tsl/src/compression/create.c
- tsl/test/expected/compression_merge.out
- tsl/test/sql/compression_merge.sql
Compress chunk interval is set using an ALTER TABLE statement.
This change makes it so you can update the compress chunk interval
while keeping the rest of the compression settings intact.
Updating it will only affect chunks that are compressed and rolled
up after the change.
> Update compress chunk interval on compressed data

- src/bgw/job.c
- src/bgw/job.h
- tsl/src/bgw_policy/job_api.c
Job ids are locked using an advisory lock rather than a row lock on the
jobs table, but this lock is not taken in the job API functions
(`alter_job`, `delete_job`, etc.), which appears to cause a race
condition resulting in addition of multiple rows with the same job id.
This commit adds an advisory `RowExclusiveLock` on the job id while
altering it to match the advisory locks taken while performing other
modifications.
Closes #4863
> Take advisory lock for job tuple

- .github/gh_matrix_builder.py
- tsl/test/t/007_healthcheck.pl
Removed an invalid import from 007_healthcheck.pl test.
Also enabled all the perl tests in PG15.
> Fix perl test import in PG15

- CHANGELOG.md
- sql/chunk.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/chunk_utils_internal.sql
Commit 9f4dcea30135d1e36d1c452d631fc8b8743b3995 introduces frozen chunks. Checking whether a chunk is frozen or not has been done so far in the query planner. If it is not possible to determine which chunks are affected by a query in the planner (e.g., due to a cast in the WHERE condition), all chunks are checked. This leads: (1) to an increased planning time and (2) to the situation that a single frozen chunk could reject queries, even if the frozen chunk is not addressed by the query.
Commit 9f4dcea30135d1e36d1c452d631fc8b8743b3995 introduces the `get_or_add_baserel_from_cache` function. It contains a performance regression since an expensive metadata scan (`ts_chunk_get_hypertable_id_by_relid`) is performed even when it could be avoided.
The query performance is even with the 2.6.0 …
> Fix performance regressions introduced by freeze chunk

- src/planner/planner.c
This patch changes an Assert in get_or_add_baserel_from_cache to an Ensure. Therefore, this check is also performed in release builds. This is done to detect metadata corruptions at an early stage.
> Use Ensure in get_or_add_baserel_from_cache

- src/telemetry/stats.c
- src/telemetry/stats.h
- src/telemetry/telemetry.c
- tsl/test/expected/telemetry_stats.out
- tsl/test/sql/telemetry_stats.sql
Commit #4668 introduced hierarchical caggs. This patch adds a field `num_caggs_nested` to the telemetry report to include the number of caggs defined on top of other caggs.
> Add telemetry for caggs on top of caggs

- .github/workflows/linux-build-and-test.yaml
Since we now use the date as a part of the cache key to ensure no stale cache entries hiding build failures we need to make sure we have a cache entry present before workflows that depend on cache are run.
> Change time of scheduled CI run

- sql/cagg_migrate.sql
- tsl/test/expected/cagg_migrate_integer.out
- tsl/test/expected/cagg_migrate_integer_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamp.out
- tsl/test/expected/cagg_migrate_timestamp_dist_ht.out
- tsl/test/expected/cagg_migrate_timestamptz.out
- tsl/test/expected/cagg_migrate_timestamptz_dist_ht.out
We're facing some weird `portal snapshot` issues running the
`refresh_continuous_aggregate` procedure called from other procedures.
Fixed it by ignoring the Refresh Continuous Aggregate step from the
`cagg_migrate` and warning users to run it manually after the execution.
Fixes #4913
> Remove refresh step from CAGG migration

- src/process_utility.c
- tsl/test/expected/cagg_on_cagg_integer.out
- tsl/test/expected/cagg_on_cagg_integer_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamp.out
- tsl/test/expected/cagg_on_cagg_timestamp_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamptz.out
- tsl/test/expected/cagg_on_cagg_timestamptz_dist_ht.out
- tsl/test/sql/include/cagg_on_cagg_common.sql
When truncating a cagg that had another cagg defined on top of it, the nested cagg would not get invalidated accordingly. That was because we were not adding a corresponding entry in the hypertable invalidation log for the materialization hypertable of the base cagg.
This commit adds an invalidation entry in the table so that subsequent refreshes see and properly process this invalidation.
> Fix TRUNCATE on hierarchical caggs

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
We have to add it to WSLENV variable or else it's not passed to the WSL processes.
> Fix GITHUB_OUTPUT on Windows

- sql/ddl_internal.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/chunk.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/hypertable.h
- tsl/src/chunk.c
- tsl/src/chunk.h
- tsl/src/data_node.c
- tsl/src/init.c
- tsl/test/expected/dist_ddl.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/dist_ddl.sql
This function drops chunks on a specified data node if those chunks are not known by the access node.
Call `drop_stale_chunks()` automatically when data node becomes available again.
Fix #4848
> Introduce drop_stale_chunks() function

- tsl/src/data_node.c
- tsl/src/data_node.h
- tsl/src/dist_backup.c
- tsl/test/expected/dist_backup.out
- tsl/test/sql/dist_backup.sql
Make sure that a data node list does not have unavailable data nodes when using create_distributed_restore_point() API.
Fix #4979
> Ensure nodes availability using dist restore point

- tsl/test/expected/dist_cagg.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_cagg.sql
Add additional test cases to ensure caggs functionality on distributed hypertable during data node being unavailable.
Fix #4978
> Test dist caggs with an unavailable data node

- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
Apply date_trunc to last_successful_finish.
Commit 20cdd9ca3ed0c2d62779c4fc61d278a489b4460a mostly fixed the flakiness, but date_trunc was not
applied to the last_successful_finish
so we still got some flaky runs.
> Fix flaky bgw_db_scheduler_fixed test

- sql/chunk.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/chunk.c
- src/nodes/chunk_dispatch.c
- src/process_utility.c
- tsl/src/nodes/CMakeLists.txt
- tsl/src/nodes/frozen_chunk_dml/CMakeLists.txt
- tsl/src/nodes/frozen_chunk_dml/frozen_chunk_dml.c
- tsl/src/nodes/frozen_chunk_dml/frozen_chunk_dml.h
- tsl/src/planner.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/chunk_utils_internal.sql
This patch changes the code that blocks frozen chunk modifications to no longer use triggers but to use custom node instead. Frozen chunks is a timescaledb internal object and should therefore not be protected by TRIGGER which is external and creates several hazards. TRIGGERs created to protect internal state contend with user-created triggers. The trigger created to protect frozen chunks does not work well with our restoring GUC which we use when restoring logical dumps. Thirdly triggers are not functional for any internal operations but are only working in code pathes that explicitly added trigger support.
> Use custom node to block frozen chunk modifications

- .github/workflows/coverity.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
The sqlsmith and coverity workflows used the cache postgres build but could not produce a build by themselves and therefore relied on other workflows to produce the cached binaries. This patch changes those workflows to use normal postgres packages instead of custom built postgres to remove that dependency.
> Use packaged postgres for sqlsmith and coverity CI

- src/ts_catalog/continuous_agg.c
- src/ts_catalog/continuous_agg.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/options.c
- tsl/test/expected/cagg_on_cagg_integer.out
- tsl/test/expected/cagg_on_cagg_integer_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamp.out
- tsl/test/expected/cagg_on_cagg_timestamp_dist_ht.out
- tsl/test/expected/cagg_on_cagg_timestamptz.out
- tsl/test/expected/cagg_on_cagg_timestamptz_dist_ht.out
- tsl/test/sql/cagg_on_cagg_integer.sql
- tsl/test/sql/cagg_on_cagg_integer_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_timestamp.sql
- tsl/test/sql/cagg_on_cagg_timestamp_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_timestamptz.sql
- tsl/test/sql/cagg_on_cagg_timestamptz_dist_ht.sql
- tsl/test/sql/include/cagg_on_cagg_validations.sql
Commit https://github.com/timescale/timescaledb/commit/3749953e9704e45df8f621607989ada0714ce28d introduce Hierarchical Continuous Aggregates (aka
Continuous Aggregate on top of another Continuous Aggregate) but it
lacks of some basic validations.
Validations added during the creation of a Hierarchical Continuous
Aggregate:
* Forbid create a continuous aggregate with fixed-width bucket on top of
a continuous aggregate with variable-width bucket.
* Forbid incompatible bucket widths:
- should not be equal;
- bucket width of the new continuous aggregate should be greater than
the source continuous aggregate;
- bucket width of the new continuous aggregate should be multiple of
the source continuous aggregate.
> Add Hierarchical Continuous Aggregates validations

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_errors.out
- tsl/test/sql/cagg_errors.sql
When trying to create cagg on top of any relation that is a neither a hypertable nor a continuous aggregate the command would segfault. This patch changes the code to handle this case gracefully and error out when trying to create a cagg on top of a relation that is not supported. Found by coverity.
> Fix segfault in cagg creation

- src/copy.c
rd_smgr should not be accessed directly but RelationGetSmgr should be used instead. Accessing it directly can lead to segfaults when parallel relcache flushes are happening.
https://github.com/postgres/postgres/commit/f10f0ae420ee62400876ab34dca2c09c20dcd030
> Use RelationGetSmgr instead of rd_smgr

- src/bgw/job.c
- src/bgw/worker.h
- src/net/conn.c
- src/telemetry/telemetry.c
- test/expected/telemetry.out
Do not spam log with telemetry problems
The telemetry process runs on a regular basis and usually does not make
a lot of noise, but in a few particular cases, it writes entries to the
log unnecessarily.
If the telemetry server cannot be contacted, it will print a warning in
the log that the server cannot be contacted. Since it is nothing wrong
with the system and the telemetry process will try to re-connect at a
later time, it is unnecessary to print as a warning.
If the telemetry response is malformed, a warning is printed. This is
also unnecessary since there is nothing wrong with the system, there is
nothing the user can do about it, and this warning can be largely
ignored.
If the hard-coded telemetry scheme is incorrect, a warning will be
printed. This should not normally happen, and …
> Do not spam log with telemetry problems

- CMakeLists.txt
- src/compat/compat.h
- src/copy.c
RelationGetSmgr was backported by upstream to the STABLE branches but is not yet available in any released version so we cannot use pg version to determine presence of RelationGetSmgr.
> Check for presence of RelationGetSmgr

- tsl/src/remote/connection.c
- tsl/src/remote/copy_fetcher.c
- tsl/test/shared/expected/dist_fetcher_type-12.out
- tsl/test/shared/expected/dist_fetcher_type-13.out
- tsl/test/shared/expected/dist_fetcher_type-14.out
- tsl/test/shared/expected/dist_fetcher_type-15.out
- tsl/test/shared/sql/dist_fetcher_type.sql.in
- tsl/test/shared/sql/include/shared_setup.sql
Ensure the COPY fetcher implementation reads data until EOF with `PQgetCopyData()`. Also ensure the malloc'ed copy data is freed with `PQfreemem()` if an error is thrown in the processing loop.
Previously, the COPY fetcher didn't read until EOF, and instead assumed EOF when the COPY file trailer is received. Since EOF wasn't reached, it required terminating the COPY with an extra call to the (deprecated) `PQendcopy()` function.
Still, there are cases when a COPY needs to be prematurely terminated, for example, when querying with a LIMIT clause. Therefore, distinguish between "normal" end (when receiving EOF) and forceful end (cancel the ongoing query).
> Read until EOF in COPY fetcher

- .github/gh_matrix_builder.py
- tsl/test/expected/remote_txn.out
- tsl/test/sql/remote_txn.sql
In remote_txn, testcases which kill remote processes on data nodes,
tend to rollback transactions and as part of the process, WARNINGS/ERROR
are reported to client. Client however reports WARNINGS/ERROR in different
order intermittently. This is an issue specific to psql utility. Placing 
psql in gdb and trying to diagnose the problem does not reproduce the issue.
This patch fixes the tests by not reporting WARNINGS.
Fixes #4837
> Fix remote_txn on PG15

- .github/workflows/sanitizer-build-and-test.yaml
So far, we have treated the `log_path` setting of the sanitizer like a file. In fact, this value is used as a prefix for the created log file. Since we expected the exact file name when uploading the sanitizer output, this file was not found and we lost the messages of the sanitizer. This PR changes the behavior. We now treat the setting as a prefix and upload all files created in a dedicated sanitizer output folder.
Example output when `log_path` is set to `/tmp/sanitizer/sanitizer` :
```
$ ls -l /tmp/sanitizer/
total 16
-rw------- 1 jan jan 13757 Dec  7 17:48 sanitizer.postgres.1894562
```
Link to CI run with failed upload: https://github.com/timescale/timescaledb/actions/runs/3633428885
> Correct Sanitizer log directory

- tsl/test/sql/CMakeLists.txt
The `dist_hypertable` test needs a lot of memory, especially when the sanitizer is enabled. This patch runs this test as a `SOLO_TEST`. This ensures that PostgreSQL does not run into an out-of-memory situation.
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/3642792492
Link to successful CI run (containing this change): https://github.com/timescale/timescaledb/actions/runs/3643058327/jobs/6150867765
> Ensure dist_hypertable is executed as solo test

- .github/workflows/sanitizer-build-and-test.yaml
When the sanitizer is active, the tests require a lot of memory. If they are run in large parallel groups, out-of-memory situations can occur. This patch reduces the size of parallel groups to 5 when the sanitizer is active.
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/3648618648/jobs/6162253916
The 'show regression logs' step shows:
```
Dec 08 13:50:13 fv-az344-99 kernel: Out of memory: Killed process 24065 (postgres) total-vm:21475224588kB, anon-rss:108576kB, file-rss:2172kB, shmem-rss:62416kB, UID:1001 pgtables:3360kB oom_score_adj:500
```
> Reduce parallel test group size in sanitizer runs

- CHANGELOG.md
- src/process_utility.c
- test/expected/size_utils.out
- test/sql/size_utils.sql
Issue occurs in extended query protocol mode only where every query goes through PREPARE and EXECUTE phase. First time ANALYZE is executed, a list of relations to be vaccumed is extracted and saved in a list. This list is referenced in parsetree node. Once execution of ANALYZE is complete, this list is cleaned up, however reference to the same is not cleaned up in parsetree node. When second time ANALYZE is executed, segfault happens as we access an invalid memory location.
Fixed the issue by restoring the actual value in parsetree node once ANALYZE completes its execution.
Fixes #4857
> Fix segfault after second ANALYZE

- tsl/src/compression/compression.c
The RelationInitIndexAccessInfo call leaks cache memory and seems to be unnecessary.
> Fix memory leak for compression with merge chunks

- src/planner/planner.c
When popping the hypertable cache stack, it might happen that the hypertable cache was invalidated between the push and the pop. In that case, the baserel cache can contain invalid entries pointing to the now popped hypertable cache, so we reset the baserel cache.
Fixes #4795
> Reset baserel cache on invalid hypertable cache

- .github/workflows/linux-32bit-build-and-test.yaml
The new permissions checks to fix CVE-2022-29187 in Git caused some issues in our CI pipeline. This patch adds the checkout directory to Git's "safe.directory" setting.
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/3690974658/jobs/6248545042
> Fix git permission issue in CI build

- tsl/src/remote/cursor_fetcher.c
- tsl/test/shared/expected/dist_fetcher_type-12.out
- tsl/test/shared/expected/dist_fetcher_type-13.out
- tsl/test/shared/expected/dist_fetcher_type-14.out
- tsl/test/shared/expected/dist_fetcher_type-15.out
- tsl/test/shared/sql/dist_fetcher_type.sql.in
The cursor_fetcher_rewind method assumes that the data node cursor is
rewind either after eof or when there is an associated request. But the
rewind can also occur once the server has generated required number of
rows by joining the relation being scanned with another regular
relation. In this case, the fetch would not have reached eof and there
will be no associated requests as the rows would have been already
loaded into the cursor causing the assertion in cursor_fetcher_rewind
to fail. Fixed that by removing the Assert and updating
cursor_fetcher_rewind to discard the response only if there is an
associated request.
Fixes: #5053 
Fixes: #5085
> Fix assertion failure in cursor_fetcher_rewind 

- tsl/src/compression/compression.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_merge.out
- tsl/test/sql/compression_merge.sql
Planner can decide to use BitmapHeapScans exclusively when
scanning compressed chunks. Since we filter out such scans
due to previously reported issues, this can lead to no
query plan devised when querying compressed chunks. This
change allows Bitmap scans on compressed chunks only when
it is not parametrized.
Fixes https://github.com/timescale/timescaledb/issues/5090
> Allow BitmapHeapScans on non-parametrized paths

- src/guc.c
- src/guc.h
- tsl/src/compression/compression.c
- tsl/test/expected/compression_indexscan.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_indexscan.sql
Index support for compress chunk
It allows to override tuplesort with indexscan
if compression setting keys matches with Index keys.
Moreover this feature has Enable/Disable Toggle.
To Disable from the client use the following command,
SET timescaledb.enable_compression_indexscan = 'OFF'
Fixes #4617
> Index support for compress chunk

- README.md
- src/README.md
- src/bgw/README.md
- test/README.md
- tsl/README.md
- tsl/src/nodes/README.md
The tree contains a lot of design and architecture documents, but they
are not linked together, so this commits adds a few additional README
and build a basic structure for the documentation.
> Link development and design documentation

- .github/workflows/windows-build-and-test.yaml
The last minor versions for PG14 (14.6) and PG15 (15.1) were unlisted by
chocolatey maintainers due to some issues.
Fixed it by hardcoding the 14.5 until the packages become available
again.
This is intended to be a temporary fix until the chocolatey maintainers
fix their issues and make the packages listed and we can revert this change.
> Fix broken postgres install on Windows CI

- tsl/src/continuous_aggs/options.c
- tsl/test/shared/expected/cagg_compression.out
- tsl/test/shared/sql/cagg_compression.sql
On caggs with realtime aggregation changing the column name does not update all the column aliases inside the view metadata. This patch changes the code that creates the compression configuration for caggs to get the column name from the materialization hypertable instead of the view internals.
Fixes #5100
> Fix enabling compression on caggs with renamed columns

- .github/workflows/windows-build-and-test.yaml
- src/bgw/job_stat.c
> Run regression tests on pg15 windows

- tsl/src/compression/create.c
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/sql/compression_ddl.sql
When defining compression segment by parameter using multiple columns, the parameter ordering is not respected for index creation.
This patch fixes the issue by maintaining the same order in which user has defined columns in segment by clause.
Fixes #5104
> Fix column ordering in compressed table index.

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/sql/cagg_on_cagg.sql
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
The bucket size of a Continuous Aggregate should be greater or equal to
the parent Continuous Aggregate because there are many cases where you
actually want to roll up on another dimension.
> Fix CAgg on CAgg bucket size validation

- .github/gh_matrix_builder.py
- .github/workflows/abi.yaml
- .github/workflows/coverity.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/memory-tests.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/sqlsmith.yaml
- .github/workflows/windows-build-and-test.yaml
This PR enables PG15 in the following workflows:
- Regression Linux
- ABI test
- Memory tests
- Coverity
- SQLSmith
- Additional cron tests
> Enable various PG15 CI Checks

- .github/workflows/apt-packages.yaml
- .github/workflows/rpm-packages.yaml
Since we currently only have 1 released version that supports PG15 we cannot test downgrade with PG15.
> Skip package downgrade test for PG15

- CHANGELOG.md
- sql/policy_internal.sql
- src/chunk.c
- src/copy.c
- src/nodes/chunk_dispatch_state.c
- src/nodes/chunk_insert_state.c
- src/nodes/chunk_insert_state.h
- src/planner/planner.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.h
- tsl/src/remote/dist_copy.c
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/compression_bgw.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/compression_insert-15.out
- tsl/test/expected/dist_compression.out
- tsl/test/isolation/expected/compression_ddl_iso.out
This patch changes INSERTs into compressed chunks to no longer
be immediately compressed but stored in the uncompressed chunk
instead and later merged with the compressed chunk by a separate
job.
This greatly simplifies the INSERT-codepath as we no longer have
to rewrite the target of INSERTs and on-the-fly compress leading to a
roughly 2x improvement on INSERT rate into compressed chunk.
Additionally this improves TRIGGER-support for INSERTs into compressed chunks.
This is a necessary refactoring to allow UPSERT/UPDATE/DELETE on
compressed chunks in follow-patches.
Fixes #4655
> Refactor INSERT into compressed chunks

- CHANGELOG.md
- sql/CMakeLists.txt
- sql/updates/2.9.0--2.9.1.sql
- sql/updates/latest-dev.sql
- version.config
This release contains bug fixes since the 2.9.0 release.
This release is high priority for upgrade. We strongly recommend that you
upgrade as soon as possible.
**Bugfixes**
* https://github.com/timescale/timescaledb/pull/5072 Fix CAgg on CAgg bucket size validation
* https://github.com/timescale/timescaledb/pull/5101 Fix enabling compression on caggs with renamed columns
* https://github.com/timescale/timescaledb/pull/5106 Fix building against PG15 on Windows
* https://github.com/timescale/timescaledb/pull/5117 Fix postgres server restart on background worker exit
* https://github.com/timescale/timescaledb/pull/5121 Fix privileges for job_errors in update script
> Release 2.9.1

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/shared/expected/compression_dml.out
- tsl/test/shared/sql/compression_dml.sql
SELECT from partially compressed chunk crashes due to reference to NULL pointer. When generating paths for DecompressChunk, uncompressed_partial_path is null which is not checked, thus causing a crash. This patch checks for NULL before calling create_append_path().
Fixes #5134
> SELECT from partial compressed chunks crashes

- src/chunk.h
Currently when ASSERT_IS_VALID_CHUNK fails it is impossible to tell which of the conditions fails without opening the coredump in debugger as all the conditions are ANDed in a single Assert. This patch splits the conditions into individual Asserts so you can immediately see from stacktrace which condition failed.
> Improve ASSERT_IS_VALID_CHUNK macro

- .github/workflows/coccinelle.yaml
- .github/workflows/code_style.yaml
- .github/workflows/cron-tests.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/memory-tests.yaml
- .github/workflows/pgspot.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/update-test.yaml
- .github/workflows/windows-build-and-test.yaml
If we test every commit in main, we can allow GitHub to merge the PRs automatically without requiring a manual rebase on the current master. These rebases are a real time sink.
Also it will help to get more statistics for our test result database, and get more coverage for probabilistic tests like sqlsmith.
> Run all the tests on every commit in main

- CHANGELOG.md
- src/process_utility.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
Adding new column with NULL constraint to a compressed hypertable is raising an error but it make no sense because NULL constraints in Postgres does nothing, I mean it is useless and exist just for compatibility with other database systems:
https://www.postgresql.org/docs/current/ddl-constraints.html#id-1.5.4.6.6
Fixed it by ignoring the NULL constraints when we check for `ALTER TABLE .. ADD COLUMN ..` to a compressed hypertable.
Fixes #5151
> Fix adding column with NULL constraint

- CHANGELOG.md
- src/ts_catalog/continuous_agg.h
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/sql/cagg_on_cagg.sql
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
- tsl/test/sql/include/cagg_on_cagg_common.sql
- tsl/test/sql/include/cagg_on_cagg_setup.sql
Creating a CAgg on a CAgg where the time column is in a different order of the original hypertable was raising the following exception:
`ERROR:  time bucket function must reference a hypertable dimension column`
The problem was during the validation we're initializing internal data structure with the wrong hypertable metadata.
Fixes #5131
> Fix CAgg on CAgg different column order

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/sql/cagg_on_cagg.sql
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
- tsl/test/sql/include/cagg_on_cagg_validations.sql
During the creation of a CAgg on top of another CAgg we check if the bucket width is multiple of the parent and for this arithmetic we made an assumption that picking just the `month` part of the `interval` for variable bucket size was enought.
This assumption was wrong for bucket sizes that doesn't have the month part (i.e: using timezones) leading to division by zero error because in that case the `month` part of an `interval` is equal to 0 (zero).
Fixed it by properly calculating the bucket width for variable sized buckets.
Fixes #5126
> Fix CAgg on CAgg variable bucket size validation

- .github/workflows/pr-handling.yaml
Reviewers should be assigned only when the PR is ready for review.
> Skip auto assigning reviewers for draft PRs

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test-ignored.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/shellcheck-ignored.yaml
- .github/workflows/shellcheck.yaml
- .github/workflows/windows-build-and-test.yaml
If only documentation is changed, the full regression check workflow will still be executed, so this commit will instead skip running the regression workflows if there are only changes to files that will not affect the success of the workflow.
> Do not run regress workflows on benign changes

- sql/partialize_finalize.sql
- tsl/test/expected/partialize_finalize.out
- tsl/test/sql/partialize_finalize.sql
Previous PR #4307 mark `partialize_agg` and `finalize_agg` as parallel safe but this change is leading to incorrect results in some cases.
Those functions are supposed work in parallel but seems is not the case and it is not evident yet the root cause and how to properly use it in parallel queries so we decided to revert this change and provide correct results to users.
Fixes #4922
> Remove parallel safe from partialize_agg

- CHANGELOG.md
- tsl/src/data_node.c
- tsl/test/expected/data_node.out
- tsl/test/expected/data_node_bootstrap.out
- tsl/test/sql/data_node.sql
- tsl/test/sql/data_node_bootstrap.sql
When deleting a data node with the option `drop_database=>true`, the database is deleted even if the command fails for other reasons.
Fix this behavior by dropping the remote database at the end of the delete data node operation so that other checks fail first.
> Fix issue with deleting data node and dropping database

- .github/workflows/linux-32bit-build-and-test-ignored.yaml
- .github/workflows/windows-build-and-test-ignored.yaml
The workflow ignore files for 32-bit Linux builds and Windows was missing from #5156 so these are added here.
> Add missing ignore files

- tsl/src/data_node.c
Function alter_data_node() return uninitialized value for "available" option when it is not presented in the option list.
Fix #5154
> Fix dist_cagg flaky test

- .github/workflows/procedural.yaml
This patch updates the used issue workflow actions and ensures that the 'secrets.ORG_AUTOMATION_TOKEN' is used by all actions.
> Update issue workflow actions and used token

- .github/workflows/linux-build-and-test-ignored.yaml
- .github/workflows/windows-build-and-test-ignored.yaml
Build matrix is missing from the ignore workflows for the Windows and Linux builds, so this commit adds them.
> Add build matrix to Windows and Linux builds

- src/nodes/chunk_append/planner.c
- src/nodes/constraint_aware_append/constraint_aware_append.c
- test/expected/create_hypertable.out
- test/sql/create_hypertable.sql
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
When TidRangeScan is child of ChunkAppend or ConstraintAwareAppend node, an
error is reported as "invalid child of chunk append: Node (26)". This patch
fixes the issue by recognising TidRangeScan as a valid child.
Fixes: #4872
> Fix ChunkAppend, ConstraintAwareAppend child subplan

- tsl/src/fdw/option.c
- tsl/src/fdw/option.h
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/test/expected/dist_ref_table_join-12.out
- tsl/test/expected/dist_ref_table_join-13.out
- tsl/test/expected/dist_ref_table_join-14.out
- tsl/test/expected/dist_ref_table_join-15.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_ref_table_join.sql.in
With this patch, the ability to mark reference tables (tables that exist on all data nodes of a multi-node installation) via an FDW option has been added.
**Note:** This patch is part of a series of patches that allows join pushdowns in the multi-node code. This commit also introduces the regression test files for the join pushdowns. The test output is currently the same for all PG versions. However, this will change when the test cases for the join pushdown are added.
> Introduce a FDW option to mark reference tables

- tsl/src/fdw/estimate.c
This patch adds the missing functionality to estimate the costs of remote joins. Most of the code is a backport from PG Upstream.
> Add cost estimation for remote joins

- CMakeLists.txt
This is aimed at developers. If we enable it by default, it confuses our users and slows down the build for them.
Fixes https://github.com/timescale/timescaledb/issues/5092
> Don't enable clang-tidy by default

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.9.1 release.
**Bugfixes**
* #5114 Fix issue with deleting data node and dropping the database on multi-node
* #5133 Fix creating a CAgg on a CAgg where the time column is in a different order of the original hypertable
* #5152 Fix adding column with NULL constraint to compressed hypertable
* #5170 Fix CAgg on CAgg variable bucket size validation
* #5180 Fix default data node availability status on multi-node
* #5181 Fix ChunkAppend and ConstraintAwareAppend with TidRangeScan child subplan
* #5193 Fix repartition behavior when attaching data node on multi-node
> Release 2.9.2

- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/fdw.c
- tsl/src/fdw/scan_plan.c
- tsl/src/fdw/scan_plan.h
This patch adds the missing functionality to create scan plans for remote joins. Most of the code is a backport from PG Upstream.
> Add scan plan logic for remote joins

- CHANGELOG.md
- src/dimension.h
- src/planner/space_constraint.c
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_errors.out
- tsl/test/expected/cagg_errors_deprecated.out
- tsl/test/expected/cagg_joins-12.out
- tsl/test/expected/cagg_joins-13.out
- tsl/test/expected/cagg_joins-14.out
- tsl/test/expected/cagg_joins-15.out
- tsl/test/sql/.gitignore
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_errors.sql
- tsl/test/sql/cagg_errors_deprecated.sql
- tsl/test/sql/cagg_joins.sql.in
Enable the support of having join in the query used for creating the continuous aggregates. It has follwoing restrictions-
1. Join can involve only one hypertable and one normal table
2. Join should be a left inner join
3. Join condition can only be equality
> Allow joins in continuous aggregates

- CHANGELOG.md
- src/nodes/chunk_dispatch/chunk_insert_state.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/compression_insert-15.out
- tsl/test/sql/compression_insert.sql.in
Recent refactorings in the INSERT into compressed chunk code path allowed us to support this feature but the check to prevent users from using this feature was not removed as part of that patch. This patch removes the blocker code and adds a minimal test case.
> Allow RETURNING clause when inserting into compressed chunks

- CHANGELOG.md
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- sql/views.sql
- sql/with_telemetry.sql
- tsl/test/expected/job_errors_permissions.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/job_errors_permissions.sql
Since the job error log can contain information from many different
sources and also from many different jobs it is important to ensure
that visibility of the job error log entries is restricted to job
owners.
This commit extend the view `timescaledb_information.job_errors` with
role-based checks so that a user can only see entries for jobs that she
has permission to view and restrict the permissions to
`_timescaledb_internal.job_errors` so that users only can view the job
error log through the view. A special case is added so that the
superuser and the database owner can see all log entries, even if there 
is no associated job id with the log entry.
Closes #5217
> Add role-level security to job error log

- .github/workflows/changelog-check.yaml
Update checkout to not pull in Node.js 12 which is deprecated on GitHub.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
> Update checkout version in changelog-check

- src/nodes/chunk_dispatch/chunk_dispatch.c
- tsl/src/compression/compression.c
Refactor the decompression code to move the decompressor initialization into a separate function.
> Small decompress_chunk refactor

- CHANGELOG.md
- tsl/src/data_node.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/src/remote/connection_cache.c
- tsl/src/remote/txn_resolve.c
- tsl/test/expected/remote_connection.out
- tsl/test/src/remote/connection.c
Refactor the data node connection establishment so that it is interruptible, e.g., by ctrl-c or `statement_timeout`.
Previously, the connection establishment used blocking libpq calls. By instead using asynchronous connection APIs and integrating with PostgreSQL interrupt handling, the connection establishment can be canceled by an interrupt caused by a statement timeout or a user.
Fixes #2757
> Make connection establishment interruptible

- tsl/test/sql/CMakeLists.txt
The telemetry_stats tescase was accidentally disabled by PR #5162.
> Enable telemetry_stats testcase

- .github/gh_matrix_builder.py
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/windows-build-and-test-ignored.yaml
- .github/workflows/windows-build-and-test.yaml
- tsl/test/sql/CMakeLists.txt
When run in a parallel group, the dist_move_chunk test can get into a deadlock with another test running a 'DROP DATABASE' command. So, mark it as a solo test to disallow it from running in a parallel group.
Closes #4972
> Run dist_move_chunk as a solo test in PG15

- CHANGELOG.md
- tsl/src/remote/async.c
Broken code caused the async connection module to never send queries
using prepared statements. Instead, queries were sent using the
parameterized query statement instead.
The regression was introduced a long time ago in commit https://github.com/timescale/timescaledb/commit/86858e36e9fb6243d52191bcedc6be05ee2ab734
Fix this so that prepared statements are used when created.
> Fix use of prepared statement in async module

- sql/util_time.sql
- src/ts_catalog/continuous_agg.c
- tsl/test/expected/continuous_aggs-12.out
- tsl/test/expected/continuous_aggs-13.out
- tsl/test/expected/continuous_aggs-14.out
- tsl/test/expected/continuous_aggs-15.out
- tsl/test/sql/continuous_aggs.sql.in
The `cagg_watermark` function perform just read-only operations so is
safe to make it parallel safe to take advantage of the Postgres
parallel query.
Since 2.7 when we introduced the new Continuous Aggregate format we
don't use partials anymore and those aggregate functions
`partialize_agg` and `finalize_agg` are not parallel safe, so make no
sense don't take advantage of Postgres parallel query for realtime
Continuous Aggregates.
Disable-Check: force-changelog-changed
Related to #4699
> Mark cagg_watermark parallel safe

- .github/workflows/windows-build-and-test.yaml
The currently used version pulls in Node.js 12 which is deprecated on github.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump version of setup-wsl github action

- .github/workflows/code_style.yaml
For an unknown reason, pip started to install an older version of
prospector which is incompatible with the current pylint. Require the
new prospector version explicitly.
> Fix the python code style check 

- .github/workflows/backport.yaml
- .github/workflows/changelog-check.yaml
- .github/workflows/code_style.yaml
- .pull-review
- scripts/backport.py
1. Find the latest release branch
1. For each commit in main and not in release branch (compared by title), find the corresponding PR.
1. If the PR fixes an issue labeled "bug", and neither the PR nor the issue are labeled "no-backport", cherry-pick the commits from the PR onto the release branch, and create a PR with these changes.
The resulting backport PRs: https://github.com/timescale/timescaledb/labels/pr-backport
> Add a workflow for automated backporting

- .github/workflows/changelog-check.yaml
- .pull-review
- scripts/backport.py
A follow-up for the review comments in the previous PR https://github.com/timescale/timescaledb/pull/5227
1. Create one backport PR per one source PR, even with multiple commits.
1. Add a comment to the source PR if we fail to backport it for some reason.
> Improve automated backports

- CHANGELOG.md
- tsl/src/data_node.c
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/test/shared/expected/dist_queries.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/dist_queries.sql
- tsl/test/src/data_node.c
The function to execute remote commands on data nodes used a blocking libpq API that doesn't integrate with PostgreSQL interrupt handling, making it impossible for a user or statement timeout to cancel a remote command.
Refactor the remote command execution function to use a non-blocking API and integrate with PostgreSQL signal handling via WaitEventSets.
Partial fix for #4958.
> Make data node command execution interruptible

- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_hypertable-15.out
- tsl/test/sql/dist_hypertable.sql.in
A previous change accidentally broke the dist_hypertable test so that it prematurely exited. This change restores the test so that it executes properly.
> Fix dist_hypertable test

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.9.2 release.
This release is high priority for upgrade. We strongly recommend that you upgrade as soon as possible.
**Bugfixes**
* https://github.com/timescale/timescaledb/pull/4804 Skip bucketing when start or end of refresh job is null
* https://github.com/timescale/timescaledb/pull/5108 Fix column ordering in compressed table index not following the order of a multi-column segment by definition
* https://github.com/timescale/timescaledb/pull/5187 Don't enable clang-tidy by default
* https://github.com/timescale/timescaledb/pull/5255 Fix year not being considered as a multiple of day/month in hierarchical continuous aggregates
* https://github.com/timescale/timescaledb/pull/5259 Lock down search_path in SPI calls
> Release 2.9.3

- CHANGELOG.md
- tsl/src/continuous_aggs/options.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
consider the sql commands:
```
drop table if EXISTS "tEst2" ;
-- Creating hypertable
CREATE TABLE IF NOT EXISTS "tEst2" (
"Id" uuid NOT NULL,
"Time" timestamp with time zone NOT NULL,
CONSTRAINT "test2_pkey" PRIMARY KEY ("Id", "Time")
);
SELECT create_hypertable(
'"tEst2"',
'Time',
chunk_time_interval => INTERVAL '1 day'
);
alter table "tEst2" set (timescaledb.compress=true, timescaledb.compress_segmentby='"Id"');
DROP MATERIALIZED VIEW if EXISTS "tEst2_mv";
CREATE MATERIALIZED VIEW "tEst2_mv"
WITH (timescaledb.continuous) AS
SELECT "Id" as "Idd",
time_bucket(INTERVAL '1 day', "Time") AS "bUcket"
FROM public."tEst2" 
GROUP BY "Idd", "bUcket";
ALTER MATERIALIZED VIEW "tEst2_mv" SET (timescaledb.compress = true);
```
before this patch the last command failed because:
* the `Idd` column lost …
> Compression can't be enabled on continuous aggregates when segmentby/orderby columns need quotation

- .github/workflows/backport.yaml
- scripts/backport.py
Apparently in some cases we're getting a shallow repo in the Github Actions.
> When backporting, fetch the main branch with large depth

- tsl/test/expected/compression_hypertable.out
- tsl/test/sql/compression_hypertable.sql
- tsl/test/sql/include/compression_test_hypertable.sql
The hypertable_compression test had on implicit reliance on the ordering of tuples when querying the materialized results. This patch makes the ordering explicit in this test.
> Fix compression_hypertable ordering reliance

- CHANGELOG.md
- src/bgw/job_stat.c
- test/src/bgw/scheduler_mock.c
- tsl/test/expected/fixed_schedules.out
- tsl/test/expected/scheduler_fixed.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/fixed_schedules.sql
- tsl/test/sql/include/scheduler_fixed_common.sql
- tsl/test/sql/scheduler_fixed.sql
- tsl/test/t/006_job_crash_log.pl
This patch fixes several issues with next_start calculation.
- Previously, the offset was added twice in some cases.
This is fixed by this patch.
- Additionally, schedule intervals with month components
were not handled correctly.
Internally, time_bucket with origin is used to calculate
the next start. However, in the case of month intervals, the
timestamp calculated for a bucket is always aligned on the first
day of the month, regardless of origin.
Therefore, previously the result was aligned with origin by adding
the difference between origin and its respective time bucket.
This difference was computed as a fixed length interval in terms
of days and time. That computation led to incorrect computation of
next start occasionally, for example when a job should be executed on
the last day …
> Fix next_start calculation for fixed schedules 

- coccinelle/ereport_pg12.cocci
- src/guc.c
- test/expected/insert_single.out
- test/sql/insert_single.sql
- tsl/test/expected/dist_copy_available_dns.out
- tsl/test/expected/dist_copy_long.out
Just noticed abysmal INSERT performance when experimenting with one of our customers' data set, and turns out my cache sizes were misconfigured, leading to constant hypertable chunk cache thrashing. Show a warning to detect this misconfiguration. Also use more generous defaults, we're not supposed to run on a microwave (unlike Postgres).
> Warn about mismatched chunk cache sizes

- src/guc.c
- src/ts_catalog/metadata.c
- src/utils.c
- tsl/src/data_node.c
PG16's dev branch has added a few new assertions and type-safety improvements that trip against our extension. This PR contains a few related fixes; I think they'd be desirable even if the upstream changes were eventually reverted before release.
> Miscellaneous fixups for PG16

- CHANGELOG.md
- scripts/test_update_from_tag.sh
- src/partitioning.c
- src/partitioning.h
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
Using `strlcpy` to copy variables holding PostgreSQL names can cause issues since names are fixed-size types of length 64. This means that any data that follows the initial null-terminated string will also be part of the data.
Instead of using `const char*` for PostgreSQL names, use `NameData` type for PostgreSQL names and use `namestrcpy` to copy them rather than `strlcpy`, which is a safe alternative since it will write null characters to the entire buffer.
> Use NameData and namestrcpy for names

- tsl/src/continuous_aggs/create.c
> Fix uninitialized `bucket_info.htpartcolno` warning

- src/ts_catalog/continuous_agg.h
- tsl/src/continuous_aggs/create.c
To don't make developers confused the right name for Continuous Aggregates on top of another Continuous Aggregates is `Hierarchical Continuous Aggregates`, so changed the usage of term `nested` for `hierarchical`.
> Change usage of term nested to hierarchical

- src/bgw/scheduler.c
- src/bgw/worker.h
The content of `bgw_main` is copied into `BackgroundWorker.bgw_function_name`, which [has a length of ](https://github.com/postgres/postgres/blob/c8e1ba736b2b9e8c98d37a5b77c4ed31baf94147/src/include/postmaster/bgworker.h#L97)`BGW_MAXLEN`. This patch ensures that the size of these fields has the same length.
---
Found by: https://github.com/timescale/timescaledb/pull/5340
> Change bgw_main field length to BGW_MAXLEN

- CHANGELOG.md
- tsl/src/bgw_policy/job.c
When executing functions, SPI assumes that `TopTransactionContext` is used for atomic execution contexts and `PortalContext` is used for non-atomic contexts. Since jobs need to be able to commit and start transactions, they are executing in a non-atomic context hence `PortalContext` will be used, but `PortalContext` is not set when starting the job. This is not a problem for PL/PgSQL executor, but for other executors (such as PL/Python) it would be.
This commit fixes the issue by setting the `PortalContext` variable to the portal context created for the portal and restores it (to NULL) after execution.
Fixes #5326
> Set PortalContext when starting job

- scripts/test_update_from_tag.sh
The upgrade and downgrade tests are running PostgreSQL in Docker containers. The function 'wait_for_pg' is used to determine if PostgreSQL is ready to accept connections. In contrast to the upgrade tests, the downgrade tests use [more relaxed timeout values](https://github.com/timescale/timescaledb/blob/83fc20f1954c5ff0d22f790cd8ee11309724445a/scripts/test_downgrade_from_tag.sh#L139). The upgrade tests [sometimes fail](https://github.com/timescale/timescaledb/actions/runs/4221187281/jobs/7328191286) because PostgreSQL does not accept connections within the configured time range. This patch applies the more relaxed timeout values also to the upgrade script.
> Increase timeout for PostgreSQL in upgrade tests

- CHANGELOG.md
- src/process_utility.c
- src/ts_catalog/metadata.c
While running TimescaleDB under valgrind I've found two cases of incorrect memory handling.
Case 1: When creating timescaledb extension, during the insertion of metadata there is some junk in memory that is not zeroed before writing there.
Changes in metadata.c fix this.
Case 2: When executing GRANT smth ON ALL TABLES IN SCHEMA some_schema and deconstructing this statement into granting to individual tables, process of copying names of those tables is wrong. Currently, you aren't copying the data itself, but an address to data on a page in some buffer. There's a problem - when the page in this buffer changes, copied address would lead to wrong data. Changes in process_utility.c fix this by allocating memory and then copying needed relname there.
Fixes #5311
> Fix some incorrect memory handling

- coccinelle/namedata.cocci
- scripts/coccinelle.sh
NameData is a fixed-size type of 64 bytes. Using strlcpy to copy data into a NameData struct can cause problems because any data that follows the initial null-terminated string will also be part of the data.
Note:
Should be merged after #5336, #5345, and #5317
> Added coccinelle rule to find strlcpy on NameData

- src/copy.c
Having the hash table named makes debugging easier as the name is used for the MemoryContext used by the hash table.
> Set name for COPY insert buffer hash table

- CHANGELOG.md
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/planner/planner.c
- tsl/src/fdw/data_node_scan_plan.c
- tsl/src/fdw/data_node_scan_plan.h
- tsl/src/fdw/fdw.c
- tsl/src/fdw/fdw.h
- tsl/src/fdw/relinfo.c
- tsl/src/fdw/relinfo.h
- tsl/src/fdw/shippable.c
- tsl/src/init.c
- tsl/test/expected/dist_ref_table_join-12.out
- tsl/test/expected/dist_ref_table_join-13.out
- tsl/test/expected/dist_ref_table_join-14.out
- tsl/test/expected/dist_ref_table_join-15.out
- tsl/test/sql/dist_ref_table_join.sql.in
This patch adds the functionality that is needed to perform distributed, parallel joins on reference tables on access nodes. This code allows the pushdown of a join if:
* (1) The setting "ts_guc_enable_per_data_node_queries" is enabled
* (2) The outer relation is a distributed hypertable
* (3) The inner relation is marked as a reference table
* (4) The join is a left join or an inner join
> Allow pushdown of reference table joins

- sql/size_utils.sql
- tsl/test/expected/size_utils.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/size_utils.sql
This small patch adds support for continuous aggregates to the
`hypertable_detailed_size` (and with that `hypertable_size`).
It adds an additional check to see if a continuous aggregate exists
if a hypertable with the given regclass name isn't found.
> Support CAGG names in hypertable_(detailed_)size

- tsl/src/continuous_aggs/create.c
The `bucket_info` variable is initialized by `caggtimebucketinfo_init` function called inside the following branch:
`if (rte->relkind == RELKIND_RELATION || rte->relkind == RELKIND_VIEW)`
If for some reason we don't enter in this branch then the `bucket_info` will not be initialized leading to an uninitialized variable when returning `bucket_info` at the end of the `cagg_validate_query` function.
Fixed it by initializing with zeros the `bucket_info` variable when declaring it.
Found by coverity scan:
https://scan4.scan.coverity.com/reports.htm#v54116/p12995/fileInstanceId=128875670&defectInstanceId=14557559&mergedDefectId=383108
> Fix uninitialized bucket_info variable

- src/import/CMakeLists.txt
- src/import/ht_hypertable_modify.c
- src/import/ht_hypertable_modify.h
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
This patch backports following:
1. Refactor ExecInsert/Delete/Update Backported commit 25e777cf8e547d7423d2e1e9da71f98b9414d59e
2. Backport all MERGE related interfaces and its implementations. Backported commit 7103ebb7aae8ab8076b7e85f335ceb8fe799097c
> Backport MERGE command specific postgresql code

- src/process_utility.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
We cannot create indexes on foreign tables. This PR modifies process_index_chunk to skip OSM chunks
> Create index fails if hypertable has foreign table chunk

- CHANGELOG.md
- sql/views.sql
- tsl/test/expected/information_view_chunk_count.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/information_view_chunk_count.sql
Different num_chunks values reported by
timescaledb_information.hypertables and
timescaledb_information.chunks.
View definition of hypertables was
not filtering dropped and osm_chunks.
Fixes #5338
> Fix for inconsistent num_chunks

- tsl/src/fdw/data_node_scan_plan.c
- tsl/test/expected/dist_ref_table_join-12.out
- tsl/test/expected/dist_ref_table_join-13.out
- tsl/test/expected/dist_ref_table_join-14.out
- tsl/test/expected/dist_ref_table_join-15.out
- tsl/test/sql/dist_ref_table_join.sql.in
At the moment, the `MERGE` command [is not supported](https://github.com/timescale/timescaledb/pull/5150) on distributed hypertables. When the join planner hook is invoked by a `MERGE` command, a few data structures are uninitialized (e.g., `nparts` of a distributed hypertable is set to -1). This patch ensures that the join pushdown code can handle these invocations. The patch restricts the invocations of the code to `SELECT` statements. This restriction can be lifted after `MERGE` is fully supported.
---
Found by SQLSmith: https://github.com/timescale/timescaledb/actions/runs/4253118392/jobs/7397565855
SQLSmith run with fix: https://github.com/timescale/timescaledb/actions/runs/4256142168
> Restrict the reference join pushdowns to SELECT statements

- CHANGELOG.md
- tsl/src/remote/copy_fetcher.c
Make the copy fetcher more asynchronous by separating the sending of the request for data from the receiving of the response. By doing that, the async append node can send the request to each data node before it starts reading the first response. This can massively improve the performance because the response isn't returned until the remote node has finished executing the query and is ready to return the first tuple.
> Make copy fetcher more async

- tsl/test/shared/sql/CMakeLists.txt
It was incorrectly flagged as requiring a debug build.
> Flag test space_constraint.sql.in for release run

- .github/workflows/apt-arm-packages.yaml
We only package timescaledb for ubuntu kinetic on PG14 because there are no prebuilt postgres packages available for the other postgres versions.
> Adjust ARM64 package test

- .github/workflows/sanitizer-build-and-test.yaml
Sanitizer tests take a long time to run so we don't want to run them on individual PRs but instead run them nightly and on commits to master.
> Don't run sanitizer test on individual PRs

- CHANGELOG.md
- sql/updates/2.4.1--2.4.2.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
For continuous aggregates with the old-style partial aggregates renaming columns that are not in the group-by clause will generate an error when upgrading to a later version. The reason is that it is implicitly assumed that the name of the column is the same as for the direct view. This holds true for new-style continous aggregates, but is not true for old-style continuous aggregates.
This commit fixes that by extracting the name of the column from the partial view and use that when renaming the partial view column and the materialized table column.
Fixes #5348
> Rename columns in old-style continuous aggregates

- tsl/src/data_node.c
- tsl/src/data_node.h
- tsl/src/dist_backup.c
- tsl/src/remote/dist_copy.c
We added checks via #4846 to handle DML HA when replication factor is
greater than 1 and a datanode is down. Since each insert can go to a different
chunk with a different set of datanodes, we added checks on every insert to check if DNs are unavailable. This increased CPU consumption on the AN leading to a performance regression for RF > 1 code paths.
This patch fixes this regression. We now track if any DN is marked as unavailable at the start of the transaction and use that information to reduce unnecessary checks for each inserted row.
> Fix perf regression due to DML HA

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/sql/include/cagg_on_cagg_common.sql
When a Continuous Aggregate is created the `chunk_interval_size` is defined my the `chunk_interval_size` of the original hypertable multiplied by a fixed factor of 10.
The problem is currently when we create a Hierarchical Continuous Aggregate the same factor is applied and it lead to an exponential `chunk_interval_size`.
Fixed it by just copying the `chunk_interval_size` from the base Continuous Aggregate for an Hierachical Continuous Aggreagate.
Fixes #5382
> Fix Hierarchical CAgg chunk_interval_size

- src/CMakeLists.txt
- src/chunk.c
- src/hypertable.c
- src/osm_callbacks.c
- src/osm_callbacks.h
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
- tsl/test/src/test_chunk_stats.c
To properly clean up the OSM catalog we need a way to reliably track hypertables deletion (including internal hypertables for CAGGs). This PR adds two more hooks:
- `hypertable_drop_hook`
- `hypertable_drop_by_name_hook`
> Add hooks for hypertable deletion

- CHANGELOG.md
- src/ts_catalog/chunk_data_node.c
- tsl/src/chunk.c
- tsl/src/chunk_api.c
- tsl/src/data_node.c
- tsl/src/fdw/modify_exec.c
- tsl/test/isolation/expected/dist_ha_chunk_drop.out
- tsl/test/isolation/expected/dist_restore_point.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/dist_ha_chunk_drop.spec.in
- tsl/test/isolation/specs/dist_restore_point.spec.in
Concurrent insert into dist hypertable after a data node marked as unavailable would produce 'tuple concurrently deleted` error.
The problem occurs because of missing tuple level locking during scan and concurrent delete from chunk_data_node table afterwards, which should be treated as `SELECT … FOR UPDATE` case instead.
Fix #5153
> Fix concurrent locking with chunk_data_node table

- .github/workflows/windows-build-and-test-ignored.yaml
- .github/workflows/windows-build-and-test.yaml
- .github/workflows/windows-packages.yaml
Chocolatey has all the postgres versions we need available so we can reenable previously disabled tests. But the recent packages seem to have different versioning schema without a suffix.
> Fix windows package test

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.10.0 release.
**Bugfixes**
* #5226 Fix concurrent locking with chunk_data_node table
* #5317 Fix some incorrect memory handling
* #5336 Use NameData and namestrcpy for names
* #5343 Set PortalContext when starting job
* #5360 Fix uninitialized bucket_info variable
* #5362 Make copy fetcher more async
* #5364 Fix num_chunks inconsistency in hypertables view
* #5367 Fix column name handling in old-style continuous aggregates
* #5378 Fix multinode DML HA performance regression
* #5384 Fix Hierarchical Continuous Aggregates chunk_interval_size
**Thanks**
* @justinozavala for reporting an issue with PL/Python procedures in the background worker
* @Medvecrab for discovering an issue with …
> Release 2.10.1

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/sql/cagg_on_cagg.sql
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
Previously we used date_part("epoch", interval) and integer division
internally to determine whether the top cagg's interval is a
multiple of its parent's.
This led to precision loss and wrong results
in the case of intervals with sub-second components.
Fixed by using the `ts_interval_value_to_internal` function to convert
intervals to appropriate integer representation for division.
Fixes #5277
> Fix sub-second intervals in hierarchical caggs

- src/chunk_adaptive.c
- test/expected/chunk_adaptive.out
- test/sql/chunk_adaptive.sql
When called with negative chunk_target_size_bytes calculate_chunk_interval will throw an assertion. This patch adds error handling for this condition. Found by sqlsmith.
> Fix assertion in calculate_chunk_interval for negative target size

- CHANGELOG.md
- sql/partialize_finalize.sql
- src/planner/expand_hypertable.c
- src/planner/partialize.c
- src/planner/planner.c
- src/planner/planner.h
- tsl/test/expected/dist_copy_long.out
- tsl/test/expected/dist_partial_agg-12.out
- tsl/test/expected/dist_partial_agg-13.out
- tsl/test/expected/dist_partial_agg-14.out
- tsl/test/expected/dist_partial_agg-15.out
- tsl/test/expected/partialize_finalize.out
- tsl/test/sql/dist_copy_long.sql
- tsl/test/sql/dist_partial_agg.sql.in
- tsl/test/sql/partialize_finalize.sql
Make `partialize_agg()` support parallel query execution. To make this work, the finalize node need combine the individual partials from each parallel worker, but the final step that turns the resulting partial into the finished aggregate should not happen. Thus, in the case of distributed hypertables, each data node can run a parallel query to compute a partial, and the access node can later combine and finalize these partials into the final aggregate. Esssentially, there will be one combine step (minus final) on each data node, and then another one plus final on the access node.
To implement this, the finalize aggregate plan is simply modified to elide the final step, and to reserialize the partial. It is only possible to do this at the plan stage; if done at the path stage, the …
> Add parallel support for partialize_agg()

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/shared/expected/constraint_exclusion_prepared.out
- tsl/test/shared/expected/ordered_append-12.out
- tsl/test/shared/expected/ordered_append-13.out
- tsl/test/shared/expected/ordered_append-14.out
- tsl/test/shared/expected/ordered_append-15.out
- tsl/test/sql/compression_qualpushdown.sql
WHERE clause with SEGMENTBY column of type text/bytea non-equality operators are not pushed down to Seq Scan node of compressed chunk. This patch fixes this issue.
Fixes #5286
> Fix SEGMENTBY columns predicates to be pushed down

- src/indexing.c
Rely on postgres functionality for index column tracking instead of rolling our own.
> Simplify ts_indexing_relation_has_primary_or_unique_index

- CHANGELOG.md
- tsl/src/remote/copy_fetcher.c
- tsl/test/expected/data_fetcher.out
- tsl/test/sql/data_fetcher.sql
- tsl/test/sql/include/data_fetcher_run.sql
The copy fetcher fetches tuples in batches. When the last element in the batch is the file trailer, the trailer was not handled correctly. The existing logic did not perform a PQgetCopyData in that case. Therefore the state of the fetcher was not set to EOF and the copy operation was not correctly finished at this point.
Fixes: #5323, #5394
> Fix file trailer handling in the copy fetcher

- CMakeLists.txt
- src/compat/compat.h
Use explicit version checks to decide whether to define backported RelationGetSmgr function or rely on the function being available. This simplifies the cmake code a bit and make the backporting similar to how we handle this for other functions.
> Use version checks to decide about RelationGetSmgr backporting

- tsl/src/remote/copy_fetcher.c
The commit 96574a749757b20e995dd6fcd9be5140f34092c1 changes the handling of the `file_trailer_received` flag. It
is now only used in asserts and not in any other kind of logic. This
patch encapsulates the `file_trailer_received` in a `USE_ASSERT_CHECKING`
macro.
> Track file trailer only in debug builds

- tsl/src/compression/deltadelta.c
- tsl/src/compression/deltadelta.h
- tsl/src/compression/gorilla.c
- tsl/test/expected/compression_algos.out
- tsl/test/sql/compression_algos.sql
- tsl/test/sql/include/compression_utils.sql
- tsl/test/src/test_compression.c
Unit tests for different data sequences, and SQL test for float4.
> Add more tests for compression

- CHANGELOG.md
- src/license_guc.c
- tsl/src/init.c
When the guc timescaledb.license = 'timescale' is set in the conf file
and a SIGHUP is sent to postgress process and a reload of the tsl
module is triggered.
This reload happens in 2 phases 1. tsl_module_load is called which
will load the module only if not already loaded and 2.The
ts_module_init is called for every ts_license_guc_assign_hook
irrespective of if it is new load.This ts_module_init initialization
function also registers a on_proc_exit function to be called on exit.
The list of on_proc_exit methods are maintained in a fixed array
on_proc_exit_list of size MAX_ON_EXITS (20) which gets filled up on
repeated SIGHUPs and hence an error.
Fix:
The fix is to make the ts_module_init() register the on_proc_exit
callback, only in case the module is reloaded and not in every init
call. …
> Out of on_proc_exit slots on guc license change

- CHANGELOG.md
- tsl/src/fdw/relinfo.c
- tsl/test/expected/data_fetcher.out
- tsl/test/sql/data_fetcher.sql
- tsl/test/sql/include/data_fetcher_fdw_settings.sql
This patch changes the way user-defined FDW options (e.g., startup costs, per-tuple costs) are handled. So far, these values were retrieved in `apply_fdw_and_server_options()` but reset to default values afterward.
> Handle user-defined FDW options properly

- src/chunk_adaptive.c
- src/chunk_index.c
- src/utils.c
- src/utils.h
This patch adds a function ts_map_attno that can be used to map the attribute number from one relation to another by column name.
> Add utility function to map attribute numbers

- CHANGELOG.md
- src/chunk.c
- src/chunk.h
- src/copy.c
- src/cross_module_fn.h
- src/indexing.c
- src/indexing.h
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/process_utility.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/create.c
- tsl/src/init.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_conflicts.out
- tsl/test/expected/compression_errors.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_conflicts.sql
- tsl/test/sql/compression_errors.sql
This patch allows unique constraints on compressed chunks. When trying to INSERT into compressed chunks with unique constraints any potentially conflicting compressed batches will be decompressed to let postgres do constraint checking on the INSERT. With this patch only INSERT ON CONFLICT DO NOTHING will be supported. For decompression only segment by information is considered to determine conflicting batches. This will be enhanced in a follow-up patch to also include orderby metadata to require decompressing less batches.
> Support ON CONFLICT DO NOTHING on compressed hypertables

- src/chunk.c
When adding new status values we must make sure to add special handling for these values to the downgrade script as previous versions will not know how to deal with those.
> Mention that new status values need handling in downgrade script

- CHANGELOG.md
- test/sql/include/test_utils.sql
- tsl/src/compression/compression.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/include/compression_alter.sql
The sql function decompress_chunk did not filled in default values during its operation.
> Decompression may have lost DEFAULT values

- CHANGELOG.md
- src/utils.h
- tsl/src/remote/connection.c
The functions `PQconndefaults` and `PQmakeEmptyPGresult` calls
`malloc` and can return NULL if it fails to allocate memory for the
defaults and the empty result. It is checked with an `Assert`, but this
will be removed in production builds.
Replace the `Assert` with an checks to generate an error in production
builds rather than trying to de-reference the pointer and cause a
crash.
Fixes #5447
> Add check for malloc failure in libpq calls

- .gitignore
Recent versions of clangd store cached data in the `.cache` directory instead of `.clangd`; this PR makes the new directory ignored by Git in addition to the old one.
> Add new clangd cache location to gitignore

- CHANGELOG.md
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- tsl/test/expected/compression.out
- tsl/test/expected/compression_conflicts.out
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_conflicts.sql
This patch fixes execution of INSERT with ON CONFLICT DO UPDATE by removing error and allowing UPDATE do happen on the given compressed hypertable.
> Add support for ON CONFLICT DO UPDATE for compressed hypertables.

- CHANGELOG.md
- src/scanner.c
Invalidate the catalog snapshot in the scanner to ensure that any lookups into `pg_catalog` uses a snapshot that is consistent with the snapshot used to scan TimescaleDB metadata.
This fixes an issue where a chunk could be looked up without having a proper relid filled in, causing an assertion failure (`ASSERT_IS_VALID_CHUNK`). When a chunk is scanned and found (in `chunk_tuple_found()`), the Oid of the chunk table is filled in using `get_relname_relid()`, which could return InvalidOid due to use of a different snapshot when scanning `pg_class`. Calling `InvalidateCatalogSnapshot()` before starting the metadata scan in `Scanner` ensures the pg_catalog snapshot used is refreshed.
Due to the difficulty of reproducing this MVCC issue, there is not yet a regression or isolation test for it, …
> Use consistent snapshots when scanning metadata

- CHANGELOG.md
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/post-update.sql
- sql/updates/reverse-dev.sql
- sql/util_time.sql
- src/chunk.c
- src/hypertable.c
- src/hypertable.h
- src/ts_catalog/CMakeLists.txt
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- src/ts_catalog/continuous_agg.c
- src/ts_catalog/continuous_aggs_watermark.c
- src/ts_catalog/continuous_aggs_watermark.h
- test/expected/drop_rename_hypertable.out
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/materialize.c
- tsl/src/continuous_aggs/materialize.h
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/cagg_refresh.out
- tsl/test/expected/cagg_union_view-12.out
- tsl/test/expected/cagg_union_view-13.out
- tsl/test/expected/cagg_union_view-14.out
- tsl/test/expected/cagg_union_view-15.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/cagg_union_view.sql.in
When calling the `cagg_watermark` function to get the watermark of a
Continuous Aggregate we execute a `SELECT MAX(time_dimension)` query
in the underlying materialization hypertable.
The problem is that a `SELECT MAX(time_dimention)` query can be
expensive because it will scan all hypertable chunks increasing the
planning time for a Realtime Continuous Aggregates.
Improved it by creating a new catalog table to serve as a cache table
to store the current Continous Aggregate watermark in the following
situations:
- Create CAgg: store the minimum value of hypertable time dimension
data type;
- Refresh CAgg: store the last value of the time dimension materialized
in the underlying materialization hypertable (or the minimum value of
materialization hypertable time dimension data type if …
> Improve Realtime Continuous Aggregate performance

- CHANGELOG.md
- tsl/src/chunk_copy.c
There is a security loophole in current core Postgres, due to which it's possible for a non-superuser to gain superuser access by attaching dependencies like expression indexes, triggers, etc. before logical replication commences.
To avoid this, we now ensure that the chunk objects that get created for the subscription are done so as a superuser. This avoids malicious dependencies by regular users.
> Ensure superuser perms during copy/move chunk

- .github/workflows/linux-32bit-build-and-test.yaml
- CHANGELOG.md
- src/histogram.c
- test/expected/histogram_test.out
- test/sql/histogram_test.sql
There is a bug in `width_bucket()` causing an overflow and subsequent NaN value as a result of dividing with `+inf`. The NaN value is interpreted as an integer and hence generates an index out of range for the buckets.
This commit fixes this by generating an error rather than segfaulting for bucket indexes that are out of range.
Fixes #5489
> Do not segfault on large histogram() parameters

- tsl/test/isolation/expected/dist_su_copy_chunk.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/dist_su_copy_chunk.spec.in
Add isolation test case to check that the chunk object created during chunk copy/move operation on the destination datanode always has superuser credentials till the end of the operation.
Note that the flaky test run on CI will fail. This is because of issues with cleanup of multinode objects when a same MN isolation test is re-run repeatedly. Other MN isolation tests also suffer from the same issue. So it can be ignored for now.
> Add test for superuser chunk copy/move

- src/planner/planner.c
OSM chunks have their own `fdw_private` which conflicts with checks in the `MergeAppend` code path causing segfaults. This PR fixes this by returning early when there is an OSM chunk in the `MergeAppendPath`.
> Disallow MergeAppend optimizations when there is an OSM chunk

- CHANGELOG.md
- tsl/src/fdw/option.c
- tsl/src/nodes/data_node_copy.c
- tsl/src/remote/CMakeLists.txt
- tsl/src/remote/connection.c
- tsl/src/remote/connection.h
- tsl/src/remote/dist_copy.c
- tsl/src/remote/dist_copy.h
- tsl/test/expected/dist_copy_format_long.out
- tsl/test/expected/dist_remote_error-14.out
- tsl/test/expected/dist_remote_error-15.out
- tsl/test/expected/remote_copy-12.out
- tsl/test/expected/remote_copy-13.out
- tsl/test/expected/remote_copy-14.out
- tsl/test/expected/remote_copy-15.out
- tsl/test/sql/dist_copy_format_long.sql
- tsl/test/sql/remote_copy.sql.in
Refactor the code path that handles remote distributed COPY. The
main changes are:
* Use a hash table to lookup data node connections instead of a list.
* Reduce the number of data copies by accumulating bigger CopyData
messages directly in the libpq connection buffer instead of doing it
in a separate buffer which later requires copying the data. To
achieve this, some internal libpq functions are imported that gives
more fine-grain control over buffers.
* Add an foreign data wrapper option to set the number of rows to
send in a CopyData message.
> Refactor and optimize distributed COPY

- CHANGELOG.md
- src/cross_module_fn.h
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/init.c
- tsl/src/planner.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/expected/compression.out
- tsl/test/expected/compression_permissions.out
- tsl/test/expected/compression_update_delete.out
- tsl/test/expected/continuous_aggs-12.out
- tsl/test/expected/continuous_aggs-13.out
- tsl/test/expected/continuous_aggs-14.out
- tsl/test/expected/continuous_aggs-15.out
- tsl/test/expected/continuous_aggs_deprecated.out
- tsl/test/isolation/expected/compression_dml_iso.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/compression_dml_iso.spec
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_update_delete.sql
- tsl/test/sql/continuous_aggs.sql.in
- tsl/test/sql/continuous_aggs_deprecated.sql
This patch does following:
1. Executor changes to parse qual ExprState to check if SEGMENTBY
column is specified in WHERE clause.
2. Based on step 1, we build scan keys.  
3. Executor changes to do heapscan on compressed chunk based on
scan keys and move only those rows which match the WHERE clause
to staging are aka uncompressed chunk.
4. Mark affected chunk as partially compressed.
5. Perform regular UPDATE/DELETE operations on staging area aka
uncompressed chunk.
6. Since there is no Custom Scan (HypertableModify) node for
UPDATE/DELETE operations on PG versions < 14, we don't support this
feature on PG12 and PG13.
> Support UPDATE/DELETE on compressed hypertables.

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
Decompression produces records which have all the decompressed data set, but it also retains the fields which are used internally during decompression.
These didn't cause any problem - unless an operation is being done with the whole row - in which case all the fields which have ended up being non-null can be a potential segfault source.
Fixes #5458 #5411
> Fix segfault after column drop on compressed table

- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
Now we look them up at execution time for each chunk separately, which adds up for tables with a large number of chunks.
This gives about 15% speedup (100 mcs) on a small query on a table from tests with 50 chunks:
`select id, ts, value from metric_compressed order by id, ts limit 100;`
> Look up compressed column metadata at planning time

- src/cross_module_fn.c
- src/nodes/chunk_dispatch/chunk_dispatch.c
- test/expected/license.out
Commit 57fde383b3dddd0b52263218e65a0135981c2d34 changed the messaging but did not format the error hint correctly. This patch fixes the error hint.
> Properly format license error hint

- sql/updates/post-update.sql
Commit 8afdddc2da added the first step for deprecating the old format of Continuous Aggregate but just for PostgreSQL 15 and later versions.
During the extension update we emit a message about the deprecation but this has being emited even if the user is using PostgreSQL versions before 15.
Fixed it by emiting the WARNING just when PostgreSQL version is greater or equal to 15.
> Silence WARNING after extension update

- tsl/test/expected/compression_ddl.out
- tsl/test/isolation/expected/compression_ddl_iso.out
- tsl/test/isolation/specs/compression_ddl_iso.spec
- tsl/test/sql/compression_ddl.sql
This PR contains a couple of commits that add tests to recent compression DML changes:
- tests with physical layout changes and index mapping while inserting into compressed chunks
- isolation tests to test locking between multiple insert sessions and using RETURNING clause
> Add more compression DML tests

- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- tsl/src/compression/compression.c
- tsl/test/isolation/expected/compression_conflicts_iso.out
- tsl/test/isolation/expected/compression_ddl_iso.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/compression_conflicts_iso.spec
While executing compression operations in parallel with inserting into chunks (both operations which can potentially change the chunk status), we could get into situations where the chunk status would end up inconsistent. This change re-reads the chunk status after locking the chunk to make sure it can decompress data when handling ON CONFLICT inserts correctly.
Fixes #5398 #5471 #5480
> Fix chunk status when inserting into chunks

- CHANGELOG.md
- src/planner/planner.c
- test/expected/agg_bookends-12.out
- test/expected/agg_bookends-13.out
- test/expected/agg_bookends-14.out
- test/expected/agg_bookends-15.out
- test/expected/query-12.out
- test/expected/query-13.out
- test/expected/query-14.out
- test/expected/query-15.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/compression_insert-15.out
- tsl/test/expected/dist_hypertable-12.out
- tsl/test/expected/dist_hypertable-13.out
- tsl/test/expected/dist_hypertable-14.out
- tsl/test/expected/dist_hypertable-15.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
This is mostly a cosmetic change. When only 1 child is present there is no need for ordered append. In this situation we might still benefit from a ChunkAppend node here due to runtime chunk exclusion when we have non-immutable constraints, so we still add the ChunkAppend node in that situation even with only 1 child.
> Skip Ordered Append when only 1 child node is present

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_joins-12.out
- tsl/test/expected/cagg_joins-13.out
- tsl/test/expected/cagg_joins-14.out
- tsl/test/expected/cagg_joins-15.out
Several error messages for continuous aggregates are not following the error message style guidelines at
https://www.postgresql.org/docs/current/error-style-guide.html
In particular, they do not write the hints and detailed messages as full sentences.
> Fix error message for continuous aggregates

- CHANGELOG.md
- src/time_utils.c
- src/time_utils.h
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/sql/include/cagg_ddl_common.sql
When refreshing from the beginning (window_start=NULL) of a
Continuous Aggregate with variable time bucket we were getting a
`timestamp out of range` error.
Fixed it by setting `-Infinity` when passing `window_start=NULL` when
refreshing a Continuous Aggregate with variable time bucket.
Fixes #5474, #5534
> Fix timestamp out of range refreshing CAgg

- CHANGELOG.md
- sql/views_experimental.sql
- tsl/test/expected/cagg_policy.out
- tsl/test/sql/cagg_policy.sql
Commit 16fdb6ca5e introduced `timescaledb_experimental.policies` view to expose the Continuous Aggregate policies but the current JOINS over our catalog are not accurate.
Fixed it by properly JOIN the underlying catalog tables to expose the correct information without duplicates about the Continuous Aggregate policies.
Fixes #5492
> Fix timescaledb_experimental.policies duplicates

- CHANGELOG.md
- src/process_utility.c
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
With recent changes, we enabled analyze on uncompressed chunk tables for compressed chunks. This change includes analyzing the compressed chunks table when analyzing the hypertable and its chunks, enabling us to remove the generating stats when compressing chunks.
Fixes #5431
> Propagate vacuum/analyze to compressed chunks

- tsl/test/sql/CMakeLists.txt
Running the test dist_move_chunk in parallel can 
cause deadlock(and timeouts) in other tests running
in parallel on PG15.2. Force the test to run solo.
> Force dist_move_chunk as solo test for PG15.2

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
Decompression produces records which have all the decompressed data set, but it also retains the fields which are used internally during decompression.
These didn't cause any problem - unless an operation is being done with the whole row - in which case all the fields which have ended up being non-null can be a potential segfault source.
Fixes #`5458` #`5411`
cherry-picked from 975e9ca1
Backport of https://github.com/timescale/timescaledb/pull/5462
> Backport to 2.10.x: Fix segfault after column drop on compressed table

- CHANGELOG.md
- src/bgw/scheduler.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
The start_scheduled_jobs function mistakenly sorts the scheduled_jobs list in-place. As a result, when the ts_update_scheduled_jobs_list function compares the updated list of scheduled jobs with the existing scheduled jobs list, it is comparing a list that is sorted by job_id to one that is sorted by next_start time. Fix that by properly copying the scheduled_jobs list into a new list and use that for sorting.
Fixes #5537
> Copy scheduled_jobs list before sorting it

- .github/workflows/code_style.yaml
- scripts/check_missing_gitignore_for_template_tests.sh
- test/sql/.gitignore
Whenever we create a template sql file (*.sql.in) we should add the respective .gitignore entry for the generated test files.
So added a CI check to check for missing gitignore entries for generated test files.
> Add CI check for missing gitignore entries

- CHANGELOG.md
- tsl/src/nodes/gapfill/interpolate.c
- tsl/test/shared/expected/gapfill-12.out
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/expected/gapfill-15.out
- tsl/test/shared/sql/gapfill.sql.in
Include information about the expected and the returned datatype in the error details of interpolate.
Fixes #5555
> Improve interpolate error message on datatype mismatch

- scripts/backport.py
Makes it easier to check what was done when looking at the release milestone.
example: https://github.com/timescale/timescaledb/milestone/70?closed=1
> Add labels to backported PRs.

- test/sql/updates/post.repair.sql
Commit 3f9cb3c2 introduced new repair tests for broken Continuous Aggregates with JOIN clause but in the post.repair.sql we not properly calling the post.repair.cagg_joins.sql because a wrong usage of psql `if` statement.
> Fix post repair tests

- .github/gh_matrix_builder.py
- tsl/test/shared/expected/transparent_decompress_chunk-12.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
- tsl/test/shared/sql/transparent_decompress_chunk.sql.in
Transparent decompress chunk was added into to ignore list due to the side effect of #5118. This issue is to fix the flaky nature of the test.
> Fixed transparent decompress chunk

- CHANGELOG.md
- src/planner/planner.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
This was previously disabled as no data resided on the
uncompressed chunk once it was compressed, but this is not
the case anymore with partially compressed chunks, so we
enable indexscan for the uncompressed chunk again.
Fixes #5432
Co-authored-by: Ante Kresic <ante.kresic@gmail.com>
> Enable indexscan on uncompressed part of partially compressed chunks

- CHANGELOG.md
- tsl/src/compression/compression.c
- tsl/test/expected/compression_conflicts.out
- tsl/test/sql/compression_conflicts.sql
When inserting into a compressed chunk with constraints present, we need to decompress relevant tuples in order to do speculative inserting. Usually we used segment by column values to limit the amount of compressed segments to decompress. This change expands on that by also using segment metadata to further filter compressed rows that need to be decompressed.
> Reduce decompression during constraint checking

- CHANGELOG.md
- src/nodes/chunk_dispatch/chunk_dispatch.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
Inserting multiple rows into a compressed chunk could have bypassed
constraint check in case the table had segment_by columns.
Fixes #5553
> Fix unique constraint on compressed tables

- src/process_utility.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
This block was removed by accident, in order to support this we need to ensure the uniqueness in the compressed data which is something we should do in the future thus removing this block.
Fixes #5592 
> Block unique idx creation on compressed hypertable

- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
Some queries in `compression_ddl` had no order by. Therefore the output order was not defined, which led to flaky tests.
> Add missing order by to compression_ddl tests

- tsl/src/compression/create.c
- tsl/src/compression/create.h
Move the creation of metadata column names for min/max values to separate functions to make the code reusable.
> Make compression metadata column names reusable

- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
When updating or deleting tuples from a compressed chunk, we first need to decompress the matching tuples then proceed with the operation. This optimization reduces the amount of data decompressed by using compressed metadata to decompress only the affected segments.
> Reduce decompression during UPDATE/DELETE

- CHANGELOG.md
- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_repair.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_repair.sql
The internal `cagg_rebuild_view_definition` function was trying to cast a pointer to `RangeTblRef` but it actually is a `RangeTblEntry`.
Fixed it by using the already existing `direct_query` data struct to check if there are JOINs in the CAgg to be repaired.
Fixes #5601
> Fix broken CAgg with JOIN repair function

- CHANGELOG.md
- src/bgw/job.c
- src/bgw/job.h
- tsl/src/bgw_policy/job_api.c
- tsl/test/expected/bgw_security.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/bgw_security.sql
There were no permission checks when calling run_job(), so it was possible to execute any job regardless of who owned it. This commit adds such checks.
> Add permission checks to run_job()

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/cagg_repair.out
- tsl/test/sql/cagg_repair.sql
In commit 4a6650d1 we fixed the cagg_repair running for broken Continuous Aggregates with JOINs but we accidentally remove the code path for running agains the old format (finalized=false) leading us to a dead code pointed out by CoverityScan: https://scan4.scan.coverity.com/reports.htm#v54116/p12995/fileInstanceId=131706317&defectInstanceId=14569420&mergedDefectId=384044
Fixed it by restoring the old code path for running the cagg_repair for Continuous Aggregates in the old format (finalized=false).
> Fix cagg_repair for the old CAgg format

- .github/workflows/linux-build-and-test-ignored.yaml
We defined some paths to ignore regression test workflows when, for example, we change the CHANGELOG.md and others. But in fact it was not happening because we didn't define a proper name in the fake regression workflow that fake to the CI that some required status passed.
Fixed it defining a proper regression name like we do for the regular regression workflow and also added a path to ignore changes in the YAML file that define the workflow.
> Fix CI ignored regression workflows

- CHANGELOG.md
- tsl/src/compression/compression.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
On compressed tables 3 schema levels are active simultaneously;
in build_scankeys all of them appears - and the hypertable level slot
was access using sibling table indices.
Multiple alteration of the table schema could lead to segfaults as well.
Fixes #5577
depends on #5553
> Fix on-insert decompression after schema changes

- CHANGELOG.md
- sql/job_error_log_retention.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- sql/with_telemetry.sql
- test/expected/extension_scripts.out
- test/sql/extension_scripts.sql
- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
Need to use quote_ident() on the user roles. Otherwise the extension scripts will fail.
> Quote username identifier appropriately

- sql/CMakeLists.txt
- version.config
For less confusion if we ever want to do the 2.10.4.
> Bump version to 2.10.4 after release

- CHANGELOG.md
- tsl/src/compression/create.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
If a hypertable uses a non default tablespace, the compressed hypertable
and its corresponding toast table and index is still created in the
default tablespace.
This PR fixes this unexpected behavior and creates the compressed
hypertable and its toast table and index in the same tablespace as
the hypertable.
Fixes #5520
> Fix tablespace for compressed hypertable and corresponding toast 

- tsl/src/continuous_aggs/create.c
Don't need to check NULL for `direct_query->jointree` because we don't allow queries without FROM clause in Continuous Aggregate definition.
CoverityScan link:
https://scan4.scan.coverity.com/reports.htm#v54116/p12995/fileInstanceId=131745632&defectInstanceId=14569562&mergedDefectId=384045
> Fix CoverityScan deference after null check

- src/cross_module_fn.h
- src/nodes/hypertable_modify.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/init.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_update_delete.sql
During UPDATE/DELETE on compressed hypertables, we iterate over plan
tree to collect all scan nodes. For each scan nodes there can be
filter conditions.
Prior to this patch we collect only first filter condition and use
for first chunk which may be wrong. In this patch as and when we
encounter a target scan node, we immediately process those chunks.
Fixes #5640
> Fix segfault when deleting from compressed chunk

- src/cross_module_fn.h
- src/nodes/hypertable_modify.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
When JOINs were present during UPDATE/DELETE on compressed chunks
the code would decompress other hypertables that were not the
target of the UPDATE/DELETE operations and in the case of self-JOINs
potentially decompress chunks not required to be decompressed.
> Fix JOIN handling in UPDATE/DELETE on compressed chunks

- CHANGELOG.md
- src/process_utility.c
- test/expected/reloptions.out
- test/sql/reloptions.sql
Running ALTER TABLE SET with multiple SET clauses on a regular PostreSQL table produces irrelevant error when timescaledb extension is installed.
Fix #5641
> Fix ALTER TABLE SET with normal tables

- tsl/src/compression/compression.c
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
We need to use the correct qualifiers for index scans since the generic scan qualifiers are not populated in this case.
Fixes #5645
> Fix index scan handling in DML decompression

- src/guc.c
- src/guc.h
- src/planner/planner.c
- tsl/src/compression/compression.c
- tsl/src/nodes/compress_dml/compress_dml.c
- tsl/src/planner.c
- tsl/test/expected/compression_conflicts.out
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_conflicts.sql
- tsl/test/sql/compression_update_delete.sql
> Add GUC to enable/disable DML decompression

- .github/gh_matrix_builder.py
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- test/pg_regress.sh
dist_move_chunk and dist_param create a lot of friction due to their flakiness. Ignoring them until we can fix them.
Edit: make that dist_insert as well, it caused my CI to fail on this PR.
> Ignore multinode tests from PR CI runs

- tsl/src/compression/compression.c
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
Bitmap heap scans are specific in that they store scan state during node initialization. This means they would not pick up on any data that might have been decompressed during a DML command from the compressed chunk. To avoid this, we update the snapshot on the node scan state and issue a rescan to update the internal state.
Fixes #5658 
> Fix DML decompression issues with bitmap heap scan

- CHANGELOG.md
- src/bgw/job.c
- src/bgw/job_stat.c
- tsl/test/expected/bgw_telemetry.out
When executing a subtransaction using `BeginInternalSubTransaction` the memory context switches from the current context to `CurTransactionContext` and when the transaction is aborted or committed using `ReleaseCurrentSubTransaction` or `RollbackAndReleaseCurrentSubTransaction` respectively, it will not restore to the previous memory context or resource owner but rather use `TopTransactionContext`. Because of this, both the memory context and the resource owner will be wrong when executing `calculate_next_start_on_failure`, which causes `run_job` to generate an error when used with the telemetry job.
This commit fixes this by saving both the resource owner and the memory context before starting the internal subtransaction and restoring it after finishing the internal subtransaction.
Since …
> Fix subtransaction resource owner

- tsl/src/compression/compression.c
- tsl/test/isolation/expected/compression_dml_iso.out
- tsl/test/isolation/specs/compression_dml_iso.spec
When updating and deleting the same tuple while both transactions are running at the same time, we end up with reference leak. This is because one of the query in a transaction fails and we take error path. However we fail to close the table.
This patch fixes the above mentioned problem by closing the required tables.
Fixes #5674
> Fix leak during concurrent UPDATE/DELETE

- CHANGELOG.md
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- sql/with_telemetry.sql
- src/telemetry/telemetry.c
- src/telemetry/telemetry_metadata.c
- src/telemetry/telemetry_metadata.h
- src/ts_catalog/catalog.c
- src/ts_catalog/catalog.h
- test/expected/drop_rename_hypertable.out
- test/expected/pg_dump.out
- test/expected/telemetry.out
- test/sql/telemetry.sql
Add table `_timescaledb_catalog.telemetry_event` table containing
events that should be sent out with telemetry reports. The table will
be truncated after report being generated.
> Support sending telemetry event reports

- CHANGELOG.md
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression_join_index.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/transparent_decompression_join_index.sql
Previously when adding equivalence class members for the compressed
chunk's variables, we would only consider Vars. This led us to ignore
cases where the Var was wrapped in a RelabelType,
returning inaccurate results.
Fixed the issue by accepting Vars
with RelabelType for segmentby equivalence class.
Fixes #5585
> Fix DISTINCT query with JOIN on multiple segmentby columns

- .github/workflows/changelog-check.yaml
- .github/workflows/pr-validation.yaml
- .github/workflows/windows-build-and-test.yaml
Remove GitHub variables from locations where they are expanded in place.
See https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
> Use environment variables for workflows

- .github/workflows/changelog-check.yaml
- .unreleased/template.rfc822
- scripts/check_changelog_format.py
- scripts/delete_released_change_logs.sh
- scripts/merge_changelogs.sh
Improve changelog handling
Every PR to have its own changelog in the folder ".unreleased/features" or ".unreleased/bugfixes". The changes in this commit are to
1. workflow action to check if a PR has its own changelog file and the contents follow the changelog format.
2. merge the individual changelogs into the CHANGELOG.md file.
3. delete the individual changelogs, post release
https://timescale.slab.com/posts/the-new-changelog-handling-5bhnkqej
> Improve changelog handling

- src/chunk.c
- src/chunk_scan.c
- src/extension_utils.c
- src/hypertable.c
- src/process_utility.c
- src/ts_catalog/catalog.c
- src/ts_catalog/continuous_agg.c
- src/utils.h
- test/src/bgw/log.c
- test/src/bgw/params.c
- tsl/src/bgw_policy/job.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/continuous_aggs/create.c
In several places of our code base we use a combination of
`get_namespace_oid` and `get_relname_relid` to return the Oid of a
schema qualified relation, so refactored the code to encapsulate this
behavior in a single function.
> Introduce utility function ts_get_relation_relid

- .github/gh_matrix_builder.py
- .github/workflows/libfuzzer.yaml
- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/windows-build-and-test.yaml
- tsl/src/compression/compression.c
This serves as a way to exercise the decompression fuzzing code, which will be useful when we need to change the decompression functions. Also this way we'll have a check in CI that uses libfuzzer, and it will be easier to apply it to other areas of code in the future.
> Compression fuzzing in CI

- .unreleased/PR_5150
- CHANGELOG.md
- src/import/ht_hypertable_modify.c
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/hypertable_modify.c
- src/partitioning.c
- src/planner/planner.c
- test/expected/merge.out
- test/expected/ts_merge.out
- test/sql/CMakeLists.txt
- test/sql/include/ts_merge_load.sql
- test/sql/include/ts_merge_load_ht.sql
- test/sql/include/ts_merge_query.sql
- test/sql/merge.sql
- test/sql/ts_merge.sql
- tsl/src/planner.c
- tsl/test/expected/dist_ref_table_join-12.out
- tsl/test/expected/dist_ref_table_join-13.out
- tsl/test/expected/dist_ref_table_join-14.out
- tsl/test/expected/dist_ref_table_join-15.out
- tsl/test/expected/merge_compress.out
- tsl/test/shared/expected/merge_dml.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/merge_dml.sql
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/dist_ref_table_join.sql.in
- tsl/test/sql/merge_compress.sql
This patch does following:
1. Planner changes to create ChunkDispatch node when MERGE command
has INSERT action.
2. Changes to map partition attributes from a tuple returned from
child node of ChunkDispatch against physical targetlist, so that
ChunkDispatch node can read the correct value from partition column.
3. Fixed issues with MERGE on compressed hypertable.
4. Added more testcases.
5. MERGE in distributed hypertables is not supported.
6. Since there is no Custom Scan (HypertableModify) node for MERGE
with UPDATE/DELETE on compressed hypertables, we don't support this.
Fixes #5139
> MERGE support on hypertables

- .unreleased/feature_5599
- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/planner.c
- src/planner/planner.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/compression_insert-15.out
- tsl/test/sql/compression_ddl.sql
- tsl/test/sql/compression_insert.sql.in
This patch enables ChunkAppend optimization for partially
compressed chunks on hypertables without space partitioning,
allowing for more efficient processing of LIMIT order by
queries.
A follow-up patch is required to handle space partitioned
hypertables.
Disable-Check: force-changelog-changed
> Enable ChunkAppend for partial chunks

- sql/size_utils.sql
- tsl/test/expected/dist_util.out
- tsl/test/sql/dist_util.sql
This is with reference to a weird scenarios where chunk table entry exist in timescaledb catalog but it does not exist in PG catalog. The stale entry blocks executing hypertable_size function on the hypertable.
The changes in this patch are related to improvements suggested for hypertable_size function which involves:
1. Locking the hypertable in ACCESS SHARE mode in function hypertable_size to avoid risk of chunks being dropped by another concurrent process.
2. Joining the hypertable and inherited chunk tables with "pg_class" to make sure that a stale table without an entry is pg_catalog is not included as part of hypertable size calculation.
NOTE: With this change calling hypertable_size function will require select privilege on the table.
Closes #995
> Internal Server Error when loading Explorer tab

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_insert-12.out
- tsl/test/expected/compression_insert-13.out
- tsl/test/expected/compression_insert-14.out
- tsl/test/expected/compression_insert-15.out
- tsl/test/expected/compression_sorted_merge-12.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/sql/compression_insert.sql.in
- tsl/test/sql/compression_sorted_merge.sql.in
This patch enables the compressed merge optimization also for partially compressed chunks.
> Enable compressed merge append for partial chunks

- .github/workflows/changelog-check.yaml
- CHANGELOG.md
- scripts/check_changelog_format.py
Adds a simple check to ensure that the PR number is present at least once in the added changelog file.
Also fixes an earlier PR which introduced a typo.
> Ensure PR number is referenced in .unreleased files

- .unreleased/bugfix_5750
- src/import/planner.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/compression_sorted_merge-12.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/sql/compression_sorted_merge.sql.in
In PostgreSQL < 15, CustomScan nodes are projection capable per default. The planner invokes create_plan_recurse with the flag `CP_IGNORE_TLIST`. So, the target list of a CustomScan node can be NIL. However, we rely on the target list to derive information for sorting.
This patch ensures that the target list is always populated before the sort functions are called.
Fixes: #5738
> Ensure tlist is present in decompress chunk plan

- .unreleased/bugfix_5754
- src/agg_bookend.c
- test/expected/agg_bookends-12.out
- test/expected/agg_bookends-13.out
- test/expected/agg_bookends-14.out
- test/expected/agg_bookends-15.out
- test/sql/include/agg_bookends_query.sql
In the function `bookend_sfunc` values are compared. If the first processed value is a `NULL` value, it was copied into the state of the sfunc. A following comparison between the NULL value of the state and a non-NULL value could lead to a crash.
This patch improves the handling of NULL values in bookend_sfunc.
> Fixed handling of NULL values in bookend_sfunc

- scripts/test_update_smoke.sh
- test/sql/updates/cleanup.multinode.sql
The test was failing on first run by leaving a database behind as a sideeffect.
Between two steps the extension was dropped; without a proper cleanup. A non-existent sql function was called during cleanup.
This patch also removes the "debug mode" and every execution will leave the logs/etc in the /tmp directory for further inspection.
> Fix issues with scripts/test_update_smoke.sh

- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
We have changed the compression test by disabling parallel append
in some test cases because the regression test was falling only 
in PG14.0 but not in PG14.8 or any other PostgreSQL version
Below is a link of the failed regression test for PG14.0
https://github.com/timescale/timescaledb/actions/runs/5183083367/jobs/9397412094#step:14:930
> Compression test changes for PG14

- .github/workflows/procedural.yaml
- .github/workflows/stalebot.yaml
We plan to rename the need-more-info label to waiting-for-author.
This PR performs the needed adjustments in our GitHub actions.
> Renamed need-more-info label

- .unreleased/bugfix_5774
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
- tsl/test/expected/compression_sorted_merge-12.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/sql/compression_sorted_merge.sql.in
SQLSmith found two bugs in the compression sorted merge code.
* The unused_batch_states are not initialized properly. Therefore, non-existing unused batch states can be part of the BMS. This patch fixes the initialization.
* For performance reasons, We reuse the same TupleDesc across all TupleTableSlots. PostgreSQL sometimes uses TupleDesc data structures with active reference counting. The way we use the TupleDesc structures collides with the reference counting of PostgreSQL. This patch introduces a private TupleDesc copy without reference counting.
Link to failed SQLSmith run: https://github.com/timescale/timescaledb/actions/runs/5233117820/jobs/9448359165
> Fixed two bugs in decompression sorted merge code

- README.md
The download links for several platforms are broken. This patch removes the links for the individual platforms and adds a link that points to the self-hosted install docs instead (as proposed by the docs team, see the discussion in #5762).
Fixes: #5762
---
> Fix broken download links

- .unreleased/PR_5586
- tsl/src/compression/compression.c
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
During UPDATE/DELETE on compressed hypertables, we do a sequential scan which can be improved by supporting index scans.
In this patch for a given UPDATE/DELETE query, if there are any WHERE conditions specified using SEGMENT BY columns, we use index scan to fetch all matching rows. Fetched rows will be decompressed and moved to uncompressed chunk and a regular UPDATE/DELETE is performed on the uncompressed chunk.
> Index scan support during UPDATE/DELETE on compressed hypertables.

- src/nodes/chunk_append/chunk_append.c
- src/planner/planner.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
This is a follow-up patch for https://github.com/timescale/timescaledb/pull/5599 which handles space
partitioned hypertables.
> Enable ChunkAppend for space partitioned partial chunks

- src/cache.c
- src/copy.c
- src/process_utility.c
- tsl/src/compression/compression.c
This PR consists of the following 3 commits :
[PG16: Remove MemoryContextContains usage](https://github.com/timescale/timescaledb/commit/c1b2fbd715e1564246d9bd908e8470a2c4128353) 
Remove the usage of MemoryContextContains as it has been removed in PG16.
https://github.com/postgres/postgres/commit/9543eff
---
[PG16: Rename RelFileNode references to RelFileNumber or RelFileLocator](https://github.com/timescale/timescaledb/commit/2a1f3cb6524ca535f520b740806df5fb7905717c) 
https://github.com/postgres/postgres/commit/b0a55e4
---
[PG16: Use new function to check vacuum permission](https://github.com/timescale/timescaledb/commit/100ebb6848bb8eadf2bef7b75117a74bad628201) 
https://github.com/postgres/postgres/commit/b5d63824
> PG16 : Function renames

- src/chunk.c
- src/chunk.h
- src/nodes/chunk_dispatch/chunk_insert_state.c
- tsl/src/compression/api.c
* passing a `Chunk` is more straightforward/cleaner
* easier to extend the checks later (if needed)
> Make validate_chunk_status_for_operation accept Chunk as argument

- .unreleased/bugfix_chunk_create
- src/chunk.c
- tsl/test/expected/chunk_api.out
- tsl/test/sql/chunk_api.sql
Earlier this function have completed successfully if the requested range already existed - regardless an existing table was supplied or not.
> Chunk_create must add existing table or fail

- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
The flakiness was due to two inserts falling into the
same chunk instead of distinct ones, so inserted data
further apart to ensure they fall in different chunks.
> Fix flaky test bgw_db_scheduler_fixed

- .unreleased/bugfix_5804
- sql/util_time.sql
- src/ts_catalog/continuous_aggs_watermark.c
- tsl/test/expected/continuous_aggs-12.out
- tsl/test/expected/continuous_aggs-13.out
- tsl/test/expected/continuous_aggs-14.out
- tsl/test/expected/continuous_aggs-15.out
- tsl/test/t/008_mvcc_cagg.pl
- tsl/test/t/CMakeLists.txt
This patch marks the function cagg_watermark as `PARALLEL RESTRICTED`. It partially reverts the change of c0f2ed18095f21ac737f96fe93e4035dbfeeaf2c. The reason is as follows: for transaction isolation levels < `REPEATABLE READ` it can not be ensured that parallel worker reads the same watermark (e.g., using read committed isolation level: worker A reads the watermark, the CAGG is refreshed and the watermark changes, worker B reads the newer watermark). The different views on the CAGG can cause unexpected results and crashes (e.g., the chunk exclusion excludes different chunks in worker A and in worker B).
In addition, a correct snapshot is used when the watermark is read from the CAGG and a TAP test is added, which detects inconsistent watermark reads.
> Mark cagg_watermark function as PARALLEL RESTRICTED

- .unreleased/feature_5137
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/expected/compression.out
- tsl/test/expected/compression_errors.out
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/compression_sorted_merge-12.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/expected/transparent_decompression-12.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/expected/transparent_decompression_join_index.out
- tsl/test/expected/transparent_decompression_ordered_index-12.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/isolation/expected/compression_merge_race.out
- tsl/test/isolation/specs/compression_merge_race.spec.in
- tsl/test/shared/sql/include/shared_setup.sql
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_errors.sql
- tsl/test/sql/compression_qualpushdown.sql
- tsl/test/sql/compression_sorted_merge.sql.in
- tsl/test/sql/include/transparent_decompression_ordered.sql
- tsl/test/sql/transparent_decompression_join_index.sql
- tsl/test/sql/transparent_decompression_ordered_index.sql.in
If there is an index on the compressed chunk, insert into it while inserting the heap data rather than reindexing the relation at the end. This reduces the amount of locking on the compressed chunk index which created issues when merging chunks and should help with the future updates of compressed data.
> Insert into index during chunk compression

- CMakeLists.txt
- scripts/perltidy_format_all.sh
- test/perl/TimescaleNode.pm
This patch introduces the make target 'perltidy' to format Perl files with perltidy. In addition, calling perltidy is added to 'make format'.
> Added perltidy make target

- .unreleased/bugfix_5807
- src/bgw/job.c
- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
The job config jsonb can be a nested structure of elements that all need to reside in the same memory context as the other job values. To ensure this we copy the structure on assignment.
> Copy job config JSONB structure into current MemoryContext

- .unreleased/feature_5515
- src/chunk.c
- src/chunk_index.c
- src/chunk_index.h
- src/hypertable.c
- src/process_utility.c
- test/expected/alter.out
- test/expected/ddl_errors.out
- test/sql/alter.sql
- test/sql/ddl_errors.sql
- tsl/src/remote/dist_ddl.c
- tsl/test/expected/dist_ddl.out
- tsl/test/sql/dist_ddl.sql
Add support for setting replica identity on hypertables via ALTER
TABLE. The replica identity is used in logical replication to identify
rows that have changed.
Currently, replica identity can only be altered on hypertables via the
root; changing it directly on chunks will raise an error.
> Make hypertables support replica identity

- .unreleased/bugfix_5824
- src/planner/expand_hypertable.c
- test/expected/plan_expand_hypertable-12.out
- test/expected/plan_expand_hypertable-13.out
- test/expected/plan_expand_hypertable-14.out
- test/expected/plan_expand_hypertable-15.out
This patch changes the time_bucket exclusion in cagg queries to distinguish between < and <=. Previously those were treated the same leading to failure to exclude chunks when the constraints where exactly at the bucket boundary.
> Improve cagg query chunk exclusion

- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.11.0 release. We recommend that you upgrade at the next available opportunity.
**Features**
* #5679 Teach loader to load OSM extension
**Bugfixes**
* #5705 Scheduler accidentally getting killed when calling `delete_job`
* #5742 Fix Result node handling with ConstraintAwareAppend on compressed chunks
* #5750 Ensure tlist is present in decompress chunk plan
* #5754 Fixed handling of NULL values in bookend_sfunc
* #5798 Fixed batch look ahead in compressed sorted merge
* #5804 Mark cagg_watermark function as PARALLEL RESTRICTED
* #5807 Copy job config JSONB structure into current MemoryContext
* #5824 Improve continuous aggregate query chunk exclusion
**Thanks**
* @JamieD9 for reporting an issue with a wrong result ordering
* @xvaara for reporting …
> Release 2.11.1

- scripts/merge_changelogs.sh
The [CHANGELOG.md](https://github.com/timescale/timescaledb/blob/main/CHANGELOG.md) file contains the sections features, bugfixes, and thanks. This patch adjusts the script merge_changelogs.sh to produce the sections in the same order.
> Fixed output ordering of merge_changelogs.sh script

- src/utils.h
The `ts_set_flags_32` function takes a bitmap and flags and returns an updated bitmap. However, if the returned value is not used, the function call has no effect. An unused result may indicate the improper use of this function.
This patch adds the qualifier `pg_nodiscard` to the function which triggers a warning if the returned value is not used.
> Warn if result of ts_set_flags_32 is not used

- .github/workflows/libfuzzer.yaml
- src/adts/bit_array_impl.h
- tsl/src/compression/arrow_c_data_interface.h
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/decompress_test_impl.c
- tsl/src/compression/deltadelta.c
- tsl/src/compression/deltadelta.h
- tsl/src/compression/deltadelta_impl.c
- tsl/src/compression/gorilla.c
- tsl/src/compression/gorilla.h
- tsl/src/compression/gorilla_impl.c
- tsl/src/compression/simple8b_rle_bitmap.h
- tsl/src/compression/simple8b_rle_decompress_all.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
- tsl/test/expected/compression_algos.out
- tsl/test/shared/expected/transparent_decompress_chunk-12.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
- tsl/test/src/test_compression.c
Do some cleanup and support decompression in the reverse direction.
In tsbench it improves the first/last queries, by using the old sizes for the per-batch memory context: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=2477&var-run2=2478&var-threshold=0.05
> Small improvements of bulk decompression

- .unreleased/PR_5868
- src/process_utility.c
This commit is a follow up of #5515, which added support for ALTER TABLE ... REPLICA IDENTITY (FULL | INDEX) on hypertables.
This commit allows the execution against materialized hypertables to enable update / delete operations on continuous aggregates when logical replication in enabled for them.
> Allow Replica Identity (Alter Table) on CAGGs

- .unreleased/PR_5852
- src/chunk.c
- src/dimension.c
- src/hypertable.c
- src/hypertable.h
- tsl/test/expected/cagg_ddl.out
- tsl/test/expected/cagg_ddl_dist_ht.out
- tsl/test/sql/include/cagg_ddl_common.sql
This patch adds support to pass continuous aggregate names to the `set_chunk_time_interval` function to align it with functions, such as `show_chunks`, `drop_chunks`, and others.
It reuses the previously existing function to find a hypertable or resolve a continuous aggregate to its underlying hypertable found in chunk.c. It, however, moves the function to hypertable.c and exports it from here. There is some discussion if this functionality should stay in chunk.c, though, it feels wrong in that file now that it is exported.
> Make `set_chunk_time_interval` CAGGs aware

- .unreleased/PR_5839
- sql/size_utils.sql
- tsl/test/expected/size_utils_tsl.out
- tsl/test/sql/size_utils_tsl.sql
This patch adds support to pass continuous aggregate names to `chunk_detailed_size` to align it to the behavior of other functions such as `show_chunks`, `drop_chunks`, `hypertable_size`.
> Support CAGG names in chunk_detailed_size

- .unreleased/bugfix_5734
- test/sql/updates/post.repair.hierarchical_cagg.sql
- test/sql/updates/post.repair.sql
- test/sql/updates/setup.repair.hierarchical_cagg.sql
- test/sql/updates/setup.repair.sql
- tsl/src/continuous_aggs/common.c
- tsl/test/expected/cagg_on_cagg.out
- tsl/test/expected/cagg_on_cagg_dist_ht.out
- tsl/test/expected/cagg_on_cagg_joins.out
- tsl/test/expected/cagg_on_cagg_joins_dist_ht.out
- tsl/test/sql/cagg_on_cagg.sql
- tsl/test/sql/cagg_on_cagg_dist_ht.sql
- tsl/test/sql/cagg_on_cagg_joins.sql
- tsl/test/sql/cagg_on_cagg_joins_dist_ht.sql
- tsl/test/sql/include/cagg_on_cagg_setup.sql
- tsl/test/sql/include/cagg_on_cagg_validations.sql
For Hierarchical continuous aggregates with variable bucket size, the interval was wrongly manipulated in the process. It was introduced by commit 5b60343ac4 .
Now it is corrected by creating a copy of interval structure for validation purposes and keeping the original structure untouched.
Fixes #5734
> Rectify interval calculation

- .unreleased/bugfix_5872
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
When the uncompressed part of a partially compressed chunk is read by a non-partial path and the compressed part by a partial path, the append node on top could process the uncompressed part multiple times because the path was declared as a partial path (correct is non-partial path) and the append node assumed it could be executed in all workers in parallel without producing duplicates.
This PR ensures that the append node is aware of the correct path type.
> Fix duplicates on partially compressed chunk reads

- .unreleased/feature_5875
- src/bgw/job.c
- tsl/src/continuous_aggs/materialize.c
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/cagg_bgw.out
- tsl/test/expected/cagg_bgw_dist_ht.out
- tsl/test/expected/cagg_refresh.out
- tsl/test/sql/bgw_db_scheduler.sql
- tsl/test/sql/bgw_db_scheduler_fixed.sql
- tsl/test/sql/bgw_reorder_drop_chunks.sql
- tsl/test/sql/include/cagg_bgw_common.sql
When a job finishes execution, either because of an error or a success,
this commit will print out the execution time of the job in the log
together with a message about what job that finished.
For continuous aggregate refreshes, the number of rows deleted from and
inserted into the materialization table will be printed.
Fixes #5876
> Add job exit status and runtime to log

- .github/gh_matrix_builder.py
The commit cdea343cc updated the gh_matrix_builder.py script but failed to import PG_LATEST variable into the script thus breaking the CI. Import that variable to fix the CI tests.
> Fix broken CI after PG12 removal

- .unreleased/bugfix_5892
- tsl/src/compression/create.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
When enabling compression on a table, there is a check of unique constraints and primary key constraints, but no check if there is just a unique index. This means that it is possible to create a compressed table without getting a warning that you should include the columns in the index into the segmentby field, which can lead to suboptimal query times.
This commit adds a check for the unique index as well and ensure that a similar warning is printed as for a unique constraint.
Fixes #5892
> Check unique indexes when enabling compression

- .unreleased/bugfix_5918
- src/copy.c
- test/expected/copy.out
- test/sql/copy.sql
Reset the errcallback appropriately so that the ereport in case of a PROGRAM returning error can work correctly.
> Fix crash in COPY from program returning error

- .unreleased/bugfix_5907
- tsl/src/bgw_policy/policies_v2.c
- tsl/test/expected/cagg_policy.out
- tsl/test/sql/cagg_policy.sql
Previously when a retention policy existed on the underlying hypertable,
we would get a segmentation fault when trying to add a Cagg refresh
policy, due to passing a bool instead of pointer to bool argument to
function `ts_jsonb_get_int64_field` in a particular code path.
Fixed by passing the expected pointer type.
Fixes #5907
> Fix crash in 1-step integer policy creation

- src/process_utility.c
- tsl/src/process_utility.c
- tsl/src/remote/dist_ddl.c
PG16 removed the recursion-marker values used to handle certain subcommands during an ALTER TABLE execution and provides an alternative flag. Removed the references to the recursion-marker values from timescaledb code.
postgres/postgres@840ff5f4
> PG16: Remove recursion-marker values in enum AlterTableType

- .unreleased/bugfix_5909
- src/process_utility.c
- test/expected/index.out
- test/sql/index.sql
This PR adds support for CREATE INDEX ONLY ON clause which allows to create index only on the main table excluding chunks.
Fix #5908
> Support CREATE INDEX ONLY ON main table

- .unreleased/PR_5906
- sql/updates/2.10.1--2.10.2.sql
- sql/updates/2.11.0--2.10.3.sql
When referring to a role from a string type, it must be properly quoted using `pg_catalog.quote_ident` before it can be casted to `regrole`. Fixed this, especially in update scripts.
See also #5900
> Fix quoting owners in sql scripts.

- .unreleased/PR_5923
- src/guc.c
- src/guc.h
- src/hypertable.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/policies_v2.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/compression/api.c
- tsl/src/compression/create.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/feature_flags.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/feature_flags.sql
This PR adds several GUCs which allow to enable/disable major timescaledb features:
- enable_hypertable_create
- enable_hypertable_compression
- enable_cagg_create
- enable_policy_create
Original issue: https://github.com/timescale/eng-database/issues/512
Based on @mkindahl original implementation
> Feature flags for TimescaleDB features

- .unreleased/PR_5923
- src/guc.c
- src/guc.h
- src/hypertable.c
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/policies_v2.c
- tsl/src/bgw_policy/reorder_api.c
- tsl/src/bgw_policy/retention_api.c
- tsl/src/compression/api.c
- tsl/src/compression/create.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/feature_flags.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/feature_flags.sql
This PR adds several GUCs which allow to enable/disable major timescaledb features:
- enable_hypertable_create
- enable_hypertable_compression
- enable_cagg_create
- enable_policy_create
cherry-picked from https://github.com/timescale/timescaledb/commit/7aeed663b9c0f337b530fd6cad47704a51a9b2ec
> Backport to 2.11.x: #5923 Feature flags for TimescaleDB features

- src/compat/compat.h
- src/copy.c
- src/import/ht_hypertable_modify.c
- src/nodes/hypertable_modify.c
- tsl/src/compression/compression.c
PG16 adds a new boolean parameter to the ExecInsertIndexTuples function to denote if the index is a BRIN index, which is then used to determine if the index update can be skipped. The fix also removes the INDEX_ATTR_BITMAP_ALL enum value.
Adapt these changes by updating the compat function to accomodate the new parameter added to the ExecInsertIndexTuples function and using an alternative for the removed INDEX_ATTR_BITMAP_ALL enum value.
postgres/postgres@19d8e23
> PG16: ExecInsertIndexTuples requires additional parameter

- src/compat/compat.h
- src/copy.c
- src/import/ht_hypertable_modify.c
- src/indexing.c
- src/nodes/hypertable_modify.c
- tsl/src/compression/compression.c
- tsl/src/compression/create.c
- tsl/src/continuous_aggs/create.c
[PG16: Handle DefineIndex's new parameter](https://github.com/lkshminarayanan/timescaledb/commit/26d4dc85a7f90d9be60672a92530fd6e9f99da9a) 
PG16 adds a new parameter to DefineIndex, total_parts, that takes in the
total number of direct and indirect partitions of the relation. Updated
all the callers to pass either the actual number if it is known or -1 if
it is unknown at that point.
https://github.com/postgres/postgres/commit/27f5c712
---
[PG16: ExecInsertIndexTuples requires additional parameter](https://github.com/lkshminarayanan/timescaledb/commit/7d673230d27c5239500e387a7ca51ddd8df0e984) 
PG16 adds a new boolean parameter to the ExecInsertIndexTuples function
to denote if the index is a BRIN index, which is then used to determine
if the index update can be skipped. The fix also …
> PG16 : New parameters added to DefineIndex and ExecInsertIndexTuples

- src/import/planner.c
- src/ts_catalog/catalog.c
- tsl/src/fdw/option.c
[PG16: stringToQualifiedNameList requires escontext parameter](https://github.com/timescale/timescaledb/commit/599b4ea31186f1d7110fb9e9bcc24334be50f46f) 
https://github.com/postgres/postgres/commit/858e776c84f
---
[PG16: No need to pass create_new_ph flag to find_placeholder_info](https://github.com/timescale/timescaledb/commit/8fee6164824ed57ebeafc06c418db963d0b376b9) 
https://github.com/postgres/postgres/commit/b3ff6c742
> PG16 : update couple of redefined functions

- src/compat/compat.h
- src/hypertable.c
- src/partitioning.c
- src/ts_catalog/hypertable_data_node.c
- src/ts_catalog/tablespace.c
- tsl/src/bgw_policy/job_api.c
- tsl/src/continuous_aggs/refresh.c
- tsl/src/data_node.c
- tsl/src/reorder.c
[PG16: Make aclcheck function calls compatible with PG16](https://github.com/timescale/timescaledb/commit/679719a1369cc22c293c2f63ce0f688fbcd95de1) 
PG16 replaced most of the aclcheck functions with a common object_aclcheck
function. Updated the various aclcheck calls in the code to use the new
function when compiled with PG16.
https://github.com/postgres/postgres/commit/c727f511
---
[PG16: Replace pg_class_ownercheck() with object_ownercheck](https://github.com/timescale/timescaledb/commit/32918ce76b55b44080f809ba4cccf4a67b628fe0) 
PG16 replaces pg_foo_ownercheck() functions with a common
object_ownercheck() function. Added a new compat function for
pg_class_ownercheck() function affected by this change and replaced all
its callers.
https://github.com/postgres/postgres/commit/afbfc029 …
> PG16 : Updates to aclcheck and ownercheck functions

- .unreleased/PR_5805
- src/guc.c
- src/guc.h
- tsl/src/compression/compression.c
- tsl/test/t/009_logrepl_decomp_marker.pl
- tsl/test/t/CMakeLists.txt
Added logical replication messages (PG14+) as markers for (partial) decompression events (mutual compression), which makes it possible to differentiate inserts happening as part of the decompression vs actual inserts by the user, and filter the former out of the event stream. While some tools may be interested in all events, synching the pure "state" (without internal behavior) is required for others.
As of now this PR is missing tests. I wonder if anyone has a good idea how to create an automatic test for it.
> Make logrepl markers for (partial) decompressions

- src/process_utility.c
This reverts commit 8b0ab4164 as the commit that introduced the new function has been reverted upstream.
postgres/postgres@95744599
> Revert "PG16: Use new function to check vacuum permission"

- .unreleased/PR_5906
- .unreleased/PR_5923
- .unreleased/bugfix_5774
- .unreleased/bugfix_5786
- .unreleased/bugfix_5907
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.11.1 release.
**Features**
* https://github.com/timescale/timescaledb/pull/5909 CREATE INDEX ONLY ON hypertable creates index on chunks
* https://github.com/timescale/timescaledb/pull/5923 Feature flags for TimescaleDB features
**Bugfixes**
* https://github.com/timescale/timescaledb/pull/5680 Fix DISTINCT query with JOIN on multiple segmentby columns
* https://github.com/timescale/timescaledb/pull/5774 Fixed two bugs in decompression sorted merge code
* https://github.com/timescale/timescaledb/pull/5786 Ensure pg_config --cppflags are passed
* https://github.com/timescale/timescaledb/pull/5906 Fix quoting owners in sql scripts.
* https://github.com/timescale/timescaledb/pull/5912 …
> Release 2.11.2

- src/import/allpaths.c
- src/import/allpaths.h
- test/sql/updates/post.compression.sql
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
This PR improves the way the number of parallel workers for the DecompressChunk node are calculated. Since
1a93c2d482b50a43c105427ad99e6ecb58fcac7f, no partial paths for small chunks are generated, which could cause a fallback to a sequential plan and a performance regression. This patch ensures that a partial path is created again to get the 2.11.x behavior back.
---
---
Tsbench against the last commit before this PR: https://grafana.ops.savannah-dev.timescale.com/d/NdmLnOk4z/compare-benchmark-runs?orgId=1&var-branch=All&var-run1=2549&var-run2=2551&var-threshold=0.02
Tsbench against 2.11.1 (a version without the commit 1a93c2d482b50a43c105427ad99e6ecb58fcac7f): https://grafana.ops.savannah-dev.timescale.com/d/NdmLnOk4z/compare-benchmark-runs?orgId=1&var …
> Improved parallel DecompressChunk worker selection

- test/expected/telemetry.out
- test/sql/telemetry.sql
Due to the postman-echo endpoint redirecting http requests to https, we get an unexpected 301 response in the tests, leading to repeated test failures. This commit removes these function calls.
> Remove test_status calls from telemetry test

- src/nodes/chunk_append/exec.c
- test/expected/parallel-13.out
- test/expected/parallel-14.out
- test/expected/parallel-15.out
- test/sql/parallel.sql.in
The parallel version of the ChunkAppend node uses shared memory to coordinate the plan selection for the parallel workers. If the workers perform the startup exclusion individually, it may choose different subplans for each worker (e.g., due to a "constant" function that claims to be constant but returns different results). In that case, we have a disagreement about the plans between the workers. This would lead to hard-to-debug problems and out-of-bounds reads when pstate->next_plan is  used for subplan selection.
With this patch, startup exclusion is only performed in the parallel leader. The leader stores this information in shared memory. The parallel workers read the information from shared memory and don't perform startup exclusion.
> Perform startup chunk exclusion in parallel leader

- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
- tsl/src/fdw/data_node_chunk_assignment.c
- tsl/src/fdw/relinfo.c
- tsl/src/planner.c
Full catalog lookups for a Chunk are expensive, avoiding them speeds up the planning.
> Use cached Chunk struct when considering compressed paths

- src/planner/planner.h
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/expected/transparent_decompression_join_index.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
When looking up a pathkey for compressed scan, we used to do a lot of work, including a quadratic lookup through all the equivalence members, to always arrive at the same canonical pathkey we started from. Just remove this useless code for a significant planning speedup.
This uncovers two bugs, fix them as well (see comments below).
> Simplify compressed pathkey lookup

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/expected/transparent_decompression_join_index.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
We just had a bad cast inside `is_redundant_derived_clause` before, because it doesn't work with `IndexClause`s. Filtering didn't work as a result.
> Fix filtering of the redundant decompress chunk clauses over a compressed index path

- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/utils.c
- tsl/src/compression/compression.c
- tsl/src/debug.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
[PG16: Rename ri_RootToPartitionMap to ri_RootToChildMap](https://github.com/timescale/timescaledb/commit/77992ba99e0d877e2935fb93afc1a11e79578268)
https://github.com/postgres/postgres/commit/fb958b5d
---
[PG16: Node tags T_Join, T_Plan and T_Scan have been removed](https://github.com/timescale/timescaledb/commit/d93a4dbfcde19178bfa156771339c49262f0354d) 
Node tags T_Join, T_Plan and T_Scan have been removed in PG16 as those
nodes are of abstract type and never directly instantiated.
https://github.com/postgres/postgres/commit/251154be
https://github.com/postgres/postgres/commit/8c73c11a
---
[PG16: When removing a relation from the query, drop its RelOptInfo.](https://github.com/timescale/timescaledb/commit/6939e6faa2acb88dcff49c11b40add8eb969c962) 
PG16 removes the notion of "dead …
> PG16 - Few more simple fixes

- src/guc.c
- tsl/src/bgw_policy/policies_v2.c
- tsl/src/remote/dist_txn.c
- tsl/src/remote/txn.c
[PG16: Replace float8in_internal_opt_error with float8in_internal](https://github.com/timescale/timescaledb/commit/f770db913b238671e49471a929d3286b5c5a2b6d) 
PG16 updated float8in_internal_opt_error() function to use soft error
reporting and renamed it to float8in_internal(). Updated the code to use
the new mechanism.
https://github.com/postgres/postgres/commit/ccff2d20e
---
[PG16: Include guc header to use GetConfigOptionByName](https://github.com/timescale/timescaledb/commit/af11870c762093253f7d30450c7b470f0796ecfa) 
https://github.com/postgres/postgres/commit/0a20ff54f5
---
[PG16: Align GUC variables initial value with boot values](https://github.com/timescale/timescaledb/commit/1a9098e5926f3cb6e52cd1fc148d5ed8fca9fbed) 
Any value hardcoded to a GUC variable will be overwritten by the …
> Pg16 few more fixes

- .unreleased/bugfix_5990
- src/agg_bookend.c
- test/expected/agg_bookends.out
- test/sql/agg_bookends.sql
So far, the `ts_bookend_deserializefunc()` function has allocated the deserialized data in the current memory context. This data could be removed before the aggregation is finished. This patch moves the data into the aggregation memory context.
> Place data in first/last function in correct mctx

- .unreleased/bugfix_5991
- tsl/src/nodes/gapfill/gapfill_exec.c
- tsl/test/shared/expected/gapfill.out
- tsl/test/shared/sql/gapfill.sql
The equality comparison function is called using
`DirectFunctionCall2Coll`, which do not set the `fcinfo->flinfo` when calling the function.  Since `array_eq` uses `fcinfo->flinfo->fn_extra` for caching, and `flinfo` is null, this causes a crash.
Fix this issue by using `FunctionCall2Coll` instead, which sets `fcinfo->flinfo` before calling the function.
Fixes #5981
> Call eq_func correctly in time_bucket_gapfill

- .github/workflows/pgspot.yaml
pgspot 0.6.0 has a bugfix for function signature tracking to no longer consider default values as part of the function signature.
> Bump pgspot version to 0.6.0

- .github/workflows/procedural.yaml
An `issue_comment` event is triggered by comments on both issues and PRs. However, the bugs project workflow did not filter out pull requests when the `issue_comment` event happened, so pull requests were also added to the bugs project board.
Add a conditional that filters out pull requests so that only issues are added to the board.
> Exclude PRs from bugs project board

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression.out
- tsl/test/expected/compression_insert.out
- tsl/test/expected/merge_append_partially_compressed-13.out
- tsl/test/expected/merge_append_partially_compressed-14.out
- tsl/test/expected/merge_append_partially_compressed-15.out
- tsl/test/sql/.gitignore
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_insert.sql
- tsl/test/sql/merge_append_partially_compressed.sql.in
In the exclusive presence of partially compressed chunks, this
optimization was not applied because no pathkeys were supplied.
Additionally, this patch makes sure that if applicable, the
`enable_decompression_sorted_merge` optimization is chosen for
the path, since it is more beneficial due to the ability to
push down the sort below DecompressChunk.
> Fix ordered append for partially compressed chunks

- src/chunk.c
- src/chunk.h
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
- tsl/src/fdw/modify_exec.c
- tsl/src/fdw/modify_plan.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
It's not needed. Also add them to baserel cache.
> Don't look up entire Chunk struct for compressed chunks

- sql/partitioning.sql
- sql/updates/latest-dev.sql
- src/hypertable.c
- tsl/test/shared/expected/extension.out
This function was used in an old version of a cagg informational view that was removed but the function itself was left in.
> Remove _timescaledb_internal.get_time_type

- .unreleased/feature_5809
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/src/continuous_aggs/invalidation_threshold.h
- tsl/src/continuous_aggs/refresh.c
- tsl/test/expected/cagg_invalidation.out
- tsl/test/expected/cagg_invalidation_dist_ht-13.out
- tsl/test/expected/cagg_invalidation_dist_ht-14.out
- tsl/test/expected/cagg_invalidation_dist_ht-15.out
- tsl/test/expected/cagg_watermark.out
- tsl/test/expected/exp_cagg_monthly.out
- tsl/test/expected/exp_cagg_timezone.out
- tsl/test/isolation/expected/cagg_concurrent_refresh.out
- tsl/test/isolation/expected/cagg_concurrent_refresh_dist_ht.out
- tsl/test/isolation/expected/cagg_insert.out
- tsl/test/isolation/specs/cagg_concurrent_refresh.spec
- tsl/test/isolation/specs/cagg_insert.spec
- tsl/test/sql/cagg_watermark.sql
- tsl/test/sql/exp_cagg_monthly.sql
- tsl/test/sql/exp_cagg_timezone.sql
- tsl/test/sql/include/cagg_invalidation_common.sql
When refreshing a Continuous Aggregate we take a table lock on
_timescaledb_catalog.continuous_aggs_invalidation_threshold when
processing the invalidation logs (the first transaction of the refresh
Continuous Aggregate procedure). It means that even two different
Continuous Aggregates over two different hypertables will wait each
other in the first phase of the refreshing procedure. Also it lead to
problems when a pg_dump is running because it take an AccessShareLock on
tables so Continuous Aggregate refresh execution will wait until the
pg_dump finish.
Improved it by relaxing the strong table-level lock to a row-level lock
so now the Continuous Aggregate refresh procedure can be executed in
multiple sessions with less locks.
Fix #3554
> Relax strong table lock when refreshing a Continuous Aggregate

- src/compression_with_clause.c
- src/process_utility.c
- src/ts_catalog/continuous_agg.c
- test/src/telemetry/test_telemetry.c
- test/src/test_with_clause_parser.c
- tsl/test/src/test_compression.c
PG16 converted the *GetDatum() and DatumGet*() macros to inline functions. This doesn't affect most of our code but a few places like struct object initialisations cannot use inline functions. This commit updates all the places affected by this change.
postgres/postgres@c8b2ef05
> PG16: Datum macros are now inline functions

- .unreleased/bugfix_5951
- src/chunk.c
- src/hypertable.c
- src/utils.c
- src/utils.h
- tsl/src/compression/api.c
- tsl/test/expected/compression_create_compressed_table.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_create_compressed_table.sql
`_timescaledb_internal.create_compressed_chunk` can be used to create a compressed chunk with existing compressed data. It did not account for the fact that the chunk can contain uncompressed data, in which case the chunk status must be set to partial.
Fixes #5946
> Account for uncompressed rows in 'create_compressed_chunk'

- test/sql/updates/post.continuous_aggs.v3.sql
Two queries in post.continuous_aggs.v3.sql had no ORDER BY specification. Therefore, the query output was not deterministic. This patch adds the missing ORDER BY.
---
> Make up/downgrade test deterministic

- .github/workflows/sanitizer-build-and-test.yaml
- src/chunk_scan.c
- src/planner/planner.c
- src/planner/planner.h
- test/isolation/expected/concurrent_query_and_drop_chunks.out
- test/isolation/specs/concurrent_query_and_drop_chunks.spec
- tsl/src/planner.c
- tsl/test/isolation/expected/concurrent_decompress_update.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/concurrent_decompress_update.spec
The compression status can change, and this is prevented by locking, so to keep our data consistent, we should reread the chunk metadata after we have locked it. Currently we have some code in place that masks this inconsistency by rereading the metadata in another place. This code is removed.
> Reread the catalog data after locking the chunk

- .github/gh_matrix_builder.py
- .github/workflows/abi.yaml
- .github/workflows/sanitizer-build-and-test.yaml
- CMakeLists.txt
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/sql/CMakeLists.txt
Since multinode tests take a long time to run we dont want to run them in CI on individual PRs but only on nightly runs.
> Make multinode tests conditional

- src/hypertable.c
This PR fixes the invalid use of an SPI result after SPI_finish is called and the result is freed.
> Fix an invalid SPI result use after free

- src/gapfill.c
- src/gapfill.h
- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/chunk_append.h
- src/planner/add_hashagg.c
- tsl/src/nodes/skip_scan/planner.c
This patch adds the 'ts_' prefix to the function names of is_decompress_chunk_path and is_gapfill_path and makes them available for use by other parts of TimescaleDB.
> Export is_decompress_chunk_path / is_gapfill_path

- src/compat/compat.h
- src/import/ht_hypertable_modify.c
- src/import/ht_hypertable_modify.h
- src/nodes/hypertable_modify.c
PG16 commit postgres/postgres@9321c79c fixes an issue with concurrent update issues in MERGE. This patch adapts that fix into the MERGE support for hypertables as well.
postgres/postgres@9321c79c
> PG16: Fix concurrent update issues with MERGE.

- .unreleased/bugfix_6015
- src/nodes/hypertable_modify.c
- test/expected/upsert.out
- test/sql/upsert.sql
INSERT ... ON CONFLICT statements record few metrics in the ModifyTable
node's instrument but they get overwritten by hypertable_modify_explain
causing wrong output in EXPLAIN ANALYZE statments. Fix it by saving the
metrics into HypertableModify node before replacing them.
Fixes https://github.com/timescale/timescaledb/issues/6014
> Fix incorrect row count in EXPLAIN ANALYZE INSERT .. ON CONFLICT output

- .github/workflows/linux-32bit-build-and-test.yaml
So far, we have used Debian Buster (10) for our 32-bit tests. This distribution is EOL in ~1 year and contains an old LLVM version (7.0). LLVM 7 contains a few bugs that break the JIT functionality of PostgreSQL ([missing mixed-sign 64-bit operands on 32-bit architectures](https://bugs.llvm.org/show_bug.cgi?id=34920) / `failed to resolve name __mulodi4`).
This patch changes the used Distribution for 32-bit tests to Debian Bookworm (12 / LLVM 14). Since the PostgreSQL download server no longer offers 32-bit Debian packages, PostgreSQL is built from source.
--
> Use Debian Bookworm for 32-bit tests

- .unreleased/bugfix_6024
- tsl/src/compression/compression.c
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
UPDATE query with system attributes in WHERE clause causes server to crash. This patch fixes this issue by checking for system attributes and handle cases only for segmentby attributes in fill_predicate_context().
Fixes #6024
> Fix server crash on UPDATE of compressed chunk

- .unreleased/bugfix_6037
- src/hypertable.c
- test/expected/create_hypertable.out
- test/sql/create_hypertable.sql
When an invalid function oid is passed to set_integer_now_func, it finds out that the function oid is invalid but before throwing the error, it calls ReleaseSysCache on an invalid tuple causing a segfault. Fixed that by removing the invalid call to ReleaseSysCache.
Fixes #6037
> Fix segfault in set_integer_now_func

- .github/workflows/linux-32bit-build-and-test.yaml
- .unreleased/bugfix_6044
- tsl/src/compression/create.c
- tsl/test/expected/compression_errors.out
- tsl/test/sql/compression_errors.sql
The segmentby column info array is populated by using the column attribute number as an array index. This is done as part of validating and creating segment by column info in function `compresscolinfo_init`.
Since the column is duplicated the attribute number for both the segmentby column is same. When this attribute number is used as an index, only one of the array element is populated correctly with the detailed column info whareas the other element of the array ramins NULL. This segmentby column info is updated in catalog as part of processing compression options (ALTER TABLE ...).
When the chunk is being compressed this segmentby column information is being retrieved from the catalog to create the scan key in order to identify any existing index on the table that matches the segmentby …
> Server crash when using duplicate segmentby column

- .unreleased/bugfix_6053
- sql/size_utils.sql
- tsl/test/expected/size_utils_tsl.out
- tsl/test/sql/size_utils_tsl.sql
The approximate_row_count function is executed directly on the user view instead of corresponding materialized hypertable which returns 0 for caggs. The function is updated to fetch the details for materialized hypertable information corresponding to cagg and then get the approximate_row_count for the materialized hypertable.
Fixes #6051
> Function approximate_row_count returns 0 for caggs

- sql/updates/latest-dev.sql
- src/chunk.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
The initial range for the OSM chunk will be from INT64_MAX - 1 to INT64_MAX. This range was chosen to minimize interference with tuple routing and occupy a range outside of potential values as there must be no overlap between the hypercube occupied by the osm chunk and actual chunks. Previously the range covered by the osm chunk would bucket the start of the range leading to a dependency on chunk_time_interval and limiting the range of usable values in the hypertable when an osm chunk is present.
> Fix range covered by osm chunk slices

- .github/workflows/procedural.yaml
In our bug board, issues were moved into the 'Waiting for Engineering' column when the author of an issue responded. The column move was made if the issue was tagged with the label 'waiting-for-author'. However, sometimes this label was not added to the waiting issues. As a result, the issue was not moved to the right column when the author responded.
This PR replaces the error-prone label check with a check in which column the issue is.
---
The workflow was tested in the timescaledb-tune repository with the issue https://github.com/timescale/timescaledb-tune/issues/126
> Improved bug board automatization

- src/planner/expand_hypertable.c
- test/expected/partitionwise.out
- test/sql/partitionwise.sql
So far, we have created fake partitioning info for hypertables if the PostgreSQL setting 'enable_partitionwise_aggregate' is set. This causes PostgreSQL to push down partial aggregations to the chunk level. However, the PostgreSQL code has some drawbacks because the query is replanned and optimizations like ChunkAppend are lost. Since #5596 we have implemented our own code to push down partial aggregations. Therefore, we can ignore the PostgreSQL setting from now on.
---
Should be merged after #5596 which fixes also the currently failing regression test _partitionwise_
> Don't build partition info for local hypertables

- src/planner/partialize.c
The Sanitizer build found a missing memory initialization of the aggregation costs. This PR adds the missing initialization.
---
Failing CI run: https://github.com/timescale/timescaledb/actions/runs/6192216103/job/16824687929
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6197194660/job/16825298034
> Fix missing cost initialization

- .pull-review
The pull-review bot requires that the chosen accounts be part of the organization. Updating the reviewer list to ensure the bot works.
---
> Updated reviewer list for pull-review bot

- .github/workflows/coverity.yaml
> Fix build failure in coverity workflow

- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
> Remove ubuntu kinetic from package test since it's EOL

- test/runner.sh
- test/runner_shared.sh
The compression_update_delete test (and further tests) sets the log level to DEBUG1. Especially on Windows, the additional log message 'DEBUG:  compacted fsync request queue from XXX entries to XXX entries' causes the test to be flaky. This patch removes this log message from the test output.
Fixes: #4723
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6215855526/job/16869164441
> Fix flaky compression_update_delete test

- .unreleased/PR_6081
- tsl/src/compression/compression.c
- tsl/test/shared/expected/compression_dml.out
- tsl/test/shared/sql/compression_dml.sql
Fall back to btree operator input type when it is binary compatible with the column type and no operator for column type could be found. This should improve performance when using column types like char or varchar instead of text.
Fixes: #6076
> Improve compression datatype handling

- test/sql/include/join_query.sql
The pg_join regression test is flaky. This PR adds some analyze calls and increases the size of one table to make the test outcome more deterministic (see #5167).
---
> Make pg_join test more deterministic

- src/chunk.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
In #6036 we introduced a status field on the hypertable catalog table,
to indicate whether an OSM chunk exists and if its range is
noncontiguous.
When an OSM chunk was attached to a hypertable, the noncontiguous flag
was not set because the expectation was for the OSM extension to update
this with an API call when data was actually moved inside OSM from
timescaledb.
However, this would create compatibility issues because the new version
of OSM will not be rolled out at the same time as the new version of
timescaledb.
This commit sets the noncontiguous flag upon new OSM chunk creation to
ensure backwards compatibility. However it should be reverted once the
new version of OSM is deployed.
> Set NONCONTIGUOUS status flag upon OSM chunk creation

- .github/workflows/memory-tests.yaml
This PR ensures the path to the PostgreSQL installation is set in the memory test workflow before TimescaleDB is compiled. 
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/6234012065/job/16920380918
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6234178259/job/16920879363
> Fix build failure in PG15 memory test

- .unreleased/PR_6067
- src/chunk.c
- src/hypertable.c
- src/osm_callbacks.c
- src/osm_callbacks.h
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
- tsl/test/src/test_chunk_stats.c
Add a callback for cascading drop chunks to OSM and integrate with drop_chunks
Add tests to verify that callbacks are triggered for drop_chunks
> Add drop chunk hook for OSM 

- .github/workflows/linux-32bit-build-and-test-ignored.yaml
- .github/workflows/linux-build-and-test-ignored.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/shellcheck-ignored.yaml
- .github/workflows/windows-build-and-test-ignored.yaml
The paths filter in github workflows will trigger when at least
one of the pathes match unless everything else has been explicitly
excluded. For the ignored workflows we want it to only trigger
when only those files explicitly specified are changed and nothing
else.
> Fix ignored workflow logic

- sql/notice.sql
With the current version of our docs, the first and third URL in our extension installation message pointed to the same page. This PR removes one of the duplicates.
---
```
test4=# create extension timescaledb;
WARNING:  
WELCOME TO
_____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
| |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
| | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
| | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
|_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
Running version 2.12.0-dev
For more information on TimescaleDB, please visit the following links:
1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
2. …
```
> Remove outdated URL from install message

- src/bgw/scheduler.c
- src/bgw/scheduler.h
- test/src/bgw/scheduler_mock.c
- test/src/bgw/timer_mock.c
- test/src/bgw/timer_mock.h
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/sql/bgw_reorder_drop_chunks.sql
The current version of the BGW scheduler mock does not support multiple background workers. If a second worker was registered, the reference to the previously registered worker gets lost. So, the implementation of the mock scheduler only waits for the latest registered worker before updating the mocked current time, which causes a race condition. If the previous workers are still active and logging messages after this point, the messages are logged with the updated mocked time. This leads to a non-deterministic behavior and test failures. For example:
```
msg_no | mock_time |    application_name     |    msg
---------+-----------+-------------------------+----------------------
-      1 |         0 | Retention Policy [1002] | job 1002 [...]
[...]
+      1 |   1000000 | Retention Policy …
```
> Support for multiple BGW in scheduler mock

- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/sql/bgw_db_scheduler.sql
The regression test bgw_db_scheduler tests if the BGW scheduler starts a background job after it is created. However, this only happens if the previous instance of the BGW scheduler is no longer active. If the old BGW scheduler instance is still running, it will pick up the job and prevent it from starting in the current test.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6249241189/job/16965466092?pr=6100 (attempt 1)
> Fix race condition in bgw_db_scheduler

- test/expected/bgw_launcher.out
- test/sql/bgw_launcher.sql
This patch stops the background worker in the bgw_launcher test teardown before the database is dropped. The current version of the test is flaky because sometimes the database cannot be dropped due to BGW activity.
---
Link to failing CI run: https://github.com/timescale/timescaledb/actions/runs/6238257502/job/16933717932
> Make sure BGW are stopped in test teardown

- .github/workflows/windows-build-and-test.yaml
Our nightly windows tests have not been running for several months, causing the status badge in our readme to remain in a failing state without ever turning green. This pull request enables the daily scheduled windows tests once again.
---
Previous CI runs: https://github.com/timescale/timescaledb/actions?query=workflow%3A%22Regression+Windows%22+branch%3Amain+event%3Aschedule
> Run scheduled windows test

- .unreleased/PR_6106
- src/osm_callbacks.c
The callback hook should use the old pointer instead of the new. This causes a segfault when ptr is NULL.
> Fix error in osmcallback hook

- src/dimension_slice.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
Calling ts_scan_iterator_next will advance internal scanner data structures. It is therefore not safe to use the iterator after ts_scan_iterator_next returned NULL and expect to be able to access the previous tuple. Under certain circumstances this may point the iterator to tuples not normally visible.
> Fix assert in dimension slice lookup

- tsl/test/expected/compression_bgw.out
- tsl/test/sql/compression_bgw.sql
The test compression_bgw cannot be executed multiple times because a role was created and not properly deleted. This PR adds the needed teardown step to the test.
-- 
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6262456556/job/17004671724?pr=6102
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6273903911/job/17038280449?pr=6110
> Make compression_bgw executable multiple times

- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
One of the test cases changes chunk status in order to fail the background job in order to ensure jobs continue to be scheduled even after such a scenario. The problem lies in the race condition between compression policy and the status update which both update the catalog and that causes random test failures. The solution is to add the compression policy after updating the status, eliminating the possibility of race condition.
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/6292122261/job/17081217268
> Fix bgw_custom test flakiness

- CONTRIBUTING.md
The CONTRIBUTING.md file states that our CI does not run regression checks on Windows, which is outdated information. In fact, we do execute regression checks on Windows in our current CI. This pull request removes the outdated section.
---
> Remove outdated windows CI information

- test/expected/bgw_launcher.out
- test/sql/bgw_launcher.sql
The bgw_launcher test changes the tablespace for a database. However, this requires that the database is used and no BGW are accessing the database. This PR ensures that the background workers are stopped before the tablespace is changed.
---
Failing CI run: https://github.com/timescale/timescaledb/actions/runs/6268372126/job/17023181691
> Ensure database is unused in bgw_launcher test

- .unreleased/pr_6113
- src/planner/planner.c
The check for a distributed hypertable was done after ht had been changed to the compressed hypertable potentially leading to miscount or even segfault when the cache lookup for the compressed hypertable returned NULL.
Fixes #5966
> Fix planner distributed table count

- test/perl/README.md
Updated the location and name of .perltidyrc in the README
After the recent change (https://github.com/timescale/timescaledb/commit/f1726790224e5444a2a2cb8c66155e4fb0b54e95) the location and name of perltitdyrc has changed.
> Fixed location (and name) of .perltidyrc

- .github/workflows/apt-arm-packages.yaml
- .github/workflows/apt-packages.yaml
We now build APT packages for Debian 10,11,12 and Ubuntu packages for 20.04 and 22.04 for both amd64 and arm64.
We also build Ubuntu packages for 23.04 for amd64 but not for arm64 because pgdg packages for postgres is not available for arm64 on Ubuntu 23.04.
> Adjust APT package test

- CMakeLists.txt
- src/copy.c
- src/import/ht_hypertable_modify.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/planner/expand_hypertable.c
- src/planner/planner.c
- tsl/src/continuous_aggs/common.c
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/finalize.c
- tsl/src/continuous_aggs/options.c
- tsl/src/fdw/modify_exec.c
- tsl/src/fdw/modify_plan.c
- tsl/src/fdw/scan_exec.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/planner.c
With the two commits included in this PR, timescaledb can be compiled with PG16.
> PG16 - Adapt to the new RTEPerminfo logic.

- tsl/test/isolation/expected/cagg_insert.out
- tsl/test/isolation/specs/cagg_insert.spec
Isolation test `cagg_insert` is flaky because refresh steps can complete in any order. Adding constraints so that completion is reported in the same order in all test runs.
Fixes #5331
> Fix flaky cagg_insert

- tsl/test/expected/bgw_custom.out
- tsl/test/sql/bgw_custom.sql
When dropping a table, we get notices if that causes to cancel background jobs and thus fail tests. By stopping the workers before dropping the table, we should reduce this flakiness.
Flaky CI runs:
https://github.com/timescale/timescaledb/actions/runs/6350907791/job/17251315853
https://github.com/timescale/timescaledb/actions/runs/6350907791/job/17251315717
> Fix bgw_custom flakiness by stopping bgws

- src/dimension.c
- src/error_utils.h
- src/hypertable.c
- tsl/test/expected/hypertable_generalization.out
- tsl/test/sql/hypertable_generalization.sql
This patch fixes segfaults in create_hypertable and add_dimension when passing NULL parameters.
> Fix segfaults in generic hypertable api

- src/dimension.c
- tsl/test/expected/hypertable_generalization.out
- tsl/test/sql/hypertable_generalization.sql
Users can set a NULL value as column name and cause a segfault which would crash the instance. This change checks for NULL values and errors out with appropriate message.
SQLSmith CI failure: https://github.com/timescale/timescaledb/actions/runs/6346388998/job/17239806645
> NULL check column name in by_range/by_hash funcs

- .github/workflows/catalog-updates-check.yaml
- .unreleased/enhancement_6049
- scripts/check_updates_ast.py
There are certain modifications/commands that should not be allowed
in our update/downgrade scripts. For example, when adding or dropping
columns to timescaledb catalog tables, the right way to do this is to
drop and recreate the table with the desired definition instead of doing
ALTER TABLE ... ADD/DROP COLUMN. This is required to ensure consistent
attribute numbers across versions.
This workflow detects this and some other incorrect catalog table
modifications and fails with an error in that case.
Fixes #6049
> Add CI check for incorrect catalog updates

- test/expected/loader-tsl.out
- test/expected/parallel-13.out
- test/expected/parallel-14.out
- test/expected/parallel-15.out
- test/sql/loader.sql.in
- test/sql/parallel.sql.in
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/expected/continuous_aggs-13.out
- tsl/test/expected/continuous_aggs-14.out
- tsl/test/expected/continuous_aggs-15.out
- tsl/test/expected/partialize_finalize.out
- tsl/test/expected/plan_skip_scan-13.out
- tsl/test/expected/plan_skip_scan-14.out
- tsl/test/expected/plan_skip_scan-15.out
- tsl/test/expected/skip_scan.out
- tsl/test/sql/agg_partials_pushdown.sql
- tsl/test/sql/continuous_aggs.sql.in
- tsl/test/sql/include/skip_scan_query.sql
- tsl/test/sql/partialize_finalize.sql
- tsl/test/t/008_mvcc_cagg.pl
PG16 renamed force_parallel_mode to debug_parallel_query.
https://github.com/postgres/postgres/commit/5352ca22e
> PG16: adjust tests to use debug_parallel_query

- .unreleased/pr_6142
- sql/compat.sql
When connected to TimescaleDB with the timescaledb.disable_load=on GUC setting, calling these functions causes an error to be thrown.
By specifying missing_ok=true, we prevent this situation from causing an error for the user.
> Do not throw an error on missing GUC value

- tsl/test/shared/expected/gapfill.out
- tsl/test/shared/sql/gapfill.sql
To work fine on dev-cloud tests, in presence of other extensions.
> Modify interpolate() call in gapfill test

- src/chunk.c
- src/dimension_slice.c
- src/dimension_slice.h
- src/hypertable.c
- tsl/test/isolation/expected/osm_range_updates_iso.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/osm_range_updates_iso.spec
This commit fixes two issues with the osm range update API:
1. Deadlock between two concurrent range updates.
Two transactions concurrently attempting to update the range
of the OSM chunk by calling hypertable_osm_range_update would
deadlock because the dimension slice tuple was first locked with
a FOR KEY SHARE lock, then a FOR UPDATE lock was requested before
proceeding with the dimension slice tuple udpate.
This commit fixes the deadlock by taking FOR UPDATE lock on the
tuple from the start, before proceeding to update it.
2. Tuple concurrently updated error for hypertable tuple.
When one session tries to update the range of the OSM chunk and another
enables compression on the hypertable, the update failed with tuple
concurrently updated error. This commit fixes this by first locking …
> Fix errors and add isolation tests for OSM API

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
The initial commit to adjust RELOPT_DEADREL for PG16 also freed
the RelOptInfo but even though we dont want them to be referenced
again since they are internal we must not free them because the
lower plan nodes still reference them leading to segfaults in the
executor when trying to access those reloptinfo. With this change
most of the compression tests pass on PG16.
This patch also gets rid of RELOPT_DEADREL for earlier PG versions
and always removes the entry from simple_rel_array.
> PG16 Fix transparent decompression

- src/bgw/scheduler.c
- src/bgw/scheduler.h
- test/expected/bgw_launcher.out
- test/sql/bgw_launcher.sql
- test/src/bgw/scheduler_mock.c
- test/src/bgw/timer_mock.c
- test/src/bgw/timer_mock.h
- tsl/test/expected/bgw_custom.out
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/isolation/expected/cagg_insert.out
- tsl/test/isolation/specs/cagg_insert.spec
- tsl/test/sql/bgw_custom.sql
- tsl/test/sql/bgw_db_scheduler.sql
- tsl/test/sql/bgw_reorder_drop_chunks.sql
> Fixes for 2.12.x

- tsl/src/continuous_aggs/insert.c
- tsl/test/expected/cagg_usage.out
- tsl/test/sql/cagg_usage.sql
When `continuous_agg_invalidation_trigger` is called without any argument, fcinfo->context in continuous_agg_trigfn is NULL and it should not be dereferenced.
---
> Improve arg handling in continuous_agg_trigfn

- .github/workflows/sqlsmith.yaml
The scheduled sqlsmith seems to run into timeout quite often so reduce the number of loops a bit.
> Reduce loops in scheduled sqlsmith runs

- src/planner/agg_bookend.c
- tsl/test/shared/expected/ordered_append-16.out
Reset the flag to control PlaceHolderInfo creation because we're copying the entire content of the (PlannerInfo *)root data structure when building the first/last path.
https://github.com/postgres/postgres/commit/b3ff6c74
> PG16: Reset PlannerInfo->placeholdersFrozen

- tsl/src/continuous_aggs/insert.c
- tsl/test/expected/cagg_usage.out
- tsl/test/sql/cagg_usage.sql
When the `continuous_agg_invalidation` trigger is called with an invalid hypertable id (e.g., caused by a user that modifies the trigger), the hypertable lookup returns NULL. This case was not handled properly so far. This patch adds proper checks to the function.
---
> Handle non existing ht in cache_inval_entry_init

- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/sql/agg_partials_pushdown.sql
So far, the parallel query plans of the agg_partials_pushdown test were not deterministic since multiple workers were used and the parallel session leader also participated in query processing. This makes it impossible to predict which worker would process how many tuples. With this patch, the number of parallel workers for the agg_partials_pushdown test has been reduced to 1 and the parallel_leader_participation has been disabled to ensure deterministic query plans.
-- 
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/6448252405/job/17505323789?pr=6164
> Make agg_partials_pushdown test more predictable

- .unreleased/PR_6117
- .unreleased/pr_6113
- .unreleased/pr_6142
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.12.0 release.
**Bugfixes**
* https://github.com/timescale/timescaledb/pull/6113 Fix planner distributed table count
* https://github.com/timescale/timescaledb/pull/6117 Avoid decompressing batches using an empty slot
* https://github.com/timescale/timescaledb/pull/6123 Fix concurrency errors in OSM API
* https://github.com/timescale/timescaledb/pull/6142 do not throw an error when deprecation GUC cannot be read
**Thanks**
* @symbx for reporting a crash when selecting from empty hypertables
> Release 2.12.1

- sql/updates/pre-update.sql
- src/hypertable.c
This code is no longer needed as no valid source timescaledb version in upgrade path can have those legacy triggers.
> Remove some code related to pre 1.0 triggers

- src/bgw/job.c
The jobs framework contains two functions for loading jobs (ts_bgw_job_get_scheduled and bgw_job_from_tupleinfo). However, the ts_bgw_job_get_scheduled function did not properly populate the `fixed_schedule` field, which caused some bugs in the calculation of the next execution time for a job. This PR ensures the fixed_schedule field is populated properly.
---
We have some checks in `bgw_db_scheduler_fixed` to test this code path. However, these tests use our mock framework and trigger only the `ts_bgw_job_entrypoint -> ts_bgw_job_stat_mark_end -> [..] -> ts_scanner_scan -> bgw_job_from_tupleinfo` code path for loading jobs and calculate the next execution for a failed job. Since the second code path can not be tested well at the moment, I did not add test cases and created the follow-up …
> Ensure fixed_schedule field is populated

- CHANGELOG.md
- scripts/test_updates_pg13.sh
- scripts/test_updates_pg14.sh
- scripts/test_updates_pg15.sh
- sql/CMakeLists.txt
- version.config
Bumping the previous version and adding tests for 2.12.1. Also adjust tagging date in changelog.
> Post-release fixes for 2.12.1

- .github/workflows/code_style.yaml
- scripts/check_unecessary_template_tests.sh
When the regression tests output differs between PG versions we create a template test (aka *.sql.in) and add several different output files for each supported version.
Over time we support new PG version and deprecate older ones, for example nowadays we're working on PG16 support and removed PG12 so we need to check if we still need template files.
> Add CI check for unecessary template tests

- .unreleased/pr_6178
- src/cross_module_fn.h
- src/nodes/chunk_dispatch/chunk_dispatch.h
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- src/nodes/hypertable_modify.c
- src/nodes/hypertable_modify.h
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/shared/expected/decompress_tracking.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/decompress_tracking.sql
This patch adds tracking number of batches and tuples that needed to be decompressed as part of DML operations on compressed hypertables.
These will be visible in EXPLAIN ANALYZE output like so:
QUERY PLAN
Custom Scan (HypertableModify) (actual rows=0 loops=1)
Batches decompressed: 2
Tuples decompressed: 25
->  Insert on decompress_tracking (actual rows=0 loops=1)
->  Custom Scan (ChunkDispatch) (actual rows=2 loops=1)
->  Values Scan on "*VALUES*" (actual rows=2 loops=1)
(6 rows)
> Show batches/tuples decompressed during DML operations in EXPLAIN output

- .unreleased/pr_6185
- sql/CMakeLists.txt
- sql/metadata.sql
- sql/restoring.sql
- sql/updates/version_check.sql
- test/expected/metadata.out
- test/sql/metadata.sql
- tsl/test/shared/sql/build_info.sql
This patch stores the current catalog version in an internal table to allow us to verify catalog and code version match. When doing dump/restore people occasionally report very unusual errors and during investigation it is discovered that they loaded a dump from an older version and run it with a later code version. This allows to detect mismatches between installed code version and loaded dump version. The version number in the metadata table will be kept updated in upgrade and downgrade scripts.
> Keep track of catalog version

- test/runner.sh
- test/runner_shared.sh
When a background worker is canceled by 'select delete_job()' the following log message is printed:
NOTICE:  cancelling the background worker for job
However, this log message is not deterministic and breaks our CI checks. So, this patch removes the log message from the test output to make the regression checks more deterministic.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6532360279/job/17735391567
> Remove canceled bgw jobs from test output

- .unreleased/fix_6188
- src/bgw/job.c
- src/bgw/scheduler.c
- src/guc.c
- src/guc.h
- test/src/bgw/log.c
- tsl/test/expected/bgw_db_scheduler.out
- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/expected/bgw_reorder_drop_chunks.out
- tsl/test/expected/bgw_scheduler_control.out
- tsl/test/expected/cagg_bgw-13.out
- tsl/test/expected/cagg_bgw-14.out
- tsl/test/expected/cagg_bgw-15.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/bgw_db_scheduler.sql
- tsl/test/sql/bgw_scheduler_control.sql
To avoid having to spam the log with unecessary background worker progress messages a GUC for controlling the background worker log level is introduced. This can be set using `ALTER SYSTEM` plus a call of `pg_reload_conf()` and will set the `log_min_messages` for the background workers only (scheduler and all job runners).
It also adds some job progress messages at debug level.
Fixes #6161
> Add GUC for setting background worker log level

- src/guc.c
In #6188 we introduced a new GUC `timescaledb.bgw_log_level` to control background workers log level, but if we missed to set the default value into the global variable leading to an assertion when checking for default values when defining it in the `_guc_init` process.
Fix it by properly initialize the global variable to the `log_min_messages`.
> Fix uninitialized variable ts_guc_bgw_log_level

- src/guc.c
When defining a GUC Postgres do a cross-check between the initial value of the C declaration associated to a GUC and its actual boot value in assert-enabled builds.
Previous PR #6206 didn't fixed it entirely and this happen just on PG16.
postgres/postgres@a73952b7
> PG16: Fix ts_bgw_log_level bootval

- .unreleased/pr_6210
- tsl/src/compression/compression.c
- tsl/test/shared/expected/decompress_tracking.out
- tsl/test/shared/sql/decompress_tracking.sql
EXPLAIN ANALYZE for compressed DML would error out with `bogus varno` error because we would modify the original expressions of the plan that were still referenced in nodes instead of adjusting copies and using those copies in our internal scans.
Fixes: #6175
> Fix EXPLAIN ANALYZE for compressed DML

- .unreleased/PR_6155
- tsl/src/nodes/gapfill/gapfill_exec.c
- tsl/src/nodes/gapfill/gapfill_internal.h
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/expected/gapfill-15.out
- tsl/test/shared/expected/gapfill-16.out
- tsl/test/shared/sql/gapfill.sql.in
In certain scenarios, when generating buckets with monthly buckets and different timezones, gapfill
would create timestamps which don't align with time_bucket and thus potentially generating multiple 
rows for an individual month. Instead of relying on previous timestamp to generate the next one, now
we generate them always from the start point which will make us align with time_bucket buckets.
> Align gapfill bucket generation with time_bucket

- .unreleased/PR_6155
- tsl/src/nodes/gapfill/gapfill_exec.c
- tsl/src/nodes/gapfill/gapfill_internal.h
- tsl/test/shared/expected/gapfill.out
- tsl/test/shared/sql/gapfill.sql
In certain scenarios, when generating buckets with monthly buckets and different timezones, gapfill
would create timestamps which don't align with
time_bucket and thus potentially generating multiple rows for an individual month. Instead of relying on previous timestamp to generate the next one, now
we generate them always from the start point
which will make us align with time_bucket buckets.
> Backport to 2.12.x: #6155: Align gapfill bucket generation with time_bucket

- .unreleased/PR_6155
- .unreleased/pr_6210
- CHANGELOG.md
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.12.1 release.
**Bugfixes**
* https://github.com/timescale/timescaledb/pull/6155 Align gapfill bucket generation with time_bucket
* https://github.com/timescale/timescaledb/pull/6181 Ensure fixed_schedule field is populated
* https://github.com/timescale/timescaledb/pull/6210 Fix EXPLAIN ANALYZE for compressed DML
> Release 2.12.2

- .unreleased/pr_6210
- tsl/src/compression/compression.c
EXPLAIN ANALYZE for compressed DML would error out with `bogus varno` error because we would modify the original expressions of the plan that were still referenced in nodes instead of adjusting copies and using those copies in our internal scans.
> Fix EXPLAIN for compressed DML

- .unreleased/feature_6195
- src/bgw/scheduler.c
- src/guc.c
- src/guc.h
- src/loader/bgw_launcher.c
- src/loader/bgw_launcher.h
- src/loader/loader.c
- tsl/test/expected/bgw_scheduler_restart.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/bgw_scheduler_restart.sql
If the scheduler receives an error, it will never restart again since `bgw_restart_time` is set to `BGW_NEVER_RESTART`, which will prevent all jobs from executing.
This commit fixes the issue by adding a GUC that can be set to the restart time for the scheduler, and set the default to 30 seconds. It also adds some additional variables to be able to shutdown the scheduler with a non-zero exit code, which allows the restart functionality to be tested.
Fixes #5091
> Restart scheduler on error

- .github/workflows/homebrew.yaml
The homebrew tap for timescaledb has been switched to PG15 but
the default postgres in the macos github environment is PG14 so
we have to explicitly install PG15.
> Install PG15 in homebrew test

- .unreleased/PR_6222
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/create.c
- tsl/test/expected/compression_ddl.out
- tsl/test/sql/compression_ddl.sql
Since version 2.11.0 we would get a segmentation fault during
decompression when there was an expressional or partial index on the
uncompressed chunk.
This patch fixes this by calling `ExecInsertIndexTuples` to insert into
indexes during chunk decompression, instead of `CatalogIndexInsert`.
In addition, when enabling compression on a hypertable, we check the
unique indexes defined on it to provide performance improvement hints
in case the unique index columns are not specified as compression
parameters.
However this check threw an error when expression columns were present
in the index, preventing the user from enabling compression.
This patch fixes this by simply ignoring the expression columns in the
index, since we cannot currently segment by an expression.
Fixes #6205, #6186
> Fix index inserts during decompression

- src/planner/planner.c
- test/sql/include/join_query.sql
PG16 will remove RelOptInfo entries from root->simple_rel_array when it considers them not needed in analyzejoins.c to prevent reprocessing them. Due to this a relation may be present in root->simple_rte_array but have no corresponding entry in root->simple_rel_array. This patch adds a check for this case.
https://github.com/postgres/postgres/commit/e9a20e45
> PG16: Fix JOIN behaviour

- test/pg_regress.sh
PG16 removed the `ignore` feature from `pg_regress` so as an workaround if we have any IGNORES entry then we merge it altogether with SKIPS and cleanup the IGNORES in `pg_regress.sh` wrapper.
postgres/postgres@bd8d453e
> PG16: Removed ignore feature from pg_regress

- test/sql/updates/post.continuous_aggs.sql
- test/sql/updates/post.continuous_aggs.v3.sql
- test/sql/updates/setup.catalog.sql
- test/sql/updates/setup.continuous_aggs.sql
- test/sql/updates/setup.continuous_aggs.v2.sql
The upgrade test utilizes several CAggs and defines refresh policies.
However, the test results are not deterministic due to the unpredictable
timing of the refreshes. This causes the test to be flaky. This pull
request explicitly adds explicit refreshes to the upgrade test to ensure
that the test results are deterministic.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6644016971/job/18057621681?pr=6229
Link to fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6646121959/job/18058928349
> Fix flaky upgrade test

- src/build-defs.cmake
- tsl/src/build-defs.cmake
Till PG15, shared libraries with ".so" suffix used to be loaded properly on MacOSX. That has changed with PG16. Change it so that shared libraries will uniformly use the ".dylib" suffix on MacOSX
> Use "dylib" uniformly on MacOSX

- .github/workflows/sqlsmith.yaml
In the nightly CI runs the sqlsmith job seems to fail quite often with `GitHub Actions 3 lost communication with the server.`. This can happen when the runner process is starved for CPU/Memory. To reduce the likelyhood this patch reduces the number of loops for sqlsmith during nightly CI runs further.
> Further reduce sqlsmith loops in nightly runs

- .github/workflows/issue-handling.yaml
This PR enhances the issue workflow; CAgg related issues are automatically added to the CAgg project board.
---
> Add CAgg related issues to project

- src/process_utility.c
In order to properly process hypertables, chunks and compressed chunks we run our own code when a VACUUM is executed.
PG16 introduced a new option named ONLY_DATABASE_STATS that only update the database-wide statistics and when this option is specified no other option may be enabled. Internally we build the list of all underlying relations for hypertables in order to properly execute this utility command leading to the following error:
```sql
test=# VACUUM (ONLY_DATABASE_STATS);
ERROR:  0A000: ONLY_DATABASE_STATS cannot be specified with a list of tables LOCATION:  ExecVacuum, vacuum.c:369
```
Fixed it by properly handling the ONLY_DATABASE_STATS to don't execute our modified vacuum code and instead the regular Postgres.
The error was catched up when running the `pginstallcheck` …
> PG16: Handle new vacuum option ONLY_DATABASE_STATS

- src/process_utility.c
In our code we have an Event Trigger on `ddl_command_end` to process some DDL commands, and specially the `ALTER TABLE` we execute some code to properly deal with hypertables, chunks and compressed chunks.
The problem is when we start to process our code at `ddl_command_end` event we get the related `relid` by calling the `AlterTableLookupRelation` that perform the proper acl checking. But this is a bit wrong because in case of a `ALTER TABLE ... OWNER TO ...` at this point (aka `ddl_command_end`) the ownership of the relation was already processed and with this PG16 refactoring it now is visible for the `object_ownercheck` leading to a misbehavior.
Due to our intention is just the get the `relid` related to the AlterTableCmd just fixed it by replacing the `AlterTableLookupRelation` for …
> PG16: Refactored ownercheck functions

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
f3b3e556932e016a321796bc0c517199939aabf6 introduces sorted paths for compressed chunks. However, it uses an unneeded and invalid memcpy call, which can cause crashes. This PR removes the memcpy call.
--
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6671738229/job/18134277248
> Remove invalid memcpy

- tsl/test/shared/expected/ordered_append-16.out
In #6168 we added the ordered append output test for PG16 but unfortunately it was wrong and didn't take in account the planner output differences introduced.
Fixed it by changing properly the output changes for PG16.
> PG16: Fix ordered append output test

- tsl/src/compression/compression.c
Change the code to pass RowDecompressor by reference instead of value. Found by coverity. 
> Pass RowDecompressor by reference in build_scankeys

- .unreleased/fix_6240
- test/src/bgw/scheduler_mock.c
If `RegisterDynamicbackgroundworker` fails the returned handle will be
null, which will cause `WaitForBackgroundWorkerStartup` to fail with a
crash. This can typically happen if there is not enough slots in
`BackgroundWorkerData`. In that case, just return and do not call
`WaitForBackgroundWorkerStartup`.
> Check if worker registration succeeded

- .unreleased/feature_6050
- src/compat/compat.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- src/guc.c
- src/guc.h
- src/planner/partialize.c
- src/planner/partialize.h
- tsl/src/CMakeLists.txt
- tsl/src/init.c
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/compressed_batch.h
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/partialize_agg.c
- tsl/src/partialize_agg.h
- tsl/test/expected/merge_append_partially_compressed-13.out
- tsl/test/expected/merge_append_partially_compressed-14.out
- tsl/test/expected/merge_append_partially_compressed-15.out
- tsl/test/expected/vectorized_aggregation.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/vectorized_aggregation.sql
This commit introduces a vectorized version of the sum() aggregate
function on compressed data. This optimization is enabled if (1) the
data is compressed, (2) no filters or grouping is applied, (3) the data
type is a 32-bit sum, and (4) the aggregation can be pushed down to
the chunk level.
---
Tsbench run: https://grafana.ops.savannah-dev.timescale.com/d/NdmLnOk4z/compare-benchmark-runs?orgId=1&var-branch=main&var-run1=2818&var-run2=2819&var-threshold=0.02
> Vectorized aggregation execution for sum

- tsl/src/nodes/decompress_chunk/pred_vector_const_arithmetic_all.c
- tsl/src/nodes/decompress_chunk/vector_predicates.c
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/sql/decompress_vector_qual.sql
Implement the vectorized comparison operators for Date type, using our existing vector functions for arithmetic comparison.
> vectorized comparisons for Date

- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/partialize_agg.c
- tsl/test/expected/compression_qualpushdown.out
- tsl/test/expected/vectorized_aggregation.out
- tsl/test/sql/vectorized_aggregation.sql
This patch adds support for vectorized aggregation queries with filters
on the segment_by value of compressed data.
---
Should be merged after: https://github.com/timescale/timescaledb/pull/6050
> Support for segment_by filters on vector aggs

- .unreleased/pr_6254
- sql/policy_internal.sql
In 2 instances of the exception handling _message and _detail were not properly set in compression_policy_execute leading to empty message and detail being reported.
> Fix exception detail passing in compression_policy_execute

- .unreleased/pr_6264
- tsl/src/nodes/decompress_chunk/batch_array.c
This was causing memory corruption in the PG16 tests but affects previous PG versions as well.
> Fix missing result assignment for bms_del_member

- coccinelle/bms_result.cocci
Some bitmap set operations recycle one of the input parameters or return a reference to a new bitmap set. The added set of rules checks that the returned reference is not discarded.
---
Example output
```
-	bms_del_member(chunk_state->unused_batch_states, next_free_batch);
+	/* Result of bms_del_member has to be used */
+	chunk_state->unused_batch_states = bms_del_member(chunk_state->unused_batch_states,
+							  next_free_batch);
```
--- 
Should be merged after: https://github.com/timescale/timescaledb/pull/6264
> Add Coccinelle rules - bitmap set operations

- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/shared/expected/constify_timestamptz_op_interval.out
- tsl/test/shared/expected/constraint_exclusion_prepared.out
- tsl/test/shared/expected/ordered_append-13.out
- tsl/test/shared/expected/ordered_append-14.out
- tsl/test/shared/expected/ordered_append-15.out
- tsl/test/shared/expected/ordered_append_join-13.out
- tsl/test/shared/expected/ordered_append_join-14.out
- tsl/test/shared/expected/ordered_append_join-15.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
- tsl/test/sql/decompress_vector_qual.sql
This means vectorizing very common filters such as `ts > now() - interval '1 day'`.
The only query with stable expressions we have in tsbench shows a 130% improvement:
https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=2853&var-run2=2855&var-threshold=0.05&var-use_historical_thresholds=false
> stable expressions as constant in vectorized filters

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/test/expected/merge_append_partially_compressed-16.out
- tsl/test/expected/transparent_decompression-16.out
- tsl/test/shared/expected/ordered_append_join-16.out
Mark the EquivalenceMember for the compressed chunk as derived to
prevent an infinite recursion.
> PG16: Fix join recursion

- .unreleased/pr_6275
- tsl/src/compression/create.c
Oids should not be stored in Bitmapsets as storing Oids that way is very inefficient and may potentially consume a lot of memory depending on the values of the oids. Storing them as list is more efficient instead.
Fixes #6252
> Fix compression for tables with large oids

- .github/workflows/windows-build-and-test.yaml
Sometime ago we freeze Postgres packages on Windows (14.5.1 and 15.0.1) due to some issues on chocolatey.
Now is time to remove it and use the latest version.
> Use last package Postgres version on Windows

- test/src/telemetry/test_telemetry.c
Telemetry tests without OpenSSL was failing to build because PG16 converted the *GetDatum() and DatumGet*() macros to inline functions that enable compiler to catch wrong usage of Datums.
postgres/postgres@c8b2ef0
> PG16: Fix telemetry tests without OpenSSL

- .github/workflows/abi.yaml
This changes the way of pinning OpenSSL 1.1, so that it supports the case of PG16 where both the oldest and the newest alpine docker images have OpenSSL 3. Depending on the PG versions, both old and new images might have either 1.1 or 3, so we just try to install both packages.
> Fix ABI check on PG 16

- .github/workflows/windows-build-and-test.yaml
- tsl/test/expected/compressed_collation.out
- tsl/test/sql/compressed_collation.sql
Now that PG16 is approved on Chocolatey we can finally enable Windows on CI.
https://community.chocolatey.org/packages/postgresql16
> PG16: Enable Windows on CI

- .github/workflows/windows-build-and-test-ignored.yaml
In ef505760 we enabled PG16 on Windows CI but forgot the add it to the ignored workflow.
> PG16: Fix ignored workflow for Windows on CI

- .unreleased/fix_6289
- src/nodes/chunk_append/planner.c
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/sql/agg_partials_pushdown.sql
In ba9b81854c8c94005793bccff29433f6086e5274 we added support for chunk-wise aggregates. The pushdown of the aggregate breaks the startup exclusion logic of the ChunkAppend node. This PR adds the support for startup chunk exclusion with chunk-wise aggs.
Fixes: #6282
> Add support for startup chunk exclusion with aggs

- tsl/src/nodes/decompress_chunk/decompress_chunk.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
- tsl/src/nodes/decompress_chunk/planner.c
This patch adds the support for the dynamic detection of the data type for a vectorized aggregate. In addition, it removes the hard-coded integer data type and initializes the decompression_map properly. This also fixes an invalid memory access.
---
Failed Sanitizer run: https://github.com/timescale/timescaledb/actions/runs/6751417152/job/18355481965
Fixed Sanitizer run: https://github.com/timescale/timescaledb/actions/runs/6771930209/job/18403409265?pr=6285
> Determine data type of vector agg at plan stage

- test/runner.sh
- test/runner_shared.sh
The CI tests on Windows log the creation of a new WAL file in a non-deterministic way. This message causes the regression tests to fail. This PR removed these messages from the test output.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/6809123385/job/18514803292?pr=6298
> Stabilize CI by excluding debug messages

- .github/workflows/cron-tests.yaml
- scripts/test_restore_points.sh
Currently, MN is not supported on PG16. Therefore, the creation of distributed restore points fails on PG16. This patch disables the CI test for this PG version.
---
Link to broken CI run: https://github.com/timescale/timescaledb/actions/runs/6808663440/job/18513494748
Link to fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6809128223/job/18514813987?pr=6298
> Adjust restore points test for PG 16

- .unreleased/pr_6297
- tsl/src/continuous_aggs/common.c
- tsl/test/expected/cagg_errors.out
- tsl/test/sql/cagg_errors.sql
When creating a Continuous Aggregate using a NULL `bucket_width` in the `time_bucket` function it lead to a segfault, for example:
CREATE MATERIALIZED VIEW cagg WITH (timescaledb.continuous) AS SELECT time_bucket(NULL, time), count(*)
FROM metrics
GROUP BY 1;
Fixed it by raising an ERROR if a NULL `bucked_width` is used during the Continuous Aggregate query validation.
> Fix segfault creating cagg with NULL bucket width

- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/test/expected/transparent_decompression-13.out
- tsl/test/expected/transparent_decompression-14.out
- tsl/test/expected/transparent_decompression-15.out
- tsl/test/shared/expected/transparent_decompress_chunk-13.out
- tsl/test/shared/expected/transparent_decompress_chunk-14.out
- tsl/test/shared/expected/transparent_decompress_chunk-15.out
We will decompress the compressed columns on demand, skipping them if the vectorized quals don't pass for the entire batch. This allows us to avoid reading some columns, saving on IO. The number of batches that are entirely filtered out is reflected in EXPLAIN ANALYZE as 'Batches Removed by Filters'.
Some benchmarks:
Before, ms | After, ms | Query
--- | --- | ---
73.097 | 37.005 | `select distinct(country) from uk_price_paid where price > 150000000;`
19.149 | 11.295 | `select count(*), avg(total_amount), max(dropoff_datetime) from rides where passenger_count >= 5;`
> Read and decompress columns lazily

- .unreleased/fix_6305
- sql/maintenance_utils.sql
- test/expected/util.out
- test/sql/util.sql
Function `_timescaledb_functions.makeaclitem` needs to be strict since if it is called with NULL values, it should return NULL.
> Make _timescaledb_functions.makeaclitem strict

- .unreleased/feature_6307
- sql/cagg_utils.sql
- sql/updates/reverse-dev.sql
- src/compat/compat.h
- src/cross_module_fn.c
- src/cross_module_fn.h
- tsl/src/continuous_aggs/CMakeLists.txt
- tsl/src/continuous_aggs/common.c
- tsl/src/continuous_aggs/common.h
- tsl/src/continuous_aggs/create.c
- tsl/src/continuous_aggs/repair.c
- tsl/src/continuous_aggs/utils.c
- tsl/src/continuous_aggs/utils.h
- tsl/src/init.c
- tsl/test/expected/cagg_utils.out
- tsl/test/shared/expected/extension.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/cagg_utils.sql
With this function is possible to execute the Continuous Aggregate query validation over an arbitrary query string, without the need to actually create the Continuous Aggregate.
It can be used, for example, to check for most frequent queries maybe using `pg_stat_statements`, validate them and check if there are queries that potenttialy can turned into a Continuous Aggregate.
> Add SQL function cagg_validate_query

- .github/workflows/issue-handling.yaml
Workflow actions does not move issue to Done column when there is a
comment and the issue is then closed. This commit deals with that by
handling the closed event and move it to the Done column as well as
removing labels that can interfere with processing.
> Move issue to Done column when closed

- .github/workflows/sanitizer-build-and-test.yaml
In the sanitizer workflow we're trying to upload sanitizer output logs from `${{ github.workspace }}/sanitizer` but in the ASAN_OPTIONS, LSAN_OPTIONS and UBSAN_OPTIONS we were setting output logs to another place.
Example of workflow that files were not found in the provided path: https://github.com/timescale/timescaledb/actions/runs/6830847083
> Fix sanitizer output log directory

- tsl/test/sql/CMakeLists.txt
In 068534e31730154b894dc8e4fb5315054e1ae51c we make the dist_util regression test version specific. However, the solo test declaration for this test was not adjusted, which makes this test flaky. This PR fixes the declaration.
---
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6864087479/job/18665114320?pr=6311
```
test dist_util-13                 ... ok         8627 ms
...
test dist_util-15                 ... ok         8302 ms
```
> Fix solo test for dist_util

- sql/size_utils.sql
- src/utils.c
- test/isolation/expected/concurrent_query_and_drop_chunks.out
- test/isolation/specs/concurrent_query_and_drop_chunks.spec
In https://github.com/timescale/timescaledb/commit/ae21ee96565f58efade65d82611354679745b5b8 we fixed a race condition when running a query to get the
hypertable sizes and one or more chunks was dropped in a concurrent
session leading to exception because the chunks does not exist.
In fact the table lock introduced is useless because we also addad
proper joins with Postgres catalog tables to ensure that the relation
exists in the database when calculation the sizes. And even worse with
this table lock now dropping chunks wait for the functions that
calculate the hypertable sizes.
Fixed it by removing the useless table lock and also added isolation
tests to make sure we'll not end up with race conditions again.
> Remove useless table lock

- src/guc.c
- src/guc.h
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/expected/compress_default.out
- tsl/test/expected/compression_indexscan.out
- tsl/test/expected/compression_update_delete.out
- tsl/test/expected/decompress_index.out
- tsl/test/expected/decompress_memory.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compress_default.sql
- tsl/test/sql/compression_indexscan.sql
- tsl/test/sql/compression_update_delete.sql
- tsl/test/sql/decompress_index.sql
- tsl/test/sql/decompress_memory.sql
This should improve the throughput somewhat.
This PR does several things:
1. Simplify loop condition in decompressing the compressed batch by using the count metadata column.
2. Split out a separate function that decompresses the entire compressed batch and saves the decompressed tuples slot into `RowDecompressor`.
3. Use bulk table insert function for inserting the decompressed rows, this reduces WAL activity.
4. If we have indexes on uncompressed chunk, update them one index for entire batch at a time, to reduce load on shared buffers cache. Before that we used to update all indexes for one row, then for another, etc.
5. Add a test for memory leaks during (de)compression.
6. Update the `compression_update_delete` test to use INFO messages + a debug GUC instead of DEBUG messages which …
> Use bulk heap insert API for decompression

- test/expected/repair.out
- test/expected/util.out
- test/sql/repair.sql
- test/sql/util.sql
Tests `util` and `repair` both used the same user name, so when executing in the same parallel suite they could cause conflict.
Instead, use different role names for different tests.
> Use test-specific temporary roles

- src/nodes/chunk_append/planner.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
Foreign tables add an extra "wholerow" `ROWID_VAR` to the `HypertableModify` scan's targetlist. It causes `adjust_appendrel_attrs()` to assert when the Var has been previously modified by `ts_replace_rowid_vars()`. This patch keeps the original unaltered targetlist letting `adjust_appendrel_attrs()` properly replace these `ROWID_VAR`s for the chunks.
timescale/timescaledb-osm#398
> Bugfix: adjust "wholerow" `ROWID_VAR` in the chunks' targetlist

- tsl/src/compression/compression.c
Only read list of indexes when we actually intend to use it in compress_chunk.
> Optimize compress_chunk index behaviour

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/expected/compression_sorted_merge-16.out
- tsl/test/sql/compression_sorted_merge.sql.in
We have a separate GUC for it, this way it's more convenient to test various plans.
Part of https://github.com/timescale/timescaledb/pull/6323
This can help with debugging problems like this one https://github.com/timescale/timescaledb/issues/6310
> Don't disable batch sorted merge plan with enable_sort GUC

- .unreleased/pr_6332
- sql/updates/latest-dev.sql
- tsl/src/nodes/decompress_chunk/planner.c
We added a workaround for segmentby columns with incorrect typmod
and collation in c73c5a74 but did not adjust pre-existing relations.
This patch will fix any existing relations where the segmentby columns
of compressed chunks have incorrect typmod and collation and remove
the code workaround.
> Fix segmentby typmod and collation of compressed chunks

- src/nodes/chunk_append/planner.c
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/sql/agg_partials_pushdown.sql
In e90280a we added support for ChunkAppend startup chunk exclusion with a custom scan below a partial aggregation. This PR changes the logic and adds support for more nodes below the partial aggregation (e.g., IndexScans).
--- 
> Add support for chunk exclusion with partial aggs

- .github/gh_matrix_builder.py
In e3437786ad we disabled the MN test for PR. This leads to the problem that a PR can break MN tests and get merged. This PR enables MN test for one PG version to make the PR author aware of any MN-related problems. This PR fixes also a typo in the configuration settings, which prevented that MN tests are executed by our scheduled CI runs.
---
> Enable MN test for PG 15 in CI

- tsl/src/partialize_agg.c
Remove checks that will always return true in current implementation to make refactoring easier. Aggref->args will always be list of TargetEntry, and the bulk_decompression check will always return true as well.
> Remove superfluous checks in partialize_agg

- test/expected/parallel-13.out
- test/expected/parallel-14.out
- test/expected/parallel-15.out
- test/expected/parallel-16.out
- test/sql/parallel.sql.in
One test query of the parallel test did not contain an ORDER BY. Therefore, the test result was not deterministic. This patch adds the missing ORDER BY.
---
> Make parallel test deterministic

- .unreleased/fix_6343
- sql/policy_internal.sql
- tsl/test/expected/bgw_custom-13.out
- tsl/test/expected/bgw_custom-14.out
- tsl/test/expected/bgw_custom-15.out
- tsl/test/expected/bgw_custom-16.out
- tsl/test/expected/compression_bgw-13.out
- tsl/test/expected/compression_bgw-14.out
- tsl/test/expected/compression_bgw-15.out
- tsl/test/expected/compression_bgw-16.out
- tsl/test/sql/include/recompress_basic.sql
Change compression policy to use segmentwise
recompression when possible to increase performance. Segmentwise recompression decompresses rows into memory, thus reducing IO load when recompressing, making it much faster for bigger chunks.
Fixes #6255
> Use segmentwise recompression in compress policy

- .unreleased/fix_6339
- sql/chunk_constraint.sql
- sql/updates/reverse-dev.sql
- test/expected/constraint.out
- test/sql/constraint.sql
If a hypertable uses a non-default tablespace for its primary or unique constraints with additional DEFERRABLE or INITIALLY DEFERRED characteristics then any chunk creation will fail with syntax error. We now set the tablespace via a separate command for such constraints for the chunks.
Fixes #6338
> Fix non-default tablespaces with constraints

- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
If we reuse the compressor to recompress multiple sets of tuples, internal state gets left behind from the previous run which can contain invalid data. Resetting the compressor first iteration field between runs fixes this.
Issue was caught by the sanitizer run with the following stacktrace:
```
#10 0x00005592c652336d in toast_raw_datum_size (value=108370616179040)
at detoast.c:550
attr = 0x62900014d960
result = <optimized out>
#11 0x00005592c8093bfe in texteq (fcinfo=0x62900014c2f8) at varlena.c:1799
arg1 = 108370616179040
arg2 = 108095738524216
len1 = <optimized out>
len2 = <optimized out>
collid = <optimized out>
result = <optimized out>
#12 0x00007f40a20e230a in segment_info_datum_is_in_group (
segment_info=segment_info@entry=0x625000185868, datum=<optimized out>, 
is_null=<optimized …
```
> Reset compressor between recompression runs

- .github/workflows/windows-packages.yaml
PostgreSQL 13.13 is currently not available on chocolatey. Therefore, use PostgreSQL 13.12 instead.
--
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/6985699521/job/19010276132
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/6988840218/job/19016808466
> Use PG 13.12 for windows builds

- src/ts_catalog/array_utils.c
- src/ts_catalog/array_utils.h
This patch fixes ts_array_position when the entry was not found. Previously it would return the position of the last element in that case. This patch also adds a NULL check to ts_array_length and an Assert for TEXT array to ts_array_is_member and ts_array_position. Current code should not be affected by any of these changes.
> Fix ts_array_position when entry is not found

- tsl/src/nodes/decompress_chunk/batch_array.c
- tsl/src/nodes/decompress_chunk/batch_array.h
- tsl/src/nodes/decompress_chunk/batch_queue_fifo.h
- tsl/src/nodes/decompress_chunk/batch_queue_heap.c
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/compressed_batch.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
Refactor DecompressChunk to make it more modular. This is the first step of a bigger refactor that aims to create better separation of concerns across the code that implements transparent decompression.
Currently, the code is only semi-modular, and all state is kept directly in the DecompressChunk scan node. As a result, this object has to be passed into all the related modules, which makes it harder to call that code from other places without a reference to the "big" scan node.
The goal of this change (and upcoming changes) is to make each module hold its own state relevant to that module. DecompressChunk can then be composed of these distinct modules instead of being a monolith.
> Decouple batch array from DecompressChunk

- scripts/merge_changelogs.sh
Our changelog contains empty lines between the version sections. These empty lines were missing in the script output so far.
---
> Add missing new lines to changelog script

- CMakeLists.txt
Since a664e685cd, we are using the PREPEND statement in our CMake files, which was added in CMake 3.15. This PR adjusts the required CMake version.
---
See: https://cmake.org/cmake/help/latest/release/3.15.html
> Adjust required CMake version

- tsl/src/nodes/decompress_chunk/batch_queue_fifo.h
- tsl/src/nodes/decompress_chunk/batch_queue_heap.c
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
This change continues the refactor of transparent decompression in order to make it more modular. A new structure called DecompressContext is introduced that holds the state necessary to do execution-time decompression. The context can be passed around to related code without passing on the full DecompressChunkState node. However, this is not yet fully realized and DecompressChunkState is still passed around across many modules. This will be addressed in follow-on changes.
> Break out decompress state from DecompressChunkState

- .github/workflows/pr-validation.yaml
Changes in the loader code require a restart of PostgreSQL during upgrades. This check creates awareness of these changes and allows the coordination of the update process early.
---
> Add CI check for loader changes

- tsl/src/continuous_aggs/create.c
- tsl/test/expected/exp_cagg_next_gen.out
- tsl/test/sql/exp_cagg_next_gen.sql
When a Continuous Aggregate with variable size bucket is created is added one entry into the
`_timescaledb_catalog.continuous_aggs_bucket_function` catalog table.
The problem is that the `experimental` flag was not properly updated if the extension is installed into a schema other than PUBLIC.
Fixed it by checking if the bucket function resides or not on the experimental schema (aka `timescaledb_experimental`).
> Fix CAgg bucket function metadata

- .unreleased/fix_6365
- sql/size_utils.sql
- tsl/test/expected/compression.out
- tsl/test/sql/compression.sql
The approximate_row_count function was using the reltuples from compressed chunks and multiplying that with 1000 which is the default batch size. This was leading to a huge skew between the actual row count and the approximate one. We now use the numrows_pre_compression value from the timescaledb catalog which accurately represents the number of rows before the actual compression.
> Use numrows_pre_compression in approx row count

- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/create.c
Remove some references to algo_id since it the actual algorithm used for a batch can only be determined by reading the batch header. algo_id will be removed entirely in a followup patch. This patch also makes the function to get the default algorithm no longer static.
> Refactor default algorithm handling

- src/debug_assert.h
- src/with_clause_parser.c
- src/with_clause_parser.h
- tsl/src/bgw_policy/job.h
- tsl/src/compression/array.h
- tsl/src/compression/compression.h
- tsl/src/compression/deltadelta.h
Since postgres.h includes c.h and we are including that in almost every file there is no need to directly include c.h in those same files.
> Remove direct c.h include

- src/guc.c
- tsl/test/expected/vectorized_aggregation.out
- tsl/test/sql/vectorized_aggregation.sql
This PR renames the GUC for vectorized aggregation from `timescaledb.vectorized_aggregation` to
`timescaledb.enable_vectorized_aggregation` to be consistent with the naming of our other GUCs.
---
> Rename vectorized aggregation GUC

- .github/gh_matrix_builder.py
Since we now have all PG16 patches merged we dont need to run MacOS and no-telemetry build tests on multiple PG versions. Especially the MacOS test is quite time-consuming.
> Run MacOS and no-telemetry tests only on latest PG

- .unreleased/fix_6377
- src/planner/partialize.c
- test/expected/partitionwise-13.out
- test/expected/partitionwise-14.out
- test/expected/partitionwise-15.out
- test/expected/partitionwise-16.out
- test/sql/.gitignore
- test/sql/CMakeLists.txt
- test/sql/partitionwise.sql.in
- tsl/test/expected/merge_append_partially_compressed-16.out
Latest version of Postgres introduced an optimization which removes redundant grouping and DISTINCT columns. This optimization needs to be taken into account when generating pushdown aggregation plans so we can create valid plans with correct grouping columns.
> Use processed group clauses in PG16

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_chunk.h
Change the is_compressed_column implementation to determine whether a column is compressed based on datatype. Any column with type _timescaledb_internal.compressed_data is considered compressed. The new implementation should return exactly the same result as the old one.
> Simplify is_compressed_column in DecompressChunk

- tsl/src/compression/compression.h
This field was added in fb0df1ae but never actually used for anything.
> Remove unused segmentby_index_index from struct RowCompressor

- src/ts_catalog/array_utils.c
- src/ts_catalog/array_utils.h
- tsl/src/chunk_api.c
- tsl/src/compression/create.c
- tsl/src/remote/dist_commands.c
This change makes ts_array_length constraints consistant with the constraints of the other array helper functions. Previously ts_array_length would also work on multidimensional arrays but by limiting to 1-dimensional arrays we can optimize the code path. This patch also adds helper functions for appending an element to an array.
> Limit ts_array_length to 1 dimensional arrays

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/test/expected/compress_sorted_merge_filter.out
- tsl/test/expected/compression.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/expected/compression_sorted_merge-16.out
- tsl/test/expected/compression_sorted_merge_distinct.out
- tsl/test/expected/transparent_decompression_ordered_index-13.out
- tsl/test/expected/transparent_decompression_ordered_index-14.out
- tsl/test/expected/transparent_decompression_ordered_index-15.out
- tsl/test/expected/transparent_decompression_ordered_index-16.out
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compress_sorted_merge_filter.sql
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_sorted_merge.sql.in
- tsl/test/sql/compression_sorted_merge_distinct.sql
This PR makes several modifications to the cost model of batch sorted merge, that should allow us to apply it in more cases where it's beneficial:
1. When doing batch sorted merge, we have to hold the latest batch open for each distinct value of segmentby columns. This commit adds estimation for this number with the usual Postgres estimators for grouping cardinality.
1. The number of open batches is used to estimates the amount of required memory. If it is above `work_mem`, the batch sorted merge cost is penalized.
1. The cost function is changed to `O(uncompressed_rows * log(open_batches))`, which reflects the nature of the algorithm. 
> Make batch sorted merge cost depend on number of unique segmentby values

- tsl/src/nodes/decompress_chunk/CMakeLists.txt
- tsl/src/nodes/decompress_chunk/batch_queue.h
- tsl/src/nodes/decompress_chunk/batch_queue_fifo.c
- tsl/src/nodes/decompress_chunk/batch_queue_fifo.h
- tsl/src/nodes/decompress_chunk/batch_queue_heap.c
- tsl/src/nodes/decompress_chunk/batch_queue_heap.h
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/compressed_batch.h
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/src/nodes/decompress_chunk/decompress_context.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/exec.h
The batch queue implementation, which is part of transparent decompression, is refactored to be its own self-contained module. Previously, the batch queue functionality consisted of functions that operated on the DecompressChunkState node instead of its own distinct object.
The two batch queue types, heap and fifo, are now modularized in their separate source files with a common interface exposed in `batch_queue.h`. The state related to the two batch queue implementations is moved from DecompressChunkState into the respective modules depending on type. For example, the heap state and related initialization code is moved to the heap-based batch queue.
The DecompressContext is also moved to its own header file so that other modules need not include everything related to …
> Modularize batch queue in transparent decompression

- src/hypertable.c
- src/hypertable.h
- src/hypertable_cache.c
The tuplelock argument was never used in hypertable_scan_limit_internal. This patch removes it and also removes some other unused functions related to locking.
> Remove unused argument tuplock in hypertable_scan_limit_internal

- .unreleased/fix_6393
- tsl/src/partialize_agg.c
- tsl/test/expected/vectorized_aggregation.out
- tsl/test/sql/vectorized_aggregation.sql
This is not supported at the moment, we can only aggregate bare columns, but we forgot to check this at the planning stage, so it fails.
> Disable vectorized sum for expressions

- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/compression_api.h
This patch removes the following unused functions:
- policy_compression_get_compress_after_int(const Jsonb *config)
- policy_compression_get_compress_after_interval(const Jsonb *config)
- policy_compression_get_compress_created_before_interval(const Jsonb *config)
> Remove unused compression policy helper functions

- .github/workflows/abi.yaml
Pin Alpine version to 3.18 since 3.19 does not have openssl 1.1 at all which we need for some of the ABI checks against older versions.
> Pin Alpine version to 3.18 in ABI test

- coccinelle/namedata.cocci
- tsl/src/deparse.c
Direct access of the `.data` member of `NameData` structures are discuraged and `NameStr` should be used instead.
Also adding one instance that was missed in #5336.
> Add Coccinelle rule to use NameStr

- .unreleased/fix_6408
- tsl/src/nodes/gapfill/gapfill_plan.c
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/expected/gapfill-15.out
- tsl/test/shared/expected/gapfill-16.out
- tsl/test/shared/sql/gapfill.sql.in
With PG16, group pathkeys can include column which are not in the GROUP BY clause when dealing with ordered aggregates. This means we have to exclude those columns when checking and creating the gapfill custom scan subpath.
Fixes #6396
> Fix groupby pathkeys for gapfill in PG16

- tsl/test/expected/bgw_db_scheduler_fixed.out
- tsl/test/expected/job_errors_permissions.out
- tsl/test/expected/scheduler_fixed.out
- tsl/test/sql/bgw_db_scheduler_fixed.sql
- tsl/test/sql/job_errors_permissions.sql
- tsl/test/sql/scheduler_fixed.sql
Speed up bgw tests by reducing the amount of time we wait in pg_sleep.
> Speed up bgw scheduler tests

- .github/gh_matrix_builder.py
- .github/workflows/linux-build-and-test.yaml
The latest OpenSSL 3.2.0 version has known issues with Postgres. MacOSX
CI runs were failing because of this. We now use macos-13 visavis the
earlier macos-11. That seems to solve this OpenSSL issue.
> Fix OpenSSL issues by using latest MacOSx

- tsl/src/compression/compression.c
The -Werror,-Wunused-but-set-variable parameters while compiling on MacOSx were causing compilation to fail on CI. Fixed that now.
> Remove warning on MacOSx

- test/sql/updates/post.repair.cagg_joins.sql
The update test fails on PG13 on the statement
`\d+ cagg_joins_upgrade_test_with_realtime_using` with the error message `ERROR:  invalid memory alloc request size 13877216128`.
To unblock CI and allow other PRs to get merged we temporarily skip the offending query on PG13.
> Disable failing cagg query on PG13 update test

- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/compression_sorted_merge_distinct.out
- tsl/test/sql/compression_sorted_merge_distinct.sql
Also remove a leftover debug print.
> Fix integer overflow in batch sorted merge costs

- tsl/src/continuous_aggs/common.h
- tsl/src/continuous_aggs/finalize.c
This data structure is a leftover of 78490c47 where we removed the support for creating Continuous Aggregate in the old format.
> Remove useless AggPartCxt data structure

- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/decompress_test_impl.c
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
This is a refactoring to enable bulk decompression of array and dictionary compressed text columns, but not other types. Currently has no effect.
> Make the bulk decompression function depend on PG type

- .github/gh_matrix_builder.py
- .github/workflows/linux-build-and-test.yaml
- scripts/upload_ci_stats.sh
- test/sql/updates/post.repair.cagg_joins.sql
This is necessary in order to get the CI to function properly on the 2.13.x branch
> Backport CI fixes to 2.13.x branch

- .unreleased/fix_6428
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/expected/compression_update_delete.out
- tsl/test/sql/compression_update_delete.sql
Prior to version 2.8, compressed chunks had a different format for indexing. This change attempts to find the best index it can actually use during scanning of compressed data and moves filters around based on the selected index. If no index exists, it should fallback to doing a sequencial scan.
Fixes #6367
> Fix index matching during DML decompression

- .unreleased/pr_6439
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/shared/expected/security_barrier.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/security_barrier.sql
Before this patch we required the user to have select permissions on the compressed chunks in addition to permissions on the hypertable. This patch changes our code to not require permission on the compressed chunk when querying through the uncompressed hypertable or chunk similar to how we handle this on PG < 16. This fixes views with security_barrier that have constraints on the user.
Fixes: #6425
> Fix permission handling for compressed chunks on PG16

- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/nodes/decompress_chunk/CMakeLists.txt
- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/decompress_context.h
- tsl/src/nodes/decompress_chunk/detoaster.c
- tsl/src/nodes/decompress_chunk/detoaster.h
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/test/expected/compressed_detoaster.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compressed_detoaster.sql
The normal Postgres detoasting code locks and opens toast tables and indexes for each toast value, which can take a large percentage CPU time on simple queries. Since in decompression we're working with one table at a time, the toast table and index are the same for every datum, so we don't have to redo this work.
Gives up to 60% speedup on some queries to compressed hypertables: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=3012&var-run2=3018&var-threshold=0&var-use_historical_thresholds=true&var-threshold_expression=2.0%20*%20percentile_disc(0.90)&var-exact_suite_version=false
> Use a stateful detoaster for compressed data

- test/expected/bgw_launcher.out
- test/expected/pg_dump.out
- test/sql/bgw_launcher.sql
- test/sql/pg_dump.sql
During dropping of the database used in the various tests we can encounter an error if something is still connected to the database, making the output unpredicatable. This change should reduce the possibility of that happening.
> Fix flaky SQL test

- sql/notice.sql
Now we display it as WARNING and it makes it harder to grep the logs for failures such as broken memory contexts or tupdesc reference leaks, which are also reported as warnings.
> Display the welcome message as NOTICE

- test/expected/pg_dump.out
- test/sql/pg_dump.sql
During pg_dump creation of extra database, we terminate all processes connected to the template database but we don't revoke connection to it. This is why we still see random failures to create the new database.
> Fix pg_dump flakiness

- .github/workflows/linux-build-and-test.yaml
Most if not all commits have failed on the main branch due to macos-13 regression tests failing to upload test results to CI database. Switching to using libpq psql seems to fix the issue.
https://github.com/timescale/timescaledb/actions/workflows/linux-build-and-test.yaml?query=is%3Afailure+branch%3Amain
This PR success CI run: https://github.com/timescale/timescaledb/actions/runs/7276339952/job/19826008689?pr=6449
> Fix upload test results for macos regression CI 

- .unreleased/fix_6384
- src/guc.c
- tsl/test/expected/bgw_scheduler_control.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/bgw_scheduler_control.sql
Right now `bgw_log_level` requires `ALTER SYSTEM` since it is using `PGC_SIGHUP` but we want to make sure that it is possible to set the scheduler log level using `ALTER DATABASE` which allows it to be replicated and also allows the database owner to set the value rather than requiring superuser privileges or explicit grants.
Since we want to allow configuration to be reloaded without restarting the server, we are limited to `PGC_SUSET` and `PGC_SIGHUP`.
> Change bgw_log_level to use PGC_SUSET

- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/compressed_batch.h
This commit makes some mechanical changes to the tuple forming function make_next_tuple(), to prepare it for the subsequent introduction of bulk decompression for text columns. It also simplifies the layout of data for the compressed columns to contain less indirections. This is important because tuple forming is a hot function that we try to keep simple.
> Refactor tuple forming function for bulk decompression of text columns

- .unreleased/pr_6454
- src/indexing.c
- tsl/test/shared/expected/compress_unique_index.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/compress_unique_index.sql
RelationGetIndexAttrBitmap has a slightly different purpose then what we need here and does not return the correct result for us for expression indexes. This reverts commit a854b276.
Fixes #6302
> Fix unique index detection for compressed chunks

- src/chunk.c
- src/event_trigger.c
- src/event_trigger.h
- src/hypertable.c
- src/process_utility.c
- src/ts_catalog/compression_settings.c
- src/ts_catalog/compression_settings.h
- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/src/compression/create.c
- tsl/test/expected/compression_settings.out
- tsl/test/sql/CMakeLists.txt
- tsl/test/sql/compression_settings.sql
This patch materializes the hypertable compression configuration when the compressed chunk is created and adjusts the code to use the per chunk settings whenever working with compressed data. Allowing chunk settings to differ from hypertable settings will be implemented in a follow-up patch.
> Store per chunk compression settings

- tsl/src/continuous_aggs/materialize.c
- tsl/test/expected/cagg_refresh.out
In 38fcd1b we improved the cagg_watermark performance by storing it into a metadata table and update it during the refresh.
But we made a minor mistake here reading the watermark from the partial view instead of the already materialized data that should be much fast because we're reading already aggregated data.
Fixed this mistake by reading the watermark from the underlying materialization hypertable (already aggregated data).
> Read watermark from materialized data

- test/expected/pg_dump.out
- test/sql/pg_dump.sql
Another try to reduce the flakiness of this test. Previously added REVOKE CONNECT does not stop db owners or superusers connecting. Altering the database with allow_connections = off should stop everybody from connecting.
> Disallow database connection in pg_dump

- tsl/src/compression/compression.c
- tsl/test/shared/expected/compress_unique_index.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/compress_unique_index.sql
Previously for insert on hypertables with unique expression indexes we used to decompress full chunk as we would do no batch filtering in the dml compression. This patch adds batch filtering for columns that are part of an unique expression index but not filtered by an expression.
> Properly detect key columns for unique expression indexes

- tsl/src/continuous_aggs/repair.c
https://scan4.scan.coverity.com/reports.htm#v54116/p12995/fileInstanceId=143855089&defectInstanceId=14714889&mergedDefectId=384044 https://scan4.scan.coverity.com/reports.htm#v54116/p12995/fileInstanceId=143855089&defectInstanceId=14714890&mergedDefectId=378576
> Fix coverity scan logically dead code

- .github/workflows/linux-32bit-build-and-test.yaml
- .github/workflows/linux-build-and-test.yaml
- .github/workflows/sanitizer-build-and-test.yaml
We don't build the same configuration with different compilers for one commit, and the changes between commits are handled by the hash of `.github` subdirectory in the cache key.
> Remove unneded parameter from PG build cache keys

- .unreleased/fix_6465
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/shared/expected/transparent_decompress_chunk-16.out
- tsl/test/sql/transparent_decompression_queries.sql
In the function add_chunk_sorted_paths, we create sorted versions of the decompress paths. We construct a sort node and place it on top of the decompressed chunk to do this. However, the decompress chunk path will also be added to the relation via add_path. This function can recycle the provided path if better paths are already known. Therefore, we need our own private copy for the sorted paths.
> Fix use of freed path in decompression sort logic

- .github/gh_matrix_builder.py
- .github/workflows/linux-build-and-test.yaml
This patch changes the OpenSSL version for the OS X builds to 3.1.4,
since recent PostgreSQL versions contain a bug in the SSL handling and
crash on OS X when OpenSSL 3.2.0 is used.
See: https://github.com/Homebrew/homebrew-core/issues/155651
---
This also fixes the build problem in our 2.13.x branch
Link to current CI failures: https://github.com/timescale/timescaledb/actions/runs/7310652505/job/19919464262?pr=6467
Link to successful CI run in our 2.13.x branch: https://github.com/timescale/timescaledb/actions/runs/7314107994/job/19926391007?pr=6470
> Use OpenSSL 3.1.4 for OS X builds

- .github/workflows/linux-build-and-test.yaml
So far, we have analyzed the core dumps only on Linux. This patch adds some logic to get a stack trace on OS X.
--- 
###
Sample output: https://github.com/timescale/timescaledb/actions/runs/7313532618/job/19925218573?pr=6468
(Please check the raw output from the action, since we had a lot of core dumps, we also ran out of disk space during decoding and the GitHub UI does not show log outputs for incomplete steps in the UI.)
```
(lldb) target create --core "/cores/core.51370"
Core file '/cores/core.51370' (x86_64) was loaded.
(lldb) thread backtrace all
* thread #1
* frame #0: 0x00007ff80d8aa1e2 libsystem_kernel.dylib`__pthread_kill + 10
frame #1: 0x00007ff80d8e1ee6 libsystem_pthread.dylib`pthread_kill + 263
frame #2: 0x00007ff80d808b45 libsystem_c.dylib`abort + 123
frame #3: …
```
> Improve core dump handling on OS X

- .github/gh_matrix_builder.py
- .github/workflows/linux-build-and-test.yaml
This patch changes the OpenSSL version for the OS X builds to 3.1.4 since recent PostgreSQL versions contain a bug in the SSL handling and crash on OS X when OpenSSL 3.2.0 is used.
See: https://github.com/Homebrew/homebrew-core/issues/155651
> Backport to 2.13.x: Use OpenSSL 3.1.4 for OS X builds

- .unreleased/fix_6465
- tsl/src/nodes/decompress_chunk/decompress_chunk.c
- tsl/test/expected/transparent_decompression_queries.out
- tsl/test/shared/expected/transparent_decompress_chunk-16.out
- tsl/test/sql/transparent_decompression_queries.sql
In the function add_chunk_sorted_paths, we create sorted versions of the decompress paths. We construct a sort node and place it on top of the decompressed chunk to do this. However, the decompress chunk path will be also added to the relation via add_path. This function can recycle the provided path if better paths are already known. Therefore, we need our own private copy for the sorted paths.
> Backport to 2.13.x: Fix use of freed path in decompression sort logic

- .github/workflows/linux-build-and-test.yaml
(cherry picked from commit ffe8c768f07c3948e85f674fec414bd7efdf932b)
> Fix upload test results for macos regression CI

- .github/workflows/linux-build-and-test.yaml
Homebrew can change the installed Perl version. Therefore, the
installation of custom modules should be done after the last Homebrew
call.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/7380805733/job/20078592771
Link to fixed run: https://github.com/timescale/timescaledb/actions/runs/7384504062/job/20087581577?pr=6477
> Fix perl modules installation on OS X

- .github/workflows/linux-build-and-test.yaml
Homebrew can change the installed Perl version. Therefore, the installation of custom modules should be done after the last Homebrew call.
> Backport to 2.13.x: Fix perl modules installation on OS X

- .unreleased/fix_6443
- src/scanner.c
- src/scanner.h
- tsl/src/continuous_aggs/invalidation_threshold.c
- tsl/test/isolation/expected/cagg_concurrent_invalidation.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/cagg_concurrent_invalidation.spec
When two CAggs on the same hypertable are refreshed at the same type, we had a race condition on the invalidation threshold table occur.
So far, the table has been locked with a non-self-conflicting lock. Therefore, both scanners ran at the same time, but only one was able to lock the threshold value with a proper tuple lock. The other scanner ignored this failing lock and just returned. Therefore, the field computed_invalidation_threshold was never populated and still contains 0.
So, invalidation_threshold_set_or_get returns and refresh end interval of 0. As a consequence, the `if (refresh_window.start >= refresh_window.end)` branch in continuous_agg_refresh_internal could be taken and we return from the refresh without doing any work.
This patch adds proper error reporting and also …
> Fix lost concurrent CAgg updates

- tsl/src/compression/compression.c
- tsl/test/shared/expected/compress_unique_index.out
- tsl/test/shared/sql/CMakeLists.txt
- tsl/test/shared/sql/compress_unique_index.sql
Previously for insert on hypertables with unique expression indexes we used to decompress full chunk as we would do no batch filtering in the dml compression. This patch adds batch filtering for columns that are part of an unique expression index but not filtered by an expression.
> Properly detect key columns for expression indexes

- .unreleased/fix_6365
- .unreleased/fix_6377
- .unreleased/fix_6384
- .unreleased/fix_6393
- .unreleased/fix_6408
- .unreleased/fix_6428
- .unreleased/fix_6443
- .unreleased/fix_6465
- .unreleased/pr_6439
- .unreleased/pr_6454
- CHANGELOG.md
- cmake/GenerateScripts.cmake
- sql/CMakeLists.txt
- version.config
This release contains bug fixes since the 2.13.0 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* #6365 Use numrows_pre_compression in approximate row count
* #6377 Use processed group clauses in PG16
* #6384 Change bgw_log_level to use PGC_SUSET
* #6393 Disable vectorized sum for expressions.
* #6408 Fix groupby pathkeys for gapfill in PG16
* #6428 Fix index matching during DML decompression
* #6439 Fix compressed chunk permission handling on PG16
* #6443 Fix lost concurrent CAgg updates
* #6454 Fix unique expression indexes on compressed chunks
* #6465 Fix use of freed path in decompression sort logic
**Thanks**
* @MA-MacDonald for reporting an issue with gapfill in PG16
* @aarondglover for reporting an issue with unique expression indexes on …
> Release 2.13.1

- .github/workflows/linux-build-and-test.yaml
The OS X build currently fails with a brew link error for Python. This PR fixes the problem by allowing the overwriting of existing files in the Python install step.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/7458415023/job/20292684115?pr=6497
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/7458792901/job/20293479793?pr=6503
> Fix OS X build

- tsl/test/expected/cagg_errors.out
- tsl/test/expected/compressed_collation.out
- tsl/test/expected/reorder.out
- tsl/test/sql/cagg_errors.sql
- tsl/test/sql/compressed_collation.sql
- tsl/test/sql/reorder.sql
Adjust tests to not access columns in the compressed hypertable. While this is currently possible a followup patch will remove this functionality.
> Remove references to compressed hypertable internals from tests

- .github/workflows/changelog-check.yaml
So far, we have also checked the changelog files on our backport branch. However, the test always failed since the backported PR numbers did not match the changelog PR numbers. This PR disables the changelog check on the backport branch.
---
Link to failed CI run: https://github.com/timescale/timescaledb/actions/runs/7395253176/job/20118061456
> Disable changelog check for backports

- tsl/src/nodes/decompress_chunk/compressed_batch.c
- tsl/src/nodes/decompress_chunk/exec.c
- tsl/src/nodes/decompress_chunk/planner.c
- tsl/src/nodes/decompress_chunk/qual_pushdown.c
- tsl/src/nodes/decompress_chunk/vector_predicates.c
- tsl/src/nodes/decompress_chunk/vector_predicates.h
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/shared/expected/ordered_append-13.out
- tsl/test/shared/expected/ordered_append-14.out
- tsl/test/shared/expected/ordered_append-15.out
- tsl/test/shared/expected/ordered_append-16.out
- tsl/test/shared/expected/ordered_append_join-13.out
- tsl/test/shared/expected/ordered_append_join-14.out
- tsl/test/shared/expected/ordered_append_join-15.out
- tsl/test/shared/expected/ordered_append_join-16.out
- tsl/test/sql/decompress_vector_qual.sql
For checks like `variable IS (NOT) NULL`.
Up to 20% speedup on some queries we have in tsbench: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=3093&var-run2=3080&var-threshold=0&var-use_historical_thresholds=true&var-threshold_expression=2.5%20*%20percentile_cont(0.90)&var-exact_suite_version=false
> Vectorize NullTest

- .unreleased/fix_6507
- tsl/src/nodes/gapfill/gapfill_exec.c
- tsl/test/shared/expected/gapfill-13.out
- tsl/test/shared/expected/gapfill-14.out
- tsl/test/shared/expected/gapfill-15.out
- tsl/test/shared/expected/gapfill-16.out
- tsl/test/shared/sql/gapfill.sql.in
This change makes gapfill calculate timezone offsets like we do in time_bucket when there is a supplied timezone. Without this, timezones would not align and we get timestamp mismatches which cause double entries for a single bucket.
Fixes #6344
> Handle DST changes in gapfill

- src/planner/agg_bookend.c
- test/expected/agg_bookends.out
- test/expected/plan_expand_hypertable-13.out
- test/expected/plan_expand_hypertable-14.out
- test/expected/plan_expand_hypertable-15.out
- test/expected/plan_expand_hypertable-16.out
- tsl/test/shared/expected/ordered_append-13.out
- tsl/test/shared/expected/ordered_append-14.out
- tsl/test/shared/expected/ordered_append-15.out
- tsl/test/shared/expected/ordered_append-16.out
If we use NULLS LAST, we don't need the null test. This saves some CPU.
> Don't add unneded null test in sorted query plan for minmax

- .unreleased/fix_6509
- cmake/ScriptFiles.cmake
- sql/debug_build_utils.sql
- sql/debug_utils.sql
- sql/pre_install/schemas.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- src/extension.c
- test/expected/debug_utils.out
- test/sql/CMakeLists.txt
- test/sql/debug_utils.sql
- tsl/test/shared/expected/extension.out
The extension state is not easily accessible in release builds, which makes debugging issue with the loader very difficult. This commit introduces a new schema `timescaledb_debug` and makes the function `ts_extension_get_state` available also in release builds as `timescaledb_debug.extension_state`.
See #1682
> Make extension state available through function

- tsl/src/compression/compression.c
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/expected/compression.out
- tsl/test/expected/compression_sorted_merge-13.out
- tsl/test/expected/compression_sorted_merge-14.out
- tsl/test/expected/compression_sorted_merge-15.out
- tsl/test/expected/compression_sorted_merge-16.out
- tsl/test/expected/transparent_decompression_join_index-13.out
- tsl/test/expected/transparent_decompression_join_index-14.out
- tsl/test/expected/transparent_decompression_join_index-15.out
- tsl/test/expected/transparent_decompression_join_index-16.out
- tsl/test/shared/expected/decompress_tracking.out
- tsl/test/shared/sql/decompress_tracking.sql
- tsl/test/sql/agg_partials_pushdown.sql
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_sorted_merge.sql.in
- tsl/test/sql/transparent_decompression_join_index.sql.in
This speeds up the compression queries by 10% to 300%: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=3116&var-run2=3117&var-threshold=0&var-use_historical_thresholds=true&var-threshold_expression=2.5%20*%20percentile_cont(0.90)&var-exact_suite_version=false
Apparently we don't use the statistics on the uncompressed chunk anyway:
<details>
```
schemaname             │ _timescaledb_internal
tablename              │ _hyper_5_174_chunk
attname                │ country
inherited              │ f
null_frac              │ 0
avg_width              │ 13
n_distinct             │ 112
most_common_vals       │ {"GREATER LONDON","GREATER MANCHESTER","WEST YORKSHIRE","WEST …
```
> Don't analyze the uncompressed chunk before compressing it

- sql/updates/latest-dev.sql
Previously we would only check for data nodes defined or distributed hypertables being present which might not be true on data nodes so we prevent update on any installation that has dist_uuid defined which is also true on data nodes.
> Improve multinode detection in update script

- .github/workflows/libfuzzer.yaml
Fixes the package install failures: https://github.com/timescale/timescaledb/actions/runs/7500828565/job/20421673435
> Add apt update to libfuzzer workflow

- .unreleased/fix_6522
- src/process_utility.c
- tsl/test/expected/cagg_errors.out
- tsl/test/sql/cagg_errors.sql
We don't support triggers on CAggs yet. Disallow that explicitly till we support them later.
Fixes #6500
> Disallow triggers on CAggs

- src/guc.c
- tsl/test/expected/compression_settings.out
- tsl/test/sql/compression_settings.sql
We enabled scans using indexes for a chunk that is to be compressed. The theory was that avoding tuplesort will be a win if there's a matching index to the compression settings. However, a few customers have reported very slow compress timings with lots of disk usage. It's important to know which scan is being used for the compression in such cases to help debug the issue. There's an existing GUC parameter which was "DEBUG" only till now. Make it available in release builds as well.
> Enable debug info about compression scan paths

- .unreleased/bugfix_5688
- tsl/src/bgw_policy/compression_api.c
- tsl/src/bgw_policy/continuous_aggregate_api.c
- tsl/src/bgw_policy/policy_utils.c
- tsl/src/bgw_policy/policy_utils.h
- tsl/src/bgw_policy/retention_api.c
- tsl/test/expected/cagg_policy.out
- tsl/test/sql/cagg_policy.sql
> Fix if_not_exists behavior for CAgg policy with NULL offsets

- tsl/test/isolation/expected/parallel_compression.out
- tsl/test/isolation/specs/CMakeLists.txt
- tsl/test/isolation/specs/parallel_compression.spec
The changes for per chunk compression settings got rid of some locking that previously prevented compressing different chunks of the same hypertable. This patch just adds an isolation test for that functionality.
> Add isolation test for parallel compression

- .github/workflows/changelog-check.yaml
- .unreleased/fix-parameterized-time-bucket
- scripts/check_changelog_format.py
- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/exec.c
- src/planner/expand_hypertable.c
- src/planner/planner.c
- src/planner/planner.h
- test/expected/plan_expand_hypertable-13.out
- test/expected/plan_expand_hypertable-14.out
- test/expected/plan_expand_hypertable-15.out
- test/expected/plan_expand_hypertable-16.out
- test/sql/include/plan_expand_hypertable_query.sql
- tsl/test/shared/expected/constraint_exclusion_prepared.out
When time_bucket is compared to constant in WHERE, we also add condition on the underlying time variable (ts_transform_time_bucket_comparison). Unfortunately we only do this for plan-time constants, which prevents chunk exclusion when the interval is given by a query parameter, and a generic plan is used. This commit also tries to apply this optimization after applying the execution-time constants.
This PR also enables startup exclusion based on parameterized filters.
Fixes https://github.com/timescale/timescaledb/issues/6498
> Use parameterized time_bucket for chunk exclusion

- .github/workflows/issue-handling.yaml
If an issue is labeled with either `segfault` or `security`, send a
message to the security channel that the issue needs attention.
> Send message to security channel on segfault label

- .github/workflows/linux-build-and-test.yaml
Use Python 3.12 instead of 3.11 to avoid brew link error
with dependencies.
> Fix OSX build failure

- src/planner/expand_hypertable.c
- test/expected/plan_expand_hypertable-13.out
- test/expected/plan_expand_hypertable-14.out
- test/expected/plan_expand_hypertable-15.out
- test/expected/plan_expand_hypertable-16.out
- test/sql/include/plan_expand_hypertable_query.sql
Since the optional time_bucket arguments like offset, origin and timezone shift the output by at most bucket width we can optimize these similar to how we optimize the other time_bucket constraints.
Fixes #4825
> Support all time_bucket variants in plan time chunk exclusion

- .github/workflows/changelog-check.yaml
- scripts/check_changelog_format.py
Since #6505, the changelog script tries to access
`secrets.ORG_AUTOMATION_TOKEN`. However, accessing secrets is not possible
for PRs. This PR changes the token to the default access token, which is available in PRs
and provides read access to the issue API.
---
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/7613913110/job/20734963199?pr=6560
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/7610536985/job/20724062414?pr=6325
> Change GitHub token for changelog check

- sql/metadata.sql
- sql/pre_install/tables.sql
- sql/restoring.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- test/expected/metadata.out
- test/expected/pg_dump.out
- test/sql/metadata.sql
- test/sql/pg_dump.sql
- tsl/test/shared/expected/extension.out
This patch changes the dump configuration for
_timescaledb_catalog.metadata to include all entries. To allow loading logical dumps with this configuration an insert trigger is added that turns uniqueness conflicts into updates to not block the restore.
> Include _timescaledb_catalog.metadata in dumps

- src/process_utility.c
- tsl/test/expected/chunk_utils_internal.out
- tsl/test/sql/chunk_utils_internal.sql
The commit #6513 removed some restricted chunk operations, enabling adding constraints to OSM chunks directly. This operation is blocked on OSM chunks. The present commit ensures that adding a constraint directly on an OSM chunk is blocked.
> Fix OSM build failure

- tsl/src/nodes/decompress_chunk/pred_vector_const_arithmetic_all.c
- tsl/test/expected/decompress_vector_qual.out
- tsl/test/sql/decompress_vector_qual.sql
We didn't account for some permutations of types like comparing int4 to int2.
> Vectorize more arithmetic functions

- sql/pre_install/cache.sql
- sql/pre_install/tables.sql
- sql/updates/latest-dev.sql
- sql/updates/reverse-dev.sql
- test/expected/pg_dump.out
- test/expected/pg_dump_unprivileged.out
- test/sql/pg_dump.sql
- test/sql/pg_dump_unprivileged.sql
- test/sql/updates/post.catalog.sql
Logging and caching related tables from the timescaledb extension should not be dumped using pg_dump. Our scripts specify a few such unwanted tables. Apart from being unnecessary, the "job_errors" had some restricted permissions causing additional problems in pg_dump.
We now don't include such tables for dumping.
Fixes #5449
> Don't dump unnecessary extension tables

- .unreleased/pr_6545
- src/compression_with_clause.c
- src/compression_with_clause.h
- src/hypertable.c
- src/process_utility.c
- src/ts_catalog/compression_settings.c
- tsl/src/compression/api.c
- tsl/src/compression/compression_storage.c
- tsl/src/compression/create.c
- tsl/test/expected/cagg_ddl-13.out
- tsl/test/expected/cagg_ddl-14.out
- tsl/test/expected/cagg_ddl-15.out
- tsl/test/expected/cagg_ddl-16.out
- tsl/test/expected/cagg_errors.out
- tsl/test/expected/compression_ddl.out
- tsl/test/expected/compression_errors-13.out
- tsl/test/expected/compression_errors-14.out
- tsl/test/expected/compression_errors-15.out
- tsl/test/expected/compression_errors-16.out
- tsl/test/expected/compression_indexscan.out
- tsl/test/expected/compression_settings.out
- tsl/test/expected/continuous_aggs-13.out
- tsl/test/expected/continuous_aggs-14.out
- tsl/test/expected/continuous_aggs-15.out
- tsl/test/expected/continuous_aggs-16.out
- tsl/test/sql/compression_settings.sql
This patch removes the restrictions preventing changing compression settings when compressed chunks exist. Compression settings can now be changed at any time and will not affect existing compressed chunks but any subsequent compress_chunk will apply the changed settings. A decompress_chunk/compress_chunk cycle will also compress the chunk with the new settings.
> Remove restrictions for changing compression settings

- .unreleased/fix_6571
- src/nodes/chunk_append/chunk_append.c
- src/nodes/chunk_append/chunk_append.h
- src/planner/partialize.c
- tsl/src/nodes/skip_scan/planner.c
- tsl/test/expected/agg_partials_pushdown.out
- tsl/test/sql/agg_partials_pushdown.sql
The chunk-wise aggregation pushdown code creates a copy of the existing paths; it copies the existing paths to create new ones with pushed-down aggregates. However, the copy_merge_append_path function behaves differently than other copy functions (e.g., copy_append_path); it resets the pathtarget on the copy. This leads to a wrong pathlist and crashes. This PR fixes the wrong pathtarget by setting it after the path is copied.
> Fix pathtarget adjustment for MergeAppend paths

- tsl/src/compression/api.c
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
Refactor the compression to code to move the column map code in a separate function and change tsl_get_compressed_chunk_index_for_recompression to not initialize RowCompressor anymore.
> Refactor tsl_get_compressed_chunk_index_for_recompression

- .unreleased/fix_6494
- src/hypertable.c
- test/expected/create_hypertable.out
- test/sql/create_hypertable.sql
Foreign keys pointing to hypertables are not supported. Creating a
hypertable from a table referenced by foreign key succeeds, but it
leaves the referencing (child) table in a broken state, failing on every
insert with a `violates foreign key constraint` error.
To prevent this scenario, if a foreign key reference to the table exists
before converting it to a hypertable, the following error will be
raised:
```
cannot have FOREIGN KEY contraints to hypertable "<table_name>"
HINT: Remove all FOREIGN KEY constraints to table "<table_name>"
before making it a hypertable.
```
Fixes #6452
> Fix create_hypertable referenced by fk succeeds

- .unreleased/fix_6575
- src/cross_module_fn.h
- src/nodes/chunk_dispatch/chunk_dispatch.c
- src/nodes/chunk_dispatch/chunk_insert_state.c
- src/nodes/chunk_dispatch/chunk_insert_state.h
- tsl/src/compression/compression.c
- tsl/src/compression/compression.h
- tsl/test/isolation/expected/compression_recompress.out
- tsl/test/isolation/specs/compression_recompress.spec
When inserting into a compressed chunk with an ON CONFLICT clause, and there is a concurrent recompression of the chunk, an error can occur due to a failed lookup of the compressed chunk.
The error happens because the chunk information is re-read from an outdated cache holding a compressed chunk ID that no longer exists after the chunk was recompressed (recompression effectively removes the compressed chunk and creates it again).
Fix this issue by ensuring that the insert path only uses up-to-date chunk metadata read _after_ the lock on the chunk was taken.
Disable-Check: commit-count
> Fix compressed chunk not found during upserts

- .unreleased/pr_6579
- sql/maintenance_utils.sql
- tsl/test/expected/compression.out
- tsl/test/expected/compression_errors-13.out
- tsl/test/expected/compression_errors-14.out
- tsl/test/expected/compression_errors-15.out
- tsl/test/expected/compression_errors-16.out
- tsl/test/isolation/expected/compression_ddl_iso.out
- tsl/test/isolation/specs/compression_ddl_iso.spec
- tsl/test/sql/compression.sql
- tsl/test/sql/compression_errors.sql.in
This patch changes those functions to no longer error by default when the chunk is not the expected state, instead a warning is raised. This is in preparation for changing compress_chunk to forward to the appropriate operation depending on the chunk state.
> Change boolean default value for compress_chunk and decompress_chunk

- .github/ci_settings.py
- .github/workflows/linux-build-and-test.yaml
Issues due to OpenSSL 3.2 seem to be resolved via components
installing 3.1.x. So, remove our temporary changes.
We also disable uploading of test stats till the next minor release
of PG on macOS.
> Fix openssl issues on MacOSX on CI

- .github/workflows/pgspot.yaml
Use pgspot 0.7.0 in our CI which updates the parser used by pgspot to the PG16 parser.
> Bump pgspot to 0.7.0

- src/time_bucket.c
The variable origin in ts_timestamptz_bucket was initialized two times. This commit removes one of the initializations.
---
> Remove double initialization of time_bucket origin
