sql/policy_internal.sql
tsl/test/expected/bgw_custom-13.out
tsl/test/expected/bgw_custom-14.out
tsl/test/expected/bgw_custom-15.out
tsl/test/expected/bgw_custom-16.out
tsl/test/expected/read_only.out

In #4770 we changed the behavior of compression policies to continue compressing chunks even if a failure happens in one of them.
The problem is if a failure happens in one or all the chunks the job is marked as successful, and this is wrong because a failure happens so if an exception occurs when compressing chunks we'll raise an exception at the end of the procedure in order to mark the job as failed.

Properly set job failure on compression policies

---

.unreleased/pr_6592
tsl/src/bgw_policy/job.c
tsl/src/compression/api.c
tsl/test/expected/compression_bgw-13.out
tsl/test/expected/compression_bgw-14.out
tsl/test/expected/compression_bgw-15.out
tsl/test/expected/compression_bgw-16.out

The recompression policy only recompresses unordered chunks which will be rarely created but does not deal with partial chunks which are the result of DML operations into compressed chunks.

Fix recompression ignoring partial compressed chunks

---

tsl/src/nodes/skip_scan/planner.c

Improve the error message when we encounter unexpected node types by printing the node name instead of the node id.

Improve SkipScan unsupported node type error message

---

.github/workflows/sqlsmith.yaml
tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/exec.c
tsl/src/nodes/decompress_chunk/exec.h
tsl/test/expected/decompress_vector_qual.out
tsl/test/sql/decompress_vector_qual.sql

We had this handling for top-level AND, but not for deeper boolean expressions. Make it general.
Found by SQLSmith: https://github.com/timescale/timescaledb/actions/runs/7750432562/job/21136641284

Fix handling of expressions evaluated to Const in OR

---

src/chunk.c
src/chunk.h
tsl/src/bgw_policy/job.c
tsl/src/compression/api.c
tsl/src/compression/api.h
tsl/test/expected/compression_ddl.out
tsl/test/expected/compression_insert.out
tsl/test/expected/decompress_vector_qual.out
tsl/test/isolation/expected/compression_recompress.out

This patch changes compress_chunk to recompress partial or unordered chunks so the result of compress_chunk will always be a fully compressed chunk.

Change compress_chunk to recompress partial and unordered chunks when needed

---

tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/test/expected/compression_bgw-13.out
tsl/test/expected/compression_bgw-14.out
tsl/test/expected/compression_bgw-15.out
tsl/test/expected/compression_bgw-16.out
tsl/test/expected/compression_indexscan.out
tsl/test/sql/compression_indexscan.sql

Log progress of the compression/decompression APIs into the postgresql
log file. In case of issues in the field, we really do not have much
idea about which stage the compression function is stuck at. Hopefully
we will have a better idea now with these log messages in place. We
want to keep things simple and enable logging of the progress by
default for these APIs. We can relook if the users complaint about the
chattiness later.

Report progress in compression related APIs

---

src/utils.c

https://scan4.scan.coverity.com/#/project-view/54116/12995?selectedIssue=414714

Fix coverityscan logically dead code

---

.unreleased/fix_6610
src/planner/expand_hypertable.c
src/process_utility.c

If the comparison function for qsort is non-transitive, there is a risk of out-of-bounds access. Subtraction of integers can lead to overflows, so instead use a real comparison function.

Ensure qsort comparison function is transitive

---

.github/workflows/apt-packages.yaml
.github/workflows/rpm-packages.yaml

Since we now have multiple versions packaged for PG16 we can enable the downgrade test in our apt and rpm package test.

Don't disable downgrade test on PG16

---

.unreleased/pr_6608
src/bgw/launcher_interface.c
src/loader/bgw_interface.c
src/loader/lwlocks.c
src/loader/lwlocks.h
test/expected/loader-tsl.out
test/src/loader/osm_init.c

Modify the loader to add a LWLock for OSM code.

Add LWLock for OSM usage in loader

---

tsl/test/shared/expected/transparent_decompress_chunk-13.out
tsl/test/shared/expected/transparent_decompress_chunk-14.out
tsl/test/shared/expected/transparent_decompress_chunk-15.out
tsl/test/shared/expected/transparent_decompress_chunk-16.out
tsl/test/shared/sql/transparent_decompress_chunk.sql.in

Change more queries to run EXPLAIN without ANALYZE to make the test less flaky due to different parallelization.

Make transparent_decompress_chunk test less flaky

---

test/expected/pg_dump_unprivileged.out
test/sql/CMakeLists.txt

pg_dump_unprivileged.sql was fixed by an upstream change to pg_dump in 13.14, 14.11, 15.6, and 16.2

Adjust pg_dump_unprivileged test to only run on versions with fixed pg_dump

---

.github/workflows/abi.yaml
.github/workflows/libfuzzer.yaml
.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
.github/workflows/sanitizer-build-and-test.yaml
.github/workflows/sqlsmith.yaml
.github/workflows/windows-build-and-test.yaml
scripts/upload_ci_stats.sh
test/postgresql.conf.in
test/test-defs.cmake
tsl/test/postgresql.conf.in

SQLSmith finds many internal program errors (`elog`, code `XX000`). Normally these errors shouldn't be triggered by user actions and indicate a bug in the program (like `variable not found in subplan targetlist`). We don't have a capacity to fix all of them currently, especially since some of them seem to be the upstream ones. This commit adds logging for these errors so that we at least can study the current situation.

Log internal program errors to CI database

---

src/compat/compat.h
src/event_trigger.c
src/utils.h
tsl/src/bgw_policy/job.c
tsl/src/partialize_finalize.c

The last caller for this was removed as part of multinode removal.

Remove unused function get_vacuum_options

---

CMakeLists.txt

Helps to investigate errors where a wrong PG version gets picked.
Related to https://github.com/timescale/timescaledb/issues/6474

Report the PG version and path before complaining it's incorrect

---

src/guc.c
tsl/test/expected/compression_bgw-13.out
tsl/test/expected/compression_bgw-14.out
tsl/test/expected/compression_bgw-15.out
tsl/test/expected/compression_bgw-16.out
tsl/test/expected/compression_indexscan.out
tsl/test/sql/compression_indexscan.sql

The current code would always prefer indexscan over tuplesort while doing scans of the rows from the chunk that was being compressed. The thinking was that we'd avoid doing a sort via the indexscan. The theory looked good on paper, but from various cloud customer reports we have seen that the random access of the heap pages via the indexscan was typically more expensive than doing the tuplesort. So we disable the default indexscan till we get better usecases warranting enabling it again for all scenarios. Specific use cases can enable the timescaledb.enable_compression_indexscan manually if desired.

Disable default indexscan for compression

---

.unreleased/pr_6636
sql/updates/2.13.1--2.14.0.sql
test/sql/updates/post.compression.sql
test/sql/updates/setup.compression.sql

Fixes https://github.com/timescale/timescaledb/issues/6633

Fix update script for tables with dropped columns

---

.unreleased/pr_6630
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
sql/views.sql
test/expected/pg_dump.out
tsl/test/expected/compression_settings.out
tsl/test/sql/compression_settings.sql

This patch adds 2 new views hypertable_compression_settings and chunk_compression_settings to query the per chunk compression settings.

Add compression settings informational view

---

.github/ci_settings.py
.github/workflows/linux-build-and-test.yaml
.github/workflows/update-test.yaml

Use newly released 13.14, 14.11, 15.6 and 16.2 in CI.

Bump PG versions used in CI

---

src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h

This commit removes the unused function ts_number_of_continuous_aggs.
---

Remove function ts_number_of_continuous_aggs

---

src/debug_assert.h

Since conditions used with `Ensure` are not expected to fire except in rare circumstances, we should always treat this as unlikely.

Use "unlikely" with Ensure

---

src/guc.c
src/guc.h

Leftover GUC `ts_guc_max_insert_batch_size` from multinode removal.

Remove multinode related GUC

---

sql/updates/2.14.0--2.13.1.sql

While the downgrade script doesnt combine multiple version into a single script since we only create the script for the previous version, fixing this will make backporting in the release branch easier.

Fix downgrade script to make backports easier

---

src/adts/bit_array.h
src/adts/bit_array_impl.h
src/adts/vec.h
test/src/adt_tests.c
tsl/src/compression/gorilla.c
tsl/src/compression/simple8b_rle.h

Memory operations can add up to tens of percents of the total
compression CPU load. To reduce the need for them, reserve for the
expected array sizes when initializing the compressor.
Based on measurements in this issue: https://github.com/timescale/Support-Dev-Collab/issues/1498#issuecomment-1936607692
We don't have a dataset which reproduces it well in tsbench, but I think it's a safe change anyway: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=3238&var-run2=3239&var-threshold=0.02&var-use_historical_thresholds=true&var-threshold_expression=2.5%20%2A%20percentile_cont%280.90%29&var-exact_suite_version=true

Avoid excessive reallocation in row compressors 

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
.github/workflows/sanitizer-build-and-test.yaml
.github/workflows/windows-build-and-test.yaml

This commit updates the following workflows that used Node.js 16 to a newer version that uses Node.js 20:
* actions/cache
* codecov/codecov-action
* Vampire/setup-wsl
----

Update GitHub actions to Node.js 20

---

.unreleased/pr_6655
tsl/src/continuous_aggs/utils.c
tsl/test/expected/cagg_utils.out
tsl/test/sql/cagg_utils.sql

With the input to pg_parse_query does not contain anything to parse it will return NIL. This patch adds a check for NIL to prevent the segfault that would otherwise happen later in the code.
Fixes: #6625

Fix segfault in cagg_validate_query

---

tsl/src/continuous_aggs/insert.c

This commit fixes a misleading error message when we get more than one invalidation threshold message for a continuous aggregate.
---

Fix misleading watermark threshold error message

---

coccinelle/attrnumbergetattroffset.cocci
src/dimension.c
src/ts_catalog/continuous_agg.c
src/utils.c

Postgres has `AttrNumberGetAttrOffset()` macro to proper access Datum array members, so added a new coccinele static analysis to check for missing macro usage.
Example:
`datum[attrno - 1]` should be `datum[AttrNumberGetAttrOffset(attrno)]`
Reference:
* https://github.com/postgres/postgres/blob/master/src/include/access/attnum.h)

Add coccinele checking for AttrNumberGetAttrOffset

---

.unreleased/pr_6621
sql/cagg_migrate.sql
sql/maintenance_utils.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/chunk.c
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
test/sql/updates/post.catalog.sql
tsl/test/expected/cagg_ddl-13.out
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_migrate.out
tsl/test/expected/cagg_usage-13.out
tsl/test/expected/cagg_usage-14.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/expected/compression.out
tsl/test/expected/compression_bgw-13.out
tsl/test/expected/compression_bgw-14.out
tsl/test/expected/compression_bgw-15.out
tsl/test/expected/compression_bgw-16.out
tsl/test/shared/expected/extension.out
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/cagg_usage.sql.in
tsl/test/sql/compression_bgw.sql.in
tsl/test/sql/include/cagg_migrate_common.sql

Historically we preserve chunk metadata because the old format of the
Continuous Aggregate has the `chunk_id` column in the materialization
hypertable so in order to don't have chunk ids left over there we just
mark it as dropped when dropping chunks.
In #4269 we introduced a new Continuous Aggregate format that don't
store the `chunk_id` in the materialization hypertable anymore so it's
safe to also remove the metadata when dropping chunk and all associated
Continuous Aggregates are in the new format.
Also added a post-update SQL script to cleanup unnecessary dropped chunk
metadata in our catalog.
Closes #6570

Remove metadata when dropping chunk

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
src/ts_catalog/catalog.c
src/ts_catalog/catalog.h
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/repair.c
tsl/src/continuous_aggs/repair.h
tsl/src/init.c
tsl/test/expected/cagg_utils.out
tsl/test/expected/exp_cagg_monthly.out
tsl/test/expected/exp_cagg_next_gen.out
tsl/test/expected/exp_cagg_timezone.out
tsl/test/sql/cagg_utils.sql
tsl/test/sql/exp_cagg_monthly.sql
tsl/test/sql/exp_cagg_next_gen.sql
tsl/test/sql/exp_cagg_timezone.sql

The catalog table continuous_aggs_bucket_function is currently only used for variable bucket sizes. Information about the fixed-size buckets is stored in the table continuous_agg only. This causes some problems (e.g., we have redundant fields for the bucket_size, fixes size buckets with offsets are not supported, ...).
This commit is the first in a row of commits that refactor the catalog for the CAgg time_bucket function. The goals are:
* Remove the CAgg redundant attributes in the catalog 
* Create an entry in continuous_aggs_bucket_function for all CAggs that use time_bucket
This first commit refactors the continuous_aggs_bucket_function table and prepares it for more generic use. Not all attributes are used yet, but these will change in follow-up PRs.
---
Should be merged after: …

Make CAgg time_bucket catalog table more generic

---

sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/create.c
tsl/test/expected/exp_cagg_origin.out
tsl/test/sql/exp_cagg_origin.sql

So far, bucket_origin was defined as a Timestamp but used as a
TimestampTz in many places. This commit changes this and unifies the
usage of the variable.
---
Should be merged after: https://github.com/timescale/timescaledb/pull/6624

Unify handling of CAgg bucket_origin

---

.unreleased/bugfix_6660
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/cagg_invalidation.out
tsl/test/sql/cagg_invalidation.sql

So far, we have not handled CAggs with variable buckets correctly. The CAgg refresh on a hypertable without any data lead to the error message "timestamp out of range". This patch fixes the problem by declaring empty CAggs as up-to-date.

Fix refresh on empty CAgg with variable bucket

---

sql/policy_internal.sql
src/chunk.c
tsl/src/chunk.c
tsl/src/compression/compression.c
tsl/test/expected/compression_errors-13.out
tsl/test/expected/compression_errors-14.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/sql/compression_errors.sql.in

This patch filters out the osm chunk in the compression policy and adds some additional checks so we dont run compress_chunk on osm chunks.

Don't try to compress osm chunks

---

.github/workflows/pr-handling.yaml

The job assigning PR needs write permissions and the pull requests to function.

Grant write permissions to pr handling workflow

---

coccinelle/namedata.cocci
src/bgw/job.c
src/chunk.c
src/dimension.c
src/hypertable.c
src/ts_catalog/continuous_agg.c

This PR replaces memcpy calls on NameData with namestrcpy. In addition, a Coccinelle rule is introduced to detect these problems automatically.
---

Replace memcpy on NameData with namestrcpy

---

tsl/src/nodes/decompress_chunk/batch_array.c
tsl/src/nodes/decompress_chunk/batch_queue_fifo.h
tsl/src/nodes/decompress_chunk/batch_queue_heap.c
tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/compressed_batch.h
tsl/src/nodes/decompress_chunk/decompress_context.h

This simplifies passing the columnar data out of the DecompressChunk to Vectorized Aggregation node which we plan to implement. Also this should improve memory locality and bring us closer to the architecture used in TAM for ArrowTupleSlot.

Use data inheritance from VirtualTupleTableSlot in compressed batch

---

test/runner_isolation.sh
tsl/test/isolation/expected/cagg_watermark_concurrent_update.out
tsl/test/isolation/expected/cagg_watermark_concurrent_update_1.out

This patch makes the isolation tests more robust by replacing chunk IDs with X. So, even if the chunk ID changes, the tests will not fail.
---

Make isolation tests more robust

---

.unreleased/bugfix_6677
test/runner_isolation.sh
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/insert.c
tsl/src/continuous_aggs/invalidation_threshold.c
tsl/test/isolation/expected/cagg_concurrent_invalidation.out
tsl/test/isolation/expected/cagg_watermark_concurrent_update.out
tsl/test/isolation/expected/cagg_watermark_concurrent_update_1.out
tsl/test/isolation/specs/cagg_concurrent_invalidation.spec

So far, the scanner in `get_lowest_invalidated_time_for_hypertable()` used a Snapshot that includes the data of all committed transactions (and not only the transactions that are started before the snapshot was created - `SNAPSHOT_SELF`). This could lead to a situation where we see the old and the new value of a parallel updated tuple. Since `get_lowest_invalidated_time_for_hypertable() `expects exactly one tuple to be found during the scan, we end up with an error. Since this is performed in our insert path (i.e., it is executed by the invalidation trigger), this error could reject inserts on the hypertable (`ERROR: more than one invalidation watermark found`).
---
Should be merged after: https://github.com/timescale/timescaledb/pull/6678

Fix snapshot usage in CAgg invalidation scanner

---

src/debug_assert.h

PR #6648 introduces a branch prediction in the Ensure macro. However, the checked condition needs to be negated to be unlikely. Therefore, the check predicts the branch likelihood wrongly. In other words, reporting an error in Ensure should be the unlikely case, and the condition should be fulfilled in most calls. This commit fixes the branch prediction.
---

Fix branch prediction in Ensure

---

src/nodes/chunk_append/transform.c
src/nodes/chunk_append/transform.h
tsl/src/nodes/decompress_chunk/planner.c
tsl/test/expected/decompress_vector_qual.out
tsl/test/expected/transparent_decompression_queries.out
tsl/test/sql/decompress_vector_qual.sql

Apply the same approach we use for chunk exclusion: try to cast the constant to the same type.

Vectorize cross-datatype timestamp comparisons

---

sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/create.c
tsl/test/expected/exp_cagg_monthly.out
tsl/test/sql/exp_cagg_monthly.sql

Historically, we have used an empty string for undefined values in the catalog table continuous_aggs_bucket_function. Since #6624, the optional arguments can be NULL. This patch cleans up the empty strings and changes the logic to work with NULL values.
---

Use NULL in CAgg bucket function catalog table

---

.unreleased/pr_6698
sql/updates/latest-dev.sql
src/bgw/job.c
tsl/src/bgw_policy/compression_api.c
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/job_api.c
tsl/src/bgw_policy/job_api.h
tsl/src/bgw_policy/reorder_api.c
tsl/test/expected/bgw_db_scheduler.out
tsl/test/sql/bgw_db_scheduler.sql

So far, we have not differentiated between 0 and -1 retries of a job. -1 was defined as an infinite number of retries. The behavior of 0 was not well defined and also handled as an infinite number of retries. This commit defines 0 as no retries.
Fixes: #6691
--
Docs PR: https://github.com/timescale/docs/pull/3028

Define meaning of 0 retries for jobs as no retries

---

.github/workflows/linux-32bit-build-and-test.yaml

The CI workflow for i386 test was missing the schedule trigger. Therefore, no scheduled builds are performed, and the status badge of our README file returns an "unknown" status.
---

Add missing schedule trigger for i386 test

---

tsl/test/expected/bgw_db_scheduler.out
tsl/test/sql/bgw_db_scheduler.sql

When the tests wait for a scheduler run that spans multiple wakeup cycles, the amount of scheduler wakeups is not deterministic. This commit adds filters for the logfile to avoid failing tests due to a different number of scheduler wakeups.
--
Link to failed CI runs: 
https://github.com/timescale/timescaledb/actions/runs/8050436144/job/21986044894
https://github.com/timescale/timescaledb/actions/runs/8050436144/job/21986047758

Make bgw_db_scheduler test more predictable

---

src/dimension.c
src/dimension.h
tsl/test/expected/hypertable_generalization.out
tsl/test/sql/hypertable_generalization.sql

The SQL data type _timescaledb_internal.dimension_info is declared with INTERNALLENGTH = VARIABLE. This requires a varlen header, which was missing. Therefore, the needed space of the function result was not handled properly. This commit introduces the missing header.
---
Found by SQLSmith: https://github.com/timescale/timescaledb/actions/runs/8058580265/job/22011569432
```sql
smith=# update public.metrics_compressed set 
smith-#   time = public.metrics_compressed.time, 
smith-#   device_id = pg_catalog.btint42cmp(
smith(#     cast(public.metrics_compressed.v1 as int4),
smith(#     cast(case when (cast(null as box) >^ cast(null as box)) 
smith(#         and ((select schedule_interval from timescaledb_experimental.policies limit 1 offset 3)
smith(# …
```

Fix missing varlen header in DimensionInfo

---

.github/workflows/backport.yaml

The GitHub token only provides read-only access per default since a few days. This PR adjusts the backport workflow to request the write permissions for the repository.
--
Failed CI runs: https://github.com/timescale/timescaledb/actions/workflows/backport.yaml
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/8077881034/job/22069053250?pr=6706

Add write permissions for the backport workflow

---

.unreleased/bugfix_6717
src/copy.c
src/nodes/chunk_dispatch/chunk_dispatch.h
src/nodes/chunk_dispatch/chunk_insert_state.c
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

The dispatch_state of ChunkDispatch was not set in the COPY path (see
the definition of ChunkDispatch). However, it was accessed to count the
number of decompressed tuples. This PR creates the needed state and
introduces a missing check for the amount of decompressed tuples.

Fix handling of compressed tables in COPY path

---

.github/workflows/windows-build-and-test.yaml

The PG server sometimes needs longer than 30 seconds to start up. This commit changes the wait interval to 60 seconds to give the server more time to respond to connections.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/8109148666/job/22163746540

Increase PG startup time on windows

---

.unreleased/pr_6726
tsl/src/continuous_aggs/planner.c
tsl/test/expected/cagg_watermark-13.out
tsl/test/expected/cagg_watermark-14.out
tsl/test/expected/cagg_watermark-15.out
tsl/test/expected/cagg_watermark-16.out
tsl/test/sql/cagg_watermark.sql.in

When querying a realtime Continuous Aggregate using window functions the new planner optimization to constify the `cagg_watermark` function call is not working because we're checking for window function usage on the query tree but actually this is a current limitation when creating a new Continuous Aggregate, but users can use window functions when querying it.
Fixed it by removing the check for `query->hasWindowFuncs` to prevent the process of constification of the `cagg_watermak` function call.
Fixes #6722

Fix constify cagg_watermark using window functions

---

.unreleased/bugfix_6729
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/continuous_aggregate_api.h
tsl/src/bgw_policy/job.c
tsl/test/expected/cagg_invalidation.out
tsl/test/sql/cagg_invalidation.sql

The CAgg refresh job did not handle the `NULL` value of `start_offset` for a `time_bucket` function with a variable width properly. This problem has led to the creation of invalid invalidation records and 'timestamp out of range' errors during the next refresh.
Fixes: #5474

Fix NULL start value handling in CAgg refresh

---

.unreleased/bugfix_6732
sql/cagg_migrate.sql
tsl/test/expected/cagg_migrate.out
tsl/test/sql/cagg_migrate.sql
tsl/test/sql/include/cagg_migrate_custom_timezone.sql

The CAgg migration path contained two bugs. This PR fixes both. A typo in the column type prevented 'timestamp with time zone' buckets from being handled properly. In addition, a custom setting of the datestyle could create errors during the parsing of the generated timestamp values.
Fixes: #5359

Fix CAgg migration with custom settings

---

.github/workflows/linux-build-and-test.yaml

Setting the HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 when using `brew
install` will turn off the automatic dependency upgrade when using this command.
Reference:
https://docs.brew.sh/Manpage#install-options-formulacask-
---
CI failure:
https://github.com/timescale/timescaledb/actions/runs/8162808777/job/22314629103?pr=6737

Disable homebrew automatic dependency upgrades

---

.github/workflows/pr-validation.yaml

It's convenient to squash the cleanup commits using the GitHub interface, but currently the PR validation prevents the squash merge from succeeding. Fix this.

Allow multi-commit PRs with squash auto-merge

---

tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/invalidation_threshold.c
tsl/src/continuous_aggs/refresh.c

Encapsulate the logic for getting the MINIMUM value of a time dimension for a Continuous Aggregate in a single place instead of spread the logic everywhere that can lead to wrong usage specially because there are a difference between fixed and variable size buckets.

Refactor returning time dimension MINIMUM value

---

src/bgw/job.c
tsl/src/bgw_policy/job_api.c

Instead of checking an invalid hypertable id against an arbitrary integer number (in this case zero) use the existing constant INVALID_HYPERTABLE_ID.

Use INVALID_HYPERTABLE_ID constant when necessary

---

src/utils.c
src/utils.h
tsl/src/continuous_aggs/utils.c

When updating catalog tables we rely on low level functions instead of SQL statements and in order to read/write data from/to those tables we frequent do something like:
```CPP
Datum values[natts] = { 0 };
bool nulls[natts] = { false };
char *char_value = "foo";
if (char_value != NULL)
values[AttrNumberGetAttrOffset(text_value_offset)] =
PointerGetDatum(cstring_to_text(char_value);
else
null[AttrNumberGetAttrOffset(char_value_offset)] = true;
```
So instead of using a pair of Datum and bool arrays we'll replace it by using arrays of `NullableDatum` that contains both members and introduce some accessor functions to encapsulate the logic to fill the proper values, like:
```CPP
ts_datum_set_text(int index, NullableDatum *datums, text *value);
ts_datum_set_bool(int index, NullableDatum …
```

Add handler functions for Datum/Bools arrays

---

.github/workflows/issue-handling.yaml

The wrong path was used with `contains()`.

Fixing security issue printing

---

coccinelle/mcxt.cocci
src/telemetry/telemetry.c

If memory context is switched temporarily and there is no switch back, it will cause strange errors.
This adds a Coccinelle rule that checks for a case where the memory context is saved in a temporary variable but this variable is not used to switch back to the original memory context.

Check for missing memory context switch back

---

.unreleased/fix_6617
src/chunk.c
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/test/expected/policy_generalization.out
tsl/test/sql/policy_generalization.sql

If "created_after/before" is used with a "time" type partitioning column then show_chunks was not showing appropriate list due to a mismatch in the comparison of the "creation_time" metadata (which is stored as a timestamptz) with the internally converted epoch based input argument value. This is now fixed by not doing the unnecessary conversion into the internal format for cases where it's not needed.
Fixes #6611

Fix error in show_chunks

---

.unreleased/bugfix_6752
sql/updates/latest-dev.sql

In old TSDB versions, we disabled autovacuum for compressed chunks to keep the statistics. However, this restriction was removed in #5118, but no migration was performed to reset the custom autovacuum setting for existing chunks.

Remove autovacuum setting from compressed chunks

---

src/guc.c
src/guc.h
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/cagg_invalidation.out
tsl/test/sql/cagg_invalidation.sql

PR #2926 introduced a session-based configuration parameter for the CAgg refresh behavior. If more individual refreshes have to be carried out than specified by this setting, a refresh for a larger window is performed.
It is mentioned in the original PR that this setting should be converted into a GUC later. This PR performs the proposed change.
---
BGW tests are contained in: #6756

Convert max materializations setting to GUC

---

tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_bgw-13.out
tsl/test/expected/cagg_bgw-14.out
tsl/test/expected/cagg_bgw-15.out
tsl/test/expected/cagg_bgw-16.out
tsl/test/expected/cagg_refresh.out
tsl/test/sql/cagg_bgw.sql.in

Currently, when a CAgg is refreshed using a background worker, only the refresh invocation is logged. However, the details of the refresh, such as the number of individual ranges that are refreshed, are not logged. This PR changes the log level for these details in background workers to INFO, to ensure the information is captured.
---
Should be merged after: #6740

Log CAgg refresh details in BGW

---

tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_errors.out

When creating a Continuous Aggregate we can only reference the primary hypertable dimension column on the `time_bucket` function, so reworded a bit the error message to be more clear.

Make CAgg error message more clear

---

tsl/src/compression/create.c

PR #6705 introduces the function is_sparse_index_type. However, it is only used for assert checking. If no assets are checked, the function is unused, and some compilers error out. This PR includes the function only if asserts are checked.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/8263661782/job/22605588883
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/8264499578/job/22608227365?pr=6764

Exclude is_sparse_index_type in non assert builds

---

tsl/test/sql/CMakeLists.txt

The cagg_invalidation test [stops](https://github.com/timescale/timescaledb/blob/8dcb6eed993b06e6fbb6703bfcb54a61b23d692d/tsl/test/sql/cagg_invalidation.sql#L5) the background workers and performs
tests with invalidations. However, they the test was running in a
parallel group, and background workers could be activated by other
tests, leading to flaky test behavior. This PR moves the
cagg_invalidation tests to the solo tests.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/8264761038/job/22611014318, https://github.com/timescale/timescaledb/actions/runs/8264761038/job/22611013928
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/8267219857/job/22617100451?pr=6765, …

Move cagg_invalidation to solo tests

---

tsl/src/bgw_policy/continuous_aggregate_api.c

PR #6737 introduced a new function to determine the min value for a given data type. This patch uses the function in a further place.
---

Unify dimension min handling

---

scripts/test_update_smoke.sh

Related to Issue https://github.com/timescale/eng-database/issues/565
So, we no more need update-test-patch for dev-cloud update pre-release tests.

Remove multinode reference from update smoke test.

---

.github/gh_matrix_builder.py

It is not possible to get anything sensible out of core dumps that do not contain debug info, so make sure that release builds are built with debug information by using `RelWithDebInfo`.

Build release builds with debug info

---

.github/workflows/linux-build-and-test.yaml

Backport of Fabrizio's commit: https://github.com/timescale/timescaledb/commit/b719787aa66e16433172d73ec02c16ec39b81e52 To 2.14.x branch.
Setting the HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 when using brew install will turn off the automatic dependency upgrade when using this command.
Reference:
https://docs.brew.sh/Manpage#install-options-formulacask-
CI failure:
https://github.com/timescale/timescaledb/actions/runs/8277163080/job/22649592824?pr=6769

Backport to 2.14.x: #6738: Disable homebrew automatic dependency upgrades

---

src/chunk.c
tsl/src/continuous_aggs/utils.c
tsl/test/expected/chunk_utils_internal.out
tsl/test/expected/compression_errors-13.out
tsl/test/expected/compression_errors-14.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/sql/chunk_utils_internal.sql
tsl/test/sql/compression_errors.sql.in

Fix show_chunks to not to show the OSM chunk. In passing, also fix a compilation error on macOS.

Don't show osm chunk via show_chunks

---

tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/refresh.c

So far, the invalidation_state_init function used a loop to find the proper CAgg bucket function. This PR refactors the parameter of the function and passes the needed information directly.
---

Refactor parameter of invalidation_state_init

---

.github/workflows/windows-build-and-test.yaml

We were not uploading the correct Postgres log to the CI artifacts, so
fixed it by setting the TEST_PG_LOG_DIRECTORY when building the
extension and using it properly when uploading the postmaster.log
artifact.

Fix uploading Postgres log on Windows CI

---

test/runner.sh
test/sql/utils/testsupport.sql
tsl/test/expected/bgw_custom-13.out
tsl/test/expected/bgw_custom-14.out
tsl/test/expected/bgw_custom-15.out
tsl/test/expected/bgw_custom-16.out
tsl/test/expected/cagg_bgw-13.out
tsl/test/expected/cagg_bgw-14.out
tsl/test/expected/cagg_bgw-15.out
tsl/test/expected/cagg_bgw-16.out
tsl/test/expected/scheduler_fixed.out
tsl/test/sql/bgw_custom.sql.in
tsl/test/sql/cagg_bgw.sql.in
tsl/test/sql/scheduler_fixed.sql

Several scheduler regression tests create the plpgsql function `wait_for_job_to_run` with the same purpose of waiting for a given job to execute or fail, so refactor the regression tests by adding it to the testsupport.sql library.

Add wait_for_job_to_run to testsupport.sql

---

.unreleased/bugfix_6789
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/compression_update_delete.out
tsl/test/sql/compression_update_delete.sql

For UPDATEs and DELETEs when a compressed chunk is involved, the code decompresses the relevant data into the uncompressed portion of the chunk. This happens during execution, so it's possible that if the planner doesn't have a plan for the uncompressed chunk then we might miss scanning out on those decompressed rows. We now check for the possibility of a compressed chunk becoming partial during the planning itself and tag on an APPEND plan on top of scans on the compressed and uncompressed parts.

Fix deletes with subqueries and compression

---

tsl/src/nodes/decompress_chunk/pred_text.c

This include will pull in header files from ICU which would result in ICU being a build requirement for timescaledb.

Remove unneeded pg_locale.h include

---

.unreleased/bugfix_6796
src/nodes/chunk_append/chunk_append.c
test/expected/chunk_utils.out
test/sql/chunk_utils.sql

The logic in chunk append path creation when a space dimension was involved was crashing while checking for matches in the flattened out children chunk lists. This has been fixed now.

Fix a crash involving a view on a hypertable

---

.unreleased/feature_6382
src/func_cache.c
src/time_bucket.c
src/time_bucket.h
src/ts_catalog/continuous_agg.c
src/utils.h
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/materialize.h
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_ddl-13.out
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_query.out
tsl/test/expected/cagg_usage-13.out
tsl/test/expected/cagg_usage-14.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/expected/cagg_utils.out
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/cagg_errors.sql
tsl/test/sql/cagg_query.sql
tsl/test/sql/cagg_usage.sql.in

So far, we allowed only CAggs without origin or offset parameters in the 
time_bucket definition. This commit adds support for the remaining
time_bucket variants.
Fixes #2265, Fixes #5453, Fixes #5828
---
* Allow additional time_bucket variants
* Enhance time_bucket query parsing in CAgg code to capture offset/origin properly
* Align refresh window
* Call proper time_bucket functions (offset and origin are handled by different implementations)
* Restrict use of broken time_bucket queries (i.e., variable bucket with offset)
```[tasklist]
```

Support for CAgg with time_bucket origin/offset parameter

---

tsl/src/continuous_aggs/common.c

The CAgg validation logic is quite complex. This PR adds two ensure() statements to the validation function to make it more clear (e.g., also for static code analyzers) that we expect a valid bucket function.
---

Add ensure calls to CAgg validation function

---

.unreleased/pr_6811
src/extension_utils.c

The GUC allow_install_without_preload allowed the installation of the extension without the preloaded loader in place. However, this way of installing TimescaleDB is not longer supported since we reuqest shared memory and rendezvous variables in the loader. This PR removes this deprecated way of installing TimescaleDB.

Remove allow_install_without_preload GUC

---

src/chunk.c

The found attribute is not used in release builds when Asserts are not evaluated. This leads to unused attributes and compiler errors. This PR fixes this problem by adding PG_USED_FOR_ASSERTS_ONLY to the variable declaration.
--
Broken CI run: https://github.com/timescale/timescaledb/actions/runs/8609324516/job/23593073324
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/8613071090/job/23603642548?pr=6812

Improve found attribute handling in release builds

---

.unreleased/pr_6798
src/func_cache.c
src/guc.c
src/guc.h
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_deprecated_bucket_ng.out
tsl/test/expected/cagg_query.out
tsl/test/expected/cagg_usage-13.out
tsl/test/expected/cagg_usage-14.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/expected/cagg_utils.out
tsl/test/expected/exp_cagg_monthly.out
tsl/test/expected/exp_cagg_next_gen.out
tsl/test/expected/exp_cagg_origin.out
tsl/test/expected/exp_cagg_timezone.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_deprecated_bucket_ng.sql
tsl/test/sql/cagg_utils.sql
tsl/test/sql/exp_cagg_monthly.sql
tsl/test/sql/exp_cagg_next_gen.sql
tsl/test/sql/exp_cagg_origin.sql
tsl/test/sql/exp_cagg_timezone.sql

The function timescaledb_experimental.time_bucket_ng() has been
deprecated for two years. This PR removes it from the list of bucketing
functions supported in a CAgg. Existing CAggs using this function will
still be supported; however, no new CAggs using this function can be
created.
---
I added a GUC, that is only available in debug builds (similar to `debug_require_batch_sorted_merge`), to allow the creation of CAggs using `time_bucket_ng`. This GUC allows it to prove that existing CAggs using this bucket function continue to work. In addition, this GUC can be used in a further PR to introduce and test migration steps.

Prevent usage of time_bucket_ng in CAgg definition

---

.unreleased/fix_6816
src/chunk_scan.c
test/expected/catalog_corruption.out
test/sql/CMakeLists.txt
test/sql/catalog_corruption.sql

When a catalog corruption occurs, and a chunk does not contain any dimension slices, we crash in ts_dimension_slice_cmp(). This patch adds a proper check and errors out before the code path is called.

Fix handling of chunks with no dimension slices

---

.unreleased/fix_6820
src/hypertable.c
test/expected/triggers.out
test/sql/triggers.sql

The ts_hypertable_insert_blocker function was accessing data from the trigger context before it was tested that a trigger context actually exists. This led to a crash when the function was called directly.
Fixes: #6819

Check for trigger context before accessing data

---

.github/codespell-ignore-words
.github/workflows/code_style.yaml

It is not possible to automatically backport pull requests that makes modifications to workflow files and since the codespell action has a hard-coded list of ignored words as options, this means that any changes to the ignored codespell words cannot be backported.
This pull request fixes this by using a ignore words file instead, which means that adding new words does not require changing a workflow file and hence the pull requests can be automatically backported.

Use ignore words file with codespell

---

.github/workflows/code_style.yaml
.unreleased/pr_6810
src/jsonb_utils.c
src/jsonb_utils.h
src/telemetry/telemetry.c
test/expected/telemetry.out
test/sql/telemetry.sql

Add telemetry for tracking access methods used, number of pages for each access method, and number of instances using each access method.
Also introduces a type-based function `ts_jsonb_set_value_by_type` that can generate correct JSONB based on the PostgreSQL type. It will generate "bare" values for numerics, and strings for anything else using the output function for the type.
To test this for string values, we update `ts_jsonb_add_interval` to use this new function, which is calling the output function for the type, just like `ts_jsonb_set_value_by_type`.

Backport of: Add telemetry for access methods

---

scripts/backport.py

We were always looking at the referenced issue number in the timescaledb repo, which is incorrect.

Fix backport script when PR references an issue from another repo

---

.unreleased/pr_6797
src/chunk.c
src/chunk.h
tsl/src/compression/api.c
tsl/test/expected/compression.out
tsl/test/expected/compression_fks.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression_fks.sql

When foreign key support for compressed chunks was added we moved
the FK constraint from the uncompressed chunk to the compressed chunk as
part of compress_chunk and moved it back as part of decompress_chunk.
With the addition of partially compressed chunks in 2.10.x this approach
was no longer sufficient and the FK constraint needs to be present on
both the uncompressed and the compressed chunk.
While this patch will fix future compressed chunks a migration has to be
run after upgrading timescaledb to migrate existing chunks affected by
this.
The following code will fix any affected hypertables:
```
CREATE OR REPLACE FUNCTION pg_temp.constraint_columns(regclass, int2[]) RETURNS text[] AS
$$
SELECT array_agg(attname) FROM unnest($2) un(attnum) LEFT JOIN pg_attribute att ON att.attrelid=$1 …
```

Fix FK constraints for compressed chunks

---

src/ts_catalog/continuous_aggs_watermark.c

Since #6325 we constify the watermark value of a CAgg during planning time. Therefore, the planner calls the watermark function only once. This PR removes the old code to cache the watermark value and speed up multiple calls of the watermark function.
---
Tsbench does not show any CAgg related regressions: https://grafana.ops.savannah-dev.timescale.com/d/NdmLnOk4z/compare-benchmark-runs?orgId=1&var-branch=main&var-run1=3424&var-run2=3425&var-threshold=0.02

Remove CAgg watermark cache

---

src/planner/planner.c
test/test-defs.cmake
tsl/test/expected/chunk_utils_internal.out
tsl/test/sql/chunk_utils_internal.sql

Previously we only handled the case of OSM chunk expanded as a child of hypertable, so in the case of direct select it segfaulted while trying to access an fdw_private which is managed by OSM.

Correctly determine relation type of OSM chunk as standalone table

---

tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/repair.c
tsl/test/expected/exp_cagg_next_gen.out
tsl/test/sql/exp_cagg_next_gen.sql

PR #6798 prevents the usage of time_bucket_ng in CAgg definitions. However, flipping the real-time functionality should still be possible.
---

Allow changing real-time flag on deprecated CAggs

---

src/CMakeLists.txt
src/guc.c
src/guc.h
src/process_utility.c
src/tss_callbacks.c
src/tss_callbacks.h
test/expected/test_tss_callbacks.out
test/sql/CMakeLists.txt
test/sql/test_tss_callbacks.sql
test/src/CMakeLists.txt
test/src/test_tss_callbacks.c

Currently we finish the execution of some process utility statements and don't execute other hooks in the chain.
Because that reason neither `ts_stat_statements` and `pg_stat_statements` are able to track some utility statements, for example COPY ... FROM.
To be able to track it on `ts_stat_statements` we're introducing some callbacks in order to hook `pgss_store` from TimescaleDB and store information about the execution of those statements.
In this PR we're also adding a new GUC `enable_tss_callbacks=fase` to enable or disable the ability to hook `ts_stat_statements` from TimescaleDB.

Add ts_stat_statements callbacks

---

sql/updates/latest-dev.sql

In #6767 and #6831 we introduced the ability to track job execution history including succeeded and failed jobs.
We migrate records from the old `_timescaledb_internal.job_errors` to the new `_timescaledb_internal.bgw_job_stat_history` table but we miss to get the job information into the JSONB field where we store detailed information about the job execution.

Migrate missing job info to history table

---

src/bgw/job_stat_history.c
tsl/test/expected/bgw_job_stat_history.out
tsl/test/sql/bgw_job_stat_history.sql

When the `timescaledb.enable_job_execution_logging` is OFF we should track only errors but we're not saving the related PID.
Fixed it by using MyProcPid when inserting new tuple in `_timescaledb_internal.bgw_job_stat_history`.

Fix missing pid in job execution history

---

.unreleased/pr_6849
tsl/src/compression/compression.c
tsl/test/expected/compression_update_delete.out
tsl/test/sql/compression_update_delete.sql

Currently the additional metadata derived from index columns are only used for the qualifier pushdown in querying but not the decompression during compressed DML. This patch makes use of this metadata for compressed DML as well.

Use non-orderby compressed metadata in compressed DML

---

src/bgw/job.c
src/chunk.c

* INVALID_HYPERTABLE_ID
* INVALID_CHUNK_ID
* OidIsValid

Use proper macros to check for invalid objects

---

src/process_utility.c

The CAgg error hint regarding adding indexes to non-finalized CAggs was proposing to recreate the whole CAgg. However, pointing to the migration function should be the preferred method. This PR changes the error wording.
---

Update outdated CAgg error hint

---

src/chunk.c
src/chunk.h

This PR removes the unused ts_chunk_oid_cmp function.
---

Remove unused ts_chunk_oid_cmp function

---

CMakeLists.txt
timescaledb.control.in

All postgres versions supported by timescaledb support trusted extensions so we do no longer need the conditional in the control file.

Remove conditional for trusted in control file

---

tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/repair.c

We already have `ts_get_relation_relid` that have the same purpose of the `relation_oid` so removed it.

Remove `relation_oid` duplicated function

---

sql/updates/2.7.2--2.8.0.sql
src/hypertable.c

This commit removes an unused function that was used in MN setups to create distributed hypertables.
---

Remove MN leftover create distributed hypertable

---

tsl/src/continuous_aggs/utils.c

The function continuous_agg_migrate_to_time_bucket contains a variable that is used only for asserts. This PR marks this variable as PG_USED_FOR_ASSERTS_ONLY.
---
Failed CI run: https://github.com/timescale/timescaledb/actions/runs/8842109687/job/24280225015
Fixed CI run: https://github.com/timescale/timescaledb/actions/runs/8844950407/job/24287855023?pr=6864

Tag variable with PG_USED_FOR_ASSERTS_ONLY

---

.unreleased/feature_6865
src/process_utility.c
tsl/test/expected/cagg_ddl-13.out
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/sql/cagg_ddl.sql.in

In #5261 we cached the Continuous Aggregate watermark value in a metadata table to improve performance avoiding compute the watermark at planning time.
Manually DML operations on a CAgg are not recommended and instead the user should use the `refresh_continuous_aggregate` procedure. But we handle `TRUNCATE` over CAggs generating the necessary invalidation logs so make sense to also update the watermark.

Update the watermark when truncating a CAgg

---

.unreleased/pr_6867
src/ts_catalog/continuous_agg.c
tsl/test/expected/cagg_ddl-13.out
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/sql/cagg_ddl.sql.in

When deleting a cagg with compression on the materialization hypertable the compression settings for that hypertable would not get removed when dropping the cagg.
Fixes #6866

Clean up compression settings when deleting compressed cagg

---

.unreleased/pr_6869
tsl/src/compression/compression.c
tsl/test/expected/compression_update_delete.out
tsl/test/sql/compression_update_delete.sql

UPDATE/DELETE operations with constraints where the column is on the right side of the expression and the value on the left side e.g. 'a' > column were not handled correctly when operating on compressed chunks.

Fix compressed DML with constraints of form value OP column

---

.unreleased/pr_6870
tsl/src/nodes/decompress_chunk/qual_pushdown.c
tsl/test/expected/compression_qualpushdown.out
tsl/test/expected/transparent_decompression-13.out
tsl/test/expected/transparent_decompression-14.out
tsl/test/expected/transparent_decompression-15.out
tsl/test/expected/transparent_decompression-16.out
tsl/test/shared/expected/transparent_decompress_chunk-13.out
tsl/test/shared/expected/transparent_decompress_chunk-14.out
tsl/test/shared/expected/transparent_decompress_chunk-15.out
tsl/test/shared/expected/transparent_decompress_chunk-16.out
tsl/test/sql/compression_qualpushdown.sql

`NOT column` or `column = false` result in different expressions than other boolean expressions which were not handled in the qual pushdown code. This patch enables pushdown for these expressions and also enables pushdown for OR expressions on compressed chunks.

Fix bool expression pushdown for queries on compressed chunks

---

.github/workflows/changelog-check.yaml
.unreleased/template.release_notes.j2
scripts/merge_changelogs.sh

This PR introduce the release notes header template using Jinja [1]. Also improved the script to merge changelogs to include the upcoming .unreleased/RELEASE_NOTES_HEADER.md.j2 where we'll actually write the release notes header for the next release.

Introduce release notes header template

---

sql/job_stat_history_log_retention.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
tsl/test/expected/bgw_custom-13.out
tsl/test/expected/bgw_custom-14.out
tsl/test/expected/bgw_custom-15.out
tsl/test/expected/bgw_custom-16.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/expected/bgw_policy.out
tsl/test/expected/telemetry_stats-13.out
tsl/test/expected/telemetry_stats-14.out
tsl/test/expected/telemetry_stats-15.out
tsl/test/expected/telemetry_stats-16.out
tsl/test/sql/bgw_custom.sql.in
tsl/test/sql/bgw_job_stat_history_errors.sql
tsl/test/sql/bgw_policy.sql

We must not reuse job ids of system jobs as that will create problems when updating as system jobs are not dumped and will be recreated during extension update.

Don't reuse job id

---

tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/test/expected/exp_cagg_monthly.out
tsl/test/sql/exp_cagg_monthly.sql

When adding a CAgg refresh policy using `start_offset => '2 months'` and `end_offset => '0 months'` was failing because the policy refresh window is too small and it should cover at least two buckets in the valid time range of timestamptz.
The problem was when calculating the bucket width for the variable bucket size (like months) we're assuming 31 days for each month but when converting the end offset to integer using `interval_to_int64` we use 30 days per month. Fixed it by aligning the variable bucket size calculation to also use 30 days.

Fix policy refresh window too small

---

src/ts_catalog/compression_settings.c

Use ObjectId datum functions in compression settings instead of int32 functions when storing `regclass` types.
Also fix a minor issue where an array for Datum information was using the wrong size.

Fix use of ObjectId datums in compression settings

---

.unreleased/pr_6895
tsl/src/compression/compression.c
tsl/test/expected/compression_update_delete.out
tsl/test/sql/compression_update_delete.sql

Try to constify query constraints when filtering batches to cover
a wider range of expressions that are safe to evaluate when we
do the batch filtering.
This will allow the following expressions to be usable with
compressed DML batch filtering:
- IMMUTABLE and STABLE functions
- SQLValueFunction (CURRENT_TIME,CURRENT_USER,LOCAL_TIME,...)
- Prepared Statement parameters

Improve compressed DML expression pushdown

---

.unreleased/pr_6880
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/test/expected/compression_update_delete.out
tsl/test/sql/compression_update_delete.sql

Add support for array operations to compressed DML

---

.github/workflows/release_build_packages.yml

The bitnami docker image generation has been split into dedicated workflow and is no longer part of the docker image workflow so we have to trigger it explicitly.

Add bitnami docker workflow

---

.unreleased/pr_6908
tsl/src/nodes/gapfill/gapfill_exec.c
tsl/test/shared/expected/gapfill-13.out
tsl/test/shared/expected/gapfill-14.out
tsl/test/shared/expected/gapfill-15.out
tsl/test/shared/expected/gapfill-16.out
tsl/test/shared/sql/gapfill.sql.in

When advancing local time we might not actually advance the timestamp we process e.g. when we switch to DST in spring the local time advances by 1 hour but the UTC time stays the same. Therefore we need to keep advancing until we actually move forward.
Fixes: #6788

Fix gapfill behaviour around dst switches

---

.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml

Since 2.15.0 is the first version available we can't do downgrade test until we released an additional version on that platform.

Skip downgrade test for Ubuntu 24.04

---

src/telemetry/telemetry.c
tsl/test/expected/telemetry_stats.out

In #6767 we introduced the track job execution history and renamed the `policy_job_error_retention` to `policy_job_stat_history_retention` but we forgot to adapt the telemetry to identify this change.
Fixes #6898

Fix telemetry stats regression test

---

test/sql/utils/testsupport.sql
tsl/test/expected/telemetry_stats.out

In #6907 we supposed to fix the telemetry stats regression test flakiness but unfortutanely it was not enough.
What happens is when the regression test runner setup the database for regression tests be executed we stop the scheduler and if for some reason a system job is running then it will be killed and it produces records on `bgw_job_stat` and `bgw_job_stat_history` with the crash information that can potentially lead to flaky test output.
To prevent it we cleanup system job stats metadata table just after stop the scheduler.

Fix flaky telemetry stats regression tests

---

tsl/src/continuous_aggs/repair.c
tsl/test/expected/cagg_utils.out
tsl/test/sql/cagg_utils.sql

In #6624 we refactored time_bucket catalog table to be more generic and introduced the `cagg_get_bucket_function` to inspect the query tree of a given Continuous Aggregate and return the time_bucket function oid.
The problem with the implementation is we traverse the whole query tree looking for `FuncExpr` and in certain cases we can have two different `time_bucket` function definition but what matters is the correct and valid `time_bucket` function that is part of the `Query->groupClause`.
Fixed it by inspecting only the `Query->groupClause` items looking for a valid time bucket `FuncExpr` and return it `Oid`.

Fix accessor function cagg_get_bucket_function

---

src/process_utility.c
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_invalidation.out
tsl/test/expected/cagg_on_cagg.out
tsl/test/expected/cagg_on_cagg_joins.out
tsl/test/sql/cagg_ddl.sql.in

When truncating a regular hypertable all chunks are removed but for some reason it don't happen when truncating a continuous aggregate.
Improved it by removing the underlying materialization hypertable chunks when truncating a continuous aggregate.

Remove chunks when truncating a CAgg

---

src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/create.c

Inside `CAggTimebucketInfo` data structure we're using several properties that actually is also part of `ContinuousAggsBucketFunction`, so refactor the code to use it and remove the properties redundancy.

Refactor CAggTimeBucketInfo to remove redundancy

---

.unreleased/pr_6911
sql/maintenance_utils.sql
sql/updates/2.14.2--2.15.0.sql

The removal function would only remove chunk_constraints that are part of dimension constraints. This patch changes it to remove all constraints of a chunk.
Fixes #6905

Fix _timescaledb_functions.remove_dropped_chunk_metadata

---

src/nodes/chunk_append/chunk_append.h
src/nodes/chunk_append/exec.c

`ts_constify_restrictinfos` and `ts_constify_restrictinfo_params` are useful functions for OSM to implement runtime chunk exclusion. This PR makes them visible from outside the library so that OSM could find and reuse them.

Make constification functions visible outside timescale library

---

src/copy.c
src/nodes/chunk_dispatch/chunk_dispatch.c
src/nodes/chunk_dispatch/chunk_dispatch.h
tsl/src/compression/compression.c
tsl/test/expected/compress_dml_copy.out
tsl/test/expected/compression_insert.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compress_dml_copy.sql
tsl/test/sql/compression_insert.sql

We don't have to decompress anything more when we re-lookup the chunk insert state on COPY buffer flush. Moreover, `ChunkInsertState.slots[0]` is incorrect slot type for `decompress_batches_for_insert()`, because it is a chunk slot, not a hypertable slot. This can lead to rare errors when the chunk insert states go out of cache.
Just don't do this unnecessary lookup, and move decompression to a separate function for clarity. Add an assertion and test that detect the slot type mismatch on main.
There was a related fix that improved the situation for empty copy buffers, but not for wrong slot type https://github.com/timescale/timescaledb/pull/6117
Fixes https://github.com/timescale/timescaledb/issues/6540

Do not decompress batches for COPY with potentially invalid slot

---

.unreleased/fix_compressed_copy_segfault

We didn't have changelog check in the required ones, I added it now.
Fixes #6540

Add missed changelog message for COPY segfault fix

---

tsl/src/nodes/decompress_chunk/qual_pushdown.c
tsl/test/expected/compression_qualpushdown.out
tsl/test/expected/transparent_decompression-14.out
tsl/test/expected/transparent_decompression-15.out
tsl/test/expected/transparent_decompression-16.out
tsl/test/shared/expected/transparent_decompress_chunk-14.out
tsl/test/shared/expected/transparent_decompress_chunk-15.out
tsl/test/shared/expected/transparent_decompress_chunk-16.out
tsl/test/sql/compression_qualpushdown.sql

To fix the original problem, it is enough to call
eval_const_expressions() to normalize the nested AND boolexprs.
This is a follow-up to #6917

Re-enable compressed OR boolexpr pushdown

---

src/compat/compat-msvc-enter.h
src/compat/compat-msvc-exit.h
src/extension.c
src/loader/loader.c
src/planner/add_hashagg.c
src/planner/planner.c

Some of the fixes are no longer needed and it is completely fixed
upstream in PG15+.
Disable-check: loader-change

Simplify msvc compat stuff

---

.github/codespell-ignore-words
.github/workflows/code_style.yaml
cmake/GenerateScripts.cmake
cmake/ScriptFiles.cmake
scripts/backport.py
scripts/export_prefix_check.sh.in
tsl/src/continuous_aggs/repair.c
tsl/test/shared/sql/CMakeLists.txt
tsl/test/t/003_mvcc_cagg.pl

(cherry picked from commit 2a3a471bb711c79c59f4d9e9b9062cd61d4aa6a1)

Backport to 2.15.x: #6953: Silence codespell check

---

.github/workflows/code_style.yaml
.github/workflows/pg_upgrade-test.yaml
scripts/test_pg_upgrade.py
test/sql/updates/post.pg_upgrade.sql

It's long we need to have binary upgrade tests in our CI. One example is https://github.com/timescale/timescaledb/issues/6935 (and others) that can be prevented if we have such kind of test in our CI.
To implement the `pg_upgrade` test we used the python Testing Framework for PostgreSQL (https://github.com/postgrespro/testgres).
Unfortunately the testing framework don't have the ability to retain the pg_upgrade log files after a successful execution, then we created a PR to make it possible and we'll use this patched version until we get the code merged and released on upstream.
postgrespro/testgres#125
Closes #3868 #4428

Add pg_upgrade test to CI

---

tsl/src/continuous_aggs/common.c

While the coverity warning is a false positive since rte->relkind is always either RELKIND_RELATION or RELKIND_VIEW this might not hold always true. This patch changes the if check to an Ensure and removes some nesting in the function.

Fix coverity warning about null pointer dereference

---

.unreleased/pr_6957
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/shared/expected/transparent_decompress_chunk-14.out
tsl/test/shared/expected/transparent_decompress_chunk-15.out
tsl/test/shared/expected/transparent_decompress_chunk-16.out
tsl/test/shared/sql/transparent_decompress_chunk.sql.in

We can't just filter the equivalence member based on em_is_child as our hypertable might not be top-level equivalence member.
Fixes #6925

Fix segfault in UNION queries with top-level ordering

---

.github/workflows/catalog-updates-check.yaml
scripts/check_updates_ast.py

We have to be careful with the column types we use in our catalog to only allow types that are safe to use in catalog tables and not cause problems during extension upgrade, pg_upgrade or dump/restore.

Add check for column types we use in our catalog.

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
.unreleased/pr_6920
src/guc.c
src/guc.h
tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/src/compression/wal_utils.h
tsl/test/t/002_logrepl_decomp_marker.pl

- Adds WAL markers around all compression and decompression activities.
- Renames the GUC controlling this behaviour.
- Enables the WAL marker GUC by default.
This allows to distinguish between "user-driven" and
"compression-driven" DML on uncompressed chunks. This is a requirement
to be able to support DML on compressed chunks in live migration.
Note: A previous commit [1] added wal markers before and after inserts
which were part of "transparent decompression". Transparent
decompression is triggered when an UPDATE or DELETE statement affects
compressed data, or an INSERT statment inserts into a range of
compressed data which has a unique or primary key constraint. In these
cases, the data is first moved from the compressed chunk to the
uncompressed chunk, and then the DML is applied. …

Rework compression activity wal markers

---

.unreleased/pr_6978
src/subspace_store.c
tsl/src/compression/api.c
tsl/test/expected/compression_merge.out
tsl/test/sql/compression_merge.sql

With the new hypertable API hypertables can be created with primary space partition. In dev-builds this was prevented with Asserts. This patch removes the Asserts and adds a proper check.
Fixes #6977

Fix segfault on non-open primary dimension when compressing

---

src/dimension_slice.c
src/dimension_slice.h
src/hypertable.c

Use the same logic as PR 6773 while updating dimension slice catalog tuples. PR 6773 addresses chunk catalog updates. We first lock the tuple and then modify the values and update the locked tuple. Replace ts_dimension_slice_update_by_id with field specific APIs and use dimension_slice_update_catalog_tuple calls consistently.

Modify dimension slice catalog update API

---

.unreleased/pr_6992
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/merge_append_partially_compressed-14.out
tsl/test/expected/merge_append_partially_compressed-15.out
tsl/test/expected/merge_append_partially_compressed-16.out
tsl/test/sql/merge_append_partially_compressed.sql.in

Using all sort pathkeys with append node for partially compressed chunks ends up creating invalid plans when using joined columns in ORDER BY clause. Using the pathkey prefix that belongs to the underlying relation fixes the issue and sets us up for possible incremental sort optimization.
Fixes #6975

Fix sort pushdown for partially compressed chunks

---

src/debug_assert.h
src/dimension_slice.c

Also make Ensure use all its argument even in debug mode, so that these things are easier to notice.
The problem was introduced by https://github.com/timescale/timescaledb/pull/6838

Fix stale code in Ensure

---

.unreleased/pr_6996
sql/maintenance_utils.sql
sql/updates/2.14.2--2.15.0.sql
tsl/test/expected/cagg_migrate.out
tsl/test/sql/cagg_migrate.sql

Changing the code to remove the assumption of 1:1
mapping between chunks and chunk constraints. Including
a check if a chunk constraint is shared with another chunk.
In that case, skip deleting the dimension slice.
Fixes #6976 

Fix removal of metadata function and update script

---

.unreleased/pr_6992
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/merge_append_partially_compressed-13.out
tsl/test/expected/merge_append_partially_compressed-14.out
tsl/test/expected/merge_append_partially_compressed-15.out
tsl/test/expected/merge_append_partially_compressed-16.out
tsl/test/sql/merge_append_partially_compressed.sql.in

Using all sort pathkeys with append node for partially compressed chunks ends up creating invalid plans when using joined columns in ORDER BY clause. Using the pathkey prefix that belongs to the underlying relation fixes the issue and sets us up for possible incremental sort optimization.
(cherry picked from commit eb548b60d1cc9bc5874cafdf2508a00694d6a44c)

Backport to 2.15.x: #6992: Fix sort pushdown for partially compressed chunks

---

.github/gh_matrix_builder.py

When building the CI matrix we create a list of ignored tests that are known to be flaky but the logic was wrong leading to an empty `IGNORES` variable when running the regression.
https://github.com/timescale/timescaledb/actions/runs/9310783691

Fix broken CI build matrix

---

tsl/src/continuous_aggs/common.c

The new hypertable API allows create it with primary space partition and CAggs doesn't support hypertables with custom partition functions.
Fixed the segfault by properly checking if there are an open dimension available during the validation.

Fix segfault creating CAgg on hypertable by hash

---

tsl/src/compression/create.c

While it is no longer possible to create this checking return value of hyperspace_get_open_dimension should still not be neglected.
Fixes #6983 

Fix segfault with closed primary dimension

---

src/chunk.c

Using the new hypertable API creating closed dimentions when partitioning by hash was leading to a segfault on show_chunks.
Fixed it by checking for the closed primary dimension and erroring out in case of using parameters `older_than` and `newer_than`.

Fix show_chunks on hypertable by hash

---

tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_query.out
tsl/test/expected/cagg_usage-14.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/cagg_query.sql
tsl/test/sql/cagg_usage.sql.in

On 2.15.x we added complete support of CAggs using time bucket with origin and/or offset, but we restrict the creating when the bucked size is variable due to some uncertaing regarding monthly buckets.
When bucketing by month we always align with the beginning of the month even defining an origin with day component. So to be consistent with the current implementation we'll not change this behavior and allow it to be used in Continuous Aggregates.

Allow CAggs with variable sized bucked with origin/offset

---

.github/workflows/linux-32bit-build-and-test.yaml

The `bgw_db_scheduler*` are known to be a bit flaky and the results are ignored in normal Linux/MacOS CI but currently Linux32bit don't use the gh_matrix_builder.py so those tests are not added by default.

Add known flaky tests to linux32bit CI

---

src/ts_catalog/continuous_agg.h
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/create.c
tsl/test/expected/cagg_ddl-13.out
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_query.out
tsl/test/expected/cagg_usage-13.out
tsl/test/expected/cagg_usage-14.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/cagg_query.sql
tsl/test/sql/cagg_usage.sql.in

On 2.15.x we added complete support of CAggs using time bucket with origin and/or offset, but we restrict the creating when the bucked size is variable due to some uncertaing regarding monthly buckets.
When bucketing by month we always align with the beginning of the month even defining an origin with day component. So to be consistent with the current implementation we'll not change this behavior and allow it to be used in Continuous Aggregates.
In order to make less painful the manual backport we also backported #6939

Backport to 2.15.x: #7005: Allow CAggs with variable sized bucked with origin/offset

---

.unreleased/RELEASE_NOTES_HEADER.md.j2
.unreleased/pr_6978
.unreleased/pr_6992
.unreleased/pr_6993
.unreleased/pr_6996
.unreleased/template.release_notes_header.j2
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains performance improvements and bug fixes since the 2.15.1 release. Best practice is to upgrade at the next available opportunity.
**Bugfixes**
* #6975: Fix sort pushdown for partially compressed chunks.
* #6976: Fix removal of metadata function and the update script.
* #6978: Fix segfault in compress_chunk with primary space partition.
* #6993: Disallow hash partitioning on the primary column.
**Thanks**
* @gugu for reporting the issue with catalog corruption due to update.
* @srieding for reporting the issue with partially compressed chunks and ordering on joined columns.

Release 2.15.2

---

test/expected/drop_extension.out
test/sql/drop_extension.sql

In this regression test we check the `DROP SCHEMA public CASCADE;` for removing the extension objects stored in that schema. The problem is if at the same moment we're running a background job it will lead to a deadlock because the scheduler maintain information about each execution in the metadata tables that should be part of the cascade schema removal.
Forced stop the background jobs and also terminate any running job.
https://github.com/timescale/timescaledb/actions/runs/9424506293/job/25964852620

Reduce drop_extension test flakiness

---

src/process_utility.c
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/sql/cagg_ddl.sql.in

Unfortunately the code-path for `ALTER TABLE...{RENAME | SET SCHEMA}` over a Continuous Aggregate was not handled very well in the process utility hook leading to a catalog corruption because it was not updating properly the internal metadata information.
Fixed it by properly update the catalog information.

Fix catalog corruption on Continuous Aggregate

---

tsl/test/expected/bgw_job_stat_history.out
tsl/test/sql/bgw_job_stat_history.sql

Removed the unecessary `start/stop` background workers during the test execution to avoid canceling any ongoing job execution leading to non-deterministic status checks.
https://github.com/timescale/timescaledb/actions/runs/9491560936/job/26157244186

Reduce bgw_job_stat_history test flakiness

---

src/hypertable.c

Planner attempts acquiring a `LockTupleKeyShare` tuple lock on an OSM chunk's dimension slice which results in an error on 
replica. This patch fixes the issue by avoiding tuple locking when in recovery mode.
Fix for timescale/Support-Dev-Collab#1847

Fix ERROR when acquiring a tuple lock on OSM chunks on replica

---

.unreleased/pr_6989
coccinelle/namedata.cocci
src/CMakeLists.txt
src/chunk_constraint.c
src/foreign_key.c
src/foreign_key.h
src/hypertable.c
src/planner/planner.c
src/process_utility.c
test/expected/constraint.out
test/expected/create_table.out
test/expected/rowsecurity-14.out
test/expected/rowsecurity-15.out
test/expected/rowsecurity-16.out
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/planner.c
tsl/test/expected/foreign_keys.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/foreign_keys.sql

Currrently we only allow Hypertables references other tables, with this patch the opposite direction is supported as well and tables can have foreign key references into hypertables.

Add support for foreign keys to hypertables

---

src/telemetry/replication.c
src/telemetry/telemetry.c
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/refresh.c

Change other places that lock down search_path to use RestrictSearchPath instead of SPI commands.

Use RestrictSearchPath to lock down search_path

---

.unreleased/pr_7046
tsl/src/nodes/decompress_chunk/exec.c
tsl/src/nodes/decompress_chunk/exec.h
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/decompress_chunk/planner.h
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/sql/compression_dml.sql

Error out when we detect that a scan is trying to lock compressed tuple. This does not block lock tuples on compressed hypertables in general but only errors for queries where actual compressed tuples would be returned. This will allow queries on compressed hypertables where compressed tuples are filtered by other means e.g. chunk exclusion or query constraints.
Not blocking this will produce a very misleading `Could not read block 0` error.

Prevent locking compressed tuples

---

.unreleased/fix_7055
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

When we decide to use an indexscan on the segment-by column for any query for decompression, then it's possible that the RHS constant type is not the same as the variable on the LHS of the comparison.
A typical example is "int8 = int4" comparison. While this works ok on 64 bit instances, it can crash on i386 ones. The issue is in the scankey that we build for segment-by columns. Even though we specify the valid "opcode" for cases where the arguments types don't match we also need to specify the "sk_subtype" appropriately.
Fixes #7039

Fix scankey where consttype is different from var

---

.unreleased/pr_7048
src/nodes/chunk_dispatch/chunk_insert_state.c
src/nodes/chunk_dispatch/chunk_insert_state.h
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/test/expected/compression_conflicts.out
tsl/test/isolation/expected/compression_conflicts_iso.out
tsl/test/sql/compression_conflicts.sql
tsl/test/t/002_logrepl_decomp_marker.pl

In order to verify constraints, we have to decompress batches that could contain duplicates of the tuples we are inserting. To find such batches, we use heap scans which can be very expensive if the compressed chunk contains a lot of tuples. Doing an index scan makes much more sense in this scenario and will
give great performance benefits.
Additionally, we don't want to create the decompressor until we determine we actually want to decompress a batch so we try to lazily initialize it once a batch is found.

Add index scan to INSERT DML decompression

---

tsl/src/bgw_policy/policies_v2.c
tsl/src/compression/dictionary.c
tsl/test/expected/cagg_policy.out

Theoretical overflow calculations fixed in a couple of places.

Quell a couple of coverity warnings

---

.unreleased/fix_7064
sql/compression_defaults.sql
tsl/test/expected/compression_defaults.out
tsl/test/sql/compression_defaults.sql

There was a "cute" typo in the query used for the calculation of default orderbys in the case of compression. Fixed that.

Fix a bug in default orderby calc. in compression

---

.github/workflows/pr-handling.yaml

We don't have the same review requirements for other branches.

Don't assign reviewers for PRs not to main branch

---

tsl/src/compression/compression.c
tsl/test/isolation/expected/compression_conflicts_iso.out

With index scans during INSERT decompression caused by unique constraints, we need to make sure we are using key columns from constraints while building scan keys. This makes the code more flexible for any kind of
index found on the chunk by not relying on compression settings.

Fix column filtering for DML decompression

---

.unreleased/pr_7061
tsl/src/compression/compression.c
tsl/test/expected/compression_insert.out
tsl/test/sql/compression_insert.sql

Adjust compressed_insert_key_columns to correctly handle multiple
unique indexes. This patch changes the function to no longer combine
the columns from multiple indexes but instead only return intersecting
columns from all the unique indexes.
This patch also fixes a couple comments in that function.

Fix handling for multiple unique index in compressed INSERT

---

.unreleased/pr_7069
tsl/src/compression/compression.c
tsl/test/shared/sql/include/shared_setup.sql

We must never use index column names to try to match relation column names between different relations as index column names are independent of relation column names and can get out of sync due to column renames.

Don't use index column names

---

.unreleased/fix_7074
sql/compression_defaults.sql
tsl/test/expected/compression_defaults.out
tsl/test/sql/compression_defaults.sql

There was a typo in the query used for the calculation of default segmentbys in the case of compression.

Fix bug in default segmentby calc. in compression

---

.unreleased/pr_7080
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/transparent_decompression-14.out
tsl/test/expected/transparent_decompression-15.out
tsl/test/expected/transparent_decompression-16.out
tsl/test/sql/transparent_decompression.sql.in

When querying compressed data we determine whether the requested ORDER
can be applied to the underlying query on the compressed data itself.
This happens twice. The first time we decide whether we can push down
the sort and then we do a recheck when we setup the sort metadata.
Unfortunately those two checks did not agree. The initial check concluded
it is possible but the recheck disagreed.  This was due to a bug when
checking the query properties we mixed up the attnos and used attnos
from uncompressed chunk and compressed chunk in the same bitmapset.
If a segmentby column with equality constraint was present in the WHERE
clause whose attno was identical to a compressed attno of a different
column that was part of the ORDER BY the recheck would fail.
This patch removes the recheck and …

Fix `corresponding equivalence member not found`

---

.unreleased/fix_7088
src/cache.c
test/expected/copy_memory_usage.out
test/sql/copy_memory_usage.sql

If plpgsql functions are used in DML queries then we were leaking 8KB for every invocation of that function. This can quickly add up.
The issue was that the "CurTransactionContext" was not getting cleaned up after every invocation. The reason was that we were inadvertantly allocating a temporary list in that context. Postgres then thought that this CurTransactionContext needs to be re-used further and kept it around. We now use a proper memory context to avoid this.
Fixes #7053

Fix leaks with functions in DML

---

.unreleased/fix_7088
.unreleased/pr_7061
.unreleased/pr_7080
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains bug fixes since the 2.15.2 release.
Best practice is to upgrade at the next available opportunity.
**Migrating from self-hosted TimescaleDB v2.14.x and earlier**
After you run `ALTER EXTENSION`, you must run [this SQL script](https://github.com/timescale/timescaledb-extras/blob/master/utils/2.15.X-fix_hypertable_foreign_keys.sql). For more details, see the following pull request [#6797](https://github.com/timescale/timescaledb/pull/6797).
If you are migrating from TimescaleDB v2.15.0, v2.15.1 or v2.15.2, no changes are required.
**Bugfixes**
* #7061: Fix the handling of multiple unique indexes in a compressed INSERT.
* #7080: Fix the `corresponding equivalence member not found` error.
* #7088: Fix the leaks in the DML functions.
* #7035: Fix the error when acquiring …

Release 2.15.3

---

src/planner/add_hashagg.c
tsl/test/expected/cagg_joins.out
tsl/test/sql/cagg_joins.sql

In #6377 we fixed an `ORDER BY/GROUP BY expression not found in targetlist` by using the `root->processed_groupClause` instead of `parse->groupClause` due to an optimization introduced in PG16 that removes redundant grouping and distinct columns.
But looks like we didn't change all necessary places, specially our HashAggregate optimization.

Use processed group clause in PG16 (take 2)

---

.github/workflows/rpm-packages.yaml

Centos 7 is EOL since June 30th so we no longer build packages for it and test it.

Remove centos7 from package test

---

.unreleased/pr_7075
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/test/expected/compression.out
tsl/test/expected/compression_conflicts.out
tsl/test/expected/compression_insert.out
tsl/test/shared/expected/compress_unique_index.out
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/expected/decompress_tracking.out
tsl/test/shared/sql/compression_dml.sql
tsl/test/sql/compression_insert.sql
tsl/test/t/002_logrepl_decomp_marker.pl

Previously for INSERTs into compressed chunks with unique constraints we would decompress the batch which would contain the tuple matching according to the constraints. This patch will skip the decompressing if the batch does not contain an actual matching tuples. This patch adds the optimization for INSERT with unique constraints. Similar optimizations for UPDATE and DELETE will be added in followup patches.

Reduce decompression on compressed INSERT

---

.unreleased/pr_7101
src/guc.c
src/guc.h
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/compression/compression_scankey.c
tsl/test/expected/compression_update_delete.out
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/sql/compression_dml.sql

Only decompress batches for compressed UPDATE/DELETE when the batch actually has tuples that match the query constraints. This will work even for columns we have no metadata on.

Reduce decompressions for compressed UPDATE/DELETE

---

src/telemetry/replication.c
test/expected/alter.out
test/sql/alter.sql
tsl/src/continuous_aggs/materialize.c

PG17 changed attstattarget to be NULLABLE and changed the default to NULL. This patch changes the pg_attribute to produce the same result against PG17 and previous versions.
https://github.com/postgres/postgres/commit/4f622503d6de975ac87448aea5cea7de4bc140d5

Handle NULL as attstattarget default value in PG17

---

src/bgw/job.c
src/chunk_index.c
src/compat/compat.h
src/copy.c
src/import/ht_hypertable_modify.c
src/loader/bgw_message_queue.c
src/nodes/chunk_dispatch/chunk_dispatch.c
src/nodes/chunk_dispatch/chunk_insert_state.c
src/nodes/hypertable_modify.c
src/process_utility.c
test/src/test_utils.c
tsl/src/compression/compression.c
tsl/src/compression/compression_storage.c
tsl/src/compression/wal_utils.h
tsl/src/reorder.c

With these changes TimescaleDB can be built against PG17. Doing so still requires -DEXPERIMENTAL=ON.
Disable-check: loader-change

Allow building against PG17

---

CMakeLists.txt
src/CMakeLists.txt
tsl/src/CMakeLists.txt

This patch changes our build process to no longer link against
openssl directly but instead rely on postgres linking it.
Linking to openssl directly is causing problems when the openssl
version we link against does not match the version postgres links
against. While this is easy to prevent where we fully control the
build process it is repeatedly causing problems e.g. in ABI tests.
This patch changes only changes the behaviour for non-Windows as
we are running into linker problems on Windows with this change.
Until we can find a workaround for those problems Windows binaries
we still link OpenSSL directly.

Don't link against openssl directly

---

tsl/test/expected/transparent_decompression-14.out
tsl/test/expected/transparent_decompression-15.out
tsl/test/expected/transparent_decompression-16.out
tsl/test/sql/transparent_decompression.sql.in

The `transparent_decompression` test is flaky because incremental sort is chosen most times but normal sort is picked up as well when under load.
Making the test less flaky by turning off incremental sort. The test exists to test that DecompressChunk works as intended.

Fix flaky transparent_decompression

---

.unreleased/pr_7108
src/nodes/chunk_dispatch/chunk_dispatch.c
src/nodes/chunk_dispatch/chunk_dispatch.h
src/nodes/chunk_dispatch/chunk_insert_state.c
src/nodes/chunk_dispatch/chunk_insert_state.h
src/nodes/hypertable_modify.c
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/compression/compression_scankey.c
tsl/test/expected/compression_conflicts.out
tsl/test/expected/compression_insert.out
tsl/test/isolation/expected/compression_conflicts_iso.out
tsl/test/shared/expected/compression_dml.out
tsl/test/t/002_logrepl_decomp_marker.pl

On INSERT into compressed chunks with unique constraints we can
check for conflict without decompressing when no ON CONFLICT clause
is present and we only have one unique constraint. With ON CONFLICT
clause with DO NOTHING we can just skip the INSERT if we detect conflict
and return early. Only for ON CONFLICT DO UPDATE/UPSERT do we need
to decompress when there is a constraint conflict.
Doing the optimization in the presence of multiple constraints is
also possible but not part of this patch.

Reduce decompression for INSERT with unique constraints

---

.unreleased/fix_7051
.unreleased/fix_7055
.unreleased/fix_7064
.unreleased/fix_7074
.unreleased/pr_6880
.unreleased/pr_6895
.unreleased/pr_6897
.unreleased/pr_6918
.unreleased/pr_6920
.unreleased/pr_6989
.unreleased/pr_7018
.unreleased/pr_7020
.unreleased/pr_7046
.unreleased/pr_7048
.unreleased/pr_7069
.unreleased/pr_7075
.unreleased/pr_7101

For docs-compliance for the upcoming release.

Improve release-notes further

---

tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_joins.out
tsl/test/expected/cagg_utils.out
tsl/test/sql/cagg_joins.sql

Remove some Continuous Aggregates JOIN restrictions by allowing:
* INNER/LEFT join;
* LATERAL join;
* JOIN between 1 hypertable and N tables, foreign tables, views or
materialized views;
* Remove restriction of only ONE equality operator on JOIN clause.
Closes #1446, #1516, #1717, #2400, #3314, #4088, #7107

Relax CAggs JOIN restrictions

---

src/guc.c
tsl/test/expected/bgw_job_stat_history.out
tsl/test/sql/bgw_job_stat_history.sql

In #6767 we allowed users to track job execution history by turning on the new GUC `timescaledb.enable_job_execution_logging`.
Unfortunately we defined this GUC as PGC_USERSET context but the right context should be PGC_SIGHUP since it won't work when setting at session and/or database level so we should restrict it to be used only by `ALTER SYSTEM SET` or changing the config files.

Fix `enable_job_execution_logging` GUC context

---

tsl/src/continuous_aggs/planner.c
tsl/test/expected/cagg_watermark-14.out
tsl/test/expected/cagg_watermark-15.out
tsl/test/expected/cagg_watermark-16.out
tsl/test/expected/cagg_watermark-17.out
tsl/test/sql/cagg_watermark.sql.in

Some more complex queries using CAggs on CTEs was not properly applying the `cagg_watermark` constify optimization because we restricted it to more simple queries.
Simplified the code and only restrict SELECT queries to apply the optimization.

Fix CAgg watermark constify using CTE

---

.github/workflows/catalog-updates-check.yaml
scripts/check_updates_ast.py
sql/updates/latest-dev.sql

Having c function references in the versioned part of the sql
scripts introduces linking requirements to the update script
potentially preventing version updates. To prevent this we can
have a dummy function in latest-dev.sql since it will get over-
written as the final step of the extension update.

Block c function definitions in latest-dev.sql

---

.unreleased/pr_7116
src/guc.c
src/guc.h
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/isolation/expected/compression_freeze.out
tsl/test/isolation/specs/compression_freeze.spec
tsl/test/sql/compression.sql

The last step of compressing chunk is cleanup the uncompressed chunk and currently it is done by a `TRUNCATE` that requires an `AccessExclusiveLock` preventing concurrent sessions even `SELECT` data from the hypertable.
With this PR will be possible to execute a `DELETE` instead of a `TRUNCATE` on the uncompressed chunk relaxing the lock to `RowExclusiveLock`. This new behavior is controled by a new GUC `timescaledb.enable_delete_after_compression` that is `false` by default.
The side effect of enabling this behavior will be more WAL generation because we'll delete each row from uncompressed chunk and also bloat due to a lot of dead tuples created.

Use DELETE after compression

---

.unreleased/pr_7134
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/chunk_constraint.c
src/planner/planner.c
src/process_utility.c
test/expected/rowsecurity-14.out
test/expected/rowsecurity-15.out
test/expected/rowsecurity-16.out
tsl/src/compression/compression_storage.c
tsl/src/compression/create.c
tsl/test/expected/compression.out
tsl/test/expected/compression_errors-14.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/expected/compression_fks.out
tsl/test/expected/foreign_keys.out
tsl/test/sql/compression.sql
tsl/test/sql/compression_errors.sql.in
tsl/test/sql/foreign_keys.sql

Don't copy foreign key constraints to the individual chunks and instead modify the lookup query to propagate to individual chunks to mimic how postgres does this for partitioned tables.

Change hypertable foreign key handling

---

tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/finalize.c
tsl/test/expected/cagg_joins.out
tsl/test/expected/cagg_on_cagg.out
tsl/test/expected/cagg_on_cagg_joins.out
tsl/test/expected/cagg_repair-14.out
tsl/test/expected/cagg_repair-15.out
tsl/test/expected/cagg_repair-16.out
tsl/test/sql/cagg_joins.sql
tsl/test/sql/include/cagg_on_cagg_common.sql

Creating or changing to realtime a Continuous Aggregate with multiple joins was leading to a segfault.
Fixed it by dealing properly with the `varno` when creating the `Quals` for the union view in realtime mode.
Also get rid of some left over when we relaxed the CAggs join restrictions in #7111.

Fix segfault on CAggs with multiple JOINs

---

tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/transparent_decompression-14.out
tsl/test/expected/transparent_decompression-15.out
tsl/test/expected/transparent_decompression-16.out
tsl/test/sql/include/transparent_decompression_query.sql

When creating index paths for compressed chunks, root->eq_classes can contain a lot of entries from other relations which slow down plan time. By filtering them to include only ECs which are from that relation, we can improve plan times significantly when lots of chunks are involved in the query.
Offers modest improvement up to 15% in plan times:
https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=3629&var-run2=3630&var-threshold=0&var-use_historical_thresholds=true&var-threshold_expression=2.5%20%2A%20percentile_cont%280.90%29&var-exact_suite_version=false

Optimize index path generation for ordered append

---

scripts/test_pg_upgrade.py
scripts/test_update_from_version.sh
test/sql/updates/post.pg_upgrade.sql
test/sql/updates/setup.pg_upgrade.sql
tsl/src/continuous_aggs/create.c

When creating a CAgg using a column on the projection that is not part of the `GROUP BY` clause but is functionally dependent of the primary key of the referenced table is leading to a problem in dump/restore because the wrong dependencies created changing the order and way dump is generated.
Fixed it by copying the direct view `Query` data structure and changing the necessary properties instead of creating it from scratch.

Fix CAggs partial view dependencies

---

.github/workflows/pg_upgrade-test.yaml

Now we can install `testgres` using `pip` since release `1.10.1` that includes the PR #125 was merged.
https://github.com/postgrespro/testgres/releases/tag/1.10.1

Install testgres using pip on CI

---

.unreleased/pr_6987
src/bgw/job.h
src/process_utility.c
tsl/test/expected/bgw_db_scheduler.out
tsl/test/expected/bgw_job_ddl.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/bgw_db_scheduler.sql
tsl/test/sql/bgw_job_ddl.sql

Using `REASSIGN OWNED BY` for background jobs do not work because it does not change the owner of the job. This commit fixes this by capturing the utility command and makes the necessary changes to the `bgw_job` table.
It also factors out background jobs DDL tests into a separate file.

Fix REASSIGN OWNED BY for background jobs

---

.unreleased/pr_7161
src/sort_transform.c
test/expected/sort_optimization.out
test/sql/sort_optimization.sql

We applied our sort transformation for interval calculation too aggressively even in situations where it is not safe to do so, leading to potentially incorrectly sorted output or `mergejoin input data is out of order` error messages.
Fixes #7097

Dont apply sort optimization when interval length is not fixed

---

src/planner/expand_hypertable.c
src/planner/planner.c
tsl/test/expected/chunk_utils_internal.out
tsl/test/sql/chunk_utils_internal.sql

Skip the OSM chunk when doing hypertable expansion for FK lookup queries. OSM chunks are considered archived data and we dont want to incur the performance hit of querying OSM data on modifications on the FK reference table.

Don't propagate FK lookup queries to osm chunks

---

.unreleased/pr_7126
sql/pre_install/types.functions.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
tsl/src/compression/algorithms/array.c
tsl/src/compression/algorithms/array.h
tsl/src/compression/algorithms/deltadelta.c
tsl/src/compression/algorithms/deltadelta.h
tsl/src/compression/algorithms/dictionary.c
tsl/src/compression/algorithms/dictionary.h
tsl/src/compression/algorithms/gorilla.c
tsl/src/compression/algorithms/gorilla.h
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/init.c
tsl/test/expected/compression_algos.out
tsl/test/shared/expected/extension.out
tsl/test/sql/include/compression_test.sql

Add a function that can be used on a compressed data value to show some metadata information, such as the compression algorithm used and the presence of any null values.

Add function to show compression information

---

.unreleased/pr_7182
src/hypertable_restrict_info.c
src/hypertable_restrict_info.h
src/planner/expand_hypertable.c

When hypertable expansion was instructed to ignore osm chunks it would not correctly set up the planner structures as the list position in the list of chunk oids would no longer be in sync with the index in the chunks array.

Fix untier_chunk for hypertables with foreign keys

---

.unreleased/pr_7182
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains bug fixes since the 2.16.0 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* #7182 Fix untier_chunk for hypertables with foreign keys

Release 2.16.1

---

docs/BuildSource.md

Fix minimum Cmake version in BuildSource.md

---

.unreleased/pr_7187
tsl/src/compression/compression.c
tsl/src/compression/compression.h

The function `compressed_data_info` returns a record containing `name`
but copies the data from string literal. Since `heap_form_tuple` expects a
`name` value as source as well, it will copy too much data from the
source, leading to ASAN complaining about copying outside the allocated
range of data.
The problem is fixed by `NameData` for each
source string, ensuring that each of the string literals has sufficient
data for being copied as names.

Fix string literal length for compressed_data_info

---

.unreleased/pr_6882
src/guc.c
src/guc.h
src/nodes/chunk_dispatch/chunk_dispatch.h
src/nodes/hypertable_modify.c
src/nodes/hypertable_modify.h
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c
tsl/test/expected/compression_update_delete.out
tsl/test/expected/foreign_keys.out
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/expected/decompress_tracking.out
tsl/test/shared/sql/compression_dml.sql
tsl/test/shared/sql/decompress_tracking.sql
tsl/test/sql/compression_update_delete.sql
tsl/test/sql/foreign_keys.sql

When the constraints of a DELETE on a compressed chunks fully cover the batches we can optimize the DELETE to work directly on the compressed batches and skip the expensive decompression part.

Allow DELETE on compressed chunks without decompression

---

.unreleased/pr_7191
src/hypertable.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

When creating a hypertable with default indexes and migrating data by setting `migrate_data=>true` is not creating the default indexes on chunks.
Fixed it by changing the internal order or operations by first create the default indexes and after it migrate the data.
Fixes #7190

Fix create default indexes on chunks

---

.unreleased/pr_7201
CMakeLists.txt
timescaledb.control.in

When building apt or rpm packages we build a separate loader package that will be used by both the apache and community editions. Having the edition in the description would be misleading so we remove it for these cases.
Fixes #7198

Fix extension comment for generic loader package

---

scripts/check_updates_ast.py
sql/updates/latest-dev.sql
src/utils.c

To not introduce shared object dependencies on functions in extension update scripts we use this stub function as placeholder whenever we need to reference c functions in the update scripts.

Add ts_update_placeholder function

---

.unreleased/pr_7195
tsl/src/compression/create.c
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression_ddl.sql

This fixes segmentby/orderby check when dropping a column from a
compressed hypertable. Currently, only the hypertable compression
settings are checked. This change also checks compression settings
for each chunk.

Fix check when dropping compressed column (#7102)

---

.unreleased/pr_7204
src/telemetry/telemetry.c

Add information about the existence of `ai`, `vector`, or `vectorbase` extensions to telemetry.

Track additional extensions in telemetry

---

sql/updates/pre-version-change.sql

Only creating functions/procedures in a dedicated schema allows us to further lockdown the _timescaledb_internal schema by removing EXECUTE privilege for it.

Create temporary bgw function in _timescaledb_functions schema

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
tsl/test/sql/vector_agg_default.sql

Use `runuser` instead of `sudo` so that the core ulimit is preserved.
Also make cosmetic changes for smaller diff between the 64-bit and 32-bit workflow files.
Tested on https://github.com/timescale/timescaledb/pull/7200

Fix core dumps on i386

---

.unreleased/pr_7207
tsl/src/compression/compression_dml.c

The code paths for `decompress_batches_indexscan` and `decompress_batches_seqscan` are mostly duplicated. This unifies the code path by refactoring it into a single function to make it easier to maintain.
Closes #7144.

Refactor decompress_batches_scan functions

---

.unreleased/pr_7227
sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql

During upgrade the function `remove_dropped_chunk_metadata` is used to update the metadata tables and remove data for chunks marked as dropped. The function iterates of the chunks of the provided hypertable and internally does a sequence scan of `compression_chunk_size` table to locate the `compressed_chunk_id`, resulting in quadratic execution time. This is usually not noticed for small number of chunks, but for large number of chunks this becomes a problem.
This commit fixes this by adding an index to `compression_chunk_size` catalog table, turning the sequence scan into an index scan.

Add index to compression_chunk_size catalog table

---

.unreleased/pr_7209
sql/chunk.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/chunk.c
tsl/test/expected/chunk_utils_internal.out
tsl/test/isolation/expected/osm_range_updates_iso.out
tsl/test/isolation/specs/osm_range_updates_iso.spec
tsl/test/shared/expected/extension.out
tsl/test/sql/chunk_utils_internal.sql

Reviving the old Konstantina's PR #6801. OSM requires this for the user API to disable tiering.
I kept the original commits and added mine on top for visibility, will squash them together before merging.

Add function to drop the osm chunk

---

.unreleased/pr_7229
src/foreign_key.c
tsl/test/expected/foreign_keys.out
tsl/test/sql/foreign_keys.sql

The code for finding the constraint index was expecting the index columns to be in the same order as the constraint columns. This patch changes the check to require all columns be present independent of the order.
Fixes #7226

Fix FK constraint where index and constraint column order differ

---

tsl/test/expected/bgw_custom.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/sql/bgw_custom.sql
tsl/test/sql/bgw_job_stat_history_errors.sql

This change helps optimize two bgw tests, by a) reducing the time a test spends waiting for scheduled jobs and b) decreasing the amount of data inserted into the table. This should have no effect on the efficacy of the tests themselves.

Optimize BGW CI tests

---

.unreleased/pr_7234
src/nodes/chunk_dispatch/chunk_dispatch.c
test/expected/merge.out
test/sql/merge.sql

The cache entry is released while a pointer is still pointing into the entry, which can potentially lead to accessing freed memory. The scenario for triggering this is quite complicated, but it requires a MERGE that has an INSERT statement on a table that either has dropped a column or added a column with a non-volatile default value.
Co-authored-by: Gayathri Ayyappan <gayathri@timescale.com>

Release cache after accessing the cache entry

---

.unreleased/pr_7230
src/foreign_key.c
tsl/test/expected/chunk_utils_internal.out
tsl/test/sql/chunk_utils_internal.sql

The osm chunk is a foreign table which does not support constraints so we have to exclude the osm chunk when propagating fk constraints.
Fixes #7188

Don't propagate fk constraints to osm chunk

---

tsl/test/expected/chunk_utils_internal.out
tsl/test/sql/chunk_utils_internal.sql

Fix flaky chunk_utils_internal test

---

.github/gh_matrix_builder.py
src/utils.c

Postgres 17 introduced the MAINTAIN privilege.
postgres/postgres@ecb0fd33

PG17: Fix makeaclitem

---

.github/gh_matrix_builder.py
tsl/test/t/001_job_crash_log.pl

PG17 TAP seems to require explicit node name.

Fix TAP tests for PG17

---

.unreleased/pr_7258
CMakeLists.txt

Force English in the pg_config command executed by cmake to avoid unexpected building errors. 
Fixes #7257

Force english in pg_config command

---

.unreleased/pr_7033
src/guc.c
src/guc.h
src/ts_catalog/continuous_agg.c
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/materialize.c
tsl/src/continuous_aggs/options.c
tsl/test/expected/cagg_query_using_merge.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_query_using_merge.sql
tsl/test/sql/cagg_refresh_using_merge.sql
tsl/test/sql/include/cagg_query_common.sql
tsl/test/sql/include/cagg_refresh_common.sql

Currently the materialization step of the Continuous Aggregate refresh procedure is essentially a DELETE followed by an INSERT of the affected buckets.
This implementation works well but have some side effects like bloating the materialization hypertable due to dead tuples left specially when back-filling data. Also it generate more WAL imposing more work for the auto-vacuum process.
In Postgres 15 the SQL [MERGE](https://www.postgresql.org/docs/current/sql-merge.html) command was released given the users the ability to conditionally insert, update, or delete rows of a table.
With MERGE statement we can improve back-filling data making the materialization more smart by skipping unchanged buckets and only updating those that really changed, reducing the amount of dead tuples and WAL.
For …

Use MERGE statement on CAgg Refresh

---

.unreleased/pr_7270
tsl/src/compression/compression.c

When a batch was skipped due to compression tuple filtering the per compressed row memory context would not be reset leading to memory usage increasing linearly with number of consecutive filtered batches.

Reset per compressed row memory context during tuple filtering

---

src/utils.h

Add macro `TS_DEBUG_LOG` to allow debug-only messages that are not added in release builds. Using `elog` or `ereport` with `DEBUG2` will still run the logging functions in release builds, which is unnecessary for logging messages that are strictly used for development.
Add function `datum_as_string` that converts a datum to a string using the output function. Mainly used for debug outputs.
Add function `slot_as_string` that convers a slot into a string representation for debug output.

Add debug functionality

---

tsl/test/shared/expected/transparent_decompress_chunk-14.out
tsl/test/shared/expected/transparent_decompress_chunk-15.out
tsl/test/shared/expected/transparent_decompress_chunk-16.out
tsl/test/shared/expected/transparent_decompress_chunk-17.out
tsl/test/shared/sql/transparent_decompress_chunk.sql.in

The test transparent_decompress_chunk-* is flaky because depending on resources available, either an incremental sort or a normal sort can be picked.
We fix this by disabling incremental sort and relying on normal sort all the time. This makes no difference to the tests since they just check that a DecompressChunk node is generated for the cases where necessary.

Fix flaky transparent_decompress_chunk

---

tsl/test/t/002_logrepl_decomp_marker.pl

Instead of filtering the output of `pg_logical_slot_get_changes` we set
the option `skip-empty-xacts` and clear `include-xids` to get stable
tests.
Since the option 'skip-empty-xacts' is set, this changes the order of
messages since the BEGIN of a transaction is not generated until the
decoder plugin can see that the transaction started and messages do not
count as part of a transaction.
We also remove transaction start and end marker (and strip trailing and
leading whitespace) since these will appear in different places
depending on the PostgreSQL version and they are not important for the
correctness of the test.

Disable xids and empty transactions in TAP test

---

sql/pre_install/schemas.sql
test/expected/debug_utils.out
test/sql/CMakeLists.txt
test/sql/debug_utils.sql

Make it possible for regular users to execute functions in the schema `_timescaledb_debug`.
As a consequence, the `extension_state()` function in this schema can now be executed by "public". This is the only function in this schema and there is no security risk in making it accessible.

Grant USAGE on debug schema

---

.unreleased/pr_7275
src/import/ht_hypertable_modify.c
src/import/ht_hypertable_modify.h
src/nodes/hypertable_modify.c
test/expected/ts_merge-17.out

This adds Timescale support for the RETURNING clause with MERGE statements, which was added in PG17.

Implement support for RETURNING clause for MERGE

---

test/expected/ts_merge-15.out
test/expected/ts_merge-16.out
test/expected/ts_merge-17.out
test/sql/include/ts_merge_query.sql
test/sql/ts_merge.sql.in

This adds tests for MERGE on views, `RETURNING` clause for MERGE and the `merge_action` function, which were all introduced in PG17.

Add additional tests for PG17 MERGE support

---

src/chunk.c
src/chunk.h
src/chunk_scan.c
src/import/allpaths.c
src/planner/planner.c
src/planner/planner.h
src/utils.c
src/utils.h
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/nodes/decompress_chunk/decompress_chunk.h
tsl/src/planner.c

A chunk can use different table access methods so to support this more easily, cache the AM oid in the chunk struct. This allows identifying the access method quickly at, e.g., planning time.

Add ability to plan based on chunk table AM

---

.unreleased/pr_7286
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_scankey.c
tsl/test/expected/compression_conflicts.out
tsl/test/shared/expected/compression_nulls_not_distinct.out
tsl/test/shared/sql/CMakeLists.txt
tsl/test/shared/sql/compression_nulls_not_distinct.sql
tsl/test/sql/compression_conflicts.sql

Attribute numbers for key columns are stored with system column
offsets which need to be added every time we calculate an attribute
number from an index. This was causing us not to find appropriate
indexes for scanning during DML compression.

Fix index column check while searching for index

---

src/chunk.c
tsl/src/compression/api.c
tsl/src/compression/compression_storage.c

If `create_compress_chunk()` is called as part of a utility statement, a spurious printout will happen because
`ts_alter_table_with_event_trigger()` uses a `List` node rather than a proper statement which causes `EventTriggerAlterTableEnd()` to not recognize the node and print out an error message.
This is fixed by calling `AlterTableInternal` instead of `ts_alter_table_with_event_trigger()` for utility statements and make sure that `EventTriggerAlterTableStart()` and
`EventTriggerAlterTableEnd()` are called for non-utility statements calling `create_compress_chunk()` with a dummy statement.

Fix ALTER TABLE spurious printout

---

src/import/ht_hypertable_modify.c
tsl/test/expected/move.out
tsl/test/sql/move.sql

Warnings are generated for one `GRANT` statement in the `move` test on PG17 but not other versions, so disabling warnings for that statement.
Also set default value for variable in `src/import/ht_hypertable_modify.c` to avoid warning of potentially unassigned variable when building on PG17.
Disable-check: force-changelog-file, commit-count

Disable warnings for GRANT in move test

---

.unreleased/pr_7295
src/process_utility.c
test/expected/reloptions.out
test/expected/tableam_alter.out
test/sql/CMakeLists.txt
test/sql/reloptions.sql
test/sql/tableam_alter.sql
tsl/src/compression/create.h
tsl/test/expected/compression_errors-14.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/expected/compression_errors-17.out
tsl/test/sql/compression_errors.sql.in

This commit allows `ALTER TABLE SET ACCESS METHOD` on a hypertable, which will set the access method of the hypertable to the given access method and also set the compression flag if changing to `hyperstore` access method.
In order to set compression when setting the access method, it is necessary to allow several ALTER TABLE commands, which was previously not allowed. To support this, `ProcessUtility` will process each `ALTER TABLE` command in turn and remove it from the list if it is dealt with. If there are any remaining commands in the list after that, it will assume that these are not timescaledb-specific and continue running the normal command.
Also fixes a build warning for PG17 RC1.

Add ALTER TABLE SET ACCESS METHOD support

---

tsl/src/compression/compression.c
tsl/src/compression/compression.h

Add the ability to define a callback function that gets called every time a new segment is flushed during compression. The callback can be used to report compression progress.
Also expose the function to create a tuple sort state for compression.

Add compression flush callback

---

tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/compressed_batch.h
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/decompress_chunk/vector_quals.h

Refactor the code for vectorized filtering over arrow arrays so that the code can be called from different scan nodes.
In the future, it might make sense to move the code to a separate directory for code related to vectorization.

Share vector qual functionality across scan nodes

---

.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml

Debian 10 is EOL since June 30th 2024 and PGDG repo has been removed for it leading to failing tests.

Remove debian 10 from package tests since its EOL

---

.unreleased/pr_7301
src/hypertable.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql
tsl/test/expected/foreign_keys.out
tsl/test/sql/foreign_keys.sql

We now allow FKs to hypertables but the initial check when creating the hypertable was not adjusted so tables with pre-existing FKs would not be allowed to be changed into hypertable while creating the FK constraint afterwards succeeded.

Sync FK behaviour when creating hypertable

---

src/ts_catalog/compression_chunk_size.c

In the function `ts_compression_chunk_size_delete()` a counter is used to indicate the number of catalog entries deleted. But this counter is never incremented so the returned count is not accurate.
Fix this issue by incrementing the counter when entries are deleted. Also, increment the command counter (to make changes visible) only at the end if the count is non-zero.

Fix count when deleting compression chunk size entry

---

src/bgw/job.c
src/bgw/job.h
src/bgw/job_stat.c
src/bgw/job_stat.h
src/bgw/scheduler.c
src/utils.c
src/utils.h
test/expected/test_utils.out
test/sql/test_utils.sql
test/sql/utils/testsupport.sql
test/src/test_utils.c
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/postgresql.conf.in
tsl/test/sql/bgw_job_stat_history_errors.sql

Reorganized a bit the code to also record more failures in `bgw_job_stat_history` table.
Also improved a bit the code coverage and added regression tests for `failed do start job` case.

Refactor job error handling

---

.github/gh_matrix_builder.py

For non pull-request we run CI over the EARLIEST and LATEST version but PG17 was released last week then both versions are equal so no need to add an extra item in the matrix.
https://github.com/timescale/timescaledb/actions/runs/11109257307/job/30864183372

PG17: Remove duplicated generated matrix

---

src/chunk_index.c
src/hypertable.c

This changes the return value for ts_hypertable_relid_to_id to return INVALID_HYPERTABLE_ID (0) when the relid is not a hypertable instead of returning -1.

Change return value for ts_hypertable_relid_to_id

---

tsl/src/nodes/vector_agg/function/float48_accum_single.c

It seems to think that the row counter somehow can have any negative value, but I couldn't find a way for that to happen.

Change loop counter to unsigned to fix a spurious gcc-13 warning

---

tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/compression/compression_scankey.c

We fetch key column attribute numbers from indexes on uncompressed chunks. These should not contain
system attribute numbers so there is no point in
adding/subtracting FirstLowInvalidHeapAttributeNumber.

Simplify dealing with attnos during decompression

---

src/bgw/scheduler.c
src/extension.c
src/extension.h
src/func_cache.c
src/guc.c
src/planner/planner.c
src/process_utility.c
test/src/loader/init.c

It should be possible to read the TimescaleDB catalog during restore and pg_upgrade. Currently, this is blocked in
`ts_extension_is_loaded()` by checking whether the GUC `timescaledb.restoring` is set or `IsBinaryUpgrade` is true, causing the "loaded" check to fail even though the extension is loaded and usable.
To allow catalog access while minimizing changes to existing code, the block is moved out of `ts_extension_is_loaded()` into a new function that has the old behavior.
Accessing the catalog during restores should be safe since the extension catalog tables are created and populated before regular data tables.
Note that the blocking was moved into `ts_extension_is_loaded()` in an earlier commit out of convenience, but it seems this also blocks legitimate access to the TimescaleDB …

Relax catalog access during restore

---

src/bgw/job.c
src/bgw/job.h
src/tss_callbacks.c
src/tss_callbacks.h
test/src/bgw/CMakeLists.txt
test/src/bgw/test_job_utils.c
tsl/src/bgw_policy/job.c
tsl/test/expected/bgw_custom.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/sql/bgw_custom.sql
tsl/test/sql/bgw_job_stat_history_errors.sql

Since our scheduler don't use SQL statements to execute Job procedures but instead we rely on internal Postgres API then `ts_stat_statements` can't record it execution.
Added the callbacks to `ts_stat_staments` on our scheduler to record the job procedure execution sending a query string like this:
```sql
CALL _timescaledb_functions.policy_refresh_continuous_aggregate($1, $2);
```

Add ts_stat_statements support on Jobs

---

.unreleased/pr_7318
src/hypertable_restrict_info.c
src/ts_catalog/chunk_column_stats.c
tsl/test/expected/chunk_column_stats-14.out
tsl/test/expected/chunk_column_stats-15.out
tsl/test/expected/chunk_column_stats-16.out
tsl/test/expected/chunk_column_stats-17.out
tsl/test/sql/chunk_column_stats.sql.in

Chunk skipping based on column stats had a convoluted way
of detecting if query clauses were hitting a chunk in certain
cases. This change makes things more straight forward and
adds missing test cases for range checking.

Fix chunk skipping range check bug

---

tsl/src/continuous_aggs/materialize.c

To prevent issues on TimestampTz output used in SQL statements dynamically generated for the Continuous Aggregate materialization code we replaced the `SPI_execute` by `SPI_execute_with_args` so now it will not convert timestamp to string and parse it back anymore.
This popped up due to some tzdata 2024b changes in timezone PST8PDT that also lead to some Postgres changes on PG17:
https://github.com/postgres/postgres/commit/b8ea0f67

Replace SPI_execute by SPI_execute_with_args in materialization

---

.github/workflows/abi.yaml
tsl/test/expected/cagg_watermark.out
tsl/test/sql/cagg_watermark.sql

Also don't use dates before 1970 on regression tests since the new tzdata-2024b release introduced some changes on PST8PDT timezone using dates before 1970 so make sure to use dates starting in this year to avoid flaky tests.
https://github.com/postgres/postgres/commit/b8ea0f67

PG17: Enable ABI on CI

---

scripts/backport.py

Example of error:
https://github.com/timescale/timescaledb/actions/runs/11220815161/job/31189793973

Fix list index out of range on backport.py

---

.unreleased/pr_7320
CMakeLists.txt
cmake/ScriptFiles.cmake
sql/comment_apache.sql
sql/comment_tsl.sql
test/expected/loader-oss.out
test/expected/loader-tsl.out
timescaledb.control.in
tsl/test/shared/expected/build_info.out
tsl/test/shared/sql/build_info.sql

Remove the license information from the control file as we package that with the generic loader and will be used for both Apache licensed and TSL licensed versions of the extension. This patch adjusts the extension comment in the install and update script and adds the appropriate license information.

Set license specific extension comment in install script

---

test/runner.sh
test/runner_shared.sh
test/sql/utils/testsupport.sql
test/sql/utils/testsupport_init.sql
tsl/test/expected/exp_cagg_next_gen.out
tsl/test/sql/exp_cagg_next_gen.sql

For each regression database created we execute the `test/sql/utils/testsupport.sql` to setup some test stuff before actually run the tests. Once we config Postgres to emit log for all executed statements we create a log of noise on logs about this setup SQL script.
Change it to run the setup SQL script on the `template1` database so all new created databases will contain all the necessary objects for run the tests.

Reduce Postgres logs noise on regression tests

---

.unreleased/pr_7335
tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/compression_conflicts.out
tsl/test/expected/compression_indexscan.out
tsl/test/expected/compression_settings.out
tsl/test/shared/expected/compression_nulls_not_distinct.out

Don't use LOG log level when printing out non-actionable progress information regarding compression.
Fixes #7280

Use more reasonable log level when logging compression progress

---

sql/cagg_migrate.sql
tsl/test/expected/cagg_migrate.out
tsl/test/sql/include/cagg_migrate_common.sql

During some tests on #7104 I've noticed some flakiness on Continuous Aggregates migration tests due to some output ordering.
Fixed it by explicity order policies by their IDs.

Remove some cagg_migrate test flakiness

---

tsl/src/continuous_aggs/materialize.c
tsl/test/expected/cagg_query_using_merge.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/cagg_refresh_using_merge.sql

If there's no rows in the materialization hypertable to be updated in the specific window range then fallback to INSERT rows.
It improves performance of the materialization step in the CAggs refresh and also avoid necessary DELETE.

Avoid unnecessary DELETE on materialization

---

.github/workflows/windows-build-and-test-ignored.yaml
.github/workflows/windows-build-and-test.yaml

We're forcing PG17 installation since the package still on moderation by the Chocolatey Community:
https://community.chocolatey.org/packages/postgresql17

PG17: Enable Windows tests on CI

---

.github/workflows/windows-build-and-test.yaml

Looks like version 3.1.2 does not work so pin to the previous version instead of generic v3.

Pin setup-wsl version to 3.1.1

---

.github/workflows/windows-build-and-test.yaml

Looks like version 3.1.2 does not work so pin to the previous version instead of generic v3.
(cherry-picked from commit b65083e)

Backport to 2.17.x: #7362 Pin setup-wsl version to 3.1.1

---

.unreleased/pr_7335
tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/compression_conflicts.out
tsl/test/expected/compression_indexscan.out
tsl/test/expected/compression_settings.out
tsl/test/shared/expected/compression_nulls_not_distinct.out

Don't use LOG log level when printing out non-actionable progress information regarding compression.
Fixes #7280
(cherry picked from commit 8775c84)

Backport to 2.17.x: #7335: Use more reasonable log level when logging compression progress

---

.unreleased/pr_7360
src/guc.c
src/guc.h
src/hypertable.c
src/hypertable_restrict_info.c
src/nodes/chunk_append/exec.c
src/ts_catalog/chunk_column_stats.c
tsl/test/expected/chunk_column_stats-14.out
tsl/test/expected/chunk_column_stats-15.out
tsl/test/expected/chunk_column_stats-16.out
tsl/test/expected/chunk_column_stats-17.out
tsl/test/sql/chunk_column_stats.sql.in

Add the ability to enable/disable new chunk skipping functionality completely.

Add chunk skipping GUC

---

.github/workflows/pr-approvals.yaml

All PRs except trivial ones should require 2 approvals, since this a global setting we cannot allow trivial PRs to only have 1 from github configuration alone. So we set the required approvals in github to 1 and make this check required which will enforce 2 approvals unless overwritten or only CI files are touched.

Add workflow to check number of approvals

---

tsl/src/hypercore/hypercore_handler.c

Use proper INVALID_{HYPERTABLE|CHUNK}_ID macros

---

.github/workflows/pr-approvals.yaml
src/chunk.h

Remove obsolote multinode comment about chunk status

---

test/expected/rowsecurity-14.out
test/expected/rowsecurity-15.out
test/expected/rowsecurity-16.out
test/expected/rowsecurity-17.out
test/sql/rowsecurity.sql.in

Check sql state code instead of error message in row security foreign key check.

Fix flaky rowsecurity test

---

tsl/test/expected/continuous_aggs-14.out
tsl/test/expected/continuous_aggs-15.out
tsl/test/expected/continuous_aggs-16.out
tsl/test/expected/continuous_aggs-17.out
tsl/test/sql/continuous_aggs.sql.in

Add missing ORDER BY clause to continuous_aggs test to make output deterministic.

Fix flaky continuous_aggs test

---

tsl/test/expected/hypercore_index_btree.out
tsl/test/expected/hypercore_join.out
tsl/test/sql/hypercore_index_btree.sql
tsl/test/sql/hypercore_join.sql
tsl/test/sql/include/hypercore_join_test.sql

This change should fix two Hypercore tests that could sometimes fail due to different query plans.

Fix flaky Hypercore tests

---

src/import/ht_hypertable_modify.c

Coverity detected a possible null pointer dereference. It doesn't seem like this can be triggered, so added an `Ensure` clause.

Add Ensure to fix coverity defect

---

src/utils.h
tsl/src/compression/algorithms/datum_serialize.c
tsl/src/hypercore/arrow_array.c
tsl/src/nodes/decompress_chunk/pred_vector_array.c

These two functions throw an error if you pass in a strange combination of typbyval and typlen, so we assert on bad values to get a backtrace.

Add assert for fetch_att and store_att_byval

---

.unreleased/pr_7378
sql/job_stat_history_log_retention.sql
sql/updates/latest-dev.sql

policy_job_error_retention was removed in 2.15.0 but we did not get rid of the job that called it back then. This patch removes the defunct job definition calling that function.
Fixes #7375 

Remove obsolete job

---

.unreleased/segmentby-grouping-uaf
tsl/src/nodes/vector_agg/exec.c
tsl/test/expected/vector_agg_segmentby.out
tsl/test/sql/vector_agg_segmentby.sql

The grouping column values are references into the compressed batch, so we can reset it only after we have returned the partial aggregation result.

Fix use-after-free in per-batch vectorized grouping policy

---

src/import/ht_hypertable_modify.c

A [previous commit](https://github.com/timescale/timescaledb/commit/d7513b26f667fcdb269abf1ba0453ab28e0e3801) I made added support for MERGE ... RETURNING ....
While working on the coverity fix, I realized that this code handling oldtuple was not added; that's what this fixes.

Fix handling of oldtuple to match PG17 upstream

---

.unreleased/pr_7399
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/compression_sequence_num_removal.out
tsl/test/sql/compression_sequence_num_removal.sql

Due to a typo, we were misusing OIDs and putting them into a bitmapset which caused plan time errors. Switching to using RTE index and adding a test with OID that is greater than INT32_MAX.
Fixes #7384

Fix using OIDs in bitmapset

---

tsl/test/postgresql.conf.in

We disable autovacuum on Apache regression tests to avoid flaky results and time to time we face some issues on TSL regression tests as well.
https://github.com/timescale/timescaledb/actions/runs/11470614522/job/31920227424#step:12:43

Disable autovacuum on TSL regression tests

---

test/postgresql.conf.in
tsl/test/postgresql.conf.in

We want to run autovacuum in CI to find bugs with our own code when parallel vacuum is happening.

Reenable autovacuum in CI

---

.unreleased/pr_7413
src/guc.c
src/guc.h
tsl/src/compression/api.c
tsl/test/expected/recompress_chunk_segmentwise.out
tsl/test/sql/recompress_chunk_segmentwise.sql

Add GUC option to enable or disable segmentwise recompression. If disabled, then a full recompression is done instead when recompression is attempted through `compress_chunk`. If `recompress_chunk_segmentwise` is used when GUC is disabled, then an error is thrown.
Closes #7381.

Add GUC for segmentwise recompression

---

test/pgtest/CMakeLists.txt

Until PG 17.1 is released.
Currently shows a diff in PG 17.0 regression run as:
```
select jsonb_path_query_tz('"12:34:56"', '$.time_tz().string()');
jsonb_path_query_tz
---------------------
- "12:34:56-07:00"
+ "12:34:56-08:00"
```

Ignore failure in upstream test jsonb_jsonpath

---

test/pgtest/CMakeLists.txt
test/postgresql.conf.in
tsl/test/postgresql.conf.in

This reverts commit 3130daa34f38e06b78b59ad3c092b87a64f592e4.
We will stabilize the CI after this commit in the main branch, for now it's preventing the release by making the tests too flaky.

Revert "Reenable autovacuum in CI" in 2.17.x

---

.unreleased/pr_7426
src/chunk_constraint.c

With certain timezone settings chunk constraint creation could fail as we convert the internal time to string when creating the chunk constraint leading to parse errors when the produces string could not be parsed back.

Fix datetime parse error in chunk constraint creation

---

scripts/upload_ci_stats.sh

We only parsed the old format that is used up to PG15.

Adapt test result parser for latest pg_regress output

---

.unreleased/pr_7390
src/guc.c
src/guc.h
src/planner/add_hashagg.c
test/expected/parallel-14.out
test/expected/parallel-15.out
test/expected/parallel-16.out
test/expected/parallel-17.out
test/expected/plan_hashagg-14.out
test/expected/plan_hashagg-15.out
test/expected/plan_hashagg-16.out
test/expected/plan_hashagg-17.out
test/sql/plan_hashagg.sql.in

In the past postgres would not create hashagg plans due to costing. This has been fixed upstream a couple major versions ago and this code is no longer required.

Remove custom hashagg code

---

.unreleased/pr_7432
src/bgw/job.c

In `ts_bgw_job_validate_job_owner` a heap tuple is fetched but it is
not verified that it is valid. If the heap tuple is later used it can
cause a crash at best, or leak information from random memory at worst.
Fixed this by adding a check that the tuple is valid before trying to
use it.

Verify that heap tuple is valid before using

---

tsl/test/expected/hypercore_stats.out
tsl/test/sql/hypercore_stats.sql

Execute an ANALYZE on relations to avoid flaky results in case of an autovacuum execution in background.
https://github.com/timescale/timescaledb/actions/runs/11769763355/job/32781276171#step:12:39

Fix hypercore stats flaky tests

---

.unreleased/pr_7412
src/guc.c
src/guc.h
tsl/src/bgw_policy/compression_api.h
tsl/src/compression/api.c
tsl/src/compression/api.h
tsl/test/expected/hypercore.out
tsl/test/expected/hypercore_create.out
tsl/test/expected/hypercore_vacuum.out
tsl/test/sql/hypercore_create.sql

Add the GUC `timescaledb.hypercore_use_access_method` for dealing with the default value to use for functions accepting the `hypercore_use_access_method` parameter (`compress_chunk`, `add_compression_policy`, etc.)
Value can be "on" (use the hypercore access method) or "off" (do not use the hypercore access method) and can be overridden by the parameter to the functions by explicitly providing a value. If no value is chosen, the default will be picked.

Add GUC for hypercore_use_access_method default

---

.unreleased/pr_7434
src/chunk.c
test/expected/create_chunks.out
test/sql/create_chunks.sql

The segfault happened executing `AlterTableInternal` for setting the REPLICA IDENTITY during chunk creation (introduced by https://github.com/timescale/timescaledb/issues/5512) that is dispatched by a trigger invoked by a DDL statement.
Fixed it by using our internal `ts_alter_table_with_event_trigger` handler function to setup the event trigger context.
Fixes #7406

Fix segfault when setting chunk replica identity

---

.unreleased/pr_7409
src/process_utility.c
tsl/test/expected/bgw_job_ddl.out
tsl/test/sql/bgw_job_ddl.sql

This deals with the following modifications to the name of a procedure 
used by a background job:
- If a procedure that exists in the jobs table is renamed, the corresponding names in the table will also be changed.
- When a procedure that is used for a background worker job is moved to a different schema, modify the job entry as well.
- When a schema is renamed, rename the schema name in the procedures as well.
- When a schema is dropped and there are procedures used by jobs, it will either remove the entry or throw an error, depending on whether `CASCADE` or `RESTRICT` is in effect.
- When a procedure or function used by a job is dropped, it will error out or delete the job depending on whether `CASCADE` or `RESTRICT` is in effect.

Update bgw job table when altering procedure

---

README.md

Clarified status of different platforms (cloud, docker, self-managed) for instructions on upgrading TimescaleDB given ABI incompatibility issue for the minor PG versions released 11-14-2024.

Update README with status around ABI issue

---

README.md

I actually don't understand *why* this is using a shortlink and not a real one. @billy-the-fish maybe you can shed some light?
In the meantime this can be merged to fix the dead link.

Fixed shortlink for release notes

---

tsl/src/compression/api.c
tsl/test/expected/hypercore.out
tsl/test/expected/hypercore_create.out
tsl/test/expected/hypercore_vacuum.out
tsl/test/sql/hypercore_create.sql

In a previous change, the parameter for using hypercore TAM when compressing a chunk changed, which also caused the compress_chunk() function to start emitting a notice when recompressing a chunk using Hypercore TAM. This message was meant to be emitted when recompressing and specifying an incompatible parameter option, but now it is emitted even when not specifying an option.
This change ensures the message is no longer emitted when recompressing, unless an incompatible option is specified. Also update the message to match the new parameter name.

Fix notice when recompressing hypercore TAM

---

src/ts_catalog/catalog.c
src/ts_catalog/catalog.h
tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/src/compression/compression.h

Functions `ts_catalog_open_indexes` and friends are just a copy of the corresponding PostgreSQL function `CatalogOpenIndexes`, so remove them and use these instead.

Remove unnecessary TimescaleDB functions

---

tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/test/expected/hypercore.out
tsl/test/expected/hypercore_create.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore.sql
tsl/test/src/CMakeLists.txt
tsl/test/src/test_hypercore.c

A truncate on a hypercore TAM table is executed across both compressed and non-compressed data. This caused an issue when recompressing because it tries to truncate also the compressed data. Fix this issue by introducing a flag that allows truncating only the non-compressed data.
Another issue releated to cache invalidation is also fixed. Since a recompression sometimes creates a new compressed relation, and the compressed relid is cached in the Hypercore TAM's relcache entry, the cache needs to be invalidated during recompression. However, this wasn't done previously leading to an error. This is fixed by adding a relcache invalidation during recompression.
Finally, compression using an index scan is disabled for Hypercore TAM since the index covers also compressed data (in the …

Fix issues with Hypercore TAM recompression

---

tsl/test/expected/compression.out
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression.sql
tsl/test/sql/compression_ddl.sql

Add vacuum to fix flaky tests

---

src/utils.c
src/utils.h
tsl/src/compression/api.c
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/utils.c
tsl/src/hypercore/utils.h
tsl/src/process_utility.c
tsl/test/expected/hypercore_create.out
tsl/test/sql/hypercore_create.sql

Autovacuum will run on all relations that are not explicitly disabled,
which can lead to unnecessarily vacuuming the compressed relation
inside the hypercore table access method twice: once as part of the
hypercore table access method and once as a separate relation.
This commit disables `autovacuum_enabled` for the compressed chunks
when the main chunk is turned into a hypercore access method chunk. It
deals with both the cases that you have a partially compressed chunk
and that you create a new compressed chunks as part of the conversion.

Disable autovacuum on compressed hypercore chunk

---

.github/workflows/windows-build-and-test.yaml

Since new versions of PostgreSQL can potentially break our CI and block development so we hardcode the version that we test against.

Hardcode minor version for Windows builds

---

tsl/test/expected/hypercore.out
tsl/test/sql/hypercore.sql

This adds basic tests for generated columns and columns with default values for tables using the Hypercore TAM.

Add tests for defaults and generated column values

---

.unreleased/pr_7455
src/process_utility.c
tsl/test/expected/compression_ddl.out
tsl/test/expected/hypercore_ddl.out
tsl/test/sql/compression_ddl.sql
tsl/test/sql/hypercore_ddl.sql

Remove the restriction on `ALTER TABLE ... ALTER COLUMN SET/DROP NOT NULL` on compressed tables.
Dropping or setting the `NOT NULL` constraint on a column of a compressed table is safe since it does not require re-writing any data. Setting `NOT NULL` will require a full table scan to verify that there are no NULL in the table.
Fixes #5776

Allow DROP NOT NULL on column of compressed table

---

src/utils.c
tsl/src/reorder.c

This change fixes the following:
[Add tuple locks when disabling autovacuum](https://github.com/timescale/timescaledb/commit/da32b25412eefa5ed71b64c1f8ba0af6a28b7db8)
A previous commit (https://github.com/timescale/timescaledb/commit/cbfd386c63842cb2779a8b598048381eb75a7db2) disabled autovacuum for internal
compressed relations when using Hypercore TAM, but it lacked the tuple
locks when updated pg_class that are now required by recent PG
versions.
Add the missing tuple locks to fix the issue. See commit https://github.com/timescale/timescaledb/commit/7e30ed65651ab5b0adee835f17829fa69a52382e for
more information.
[Remove lock check assertion for reorder](https://github.com/timescale/timescaledb/commit/dff09e7d55ca39db9d47a3da97fd2c0844cb0459)
A previous commit (7e30ed6) added an assertion …

Fix locking issues with new PG minor releases

---

tsl/src/compression/compression.c
tsl/src/hypercore/hypercore_handler.c

The tuple sort state used for compression was created with a reference to a tuple descriptor in a relcache entry. If this relcache entry is invalidated, the tuple sort state becomes corrupt. This caused occasional crashes when converting a chunk to using Hypercore TAM (i.e., compressing).
Fix this by always making a copy of the tuple descriptor when creating the tuple sort state.

Fix crash when converting to Hypercore TAM

---

tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/sql/cagg_ddl.sql.in

Recently Postgres updated time zone data files to tzdata2024b:
* 17.1: https://github.com/postgres/postgres/commit/cad65907ee
* 16.5: https://github.com/postgres/postgres/commit/a0c8d600bb
* 15.9: https://github.com/postgres/postgres/commit/74f70cb8633
* 14.14: https://github.com/postgres/postgres/commit/dedced73e00
In #7276 we forced our regression tests to explicit use PST8PDT timezone but for some reason on tzdata2024b it definition changed. The change is valid for dates before 1970 and this is exactly the case here for the CAgg watermark test outputs.
We're also noticing consistently failures in our CI:
* https://github.com/timescale/timescaledb/actions/runs/11883366631/job/33110029493#step:20:35
* https://github.com/timescale/timescaledb/actions/runs/11883366631/job/33110029375#step:2 …

Fix regression test output due to upstream changes

---

tsl/src/hypercore/arrow_array.c
tsl/test/expected/hypercore_scans.out
tsl/test/sql/hypercore_scans.sql

PG17 introduced a new Bump allocator for per-tuple memory contexts. Bump doesn't support pfree(), which caused an error when detoasting compressed data on the per-tuple memory context since the detoasting needs to scan some catalog tables.
Make sure Hypercore TAM always detoasts on a temporary memory to fix this issue and add a test for it.

Don't detoast compressed data on Bump memory context

---

src/process_utility.c
tsl/src/hypercore/utils.c
tsl/test/expected/compression_ddl.out
tsl/test/expected/compression_errors-14.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/expected/compression_errors-17.out
tsl/test/expected/hypercore_ddl.out
tsl/test/sql/compression_ddl.sql
tsl/test/sql/hypercore_ddl.sql

Since `SET NOT NULL` will only do a full table scan of the table to verify that there are no nulls, this should work without having to modify any data in the table. However, since the command does a `table_beginscan` it does not work for hypertables with compressed chunks that uses the `heap` table access method.

Allow SET NOT NULL on column of compressed table

---

tsl/src/compression/api.c
tsl/src/compression/compression.c
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/test/src/test_hypercore.c

Replace the scankey flag used to skip compressed data when starting a Hypercore scan with a function that sets this option on the scan descriptor. Internally, use the scan flags instead of scankey flags to convey this setting.
Overloading scankey flags was not ideal since this is supposed to be per-column settings and not overall scan settings.
Note that it is possible to set the scan flags when calling the TAM's beginscan callback, but the table_beginscan() wrapper does not expose flags and instead there's a separate function for each flag settings. Hypercore could define its own beginscan function to do the same, but this is left for the future.

Refactor option to skip compressed in Hypercore TAM scans

---

tsl/src/nodes/vector_agg/function/float48_accum_single.c
tsl/src/nodes/vector_agg/function/int24_avg_accum_templates.c

We can inline the few lines of code required to create an array, instead of calling the very generic `construct_array` function which shows up in profiles.

Optimize array creation in vectorized aggregate functions

---

tsl/src/nodes/vector_agg/exec.c
tsl/src/nodes/vector_agg/plan.c
tsl/test/expected/vector_agg_memory.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/vector_agg_memory.sql

It is enough to use the per-tuple context for them, now they end up in the ExecutorState context which is incorrect.

Put vectorized aggregation results in short-lived memory context

---

tsl/src/hypercore/hypercore_handler.c
tsl/test/expected/hypercore.out
tsl/test/sql/hypercore.sql

Concurrent index builds are not supported for hypertables at all, so this just adds tests that it fails with an error both when attempting it on a hypertable and on a chunk using the `hypercore` table access method.

Add test for concurrent index builds for hypercore

---

tsl/src/hypercore/hypercore_handler.c

In #7467 we added a `RelationCacheInvalidate(false)` but on upstream this API changed on PG14.1 by postgres/postgres@dde966e.
We build agains first minor release in our nightly CI and also on ABI tests so make sure we're using the right function call based on the Postgres version we're building against.
https://github.com/timescale/timescaledb/actions/runs/11943958854/job/33294019881#step:12:360

Fix building against PG14.0

---

tsl/src/hypercore/arrow_tts.h

We ensure that we do not lose part of the block number when shifting it to fit in the upper part of the block number of the encoded TID.

Add check that TID range is not exhausted

---

.unreleased/pr_7104

The changelog entry for the Hypercore TAM pointed to the wrong PR, so fixing.

Fix changelog reference

---

.github/workflows/pr-approvals.yaml

Team agreed that changes to Hypercore table access method files only require a single approver for the time being. This might be revised in the future.

Fix Hypercore PR approval

---

src/guc.c
src/guc.h
test/sql/utils/pg_dump_aux_dump.sh
tsl/src/compression/api.c
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/src/process_utility.c
tsl/test/expected/hypercore_dump_restore.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore_dump_restore.sql

Add support for dumping and restoring hypertables that have chunks that use the Hypercore TAM.
Dumping a Hypercore table requires special consideration because its data is internally stored in two separate relations: one for compressed data and one for non-compressed data. The TAM returns data from both relations, but they may be dumped as separate tables. This risks dumping the compressed data twice: once via the TAM and once via the compressed table in compressed format.
The `pg_dump` tool uses `COPY TO` to create dumps of each table, and, to avoid data duplication when used on Hypercore tables, this change introduces a GUC that allows selecting one of these two behaviors:
1. A `COPY TO` on a Hypercore table returns all data via the TAM, including data stored in the compressed relation. …

Add dump/restore support for Hypercore TAM

---

.github/workflows/windows-build-and-test.yaml
.unreleased/pr_7486
src/compat/compat.h

Prevent building against pg versions with broken ABI

---

.unreleased/pr_7488
src/process_utility.c
test/expected/triggers.out
test/sql/triggers.sql

If a transition table trigger is added to a hypertable, an error is generated indicating that this is not supported. However, if it is added to a chunk, it is accepted but generates an assertion failure in debug builds.
Instead, we generate an error when an attempt is made to add a transition table trigger to a chunk of a hypertable, regardless of whether the compression flag is set or not.
Fixes #7487

Emit error on transition table trigger for chunks

---

.github/workflows/windows-build-and-test.yaml

Use version on Windows from config generated file

---

tsl/test/expected/hypercore_trigger.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore_trigger.sql

Add tests for statement and row triggers on hypercore chunks. We test `INSERT`, `UPDATE`, `DELETE`, and `TRUNCATE` triggers, where applicable. We check that the `OLD` and `NEW` values are correct as well as that the statement and row triggers are executed the correct number of times.

Add hypercore chunk tests for triggers

---

.github/workflows/abi.yaml

Versions of the extension cannot be expected to always work in the backwards direction so we cannot reliably test that builds against later versions of PostgreSQL (e.g., 17.3) work with earlier versions (e.g., 17.0) if new functions are introduced in the later version.

Remove backward direction for ABI tests

---

tsl/test/expected/cagg_permissions-14.out
tsl/test/expected/cagg_permissions-15.out
tsl/test/expected/cagg_permissions-16.out
tsl/test/expected/cagg_permissions-17.out
tsl/test/sql/cagg_permissions.sql.in

We missed to re-enable ON_ERROR_STOP after some failed tests.

Fix CAgg permissions regression leftovers

---

tsl/test/expected/jit.out
tsl/test/sql/jit.sql

Disable hash aggregate to avoid flaky test output.

Fix flaky jit regression test

---

src/ts_catalog/continuous_aggs_watermark.c

It is not necessary to invalidate the relation cache during the watermark update if the GUC `enable_cagg_watermark_constify=false`. Was a leftover when the feature was introduced by #6325.

Don't invalidate relation cache if cagg watermark constify is false

---

tsl/test/expected/reorder.out
tsl/test/sql/reorder.sql

Execute manual `VACUUM` on the hypertable before reordering a chunk to avoid flaky test output.

Fix flaky reorder regression test

---

tsl/src/compression/api.c

PostgreSQL versions prior to 15.4 didn't properly update object dependencies when setting a new access method on a table. The fix for the bug is found in this commit:
https://github.com/postgres/postgres/commit/97d89101045fac8cb36f4ef6c08526ea0841a596
The `hypercore_create` test failed on buggy PG versions (e.g., 15.0) due to wrong contents of pg_depend showing up in test output when converting a table from Hypercore TAM back to regular heap.
This change adds a workaround that updates pg_depend with the correct information when compiling against PG versions that suffer from the bug.

Add workaround for pg_depend bug in PG < 15.4

---

test/runner.sh
test/runner_cleanup_output.sh
test/runner_isolation.sh
test/runner_shared.sh

Encapsulate runner output cleanup into single script

---

tsl/test/expected/hypercore_constraints.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore_constraints.sql

Add tests that exclude constraints work on Hypercore TAM tables. This
is right now limited to BTree indexes for the hypertable, but we add a
GiST exclusion constraint on a chunk and test that it works.
Disable-check: force-changelog-file, approval-count

Add tests for exclude constraints on Hypercore TAM

---

test/expected/append-14.out
test/expected/append-15.out
test/expected/append-16.out
test/expected/append-17.out
test/sql/include/append_load.sql
test/sql/include/append_query.sql

Fixed it by manually running `VACUUM ANALYZE` in all involved hypertables to avoid flaky output tests.
https://github.com/timescale/timescaledb/actions/runs/12128976291/job/33819502944?pr=7505#step:17:23

Fix flaky append regression test

---

scripts/upload_ci_stats.sh

This adds a generated column for extracting the version from the job name. It will read anything that matches `PG<number><alphanumeric>` or `PG<number>.<number>` and generate a version string. If the first pattern matches, it will generate `<number>.x` as string, signifying that this is an unknown minor version.
Disable-check: force-changelog-file, approval-count

Modify flakes table for jobs

---

.unreleased/pr_6901
src/copy.c
src/hypertable.c
src/planner/planner.c
src/process_utility.c
src/trigger.c
src/trigger.h
test/expected/triggers.out
test/sql/triggers.sql
tsl/test/expected/hypercore_trigger.out
tsl/test/sql/hypercore_trigger.sql

This adds support for using statement-level triggers with transition tables to hypertables. We deliberately do not support statement-level nor row-level triggers with transition tables on chunks and error out if attempts are made to either add such triggers to a chunk or create a hypertable from a table with such triggers.
We also change the error messages to look more like the corresponding PostgreSQL error message.

Add support for transition tables

---

tsl/test/expected/hypercore_index_btree.out
tsl/test/sql/hypercore_index_btree.sql

Unlike regular compressed tables, Hypercore TAM supports creating unique indexes after compression is enabled. Add tests for this use case.

Add tests for unique index creation with Hypercore TAM

---

.unreleased/pr_7514
src/nodes/chunk_append/planner.c

When doing startup and runtime chunk exclusion, the chunk append node could sometimes throw an error: "invalid child of chunk append: Sort". Unfortunately, this error hasn't been successfully reproduced in a test but has been reported by users.
However, it seems clear that the error happens in
ts_chunk_append_get_scan_plan() when it can't find a "known" plan node to use for chunk exclusion. This function should ideally never throw and error and instead just return NULL, which means that chunk append falls back to not doing any exclusion instead of throwing an error.
It is also possible to improve the code and make it properly handle Sort and Result nodes by not special-casing them. By inspecting ts_chunk_append_get_scan_plan(), it is clear that it can only throw the error if it encounters …

Fix error: invalid child of chunk append

---

tsl/src/continuous_aggs/materialize.c

Refactor continuous aggregate materialization code
In addition to the code reorganization and simplification we changed it by splitting the query execution in multiple steps taking advantage of `SPI_prepare`, `SPI_execute_plan` and `SPI_freeplan`:
* create_materialization_plan(PlanType)
* execute_materialization_plan(PlanType)
* free_materialization_plan(PlanType)
This PR is in preparation for a following PR to execute the materialization in small batches to alleviate the I/O spikes when reading and writing many buckets.

Refactor continuous aggregate materialization code

---

tsl/src/continuous_aggs/materialize.c

In #7505 we used PG_TRY() .. PG_FINALLY() but some CI configurations was not happy with it reporting "variable might be clobbered by longjmp".
Fixed it by using PG_TRY() .. PG_CATCH() instead.
https://github.com/timescale/timescaledb/actions/runs/12277548387/job/34257269473#step:13:206

Fix compiler error when using PG_TRY..PG_FINALLY

---

.github/workflows/snapshot-abi.yaml

This adds a test to check the ABI compatibility with PG snapshot. Timescaledb is built against the mininum abi version of postgres supported, for each major version of PG and tested against the latest snapshot.

Add ABI test against PG snapshot

---

tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_migrate_function-14.out
tsl/test/expected/cagg_migrate_function-15.out
tsl/test/expected/cagg_migrate_function-16.out
tsl/test/expected/cagg_migrate_function-17.out
tsl/test/expected/cagg_query-14.out
tsl/test/expected/cagg_query-15.out
tsl/test/expected/cagg_query-16.out
tsl/test/expected/cagg_query-17.out
tsl/test/expected/cagg_query_using_merge-15.out
tsl/test/expected/cagg_query_using_merge-16.out
tsl/test/expected/cagg_query_using_merge-17.out
tsl/test/expected/cagg_utils.out
tsl/test/sql/CMakeLists.txt

In #7042 we refactored the code for getting the time bucket function info to read information from the stored query tree on Postgres metadata.
But when an origin was not specified it was returning a wrong value instead of NULL. Fixed it by properly dealing with non-defined origin and also simplified a bit the code to process time bucket parameters.

Fix wrong origin returned by cagg_get_bucket_function_info

---

scripts/clang_format_wrapper.sh

https://github.com/timescale/timescaledb/actions/runs/12358516263/job/34489217274?pr=7538#step:4:7

Disable false positive warning on shellcheck

---

tsl/src/hypercore/arrow_cache_explain.c
tsl/test/expected/hypercore_columnar.out
tsl/test/expected/hypercore_constraints.out
tsl/test/expected/hypercore_copy.out
tsl/test/expected/hypercore_create.out
tsl/test/expected/hypercore_cursor.out
tsl/test/expected/hypercore_index_btree.out
tsl/test/expected/hypercore_index_hash.out
tsl/test/expected/hypercore_insert.out
tsl/test/expected/hypercore_join.out
tsl/test/expected/hypercore_merge.out
tsl/test/expected/hypercore_parallel.out
tsl/test/expected/hypercore_scans.out
tsl/test/expected/hypercore_stats.out
tsl/test/expected/hypercore_trigger.out
tsl/test/expected/hypercore_types.out
tsl/test/expected/hypercore_update.out
tsl/test/expected/hypercore_vacuum_full.out
tsl/test/sql/hypercore_scans.sql
tsl/test/sql/include/hypercore_helpers.sql

Use a more compact and easy to read version for the decompression and arrow array cache stats and simplify the code.
The style is copied from the style for showing Buffer information in standard PostgreSQL.

Use brief explain stats

---

src/cross_module_fn.h
src/nodes/chunk_dispatch/chunk_dispatch.c
src/nodes/hypertable_modify.c
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/src/init.c

When a conflict-do-update statement executes on a Hypercore TAM table, the conflicting TID (and slot) can point to a "row" in a compressed segment. Therefore, it is possible to directly decompress the conflicting segment before executing the update statement.
In contrast, the existing on-conflict handling for compression doesn't have a unique index that points to the conflicting tuple, so it first needs to scan for a conflicting segment on the compressed chunk, which might, in some cases, be a full sequence scan on the compressed chunk, and decompression of the segments that might conflict.
On a synthetic test case, the improvements to upserts are significant, about 32x faster execution time for a single row upsert, while buffers read is reduced by 2220x. This makes the upsert performance …

Optimize conflict do update (upserts) on Hypercore TAM

---

.github/workflows/apt-arm-packages.yaml

GitHub Actions using `ubuntu-latest` have been changed to use `ubuntu-24.04` instead by default (https://github.com/actions/runner-images/issues/10636) which breaks our APT-ARM64 package workflow. This pins the version back to `ubuntu-22.04` to avoid this.

Pinned Ubuntu version in package workflow to 22.04

---

.github/workflows/homebrew.yaml

Tests are pinned to Postgres v16, Homebrew installs timescaledb for version 17.

Fix for failing Homebrew tests

---

.unreleased/pr_7557
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/compression/compression_scankey.c
tsl/src/compression/recompress.c
tsl/test/shared/expected/compression_nulls_not_distinct.out
tsl/test/shared/sql/compression_nulls_not_distinct.sql

During DML decompression, we filter out batches that don't need decompression using in-memory filtering which filters compressed tuples using scankeys. Those scankeys were not detecting NULL values correctly for unique constraints which use NULLS NOT DISTINCT setting. This change uses existing codebase to properly detect those tuples when using SK_ISNULL flag.

Fix NULL handling for in-memory tuple filtering

---

.github/gh_matrix_builder.py

In some places we didn't pass the top-level config overrides to the lowest level debug config builder, which can result in config values being overwritten in an unexpected ways.

Use config overrides more systematically in matrix builder

---

src/guc.c

Somehow the hypercore supported am function ended up under
#ifdef TELEMETRY, so some rare build configurations are failing.
Since this is a cosmetic change in Hypercore:

Move function from under a wrong ifdef

---

.github/workflows/docker-images.yaml

Bitnami removed support for LTS branches. For us this means only
PG17 will get postgres version updates. So this PR removes the
images for previous branches from CI test.
https://github.com/bitnami/containers/issues/75671
This patch also adds missing timescaledb-ha:pg17 image to the tests.

Remove no longer supported bitnami images from CI

---

.github/workflows/linux-32bit-build-and-test-ignored.yaml
.github/workflows/linux-32bit-build-and-test.yaml

PG17 is included by default now so we dont need to explicitly add it to matrix anymore.

Remove redundant PG17 entry from build matrix

---

.github/workflows/pr-handling.yaml

Since changing the default permissions of the GITHUB_TOKEN this workflow was failing with insufficient permissions.

Remove permission section from pr handling workflow

---

tsl/src/continuous_aggs/materialize.c

In #7505 we refactored the materialization code but the debugging query was removed by accident.

Add missing elog(DEBUG2,...) after refactoring

---

.unreleased/pr_7517
sql/cagg_migrate.sql
sql/updates/reverse-dev.sql
tsl/test/expected/cagg_migrate.out
tsl/test/shared/expected/compat.out
tsl/test/shared/expected/extension.out

When creating the migration plan we need to figure out the boundaries (min and max) of the primary dimension to split the COPY data into multiple transactions to don't exauste the instance resources.
The problem is we're reading the boundaries direct from the CAgg view and when the realtime is enabled it lead to big performance penalty (this was one of the reasons for the new format).
Also in the `COPY DATA` migration plan step we changed the batch size used that previously was based on the materialization hypertable partition range and now will be the Continuous Aggregate bucked size multiplied by 10 (ten).
Fixed it by querying direct the materialization hypertable instead.
Also in ef2cfe3f we introduced a problem that now we're not explicitly updating the watermark but instead warning …

Fix CAgg migration performance regression

---

tsl/test/shared/expected/ordered_append_join-14.out
tsl/test/shared/expected/ordered_append_join-15.out
tsl/test/shared/expected/ordered_append_join-16.out
tsl/test/shared/expected/ordered_append_join-17.out
tsl/test/shared/sql/ordered_append_join.sql.in

The test only checks what index is chosen and the choice between index and index only scans generate different plans as a result of external factors such as the platform it executes on.

Disable index only scan for ordered append test

---

.unreleased/pr_7565
src/indexing.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

When creating a hypertable, we create default indexes on the partition column, which requires that the column be a part of the table's primary or composite key. The error message shown to the user in this scenario did not indicate this correctly. This adds a hint to make this clearer.
Closes #2907.

Add hint when hypertable creation fails

---

src/bgw/job_stat_history.c

In #6767 we introduced the ability to track job execution history, but looks like we exaggerated the lock level when marking the end of the job execution using `ShareRowExclusiveLock` that conflicts with autovacuum jobs that requires an `ShareUpdateExclusiveLock`, so relaxing the lock to `RowExclusiveLock` because we only update the tuple in the job execution history metadata table.

Relax lock when updating job history information

---

.unreleased/pr_7584
tsl/src/nodes/vector_agg/function/minmax_arithmetic_single.c
tsl/src/nodes/vector_agg/function/minmax_templates.c
tsl/test/expected/vector_agg_functions.out
tsl/test/sql/vector_agg_functions.sql

The vector agg functions didn't handle NaN-floats properly for min/max functions, which produced the wrong `min()` output when NaN values were presents (e.g., picking NaN over -Inf). NaN-checks are different for min and max so the checks are moved to the predicate macro instead of being defined in the template function.
The previously erroneous handling of NaN is evident by some of the changes in the test output. However, some queries didn't run any actual vectorized agg plans when they should have, thus "accidentally" producing the correct min result in the test file. In those cases, instead of the vectorized plan, the test ran an init plan doing a sort with a limit of 1 to find the min. Disabling sort in the test ensures the plan is vectorized, and thus producing the erroneous result …

Fix NaN-handling for vectorized aggregation

---

tsl/src/compression/api.c

A previous change (commit 8d29760) added a workaround for a PostgreSQL bug related to table access methods that was fixed in PG 15.4. The workaround does a build-time check for the PG version to apply the fix, but this won't work across PG server upgrades.
To avoid raising an error when running an extension compiled on PG < 15.4 on PG 15.4+, add also a runtime check.

Fix ABI issue when upgrading PG from 15.3 to 15.4+

---

.unreleased/pr_7521
sql/ddl_api.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
tsl/src/bgw_policy/job.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_refresh.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/expected/chunk_utils_internal.out
tsl/test/shared/expected/extension.out
tsl/test/sql/chunk_utils_internal.sql
tsl/test/sql/include/cagg_refresh_common.sql

Following the [SDC](https://github.com/timescale/Support-Dev-Collab/issues/2331). Continuous aggregates that are built on top of tiered hypertables cannot access and materialize tiered data when the `timescaledb.enable_tiered_reads` GUC is disabled at the server level. And there is no way for a user to manually force the refresh with tiered reads enabled. Here we add an optional `force` parameter to the `refresh_continuous_aggregate` procedure that would allow user to partially re-materialize cagg within a time window that has already been materialized.

Add optional `force` argument to `refresh_continuous_aggregate`

---

.unreleased/pr_7436
tsl/src/compression/api.c
tsl/src/compression/compression_storage.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/compression_ddl.out
tsl/test/expected/compression_indexcreate.out
tsl/test/expected/compression_insert.out
tsl/test/expected/compression_qualpushdown.out
tsl/test/expected/compression_sequence_num_removal.out
tsl/test/expected/compression_update_delete-14.out
tsl/test/expected/compression_update_delete-15.out
tsl/test/expected/compression_update_delete-16.out
tsl/test/expected/compression_update_delete-17.out
tsl/test/expected/hypercore_vacuum.out
tsl/test/expected/telemetry_stats.out
tsl/test/expected/vector_agg_default.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression_indexcreate.sql

Previously, for chunks without a segmentby column specified in the compression settings, no indexes were created. This change allows indexes to be created on orderby columns only in this scenario.

Add index creation on orderby columns

---

src/hypertable.c
src/hypertable.h
src/process_utility.c
tsl/src/compression/create.c
tsl/test/expected/compression_trigger.out
tsl/test/expected/hypercore_trigger.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression_trigger.sql
tsl/test/sql/hypercore_trigger.sql

DELETE triggers cannot be supported for compressed tables not using the hypercore table access method since it can delete an entire compressed segment and a transition table is not built for this case, so generating an error instead.
This commit also adds a bunch of tests for triggers with transition tables for normal compressed tables and extend the hypercore trigger tests.

Add error for DELETE triggers with transition tables

---

.unreleased/pr_7587
sql/policy_api.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/guc.h
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/continuous_aggregate_api.h
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job.h
tsl/src/bgw_policy/policies_v2.c
tsl/src/bgw_policy/policies_v2.h
tsl/test/expected/chunk_utils_internal.out
tsl/test/shared/expected/extension.out
tsl/test/sql/chunk_utils_internal.sql

~This PR doesn't contain any API changes yet (to be discussed).~
Refresh policy now includes or excludes tiered data based on policy's `include_tiered_data` config parameter regardless of the `timescaledb.enable_tiered_reads` GUC:
```json
{
"end_offset": "1 day",
"start_offset": "6 months",
"mat_hypertable_id": 43,
"enable_tiered_reads": true
}
```
**EDIT:**
Added the API change too:
```sql
SELECT add_continuous_aggregate_policy(
'ht_try_weekly',
start_offset => '6 months'::interval,
end_offset => '1 hour'::interval,
schedule_interval => '1 hour'::interval,
include_tiered_data => true
);

Add a cagg config parameter to override the instance-level `timescaledb.enable_tiered_reads` GUC

---

.unreleased/pr_7566
src/process_utility.c
src/process_utility.h
tsl/src/continuous_aggs/refresh.c
tsl/test/expected/cagg_refresh.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/include/cagg_refresh_common.sql

Intro: Hi, I was investigating an issue with `portal snapshots (0) did not account for all active snapshots (1)` error inside another Postgres extension ([wdb-97](https://github.com/wiltondb/wiltondb/issues/97), unrelated to Timescale) and stumbled upon the #6533 issue in Timescale that was reporting the same error. Decided to have a deeper look into it.
This PR allows better error messages to be reported from `refresh_continuous_aggregate` when it is called from an atomic (no transaction allowed) context. One of the following messages:
- `ERROR:  refresh_continuous_aggregate() cannot run inside a transaction block`
- `ERROR:  refresh_continuous_aggregate() cannot be executed from a function`
is reported now instead of: `ERROR: portal snapshots (N) did not account for all active snapshots …

Improve transaction check in refresh_cagg

---

.unreleased/pr_7433
sql/maintenance_utils.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/chunk.c
src/chunk.h
src/chunk_constraint.c
src/chunk_constraint.h
src/compat/compat.h
src/cross_module_fn.c
src/cross_module_fn.h
src/dimension.h
src/dimension_slice.h
src/hypercube.h
tsl/src/chunk.c
tsl/src/chunk.h
tsl/src/init.c
tsl/src/reorder.c
tsl/test/expected/merge_chunks.out
tsl/test/isolation/expected/merge_chunks_concurrent.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/merge_chunks_concurrent.spec
tsl/test/shared/expected/extension.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/merge_chunks.sql

New procedures to `merge_chunks` are introduced that can merge an arbitrary number of chunks if the right conditions apply. Basic checks are done to ensure that the chunks can be merged from a partitioning
perspective. Some more advanced cases that are potentially mergeable are not supported at this time (e.g., complicated merges of chunks with multi-dimensional partitioning) and merging of compressed chunks.
Merging compressed chunks requires additional work, although the same basic rewrite approach should work also on the internal compressed relations. Still, one needs to handle merge of a compressed chunk with a non-compressed chunk, or two compressed chunks with different compression settings, and so forth. This is left for a future enhancement.
Currently, the merge defaults to taking …

Add support for merging chunks

---

tsl/src/chunk.c

When merging chunks, a relation size calculation could potentially overflow an 32-bit integer value. Use a 64-bit integer for the result to prevent overflow.

Fix potential int overflow in merge chunks

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml

Upload CMake logs to the action artifacts

---

.github/workflows/docker-images.yaml
.github/workflows/release_build_packages.yml

Remove bitnami from docker test and release workflow

---

tsl/src/hypercore/CMakeLists.txt
tsl/src/hypercore/arrow_tts.c
tsl/src/hypercore/arrow_tts.h
tsl/src/hypercore/vector_quals.c
tsl/src/hypercore/vector_quals.h
tsl/src/nodes/columnar_scan/columnar_scan.c
tsl/src/nodes/columnar_scan/columnar_scan.h

Move the code for vector qual execution to its own module. The vector qual execution will produce a result in the form of a bitmap filter for the arrow array. Add functions to the arrow slot to carry the result bitmap in the arrow tuple table slot. This allows passing the filter result to nodes above the node that computed the vector qual result. This is necessary to, e.g., run vectorized aggregation above a columnar scan.

Refactor vector qual handling for arrow slots

---

.github/workflows/windows-build-and-test.yaml
scripts/clang_format_all.sh
tsl/CMakeLists.txt
tsl/src/import/CMakeLists.txt
tsl/src/import/umash.c
tsl/src/import/umash.h

We use it for vectorized hash grouping. For now, add the library separately to figure out the required CMake and CI changes.

Import the UMASH hashing library

---

.github/workflows/update-test.yaml
cmake/GenerateScripts.cmake

This patch adjusts the downgrade script generation to not include
incompatible files from the 2.18.0 release that would break script
generation and replaces them with a working version. This adjustment
can be removed after we release of 2.18.1.
This patch also reenables the downgrade test.

Fix downgrade path for 2.18.0

---

.github/workflows/abi.yaml
.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml
.github/workflows/coverity.yaml
.github/workflows/docker-images.yaml
.github/workflows/homebrew.yaml
.github/workflows/libfuzzer.yaml
.github/workflows/rpm-packages.yaml
.github/workflows/sanitizer-build-and-test.yaml
.github/workflows/snapshot-abi.yaml
.github/workflows/update-test.yaml
.github/workflows/windows-build-and-test.yaml
.github/workflows/windows-packages.yaml

This is mostly to allow triggering package tests directly from
github UI but no harm enabling it for a couple more.

Allow more workflows to be triggered by github ui

---

.github/workflows/catalog-updates-check.yaml
scripts/check_sql_script.py
scripts/check_updates_ast.py
sql/metadata.sql

To detect the problematic patterns that were part of the 2.18 release
we can check the sql scripts against a list of allowed statements.
Any non idempotent operation should be in the pre_install scripts
and not the scripts that get appended for the update scripts.

Add ci check for idempotency in sql scripts

---

cmake/GenerateScripts.cmake

Since we only support generating downgrade script for the previous
version anything targeting versions before 2.18 will never be
executed in current context. So we can safely remove the code that
deals with version before 2.3.

Remove some dead code from downgrade script generation

---

.unreleased/pr_7600
src/chunk_index.c
tsl/test/isolation/expected/deadlock_drop_index_vacuum.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/deadlock_drop_index_vacuum.spec

If an index is dropped, it is necessary to lock the heap table (of
the index) before the index since all normal operations do it in this
order. When dropping an index, we did not take all the necessary locks
in the right order before calling `performMultipleDeletions`, which can
cause deadlocks when dropping an index on a hypertable at the same time
as running a utility statement that takes heavy locks, e.g., VACUUM or
ANALYZE.
Adding a isolation test as well that will generate a deadlock if the
index and table locks are not taken in the correct order.

Fix lock order when dropping index

---

tsl/src/nodes/vector_agg/exec.c
tsl/src/nodes/vector_agg/grouping_policy.h
tsl/src/nodes/vector_agg/grouping_policy_batch.c
tsl/src/nodes/vector_agg/grouping_policy_hash.c
tsl/src/nodes/vector_agg/hashing/batch_hashing_params.h
tsl/src/nodes/vector_agg/hashing/hash_strategy_common.c
tsl/src/nodes/vector_agg/hashing/hash_strategy_impl.c
tsl/src/nodes/vector_agg/hashing/hash_strategy_impl_single_fixed_key.c
tsl/src/nodes/vector_agg/hashing/hashing_strategy.h
tsl/src/nodes/vector_agg/vector_slot.h

To support VectorAgg on top of Hypercore TAM, change the vector agg processing functions to pass around tuple table slots instead of compressed batches. This makes it possible to pass any "compatible" "vector slot" to the vector agg functions, which is required since TAM uses a slightly different slot implementation for arrow/vector data.
In addition, add some functions to handle reading vector data from compatible vector slot implementations. This commit only adds the code to read from compressed batches. Arrow slots will be supported as part of a later change.

Refactor VectorAgg to use TupleTableSlot interface

---

.unreleased/pr_7637
src/process_utility.c
tsl/test/expected/read_only.out
tsl/test/sql/read_only.sql

Using `EXPLAIN` when `transaction_read_only` is set to `on` fails with an error. This is fixed by explicitly setting the `check_read_only` flag.
Fixes #7635

Allow EXPLAIN in read-only mode

---

.unreleased/pr_7645
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/compression/compression_scankey.c
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/sql/compression_dml.sql

When deleting from compressed chunk the direct delete optimization
would ignore constraints that were not using btree operators
leading to constraints of the DELETE not being applied to the
direct delete on the compressed chunk, potentially leading to
data corruption. This patch disables the direct delete optimization
when any of the constraints can not be applied.
Fixes #7644

Fix DELETE on compressed chunk with non-btree operators

---

tsl/src/compression/algorithms/dictionary.c
tsl/src/compression/algorithms/dictionary_hash.h

This speeds up the compression.
The recompression of the hackers mailing list archive is now almost 40% faster: https://grafana.ops.savannah-dev.timescale.com/d/fasYic_4z/compare-akuzm?orgId=1&var-branch=All&var-run1=4085&var-run2=4086&var-threshold=0.02&var-use_historical_thresholds=true&var-threshold_expression=2%20%2A%20percentile_cont%280.90%29&var-exact_suite_version=false&from=now-2d&to=now

Store hash value in hash table in dictionary compressor

---

tsl/src/nodes/vector_agg/exec.c
tsl/src/nodes/vector_agg/exec.h

The VectorAgg exec loop reads tuples directly from a compressed relation, thus bypassing the DecompressChunk child node. This won't work with arrow slots, which are read via a table access method.
To make the VectorAgg exec code similar to the standard pattern of reading slots from child nodes, code specific to decompressing batches is moved out of the main VectorAgg exec loop so that the loop only deals with the final compressed batch slot instead of the raw compressed slot. The code is instead put in a "get_next_slot" function, which is called from the loop.
Also move the code to initialize vectorized filters to its own "init_vector_qual" function, since it is specific to compressed batches.
With these two function interfaces, it is possible to provide implementations of the functions …

Prepare VectorAgg exec path to handle arrow slots

---

.unreleased/pr_7649
tsl/src/compression/compression_scankey.c
tsl/test/shared/expected/compression_dml.out
tsl/test/shared/sql/compression_dml.sql

When pushing down expressions into the compressed scan we assumed
all valid expressions use btree operators and dropped any that weren't.
This patch changes the behaviour to keep those expressions and use
them as heap filter on the compressed scan for UPDATE and DELETE
on compressed chunks.

Allow non-btree operator pushdown in UPDATE/DELETE queries on compressed chunks

---

scripts/backport.py

Depending on the branch protection settings, we might have to update them before they can be merged, so do this automatically to minimize the required manual work.

Update existing backports in the backport script

---

.unreleased/pr_7653
src/guc.c
src/guc.h
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/src/nodes/columnar_scan/columnar_scan.c
tsl/test/expected/hypercore_dump_restore.out
tsl/test/expected/hypercore_scans.out
tsl/test/sql/hypercore_scans.sql

Quals on orderby columns can be pushed down to Hypercore TAM and be transformed to the corresponding min/max scankeys on the compressed relation. Previously, only quals on non-compressed segmentby columns were pushed down as scankeys.
Pushing down orderby scan keys seem to give a good performance boost for columnar scans when no index exists.
The scankey push down can be disabled with a new GUC:
`timescaledb.enable_hypercore_scankey_pushdown=false`
Closes: #7652

Push down orderby scankeys to Hypercore TAM

---

.unreleased/pr_7656
tsl/src/bgw_policy/compression_api.c
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_policy.out
tsl/test/sql/cagg_errors.sql
tsl/test/sql/cagg_policy.sql

Before compressed chunks were mutable, adding a compression policy to a continuous aggregate that could include portions of the refrsh window were blocked. When a continuous aggregate is refreshed, the underlying chunks needed to allow DELETEs and INSERTs, so they could not be compressed. Now, compressed chunks allow both operations and there is no longer a need to prevent the refresh window and compression window from overlapping.
Closes #7021

Remove limitation of compression policy for continuous aggregates

---

tsl/src/hypercore/arrow_tts.h
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/vector_quals.c
tsl/src/nodes/columnar_scan/columnar_scan.c
tsl/test/expected/hypercore_scans.out
tsl/test/sql/hypercore_scans.sql

When filtering arrow slots in ColumnarScan, quals on segmentby columns should be executed separately from those on other columns because they don't require decompression and might filter the whole arrow slot in one go. Furthermore, the quals only need to be applied once per arrow slot since the segmentby value is the same for all compressed rows in the slot.
This will speed up scans when filters on segmentby columns cannot be pushed down to Hypercore TAM as scankeys. For example, "<column> IN (1, 2, 3)" won't be pushed down as a scankey because only index scans support scankeys with such scalar array expressions.

Optimize quals on segmentby columns in ColumnarScan

---

.github/workflows/windows-packages.yaml

Since we depend on the openssl version of the postgres installer
to match the openssl version we built against and we can't ensure
stability of that version in the postgres installer we only test
windows package against the latest available postgres version.

Adjust windows package test CI

---

tsl/test/expected/bgw_scheduler_restart.out
tsl/test/sql/bgw_scheduler_restart.sql

- **Fix flaky bgw scheduler test**

Fix flaky bgw scheduler test

---

.unreleased/pr_7637

Since we split the fixes and thanks messages into separate sections
in the changelog the context between fix and thanks will be lost so
the thanks note should repeat any required context

Improve metadata for PR 7637

---

.unreleased/pr_7673
src/nodes/hypertable_modify.c
tsl/test/expected/compression_conflicts.out
tsl/test/sql/compression_conflicts.sql

When an INSERT with ON CONFLICT DO NOTHING hits the first conflicts
it would abort additional INSERTS following the INSERT triggering
the DO NOTHING clause leading to missed INSERTs.
Fixes #7672

Don't abort additional INSERTs when hitting first conflict

---

.unreleased/pr_7665
src/chunk.c
src/chunk.h
tsl/src/chunk.c
tsl/test/expected/merge_chunks.out
tsl/test/sql/merge_chunks.sql

It should not be possible to merge a frozen chunk since it is used to tier chunks. If the chunk is merged, it might no longer exist when the tiering happens.

Block merging of frozen chunks

---

tsl/test/expected/merge_append_partially_compressed-14.out
tsl/test/expected/merge_append_partially_compressed-15.out
tsl/test/expected/merge_append_partially_compressed-16.out
tsl/test/expected/merge_append_partially_compressed-17.out
tsl/test/sql/merge_append_partially_compressed.sql.in

Make the column sets used for ordering unique, otherwise the resulting order depends on the plan.

Disambiguate the merge_append_partially_compressed test

---

.unreleased/nan-vectorized-filters
.unreleased/pr_7600
.unreleased/pr_7637
.unreleased/pr_7645
.unreleased/pr_7649
.unreleased/pr_7653
.unreleased/pr_7656
.unreleased/pr_7665
.unreleased/pr_7673
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains performance improvements and bug fixes since the 2.18.0 release. We recommend that you upgrade at the next available opportunity.
**Features**
* #7656 Remove limitation of compression policy for continuous aggregates
**Bugfixes**
* #6884 Match the Postgres NaN comparison behavior in WHERE clause over compressed tables.
* #7600 Fix lock order when dropping index
* #7637 Allow EXPLAIN in read-only mode
* #7645 Fix DELETE on compressed chunk with non-btree operators
* #7649 Allow non-btree operator pushdown in UPDATE/DELETE queries on compressed chunks
* #7653 Push down orderby scankeys to Hypercore TAM
* #7665 Block merging of frozen chunks
* #7673 Don't abort additional INSERTs when hitting first conflict
**GUCs**
* enable_hypercore_scankey_pushdown: Push down …

Release 2.18.1

---

tsl/test/expected/bgw_scheduler_restart.out
tsl/test/sql/bgw_scheduler_restart.sql

If the scheduler is not restarted, it can affect other tests, so restarting it at the end of the test. Also moving some validation queries to later in the test to make sure that all background workers have restarted properly and read the configuration.

Restart launcher after bgw_scheduler_restart

---

.unreleased/hash-groupagg-bug
tsl/src/nodes/decompress_chunk/exec.c
tsl/src/nodes/vector_agg/grouping_policy_hash.h
tsl/src/nodes/vector_agg/plan.c
tsl/test/expected/vector_agg_groupagg.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/vector_agg_groupagg.sql

The hash grouping strategies do not preserve the input order when the compressed batches need to be reversed. Disable them in this case.

Fix vectorized hash agg in GroupAgg mode in reverse order

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
sql/views.sql
src/bgw/job.c
src/bgw/job_stat.c
src/bgw/job_stat_history.c
src/bgw/job_stat_history.h
src/utils.h
tsl/src/continuous_aggs/utils.c
tsl/test/expected/bgw_job_stat_history.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/expected/bgw_job_stat_history_errors_permissions.out
tsl/test/sql/bgw_job_stat_history.sql
tsl/test/sql/bgw_job_stat_history_errors.sql
tsl/test/sql/bgw_job_stat_history_errors_permissions.sql

Currently while a job is running we set `pid = SchedulerPid`, `succeed = false` and `execution_finish=NOW()` and it leads to confusion when querying either `timescaledb_information.job_errors` or `timescaledb_information.job_history` views showing in the `err_message = job crash detected, see server logs`. This information is wrong and create confusion.
Fixed it by setting `succeed=NULL` and `pid=NULL` when the scheduler launch the job and then when the job worker start to work then set `pid=MyProcPid` (it means the worker PID) meaning that the job started and didn't finished yet and at the end of the execution we set `succeed=TRUE or FALSE` and the `execution_finish=NOW()` to mark the end of the job execution. Also adjusted the views to expose the information properly.
Fixes #7239 …

Fix wrong crash error message on job history

---

tsl/src/nodes/decompress_chunk/vector_quals.h
tsl/src/nodes/vector_agg/CMakeLists.txt
tsl/src/nodes/vector_agg/plan.c
tsl/src/nodes/vector_agg/plan.h
tsl/src/nodes/vector_agg/plan_decompress_chunk.c
tsl/src/planner.c
tsl/test/expected/vector_agg_groupagg.out
tsl/test/sql/vector_agg_groupagg.sql

Vectorized aggregation assumes that it runs on top of a DecompressChunk child node, which makes it difficult to support other child plans; including those that fetch data via Hypercore TAM.
Most of the DecompressChunk-specific code for planning VectorAgg relates to identifying vectorizable columns. This code is moved to a separate source file so that the main planning code is mostly child-node independent.

Make VectorAgg support different child plans

---

tsl/src/import/CMakeLists.txt

Apparently the proper way to use the object libraries in cmake is to add them to target_sources, not target_link_libraries.
The failing workflow: https://github.com/timescale/timescaledb/actions/runs/13271561042/job/37052078190
Some references:
https://cprieto.com/posts/2020/06/cmake-and-object-libraries.html
https://cmake.org/pipermail/cmake/2018-June/067721.html

Fix the umash build

---

.unreleased/pr_7694
tsl/src/hypercore/arrow_cache_explain.c

Hooks in postgres are supposed to be chained and call the previous
hook in your own added hooks. Not calling previous hook will prevent
other extensions from having working hooks.

Fix ExplainHook breaking call chain

---

.unreleased/pr_7707
sql/pre_install/types.functions.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
src/process_utility.c
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/init.c
tsl/test/expected/compression_ddl.out
tsl/test/shared/expected/extension.out
tsl/test/sql/compression_ddl.sql

This patch adds support for ALTER TABLE ALTER COLUMN SET NOT NULL
to compressed chunks. The statement will be allowed when no NULL
values for the specific column are present in compressed chunks.

Support ALTER COLUMN SET NOT NULL on compressed chunks

---

.unreleased/pr_7632
tsl/src/compression/api.c
tsl/src/compression/recompress.c
tsl/test/expected/compression.out
tsl/test/expected/compression_ddl.out
tsl/test/expected/compression_insert.out
tsl/test/expected/compression_update_delete-14.out
tsl/test/expected/compression_update_delete-15.out
tsl/test/expected/compression_update_delete-16.out
tsl/test/expected/compression_update_delete-17.out
tsl/test/expected/hypercore.out
tsl/test/expected/recompress_chunk_segmentwise.out
tsl/test/sql/recompress_chunk_segmentwise.sql

Enables the segmentwise recompression flow to be used for chunks without segmentby columns.
This should be more performant than doing a full recompression.

Optimize recompression for non-segmentby chunks

---

.unreleased/pr_7712
tsl/src/hypercore/attr_capture.c

A fix for #7667.
When we override ExecutorStart hook that has been set by another extension we have to chain-call it not to disrupt other extension's integrity.

Respect other extensions' ExecutorStart hooks

---

.unreleased/pr_7711
src/cross_module_fn.c
src/init.c
tsl/test/expected/hypercore.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore.sql

If a crossmodule wrapper function is called as part of a query on a fresh backend, it will generate a license error even if the license is set correctly. This happens because the module load happens very late (in `post_parse_analyze_hook`) but the function call is quite early.
This is fixed by eagerly loading the TSL module in the hypercore handler function and hypercore index proxy handler function.

Load hypercore handler eagerly

---

src/guc.c
src/guc.h
tsl/src/hypercore/arrow_cache.c
tsl/src/hypercore/arrow_cache.h
tsl/test/expected/hypercore.out
tsl/test/sql/hypercore.sql

The arrow cache is used to cache decompressed arrow segments and is mostly useful for index scans that access values across segments in non-segment order.
The fixed cache size was set too small for index scans on bigger data sets. Therefore, increase the default size and make it configurable via a GUC.

Add GUC for TAM arrow cache size

---

.github/workflows/prerelease-tests-on-release-branch.yaml

As it's a direct branch and not a fork.

Use origin instead of upstream for push

---

tsl/src/chunk.c

get_relmergeinfo macro produced the following warning:
macro argument should be enclosed in parentheses [bugprone-macro-parentheses,-warnings-as-errors]

Silence compiler warning about macro arguments

---

.unreleased/pr_7695
src/chunk.c
tsl/test/expected/compression_ddl.out
tsl/test/sql/compression_ddl.sql

Follow up on this [SDC](https://github.com/timescale/Support-Dev-Collab/issues/2570)
Dropping internal compressed chunks is blocked on DDL level (with process utility hook), but is still possible with `_timescaledb_functions.drop_chunk` function. This patch adds a simple check to prevent that.

Block dropping internal compressed chunks with `drop_chunk()`

---

sql/pre_install/tables.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
sql/views.sql
src/bgw/job.c
src/bgw/job_stat.c
src/bgw/job_stat_history.c
src/bgw/job_stat_history.h
src/utils.h
tsl/src/continuous_aggs/utils.c
tsl/test/expected/bgw_job_stat_history.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/expected/bgw_job_stat_history_errors_permissions.out
tsl/test/sql/bgw_job_stat_history.sql
tsl/test/sql/bgw_job_stat_history_errors.sql
tsl/test/sql/bgw_job_stat_history_errors_permissions.sql

Currently while a job is running we set `pid = SchedulerPid`, `succeed = false` and `execution_finish=NOW()` and it leads to confusion when querying either `timescaledb_information.job_errors` or `timescaledb_information.job_history` views showing in the `err_message = job crash detected, see server logs`. This information is wrong and create confusion.
Fixed it by setting `succeed=NULL` and `pid=NULL` when the scheduler launch the job and then when the job worker start to work then set `pid=MyProcPid` (the worker PID) meaning that the job started and didn't finished yet, and at the end of the execution we set `succeed=TRUE or FALSE` and the `execution_finish=NOW()` to mark the end of the job execution. Also adjusted the views to expose the information properly.
(cherry picked from commit …

Backport to 2.18.x: #7630: Fix wrong crash error message on job history

---

tsl/test/src/compression_unit_test.c

The problem with the test in compression_unti_test.c was that tsl_bool_compressor_finish() expects a BoolCompressor and it should get it from its pair: tsl_bool_compressor_append().
The test supplied an incompatible type (ExtendedCompressor) coming from bool_compressor_for_type() and sanitizer caught it.

Fix sanitizer error by removing an invalid test

---

.github/workflows/backport-trigger.yaml
.github/workflows/backport.yaml

This will help update the pending backport PR to the latest version of the release branch.
GitHub doesn't provide a built-in possibility to trigger a workflow on the main branch when another branch has changed. For example, if we had a "push: ?.*.x" condition, it would trigger the backport workflow on the release branch itself, which is not what we need. So we have to use a helper workflow instead.

Trigger the backports when a release branch is updated

---

.unreleased/hash-groupagg-bug
.unreleased/pr_7694
.unreleased/pr_7695
.unreleased/pr_7711
.unreleased/pr_7712
CHANGELOG.md
sql/CMakeLists.txt
sql/updates/2.18.1--2.18.2.sql
sql/updates/2.18.2--2.18.1.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
version.config

This release contains performance improvements and bug fixes since the 2.18.1 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* #7686 Potential wrong aggregation result when using vectorized aggregation with hash grouping in reverse order
* #7694 Fix ExplainHook breaking call chain
* #7695 Block dropping internal compressed chunks with `drop_chunk()`
* #7711 License error when using hypercore handler
* #7712 Respect other extensions' ExecutorStart hooks
**Thanks**
* @davidmehren and @jflambert for reporting an issue with extension hooks
* @jflambert for reporting a bug with license errors shown in autovacuum

Release 2.18.2

---

tsl/src/bgw_policy/job_api.c
tsl/test/expected/bgw_security.out
tsl/test/sql/bgw_security.sql

The test `bgw_security` requires escalated privileges to modify `_timescaledb_config.bgw_job` and set the owner, which does not work when running tests on an instance without `SUPERUSER` privileges.
Reduce the requirements for the test by switching role before adding the job, and hence avoid the need to update
`_timescaledb_config.bgw_job` to set the owner.

Reduce privilege requirement in bgw_security

---

scripts/backport.py

We already do this, but it doesn't work -- turns out GitHub doesn't start the workflows for merge commits pushed through the GitHub Actions. Push instead using the personal access token. This way a user can only push to their personal fork, so change this as well.

Update the outstanding backport PRs automatically, take 2

---

tsl/test/t/001_job_crash_log.pl

In #7630 we fixed wrong crash error messages on job history. It was fixed by removing the `NOT NULL` constraint from `succeeded` column when the launcher insert the job history row that is updated by the worker when the job actually start to run.
Fixed the TAP test to properly deal with nulls on the `succeeded` column when checking for failed executions.
Flaky execution:
https://github.com/timescale/timescaledb/actions/runs/13391680375/job/37400633002?pr=7719#step:16:701

Fix flaky job crash log TAP test

---

.unreleased/pr_7746
src/guc.c
tsl/src/hypercore/hypercore_handler.c
tsl/test/expected/hypercore_create.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/hypercore_create.sql

The GUC timescaledb.enable_transparent_decompression can be set to 'hypercore' when using Hypercore TAM in order to get a DecompressChunk plan. This will make a scan read only non-compressed data from the TAM, and is used for debugging. Howver, the setting can be dangerous if a chunk is rewritten by decompression or vaccum full, leading to
data loss. Therefore, block rewrite operations on Hypercore TAM when the GUC is set to 'hypercore'. Also remove the possibility to use this GUC value entirely in release builds.

Block TAM rewrites with incompatible GUC setting

---

tsl/test/isolation/expected/merge_chunks_concurrent.out
tsl/test/isolation/specs/merge_chunks_concurrent.spec

The merge chunks functionality can use a "lock upgrade" approach that allows reads during the merge. However, this is not the default approach since it can lead to deadlocks. Some isolation test permutations were added to illustrate deadlocks for the "lock upgrade" approach, but since it can lead to either process being killed the test output is not deterministic.
Also add two new permutations for the non-lock-upgrade approach that show it does not deadlock for concurrent reads and writes.

Disable deadlock permutations in merge chunks tests

---

.github/workflows/backport.yaml
scripts/backport.py

Not sure what's going on with GitHub and push permissions, but at least this particular configuration seems to be working.

More fixes for the backport script

---

.unreleased/pr_7765
src/extension_constants.h
src/with_clause_parser.c
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/expected/compression_ddl.out
tsl/test/shared/expected/with_clause_parser.out
tsl/test/shared/sql/with_clause_parser.sql
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/compression_ddl.sql

- **Allow tsdb as alias for timescaledb in WITH clauses**

Allow tsdb as alias for timescaledb in WITH clauses

---

tsl/src/continuous_aggs/utils.c
tsl/test/expected/cagg_utils.out
tsl/test/sql/cagg_utils.sql

The temporary function `cagg_get_bucket_function` was created to be used in the update script for 2.14.2 to 2.15.0 and for some regression tests, but in 2.16.0 (#7042) we added a new persistent function `cagg_get_bucket_function_info` as a replacement so used it instead.
Leftover from #7042 refactoring PR.

Remove useless function from regression tests

---

docs/BuildSource.md

Minor fix but raising this PR because I noticed that the `docs/BuildSource.md` file mistakenly says that timescaledb cannot be built against postgres 17. Looking at the git blame for `CMakelists.txt` it seems that postgres 17 build functionality was officially supported as of commit `abd637beaa`

Update source build docs

---

.unreleased/pr_7764
sql/updates/post-update.sql
tsl/src/hypercore/hypercore_handler.c
tsl/src/hypercore/hypercore_handler.h
tsl/test/expected/hypercore_create.out
tsl/test/sql/hypercore_create.sql

Fix a bug which caused compression settings to remain after having converted a Hypercore TAM chunk back to another TAM (e.g., heap).
Remove any orphaned settings in the update script.

Fix compression settings handling in Hypercore TAM

---

.unreleased/pr_7768
src/planner/planner.c

When computing cost for a merge join path, an index scan will be done on the relation to find the actual variable range using `get_actual_variable_range()`, which will include an index scan of the hypertable parent.
In addition to being unneccessary, it can also cause problems in situations where the hypertable parent contains data as a result of a bug.
There is a check that an index scan is not done for a partitioned table, so we do the same here by setting the indexlist to NIL after hypertable expansion. The index list is needed while expanding the hypertables to construct correct index scans for chunks of a hypertable.

Remove costing index scan of hypertable parent

---

tsl/test/shared/expected/ordered_append-14.out
tsl/test/shared/expected/ordered_append-15.out
tsl/test/shared/expected/ordered_append-16.out
tsl/test/shared/expected/ordered_append-17.out
tsl/test/shared/expected/ordered_append_join-14.out
tsl/test/shared/expected/ordered_append_join-15.out
tsl/test/shared/expected/ordered_append_join-16.out
tsl/test/shared/expected/ordered_append_join-17.out
tsl/test/shared/sql/include/ordered_append_join.sql
tsl/test/shared/sql/ordered_append.sql.in
tsl/test/shared/sql/ordered_append_join.sql.in

Disabling nested loops to make output tests deterministic.
https://github.com/timescale/timescaledb/actions/runs/13556017463/job/37890546418#step:12:42 https://github.com/timescale/timescaledb/actions/runs/13556017463/job/37890546624#step:12:42

Fix flaky ordered append regression tests

---

.unreleased/pr_7786
tsl/src/compression/create.c
tsl/test/expected/compression_merge.out
tsl/test/sql/compression_merge.sql

When compress_chunk_time_interval is configured but compress_orderby does
not have the primary dimension as first column, chunk merging will
be less efficient as chunks have to be decompressed to be merged.
This patch adds a warning when we encounter this configuration.

Show warning for inefficient compress_chunk_time_interval configuration

---

.unreleased/pr_7789
tsl/src/compression/api.c
tsl/src/compression/create.c
tsl/src/compression/recompress.c
tsl/test/expected/recompress_chunk_segmentwise.out
tsl/test/sql/recompress_chunk_segmentwise.sql

When we have compression where default order by is set to "", we cannot do meaningful segmentwise recompression. Therefore we will return error when segmentwise recompression is requested directly and will do full recompression when general compression is requested.
Fixes: #7748

Do not recompress segmentwise when default order by is empty

---

tsl/src/hypercore/hypercore_handler.c

When building indexes over a table using Hypercore TAM, some memory for decompressing data wasn't released until the index build completes. This change optimizes the memory usage during index builds to release memory after every compressed batch has been processed.

Reduce memory usage when indexing Hypercore TAM

---

.unreleased/pr_7799
src/process_utility.c
test/expected/tableam_alter_defaults.out
test/sql/CMakeLists.txt
test/sql/tableam_alter_defaults.sql
tsl/src/hypercore/hypercore_handler.c
tsl/src/process_utility.c

If `ALTER TABLE ... SET ACCESS METHOD DEFAULT` is used, the name of the table access method is NULL in the `AlterTableCmd`, so add checks that the name is not null before using it.
Function `hypercore_alter_access_method_finish` expects a chunk, but could be called with a non-chunk, so checking that the relid is a chunk before calling it.

Handle DEFAULT table access name in ALTER TABLE

---

tsl/src/hypercore/hypercore_handler.c
tsl/test/expected/hypercore_scans.out
tsl/test/sql/hypercore_scans.sql

Make sure the presence of min/max metadata is detected for non-orderby columns when planning a ColumnarScan so that scankeys are pushed down to the TAM. This improves performance by avoiding decompression.

Push down non-orderby min/max scankeys to TAM

---

src/hypertable.c
src/process_utility.c
tsl/test/expected/compression_settings.out
tsl/test/sql/compression_settings.sql

When a table was dropped with the "cascade" option, compression settings weren't properly cleaned up as a result of refactoring in commit adf7c39. It seems dropping with the "cascade" option invokes a different path for dropping the hypertable and children chunks, and there was no test for it. A test has now been added.

Fix cleanup of compression settings with drop cascade

---

.unreleased/pr_7669
tsl/src/chunk.c
tsl/test/expected/merge_chunks.out
tsl/test/sql/merge_chunks.sql

Compressed chunks can be merged by applying the same copy+heap swap technique to the internal compressed chunks as applied to non-compressed chunks. However, it is necessary to consider cases when some chunks are compressed and some are not.
The way this is handled is to pick the first compressed chunk found among the input chunks, and then use that as the "result" chunk. In the next step all the chunks' non-compressed heaps are merged followed by all the "internal" compressed heaps. In the last step, the result chunk has its non-compressed and compressed heaps swapped with the merged ones, respectively.
In all other regards, the merging works the same as before when merging non-compressed chunks.

Add support for merging compressed chunks

---

tsl/test/expected/cagg_refresh_policy_incremental.out
tsl/test/sql/cagg_refresh_policy_incremental.sql

The continuous aggregate incremental refresh test accidentally used the now() function which makes it fail. Replace it with fixed dates.

Remove now() from test

---

tsl/src/compression/api.c
tsl/src/compression/recompress.c
tsl/test/isolation/expected/compression_conflicts_iso.out
tsl/test/isolation/expected/compression_recompress.out
tsl/test/isolation/specs/compression_recompress.spec
tsl/test/t/002_logrepl_decomp_marker.pl

Recompression used to take heavy Exclusive lock on chunk while it recompressed data. This blocked a lot of concurrent operations like inserts, deletes, and updates. By reducing the locking requirement to ShareUpdateExclusive, we enable more concurrent operations on the chunk and hypertable while relying on tuple locking. Recompression can still end up taking an Exclusive lock at the end in order to change the chunk status but it does this conditionally, meaning it won't take it unless it can do it immediately.

Reduce lock requirements during recompression

---

tsl/test/expected/cagg_refresh_policy_incremental.out
tsl/test/sql/cagg_refresh_policy_incremental.sql

Use timer mock on Incremental CAgg Refresh policy tests

---

.unreleased/pr_7816
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/merge_append_partially_compressed-14.out
tsl/test/expected/merge_append_partially_compressed-15.out
tsl/test/expected/merge_append_partially_compressed-16.out
tsl/test/expected/merge_append_partially_compressed-17.out
tsl/test/expected/recompress_chunk_segmentwise.out
tsl/test/sql/merge_append_partially_compressed.sql.in

When querying from a chunk directly that is partially compressed the ordering would be applied locally to compressed and uncompressed data and not globally to the complete resultset leading to incorrect ordering.
Fixes: #7084

Fix ORDER BY on partially compressed chunks

---

tsl/test/expected/cagg_refresh_policy_incremental.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_refresh_policy_incremental.sql

The usage of timer mock was wrong because we're setting it on the current session but the job is executed by a background worker that don't have the mock time configured.
Fixed it by creating a user with an specific timezone and time mock configured so any background worker created by the user will have the proper configuration.
Failed attempts to fix #7813 and #7819.

Fix Incremental CAgg Refresh policy tests

---

tsl/src/compression/api.c
tsl/test/expected/compression_merge.out
tsl/test/sql/compression_merge.sql

In the past, rolling up chunks while using primary dimension in DESC order would create unordered chunks which meant we had to do full recompress of the rolled up compressed chunk. With removal of sequence from compression schema, this no longer tracks thus we can remove this limitation.

Avoid recompression for DESC order during rollup

---

.github/workflows/backport.yaml
scripts/backport.py

The GITHUB_TOKEN variable is getting overwritten with the Github Actions
token.
Moreover, the token-based remote's credentials are somehow overwritten on push with credentials used for checkout action. Use the PAT for it as well.
This should finally let the backport script to update the outstanding backport PRs to the current target branch, and workflows to start for them.

Use the correct token for backport workflow

---

.unreleased/pr_7832
src/dimension.c
src/dimension.h
src/ts_catalog/continuous_agg.c
src/ts_catalog/continuous_agg.h
src/utils.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/options.c
tsl/test/expected/cagg_ddl-14.out
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/sql/cagg_ddl.sql.in

This patch allow setting chunk_time_interval when creating a continuous agg and allows changing it with ALTER MATERIALIZED VIEW. Previously you had to create the cagg with `WITH NO DATA` and then call `set_chunk_time_interval` followed by manually refreshing.
Fixes #6923
Fixes #1775

Simplify setting chunk_time_interval for caggs

---

tsl/test/expected/hypercore_scans.out
tsl/test/sql/hypercore_scans.sql

Remove costs from explain plans to make tests less flaky.

Remove costs from hypercore_scans explain plan

---

.unreleased/pr_7844
src/guc.c
src/guc.h
tsl/src/compression/recompress.c
tsl/test/expected/recompress_chunk_segmentwise.out
tsl/test/sql/recompress_chunk_segmentwise.sql

With reduction of locking during segmentwise recompression, we are no longer getting ExclusiveLocks on relations at the start of the operation. This GUC can be used to enable this behavior in order to replicate legacy locking style if necessary.

Add GUC to enable exclusive locking recompression

---

.unreleased/pr_7837
sql/policy_internal.sql
tsl/src/compression/api.c
tsl/test/expected/compression_bgw.out
tsl/test/expected/hypercore_policy.out
tsl/test/sql/compression_bgw.sql
tsl/test/sql/hypercore_policy.sql

Freezing a partially compressed chunk prevents us from compressing it back to fully compressed. If the chunk was frozen, we can just ignore them and continue with the rest of the chunks.

Ignore frozen chunks in compression policy

---

tsl/src/compression/recompress.c
tsl/test/isolation/expected/compression_conflicts_iso.out
tsl/test/isolation/expected/compression_recompress.out

Adding more context what happens if we end up in
serialization issues during recompression.

Update wording on logs during recompression

---

.unreleased/pr_7850
tsl/src/hypercore/arrow_tts.c

PG17 introduced the TTS callback `is_current_xact_tuple` but it was missing in our Arrow TTS definition.
https://github.com/postgres/postgres/commit/0997e0af273d80add75bcf5616eee000d0a78397

Add callback is_current_xact_tuple to Arrow TTS

---

.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml
.github/workflows/docker-images.yaml
.github/workflows/homebrew.yaml
.github/workflows/rpm-packages.yaml
.github/workflows/windows-packages.yaml

The package tests verify that the published version from the
official sources is installable and matches the expected version,
so these tests will always fail as part of prerelease since no
packages are being published as part of the procedure.

Don't run package test as part of prerelease

---

.github/gh_matrix_builder.py
.github/workflows/linux-build-and-test.yaml
.github/workflows/shellcheck-ignored.yaml
scripts/upload_ci_stats.sh
tsl/src/compression/compression.h
tsl/test/expected/compression_algos.out
tsl/test/sql/compression_algos.sql

In Flaky Check specifically. The internal program errors (XX000) are reserved for bugs, we shouldn't encounter them during normal operation. We already have some places where this code is used incorrectly, so only check it for the newly introduced tests.

Check that no new internal program errors are introduced in CI

---

.unreleased/pr_7864
src/process_utility.c
tsl/test/expected/compression_constraints.out
tsl/test/expected/compression_errors-15.out
tsl/test/expected/compression_errors-16.out
tsl/test/expected/compression_errors-17.out
tsl/test/sql/compression_constraints.sql
tsl/test/sql/compression_errors.sql.in

Allow adding CHECK constraints to hypertables that have compressed
chunks. Previously this would require decompressing any compressed
chunks before adding the CHECK constraint.

Allow adding CHECK constraints to compressed chunks

---

.unreleased/pr_7834
src/loader/bgw_launcher.c
src/loader/loader.c

When a user creates a database based on a template a FATAL error will be generated, which causes the scheduler to restart. The same happens if a FATAL error is generate in any other way, e.g., if the database does not exist.
If you use an actual template database (like template0) this can cause endless errors and retries wasting bgw slots. Hence, we avoid starting the bgw scheduler for databases that does not exist and databases we cannot connect to.
In addition to when creating a new database, a re-starting scheduler might generate errors if the database has gone away or if permissions for the database changed. This will trigger an endlessly restarting scheduler.
We fix this issue by overriding connection block when connecting to the database and perform the check ourselves to avoid a …

Avoid unnecessary scheduler restarts

---

.unreleased/pr_7877
src/process_utility.c
tsl/test/expected/compression_errors.out

Remove special handling for ADD COLUMN with unique/primary key
constraints on compressed hypertables. This patch makes the behaviour
consistent with uncompressed hypertable where ADD COLUMN with unique/
primary key constraint is blocked because those constraints require
all partitioning columns to be included.

Remove blocker for unique constraints with ADD COLUMN

---

src/loader/bgw_launcher.c

A return inside the body of a PG_TRY can trigger a segmentation fault inside `longjmp()` so this commit moves the return to outside the `PG_TRY` block and assigns the value to a `volatile` variable.
Disable-check: force-changelog-file, loader-change

Remove return from inside PG_TRY

---

tsl/src/compression/api.c

Remove redundant check in check_is_chunk_order_violated_by_merge

Remove redundant check in check_is_chunk_order_violated_by_merge

---

.unreleased/pr_7878
tsl/src/continuous_aggs/finalize.c
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_usage-15.out
tsl/test/expected/cagg_usage-16.out
tsl/test/expected/cagg_usage-17.out
tsl/test/sql/cagg_ddl.sql.in
tsl/test/sql/cagg_errors.sql
tsl/test/sql/cagg_usage.sql.in

Throw a warning when we encounter non-immutable functions in cagg
definition instead of blocking it.

Don't block non-immutable functions in caggs

---

.unreleased/pr_7890
src/bgw/job.c
src/bgw/job_stat.c
src/chunk.c
src/telemetry/telemetry.c
tsl/src/continuous_aggs/utils.c
tsl/test/src/compression_sql_test.c

If the function `FlushErrorState` is not called immediately after `CopyErrorData`, or at least before doing any serious work that can throw another error, it can exhaust the error stack (which is very small).
This commit moved calls of `FlushErrorState` to immediately after `CopyErrorData` to reset the error stack and avoid exhausting the error stack.
It also adds calls to `FreeErrorData` where applicable, i.e., where the error data is not re-thrown nor saved away.

Flush error state before doing anything else

---

.github/workflows/linux-build-and-test.yaml

Looks like tilde expansion doesnt work correctly in cmake
version which came in new ubuntu ci runner images. This patch
changes the CI workflow to no longer rely on cmake tilde expansion.

Fix PG_SRC_DIR path

---

src/cross_module_fn.c
src/cross_module_fn.h
src/process_utility.c
tsl/src/compression/create.c
tsl/src/compression/create.h
tsl/src/continuous_aggs/options.c

AlterTableCmd was never used in the function so this patch removes
it from the signature.

Remove unused argument from process_compress_table

---

.unreleased/pr_7874
src/guc.c
src/guc.h
tsl/src/nodes/skip_scan/planner.c
tsl/src/nodes/skip_scan/skip_scan.h
tsl/src/planner.c
tsl/test/expected/decompress_index.out
tsl/test/expected/plan_skip_scan_dagg.out
tsl/test/expected/skip_scan_dagg.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/decompress_index.sql
tsl/test/sql/include/skip_scan_dagg_query.sql
tsl/test/sql/include/skip_scan_dagg_query_ht.sql
tsl/test/sql/plan_skip_scan_dagg.sql
tsl/test/sql/skip_scan_dagg.sql

Implement SkipScan for eligible distinct aggregates, see https://github.com/timescale/eng-database/issues/692.
We now allow for distinct upper path to also be an AggPath with aggregates which are all distinct and all have the same input column. 
The tests for correct values and correct plans were mostly copied from `skip_scan_query.sql` and `skip_scan_query_ht.sql` and modified to use Distinct aggregates instead of `SELECT DISTINCT`.
SkipScan planner was refactored to allow for different kinds of upper distinct paths.
The parts which need improving:
- _Compute cost for the new AggPath. Right now AggClauseCosts are set to 0 while new cost over new SkipScan input into distinct aggregates is applied to new AggPath. I'm not sure if we want to fully recreate old AggPath at this point, we just …

Implement SkipScan for distinct aggregates

---

.unreleased/pr_7910
tsl/src/nodes/skip_scan/planner.c
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out
tsl/test/expected/plan_skip_scan_dagg.out
tsl/test/sql/include/skip_scan_dagg_query_ht.sql

Fixes this issue (SkipScan plan not chosen when only 1 chunk remains): https://github.com/timescale/timescaledb/issues/7778
Root cause: not considering AppendPath over one child. This AppendPath will be removed later during plan optimizations but it is still present when we try to apply SkipScan. Now we consider this scenario as well.

Fix not using SkipScan over one chunk

---

.unreleased/pr_7911
src/hypertable.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

Logical Replication of hypertables is not supported (for implementation reasons). We do not allow creation of hypertables
with publications and now throw an error if attempted.
Closes #7208

Don't create hypertable for published tables

---

.unreleased/pr_7923
src/guc.c
src/guc.h
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

This GUC can be used to set the limit of rows batched together during compression. Valid values are 1-999 with 0 disabling limiting and using the default 1000 row limit.

Add compression batch size limit GUC

---

.unreleased/pr_7902
tsl/src/nodes/columnar_scan/columnar_scan.c
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/decompress_chunk/vector_quals.h
tsl/src/nodes/vector_agg/plan.c
tsl/src/nodes/vector_agg/plan_decompress_chunk.c
tsl/src/nodes/vector_agg/plan_tam.c
tsl/test/expected/vectorized_aggregation.out
tsl/test/sql/vectorized_aggregation.sql

Due to a refactor in commit 947f7f40 that silenced a coverity warning, a crash was introduced for certain aggregation query plans. However, no such plan was covered in our tests, so the crash was never triggered.
Add a fix and a test case that triggers crash when the fix is not present.

Fix crash in VectorAgg plan code

---

.unreleased/pr_7923
src/guc.c
src/guc.h
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

This GUC can be used to set the limit of rows batched together during compression. Valid values are 1-999 with 0 disabling limiting and using the default 1000 row limit.

Backport to 2.19.x #7923: Add compression batch size limit GUC

---

CMakeLists.txt

Linting is off by default, but when it is requested we should
throw an error instead of continuing and printing warning when
we cannot find clang-tidy.

Require linter to be present when linting is requested

---

test/pg_regress.sh
test/runner_cleanup_output.sh

When selecting test files, it is possible that one more more of the files are considered binary files by grep. In these cases, we should still grep the file as if it was a text file to make sure that we do not ignore any tests that should be included.

Use -a for grep when picking test files

---

.unreleased/pr_7928
src/hypertable.c
test/expected/create_hypertable.out
test/sql/create_hypertable.sql

Previously, only explicitly published tables were blocked from creating hypertables. Logical Replication of hypertables is not supported (for implementation reasons). We do not allow creation of hypertables with publications and now throw an error if attempted.
Thanks @arajkumar for highlighting the issue https://github.com/timescale/timescaledb/pull/7911#issuecomment-2782864246

Don't create hypertable for implicitly published tables

---

.unreleased/pr_7913
tsl/src/compression/compression_storage.c
tsl/test/expected/hypercore_create.out
tsl/test/sql/hypercore_create.sql

When using Hypercore TAM on the hypertable, new chunks are created as hypercore chunks, including the compressed relation. This means that the compressed relation is created as the inserting user. However, if the inserting user is not the table owner, this operation failed.
The reason it failed was because some toast settings were changed on the compressed chunk during its creation without switching to a role with proper permissions. This is easily fixed by extending the section of code that is executed under the permissive role.

Allow TAM chunk creation as non-owner

---

.unreleased/pr_7893
src/with_clause_parser.c
test/src/test_with_clause_parser.c
tsl/test/shared/expected/with_clause_parser.out
tsl/test/shared/sql/with_clause_parser.sql

When parsing WITH clause arguments for ALTER TABLE to extract compression parameters, syntax errors in the text format are caught using PG_TRY and PG_CATCH and then processing the errors to add more information.
If an out-of-memory error occurs inside execution of the input function and this error is caught, it can continue executing and potentially cause cascading out-of-memory errors and in the end exhausting the error stack.
This commit solves this by using checking the category of the thrown error and only allow errors in the data exception and the syntax errors and access rules violation category, which are "soft" errors in this case. Hard errors, like out-of-memory errors, are re-thrown allowing the backend to deal with it properly.

Don't process hard errors in with-clause parser

---

.unreleased/pr_7941
src/ts_catalog/chunk_column_stats.c
tsl/test/expected/chunk_column_stats.out
tsl/test/sql/chunk_column_stats.sql

Column stats calculation code mistakingly used column type from hypertable based on attribute number from chunk. In many cases it worked fine unless hypertable had dropped columns that new chunks didn't have. In that case column type could be identified incorrectly causing errors or segfaults.
See #7932

Fix column mapping in column stats calculation

---

.unreleased/pr_7880
src/guc.c
src/guc.h
tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/expected/cagg_errors.out
tsl/test/sql/cagg_ddl.sql.in

This patch adds a GUC to allow window functions in continuous
aggregate view definitions. The GUC is turned off by default.

Add experimental support for window functions in caggs

---

.unreleased/pr_7915
sql/policy_api.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/continuous_aggregate_api.h
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job.h
tsl/src/bgw_policy/policies_v2.c
tsl/src/bgw_policy/policies_v2.h
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_refresh_policy_incremental.out
tsl/test/shared/expected/extension.out
tsl/test/sql/cagg_refresh_policy_incremental.sql

In the Incremental CAgg Refresh Policy introduced on 2.19.0 the default batches order is from newest data to the oldest and there's no way to change it.
This PR introduce a new option to the CAgg Refresh Policy API `refresh_newest_first = TRUE` to control this behavior. If it's set to `FALSE` then the order of the incremental refresh will be from the oldest data to the newest.

New order option for Incremental CAgg Refresh Policy

---

.unreleased/pr_7910
tsl/src/nodes/skip_scan/planner.c
tsl/test/expected/plan_skip_scan-14.out
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out

Backport to 2.19.x: Fix not using SkipScan over one chunk

---

.unreleased/pr_7929
src/CMakeLists.txt
src/create_table_with_clause.c
src/create_table_with_clause.h
src/process_utility.c
test/expected/create_table_with.out
test/sql/CMakeLists.txt
test/sql/create_table_with.sql

This is the first patch to add support for CREATE TABLE ... WITH
for creating a hypertable. This patch only adds hypertable AND
time_column as options. The other timescaledb related configuration
settings will be added in followup patches.

CREATE TABLE WITH

---

tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c

Instead of full transparent decompressing batches in order to check the columns which are used in constraint checking on INSERTs into compressed chunks, only decompress individual columns that are actually necessary.

Implement partial decompress for constraint check

---

.unreleased/pr_7935
tsl/src/hypercore/hypercore_handler.c
tsl/src/nodes/columnar_scan/columnar_scan.c

If a whole segment is deleted in a Hypercore TAM table, a segmentation fault can be triggered that results from reading freed data.
After calling `table_open()` and locking the table in `LockRelationOid()` all invalidation messages will be processed. This can invalidate the `rd_amcache` field for the relation, but also for other relations.
As a result, this caused clobbered data to be used when finding the count column in the compressed relation since the attribute number was 0x7f7f when first fetching HypercoreInfo using `RelationGetHypercoreInfo()`, calling `table_open()`, and then trying to use the data in the structure again.
This commit fixes this by not re-using data returned by `RelationGetHypercoreInfo()` after calling `table_open()`. Since one of the more common cases for this is …

Fix TAM segfault on DELETE using segmentby column

---

.unreleased/pr_7935
tsl/src/hypercore/hypercore_handler.c
tsl/src/nodes/columnar_scan/columnar_scan.c

If a whole segment is deleted in a Hypercore TAM table, a segmentation fault can be triggered that results from reading freed data.
After calling `table_open()` and locking the table in `LockRelationOid()` all invalidation messages will be processed. This can invalidate the `rd_amcache` field for the relation, but also for other relations.
As a result, this caused clobbered data to be used when finding the count column in the compressed relation since the attribute number was 0x7f7f when first fetching HypercoreInfo using
`RelationGetHypercoreInfo()`, calling `table_open()`, and then trying to use the data in the structure again.
This commit fixes this by not re-using data returned by `RelationGetHypercoreInfo()` after calling `table_open()`. Since one of the more common cases for this is …

Backport of #7935: Fix TAM segfault on DELETE using segmentby column

---

.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml
.github/workflows/docker-images.yaml
.github/workflows/homebrew.yaml
.github/workflows/pgspot.yaml
.github/workflows/rpm-packages.yaml
.github/workflows/windows-packages.yaml
CMakeLists.txt
scripts/changelog/generate.sh
scripts/test_downgrade.sh
scripts/test_update_from_version.sh
scripts/test_updates.sh
sql/CMakeLists.txt
sql/updates/README.md
version.config

Since we adjusted our release procedure recently we do no longer
need to keep track of update and downgrade version separately and
can instead combine them as previous_version, simplifying the
version.config file.

Simplify version.config

---

sql/updates/latest-dev.sql
src/hypertable.c
src/process_utility.c

When deprecating functions in the _timescaledb_internal schema
we did not migrate calculate_chunk_interval in our catalog and
didn't adjust the default function schema.

Adjust schema for calculate_chunk_interval in catalog

---

.unreleased/pr_7912
src/estimate.c
tsl/test/expected/custom_hashagg.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/custom_hashagg.sql

In the time utility functions errors were captured to, it seems, handle syntax errors and out-of-range errors, but this also capture hard errors like out-of-memory and continued to execute, which can cause panics as a result of error stack being exhausted.
This commit removes the capture and allow the error to propagate to callers, including out-of-range errors and syntax errors.
The `PG_TRY` in `estimate_max_spread_var` was added in commit 9a29f0436d59fd0f2f0876fec2de89512140c752 but it is not clear in that commit why it was needed but removing it does not cause any test failures.
In addition, an explicit test was added to trigger this function.

Don't capture errors estimating time max spread

---

.unreleased/pr_7912
src/estimate.c
tsl/test/expected/custom_hashagg.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/custom_hashagg.sql

In the time utility functions errors were captured to, it seems, handle syntax errors and out-of-range errors, but this also capture hard errors like out-of-memory and continued to execute, which can cause panics as a result of error stack being exhausted.
This commit removes the capture and allow the error to propagate to callers, including out-of-range errors and syntax errors.
The `PG_TRY` in `estimate_max_spread_var` was added in commit 9a29f0436d59fd0f2f0876fec2de89512140c752 but it is not clear in that commit why it was needed but removing it does not cause any test failures.
In addition, an explicit test was added to trigger this function.

Backport of #7935: Don't capture errors estimating time max spread

---

.unreleased/pr_7954
src/loader/bgw_launcher.c
tsl/test/expected/bgw_scheduler_restart.out
tsl/test/sql/bgw_scheduler_restart.sql

You can set the scheduler restart time using the option `timescaledb.bgw_scheduler_restart_time` but there are no means to disable it entirely.
This commit allow `timescaledb.bgw_scheduler_restart_time` to be set to zero, denoting that scheduler restarts should be disabled.
The default is set to not restart schedulers by default.
Disable-check: loader-change

Allow scheduler restarts to be disabled

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/windows-build-and-test.yaml
.unreleased/uuid-segmentby-grouping-segfault
tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/vector_agg/grouping_policy_batch.c
tsl/src/nodes/vector_agg/grouping_policy_hash.c
tsl/src/nodes/vector_agg/hashing/hash_strategy_serialized.c
tsl/src/planner.c
tsl/test/expected/vector_agg_uuid_segmentby.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/vector_agg_uuid_segmentby.sql

This case was handled incorrectly and led to a segfault when grouping by multiple columns, one of which is a UUID segmentby column.
The issue was reported here https://github.com/timescale/Support-Dev-Collab/issues/2812#issuecomment-2804490083

Fix serialized hashing for scalar fixed-width by-reference columns

---

.unreleased/pr_7893
.unreleased/pr_7903
.unreleased/pr_7910
.unreleased/pr_7912
.unreleased/pr_7913
.unreleased/pr_7935
.unreleased/pr_7941
.unreleased/pr_7954
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains bug fixes since the 2.19.2 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* [#7893](https://github.com/timescale/timescaledb/pull/7893) Don't capture hard errors in with-clause parser
* [#7903](https://github.com/timescale/timescaledb/pull/7903) Don't capture hard errors for old cagg format
* [#7912](https://github.com/timescale/timescaledb/pull/7912) Don't capture errors estimating time max spread
* [#7910](https://github.com/timescale/timescaledb/pull/7910) Fix not using SkipScan over one chunk
* [#7913](https://github.com/timescale/timescaledb/pull/7913) Allow TAM chunk creation as non-owner
* [#7935](https://github.com/timescale/timescaledb/pull/7935) Fix TAM segfault on DELETE using segmentby column
* …

2.19.3 Release

---

.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/windows-build-and-test.yaml
.unreleased/uuid-segmentby-grouping-segfault
tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/vector_agg/grouping_policy_batch.c
tsl/src/nodes/vector_agg/grouping_policy_hash.c
tsl/src/nodes/vector_agg/hashing/hash_strategy_serialized.c
tsl/src/planner.c
tsl/test/expected/vector_agg_uuid_segmentby.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/vector_agg_uuid_segmentby.sql

This case was handled incorrectly and led to a segfault when grouping by multiple columns, one of which is a UUID segmentby column.
(cherry picked from commit 0768b33ab3e793c884572479e3c943beff12df2a)
backport of https://github.com/timescale/timescaledb/pull/7964

Fix serialized hashing for scalar fixed-width by-reference columns (#7964)

---

.github/workflows/coverity.yaml
.github/workflows/memory-tests.yaml

Changing ubuntu-20.04 to ubuntu-latest for coverity and memory tests since GitHub is [deprecating this version](https://github.com/actions/runner-images/issues/11101).

Bump up runner version for CI tests

---

.github/workflows/prerelease-sanity.yaml

* Must have no leftover .unreleased files
* The commit title must start with "Release \<version\>"
* The tag must point to the actual release commit and not something else.
* The release commit must modify version.config
Tested manually here https://github.com/timescale/timescaledb/pull/7969

Add some sanity checks for potential release commits/tags

---

src/cross_module_fn.c
src/cross_module_fn.h
src/process_utility.c
tsl/src/compression/create.c
tsl/src/compression/create.h
tsl/src/init.c
tsl/test/expected/create_table_with.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/create_table_with.sql

On hypertables created with CREATE TABLE ... WITH we enable compression
by default but do not create CompressionSettings immediately assuming
that we have more information available when the first compression
is actually triggered allowing us to generate better compression
settings.

Enable compression for CREATE TABLE ... WITH ()

---

src/process_utility.c
src/ts_catalog/continuous_agg.c
src/with_clause/CMakeLists.txt
src/with_clause/alter_table_with_clause.c
src/with_clause/alter_table_with_clause.h
tsl/src/compression/create.c
tsl/src/continuous_aggs/options.c

This change is to make the naming similar to create table since
the with clause options are determined by the command used
and not limited to a specific feature.

Rename compression_with_clause to alter_table_with_clause

---

.github/workflows/backport-trigger.yaml
.github/workflows/backport.yaml
.github/workflows/catalog-updates-check.yaml
.github/workflows/changelog-check.yaml
.github/workflows/issue-handling.yaml
.github/workflows/pr-approvals.yaml
.github/workflows/pr-handling.yaml
.github/workflows/pr-validation.yaml

Move the smaller actions to a different runner to free up resources for other more involved actions.

Move small actions to different runner

---

.unreleased/pr_7982
tsl/src/nodes/decompress_chunk/planner.c
tsl/test/expected/compression_sorted_merge_columns.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression_sorted_merge_columns.sql

Fix crashes in batch sort merge over eligible OpExprs which were not recognized while setting up batch sort merge for decompression. 
Related to https://github.com/timescale/timescaledb/pull/7528.
Fixes #7975.

Fix crashes in batch sort merge over expressions

---

scripts/test_pg_upgrade.py
test/sql/updates/post.catalog.sql

A new testgres framework was released that makes `PostgresNode::port` read-only. Fixed it by properly set the port when initializing a new node.
Failure due to the new testgres version: https://github.com/timescale/timescaledb/actions/runs/14589439220/job/40921093070?pr=7976
References:
https://github.com/postgrespro/testgres/releases/tag/1.11.0
https://github.com/postgrespro/testgres/pull/234

Fixes for the new testgres 1.11.0

---

.github/workflows/pg_ladybug.yaml
.unreleased/pr_7981
src/with_clause/alter_table_with_clause.c
tsl/test/expected/columnstore_aliases.out
tsl/test/sql/columnstore_aliases.sql

Since the option is a bool the enable in the option name is redundant
and having the option named columnstore seems more consistent with
similarly named options.

Add columnstore as alias for enable_columnstore in ALTER TABLE

---

.github/workflows/pr-handling.yaml

Switch back to old git runner that has the docker image for ghcr.io/imsky/pull-review for the job "Assign PR to author and
reviewers" 

Switch to old git runner with latest docker image

---

tsl/test/expected/compression.out
tsl/test/sql/compression.sql

Add ORDER BY to a potentially flaky query.
Part of https://github.com/timescale/timescaledb/pull/7551

Stabilize the compression test

---

.github/workflows/code_style.yaml

Do git reset in actions that use git diff, otherwise the errors from the previous checks get mixed into the output of the subsequent checks.

Clean up before style checks

---

.unreleased/pr_7991
sql/compression_defaults.sql
tsl/src/compression/README.md
tsl/test/expected/compression_defaults.out
tsl/test/expected/telemetry_stats.out
tsl/test/sql/compression_defaults.sql

Previously, the default segmentby logic only used indexed columns with distinct values. It now includes non-indexed columns as candidates. When multiple columns are eligible, it selects the one with the most even value distribution based on pg_stats.
1. Low cardinality:
- Must have +ve n_distinct values (may not be optimal in some scenarios)
2. Index position:
- column in a lower index key is considered. Assumption made is indexes are appropriately designed for performance reasons (might not always be the case)
3. Even distribution of rows among the distinct values
- It is still possible for chunks to have skewed distribution causing sub-optimal segmentation

Improve default segmentby for hypertables

---

.github/workflows/memory-tests.yaml

Cluster initialization was not happening automatically after the `postgresql` package was installed. Performing it manually fixes the error.
Also added the `pull_request` trigger to this test so that it is run whenever a PR modifying it is raised.
Closes #7959.

Memory test fix

---

.unreleased/pr_7785
src/guc.c
src/guc.h
tsl/src/compression/compression.c
tsl/test/expected/compression.out
tsl/test/isolation/expected/compression_conflicts_iso.out
tsl/test/isolation/expected/compression_freeze.out
tsl/test/isolation/specs/compression_conflicts_iso.spec
tsl/test/isolation/specs/compression_freeze.spec
tsl/test/t/004_truncate_or_delete_spin_lock.pl
tsl/test/t/CMakeLists.txt

After compression, the uncompressed part of the chunk is truncated. This requires upgrading the `ExclusiveLock` to an
`AccessExclusiveLock` and hence is sometimes blocked by other other operations, including reads, on the chunk. This leads to longer compress times or potential deadlocks.
Instead of this, we fall back to deleting the tuples in the chunk row-by-row when the upgraded lock isn't immediately acquired.

Do DELETE instead of TRUNCATE when locks aren't acquired

---

.unreleased/pr_7976
sql/views.sql
tsl/test/expected/cagg_migrate.out
tsl/test/expected/cagg_policy.out
tsl/test/expected/hypercore_policy.out
tsl/test/sql/cagg_policy.sql
tsl/test/sql/hypercore_policy.sql
tsl/test/sql/include/cagg_migrate_common.sql

In the timescaledb_information.jobs view, it is not possible to see the
continuous aggregate name for jobs related to continuous aggregates and
it is necessary to use the materialized table id to look up the actual
continuous aggregate. Since hypertable_schema and hypertable_name
columns contain the materialized hypertable for the continuous
aggregate, which are considered internal objects and not very useful
except for looking up the continuous aggregate, we store the continuous
aggregate name and schema in these columns.

Include cagg name in timescaledb_information.jobs

---

.unreleased/pr_8014
src/guc.c
tsl/src/compression/algorithms/array.c
tsl/src/compression/algorithms/array.h
tsl/src/compression/algorithms/dictionary.c
tsl/src/compression/algorithms/dictionary.h
tsl/src/compression/compression.c
tsl/test/expected/decompress_vector_qual.out
tsl/test/sql/decompress_vector_qual.sql
tsl/test/src/compression_unit_test.c

This change sets the default for the GUC value:
`timescaledb.enable_bool_compression=true`
It enables bulk decompression for array and dictionary compression
for BOOLs because this is mandatory to support upgrades to 2.20.

Enable bool compression

---

.unreleased/pr_7756
src/guc.c
src/guc.h
test/postgresql.conf.in
tsl/src/compression/api.c
tsl/test/expected/compression.out
tsl/test/postgresql.conf.in
tsl/test/sql/compression.sql

Adds functionality to emit a warning to the user when the compression
ratio is "bad".
Currently, "bad" is defined to be when size after compression is higher
than after compression.

Add warning for poor compression ratio

---

.unreleased/pr_8008
sql/policy_internal.sql
sql/updates/reverse-dev.sql
tsl/test/expected/compression_bgw.out
tsl/test/sql/compression_bgw.sql

When a chunk compression happens inside the policy it is catched by a
BEGIN ... EXCEPTION block to don't stop the execution and keep
compressing other chunks. The number of succeeded compressed chunks is
increased when an exception don't occur and the number of failed
compressed chunks when it occurs. The problem was when showing the
number of succeeded compressed chunks we were subtracting the number of
succeeded executions by number of failures, so for example if we got 10
failures and 1 success then the result will be showed as -9.
Fixed it by adjusting the variables used to demonstrate correctly the
number of failures and succeeded chunks compressed and also added proper
regression test for it.
Co-authored-by: Fabrízio de Royes Mello <fabriziomello@gmail.com>

Fix compression policy error message.

---

.unreleased/pr_7972
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c
tsl/src/compression/compression_dml.h
tsl/src/nodes/decompress_chunk/compressed_batch.c
tsl/src/nodes/decompress_chunk/vector_dict.h
tsl/test/expected/compression_insert.out
tsl/test/sql/compression_insert.sql

When backfilling compressed chunks with constraint checking, we need to read and filter compressed tuples in order to confirm constraints are validated. This change adds the ability to do this operation using vectorized decompression and vectorized filtering if the types allow us to do so.

Add vectorized filtering to constraint checking

---

.unreleased/pr_8012
src/chunk.c
src/guc.c
src/guc.h
tsl/test/expected/chunk_utils_internal.out
tsl/test/sql/chunk_utils_internal.sql

Add support for event triggers on chunk creation. Event triggers are disabled by default but can be enabled with `timescaledb.enable_event_triggers` GUC.

Fire event triggers on chunk creation

---

.github/workflows/snapshot-abi.yaml
.github/workflows/sqlsmith.yaml

- **Don't build timescaledb with WARNINGS_AS_ERRORS in sqlsmith workflow**

Don't build timescaledb with WARNINGS_AS_ERRORS in sqlsmith workflow

---

tsl/src/compression/compression.c

This is a fix for `‘column_info’ may be used uninitialized in this
function [-Werror=maybe-uninitialized]`

Make compiler happy by initializing column_info

---

.unreleased/pr_7983
src/guc.c
src/guc.h
tsl/src/nodes/decompress_chunk/decompress_chunk.h
tsl/src/nodes/decompress_chunk/planner.c
tsl/src/nodes/skip_scan/exec.c
tsl/src/nodes/skip_scan/planner.c
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out
tsl/test/expected/plan_skip_scan_dagg.out
tsl/test/expected/skip_scan.out
tsl/test/expected/skip_scan_dagg.out
tsl/test/sql/include/skip_scan_comp_query.sql
tsl/test/sql/include/skip_scan_dagg_comp_query.sql
tsl/test/sql/include/skip_scan_dagg_load_comp_query.sql
tsl/test/sql/include/skip_scan_dagg_query_ht.sql
tsl/test/sql/include/skip_scan_load.sql
tsl/test/sql/include/skip_scan_load_comp_query.sql
tsl/test/sql/include/skip_scan_query_ht.sql
tsl/test/sql/plan_skip_scan.sql.in
tsl/test/sql/plan_skip_scan_dagg.sql
tsl/test/sql/skip_scan.sql
tsl/test/sql/skip_scan_dagg.sql

PR implements https://github.com/timescale/eng-database/issues/693 via "SkipScan <- DecompressChunk <- Compressed Index" plan.
SkipScan consumes DecompressChunk data to get the next distinct value, then uses it to update SkipScan qual on the compressed index under DecompressChunk node. 
DecompressChunk plan has "UniqueSegBy" flag set when it is consumed by SkipScan. When this flag is set, it jumps to the end of the current batch after the 1st tuple from the batch is retrieved.
Current unit test setup: `skip_scan_load` creates an extra table `skip_scan_htc` with the same setup as `skip_scan_ht` but with compressed data. Then the same correctness and plan tests run on `skip_scan_ht` are also run on `skip_scan_htc`.  Correctness checks pass, plan tests only apply to scenarios with index on …

SkipScan over compressed chunks

---

tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/finalize.c
tsl/src/continuous_aggs/planner.c
tsl/test/expected/cagg_planning.out
tsl/test/sql/cagg_planning.sql

In the past the query against the materialization hypertable had aggregation because we used to store the `chunk_id` in that table for historic reasons (mostly because the multinode) and it was removed in 2.7.0 (PR #4294), but unfortunately we didn't reset the `ressortgroupref` of the related target entries when building the materialization view query and this gave the wrong assumption in the `cagg_sort_pushdown` code that we have the right value to set the `tleSortGroupRef` for the related `groupClause` of materialization hypertable range table entry.
So after a dump/restore when Postgres rebuild the views we got the `ressortgroupref` for the materialization target entries leading to an error:
```
ERROR: ORDER/GROUP BY expression not found in targetlist
```
Fixed it by setting the …

Fix CAgg order by pushdown

---

.unreleased/pr_7946
sql/maintenance_utils.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
tsl/src/chunk.c
tsl/src/chunk.h
tsl/src/init.c
tsl/test/expected/split_chunk.out
tsl/test/isolation/expected/split_chunk_concurrent.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/split_chunk_concurrent.spec
tsl/test/shared/expected/extension.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/split_chunk.sql

A chunk can be split with a new procedure called split_chunk(). In this initial version, a chunk can be split in two given a split point:
```
call split_chunk('chunk_1', split_at => '2025-03-01 00:00');
```
If no split point is given, the chunk is split in two equal size partition ranges. The partitioning dimension/column to split along will be the primary dimension (time). Future updates to split_chunk() can add the ability to split also along other dimensions, e.g., space partitions.
Currently, it is not possible split a compressed chunk, but this will be added in a future update. Note that splitting a chunk takes an AccessExclusive lock on the chunk being split. A ShareUpdateExclusive lock is also taken on the hypertable root to attach new chunk partitions (this is mandated by …

Add support for splitting a chunk

---

.github/workflows/snapshot-abi.yaml

- **Ignore result of bgw_launcher test in snapshot ABI workflow**

Ignore result of bgw_launcher test in snapshot ABI workflow

---

.github/ci_settings.py
src/compat/compat.h

Due to some backports in upstream timescaledb versions compiled against
15.10+, 16.6+ and 17.2+ will not be backwardscompatible with
previous PG versions.

Bump minimum compatible postgres version to 15.10, 16.6, 17.2

---

.github/workflows/issue-handling.yaml

If an issue was labeled, the workflow only checked if a security label was part of the labels of the issue and not what label was used. Instead, only check the labels if an issue is opened. Otherwise, check if the actual security label was used.

Fix security notification

---

.unreleased/pr_8047
tsl/src/nodes/skip_scan/planner.c
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out
tsl/test/expected/skip_scan.out
tsl/test/sql/include/skip_scan_comp_query.sql
tsl/test/sql/include/skip_scan_query.sql

Fixes #7998
We should be able to use SkipScan for queries like this if we have index on dev as only dev is a proper distinct column in below queries:
SELECT DISTINCT dev, time FROM :TABLE WHERE time = 100;
SELECT DISTINCT dev, time, val FROM :TABLE WHERE time = 100 and val = 100;
SELECT DISTINCT ON (dev, time) dev, time FROM :TABLE WHERE time = 100 ORDER BY dev, time;
There is no PG support to reliably recognize that only 1 distinct aggregate is actually aggregating here, so this scenario is out of scope:
SELECT count(DISTINCT dev), count(DISTINCT val) from :TABLE WHERE val = 100;

Enable SkipScan for multi-distincts with all but one pinned

---

.unreleased/pr_7992
sql/cagg_api.sql
sql/updates/reverse-dev.sql
tsl/test/expected/cagg_api.out
tsl/test/shared/expected/extension.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_api.sql

The API is intended to be used to read hypertable invalidations for a hypertable that has continuous aggregates. This commit adds two functions: `get_hypertable_invalidations` and
`accept_hypertable_invalidations`.
The function `get_hypertable_invalidations` will get the current invalidations for buckets of a suitable size. It will also return a token that can be used when accepting the invalidations.
The function `accept_hypertable_invalidations` will take a token and remove all invalidations that are associated with that token.

Add API into hypertable invalidation log

---

test/perl/TimescaleNode.pm
tsl/test/t/001_job_crash_log.pl
tsl/test/t/004_truncate_or_delete_spin_lock.pl

Strip whitespace when checking query results in TAP tests

---

.unreleased/pr_8061
src/ts_catalog/compression_settings.c
tsl/src/compression/compression.c

This is just a sanity check, a compressed chunk must always have
corresponding chunk settings. Settings not being present points
to catalog corruption but erroring out in those cases is preferred
over segfault.
Fixes: #8034 

Ensure settings for a compressed rel are found

---

.unreleased/pg_7909
src/ts_catalog/compression_chunk_size.c
src/ts_catalog/compression_chunk_size.h
tsl/src/chunk.c
tsl/test/expected/merge_chunks.out
tsl/test/sql/merge_chunks.sql

Merge compression chunk size stats when merging chunks. The merged chunk's stats is simply the sum of the stats of all compressed chunks that are merged. This ensures that the aggregate stats do not change due to the merge. Still, the stats might not accurately represent the merged chunk since merging both compressed and non-compressed chunks will leave some data uncompressed and this data won't be reflected in the stats of the merged chunk.

Update compression stats when merging chunks

---

sql/pre_install/types.functions.sql
sql/updates/latest-dev.sql

Match the underlying byteain/out behavior, otherwise it segfaults on null input.
Found by SQLSmith: https://github.com/timescale/timescaledb/actions/runs/14880839518/job/41788386799

Declare bloom1 inout functions as strict

---

test/expected/bgw_launcher.out
test/sql/bgw_launcher.sql

https://github.com/timescale/timescaledb/actions/runs/14697618683/job/41241584618

Fix flaky bgw_launcher regression test

---

.github/workflows/code_style.yaml
.unreleased/pr_8074
tsl/src/compression/compression.c
tsl/test/expected/decompress_memory.out
tsl/test/sql/decompress_memory.sql

row_compressor_flush was called without switching to per-row memory context causing memory leaks in the ExprContext memory context. This in turn would cause problems with recompression when there were a lot of small batches.

Use correct memory context during flush

---

tsl/test/expected/compression_qualpushdown.out
tsl/test/sql/compression_qualpushdown.sql

Add VACUUM FULL ANALYZE after compression to have the predictable statistics.

Stabilize the compression_qualpushdown test

---

.github/workflows/pr-validation.yaml

They will disappear after rebasing. This allows us to update the PR to the current main branch and then "rebase and merge" from the GitHub interface only w/o additional manual work.

Exclude merge commits from total count for PR validation

---

src/guc.c
tsl/test/expected/feature_flags.out

In `ts_feature_flag_check` make changes to match current Timescale Cloud service offerings:
- change Dynamic PostgreSQL service to PostgreSQL service
- change Time-series service to Time-series and analytics service
- change the link to one that works

Remove reference to Dynamic PostgreSQL

---

.unreleased/pr_8099
tsl/src/chunk.c
tsl/test/expected/merge_chunks.out
tsl/test/sql/merge_chunks.sql

A limitation in the tuple routing cache can lead to insert  routing errors  if multi-dimensional time partitions are non-aligned (i.e., two partitions have overlapping time ranges).
Such overlapping time partitions can be created when merging chunks in multi-dimensional tables. Therefore, this change blocks such merges by default. However, since merge_chunks() already supports multi-dimensional hypertables, including tests, we use an "anonymous" settings variable to allow multi-dimensional merges.
Related issue: https://github.com/timescale/timescaledb/issues/8025

Block chunk merging on multi-dimensional hypertables

---

.unreleased/pr_8067
tsl/src/hypercore/hypercore_handler.c
tsl/test/expected/hypercore_vacuum.out
tsl/test/sql/hypercore_vacuum.sql

If the Hypertable root/parent table is using Hypercore TAM, it needs to be vacuumed in order to advance relfrozenxid. Otherwise, it might lead to wrap-around issues.

Make sure Hypercore TAM parent is vacuumed

---

src/adts/vec.h
tsl/test/expected/compression.out
tsl/test/sql/compression.sql

Our custom vector type had an issue with detecting allocation overflowing by using the wrong limit.
This change uses MaxAllocSize to limit the allocation and tries to resize to it if the realloc size can
fit into it.

Fix allocation overflow error on vec type

---

.unreleased/pr_8106
src/process_utility.c
tsl/test/expected/compression_constraints.out
tsl/test/sql/compression_constraints.sql

When trying to add a unique expression index to a compressed
chunk trying to do the constraint check would previously
lead to a segfault. This patch fixes the segfault and properly
checks the constraint.

Fix handling of unique expression indexes in constraint check

---

tsl/test/expected/cagg_api.out
tsl/test/sql/cagg_api.sql

The flaky case involved duplicate entries in https://github.com/timescale/timescaledb/actions/runs/14895676126/job/41837637831 but this should not be possible unless two triggers are by mistake added to the tables.
Duplicate entries to the invalidation log does not affect correctness since they will be merged when generating invalidation ranges.
This patch tries to avoid failing test by using `DISTINCT` in the select and add a description of the tables to check if there are two triggers added because of a race condition or some other fluke.

Fix flaky cagg_api test

---

.unreleased/pr_8106
src/process_utility.c

Change time_column to partition_column in hint to reflect rename
of the option.

Fix left over reference to time_column WITH option

---

.unreleased/pr_8081
tsl/src/bgw_policy/CMakeLists.txt
tsl/src/bgw_policy/compression_api.c
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/policies_v2.h
tsl/src/bgw_policy/policy_config.c
tsl/src/bgw_policy/policy_config.h
tsl/src/bgw_policy/reorder_api.c
tsl/src/bgw_policy/reorder_api.h
tsl/src/bgw_policy/retention_api.c
tsl/src/bgw_policy/retention_api.h

Function to read common fields in policy configurations are duplicated, so they are combined into a single module. Using more useful error codes as well instead of "internal error".

Refactor to combine policy config code

---

README.md

It has been pointed out that installation steps in the readme and in the docs use different Docker images. The docs use `-ha` image as the recommended full experience, while the readme uses the non-ha one. We might want to align unless for some specific reason the installation procedure in the readme needs to be a more light-weight one. 

Update docker image in installation

---

tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/continuous_aggs/refresh.c

We have two separate invalidation states for the two different phases of the continuous aggregate invalidation, so this commit split the invalidation state into two different states to make it clear what belongs to which phase. This is a precursor to separating the two phases completely and allowing them to run independently.

Split continuous aggregate invalidation state

---

.github/workflows/linux-32bit-build-and-test.yaml
.unreleased/pr_8115
src/guc.c
src/guc.h
tsl/src/compression/algorithms/array.c
tsl/src/compression/algorithms/array.h
tsl/src/compression/algorithms/bool_compress.c
tsl/src/compression/algorithms/deltadelta.c
tsl/src/compression/algorithms/dictionary.c
tsl/src/compression/algorithms/gorilla.c
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/test/expected/compression.out
tsl/test/expected/compression_allocation.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/compression.sql
tsl/test/sql/compression_allocation.sql

For dictionary and array compression algorithms, you could potentially hit allocation limits if you try to compress too much data in a single column. Usually we limit batches based on number of rows but with this feature, we can limit them based on the size as well.

Add batch size limiting during compression

---

scripts/backport.py

This avoids getting stuck on a single error.
Verified: https://github.com/timescale/timescaledb/actions/runs/14971334814

Randomize the PR order in backport script

---

.unreleased/pr_8127
tsl/src/hypercore/arrow_array.c
tsl/test/expected/hypercore_types.out
tsl/test/sql/hypercore_types.sql

In 695f66fc3e7bb9d548169f3f9c6902ca4166187a bit-packed representation of booleans was introduced, so when reading booleans we should not read it as fixed-length data. Instead we read it as a bit-packed version when populating the values for the Arrow TTS.

Read bit-packed version of booleans

---

CMakeLists.txt
cmake/GenerateScripts.cmake
version.config

Since we now have a released version with the new version.config
entries we can drop downgrade_to_version since it should always
match previous_version.

Remove obsolete downgrade_to_version entry

---

.github/workflows/apt-packages.yaml
.github/workflows/rpm-packages.yaml

version.config has been cleaned up and has `previous_version` entry
for the target of the downgrade, so use that instead.

Fix RPM and APT downgrade test

---

.unreleased/pr_8126
src/guc.c
tsl/test/expected/bgw_scheduler_control.out
tsl/test/sql/bgw_scheduler_control.sql

In order to exclude LOG level events, it is necessary to be able to set the `bgw_log_level` to `FATAL` as well.

Allow setting bgw_log_level to FATAL and ERROR

---

.unreleased/sort-transform-join
src/sort_transform.c
tsl/test/expected/compress_sort_transform.out
tsl/test/sql/compress_sort_transform.sql

We ended up with the transformation applying the original pathkey from a different table, after successfully transforming to a join equivalence class that contains both tables. Add a check for that.
Fixes: https://github.com/timescale/timescaledb/issues/7292

Fix sorting transformation with joins

---

.unreleased/pr_8141
sql/cagg_api.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
src/init.c
src/process_utility.c
src/process_utility.h
src/utils.h
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/invalidation.h
tsl/src/init.c
tsl/test/expected/cagg_invalidation.out
tsl/test/shared/expected/extension.out
tsl/test/sql/cagg_invalidation.sql

Continuous aggregate invalidation moves hypertable invalidations to
materialization invalidations as part of refreshing a continuous
aggregate, but it is not possible to move hypertable invalidations
without refreshing a continuous aggregate.
This commit adds a function to process hypertable invalidations by
moving them from the hypertable invalidation log to the materialization
invalidation logs for all attached continuous aggregates.

Add function to process hypertable invalidations

---

.unreleased/pr_8145
tsl/src/compression/api.c

No need for logging at DEBUG1 level. Only
log if the feature is enabled and compression
ratio is under the threshold.

Log only if compression ratio warnings enabled

---

.github/workflows/code_style.yaml
.github/workflows/label-released-prs.yaml
scripts/label-released.py

The labels are "released-...": https://github.com/timescale/timescaledb/labels?q=released This makes it easier to understand which release has a feature or a fix, especially for the backported fixes.
Run this script for each new published release.
Tested manually and here: https://github.com/timescale/timescaledb/actions/workflows/label-released-prs.yaml

Label all PRs in a given release accordingly on GitHub

---

tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c
tsl/src/compression/recompress.c
tsl/src/hypercore/hypercore_handler.c

This is a multi-commit PR:
Clean up RowCompressor and RowDecompressor
Remove unnecessary fields in the RowCompressor and RowDecompressor
structs. Some of these fields were unused or duplicated information
that could be retrieved by other means.
Break out write state from RowDecompressor
The RowDecompressor expects two relations: one reading compressed data
and one where decompressed data is written. However, some
(de)compression don't follow this pattern; for example, in case of
splitting a chunk it is necessary to split compressed segments into
multiple new segments and write back compressed to the new compressed
relations. Another is memory decompression, which has no output
relation.
To better support such use cases, move the relations and write state
out of the RowDecompressor and …

Refactor compressor and decompressor

---

tsl/test/expected/compress_bloom_sparse_debug.out
tsl/test/sql/compress_bloom_sparse_debug.sql

The bloom filter test used an incorrect constant, so a query was returning null result.

Fix a minor error in test

---

.unreleased/pr_8162
src/with_clause/alter_table_with_clause.c
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/sql/cagg_ddl.sql.in

This also syncs option names with other WITH clauses and adds some
test to verify it can be set.
Fixes #8158

Fix setting compress_chunk_interval on continuous aggregates

---

.unreleased/pr_8163
tsl/src/nodes/gapfill/gapfill_exec.c
tsl/src/nodes/gapfill/gapfill_internal.h
tsl/src/nodes/gapfill/interpolate.c
tsl/src/nodes/gapfill/locf.c
tsl/src/nodes/gapfill/locf.h
tsl/test/shared/expected/gapfill_bug.out
tsl/test/shared/sql/CMakeLists.txt
tsl/test/shared/sql/gapfill_bug.sql

Fixes #6078
Calculate `locf` for missing NULLs on the correct tuple slot.

Fix gapfill crash with locf NULL values treated as missing

---

.unreleased/pr_8151
tsl/src/continuous_aggs/materialize.c
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/cagg_refresh_using_merge.sql

When using the merge strategy to refresh a cagg, the DELETE would remove *any* row that had a `null` in any of the group by columns.
By using NULL IS NOT DISTINCT FROM NULL, we should no longer be deleting these rows.

Treat null equal to null for merged CAgg refresh

---

.github/workflows/catalog-updates-check.yaml
.github/workflows/coccinelle.yaml
.github/workflows/code_style.yaml
.github/workflows/libfuzzer.yaml
.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/linux-build-and-test.yaml
.github/workflows/memory-tests.yaml
.github/workflows/pg_ladybug.yaml
.github/workflows/pg_upgrade-test.yaml
.github/workflows/pgspot.yaml
.github/workflows/sanitizer-build-and-test.yaml
.github/workflows/shellcheck.yaml
.github/workflows/snapshot-abi.yaml
.github/workflows/sqlsmith.yaml
.github/workflows/update-test.yaml
.github/workflows/windows-build-and-test.yaml

These branches are not very active, so this would give up-to-date results w/o too much CI load.
(cherry picked from commit 9b12dbbd5817030a1bb292e6975d93ceff3e6920)
(manual backport of #8090)

Run most prerelease tests on each commit in release branches (#8090)

---

scripts/test_update_from_version.sh

Compression ratio warnings produce a lot of output making it harder
to follow what is happening in update/downgrade scripts.

Disable compression ratio warnings in update and downgrade scripts

---

.unreleased/pr_8126
.unreleased/pr_8145
.unreleased/pr_8151
.unreleased/pr_8153
.unreleased/pr_8162
.unreleased/pr_8163
.unreleased/pr_8171
.unreleased/sort-transform-join
CHANGELOG.md

This release contains performance improvements and bug fixes since the 2.20.0 release. We recommend that you upgrade at the next available opportunity.
**Features**
* [#8145](https://github.com/timescale/timescaledb/pull/8145) Log only if compression ratio warnings are enabled
**Bugfixes**
* [#7292](https://github.com/timescale/timescaledb/pull/7292) Intermittent "could not find pathkey item to sort" error when grouping or ordering by a time_bucket of an equality join variable.
* [#8126](https://github.com/timescale/timescaledb/pull/8126) Allow setting bgw_log_level to `FATAL` and `ERROR`
* [#8151](https://github.com/timescale/timescaledb/pull/8151) Treat `null` equal to `null` for merged Continous Aggregate refresh
* [#8153](https://github.com/timescale/timescaledb/pull/8153) Restoring a …

CHANGELOG 2.20.1

---

tsl/src/chunk.c

It is now possible to merge compressed chunks, but a comment in the code was not updated to reflect that.

Update outdated comment about compressed merge_chunks()

---

README.md

Reworked the README to reflect the syntax changes introduced with the 2.20 release.

Adjust README to new CREATE TABLE syntax

---

src/cross_module_fn.c
test/expected/license.out

Swap the generic timescale.com link out with direct link to our
license comparison page.

Change documentation link on license errors

---

src/chunk.c
tsl/src/compression/api.c

This code is reserved for internal program errors, i.e. bugs. This commit fixes only some of these existing files with incorrect codes, we have more files
Note: This PR has modified different files from #8188

Do not use ERRCODE_INTERNAL_ERROR for user errors

---

.unreleased/pr_8196
src/process_utility.c
tsl/test/expected/hypercore.out
tsl/test/expected/hypercore_copy.out
tsl/test/expected/hypercore_create.out
tsl/test/expected/hypercore_insert.out
tsl/test/expected/hypercore_trigger.out
tsl/test/expected/hypercore_vacuum.out

The hypercore access method is being deprecated and will be removed
in a future release. This patch adds a warning when enabling the
access method.

Show deprecation warning when using hypercore access method

---

.unreleased/pr_8200
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c
tsl/test/expected/compression_insert.out
tsl/test/sql/compression_insert.sql

NULL compression algorithm does not implement
vectorized decompression so we have to handle it
as a special case (similar to default values).

Fix handling NULL compression in DML checks

---

src/copy.c
test/expected/copy.out

Define our own CopyInsertMethod instead of inheriting from postgres.
This patch does not add any new methods but is preparation for a
followup patch that will add a method for compressed insert during
copy.

Don't inherit copy methods from postgres

---

.unreleased/pr_8200
CHANGELOG.md
sql/CMakeLists.txt
version.config

This release contains bug fixes since the 2.20.1 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* [#8200](https://github.com/timescale/timescaledb/pull/8202) Fix `NULL` compression handling for vectorized constraint checking

Release 2.20.2

---

src/cross_module_fn.c
src/cross_module_fn.h
src/nodes/chunk_dispatch/chunk_dispatch.c
tsl/src/compression/compression.h
tsl/src/compression/compression_dml.c

Small refactor to ts_chunk_dispatch_decompress_batches_for_insert
to not have duplicated license check and to have early exit when
no unique constraints are present since we never have to decompress
when no unique constraints are present.

Use generic license check from cross module instead of duplicated version

---

.unreleased/pr_8208
tsl/src/compression/algorithms/bool_compress.c
tsl/test/expected/decompress_vector_qual.out
tsl/test/sql/decompress_vector_qual.sql
tsl/test/src/compression_unit_test.c

Bool compression stored a compressed block even when all values were NULLs unlike othr compression methods thus wasting storage space. This is now changed and it does the same as others.
I added tests to verify this and also made sure that NULL compressed blocks will participate in vectorised filtering.

Make sure BOOL compression uses NULL compression for all NULL values

---

tsl/test/expected/merge_append_partially_compressed.out
tsl/test/sql/merge_append_partially_compressed.sql

Was disabled due to a bug that is now fixed.

Reenable a test in merge_append_partially_compressed

---

.unreleased/pr_8216
tsl/src/nodes/skip_scan/planner.c
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out
tsl/test/expected/skip_scan.out
tsl/test/sql/include/skip_scan_query.sql

Fixes: #8217
Also fixes failed Sanitizer runs div by NULL issue which appeared after commit for https://github.com/timescale/timescaledb/pull/8210: https://github.com/timescale/timescaledb/actions/runs/15419915713/job/43391984943

Fix dropped quals bug in skipscan

---

tsl/src/continuous_aggs/invalidation_threshold.c

It is not necessary to use a RowExclusiveLock when reading the continuous aggregate threshold and a RowShareLock is sufficient.

Use RowShareLock when reading CAgg threshold

---

.unreleased/pr_8187
tsl/src/continuous_aggs/common.h
tsl/src/continuous_aggs/invalidation.c
tsl/src/continuous_aggs/refresh.c
tsl/test/isolation/expected/cagg_concurrent_refresh.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/cagg_concurrent_refresh.spec

Historically we lock the materialization hypertable during the CAgg refresh to prevent concurrent executions. From tsl/src/continuous_aggs/refresh.c:
```C
/* Lock the continuous aggregate's materialized hypertable to protect
* against concurrent refreshes. Only concurrent reads will be
* allowed. This is a heavy lock that serializes all refreshes on the same
* continuous aggregate. We might want to consider relaxing this in the
* future, e.g., we'd like to at least allow concurrent refreshes on the
* same continuous aggregate when they don't have overlapping refresh
* windows.
*/
LockRelationOid(hyper_relid, ExclusiveLock);
```
This PR relax this strong lock on the materialization hypertable by locking the rows from the CAgg invalidation logs doing skip lock to allow concurrent refreshes.

Allow concurrent CAgg refreshes

---

src/copy.c
src/hypertable.c
src/hypertable.h
test/expected/copy.out
test/sql/copy.sql

Only do the constraint check in COPY when non-partitioning constraints
are present since partitioning constraints are satisfied by tuple
routing selecting the right target chunk or creating it.
This was showing up as 5-10% cpu spent in flamegraph for compressed
COPY.

Optimize constraint check for COPY

---

.unreleased/pr_8230
tsl/src/compression/compression_dml.c
tsl/src/nodes/decompress_chunk/vector_predicates.c
tsl/src/nodes/decompress_chunk/vector_predicates.h
tsl/test/expected/compression_insert.out
tsl/test/sql/compression_insert.sql

The lack of vectorised 'booleq' function caused crashes when a composite unique key has a boolean column. This change adds vectorisation for 'booleq' and also makes the vectorisation check more robust, so the lack of a vectorised test doesn't cause a crash.
(cherry picked from commit 6c7619ce3041ae73d38c2a1444ae62e240e018fa)

Fix vectorised check when inserting into compressed column

---

.unreleased/pr_8236
src/bgw/job.c
src/bgw/scheduler.c
test/src/bgw/log.c
tsl/src/hypercore/hypercore_handler.c

Upstream commit fe8ea7a2a introduced additional assertions to
ensure there is always a valid snapshot present when updating
catalog. These were triggered by our background worker code
leading to failing ci runs against postgres pre release branches.
https://github.com/postgres/postgres/commit/fe8ea7a2a89342ecc36a054b2f328c4d8e56f9ae

Fix snapshot handling in background worker

---

tsl/test/isolation/expected/compressed_copy.out
tsl/test/isolation/specs/compressed_copy.spec

MacOS date parameters are not compatible with linux date. Change
the isolation test to not use date since we dont need to generate
consecutive values for this test.

Adjust compressed_copy isolation test to work on Mac

---

.unreleased/pr_8191
sql/ddl_api.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job.h
tsl/src/bgw_policy/policies_v2.h
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_policy_move.out
tsl/test/shared/expected/extension.out
tsl/test/sql/cagg_policy_move.sql

Add option to `refresh_continuous_aggregate` and refresh policy to skip processing the hypertable invalidations when refreshing.
If option `process_hypertable_invalidations` is set to `false`, hypertable invalidations will not be processed as part of a refresh. If option is set to true or does not exist, hypertable invalidations will be processed.

Add option to not process hypertable invalidations

---

.github/workflows/stalebot.yaml

Disable options that require issues:
1. To _not_ be assigned to someone. Often people forget to unassign themselves and such issues were excluded. Since issues are marked stale 30 days before being closed, any people assigned will be notified and can prevent close.
2. To have certain labels, "bug", "enhancement". This meant that any issues that don't have one of the labels won't be closed. This meant that, e.g., a 'bug' that was determined not to be a bug would not be closed by the bot. In fact, issues that are neither bugs nor enhancements should probably be closed even more aggressively.
Also update the stale action to v9 and add a close label so that we can easily find issues closed by the bot.

Make stale bot more aggressive

---

tsl/src/continuous_aggs/insert.c
tsl/test/expected/cagg_errors.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_errors.sql

In #8244 we fixed a segfault in the CAgg invalidation trigger cache when trying to get an open dimension from a hypertable that don't have dimension. In a normal flow this will never happen so the tests added making a manual metadata corruption don't make sense and are hard to maintain. So removed the regression tests and used the Ensure instead of ereport to error out on release builds.
This partially reverts commit 6cb41f42f5663086196eaa85ab03bc231eb42668.

Simplify the check for valid open dimension

---

.github/workflows/windows-packages.yaml

This updates the runner to windows-2022 since windows-2019 will be fully unsupported June 30.
See https://github.com/actions/runner-images/issues/12045

Update Windows runner to 2022

---

src/nodes/chunk_dispatch/chunk_dispatch.c
src/planner/planner.c

Move the check for INSERT into compressed hypertable into planner
to error out earlier and not have to the check be part of tuple routing.

Move check for INSERT into compressed internal hypertable

---

tsl/test/expected/bgw_custom.out
tsl/test/expected/bgw_job_stat_history.out
tsl/test/expected/bgw_job_stat_history_errors.out
tsl/test/sql/bgw_custom.sql
tsl/test/sql/bgw_job_stat_history.sql
tsl/test/sql/bgw_job_stat_history_errors.sql

Restart bgw after schedule changes so changes get applied immediately
this leads to over a minute saved for every CI run.

Speed up bgw test runs

---

tsl/src/compression/compression_dml.c

This was found by coverity as dead code but is actually a copy/paste
error from code a couple lines above.

Fix typo when checking function result

---

.github/workflows/release_post_release_ceremony.yaml
scripts/release/build_post_release_artefacts.sh

This PR adds an action that runs after a release is published to handle the bulk of the post-release tasks. Example: https://github.com/timescale/timescaledb/pull/8206
A script is executed, which:
* sets the new `previous_version` in version.config
* get the updated CHANGELOG.md
* get the up & down grade SQL files
* set the up & down grade files in CMakeList.txt
What is **not** covered:
* bumping the `version` to the next minor in version.config
* removing the delta of deleted .unreleased files
AND added a missing downgrade file

Post release actions

---

.github/workflows/coverity.yaml

Make coverity run on tuesday and saturday instead of only saturday.
Have coverity be trigger by trigger/coverity similar to other
workflows and have it be triggered by changes to the workflow file.

Adjust coverity schedule

---

tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/compression/recompress.c
tsl/src/hypercore/hypercore_handler.c

Use a while loop instead of for loop so we don't have to repeat
tuplesort_gettupleslot call and remove redundant TupleDesc argument.

Small refactor for row_compressor_append_sorted_rows

---

.unreleased/pr_8307
sql/pre_install/insert_data.sql
sql/updates/latest-dev.sql

When we added bool and null compression we did not add them to the
pre_install script but only to the update scripts so any fresh
installation would miss them and updated timescaledb versions
would get them.

Fix missing compression algorithms in pre_install script

---

.github/workflows/nightly_cloud_smoke_test.yaml
.github/workflows/release_feature_freeze_ceremony.yaml
.github/workflows/trigger-package-tests.yaml
scripts/test_update_smoke.sh

- run the update smoke tests with the last 10 tags and minor changes in the script
- example: https://github.com/timescale/timescaledb/actions/runs/15918772622
- a cosmetic change in the package tests
- create only the release branch if does not exist in the feature freeze action to reuse it for patch releases

CI & testing improvements

---

.github/workflows/abi.yaml
.github/workflows/snapshot-abi.yaml

The matrix was referencing an `ignores` variable, but none where defined, so adding it.

Add tests to ignore when running ABI tests

---

.unreleased/pr_8323
tsl/src/compression/compression_dml.c
tsl/test/expected/compression_update_delete-15.out
tsl/test/expected/compression_update_delete-16.out
tsl/test/expected/compression_update_delete-17.out
tsl/test/sql/compression_update_delete.sql.in

Running a rescan in certain scenarios on a bitmap
heap scan node would cause segfaults due to zero
value parametrization on toastable types. This
change avoids the rescan and only rescans the
underlying table scan. This workaround should
be completely removed once we drop PG16 support
since the underlying scan is no longer initialized with 
the node initalization in PG17.

Fix DML issue with expression indexes and BHS

---

.unreleased/pr_8274
src/time_utils.c
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/src/bgw_policy/continuous_aggregate_api.h
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job_api.c
tsl/src/continuous_aggs/create.c
tsl/src/continuous_aggs/refresh.c
tsl/src/continuous_aggs/refresh.h
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_policy.out
tsl/test/expected/cagg_policy_concurrent.out
tsl/test/sql/CMakeLists.txt
tsl/test/sql/cagg_policy.sql
tsl/test/sql/cagg_policy_concurrent.sql

Historically, we only allow creating a single refresh policy on each continuous aggregate.
This PR removes this restriction. We now support creating concurrent CAgg refresh policies, with the restriction that there is no overlap between their refresh intervals.
Along with https://github.com/timescale/timescaledb/pull/8187, this allows refresh policies to run concurrently.

Allow creating concurrent CAgg refresh policies

---

src/chunk.c
tsl/src/compression/compression_storage.c
tsl/src/continuous_aggs/create.c

PG18 changes transformRelOptions signature to have validnsps argument be
const.
https://github.com/postgres/postgres/commit/1e35951e

Adjust HEAP_RELOPT_NAMESPACES variable definition

---

src/bgw/job.c

Replace removed isBackgroundWorker field with \!isRegularBackend check
for PostgreSQL 18 compatibility. This maintains the same logic for
identifying background worker processes in job lock detection.
https://github.com/postgres/postgres/commit/508a97ee (Replace PGPROC.isBackgroundWorker with isRegularBackend)

Fix isBackgroundWorker compatibility for PG18

---

src/process_utility.c

Update cluster_rel call to use new signature that expects a Relation
parameter instead of OID in PostgreSQL 18. Opens relation with
AccessExclusiveLock before calling cluster_rel to match upstream
API changes.
https://github.com/postgres/postgres/commit/cc811f92 Adjust signature of cluster_rel() and its subroutines

Fix cluster_rel signature for PG18

---

src/foreign_key.c

PG18 added isEnforced and conPeriod parameters
to CreateConstraintEntry. Add version guards for the new
parameters to maintain compatibility.
https://github.com/postgres/postgres/commit/fc0438b4 Add temporal PRIMARY KEY and UNIQUE constraints
https://github.com/postgres/postgres/commit/ca87c415 Add support for NOT ENFORCED in CHECK constraints

Fix CreateConstraintEntry signature for PG18

---

src/compat/compat.h
src/time_utils.c
tsl/src/bgw_policy/continuous_aggregate_api.c

Adds `make_range_compat` to make the code cleaner, since we now use it in a few places.

Refactor `make_range` into compat function

---

.github/workflows/nightly_cloud_smoke_test.yaml
.github/workflows/release_post_release_ceremony.yaml

- the nightly QA action did not pull the latest release branch, when there was no tag for it yet. Hence, this would only be active after the first tag on that release branch. This was fixed now and run through on a fork, [result](https://github.com/philkra/timescaledb/actions/runs/16069603868)
- add automation to create a follow-up PR on the release branch to bump the patch versions immediately

Improved pre & post release actions

---

test/sql/updates/cleanup.chunk_skipping.sql

The update test for chunk skipping which is run during smoke test had a table renamed, but the cleanup script still has the old table name.

Fix chunk skipping cleanup in smoke test

---

src/chunk.c
src/chunk_constraint.c
src/chunk_tuple_routing.c
src/dimension.c
src/jsonb_utils.c
src/nodes/chunk_dispatch/chunk_dispatch.c
src/ts_catalog/chunk_column_stats.c
src/utils.c
src/utils.h
src/with_clause/with_clause_parser.c
tsl/src/bgw_policy/job.c
tsl/src/bgw_policy/job.h
tsl/src/chunk.c
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/refresh.c

Often we need to get the output string representation of a given value for certain Postgres type doing something like this:
```C
bool isvarlena;
Oid outfuncid;
getTypeOutputInfo(type, &outfuncid, &isvarlena);
Assert(OidIsValid(outfuncid));
valstr = OidOutputFunctionCall(outfuncid, datum);
```
So encapsulated this pattern into a new accessor function `ts_datum_to_string` and also use the `ts_internal_to_time_string` when necessary instead of repeat a lot of code.

Refactor string output for Postgres type code

---

tsl/src/continuous_aggs/invalidation.c
tsl/test/expected/cagg_refresh.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/include/cagg_refresh_common.sql

When using `force=true` CAgg refresh option we need to invalidate the entire refresh range but we forgot to properly cut the invalidation because we only refresh full buckets and this was leading to different buckets being materialized when forcing the refresh.
Fixed it by properly cutting the invalidation to only include full buckets in the refresh.

Fix forced CAgg refresh

---

tsl/test/sql/CMakeLists.txt

When creating a logical replication slot with a lot of concurrent transactions, `pg_create_logical_replication_slot` can fail with a memory allocation error inside `LogicalDecodingProcessRecord` because it tries to allocate too much memory.
To avoid this, we make the test a solo test for now.

Fix flaky cagg_plugin

---

tsl/src/continuous_aggs/invalidation.c
tsl/test/expected/cagg_refresh.out
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/include/cagg_refresh_common.sql

Backport to branch 2.21.x
Original message
----
When using `force=true` CAgg refresh option we need to invalidate the entire refresh range but we forgot to properly cut the invalidation because we only refresh full buckets and this was leading to different buckets being materialized when forcing the refresh.
Fixed it by properly cutting the invalidation to only include full buckets in the refresh.

Backport to 2.21.x: Fix forced CAgg refresh

---

.github/workflows/update-test.yaml
scripts/test_updates.sh

When the update test does not fail due to diffing the instances
but during the ALTER EXTENSION itself you had to look into the
generated log artefacts to get to the bottom of the failure.
This PR adds this information to the normal workflow output.

Improve update test error information

---

.unreleased/pr_8371
src/with_clause/with_clause_parser.c
test/expected/alter.out
test/expected/create_table_with.out
test/sql/alter.sql
test/sql/create_table_with.sql
tsl/test/expected/cagg_errors.out

Currently we just return `unrecognized parameter "tsdb.foo"` when
encountering unrecognized options in ALTER TABLE. This change
lists all available options in these situations.
ALTER table t1 SET (tsdb.foo=bar);
ERROR:  22023: unrecognized parameter "tsdb.foo"
HINT:  Valid timescaledb parameters are: chunk_interval, compress, compress_segmentby, compress_orderby, compress_chunk_interval

Show available timescaledb ALTER options when encountering unsupported options

---

.github/workflows/pgspot.yaml

Using CREATE OR REPLACE FUNCTION is not a problem when used in an
extension context because upstream changed the code to require
the function is owned by the extension if it is preexisting so
it cannot be shadowed by user controlled functions.

Make pgspot no longer complain about CREATE OR REPLACE FUNCTION

---

src/process_utility.c
test/expected/create_table_with.out
tsl/test/expected/create_table_with.out

The error message when you omitted `tsdb.partition_column` used to mention `time_column`, which makes it seem like the name of the option.
Changed to:
ERROR: hypertable option requires a timestamp or integer partitioning column",
HINT: Use "timescaledb.partition_column" to specify the column to use as partitioning column.

Fix CREATE WITH (timescaledb.hypertable) error

---

tsl/src/chunk_merge.c

Inside `copy_table_data` the table access method is extracted and written back, however, it is always NULL so Coverity warns that this variable never changes value.

Remove update of table access method

---

test/expected/loader-oss.out
test/expected/loader-tsl.out
test/sql/loader.sql.in
test/sql/utils/testsupport.sql
tsl/test/expected/telemetry_stats.out

PG18 changes \dx to include the default version making \dx output
differ between pg versions. Change the tests using \dx to use the
pg17 \dx query. We dont want to include the default version as
this would have to be changed whenever we bump version and would
also require adjusting in release branches.

Don't use \dx in tests

---

.github/gh_matrix_builder.py
.github/workflows/linux-32bit-build-and-test.yaml
.github/workflows/windows-build-and-test.yaml
test/sql/CMakeLists.txt
test/src/net/test_conn.c

Switch out postman-echo.com test endpoint for httpbin.org

Fix net test

---

.github/workflows/release_post_release_ceremony.yaml

The docs are featuring the GUCs from timescaledb: https://docs.tigerdata.com/api/latest/configuration/gucs/
These are generated by [an action](https://github.com/timescale/docs/actions/workflows/tsdb-refresh-gucs-list.yaml) in the docs repo, after a release, this action is called to run.

Trigger docs action after release

---

.unreleased/pr_8393
sql/pre_install/insert_data.sql
sql/updates/latest-dev.sql
sql/updates/reverse-dev.sql
src/cross_module_fn.c
src/cross_module_fn.h
src/guc.c
src/guc.h
src/uuid.h
tsl/src/compression/README.md
tsl/src/compression/algorithms/CMakeLists.txt
tsl/src/compression/algorithms/uuid_compress.c
tsl/src/compression/algorithms/uuid_compress.h
tsl/src/compression/compression.c
tsl/src/compression/compression.h
tsl/src/init.c
tsl/test/expected/compression_algos.out
tsl/test/expected/compression_uuid.out
tsl/test/sql/compression_algos.sql
tsl/test/sql/compression_uuid.sql
tsl/test/sql/include/compression_utils.sql
tsl/test/src/compression_sql_test.c
tsl/test/src/compression_unit_test.c

This change introduces a new compression algorithm to support compressing UUIDs. This is only effective for UUID v7 type where the timestamp part is compressible and the random part is not.
The new compression reverts to dictionary compression if it detects redundant data and it estimates that dictionary compression provides better results. Note that dictionary compression reverts to Array compression if it thinks it results in better compression.
The new feature is controlled by a feature flag, which is turned off for compatibility reasons:
`timescaledb.enable_uuid_compression=off`
This will be shipped as off for one release and then changed to `on` in subsequent releases.
The UUID compression divides the UUID into two parts. The compressible part is compressed with the delta-delta …

Add support for UUID compression

---

.unreleased/pr_8336
CHANGELOG.md

This release contains a bug fix since the 2.21.0 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* [#8336](https://github.com/timescale/timescaledb/pull/8336) Fix generic plans for foreign key checks and prepared statements
**Thanks**
* @CodeTherapist for reporting the issue with foreign key checks not working after several `INSERT` statements

Release 2.21.1 (#8403)

---

.unreleased/pr_8401
src/process_utility.c
src/with_clause/alter_table_with_clause.c
src/with_clause/alter_table_with_clause.h
src/with_clause/with_clause_parser.c
src/with_clause/with_clause_parser.h
tsl/test/expected/compression_errors.out
tsl/test/sql/compression_errors.sql

Allows users to reset compression options like segmentby and orderby
back to their default values using ALTER TABLE RESET. This enables
easier rollback of compression configuration to default behavior
without needing to drop and recreate settings manually.

Support ALTER TABLE RESET for compression settings

---

.github/workflows/label-handling.yaml

Additive action to https://github.com/timescale/timescaledb/pull/8413 to ping if the upgrade requires restart label.

Ping on add of specific labels

---

.github/workflows/loader_check.yml

Follow to enforce a loader version upgrade if the label is `upgrade-requires-restart` is present.

Test for a bumped version on loader change

---

.github/workflows/nightly_cloud_smoke_test.yaml
scripts/test_update_smoke.sh

- disables the warning
- runs the tests if the script is modified

Disable poor compression ratio in nightly tests

---

.github/gh_matrix_builder.py
.unreleased/pr_8426
src/chunk_adaptive.c
src/chunk_adaptive.h
src/ts_catalog/chunk_column_stats.c
tsl/src/compression/api.c
tsl/src/compression/recompress.c
tsl/test/expected/chunk_column_stats.out
tsl/test/sql/chunk_column_stats.sql

When a partially compressed chunk with segmentby column was
recompressed the new min/max range would not be calculated correctly
and only take the new values into account but not already compressed
values.

Fix chunk skipping min/max calculation

---

scripts/backport.py

If the PR description does not have a body, the value of `pr_desc` is `None`, which makes the regex sub fail. E.g.: https://github.com/timescale/timescaledb/actions/runs/16652585974/job/47129046529#step:4:511

Handle None case in backport script

---

tsl/src/compression/algorithms/array.c
tsl/src/compression/algorithms/dictionary.c
tsl/src/compression/algorithms/uuid_compress.c
tsl/test/expected/compression_uuid.out
tsl/test/sql/compression_uuid.sql

Fixing the sanitizer tests that flags up unaligned access that I added in the unit tests to test exactly that.
Fixing the flakyness of the UUID filtering test that filtered timestamps on a table that has v4 (random) data, so the timestamp returned may or may not match the timesptamp filter.

Fix UUID tests

---

.github/workflows/nightly_cloud_smoke_test.yaml
test/sql/updates/post.continuous_aggs.v2.sql

The nightly upgrade tests are flakey due to the following check: https://github.com/timescale/timescaledb/actions/runs/16710897537/job/47295644172#step:4:99
We tried VACCUM, which did not take effect as expected, using sleep now as initially used in https://github.com/timescale/timescaledb/pull/8419

Avoid flakes in materialization check

---

.unreleased/pr_8471
src/nodes/modify_hypertable_exec.c
tsl/test/expected/cagg_refresh_using_merge.out
tsl/test/sql/cagg_refresh_using_merge.sql

There was a problem in ModifyHypertable when using MERGE with
updated values leading to index corruption. This was caused by
some oversight in a refactoring of ModifyHypertable.

Fix MERGE behaviour with updated values

---

.unreleased/pr_8471
CHANGELOG.md
sql/CMakeLists.txt

This release contains performance improvements and bug fixes since the 2.21.2 release. We recommend that you upgrade at the next available opportunity.
**Bugfixes**
* [#8471](https://github.com/timescale/timescaledb/pull/8471) Fix MERGE behaviour with updated values

Release 2.21.3

---

.pull-review

He's getting selected more often on the CI-unrelated PRs than we thought he would be.

Remove Philip from the reviewers list

---

src/guc.c

In debug builds an assertion is raising for new GUCs `timescaledb.cagg_low_work_mem` and `timescaledb.cagg_high_work_mem` when setting the `maintenance_work_mem` to a different value than the default of 65536 and restarting the server.
```
2025-08-19 14:14:34.509 CEST [3220946] LOG:  00000: GUC (PGC_INT) timescaledb.cagg_processing_low_work_mem, boot_val=1257676, C-var=39321
2025-08-19 14:14:34.509 CEST [3220946] LOCATION:  check_GUC_init, guc.c:1462
TRAP: failed Assert("check_GUC_init(variable)"), File: "/home/akuzm/ts1/build-pg/../pg/src/backend/utils/misc/guc.c", Line: 4946, PID: 3220946
```
The problem is when defining the GUC we're doing a calculation based on the `maintenance_work_mem` leading to different value for the GUC and the C-var. Fixed it by using a static value for both. …

Fix assertion with new CAgg GUCs

---

src/compat/compat.h
src/nodes/modify_hypertable_exec.c

In version 18, we got a breaking change in the before row delete and update triggers by adding a new parameter to the function signature. This change has been backported with 17.6 hence we need to keep track of 3 versions of these functions.
https://github.com/postgres/postgres/commit/5022ff25

Add BR delete and update triggers for PG18 compat

---

.unreleased/pr_8496
src/chunk_constraint.c
tsl/test/expected/foreign_keys_test.out
tsl/test/sql/include/foreign_keys.sql

Note I have following make installcheck failure:
```
Built target regresscheck-shared
SKIPS: 
t/001_job_crash_log.pl ................. ok   
t/002_logrepl_decomp_marker.pl ......... ok    
t/003_mvcc_cagg.pl ..................... ok   
t/004_truncate_or_delete_spin_lock.pl .. 4/? 
t/004_truncate_or_delete_spin_lock.pl .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/10 subtests 
t/005_recompression_spin_lock_test.pl .. ok    
Test Summary Report
-------------------
t/004_truncate_or_delete_spin_lock.pl (Wstat: 256 (exited 1) Tests: 10 Failed: 1)
Failed test:  10
Non-zero exit status: 1
Files=5, Tests=45, 13 wallclock secs ( 0.02 usr  0.01 sys +  2.17 cusr  1.47 csys =  3.67 CPU)
Result: FAIL
make[3]: *** [tsl/test/CMakeFiles/provecheck-t.dir/build.make:71: …
```

Fix dropping chunks with foreign keys

---

src/ts_catalog/compression_settings.c

In compression_settings_fill_from_tuple, CompressionSettings was referencing non-toasted varlen fields in the HeapTuple instead of copying them. This caused AddressSanitizer use-after-poison errors when the HeapTuple was freed. Fields are now safely copied.

Fix ASan use-after-poison in CompressionSettings

---

.unreleased/pr_8530
src/process_utility.c
test/expected/create_table_with.out
test/sql/create_table_with.sql

When initially adding CREATE TABLE WITH we would require columnstore
to be disabled when the license did not have compression available.
This patch changes the behaviour to not require explicitly disabling
columnstore when the license is apache.
Fixes: #8422

Don't require columnstore=false when using apache licensed version

---

.unreleased/pr_8528
sql/chunk.sql
sql/updates/reverse-dev.sql
src/chunk.c
src/chunk.h
test/expected/chunk_utils.out
test/sql/chunk_utils.sql
tsl/test/shared/expected/extension.out

Add helper function to decode chunk status bit field into text.
SELECT chunk,
_timescaledb_functions.chunk_status(chunk),
_timescaledb_functions.chunk_status_text(chunk)
FROM show_chunks('metrics') chunk;
chunk                  | chunk_status |  chunk_status_text
----------------------------------------+--------------+----------------------
_timescaledb_internal._hyper_1_1_chunk |            9 | {COMPRESSED,PARTIAL}
(1 row)

Add chunk_status_text helper function

---

.unreleased/pr_8513
src/guc.c
src/guc.h
tsl/src/nodes/skip_scan/exec.c
tsl/src/nodes/skip_scan/planner.c
tsl/src/nodes/skip_scan/skip_scan.h
tsl/test/expected/plan_skip_scan-15.out
tsl/test/expected/plan_skip_scan-16.out
tsl/test/expected/plan_skip_scan-17.out
tsl/test/expected/plan_skip_scan_notnull.out
tsl/test/expected/skip_scan.out
tsl/test/sql/include/skip_scan_multi_load.sql
tsl/test/sql/include/skip_scan_multi_query.sql
tsl/test/sql/include/skip_scan_query.sql
tsl/test/sql/skip_scan.sql

Implement multikey SkipScan when all distinct keys are guaranteed to be not null.
Fixes https://github.com/timescale/timescaledb/issues/3094.
Not-null mode is implemented in https://github.com/timescale/timescaledb/issues/8479.
Added unit tests based on a multikey table.

Implement multikey skipscan in not-null mode

---

.unreleased/pr_8494
sql/job_stat_history_log_retention.sql
sql/updates/reverse-dev.sql
tsl/test/expected/bgw_job_stat_history.out
tsl/test/isolation/expected/bgw_job_stat_history_retention_isolation.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/bgw_job_stat_history_retention_isolation.spec
tsl/test/shared/expected/extension.out
tsl/test/sql/bgw_job_stat_history.sql

Previously a delete query was run on the `bgw_job_stat_history` table to
remove job history. This could be slow once the job history table became
very large. We now use a temporary table to keep recent history and
truncate the job history table instead. We also introduce a
`job_history_bsearch` function which finds the ids of the jobs that need
to be deleted using binary search.
This PR is based on experiments done
previously (https://github.com/timescale/timescaledb-extras/pull/47).

Improve job stat history retention job

---

tsl/src/compression/compression.c
tsl/src/continuous_aggs/common.c
tsl/src/continuous_aggs/finalize.c
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/expected/cagg_ddl-18.out
tsl/test/sql/cagg_ddl.sql.in

With PG18, RTEs are now used for group clauses
which need to be taken into account when looking
for time_bucket during validation and finalization stages of cagg operations.
https://github.com/postgres/postgres/commit/247dea89

Check grouping set RTEs for time_bucket in PG18

---

src/guc.c
tsl/test/expected/cagg_bgw-15.out
tsl/test/expected/cagg_bgw-16.out
tsl/test/expected/cagg_bgw-17.out
tsl/test/expected/cagg_invalidation.out
tsl/test/expected/exp_cagg_monthly.out
tsl/test/sql/cagg_bgw.sql.in
tsl/test/sql/cagg_invalidation.sql
tsl/test/sql/exp_cagg_monthly.sql

In #8508 we removed the merged Continuous Aggregate materialization making the GUC `timescaledb.materializations_per_refresh_window` completely useless so removed it.

Remove Continuous Aggregate GUC

---

src/chunk_adaptive.c
src/chunk_constraint.c
src/process_utility.c
src/scanner.c
src/ts_catalog/continuous_aggs_watermark.c
tsl/src/compression/compression.c
tsl/src/compression/compression_dml.c
tsl/src/compression/recompress.c
tsl/src/continuous_aggs/insert.c
tsl/src/continuous_aggs/invalidation_threshold.c
tsl/src/continuous_aggs/utils.c

Snapshot being used for scans needs to be active
or registered so that its pinned and cannot be
invalidated from under us.
https://github.com/postgres/postgres/commit/8076c005

Use active and registered snapshots only

---

tsl/test/src/compression_unit_test.c

4-byte varlena header cannot be unaligned in Postgres. This fixes a sanitizer failure on main. Couldn't reproduce the failure itself locally though.
https://github.com/timescale/timescaledb/actions/runs/17272826513/job/49021912296#step:15:226

Remove an incorrect UUID unit test

---

tsl/src/continuous_aggs/invalidation_multi.c
tsl/test/isolation/expected/cagg_concurrent_process_wal.out
tsl/test/isolation/specs/CMakeLists.txt
tsl/test/isolation/specs/cagg_concurrent_process_wal.spec

If two sessions using WAL-based invalidation processing starts processing the WAL at the same time, the second one will get an error rather than waiting.
This is solved by adding a database object lock on the materialization table. This will not conflict with relation locks on the same table, but will allow concurrent refresh to serialize on the invalidation processing.

Serialize WAL-based invalidation processing

---

.unreleased/pr_8559
tsl/src/bgw_policy/continuous_aggregate_api.c
tsl/test/expected/cagg_policy.out
tsl/test/sql/cagg_policy.sql.orig

When setting a refresh policy with `end_offset=>NULL` for a CAgg with variable sized bucket it was erroring out when there was o data to be refreshed.
This was happening cause we're using the wrong util function to get the maximum value for the given type. Fixed it using the proper function to handle both the fixed and variable bucket size.
Fixes #6902 

Fix timestamp out of range in CAgg refresh policy

---

.github/workflows/apt-arm-packages.yaml
.github/workflows/apt-packages.yaml
.github/workflows/docker-images.yaml
.github/workflows/homebrew.yaml
.github/workflows/release_build_packages.yml
.github/workflows/rpm-packages.yaml
.github/workflows/windows-packages.yaml

prefixes the packaging workflows with same prefix to have them co-located as it's quite cumbersome to jump up and down between the tests, plus easy to miss one.

Adjust packaging test names

---

src/copy.h
src/nodes/chunk_dispatch/chunk_insert_state.h

This was forgotten in an earlier refactoring

Remove unused ChunkDispatch field from CopyChunkState

---

src/import/planner.c
src/import/planner.h
src/sort_transform.c
src/sort_transform.h
src/utils.c
src/utils.h
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/src/nodes/decompress_chunk/planner.c

PG18 introduced an optimization for more efficient iterating over ec_members which no longer include child EMs. In order to include iterating over child members, specialized iterator was created which needs to be used along with child relids.
https://github.com/postgres/postgres/commit/d69d45a5

Update iterating over ems for PG18

---

.unreleased/pr_8599
src/chunk_constraint.c
tsl/test/expected/chunk_api.out
tsl/test/sql/chunk_api.sql

Operations that creates a new chunk from an existing table (create_chunk() and attach_chunk()) may encounter mismatches in attribute numbers even though names and types match.
Use attnums on chunk instead of hypertable.

Fix attnum mismatch bug in chunk constraint checks

---

src/chunk_tuple_routing.c
src/chunk_tuple_routing.h
src/nodes/chunk_dispatch/chunk_dispatch.c
src/nodes/chunk_dispatch/chunk_dispatch.h
src/nodes/modify_hypertable.c
src/nodes/modify_hypertable.h
src/nodes/modify_hypertable_exec.c

- **Get rid of unused ChunkDispatch fields**
- **Move has_dropped_attrs to ChunkTupleRouting**
- **++**
- **Remove ChunkInsertState from ChunkDispatch**
- **Remove ChunkDispatch from ModifyHypertable**

Remove ChunkDispatch from ModifyHypertable

---

tsl/src/continuous_aggs/refresh.c
tsl/test/isolation/expected/cagg_concurrent_refresh.out
tsl/test/isolation/specs/cagg_concurrent_refresh.spec

In #8515 we made some improvements on Concurrent CAgg Refreshes but an oversight happened keeping the `ExclusiveLock` in the materialization hypertable during the CAgg invalidation logs processing ending up with concurrent refreshes on non-overlaping ranges waiting for each other.
Fixed it by relaxing the `ExclusiveLock` to `ShareUpdateExclusiveLock` since we should only guarantee that the CAgg invalidation logs processing transaction be executed serially but the next transaction (materialization phase) can't be blocked by this or block other concurrent refreshes.

Relax lock when processing CAgg invalidation logs

---

.unreleased/pr_8661
src/process_utility.c
test/expected/ddl.out
test/sql/ddl.sql

Allowing ALTER TABLE ONLY when setting/removing reloptions can
be useful to apply settings changes only to future chunks.

Don't block ALTER TABLE ONLY when setting reloptions

---

.github/gh_matrix_builder.py

Install `pgstattuple` to retrieve tuple-level statistics and `pageinspect` to look into index pages.
(cherry picked from commit af861f3e228d4b8e52bd0cbb863b33968c4d51fa)

Install PG contrib extensions

---

tsl/src/continuous_aggs/planner.c

Track sorting order for caggs in PG18

---

.unreleased/pr_8693
tsl/src/nodes/decompress_chunk/decompress_chunk.c
tsl/test/expected/decompress_index.out
tsl/test/expected/transparent_decompression_join_index.out
tsl/test/sql/decompress_index.sql

Fixes #8681 
Similar to #3720 issue when SkipScan wasn't chosen for distinct varchar column.
In this case SkipScan also cannot be chosen because underlying Columnstore cannot choose IndexScan for compressed index on a varchar segmentby column as it gets coerced into TEXT index key.
The fix includes consistent applying of type coercions.

Fix compressed index not chosen for varchar segmentby column

---

.github/gh_matrix_builder.py

On disk sizes of the resulting chunks are different on macos

Ignore result of compression_bgw test on macos

---

.github/workflows/rpm-packages.yaml

We havent yet published timescaledb-toolkit on rockylinux:9 for
PG17 due to build problems.

Ignore timescaledb-toolkit availability on rockylinux 9 for PG17

---

src/chunk.c
src/chunk.h
src/chunk_scan.c
src/hypertable.c
src/hypertable.h
src/utils.c
src/utils.h
tsl/src/chunk_api.c
tsl/src/chunk_split.c

With the removal of our table access method this was not used by
any code.

Remove amoid from Chunk struct

---

.unreleased/pr_8703
tsl/src/continuous_aggs/common.c
tsl/test/expected/cagg_ddl-15.out
tsl/test/expected/cagg_ddl-16.out
tsl/test/expected/cagg_ddl-17.out
tsl/test/expected/cagg_errors.out
tsl/test/expected/cagg_joins.out
tsl/test/sql/cagg_ddl.sql.in

Remove the blocker for set-returning functions from continuous
aggregate definitions
Fixes #1717

Allow set-returning functions in continuous aggregates

---

.github/workflows/windows-packages.yaml

Chocolatey hasnt updated their postgres versions for half a year
and they are still on 17.4 while 17.6 is current. Since we want
to test against latest we are switching to winget to install
postgres.

Use winget to install postgres in windows package test

---

.unreleased/pr_8734
src/planner/planner.c
src/process_utility.c
tsl/test/expected/chunk_utils_internal.out
tsl/test/expected/compressed_copy.out
tsl/test/sql/chunk_utils_internal.sql
tsl/test/sql/compressed_copy.sql

Previously only COPY targetting hypertable would result in our
custom COPY code being used. COPY targetting chunk directly would
instead use postgres COPY code. This means DML into frozen chunks
would not be prevented and direct compress would not be used.

Use custom COPY code for direct COPY in chunk
